import type { ToolId, TutorialId } from "./path";

export const TOOL_COVER: Record<ToolId, string> = {
  clip: "/covers/clip-sweet.jpg?v=2",
  qr: "/covers/qr-sweet.jpg?v=1",
  barcode: "/covers/barcode-sweet.jpg?v=2",
  watermark: "/covers/watermark-sweet.jpg?v=1",
  collage: "/covers/collage-sweet.jpg?v=1",
  "portrait-sim": "/covers/portrait-sim-sweet.jpg?v=1",
  resize: "/covers/resize-sweet.jpg?v=1",
  crop: "/covers/crop-sweet.jpg?v=1",
  rotate: "/covers/rotate-sweet.jpg?v=1",
  exif: "/covers/exif-sweet.jpg?v=1",
  meme: "/covers/meme-sweet.jpg?v=2",
  signature: "/covers/signature-sweet.jpg?v=2",
  favicon: "/covers/favicon-sweet.jpg?v=1",
  screenshot: "/covers/screenshot-sweet.jpg?v=1",
  convert: "/covers/convert-sweet.jpg?v=1",
  "image-pdf": "/covers/image-pdf-sweet.jpg?v=1",
  "pdf-jpg": "/covers/pdf-jpg-sweet.jpg?v=1",
  "merge-pdf": "/covers/merge-pdf-sweet.jpg?v=1",
  "compress-pdf": "/covers/compress-pdf-sweet.jpg?v=1",
  "split-pdf": "/covers/split-pdf-sweet.jpg?v=1",
  invoice: "/covers/invoice-sweet.jpg?v=2",
  audio: "/covers/audio-sweet.jpg?v=2",
  "audio-cutter": "/covers/audio-cutter-sweet.jpg?v=1",
  "audio-joiner": "/covers/audio-joiner-sweet.jpg?v=1",
  data: "/covers/data-sweet.jpg?v=2",
  "xml-json": "/covers/xml-json-sweet.jpg?v=1",
  "yaml-json": "/covers/yaml-json-sweet.jpg?v=1",
  password: "/covers/password-sweet.jpg?v=1",
  "word-count": "/covers/word-count-sweet.jpg?v=1",
  color: "/covers/color-sweet.jpg?v=1",
  "hex-rgb": "/covers/hex-rgb-sweet.jpg?v=1",
  names: "/covers/names-sweet.jpg?v=1",
  timezone: "/covers/timezone-sweet.jpg?v=2",
  timestamp: "/covers/timestamp-sweet.jpg?v=1",
  lorem: "/covers/lorem-sweet.jpg?v=2",
  units: "/covers/units-sweet.jpg?v=2",
  "text-to-speech": "/covers/text-to-speech-sweet.jpg?v=2",
  diff: "/covers/diff-sweet.jpg?v=1",
  uuid: "/covers/uuid-sweet.jpg?v=1",
  hash: "/covers/hash-sweet.jpg?v=1",
  regex: "/covers/regex-sweet.jpg?v=1",
  case: "/covers/case-sweet.jpg?v=1",
  jwt: "/covers/jwt-sweet.jpg?v=1",
  percent: "/covers/percent-sweet.jpg?v=1",
  random: "/covers/random-sweet.jpg?v=1",
  html: "/covers/html-sweet.jpg?v=1",
  cron: "/covers/cron-sweet.jpg?v=1",
  slug: "/covers/slug-sweet.jpg?v=1",
  age: "/covers/age-sweet.jpg?v=1",
  bmi: "/covers/bmi-sweet.jpg?v=1",
  binary: "/covers/binary-sweet.jpg?v=1",
};

export const LEARN_COVER: Record<TutorialId, string> = {
  "make-qr": "/covers/qr-sweet.jpg?v=1",
  "make-barcode": "/covers/barcode-sweet.jpg?v=2",
  "merge-pdf": "/covers/merge-pdf-sweet.jpg?v=1",
  "compress-pdf": "/covers/compress-pdf-sweet.jpg?v=1",
  "heic-to-jpg": "/covers/convert-sweet.jpg?v=1",
  "jpg-to-pdf": "/covers/image-pdf-sweet.jpg?v=1",
  "pdf-to-jpg": "/covers/pdf-jpg-sweet.jpg?v=1",
  "crop-photo": "/covers/crop-sweet.jpg?v=1",
  portrait: "/covers/tutorials/portrait-frames.svg",
  algorithms: "/covers/tutorials/algorithm-map.svg",
  "phone-photos": "/covers/tutorials/phone-focus.svg",
  "window-light": "/covers/tutorials/window-setup.svg",
  "crop-compose": "/covers/tutorials/crop-ratios.svg",
  "badminton-warmup": "/covers/learn-badminton-warmup-sweet.jpg?v=1",
  "badminton-rules": "/covers/learn-badminton-rules-sweet.jpg?v=1",
  "pool-safety": "/covers/learn-pool-safety-sweet.jpg?v=1",
  "one-page-site": "/covers/tutorials/site-structure.svg",
  "healthy-boundaries": "/covers/learn-healthy-boundaries-sweet.jpg?v=1",
  "read-character": "/covers/learn-read-character-sweet.jpg?v=1",
};

export const LEARN_FIG: Partial<Record<TutorialId, string>> = {
  "phone-photos": "/covers/learn-fig-phone-photos.jpg?v=1",
  "window-light": "/covers/learn-fig-window-light.jpg?v=1",
  "crop-compose": "/covers/learn-fig-crop-compose.jpg?v=1",
};

/** Instructional overview SVG shown at the top of a published lesson. */
export const LEARN_HERO: Partial<Record<TutorialId, string>> = {
  "make-qr": "/covers/tutorials/make-qr.svg",
  "make-barcode": "/covers/tutorials/make-barcode.svg",
  "merge-pdf": "/covers/tutorials/merge-pdf.svg",
  "compress-pdf": "/covers/tutorials/compress-pdf.svg",
  "heic-to-jpg": "/covers/tutorials/heic-to-jpg.svg",
  "jpg-to-pdf": "/covers/tutorials/jpg-to-pdf.svg",
  "pdf-to-jpg": "/covers/tutorials/pdf-to-jpg.svg",
  "crop-photo": "/covers/tutorials/crop-photo.svg",
};

export function coverUrl(path: string): string {
  return `https://cv.cm${path.split("?")[0]}`;
}
