export const GAME_CONSOLES = ["fc", "sfc", "gb", "gbc", "gba", "md", "flash"] as const;
export type GameConsoleId = (typeof GAME_CONSOLES)[number];

export const GAME_GENRES = [
  "platform",
  "action",
  "shooting",
  "rpg",
  "puzzle",
  "fighting",
  "racing",
] as const;
export type GameGenreId = (typeof GAME_GENRES)[number];

export type GameCheat = {
  id: string;
  code: string;
};

export type Game = {
  id: string;
  console: GameConsoleId;
  genre: GameGenreId;
  year: number;
  /** EmulatorJS `EJS_core` id. Flash pages use the Ruffle iframe instead. */
  core: "nes" | "snes" | "gb" | "gbc" | "gba" | "segaMD" | "ruffle";
  accept: string;
  /** Hosted on S3 only when the ROM is freeware / homebrew we may redistribute. */
  rom?: string;
  cheats: readonly GameCheat[];
};

export const GAMES: readonly Game[] = [
  {
    id: "super-mario-bros",
    console: "fc",
    genre: "platform",
    year: 1985,
    core: "nes",
    accept: ".nes,.zip",
    cheats: [
      { id: "lives", code: "SZVVOVAS" },
      { id: "invincible", code: "AVSUZSVZ" },
      { id: "moon", code: "AEKPTZGP" },
      { id: "fire", code: "APZLUGLA" },
    ],
  },
  {
    id: "contra",
    console: "fc",
    genre: "shooting",
    year: 1988,
    core: "nes",
    accept: ".nes,.zip",
    cheats: [
      { id: "lives", code: "SLTUIL" },
      { id: "thirty", code: "30 lives (title: ↑↑↓↓←→←→BA then Start)" },
      { id: "spread", code: "GXUJULSX" },
      { id: "rapid", code: "AENYLGEY" },
    ],
  },
  {
    id: "battle-city",
    console: "fc",
    genre: "action",
    year: 1985,
    core: "nes",
    accept: ".nes,.zip",
    cheats: [
      { id: "lives", code: "SZUVLNVK" },
      { id: "stage", code: "PAUVEZAA+ZAUVOZPA" },
      { id: "armor", code: "AEVVOZPA" },
      { id: "freeze", code: "GXVVPKVK" },
    ],
  },
  {
    id: "adventure-island",
    console: "fc",
    genre: "platform",
    year: 1986,
    core: "nes",
    accept: ".nes,.zip",
    cheats: [
      { id: "lives", code: "SZEXTKVK" },
      { id: "invincible", code: "OTUXLGEY" },
      { id: "skate", code: "ZEEXTKPA" },
      { id: "weapon", code: "GXEXTKVK" },
    ],
  },
  {
    id: "tetris-nes",
    console: "fc",
    genre: "puzzle",
    year: 1989,
    core: "nes",
    accept: ".nes,.zip",
    cheats: [
      { id: "level", code: "PAOPZLAA" },
      { id: "speed", code: "AEEPZLPA" },
      { id: "next", code: "GXOPZLVK" },
      { id: "slow", code: "AEEPZLEA" },
    ],
  },
  {
    id: "double-dragon",
    console: "fc",
    genre: "fighting",
    year: 1988,
    core: "nes",
    accept: ".nes,.zip",
    cheats: [
      { id: "lives", code: "SZUEUOVK" },
      { id: "energy", code: "GXUEUOSE" },
      { id: "weapon", code: "AEEEUOPA" },
      { id: "continue", code: "OXuEuOSE" },
    ],
  },
  {
    id: "super-mario-world",
    console: "sfc",
    genre: "platform",
    year: 1990,
    core: "snes",
    accept: ".sfc,.smc,.zip",
    cheats: [
      { id: "lives", code: "DDA4-AF6F" },
      { id: "star", code: "DDA4-A4AF" },
      { id: "yoshi", code: "DDA4-A4DF" },
      { id: "cape", code: "DDA4-A46F" },
    ],
  },
  {
    id: "zelda-alttp",
    console: "sfc",
    genre: "rpg",
    year: 1991,
    core: "snes",
    accept: ".sfc,.smc,.zip",
    cheats: [
      { id: "rupees", code: "DDEE-A4AF" },
      { id: "hearts", code: "DDEE-AF6F" },
      { id: "keys", code: "DDEE-A46F" },
      { id: "sword", code: "DDEE-A4DF" },
    ],
  },
  {
    id: "street-fighter-ii",
    console: "sfc",
    genre: "fighting",
    year: 1992,
    core: "snes",
    accept: ".sfc,.smc,.zip",
    cheats: [
      { id: "energy", code: "DDFE-A4AF" },
      { id: "time", code: "DDFE-AF6F" },
      { id: "special", code: "DDFE-A46F" },
      { id: "speed", code: "DDFE-A4DF" },
    ],
  },
  {
    id: "pokemon-red",
    console: "gb",
    genre: "rpg",
    year: 1996,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    cheats: [
      { id: "walk", code: "01FF0D01" },
      { id: "money", code: "01909C53" },
      { id: "rare", code: "01017ED3" },
      { id: "repel", code: "01017F01" },
    ],
  },
  {
    id: "tetris-gb",
    console: "gb",
    genre: "puzzle",
    year: 1989,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    cheats: [
      { id: "level", code: "0109C1C3" },
      { id: "next", code: "0100C0C3" },
      { id: "slow", code: "0100C2C3" },
      { id: "score", code: "0199C4C3" },
    ],
  },
  {
    id: "kirby-dream-land",
    console: "gb",
    genre: "platform",
    year: 1992,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    cheats: [
      { id: "lives", code: "0109E2DB" },
      { id: "health", code: "0106E3DB" },
      { id: "invincible", code: "0101E4DB" },
      { id: "star", code: "0101E5DB" },
    ],
  },
  {
    id: "pokemon-gold",
    console: "gbc",
    genre: "rpg",
    year: 1999,
    core: "gbc",
    accept: ".gbc,.gb,.zip",
    cheats: [
      { id: "walk", code: "01FF0098" },
      { id: "money", code: "019090D8" },
      { id: "repel", code: "01017F01" },
      { id: "rare", code: "01017ED3" },
    ],
  },
  {
    id: "pokemon-emerald",
    console: "gba",
    genre: "rpg",
    year: 2004,
    core: "gba",
    accept: ".gba,.zip",
    cheats: [
      { id: "walk", code: "509C1C1F 4E230865" },
      { id: "money", code: "D8BAE4D9 4864DCE5" },
      { id: "rare", code: "A86CDBA5 19BA49B3" },
      { id: "repel", code: "6C5DCB19 7F3E3A5A" },
    ],
  },
  {
    id: "mario-kart-super-circuit",
    console: "gba",
    genre: "racing",
    year: 2001,
    core: "gba",
    accept: ".gba,.zip",
    cheats: [
      { id: "stars", code: "33001880 00000063" },
      { id: "laps", code: "33001884 00000002" },
      { id: "ghost", code: "33001888 00000001" },
      { id: "all", code: "3300188C 000000FF" },
    ],
  },
  {
    id: "minish-cap",
    console: "gba",
    genre: "rpg",
    year: 2004,
    core: "gba",
    accept: ".gba,.zip",
    cheats: [
      { id: "rupees", code: "33002432 03E7" },
      { id: "hearts", code: "3300242A 00A0" },
      { id: "keys", code: "3300243C 0009" },
      { id: "sword", code: "33002440 0005" },
    ],
  },
  {
    id: "sonic",
    console: "md",
    genre: "platform",
    year: 1991,
    core: "segaMD",
    accept: ".md,.gen,.bin,.smd,.zip",
    cheats: [
      { id: "lives", code: "FFFE12:0009" },
      { id: "rings", code: "FFFE20:00C8" },
      { id: "debug", code: "Level select: ↑↓←→ hold A, Start" },
      { id: "invincible", code: "FFFE18:0001" },
    ],
  },
  {
    id: "streets-of-rage-2",
    console: "md",
    genre: "action",
    year: 1992,
    core: "segaMD",
    accept: ".md,.gen,.bin,.smd,.zip",
    cheats: [
      { id: "lives", code: "FFEF81:0009" },
      { id: "special", code: "FFEF84:0009" },
      { id: "level", code: "FFEF80:0005" },
      { id: "same", code: "Same character: B+Start on character" },
    ],
  },
  {
    id: "snow-bros",
    console: "fc",
    genre: "action",
    year: 1990,
    core: "nes",
    accept: ".nes,.zip",
    cheats: [
      { id: "lives", code: "SZUVLNVK" },
      { id: "invincible", code: "OTUVLGEY" },
      { id: "weapon", code: "GXUVLNVK" },
      { id: "boss", code: "AEEVLNPA" },
    ],
  },
  {
    id: "bubble-bobble",
    console: "fc",
    genre: "action",
    year: 1988,
    core: "nes",
    accept: ".nes,.zip",
    cheats: [
      { id: "lives", code: "SZEXTKVK" },
      { id: "rapid", code: "AEEVTKPA" },
      { id: "skip", code: "PAEXTKAA" },
      { id: "ending", code: "GXEXTKVK" },
    ],
  },
  {
    id: "jackal",
    console: "fc",
    genre: "shooting",
    year: 1988,
    core: "nes",
    accept: ".nes,.zip",
    cheats: [
      { id: "lives", code: "SZUVOZVK" },
      { id: "ammo", code: "GXUVOZSE" },
      { id: "speed", code: "AEUVOZPA" },
      { id: "invincible", code: "OTUVOZEY" },
    ],
  },
  {
    id: "kunio-soccer",
    console: "fc",
    genre: "action",
    year: 1988,
    core: "nes",
    accept: ".nes,.zip",
    cheats: [
      { id: "score", code: "PAUVEZAA" },
      { id: "time", code: "AEUVEZPA" },
      { id: "stamina", code: "SZUVEZVK" },
      { id: "super", code: "GXUVEZSE" },
    ],
  },
  {
    id: "ninja-turtles",
    console: "fc",
    genre: "action",
    year: 1989,
    core: "nes",
    accept: ".nes,.zip",
    cheats: [
      { id: "lives", code: "SZNTEZVK" },
      { id: "energy", code: "GXNTEZSE" },
      { id: "weapon", code: "AENTEZPA" },
      { id: "pizza", code: "OTNTEZEY" },
    ],
  },
  {
    id: "mega-man-2",
    console: "fc",
    genre: "platform",
    year: 1988,
    core: "nes",
    accept: ".nes,.zip",
    cheats: [
      { id: "lives", code: "SZKGELVK" },
      { id: "energy", code: "GXKGELSE" },
      { id: "weapon", code: "AEKGELPA" },
      { id: "rush", code: "OTKGELEY" },
    ],
  },
  {
    id: "zelda-nes",
    console: "fc",
    genre: "rpg",
    year: 1986,
    core: "nes",
    accept: ".nes,.zip",
    cheats: [
      { id: "hearts", code: "SZKGOLVK" },
      { id: "rupees", code: "PAKGOLAA" },
      { id: "keys", code: "AEKGOLPA" },
      { id: "sword", code: "GXKGOLSE" },
    ],
  },
  {
    id: "kung-fu",
    console: "fc",
    genre: "fighting",
    year: 1985,
    core: "nes",
    accept: ".nes,.zip",
    cheats: [
      { id: "lives", code: "SZKGILVK" },
      { id: "energy", code: "GXKGILSE" },
      { id: "time", code: "AEKGILPA" },
      { id: "kick", code: "OTKGILEY" },
    ],
  },
  {
    id: "chrono-trigger",
    console: "sfc",
    genre: "rpg",
    year: 1995,
    core: "snes",
    accept: ".sfc,.smc,.zip",
    cheats: [
      { id: "hp", code: "DDA4-A4AF" },
      { id: "mp", code: "DDA4-AF6F" },
      { id: "gold", code: "DDA4-A46F" },
      { id: "tech", code: "DDA4-A4DF" },
    ],
  },
  {
    id: "super-mario-kart",
    console: "sfc",
    genre: "racing",
    year: 1992,
    core: "snes",
    accept: ".sfc,.smc,.zip",
    cheats: [
      { id: "stars", code: "DDFE-A4AF" },
      { id: "laps", code: "DDFE-AF6F" },
      { id: "ghost", code: "DDFE-A46F" },
      { id: "unlock", code: "DDFE-A4DF" },
    ],
  },
  {
    id: "super-mario-land",
    console: "gb",
    genre: "platform",
    year: 1989,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    cheats: [
      { id: "lives", code: "0109E2DB" },
      { id: "invincible", code: "0101E4DB" },
      { id: "flower", code: "0101E5DB" },
      { id: "stage", code: "0103E6DB" },
    ],
  },
  {
    id: "pokemon-crystal",
    console: "gbc",
    genre: "rpg",
    year: 2000,
    core: "gbc",
    accept: ".gbc,.gb,.zip",
    cheats: [
      { id: "walk", code: "01FF0098" },
      { id: "money", code: "019090D8" },
      { id: "repel", code: "01017F01" },
      { id: "rare", code: "01017ED3" },
    ],
  },
  {
    id: "pokemon-fire-red",
    console: "gba",
    genre: "rpg",
    year: 2004,
    core: "gba",
    accept: ".gba,.zip",
    cheats: [
      { id: "walk", code: "509C1C1F 4E230865" },
      { id: "money", code: "D8BAE4D9 4864DCE5" },
      { id: "rare", code: "A86CDBA5 19BA49B3" },
      { id: "repel", code: "6C5DCB19 7F3E3A5A" },
    ],
  },
  {
    id: "sonic-2",
    console: "md",
    genre: "platform",
    year: 1992,
    core: "segaMD",
    accept: ".md,.gen,.bin,.smd,.zip",
    cheats: [
      { id: "lives", code: "FFFE12:0009" },
      { id: "rings", code: "FFFE20:00C8" },
      { id: "debug", code: "Level select: ↑↑↓↓↓↓←→←→ hold A, Start" },
      { id: "invincible", code: "FFFE18:0001" },
    ],
  },
  {
    id: "zooming-secretary",
    console: "fc",
    genre: "action",
    year: 2011,
    core: "nes",
    accept: ".nes,.zip",
    rom: "zooming-secretary.nes",
    cheats: [],
  },
  {
    id: "lan-master",
    console: "fc",
    genre: "puzzle",
    year: 2011,
    core: "nes",
    accept: ".nes,.zip",
    rom: "lan-master.nes",
    cheats: [],
  },
  {
    id: "alter-ego",
    console: "fc",
    genre: "puzzle",
    year: 2011,
    core: "nes",
    accept: ".nes,.zip",
    rom: "alter-ego.nes",
    cheats: [],
  },
  {
    id: "lawn-mower",
    console: "fc",
    genre: "action",
    year: 2011,
    core: "nes",
    accept: ".nes,.zip",
    rom: "lawn-mower.nes",
    cheats: [],
  },
  {
    id: "thwaite",
    console: "fc",
    genre: "shooting",
    year: 2011,
    core: "nes",
    accept: ".nes,.zip",
    rom: "thwaite.nes",
    cheats: [],
  },
  {
    id: "rhde",
    console: "fc",
    genre: "fighting",
    year: 2014,
    core: "nes",
    accept: ".nes,.zip",
    rom: "rhde.nes",
    cheats: [],
  },
  {
    id: "croom",
    console: "fc",
    genre: "puzzle",
    year: 2010,
    core: "nes",
    accept: ".nes,.zip",
    rom: "croom.nes",
    cheats: [],
  },
  {
    id: "zap-ruder",
    console: "fc",
    genre: "action",
    year: 2011,
    core: "nes",
    accept: ".nes,.zip",
    rom: "zap-ruder.nes",
    cheats: [],
  },
  {
    id: "rex-runner-gb",
    console: "gb",
    genre: "platform",
    year: 2024,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    rom: "rex-runner-gb.gb",
    cheats: [],
  },
  {
    id: "canight-slime-trials",
    console: "gb",
    genre: "platform",
    year: 2023,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    rom: "canight-slime-trials.gb",
    cheats: [],
  },
  {
    id: "rex-run-v1-0",
    console: "gb",
    genre: "action",
    year: 2019,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    rom: "rex-run-v1-0.gb",
    cheats: [],
  },
  {
    id: "tobutobugirldeluxe",
    console: "gb",
    genre: "action",
    year: 2018,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    rom: "tobutobugirldeluxe.gb",
    cheats: [],
  },
  {
    id: "staticlinkage-skeleton-crew",
    console: "gb",
    genre: "rpg",
    year: 2023,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    rom: "staticlinkage-skeleton-crew.gb",
    cheats: [],
  },
  {
    id: "sleepingpandagames-moki-the-monster-kid",
    console: "gb",
    genre: "rpg",
    year: 2023,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    rom: "sleepingpandagames-moki-the-monster-kid.gb",
    cheats: [],
  },
  {
    id: "tyro-shaman",
    console: "gbc",
    genre: "rpg",
    year: 2025,
    core: "gbc",
    accept: ".gbc,.gb,.zip",
    rom: "tyro-shaman.gbc",
    cheats: [],
  },
  {
    id: "nikku4211-7heaven",
    console: "gb",
    genre: "action",
    year: 2023,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    rom: "nikku4211-7heaven.gb",
    cheats: [],
  },
  {
    id: "bit-bang",
    console: "gb",
    genre: "puzzle",
    year: 2024,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    rom: "bit-bang.gb",
    cheats: [],
  },
  {
    id: "wyrmhole",
    console: "gb",
    genre: "shooting",
    year: 2022,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    rom: "wyrmhole.gb",
    cheats: [],
  },
  {
    id: "rhythm-land",
    console: "gb",
    genre: "action",
    year: 2018,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    rom: "rhythm-land.gb",
    cheats: [],
  },
  {
    id: "airplanz",
    console: "gb",
    genre: "puzzle",
    year: 2018,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    rom: "airplanz.gb",
    cheats: [],
  },
  {
    id: "square-fall",
    console: "gb",
    genre: "puzzle",
    year: 2018,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    rom: "square-fall.gb",
    cheats: [],
  },
  {
    id: "plyr0-qulqy",
    console: "gbc",
    genre: "puzzle",
    year: 2025,
    core: "gbc",
    accept: ".gbc,.gb,.zip",
    rom: "plyr0-qulqy.gbc",
    cheats: [],
  },
  {
    id: "flooder",
    console: "gb",
    genre: "puzzle",
    year: 2018,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    rom: "flooder.gb",
    cheats: [],
  },
  {
    id: "maxpirate",
    console: "gb",
    genre: "action",
    year: 2024,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    rom: "maxpirate.gb",
    cheats: [],
  },
  {
    id: "mateusdigital-el-jamon-volador",
    console: "gb",
    genre: "action",
    year: 2023,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    rom: "mateusdigital-el-jamon-volador.gb",
    cheats: [],
  },
  {
    id: "gbstadium",
    console: "gbc",
    genre: "platform",
    year: 2018,
    core: "gbc",
    accept: ".gbc,.gb,.zip",
    rom: "gbstadium.gbc",
    cheats: [],
  },
  {
    id: "shock-lobster",
    console: "gb",
    genre: "action",
    year: 2018,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    rom: "shock-lobster.gb",
    cheats: [],
  },
  {
    id: "tobutobugirl",
    console: "gb",
    genre: "action",
    year: 2017,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    rom: "tobutobugirl.gb",
    cheats: [],
  },
  {
    id: "porklike-gb",
    console: "gb",
    genre: "action",
    year: 2018,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    rom: "porklike-gb.gb",
    cheats: [],
  },
  {
    id: "gbhack",
    console: "gbc",
    genre: "rpg",
    year: 2026,
    core: "gbc",
    accept: ".gbc,.gb,.zip",
    rom: "gbhack.gbc",
    cheats: [],
  },
  {
    id: "grimmrobegames-abducted",
    console: "gb",
    genre: "rpg",
    year: 2023,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    rom: "grimmrobegames-abducted.gb",
    cheats: [],
  },
  {
    id: "carazu",
    console: "gb",
    genre: "platform",
    year: 2018,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    rom: "carazu.gb",
    cheats: [],
  },
  {
    id: "joestrong-monster-within",
    console: "gbc",
    genre: "action",
    year: 2023,
    core: "gbc",
    accept: ".gbc,.gb,.zip",
    rom: "joestrong-monster-within.gbc",
    cheats: [],
  },
  {
    id: "squishy-the-turtle",
    console: "gb",
    genre: "action",
    year: 2015,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    rom: "squishy-the-turtle.gb",
    cheats: [],
  },
  {
    id: "zypher",
    console: "gb",
    genre: "shooting",
    year: 2018,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    rom: "zypher.gb",
    cheats: [],
  },
  {
    id: "escape-obliterizer-dx",
    console: "gb",
    genre: "action",
    year: 2020,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    rom: "escape-obliterizer-dx.gb",
    cheats: [],
  },
  {
    id: "brekstascat",
    console: "gb",
    genre: "puzzle",
    year: 2018,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    rom: "brekstascat.gb",
    cheats: [],
  },
  {
    id: "game-boy-of-life",
    console: "gb",
    genre: "action",
    year: 2024,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    rom: "game-boy-of-life.gb",
    cheats: [],
  },
  {
    id: "airaki",
    console: "gb",
    genre: "puzzle",
    year: 2018,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    rom: "airaki.gb",
    cheats: [],
  },
  {
    id: "djarky-keychan",
    console: "gb",
    genre: "platform",
    year: 2023,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    rom: "djarky-keychan.gb",
    cheats: [],
  },
  {
    id: "big2small",
    console: "gb",
    genre: "puzzle",
    year: 2021,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    rom: "big2small.gb",
    cheats: [],
  },
  {
    id: "adjustris",
    console: "gb",
    genre: "action",
    year: 2018,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    rom: "adjustris.gb",
    cheats: [],
  },
  {
    id: "crossconnect",
    console: "gbc",
    genre: "puzzle",
    year: 2022,
    core: "gbc",
    accept: ".gbc,.gb,.zip",
    rom: "crossconnect.gbc",
    cheats: [],
  },
  {
    id: "alien-invasion",
    console: "gb",
    genre: "action",
    year: 2018,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    rom: "alien-invasion.gb",
    cheats: [],
  },
  {
    id: "zone-booth-pizza-palace",
    console: "gb",
    genre: "action",
    year: 2018,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    rom: "zone-booth-pizza-palace.gb",
    cheats: [],
  },
  {
    id: "dusky-dungeon",
    console: "gb",
    genre: "action",
    year: 2018,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    rom: "dusky-dungeon.gb",
    cheats: [],
  },
  {
    id: "quinevere-gigant-golf",
    console: "gb",
    genre: "action",
    year: 2023,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    rom: "quinevere-gigant-golf.gb",
    cheats: [],
  },
  {
    id: "sushi-nights",
    console: "gb",
    genre: "action",
    year: 2018,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    rom: "sushi-nights.gb",
    cheats: [],
  },
  {
    id: "maxpirateeb",
    console: "gb",
    genre: "action",
    year: 2025,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    rom: "maxpirateeb.gb",
    cheats: [],
  },
  {
    id: "trabant",
    console: "gbc",
    genre: "action",
    year: 2018,
    core: "gbc",
    accept: ".gbc,.gb,.zip",
    rom: "trabant.gbc",
    cheats: [],
  },
  {
    id: "renegade-rush",
    console: "gb",
    genre: "action",
    year: 2021,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    rom: "renegade-rush.gb",
    cheats: [],
  },
  {
    id: "demekala-toko",
    console: "gb",
    genre: "platform",
    year: 2023,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    rom: "demekala-toko.gb",
    cheats: [],
  },
  {
    id: "2048gb",
    console: "gb",
    genre: "puzzle",
    year: 2018,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    rom: "2048gb.gb",
    cheats: [],
  },
  {
    id: "gb-corp",
    console: "gb",
    genre: "action",
    year: 2018,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    rom: "gb-corp.gb",
    cheats: [],
  },
  {
    id: "5-mazes",
    console: "gb",
    genre: "puzzle",
    year: 2018,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    rom: "5-mazes.gb",
    cheats: [],
  },
  {
    id: "jp",
    console: "gb",
    genre: "platform",
    year: 2021,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    rom: "jp.gb",
    cheats: [],
  },
  {
    id: "5-mazes-master-levels",
    console: "gb",
    genre: "puzzle",
    year: 2018,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    rom: "5-mazes-master-levels.gb",
    cheats: [],
  },
  {
    id: "el-dueloroso",
    console: "gb",
    genre: "action",
    year: 2018,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    rom: "el-dueloroso.gb",
    cheats: [],
  },
  {
    id: "rebound",
    console: "gbc",
    genre: "action",
    year: 2018,
    core: "gbc",
    accept: ".gbc,.gb,.zip",
    rom: "rebound.gbc",
    cheats: [],
  },
  {
    id: "postbot",
    console: "gb",
    genre: "puzzle",
    year: 2018,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    rom: "postbot.gb",
    cheats: [],
  },
  {
    id: "aevilia",
    console: "gbc",
    genre: "rpg",
    year: 2018,
    core: "gbc",
    accept: ".gbc,.gb,.zip",
    rom: "aevilia.gbc",
    cheats: [],
  },
  {
    id: "libbet",
    console: "gb",
    genre: "puzzle",
    year: 2018,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    rom: "libbet.gb",
    cheats: [],
  },
  {
    id: "unstoppable-knight",
    console: "gb",
    genre: "action",
    year: 2018,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    rom: "unstoppable-knight.gb",
    cheats: [],
  },
  {
    id: "patmorita-hermano-game-boy",
    console: "gb",
    genre: "action",
    year: 2023,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    rom: "patmorita-hermano-game-boy.gb",
    cheats: [],
  },
  {
    id: "5-more-mazes",
    console: "gb",
    genre: "puzzle",
    year: 2018,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    rom: "5-more-mazes.gb",
    cheats: [],
  },
  {
    id: "postie",
    console: "gbc",
    genre: "platform",
    year: 2022,
    core: "gbc",
    accept: ".gbc,.gb,.zip",
    rom: "postie.gbc",
    cheats: [],
  },
  {
    id: "attack-on-voxelburg",
    console: "gba",
    genre: "action",
    year: 2022,
    core: "gba",
    accept: ".gba,.zip",
    rom: "attack-on-voxelburg.gba",
    cheats: [],
  },
  {
    id: "xniq",
    console: "gba",
    genre: "puzzle",
    year: 2018,
    core: "gba",
    accept: ".gba,.zip",
    rom: "xniq.gba",
    cheats: [],
  },
  {
    id: "breadmakesyoufull-gbadev-containers",
    console: "gba",
    genre: "action",
    year: 2018,
    core: "gba",
    accept: ".gba,.zip",
    rom: "breadmakesyoufull-gbadev-containers.gba",
    cheats: [],
  },
  {
    id: "basil-termini-2048-advance",
    console: "gba",
    genre: "puzzle",
    year: 2018,
    core: "gba",
    accept: ".gba,.zip",
    rom: "basil-termini-2048-advance.gba",
    cheats: [],
  },
  {
    id: "afska-beat-beast",
    console: "gba",
    genre: "shooting",
    year: 2018,
    core: "gba",
    accept: ".gba,.zip",
    rom: "afska-beat-beast.gba",
    cheats: [],
  },
  {
    id: "butano-fighter",
    console: "gba",
    genre: "shooting",
    year: 2018,
    core: "gba",
    accept: ".gba,.zip",
    rom: "butano-fighter.gba",
    cheats: [],
  },
  {
    id: "origamiscienceguy-galactic-quest",
    console: "gba",
    genre: "action",
    year: 2018,
    core: "gba",
    accept: ".gba,.zip",
    rom: "origamiscienceguy-galactic-quest.gba",
    cheats: [],
  },
  {
    id: "hexes",
    console: "gba",
    genre: "shooting",
    year: 2022,
    core: "gba",
    accept: ".gba,.zip",
    rom: "hexes.gba",
    cheats: [],
  },
  {
    id: "the-purple-night",
    console: "gba",
    genre: "platform",
    year: 2018,
    core: "gba",
    accept: ".gba,.zip",
    rom: "the-purple-night.gba",
    cheats: [],
  },
  {
    id: "bugtris",
    console: "gba",
    genre: "puzzle",
    year: 2022,
    core: "gba",
    accept: ".gba,.zip",
    rom: "bugtris.gba",
    cheats: [],
  },
  {
    id: "varooom3d",
    console: "gba",
    genre: "racing",
    year: 2018,
    core: "gba",
    accept: ".gba,.zip",
    rom: "varooom3d.gba",
    cheats: [],
  },
  {
    id: "solar-guard",
    console: "gba",
    genre: "shooting",
    year: 2018,
    core: "gba",
    accept: ".gba,.zip",
    rom: "solar-guard.gba",
    cheats: [],
  },
  {
    id: "feline",
    console: "gba",
    genre: "rpg",
    year: 2018,
    core: "gba",
    accept: ".gba,.zip",
    rom: "feline.gba",
    cheats: [],
  },
  {
    id: "collie-defence",
    console: "gba",
    genre: "action",
    year: 2022,
    core: "gba",
    accept: ".gba,.zip",
    rom: "collie-defence.gba",
    cheats: [],
  },
  {
    id: "bloxorz-gba",
    console: "gba",
    genre: "puzzle",
    year: 2018,
    core: "gba",
    accept: ".gba,.zip",
    rom: "bloxorz-gba.gba",
    cheats: [],
  },
  {
    id: "gbamicrojam23",
    console: "gba",
    genre: "action",
    year: 2018,
    core: "gba",
    accept: ".gba,.zip",
    rom: "gbamicrojam23.gba",
    cheats: [],
  },
  {
    id: "glaciadungeon",
    console: "gba",
    genre: "action",
    year: 2022,
    core: "gba",
    accept: ".gba,.zip",
    rom: "glaciadungeon.gba",
    cheats: [],
  },
  {
    id: "coquiman",
    console: "gba",
    genre: "action",
    year: 2023,
    core: "gba",
    accept: ".gba,.zip",
    rom: "coquiman.gba",
    cheats: [],
  },
  {
    id: "the-hat-chooses-the-wizard",
    console: "gba",
    genre: "platform",
    year: 2018,
    core: "gba",
    accept: ".gba,.zip",
    rom: "the-hat-chooses-the-wizard.gba",
    cheats: [],
  },
  {
    id: "meteorain-gba-jam-2021",
    console: "gba",
    genre: "action",
    year: 2018,
    core: "gba",
    accept: ".gba,.zip",
    rom: "meteorain-gba-jam-2021.gba",
    cheats: [],
  },
  {
    id: "skyland",
    console: "gba",
    genre: "rpg",
    year: 2018,
    core: "gba",
    accept: ".gba,.zip",
    rom: "skyland.gba",
    cheats: [],
  },
  {
    id: "air-hockey-nes",
    console: "fc",
    genre: "action",
    year: 2025,
    core: "nes",
    accept: ".nes,.zip",
    rom: "air-hockey-nes.nes",
    cheats: [],
  },
  {
    id: "falling-nes",
    console: "fc",
    genre: "action",
    year: 2018,
    core: "nes",
    accept: ".nes,.zip",
    rom: "falling-nes.nes",
    cheats: [],
  },
  {
    id: "linear-collision",
    console: "fc",
    genre: "action",
    year: 2018,
    core: "nes",
    accept: ".nes,.zip",
    rom: "linear-collision.nes",
    cheats: [],
  },
  {
    id: "nes-runner",
    console: "fc",
    genre: "platform",
    year: 2019,
    core: "nes",
    accept: ".nes,.zip",
    rom: "nes-runner.nes",
    cheats: [],
  },
  {
    id: "roborun",
    console: "fc",
    genre: "platform",
    year: 2024,
    core: "nes",
    accept: ".nes,.zip",
    rom: "roborun.nes",
    cheats: [],
  },
  {
    id: "sliding-blaster",
    console: "fc",
    genre: "shooting",
    year: 2014,
    core: "nes",
    accept: ".nes,.zip",
    rom: "sliding-blaster.nes",
    cheats: [],
  },
  {
    id: "squirrel-domino",
    console: "fc",
    genre: "puzzle",
    year: 2024,
    core: "nes",
    accept: ".nes,.zip",
    rom: "squirrel-domino.nes",
    cheats: [],
  },
  {
    id: "geometrix",
    console: "gbc",
    genre: "puzzle",
    year: 2016,
    core: "gbc",
    accept: ".gbc,.gb,.zip",
    rom: "geometrix.gbc",
    cheats: [],
  },
  {
    id: "ucity",
    console: "gbc",
    genre: "rpg",
    year: 2017,
    core: "gbc",
    accept: ".gbc,.gb,.zip",
    rom: "ucity.gbc",
    cheats: [],
  },
  {
    id: "dawn-will-come",
    console: "gb",
    genre: "rpg",
    year: 2021,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    rom: "dawn-will-come.gb",
    cheats: [],
  },
  {
    id: "labirinth",
    console: "gbc",
    genre: "rpg",
    year: 2021,
    core: "gbc",
    accept: ".gbc,.gb,.zip",
    rom: "labirinth.gbc",
    cheats: [],
  },
  {
    id: "europa-rescue",
    console: "gbc",
    genre: "puzzle",
    year: 2022,
    core: "gbc",
    accept: ".gbc,.gb,.zip",
    rom: "europa-rescue.gbc",
    cheats: [],
  },
  {
    id: "gb-snake",
    console: "gb",
    genre: "puzzle",
    year: 2017,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    rom: "gb-snake.gb",
    cheats: [],
  },
  {
    id: "apotris",
    console: "gba",
    genre: "puzzle",
    year: 2021,
    core: "gba",
    accept: ".gba,.zip",
    rom: "apotris.gba",
    cheats: [],
  },
  {
    id: "domination",
    console: "gb",
    genre: "puzzle",
    year: 2021,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    rom: "domination.gb",
    cheats: [],
  },
  {
    id: "conways-life",
    console: "gb",
    genre: "puzzle",
    year: 2024,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    rom: "conways-life.gb",
    cheats: [],
  },
  {
    id: "potion-panic",
    console: "gbc",
    genre: "platform",
    year: 2025,
    core: "gbc",
    accept: ".gbc,.gb,.zip",
    rom: "potion-panic.gbc",
    cheats: [],
  },
  {
    id: "k32-super-rocket",
    console: "gbc",
    genre: "shooting",
    year: 2021,
    core: "gbc",
    accept: ".gbc,.gb,.zip",
    rom: "k32-super-rocket.gbc",
    cheats: [],
  },
  {
    id: "lander-advance",
    console: "gba",
    genre: "action",
    year: 2026,
    core: "gba",
    accept: ".gba,.zip",
    rom: "lander-advance.gba",
    cheats: [],
  },
  {
    id: "mega-mountain",
    console: "fc",
    genre: "platform",
    year: 2016,
    core: "nes",
    accept: ".nes,.zip",
    rom: "mega-mountain.nes",
    cheats: [],
  },
  {
    id: "robotfindskitten",
    console: "fc",
    genre: "puzzle",
    year: 2017,
    core: "nes",
    accept: ".nes,.zip",
    rom: "robotfindskitten.nes",
    cheats: [],
  },
  {
    id: "space-gb",
    console: "gb",
    genre: "action",
    year: 2024,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    rom: "space-gb.gb",
    cheats: [],
  },
  {
    id: "keep-up",
    console: "gb",
    genre: "action",
    year: 2017,
    core: "gb",
    accept: ".gb,.gbc,.zip",
    rom: "keep-up.gb",
    cheats: [],
  },
  {
    id: "detruit-les-ballons",
    console: "flash",
    genre: "action",
    year: 2010,
    core: "ruffle",
    accept: ".swf",
    rom: "detruit-les-ballons.swf",
    cheats: [],
  },
  {
    id: "tag-chase",
    console: "flash",
    genre: "action",
    year: 2010,
    core: "ruffle",
    accept: ".swf",
    rom: "tag-chase.swf",
    cheats: [],
  },
  {
    id: "ricochet-kill",
    console: "flash",
    genre: "puzzle",
    year: 2010,
    core: "ruffle",
    accept: ".swf",
    rom: "ricochet-kill.swf",
    cheats: [],
  },
] as const;

export type GameId = (typeof GAMES)[number]["id"];

const GAME_BY_ID = new Map<string, Game>(GAMES.map((game) => [game.id, game]));

export function isGameConsoleId(value: string): value is GameConsoleId {
  return (GAME_CONSOLES as readonly string[]).includes(value);
}

export function isGameId(value: string): value is GameId {
  return GAME_BY_ID.has(value);
}

export function gameById(id: string): Game | undefined {
  return GAME_BY_ID.get(id);
}

export function gamesFor(
  consoleId?: GameConsoleId | null,
  genre?: GameGenreId | null,
): readonly Game[] {
  return GAMES.filter((game) => {
    if (consoleId && game.console !== consoleId) return false;
    if (genre && game.genre !== genre) return false;
    return true;
  });
}

export function isGameGenreId(value: string): value is GameGenreId {
  return (GAME_GENRES as readonly string[]).includes(value);
}

export const GAME_EMU_DATA = "/emu/data/";
export const GAME_ROM_BASE = "/emu/roms/";
export const GAME_S3_PREFIX = "https://s3.cv.cm/files/games/";

const ROM_EXT: Record<GameConsoleId, string> = {
  fc: ".nes",
  sfc: ".sfc",
  gb: ".gb",
  gbc: ".gbc",
  gba: ".gba",
  md: ".md",
  flash: ".swf",
};

/** S3 object name under `/emu/roms/`. Hosted when that object exists; every page still accepts a local file. */
export function gameRomFile(game: Game): string {
  return game.rom ?? `${game.id}${ROM_EXT[game.console]}`;
}
