#!/usr/bin/env python3
"""Inject PNG↔JPG, AVIF→JPG, and rotate/flip how-tos."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LOCS = ["en", "zh-CN", "zh-TW", "ja", "ko", "vi", "id", "es"]
FILES = {loc: ROOT / "src/locales" / f"{loc}.json" for loc in LOCS}


def L(*vals: str) -> dict[str, str]:
    if len(vals) != 8:
        raise ValueError(len(vals), vals[0] if vals else None)
    return dict(zip(LOCS, vals))


def lesson(fields: dict[str, dict[str, str]], faq: dict[str, dict[str, str]]) -> dict:
    return {
        "copy": {loc: {k: v[loc] for k, v in fields.items()} for loc in LOCS},
        "faq": {loc: {k: v[loc] for k, v in faq.items()} for loc in LOCS},
    }


LESSONS = {
    "png-to-jpg": lesson(
        {
            "name": L("How to convert PNG to JPG", "怎么把 PNG 转成 JPG", "怎麼把 PNG 轉成 JPG", "PNGをJPGにする", "PNG를 JPG로", "Cách đổi PNG sang JPG", "Cara ubah PNG ke JPG", "Cómo pasar PNG a JPG"),
            "blurb": L("Pick JPG for a smaller photo. Check that a clear background became a solid matte, then compare file size.", "要更小的照片就选 JPG。看透明底有没有变成实色，再比体积。", "要更小的照片就選 JPG。看透明底有沒有變成實色，再比體積。", "小さくするならJPG。透明が塗りつぶされたか見て、サイズを比べる。", "더 작은 사진이면 JPG. 투명이 단색이 됐는지 보고 용량을 비교하세요.", "Muốn ảnh nhẹ thì chọn JPG. Kiểm nền trong đã đặc chưa, rồi so dung lượng.", "Foto lebih kecil: pilih JPG. Cek latar tembus jadi solid, bandingkan ukuran.", "Elija JPG para menos peso. Compruebe que el fondo transparente se rellenó y compare el tamaño."),
            "title": L("How to convert PNG to JPG", "怎么把 PNG 转成 JPG", "怎麼把 PNG 轉成 JPG", "PNGをJPGにする方法", "PNG를 JPG로 변환하는 법", "Cách đổi PNG sang JPG", "Cara ubah PNG ke JPG", "Cómo pasar PNG a JPG"),
            "lead": L("PNG is lossless and can keep a clear background. JPG is smaller and opens in more email and form uploads. You will convert a copy in this tab and check size plus the background.", "PNG 无损，还能留透明底。JPG 更小，邮件和表单更认。在当前标签页转一份，再看体积和背景。", "PNG 無損，還能留透明底。JPG 更小，郵件和表單更認。在目前分頁轉一份，再看體積和背景。", "PNGは可逆で透明も残せる。JPGは小さく、メールや提出に通る。このタブでコピーを変換し、容量と背景を見る。", "PNG는 무손실이고 투명을 남길 수 있습니다. JPG는 더 작고 이메일·서류에 잘 통합니다. 이 탭에서 복사본을 변환한 뒤 용량과 배경을 보세요.", "PNG không mất nét và giữ nền trong. JPG nhẹ hơn, email và form nhận nhiều hơn. Đổi một bản trong tab này, kiểm dung lượng và nền.", "PNG lossless dan bisa jaga latar tembus. JPG lebih kecil, lebih diterima email dan formulir. Ubah salinan di tab ini, cek ukuran dan latar.", "PNG es sin pérdida y puede conservar el fondo. JPG pesa menos y pasa más en correo y formularios. Convierta una copia aquí y mire peso y fondo."),
            "result": L("A JPG that meets a size cap, with no leftover transparency, plus the original PNG still on disk.", "一份能塞进上限的 JPG，没有残留透明，原 PNG 还在。", "一份能塞進上限的 JPG，沒有殘留透明，原 PNG 還在。", "上限に入るJPG。透明は残らない。元のPNGは残る。", "한도에 들어가는 JPG. 투명은 남지 않습니다. 원본 PNG는 남습니다.", "JPG lọt giới hạn, không còn nền trong, PNG gốc còn trên đĩa.", "JPG yang muat batas, tanpa transparansi, PNG asli tetap di disk.", "Un JPG que cabe en el tope, sin transparencia, y el PNG original en el disco."),
            "note": L("Open convert when the .png is on disk. JPG has no alpha — a clear background becomes a solid matte, often black. Nothing is uploaded.", "文件在磁盘上再打开格式转换。JPG 没有透明通道，透明底会变成实色，常常是黑的。不上传。", "檔在磁碟上再打開格式轉換。JPG 沒有透明通道，透明底會變成實色，常常是黑的。不上傳。", "ファイルが手元にあってから変換を開く。JPGにアルファはなく、透明は塗りつぶされる（多くは黒）。アップロードなし。", "파일이 디스크에 있으면 변환을 여세요. JPG에는 알파가 없어 투명이 단색(종종 검정)이 됩니다. 업로드 없음.", "Có file .png trên đĩa thì mở chuyển đổi. JPG không có alpha — nền trong thành đặc, thường đen. Không tải lên.", "File .png di disk, baru buka konversi. JPG tidak punya alpha — latar tembus jadi solid, sering hitam. Tidak diunggah.", "Abra convertir con el .png en el disco. JPG no tiene alfa: el fondo transparente se rellena, a menudo de negro. Nada se sube."),
            "s1t": L("Decide why you need JPG", "先想清楚为什么要 JPG", "先想清楚為什麼要 JPG", "なぜJPGか決める", "왜 JPG인지 정하기", "Quyết định vì sao cần JPG", "Tentukan kenapa perlu JPG", "Decida por qué necesita JPG"),
            "s1b": L("Email and many forms prefer JPG. Photos shrink. Logos, screenshots, and stickers with a clear background should stay PNG.", "邮件和不少表单更认 JPG。照片会变小。带透明底的 logo、截图、贴纸请留 PNG。", "郵件和不少表單更認 JPG。照片會變小。帶透明底的 logo、截圖、貼紙請留 PNG。", "メールや提出はJPG向き。写真は小さくなる。透明のロゴ・スクショ・シールはPNGのまま。", "이메일과 많은 서류는 JPG를 선호합니다. 사진은 줄어듭니다. 투명이 있는 로고·스크린샷·스티커는 PNG로 두세요.", "Email và nhiều form thích JPG. Ảnh sẽ nhẹ. Logo, screenshot, sticker nền trong hãy giữ PNG.", "Email dan banyak formulir lebih suka JPG. Foto mengecil. Logo, screenshot, stiker berlatar tembus: tetap PNG.", "El correo y muchos formularios prefieren JPG. Las fotos encogen. Logos, capturas y stickers con fondo claro: déjelos en PNG."),
            "s2t": L("Open image formats on cv.cm", "打开 cv.cm 的图片格式", "打開 cv.cm 的圖片格式", "cv.cmの画像形式を開く", "cv.cm 이미지 형식을 열기", "Mở định dạng ảnh trên cv.cm", "Buka format gambar di cv.cm", "Abra formatos de imagen en cv.cm"),
            "s2b": L("Work stays in this tab. Closing it discards the file.", "转换留在当前标签页。关掉就没了。", "轉換留在目前分頁。關掉就沒了。", "このタブで処理。閉じると消える。", "이 탭에서 변환합니다. 닫으면 사라집니다.", "Xử lý trong tab này. Đóng là mất.", "Proses di tab ini. Tutup, hilang.", "El trabajo queda en esta pestaña. Al cerrarla se pierde."),
            "s3t": L("Drop the .png file", "拖入 .png", "拖入 .png", ".pngをドロップ", ".png 넣기", "Thả file .png", "Letakkan .png", "Suelte el .png"),
            "s3b": L("One file or a batch. If the preview is blank, the browser cannot decode that PNG — try another file or browser.", "一张或一批。预览空白，就是这款浏览器解不了，换文件或换浏览器。", "一張或一批。預覽空白，就是這款瀏覽器解不了，換檔或換瀏覽器。", "1枚でもまとめてでも。プレビューが空ならこのブラウザは不可。ファイルかブラウザを変える。", "한 장 또는 여러 장. 미리보기가 비면 이 브라우저는 못 엽니다. 파일이나 브라우저를 바꾸세요.", "Một hoặc nhiều. Xem trước trống thì trình duyệt không đọc được — đổi file hoặc trình duyệt.", "Satu atau batch. Pratinjau kosong: peramban ini gagal. Ganti file atau peramban.", "Uno o varios. Si la vista está en blanco, este navegador no lo decodifica: cambie de archivo o de navegador."),
            "s4t": L("Pick JPG and set quality", "选 JPG，再调质量", "選 JPG，再調品質", "JPGを選び品質を決める", "JPG를 고르고 품질 정하기", "Chọn JPG rồi chỉnh chất lượng", "Pilih JPG dan set kualitas", "Elija JPG y fije la calidad"),
            "s4b": L("Start near 0.9. A clear PNG background becomes a solid matte, often black. Optional max edge only if a form has a pixel cap.", "先从 0.9 左右。透明 PNG 会变成实色，常常是黑底。表单有像素上限再限制长边。", "先從 0.9 左右。透明 PNG 會變成實色，常常是黑底。表單有像素上限再限制長邊。", "0.9前後から。透明PNGは塗りつぶされ、多くは黒。画素上限があるときだけ長辺を制限。", "0.9 근처에서 시작하세요. 투명 PNG는 단색(종종 검정)이 됩니다. 서류에 픽셀 한도가 있을 때만 긴 변을 제한하세요.", "Bắt đầu khoảng 0.9. Nền PNG trong thành đặc, thường đen. Chỉ giới hạn cạnh dài nếu form có trần pixel.", "Mulai sekitar 0.9. Latar PNG tembus jadi solid, sering hitam. Batasi sisi panjang hanya jika formulir punya batas piksel.", "Empiece cerca de 0.9. El fondo PNG transparente se rellena, a menudo de negro. Limite el lado largo solo si el formulario tope de píxeles."),
            "s5t": L("Download the JPG", "下载 JPG", "下載 JPG", "JPGを保存", "JPG 받기", "Tải JPG", "Unduh JPG", "Descargue el JPG"),
            "s5b": L("Keep the PNG until you have opened the JPG and checked the size.", "打开 JPG、核对体积之前留着 PNG。", "打開 JPG、核對體積之前留著 PNG。", "JPGを開きサイズを見るまでPNGを残す。", "JPG를 열고 용량을 확인할 때까지 PNG를 남기세요.", "Giữ PNG đến khi đã mở JPG và kiểm dung lượng.", "Simpan PNG sampai JPG terbuka dan ukurannya dicek.", "Conserve el PNG hasta haber abierto el JPG y mirado el tamaño."),
            "s6t": L("Open the JPG and compare size and background", "打开 JPG，比体积和背景", "打開 JPG，比體積和背景", "JPGを開き容量と背景を比べる", "JPG를 열고 용량과 배경 비교", "Mở JPG, so dung lượng và nền", "Buka JPG, bandingkan ukuran dan latar", "Abra el JPG y compare peso y fondo"),
            "s6b": L("If it is still huge, lower quality or cap the long edge. If a logo now sits on black, you needed PNG. If the form still rejects it, you sent the PNG by mistake.", "还是很大，就降质量或限制长边。logo 坐在黑底上，说明该留 PNG。表单仍拒收，多半发错成 PNG。", "還是很大，就降品質或限制長邊。logo 坐在黑底上，說明該留 PNG。表單仍拒收，多半傳錯成 PNG。", "まだ大きいなら品質を下げるか長辺を制限。ロゴが黒の上ならPNGのままが正しかった。提出が拒むならPNGを送っている。", "여전히 크면 품질을 낮추거나 긴 변을 제한하세요. 로고가 검정 위에 있으면 PNG가 맞았습니다. 서류가 거부하면 PNG를 보낸 것입니다.", "Vẫn nặng thì hạ chất lượng hoặc giới hạn cạnh dài. Logo ngồi trên nền đen thì đáng lẽ giữ PNG. Form vẫn từ chối thì bạn gửi nhầm PNG.", "Masih besar: turunkan kualitas atau batasi sisi. Logo di atas hitam: seharusnya PNG. Formulir menolak: Anda kirim PNG.", "Si sigue enorme, baje calidad o el lado largo. Si el logo quedó sobre negro, debía ser PNG. Si el formulario lo rechaza, envió el PNG."),
            "diagram1": L("PNG keeps sharpness and transparency. JPG is smaller and has no alpha.", "PNG 保边缘和透明。JPG 更小，没有透明通道。", "PNG 保邊緣和透明。JPG 更小，沒有透明通道。", "PNGはSharpと透明。JPGは小さくアルファなし。", "PNG는 선명도와 투명. JPG는 더 작고 알파 없음.", "PNG giữ nét và nền trong. JPG nhẹ hơn, không có alpha.", "PNG jaga ketajaman dan transparansi. JPG lebih kecil, tanpa alpha.", "PNG conserva nitidez y transparencia. JPG pesa menos y no tiene alfa."),
            "diagram2": L("A clear PNG background becomes a solid matte in JPG, often black.", "透明 PNG 转成 JPG 会变成实色，常常是黑底。", "透明 PNG 轉成 JPG 會變成實色，常常是黑底。", "透明PNGはJPGで塗りつぶされ、多くは黒。", "투명 PNG는 JPG에서 단색(종종 검정)이 됩니다.", "Nền PNG trong thành đặc trong JPG, thường đen.", "Latar PNG tembus jadi solid di JPG, sering hitam.", "El fondo PNG transparente se rellena en JPG, a menudo de negro."),
        },
        {
            "q1": L("Can I convert PNG to JPG free online?", "可以免费在线把 PNG 转成 JPG 吗？", "可以免費線上把 PNG 轉成 JPG 嗎？", "PNGをJPGに無料で変換できる？", "PNG를 JPG로 무료 변환할 수 있나요?", "Đổi PNG sang JPG miễn phí online được không?", "Bisa ubah PNG ke JPG gratis online?", "¿Puedo pasar PNG a JPG gratis en línea?"),
            "a1": L("Yes. cv.cm converts in this tab. Nothing is uploaded.", "可以。cv.cm 在当前标签页转换，不上传。", "可以。cv.cm 在目前分頁轉換，不上傳。", "できる。このタブで変換。アップロードなし。", "됩니다. 이 탭에서 변환합니다. 업로드 없음.", "Được. cv.cm đổi trong tab này, không tải lên.", "Ya. cv.cm mengubah di tab ini. Tidak diunggah.", "Sí. cv.cm convierte en esta pestaña. Nada se sube."),
            "q2": L("Will transparency survive?", "透明底还在吗？", "透明底還在嗎？", "透明は残る？", "투명이 남나요?", "Nền trong còn không?", "Transparansi tetap ada?", "¿Se conserva la transparencia?"),
            "a2": L("No. JPG has no alpha. The clear area becomes a solid matte, often black. Keep PNG for stickers and logos.", "不会。JPG 没有透明通道。透明处会变成实色，常常是黑的。贴纸和 logo 请留 PNG。", "不會。JPG 沒有透明通道。透明處會變成實色，常常是黑的。貼紙和 logo 請留 PNG。", "残らない。JPGにアルファはない。透明は塗りつぶされ、多くは黒。シールやロゴはPNG。", "아니요. JPG에는 알파가 없습니다. 투명 부분이 단색(종종 검정)이 됩니다. 스티커와 로고는 PNG로 두세요.", "Không. JPG không có alpha. Vùng trong thành đặc, thường đen. Sticker và logo hãy giữ PNG.", "Tidak. JPG tidak punya alpha. Area tembus jadi solid, sering hitam. Stiker dan logo: tetap PNG.", "No. JPG no tiene alfa. El área clara se rellena, a menudo de negro. Stickers y logos: quédese en PNG."),
            "q3": L("Are files uploaded?", "会上传吗？", "會上傳嗎？", "アップロードされる？", "업로드되나요?", "Có tải lên không?", "Apakah diunggah?", "¿Se suben los archivos?"),
            "a3": L("No. Closing the tab discards them.", "不会。关掉标签页就没了。", "不會。關掉分頁就沒了。", "しない。タブを閉じると消える。", "아니요. 탭을 닫으면 사라집니다.", "Không. Đóng tab là mất.", "Tidak. Tutup tab, hilang.", "No. Al cerrar la pestaña se pierden."),
            "q4": L("What quality should I use?", "质量调多少？", "品質調多少？", "品質はどのくらい？", "품질은 얼마로?", "Chất lượng để bao nhiêu?", "Kualitas berapa?", "¿Qué calidad uso?"),
            "a4": L("Start near 0.9. If the file is still over the cap, lower quality or cap the long edge. Open at 100% before you send.", "先从 0.9。还超上限，就再降或限制长边。发出去之前用 100% 打开看。", "先從 0.9。還超上限，就再降或限制長邊。寄出去之前用 100% 打開看。", "0.9前後。まだ上限超えなら下げて長辺も制限。送る前に100%で開く。", "0.9 근처에서 시작하세요. 한도를 넘으면 더 낮추거나 긴 변을 제한하세요. 보내기 전에 100%로 여세요.", "Bắt đầu khoảng 0.9. Vẫn vượt hạn thì hạ thêm hoặc giới hạn cạnh dài. Mở 100% trước khi gửi.", "Mulai sekitar 0.9. Masih di atas batas: turunkan atau batasi sisi. Buka 100% sebelum kirim.", "Empiece cerca de 0.9. Si sigue sobre el tope, baje más o el lado largo. Ábralo al 100% antes de enviar."),
            "q5": L("Can I convert PNG to JPG without Photoshop?", "不用 Photoshop 能转吗？", "不用 Photoshop 能轉嗎？", "Photoshopなしで？", "포토샵 없이?", "Không cần Photoshop?", "Tanpa Photoshop?", "¿Sin Photoshop?"),
            "a5": L("Yes. This page is the converter. No account.", "可以。本页就是转换。不用账号。", "可以。本頁就是轉換。不用帳號。", "できる。このページが変換。アカウント不要。", "됩니다. 이 페이지가 변환기입니다. 계정 없음.", "Được. Trang này là bộ chuyển. Không tài khoản.", "Ya. Halaman ini konverternya. Tanpa akun.", "Sí. Esta página es el conversor. Sin cuenta."),
        },
    ),
    "jpg-to-png": lesson(
        {
            "name": L("How to convert JPG to PNG", "怎么把 JPG 转成 PNG", "怎麼把 JPG 轉成 PNG", "JPGをPNGにする", "JPG를 PNG로", "Cách đổi JPG sang PNG", "Cara ubah JPG ke PNG", "Cómo pasar JPG a PNG"),
            "blurb": L("Pick PNG for lossless edits or a form that wants PNG. It will not punch a hole in the background. The file usually gets larger.", "要无损再编辑，或表单只要 PNG，就转 PNG。它不会把背景抠成透明。文件通常会变大。", "要無損再編輯，或表單只要 PNG，就轉 PNG。它不會把背景摳成透明。檔通常會變大。", "可逆で再編集する、または提出がPNGならPNGへ。背景は透明にならない。ファイルはたいてい大きくなる。", "무손실로 다시 고치거나 서류가 PNG를 원하면 PNG로. 배경이 투명이 되지는 않습니다. 파일은 보통 커집니다.", "Cần sửa không mất nét, hoặc form bắt PNG, thì đổi PNG. Nó không khoét nền trong. File thường nặng hơn.", "Butuh sunting lossless atau formulir minta PNG: ubah ke PNG. Latar tidak tiba-tiba tembus. File biasanya lebih besar.", "Pase a PNG para editar sin pérdida o si el formulario lo pide. No agujerea el fondo. El archivo suele pesar más."),
            "title": L("How to convert JPG to PNG", "怎么把 JPG 转成 PNG", "怎麼把 JPG 轉成 PNG", "JPGをPNGにする方法", "JPG를 PNG로 변환하는 법", "Cách đổi JPG sang PNG", "Cara ubah JPG ke PNG", "Cómo pasar JPG a PNG"),
            "lead": L("JPG is already lossy. PNG will not restore detail and will not invent transparency. You convert when a tool or form wants PNG, or before you crop the same photo many times.", "JPG 已经有损。PNG 不会找回细节，也不会凭空变透明。软件或表单只要 PNG，或同一张图要裁很多次，再转。", "JPG 已經有損。PNG 不會找回細節，也不會憑空變透明。軟體或表單只要 PNG，或同一張圖要裁很多次，再轉。", "JPGはすでに非可逆。PNGにしても細部は戻らず透明にもならない。提出やツールがPNGのとき、または何度もクロップする前に変換。", "JPG는 이미 손실입니다. PNG로 바꾼다고 디테일이 돌아오거나 투명이 생기지 않습니다. 도구·서류가 PNG를 원하거나 같은 사진을 여러 번 자를 때 변환하세요.", "JPG đã mất nét. PNG không lấy lại chi tiết và không tạo nền trong. Đổi khi tool hoặc form cần PNG, hoặc trước khi crop nhiều lần.", "JPG sudah lossy. PNG tidak mengembalikan detail dan tidak membuat transparansi. Ubah jika alat atau formulir minta PNG, atau sebelum crop berkali-kali.", "JPG ya es con pérdida. PNG no recupera detalle ni inventa transparencia. Convierta si la herramienta o el formulario pide PNG, o antes de recortar muchas veces."),
            "result": L("A PNG that the destination accepts, still opaque, usually larger than the JPG, with the original still on disk.", "一份对方能打开的 PNG，仍然不透明，通常比 JPG 大，原文件还在。", "一份對方能打開的 PNG，仍然不透明，通常比 JPG 大，原檔還在。", "先が受け取るPNG。不透明のまま。JPGより大きいことが多い。元は残る。", "상대가 받는 PNG. 여전히 불투명. 보통 JPG보다 큼. 원본은 남습니다.", "PNG đích nhận được, vẫn đặc, thường nặng hơn JPG, bản gốc còn.", "PNG yang diterima tujuan, tetap buram, biasanya lebih besar dari JPG, asli tetap ada.", "Un PNG que el destino acepta, opaco, suele pesar más que el JPG, y el original en el disco."),
            "note": L("Open convert when the .jpg is on disk. PNG does not remove a photo background. Nothing is uploaded.", "文件在磁盘上再打开格式转换。PNG 不会抠掉照片背景。不上传。", "檔在磁碟上再打開格式轉換。PNG 不會摳掉照片背景。不上傳。", "ファイルが手元にあってから変換を開く。PNGは写真の背景を消さない。アップロードなし。", "파일이 디스크에 있으면 변환을 여세요. PNG가 사진 배경을 지우지 않습니다. 업로드 없음.", "Có file .jpg trên đĩa thì mở chuyển đổi. PNG không xóa nền ảnh. Không tải lên.", "File .jpg di disk, baru buka konversi. PNG tidak menghapus latar foto. Tidak diunggah.", "Abra convertir con el .jpg en el disco. PNG no recorta el fondo de una foto. Nada se sube."),
            "s1t": L("Decide why you need PNG", "先想清楚为什么要 PNG", "先想清楚為什麼要 PNG", "なぜPNGか決める", "왜 PNG인지 정하기", "Quyết định vì sao cần PNG", "Tentukan kenapa perlu PNG", "Decida por qué necesita PNG"),
            "s1b": L("A form or an editor may insist on PNG. Do not convert to 'add transparency' — a JPG has no alpha to keep.", "表单或编辑器可能只要 PNG。不要指望这一步能抠透明：JPG 本来就没有透明通道。", "表單或編輯器可能只要 PNG。不要指望這一步能摳透明：JPG 本來就沒有透明通道。", "提出や編集ソフトがPNG指定のことがある。透明を足すためではない。JPGに残すアルファはない。", "서류나 편집기가 PNG만 받을 수 있습니다. 투명을 '추가'하려고 바꾸지 마세요. JPG에는 남길 알파가 없습니다.", "Form hoặc editor có thể bắt PNG. Đừng đổi để 'thêm nền trong' — JPG không có alpha.", "Formulir atau editor mungkin hanya PNG. Jangan ubah untuk 'menambah transparansi' — JPG tidak punya alpha.", "Un formulario o un editor puede exigir PNG. No convierta para 'añadir transparencia': el JPG no tiene alfa que conservar."),
            "s2t": L("Open image formats on cv.cm", "打开 cv.cm 的图片格式", "打開 cv.cm 的圖片格式", "cv.cmの画像形式を開く", "cv.cm 이미지 형식을 열기", "Mở định dạng ảnh trên cv.cm", "Buka format gambar di cv.cm", "Abra formatos de imagen en cv.cm"),
            "s2b": L("Work stays in this tab. Closing it discards the file.", "转换留在当前标签页。关掉就没了。", "轉換留在目前分頁。關掉就沒了。", "このタブで処理。閉じると消える。", "이 탭에서 변환합니다. 닫으면 사라집니다.", "Xử lý trong tab này. Đóng là mất.", "Proses di tab ini. Tutup, hilang.", "El trabajo queda en esta pestaña. Al cerrarla se pierde."),
            "s3t": L("Drop the .jpg file", "拖入 .jpg", "拖入 .jpg", ".jpgをドロップ", ".jpg 넣기", "Thả file .jpg", "Letakkan .jpg", "Suelte el .jpg"),
            "s3b": L("One file or a batch. If the preview is blank, try another browser.", "一张或一批。预览空白，换浏览器。", "一張或一批。預覽空白，換瀏覽器。", "1枚でもまとめてでも。プレビューが空ならブラウザを変える。", "한 장 또는 여러 장. 미리보기가 비면 브라우저를 바꾸세요.", "Một hoặc nhiều. Xem trước trống thì đổi trình duyệt.", "Satu atau batch. Pratinjau kosong: ganti peramban.", "Uno o varios. Si la vista está en blanco, cambie de navegador."),
            "s4t": L("Pick PNG. Do not expect a clear background", "选 PNG。不要指望背景变透明", "選 PNG。不要指望背景變透明", "PNGを選ぶ。背景は透明にならない", "PNG를 고르기. 배경이 투명이 되지는 않음", "Chọn PNG. Đừng chờ nền trong", "Pilih PNG. Jangan harap latar tembus", "Elija PNG. No espere un fondo transparente"),
            "s4b": L("The pixels stay opaque. Quality has no slider on PNG. Optional max edge only if a form has a pixel cap.", "像素仍是实底。PNG 没有质量滑杆。表单有像素上限再限制长边。", "像素仍是實底。PNG 沒有品質滑桿。表單有像素上限再限制長邊。", "画素は不透明のまま。PNGに品質スライダーはない。画素上限があるときだけ長辺を制限。", "픽셀은 불투명합니다. PNG에는 품질 슬라이더가 없습니다. 서류에 픽셀 한도가 있을 때만 긴 변을 제한하세요.", "Pixel vẫn đặc. PNG không có thanh chất lượng. Chỉ giới hạn cạnh dài nếu form có trần pixel.", "Piksel tetap buram. PNG tidak punya slider kualitas. Batasi sisi hanya jika formulir punya batas piksel.", "Los píxeles siguen opacos. PNG no tiene control de calidad. Limite el lado largo solo si hay tope de píxeles."),
            "s5t": L("Download the PNG", "下载 PNG", "下載 PNG", "PNGを保存", "PNG 받기", "Tải PNG", "Unduh PNG", "Descargue el PNG"),
            "s5b": L("Keep the JPG until you have opened the PNG.", "打开 PNG 之前留着 JPG。", "打開 PNG 之前留著 JPG。", "PNGを開くまでJPGを残す。", "PNG를 열 때까지 JPG를 남기세요.", "Giữ JPG đến khi đã mở PNG.", "Simpan JPG sampai PNG terbuka.", "Conserve el JPG hasta haber abierto el PNG."),
            "s6t": L("Open it and expect a larger file", "打开看，文件通常会变大", "打開看，檔通常會變大", "開いて、大きくなっているのを見る", "열고, 파일이 커졌는지 보기", "Mở ra, file thường nặng hơn", "Buka: file biasanya lebih besar", "Ábralo: el archivo suele pesar más"),
            "s6b": L("If you needed a sticker with a hole, this conversion cannot do that. If the form still wants JPG, send the original.", "若要一张抠过的贴纸，这一步做不到。表单其实要 JPG，就发原文件。", "若要一張摳過的貼紙，這一步做不到。表單其實要 JPG，就傳原檔。", "切り抜きシールが欲しいならこの変換では不可。提出がJPGなら元を送る。", "구멍이 있는 스티커가 필요하면 이 변환으로는 안 됩니다. 서류가 JPG를 원하면 원본을 보내세요.", "Cần sticker thủng nền thì bước này không làm được. Form thực ra cần JPG thì gửi bản gốc.", "Butuh stiker bolong: konversi ini tidak bisa. Formulir sebenarnya JPG: kirim aslinya.", "Si quería un sticker recortado, esta conversión no lo hace. Si el formulario pide JPG, envíe el original."),
            "diagram1": L("JPG is already lossy. PNG will not restore detail.", "JPG 已经有损。转成 PNG 不会找回细节。", "JPG 已經有損。轉成 PNG 不會找回細節。", "JPGはすでに非可逆。PNGにしても細部は戻らない。", "JPG는 이미 손실. PNG로 바꿔도 디테일은 돌아오지 않습니다.", "JPG đã mất nét. Đổi PNG không lấy lại chi tiết.", "JPG sudah lossy. PNG tidak mengembalikan detail.", "JPG ya es con pérdida. PNG no recupera detalle."),
            "diagram2": L("Converting JPG to PNG does not make the background transparent.", "JPG 转 PNG 不会把背景变成透明。", "JPG 轉 PNG 不會把背景變成透明。", "JPG→PNGでは背景は透明にならない。", "JPG를 PNG로 바꾼다고 배경이 투명이 되지 않습니다.", "Đổi JPG sang PNG không làm nền trong.", "JPG ke PNG tidak membuat latar tembus.", "Pasar JPG a PNG no vuelve transparente el fondo."),
        },
        {
            "q1": L("Can I convert JPG to PNG free online?", "可以免费在线把 JPG 转成 PNG 吗？", "可以免費線上把 JPG 轉成 PNG 嗎？", "JPGをPNGに無料で変換できる？", "JPG를 PNG로 무료 변환할 수 있나요?", "Đổi JPG sang PNG miễn phí online được không?", "Bisa ubah JPG ke PNG gratis online?", "¿Puedo pasar JPG a PNG gratis en línea?"),
            "a1": L("Yes. cv.cm converts in this tab. Nothing is uploaded.", "可以。cv.cm 在当前标签页转换，不上传。", "可以。cv.cm 在目前分頁轉換，不上傳。", "できる。このタブで変換。アップロードなし。", "됩니다. 이 탭에서 변환합니다. 업로드 없음.", "Được. cv.cm đổi trong tab này, không tải lên.", "Ya. cv.cm mengubah di tab ini. Tidak diunggah.", "Sí. cv.cm convierte en esta pestaña. Nada se sube."),
            "q2": L("Will JPG to PNG make the background transparent?", "JPG 转 PNG 能抠透明吗？", "JPG 轉 PNG 能摳透明嗎？", "JPGをPNGにすると背景は透明？", "JPG를 PNG로 바꾸면 배경이 투명이 되나요?", "Đổi JPG sang PNG có làm nền trong không?", "JPG ke PNG membuat latar tembus?", "¿JPG a PNG vuelve transparente el fondo?"),
            "a2": L("No. A JPG has no alpha. The PNG stays opaque. You would need a separate cutout.", "不能。JPG 没有透明通道。转成的 PNG 仍是实底。要透明得另外抠。", "不能。JPG 沒有透明通道。轉成的 PNG 仍是實底。要透明得另外摳。", "ならない。JPGにアルファはない。PNGも不透明。切り抜きは別作業。", "아니요. JPG에는 알파가 없습니다. PNG도 불투명합니다. 투명이 필요하면 따로 잘라야 합니다.", "Không. JPG không có alpha. PNG vẫn đặc. Muốn trong phải cắt riêng.", "Tidak. JPG tidak punya alpha. PNG tetap buram. Transparan: potong terpisah.", "No. Un JPG no tiene alfa. El PNG sigue opaco. Haría falta un recorte aparte."),
            "q3": L("Why is the PNG larger?", "为什么 PNG 更大？", "為什麼 PNG 更大？", "PNGが大きいのはなぜ？", "PNG가 더 큰 이유는?", "Sao PNG nặng hơn?", "Kenapa PNG lebih besar?", "¿Por qué el PNG pesa más?"),
            "a3": L("PNG is lossless. It stores the pixels without JPEG compression, so photos often grow.", "PNG 无损，不再用 JPEG 那种压缩，照片往往会变大。", "PNG 無損，不再用 JPEG 那種壓縮，照片往往會變大。", "PNGは可逆。JPEG圧縮を外すので写真は大きくなりやすい。", "PNG는 무손실입니다. JPEG 압축을 쓰지 않아 사진이 커지는 경우가 많습니다.", "PNG không mất nét, không nén kiểu JPEG, nên ảnh thường nặng hơn.", "PNG lossless. Tanpa kompresi JPEG, foto sering membesar.", "PNG es sin pérdida. Sin la compresión JPEG, las fotos suelen crecer."),
            "q4": L("Are files uploaded?", "会上传吗？", "會上傳嗎？", "アップロードされる？", "업로드되나요?", "Có tải lên không?", "Apakah diunggah?", "¿Se suben los archivos?"),
            "a4": L("No. Closing the tab discards them.", "不会。关掉标签页就没了。", "不會。關掉分頁就沒了。", "しない。タブを閉じると消える。", "아니요. 탭을 닫으면 사라집니다.", "Không. Đóng tab là mất.", "Tidak. Tutup tab, hilang.", "No. Al cerrar la pestaña se pierden."),
            "q5": L("Can I convert JPG to PNG without Photoshop?", "不用 Photoshop 能转吗？", "不用 Photoshop 能轉嗎？", "Photoshopなしで？", "포토샵 없이?", "Không cần Photoshop?", "Tanpa Photoshop?", "¿Sin Photoshop?"),
            "a5": L("Yes. This page is the converter. No account.", "可以。本页就是转换。不用账号。", "可以。本頁就是轉換。不用帳號。", "できる。このページが変換。アカウント不要。", "됩니다. 이 페이지가 변환기입니다. 계정 없음.", "Được. Trang này là bộ chuyển. Không tài khoản.", "Ya. Halaman ini konverternya. Tanpa akun.", "Sí. Esta página es el conversor. Sin cuenta."),
        },
    ),
    "avif-to-jpg": lesson(
        {
            "name": L("How to convert AVIF to JPG", "怎么把 AVIF 转成 JPG", "怎麼把 AVIF 轉成 JPG", "AVIFをJPGにする", "AVIF를 JPG로", "Cách đổi AVIF sang JPG", "Cara ubah AVIF ke JPG", "Cómo pasar AVIF a JPG"),
            "blurb": L("Chrome often saves AVIF. Export JPG, then open it on the PC or form that rejected AVIF.", "Chrome 常存 AVIF。导出 JPG，再到打不开 AVIF 的电脑或表单里打开看。", "Chrome 常存 AVIF。匯出 JPG，再到打不開 AVIF 的電腦或表單裡打開看。", "ChromeはAVIFを保存しがち。JPGを書き出し、拒否したPCや提出で開く。", "Chrome은 AVIF를 자주 저장합니다. JPG로 보낸 뒤 거부한 PC나 서류에서 여세요.", "Chrome hay lưu AVIF. Xuất JPG rồi mở trên máy hoặc form từng từ chối AVIF.", "Chrome sering simpan AVIF. Ekspor JPG, buka di PC atau formulir yang menolak AVIF.", "Chrome suele guardar AVIF. Exporte JPG y ábralo en el PC o formulario que lo rechazó."),
            "title": L("How to convert AVIF to JPG", "怎么把 AVIF 转成 JPG", "怎麼把 AVIF 轉成 JPG", "AVIFをJPGにする方法", "AVIF를 JPG로 변환하는 법", "Cách đổi AVIF sang JPG", "Cara ubah AVIF ke JPG", "Cómo pasar AVIF a JPG"),
            "lead": L("AVIF is smaller. JPG opens on older Windows, print shops, and many chat apps. You will convert a copy in this tab and open the JPG once before sending.", "AVIF 更小。JPG 在老 Windows、打印店和不少聊天软件里打得开。在当前标签页转一份，发出去之前打开看一眼。", "AVIF 更小。JPG 在老 Windows、列印店和不少聊天軟體裡打得開。在目前分頁轉一份，寄出去之前打開看一眼。", "AVIFは小さい。JPGは古いWindows、印刷、チャットで開く。このタブでコピーを変換し、送る前に一度開く。", "AVIF는 더 작습니다. JPG는 옛 Windows, 인쇄소, 많은 채팅 앱에서 열립니다. 이 탭에서 복사본을 변환한 뒤 보내기 전에 한 번 여세요.", "AVIF nhẹ hơn. JPG mở được trên Windows cũ, tiệm in và nhiều chat. Đổi một bản trong tab này, mở JPG một lần trước khi gửi.", "AVIF lebih kecil. JPG terbuka di Windows lama, percetakan, dan banyak chat. Ubah salinan di tab ini, buka JPG sekali sebelum kirim.", "AVIF pesa menos. JPG abre en Windows viejo, imprentas y muchos chats. Convierta una copia aquí y ábrala una vez antes de enviar."),
            "result": L("JPG files that open where AVIF was rejected, with the original AVIF still on disk.", "能在拒收 AVIF 的地方打开的 JPG；原来的 AVIF 还在。", "能在拒收 AVIF 的地方打開的 JPG；原來的 AVIF 還在。", "AVIFを拒んだ先で開くJPG。元のAVIFは残る。", "AVIF를 거부한 곳에서 열리는 JPG. 원본 AVIF는 남습니다.", "JPG mở được nơi từng từ chối AVIF; bản AVIF gốc còn.", "JPG yang terbuka di tempat yang menolak AVIF; AVIF asli tetap ada.", "JPG que abren donde rechazaron AVIF, con el AVIF original en el disco."),
            "note": L("Open convert in a current Chrome, Edge, or Safari. Older browsers may not decode AVIF. Convert a copy. Nothing is uploaded.", "用较新的 Chrome、Edge 或 Safari 打开格式转换。老浏览器可能解不了 AVIF。转的是副本。不上传。", "用較新的 Chrome、Edge 或 Safari 打開格式轉換。老瀏覽器可能解不了 AVIF。轉的是副本。不上傳。", "新しいChrome / Edge / Safariで変換を開く。古いブラウザはAVIFを解けないことがある。コピーを変換。アップロードなし。", "최신 Chrome, Edge, Safari에서 변환을 여세요. 옛 브라우저는 AVIF를 못 열 수 있습니다. 복사본을 변환합니다. 업로드 없음.", "Mở chuyển đổi trong Chrome, Edge hoặc Safari mới. Trình duyệt cũ có thể không đọc AVIF. Đổi bản sao. Không tải lên.", "Buka konversi di Chrome, Edge, atau Safari baru. Peramban lama mungkin gagal decode AVIF. Ubah salinan. Tidak diunggah.", "Abra convertir en Chrome, Edge o Safari actuales. Los navegadores viejos pueden no decodificar AVIF. Convierta una copia. Nada se sube."),
            "s1t": L("Know why the file is AVIF", "先知道为什么是 AVIF", "先知道為什麼是 AVIF", "なぜAVIFか知る", "왜 AVIF인지 알기", "Biết vì sao file là AVIF", "Tahu kenapa filenya AVIF", "Sepa por qué el archivo es AVIF"),
            "s1b": L("Chrome and many sites save AVIF because it is smaller than JPG. Windows Photos, WeChat, and print kiosks often still want JPG.", "Chrome 和不少网站为了体积存 AVIF。Windows 照片、微信、打印店常常只要 JPG。", "Chrome 和不少網站為了體積存 AVIF。Windows 照片、微信、列印店常常只要 JPG。", "Chromeやサイトが小さいAVIFを保存する。Windowsのフォト、WeChat、印刷はまだJPGが多い。", "Chrome과 많은 사이트가 용량 때문에 AVIF를 저장합니다. Windows 사진, 위챗, 인쇄소는 아직 JPG를 원하는 경우가 많습니다.", "Chrome và nhiều site lưu AVIF vì nhẹ hơn JPG. Windows Photos, WeChat, tiệm in thường vẫn cần JPG.", "Chrome dan banyak situs menyimpan AVIF karena lebih kecil. Windows Photos, WeChat, percetakan sering masih minta JPG.", "Chrome y muchos sitios guardan AVIF porque pesa menos. Windows Fotos, WeChat y las imprentas suelen pedir JPG."),
            "s2t": L("Open convert in a current browser", "用较新的浏览器打开格式转换", "用較新的瀏覽器打開格式轉換", "新しいブラウザで変換を開く", "최신 브라우저에서 변환 열기", "Mở chuyển đổi trong trình duyệt mới", "Buka konversi di peramban baru", "Abra convertir en un navegador actual"),
            "s2b": L("Chrome, Edge, or recent Safari. If the preview is blank, switch browser — do not keep dropping the same file.", "Chrome、Edge 或较新的 Safari。预览空白就换浏览器，不要反复拖同一份。", "Chrome、Edge 或較新的 Safari。預覽空白就換瀏覽器，不要反覆拖同一份。", "Chrome、Edge、新しいSafari。プレビューが空なら乗り換える。同じファイルを何度も入れない。", "Chrome, Edge, 최신 Safari. 미리보기가 비면 브라우저를 바꾸세요. 같은 파일을 반복해 넣지 마세요.", "Chrome, Edge hoặc Safari mới. Xem trước trống thì đổi trình duyệt — đừng thả mãi cùng một file.", "Chrome, Edge, atau Safari baru. Pratinjau kosong: ganti peramban. Jangan taruh file yang sama berulang.", "Chrome, Edge o Safari reciente. Si la vista está en blanco, cambie de navegador; no suelte el mismo archivo una y otra vez."),
            "s3t": L("Drop the .avif file", "拖入 .avif", "拖入 .avif", ".avifをドロップ", ".avif 넣기", "Thả file .avif", "Letakkan .avif", "Suelte el .avif"),
            "s3b": L("One file or a batch. Convert a copy; keep the AVIF if you still archive it.", "一张或一批。转的是副本；还要存档就留着 AVIF。", "一張或一批。轉的是副本；還要存檔就留著 AVIF。", "1枚でもまとめてでも。コピーを変換。アーカイブするならAVIFを残す。", "한 장 또는 여러 장. 복사본을 변환합니다. 보관하려면 AVIF를 남기세요.", "Một hoặc nhiều. Đổi bản sao; còn lưu trữ thì giữ AVIF.", "Satu atau batch. Ubah salinan; jika masih arsip, simpan AVIF.", "Uno o varios. Convierta una copia; conserve el AVIF si aún lo archiva."),
            "s4t": L("Pick JPG", "选 JPG", "選 JPG", "JPGを選ぶ", "JPG 고르기", "Chọn JPG", "Pilih JPG", "Elija JPG"),
            "s4b": L("Start near 0.9 quality. Optional max edge only if a form has a pixel cap. Pick PNG only if you need a lossless copy, not for chat.", "质量先从 0.9。表单有像素上限再限制长边。要无损副本才选 PNG，聊天不要用 PNG。", "品質先從 0.9。表單有像素上限再限制長邊。要無損副本才選 PNG，聊天不要用 PNG。", "品質は0.9前後。画素上限があるときだけ長辺を制限。可逆コピーが要るときだけPNG。チャットには不向き。", "품질은 0.9 근처. 서류에 픽셀 한도가 있을 때만 긴 변을 제한하세요. 무손실 복사본이 필요할 때만 PNG. 채팅에는 PNG를 쓰지 마세요.", "Chất lượng khoảng 0.9. Chỉ giới hạn cạnh dài nếu form có trần pixel. PNG chỉ khi cần bản không mất nét, đừng dùng cho chat.", "Kualitas sekitar 0.9. Batasi sisi hanya jika formulir punya batas piksel. PNG hanya untuk salinan lossless, bukan chat.", "Calidad cerca de 0.9. Limite el lado largo solo si hay tope de píxeles. PNG solo si necesita una copia sin pérdida, no para el chat."),
            "s5t": L("Download the JPG", "下载 JPG", "下載 JPG", "JPGを保存", "JPG 받기", "Tải JPG", "Unduh JPG", "Descargue el JPG"),
            "s5b": L("Keep the AVIF until you have opened the JPG.", "打开 JPG 之前留着 AVIF。", "打開 JPG 之前留著 AVIF。", "JPGを開くまでAVIFを残す。", "JPG를 열 때까지 AVIF를 남기세요.", "Giữ AVIF đến khi đã mở JPG.", "Simpan AVIF sampai JPG terbuka.", "Conserve el AVIF hasta haber abierto el JPG."),
            "s6t": L("Open the JPG where AVIF failed", "在打不开 AVIF 的地方打开 JPG", "在打不開 AVIF 的地方打開 JPG", "AVIFがダメだった先でJPGを開く", "AVIF가 실패한 곳에서 JPG 열기", "Mở JPG đúng chỗ AVIF fail", "Buka JPG di tempat AVIF gagal", "Abra el JPG donde falló el AVIF"),
            "s6b": L("If it still fails, you sent the AVIF by mistake. Converting does not add sharpness.", "还是打不开，多半发错成 AVIF。转换不会让图更清晰。", "還是打不開，多半傳錯成 AVIF。轉換不會讓圖更清晰。", "まだダメならAVIFを送っている。変換してもSharpにはならない。", "여전히 안 열리면 AVIF를 보낸 것입니다. 변환한다고 더 선명해지지 않습니다.", "Vẫn fail thì bạn gửi nhầm AVIF. Đổi định dạng không làm nét hơn.", "Masih gagal: Anda kirim AVIF. Konversi tidak menambah ketajaman.", "Si sigue fallando, envió el AVIF. Convertir no añade nitidez."),
            "diagram1": L("AVIF is smaller. JPG opens on older Windows, print, and chat.", "AVIF 更小。JPG 在老 Windows、打印店和聊天里打得开。", "AVIF 更小。JPG 在老 Windows、列印店和聊天裡打得開。", "AVIFは小さい。JPGは古いWindows、印刷、チャットで開く。", "AVIF는 더 작고 JPG는 옛 Windows, 인쇄, 채팅에서 열립니다.", "AVIF nhẹ hơn. JPG mở trên Windows cũ, in, chat.", "AVIF lebih kecil. JPG terbuka di Windows lama, cetak, chat.", "AVIF pesa menos. JPG abre en Windows viejo, imprenta y chat."),
            "diagram2": L("Drop AVIF, pick JPG, open the result on the destination that rejected AVIF.", "拖入 AVIF，选 JPG，到拒收 AVIF 的地方打开结果。", "拖入 AVIF，選 JPG，到拒收 AVIF 的地方打開結果。", "AVIFを入れJPGを選び、拒んだ先で開く。", "AVIF를 넣고 JPG를 고른 뒤 거부한 곳에서 여세요.", "Thả AVIF, chọn JPG, mở kết quả nơi từng từ chối AVIF.", "Letakkan AVIF, pilih JPG, buka di tujuan yang menolak AVIF.", "Suelte el AVIF, elija JPG y ábralo donde lo rechazaron."),
        },
        {
            "q1": L("Can I convert AVIF to JPG free online?", "可以免费在线把 AVIF 转成 JPG 吗？", "可以免費線上把 AVIF 轉成 JPG 嗎？", "AVIFをJPGに無料で変換できる？", "AVIF를 JPG로 무료 변환할 수 있나요?", "Đổi AVIF sang JPG miễn phí online được không?", "Bisa ubah AVIF ke JPG gratis online?", "¿Puedo pasar AVIF a JPG gratis en línea?"),
            "a1": L("Yes. cv.cm converts in this tab. Nothing is uploaded.", "可以。cv.cm 在当前标签页转换，不上传。", "可以。cv.cm 在目前分頁轉換，不上傳。", "できる。このタブで変換。アップロードなし。", "됩니다. 이 탭에서 변환합니다. 업로드 없음.", "Được. cv.cm đổi trong tab này, không tải lên.", "Ya. cv.cm mengubah di tab ini. Tidak diunggah.", "Sí. cv.cm convierte en esta pestaña. Nada se sube."),
            "q2": L("Why did Chrome save an AVIF?", "为什么 Chrome 存成了 AVIF？", "為什麼 Chrome 存成了 AVIF？", "ChromeがAVIFを保存するのはなぜ？", "Chrome이 AVIF를 저장하는 이유는?", "Vì sao Chrome lưu AVIF?", "Kenapa Chrome menyimpan AVIF?", "¿Por qué Chrome guardó un AVIF?"),
            "a2": L("Many sites serve AVIF because it is smaller than JPG. Save as JPG here when the destination rejects AVIF.", "网站为了体积常用 AVIF。对方不认时，在这里另存 JPG。", "網站為了體積常用 AVIF。對方不認時，在這裡另存 JPG。", "サイトが小さいAVIFを出す。先が拒むならここでJPGにする。", "사이트가 용량 때문에 AVIF를 줍니다. 상대가 거부하면 여기서 JPG로 저장하세요.", "Nhiều site dùng AVIF vì nhẹ hơn JPG. Đích từ chối thì lưu JPG ở đây.", "Situs memakai AVIF karena lebih kecil. Jika ditolak, simpan JPG di sini.", "Muchos sitios sirven AVIF porque pesa menos. Si el destino lo rechaza, guárdelo como JPG aquí."),
            "q3": L("Why is the preview blank?", "为什么预览是空的？", "為什麼預覽是空的？", "プレビューが空なのはなぜ？", "미리보기가 빈 이유는?", "Sao xem trước trống?", "Kenapa pratinjau kosong?", "¿Por qué la vista está en blanco?"),
            "a3": L("This browser cannot decode AVIF. Switch to current Chrome, Edge, or Safari.", "这款浏览器解不了 AVIF。换成较新的 Chrome、Edge 或 Safari。", "這款瀏覽器解不了 AVIF。換成較新的 Chrome、Edge 或 Safari。", "このブラウザはAVIFを解けない。新しいChrome / Edge / Safariへ。", "이 브라우저는 AVIF를 열 수 없습니다. 최신 Chrome, Edge, Safari로 바꾸세요.", "Trình duyệt này không đọc được AVIF. Đổi sang Chrome, Edge hoặc Safari mới.", "Peramban ini gagal decode AVIF. Ganti ke Chrome, Edge, atau Safari baru.", "Este navegador no decodifica AVIF. Pase a Chrome, Edge o Safari actuales."),
            "q4": L("Are files uploaded?", "会上传吗？", "會上傳嗎？", "アップロードされる？", "업로드되나요?", "Có tải lên không?", "Apakah diunggah?", "¿Se suben los archivos?"),
            "a4": L("No. Closing the tab discards them.", "不会。关掉标签页就没了。", "不會。關掉分頁就沒了。", "しない。タブを閉じると消える。", "아니요. 탭을 닫으면 사라집니다.", "Không. Đóng tab là mất.", "Tidak. Tutup tab, hilang.", "No. Al cerrar la pestaña se pierden."),
            "q5": L("Can I convert several AVIF files at once?", "能一次转多张 AVIF 吗？", "能一次轉多張 AVIF 嗎？", "まとめて変換できる？", "여러 AVIF를 한 번에?", "Đổi nhiều AVIF một lúc?", "Beberapa AVIF sekaligus?", "¿Puedo convertir varios AVIF a la vez?"),
            "a5": L("Yes. Drop a batch and download each JPG, or a ZIP if the tool offers one.", "可以。拖入一批，逐张下载 JPG（有 ZIP 就下 ZIP）。", "可以。拖入一批，逐張下載 JPG（有 ZIP 就下 ZIP）。", "できる。まとめて入れてJPGを保存。ZIPがあればZIP。", "됩니다. 여러 장을 넣고 JPG를 받으세요. ZIP이 있으면 ZIP.", "Được. Thả một loạt rồi tải từng JPG, hoặc ZIP nếu có.", "Ya. Letakkan batch dan unduh tiap JPG, atau ZIP jika ada.", "Sí. Suelte un lote y descargue cada JPG, o un ZIP si el convertidor lo ofrece."),
        },
    ),
    "rotate-photo": lesson(
        {
            "name": L("How to rotate or flip a photo", "怎么旋转或翻转照片", "怎麼旋轉或翻轉照片", "写真の回転と反転", "사진 회전·뒤집기", "Cách xoay hoặc lật ảnh", "Cara putar atau balik foto", "Cómo rotar o voltear una foto"),
            "blurb": L("Turn 90° or 180°, or flip a mirror. Download, then open the file — not only the preview.", "转 90° 或 180°，或镜像翻转。下载后打开文件，不要只看预览。", "轉 90° 或 180°，或鏡像翻轉。下載後打開檔，不要只看預覽。", "90°か180°、または鏡反転。保存したファイルを開く。プレビューだけ見ない。", "90° 또는 180°로 돌리거나 거울처럼 뒤집으세요. 받은 파일을 여세요. 미리보기만 보지 마세요.", "Xoay 90° hoặc 180°, hoặc lật gương. Tải rồi mở file, đừng chỉ xem trước.", "Putar 90° atau 180°, atau balik cermin. Unduh lalu buka file, jangan hanya pratinjau.", "Gire 90° o 180°, o voltee en espejo. Descargue y abra el archivo, no solo la vista previa."),
            "title": L("How to rotate or flip a photo", "怎么旋转或翻转照片", "怎麼旋轉或翻轉照片", "写真を回転・反転する方法", "사진을 회전·뒤집는 법", "Cách xoay hoặc lật ảnh", "Cara putar atau balik foto", "Cómo rotar o voltear una foto"),
            "lead": L("Rotate turns the photo. Flip is a mirror. You will pick one, export a copy, and open that file so Windows or a form sees the pixels, not leftover EXIF.", "旋转是把照片转过来。翻转是镜子。选好一种，导出副本，再打开文件，让 Windows 或表单看到的是像素，而不是残留的方向信息。", "旋轉是把照片轉過來。翻轉是鏡子。選好一種，匯出副本，再打開檔，讓 Windows 或表單看到的是像素，而不是殘留的方向資訊。", "回転は向きを変える。反転は鏡。どちらか選び、コピーを書き出し、そのファイルを開く。Windowsや提出が見るのは画素でありEXIFの向きではない。", "회전은 사진을 돌립니다. 뒤집기는 거울입니다. 하나를 고른 뒤 복사본을 보내고 그 파일을 여세요. Windows나 서류가 보는 것은 픽셀이지 남은 EXIF가 아닙니다.", "Xoay là quay ảnh. Lật là gương. Chọn một, xuất bản sao, mở file đó để Windows hoặc form thấy pixel, không phải EXIF còn lại.", "Putar memutar foto. Balik adalah cermin. Pilih satu, ekspor salinan, buka file itu agar Windows atau formulir melihat piksel, bukan sisa EXIF.", "Rotar gira la foto. Voltear es un espejo. Elija uno, exporte una copia y ábrala para que Windows o el formulario vean los píxeles, no un EXIF suelto."),
            "result": L("A download that is upright (or mirrored on purpose), verified by opening the file, with the original still on disk.", "一份方向对（或故意镜像）的下载，打开文件核对过，原图还在。", "一份方向對（或故意鏡像）的下載，打開檔核對過，原圖還在。", "正しい向き（または意図した鏡）の保存ファイル。開いて確認。原版は残る。", "올바른 방향(또는 의도한 거울)의 받은 파일. 열어서 확인. 원본은 남습니다.", "File tải đúng hướng (hoặc gương cố ý), đã mở kiểm, bản gốc còn.", "Unduhan yang tegak (atau cermin sengaja), sudah dibuka, asli tetap ada.", "Una descarga derecha (o en espejo a propósito), comprobada al abrir el archivo, con el original en el disco."),
            "note": L("Open rotate when the photo is on disk. 90° chips for phone shots; flip for a mirror selfie. Export writes pixels, so a sideways EXIF photo can become actually upright. Nothing is uploaded.", "照片在磁盘上再打开旋转。手机照用 90° 按钮；镜像自拍用翻转。导出会把方向写进像素，资源管理器里看起来横的图可以真正立正。不上传。", "照片在磁碟上再打開旋轉。手機照用 90° 按鈕；鏡像自拍用翻轉。匯出會把方向寫進像素，檔案總管裡看起來橫的圖可以真正立正。不上傳。", "写真が手元にあってから回転を開く。スマホは90°ボタン。鏡セルフィーは反転。書き出しは画素に向きを焼くので、横に見えるEXIF写真を本当に正立にできる。アップロードなし。", "사진이 디스크에 있으면 회전을 여세요. 폰 사진은 90° 버튼, 거울 셀카는 뒤집기. 보내면 픽셀에 방향이 들어가, 탐색기에서 가로로 보이던 사진이 실제로 바로 섭니다. 업로드 없음.", "Có ảnh trên đĩa thì mở xoay. Ảnh điện thoại dùng nút 90°; selfie gương dùng lật. Xuất ghi hướng vào pixel, ảnh EXIF nằm ngang có thể đứng thật. Không tải lên.", "Foto di disk, baru buka putar. Foto ponsel: tombol 90°; selfie cermin: balik. Ekspor menulis piksel, foto EXIF miring bisa benar-benar tegak. Tidak diunggah.", "Abra rotar con la foto en el disco. Fotos del teléfono: chips de 90°; selfie en espejo: voltear. Exportar escribe los píxeles, así una foto EXIF de lado puede quedar derecha de verdad. Nada se sube."),
            "s1t": L("Decide 90° / 180° versus a mirror flip", "先分清是转 90°/180° 还是镜像翻转", "先分清是轉 90°/180° 還是鏡像翻轉", "90°/180°か鏡反転か", "90°/180°인지 거울 뒤집기인지", "Quyết 90°/180° hay lật gương", "Tentukan 90°/180° atau balik cermin", "Decida 90° / 180° frente a un volteo en espejo"),
            "s1b": L("A sideways phone photo needs 90° left or right. Upside down needs 180°. Text that reads backward needs a horizontal flip, not a rotation.", "手机横过来的，用向左或向右 90°。上下颠倒用 180°。字是反的，要水平翻转，不是旋转。", "手機橫過來的，用向左或向右 90°。上下顛倒用 180°。字是反的，要水平翻轉，不是旋轉。", "横のスマホ写真は左右90°。逆さは180°。文字が逆なら回転ではなく左右反転。", "옆으로 누운 폰 사진은 왼쪽 또는 오른쪽 90°. 거꾸로면 180°. 글자가 거꾸로면 회전이 아니라 좌우 뒤집기.", "Ảnh điện thoại nằm ngang cần 90° trái hoặc phải. Ngược đầu cần 180°. Chữ đọc ngược cần lật ngang, không phải xoay.", "Foto ponsel miring: 90° kiri atau kanan. Terbalik: 180°. Teks kebalik: flip horizontal, bukan putar.", "Una foto de lado necesita 90° izquierda o derecha. Boca abajo, 180°. Si el texto se lee al revés, volteo horizontal, no rotación."),
            "s2t": L("Open rotate on cv.cm", "打开 cv.cm 的旋转", "打開 cv.cm 的旋轉", "cv.cmの回転を開く", "cv.cm 회전을 열기", "Mở xoay trên cv.cm", "Buka putar di cv.cm", "Abra rotar en cv.cm"),
            "s2b": L("Work stays in this tab. Closing it discards the photo.", "处理留在当前标签页。关掉就没了。", "處理留在目前分頁。關掉就沒了。", "このタブで処理。閉じると消える。", "이 탭에서 처리합니다. 닫으면 사라집니다.", "Xử lý trong tab này. Đóng là mất.", "Proses di tab ini. Tutup, hilang.", "El trabajo queda en esta pestaña. Al cerrarla se pierde."),
            "s3t": L("Drop the photo", "拖入照片", "拖入照片", "写真をドロップ", "사진을 넣기", "Thả ảnh", "Letakkan foto", "Suelte la foto"),
            "s3b": L("If the preview is blank, convert HEIC or AVIF to JPG first, then come back. The preview already applies EXIF orientation.", "预览空白，先把 HEIC 或 AVIF 转成 JPG 再回来。预览已经按方向信息摆正过。", "預覽空白，先把 HEIC 或 AVIF 轉成 JPG 再回來。預覽已經按方向資訊擺正過。", "プレビューが空なら先にHEIC/AVIFをJPGにして戻る。プレビューはEXIFの向きをすでに適用している。", "미리보기가 비면 HEIC 또는 AVIF를 JPG로 바꾼 뒤 돌아오세요. 미리보기는 이미 EXIF 방향을 적용합니다.", "Xem trước trống thì đổi HEIC hoặc AVIF sang JPG rồi quay lại. Xem trước đã áp hướng EXIF.", "Pratinjau kosong: ubah HEIC atau AVIF ke JPG dulu. Pratinjau sudah menerapkan orientasi EXIF.", "Si la vista está en blanco, pase HEIC o AVIF a JPG y vuelva. La vista ya aplica la orientación EXIF."),
            "s4t": L("Use the 90° chips, or flip", "用 90° 按钮，或翻转", "用 90° 按鈕，或翻轉", "90°ボタン、または反転", "90° 버튼 또는 뒤집기", "Dùng nút 90°, hoặc lật", "Pakai tombol 90°, atau balik", "Use los chips de 90°, o voltee"),
            "s4b": L("Phone shots: 90° left, 90° right, or 180°. The angle slider is for a small tilt. Flip horizontal for a mirror selfie. Flip vertical only if the photo is truly upside-down in a mirror sense.", "手机照：向左 90°、向右 90° 或 180°。滑杆只适合微调倾斜。镜像自拍用水平翻转。垂直翻转只在真的上下镜像时用。", "手機照：向左 90°、向右 90° 或 180°。滑桿只適合微調傾斜。鏡像自拍用水平翻轉。垂直翻轉只在真的上下鏡像時用。", "スマホは左90°・右90°・180°。スライダーは小さな傾き用。鏡セルフィーは左右反転。上下反転は本当に鏡の上下のときだけ。", "폰 사진: 왼쪽 90°, 오른쪽 90°, 또는 180°. 슬라이더는 작은 기울기용. 거울 셀카는 좌우 뒤집기. 상하 뒤집기는 정말 상하 거울일 때만.", "Ảnh điện thoại: 90° trái, 90° phải, hoặc 180°. Thanh góc chỉ để nghiêng nhẹ. Selfie gương dùng lật ngang. Lật dọc chỉ khi đúng là gương trên-dưới.", "Foto ponsel: 90° kiri, 90° kanan, atau 180°. Slider sudut untuk miring kecil. Selfie cermin: flip horizontal. Flip vertikal hanya jika benar-benar cermin atas-bawah.", "Fotos del teléfono: 90° izquierda, 90° derecha o 180°. El deslizador es para un tilt pequeño. Selfie en espejo: volteo horizontal. Vertical solo si es un espejo de verdad de arriba abajo."),
            "s5t": L("Download PNG or JPG", "下载 PNG 或 JPG", "下載 PNG 或 JPG", "PNGかJPGを保存", "PNG 또는 JPG 받기", "Tải PNG hoặc JPG", "Unduh PNG atau JPG", "Descargue PNG o JPG"),
            "s5b": L("PNG if you need sharp type or a clear background. JPG for a smaller send. Keep the original until you have opened the download.", "字要利或要透明底就用 PNG。发出去要小就用 JPG。打开下载之前留着原图。", "字要利或要透明底就用 PNG。寄出去要小就用 JPG。打開下載之前留著原圖。", "文字をSharpに、または透明が要るならPNG。小さく送るならJPG。保存ファイルを開くまで原版を残す。", "글자를 선명히 하거나 투명이 필요하면 PNG. 작게 보내려면 JPG. 받은 파일을 열 때까지 원본을 남기세요.", "Chữ cần sắc hoặc nền trong thì PNG. Gửi nhẹ thì JPG. Giữ gốc đến khi đã mở file tải.", "Teks tajam atau latar tembus: PNG. Kirim lebih kecil: JPG. Simpan asli sampai unduhan terbuka.", "PNG si necesita tipo nítido o fondo transparente. JPG para enviar menos peso. Conserve el original hasta abrir la descarga."),
            "s6t": L("Open the downloaded file", "打开下载的文件", "打開下載的檔", "保存したファイルを開く", "받은 파일을 열기", "Mở file đã tải", "Buka file unduhan", "Abra el archivo descargado"),
            "s6b": L("Do not trust the in-page preview alone. If Explorer still shows it sideways, you sent the original. If letters are backward, you flipped when you needed 90°.", "不要只信页面预览。资源管理器里还是横的，就是发了原图。字是反的，就是该转 90° 却用了翻转。", "不要只信頁面預覽。檔案總管裡還是橫的，就是傳了原圖。字是反的，就是該轉 90° 卻用了翻轉。", "ページ内プレビューだけで送らない。エクスプローラーでまだ横なら原版を送っている。文字が逆なら90°ではなく反転した。", "페이지 미리보기만 믿지 마세요. 탐색기에서 아직 가로면 원본을 보낸 것입니다. 글자가 거꾸로면 90°가 아니라 뒤집기를 쓴 것입니다.", "Đừng chỉ tin xem trước trong trang. Explorer vẫn nằm ngang thì bạn gửi bản gốc. Chữ ngược thì bạn lật khi đáng lẽ xoay 90°.", "Jangan percaya pratinjau halaman saja. Explorer masih miring: Anda kirim asli. Huruf terbalik: Anda membalik padahal perlu 90°.", "No confíe solo en la vista previa. Si el Explorador aún la muestra de lado, envió el original. Si las letras van al revés, volteó cuando debía girar 90°."),
            "diagram1": L("Rotate 90° / 180° turns the photo. Flip is a mirror.", "旋转 90°/180° 是转向。翻转是镜子。", "旋轉 90°/180° 是轉向。翻轉是鏡子。", "90°/180°は向き。反転は鏡。", "90°/180°는 방향을 돌림. 뒤집기는 거울.", "Xoay 90°/180° là quay. Lật là gương.", "Putar 90°/180° memutar. Balik adalah cermin.", "Rotar 90° / 180° gira. Voltear es un espejo."),
            "diagram2": L("Export writes pixels. Open the file so EXIF-only sideways photos become actually upright.", "导出会把方向写进像素。打开文件，只有方向信息是横的图才能真正立正。", "匯出會把方向寫進像素。打開檔，只有方向資訊是橫的圖才能真正立正。", "書き出しは画素に向きを焼く。ファイルを開けば、EXIFだけ横の写真が本当に正立する。", "보내면 픽셀에 방향이 들어갑니다. 파일을 열면 EXIF만 가로였던 사진이 실제로 바로 섭니다.", "Xuất ghi hướng vào pixel. Mở file để ảnh chỉ lệch vì EXIF đứng thật.", "Ekspor menulis piksel. Buka file agar foto yang miring hanya karena EXIF benar-benar tegak.", "Exportar escribe los píxeles. Abra el archivo para que una foto de lado solo por EXIF quede derecha."),
        },
        {
            "q1": L("Can I rotate a photo free online?", "可以免费在线旋转照片吗？", "可以免費線上旋轉照片嗎？", "写真を無料で回転できる？", "사진을 무료로 회전할 수 있나요?", "Xoay ảnh miễn phí online được không?", "Bisa putar foto gratis online?", "¿Puedo rotar una foto gratis en línea?"),
            "a1": L("Yes. cv.cm rotates in this tab. Nothing is uploaded.", "可以。cv.cm 在当前标签页旋转，不上传。", "可以。cv.cm 在目前分頁旋轉，不上傳。", "できる。このタブで回転。アップロードなし。", "됩니다. 이 탭에서 회전합니다. 업로드 없음.", "Được. cv.cm xoay trong tab này, không tải lên.", "Ya. cv.cm memutar di tab ini. Tidak diunggah.", "Sí. cv.cm rota en esta pestaña. Nada se sube."),
            "q2": L("What is the difference between rotate and flip?", "旋转和翻转有什么差别？", "旋轉和翻轉有什麼差別？", "回転と反転の違いは？", "회전과 뒤집기의 차이는?", "Xoay khác lật thế nào?", "Beda putar dan balik?", "¿Qué diferencia hay entre rotar y voltear?"),
            "a2": L("Rotate turns the whole photo. Flip mirrors it. Use 90° for a sideways phone shot; use flip if letters read backward.", "旋转是把整张图转过来。翻转是镜子。手机横拍用 90°；字是反的才翻转。", "旋轉是把整張圖轉過來。翻轉是鏡子。手機橫拍用 90°；字是反的才翻轉。", "回転は全体の向き。反転は鏡。横のスマホは90°。文字が逆なら反転。", "회전은 사진 전체를 돌립니다. 뒤집기는 거울입니다. 옆으로 찍은 폰 사진은 90°, 글자가 거꾸로면 뒤집기.", "Xoay quay cả tấm. Lật là gương. Ảnh điện thoại nằm ngang dùng 90°; chữ đọc ngược mới lật.", "Putar memutar seluruh foto. Balik mencerminkan. Foto ponsel miring: 90°; huruf kebalik: flip.", "Rotar gira la foto entera. Voltear la refleja. Use 90° para una foto de lado; voltear si las letras se leen al revés."),
            "q3": L("Why does Windows still show my iPhone photo sideways?", "为什么 Windows 里 iPhone 照片还是横的？", "為什麼 Windows 裡 iPhone 照片還是橫的？", "WindowsでiPhone写真が横のままなのはなぜ？", "윈도우에서 아이폰 사진이 가로인 이유는?", "Sao Windows vẫn hiện ảnh iPhone nằm ngang?", "Kenapa Windows masih menampilkan foto iPhone miring?", "¿Por qué Windows sigue mostrando la foto del iPhone de lado?"),
            "a3": L("The original may only store rotation in EXIF. Export from this tab writes the pixels upright. Open the download, not the original.", "原图可能只把方向写在 EXIF 里。从本页导出才会把像素摆正。打开的是下载，不是原图。", "原圖可能只把方向寫在 EXIF 裡。從本頁匯出才會把像素擺正。打開的是下載，不是原圖。", "元は向きをEXIFにだけ持っていることがある。ここで書き出すと画素が正立する。開くのは保存ファイルであり原版ではない。", "원본은 방향이 EXIF에만 있을 수 있습니다. 이 탭에서 보내면 픽셀이 바로 섭니다. 원본이 아니라 받은 파일을 여세요.", "Bản gốc có thể chỉ ghi hướng trong EXIF. Xuất từ tab này mới ghi pixel đứng. Mở file tải, không phải bản gốc.", "Asli mungkin hanya menyimpan rotasi di EXIF. Ekspor dari tab ini menulis piksel tegak. Buka unduhan, bukan aslinya.", "El original puede guardar el giro solo en EXIF. Exportar aquí escribe los píxeles derechos. Abra la descarga, no el original."),
            "q4": L("Are photos uploaded?", "会上传吗？", "會上傳嗎？", "アップロードされる？", "업로드되나요?", "Có tải lên không?", "Apakah diunggah?", "¿Se suben las fotos?"),
            "a4": L("No. Closing the tab discards them.", "不会。关掉标签页就没了。", "不會。關掉分頁就沒了。", "しない。タブを閉じると消える。", "아니요. 탭을 닫으면 사라집니다.", "Không. Đóng tab là mất.", "Tidak. Tutup tab, hilang.", "No. Al cerrar la pestaña se pierden."),
            "q5": L("Can I rotate without Photoshop?", "不用 Photoshop 能转吗？", "不用 Photoshop 能轉嗎？", "Photoshopなしで？", "포토샵 없이?", "Không cần Photoshop?", "Tanpa Photoshop?", "¿Sin Photoshop?"),
            "a5": L("Yes. This page is the rotator. No account.", "可以。本页就是旋转。不用账号。", "可以。本頁就是旋轉。不用帳號。", "できる。このページが回転。アカウント不要。", "됩니다. 이 페이지가 회전기입니다. 계정 없음.", "Được. Trang này là xoay. Không tài khoản.", "Ya. Halaman ini pemutarnya. Tanpa akun.", "Sí. Esta página es el rotador. Sin cuenta."),
        },
    ),
}

META = {
    "titlePngToJpg": L("How to convert PNG to JPG | cv.cm", "怎么把 PNG 转成 JPG | cv.cm", "怎麼把 PNG 轉成 JPG | cv.cm", "PNGをJPGにする方法 | cv.cm", "PNG를 JPG로 변환하는 법 | cv.cm", "Cách đổi PNG sang JPG | cv.cm", "Cara ubah PNG ke JPG | cv.cm", "Cómo pasar PNG a JPG | cv.cm"),
    "descPngToJpg": L("Pick JPG for a smaller photo. A clear PNG background becomes a solid matte, often black. Download, then compare size. Nothing is uploaded.", "要更小的照片就选 JPG。透明 PNG 会变成实色，常常是黑底。下载后再比体积。不上传。", "要更小的照片就選 JPG。透明 PNG 會變成實色，常常是黑底。下載後再比體積。不上傳。", "小さくするならJPG。透明PNGは塗りつぶされ、多くは黒。保存してサイズを比べる。アップロードなし。", "더 작은 사진이면 JPG. 투명 PNG는 단색(종종 검정)이 됩니다. 받은 뒤 용량을 비교하세요. 업로드 없음.", "Muốn ảnh nhẹ thì chọn JPG. Nền PNG trong thành đặc, thường đen. Tải rồi so dung lượng. Không tải lên.", "Foto lebih kecil: pilih JPG. Latar PNG tembus jadi solid, sering hitam. Unduh, bandingkan ukuran. Tidak diunggah.", "Elija JPG para menos peso. El fondo PNG transparente se rellena, a menudo de negro. Descargue y compare el tamaño. Nada se sube."),
    "titleJpgToPng": L("How to convert JPG to PNG | cv.cm", "怎么把 JPG 转成 PNG | cv.cm", "怎麼把 JPG 轉成 PNG | cv.cm", "JPGをPNGにする方法 | cv.cm", "JPG를 PNG로 변환하는 법 | cv.cm", "Cách đổi JPG sang PNG | cv.cm", "Cara ubah JPG ke PNG | cv.cm", "Cómo pasar JPG a PNG | cv.cm"),
    "descJpgToPng": L("Pick PNG for lossless edits or a form that wants PNG. It will not invent transparency. The file usually gets larger. Nothing is uploaded.", "要无损再编辑或表单只要 PNG，就转 PNG。它不会抠透明。文件通常会变大。不上传。", "要無損再編輯或表單只要 PNG，就轉 PNG。它不會摳透明。檔通常會變大。不上傳。", "可逆編集やPNG指定の提出ならPNGへ。透明にはならない。ファイルはたいてい大きくなる。アップロードなし。", "무손실 편집이나 PNG를 원하는 서류면 PNG로. 투명이 생기지는 않습니다. 파일은 보통 커집니다. 업로드 없음.", "Cần sửa không mất nét hoặc form bắt PNG thì đổi PNG. Không tạo nền trong. File thường nặng hơn. Không tải lên.", "Sunting lossless atau formulir minta PNG: ubah ke PNG. Tidak membuat transparansi. File biasanya lebih besar. Tidak diunggah.", "Pase a PNG para editar sin pérdida o si el formulario lo pide. No inventa transparencia. Suele pesar más. Nada se sube."),
    "titleAvifToJpg": L("How to convert AVIF to JPG | cv.cm", "怎么把 AVIF 转成 JPG | cv.cm", "怎麼把 AVIF 轉成 JPG | cv.cm", "AVIFをJPGにする方法 | cv.cm", "AVIF를 JPG로 변환하는 법 | cv.cm", "Cách đổi AVIF sang JPG | cv.cm", "Cara ubah AVIF ke JPG | cv.cm", "Cómo pasar AVIF a JPG | cv.cm"),
    "descAvifToJpg": L("Chrome often saves AVIF. Export JPG in a current browser, then open it where AVIF was rejected. Nothing is uploaded.", "Chrome 常存 AVIF。用较新的浏览器导出 JPG，再到打不开 AVIF 的地方打开。不上传。", "Chrome 常存 AVIF。用較新的瀏覽器匯出 JPG，再到打不開 AVIF 的地方打開。不上傳。", "ChromeはAVIFを保存しがち。新しいブラウザでJPGを書き出し、拒んだ先で開く。アップロードなし。", "Chrome은 AVIF를 자주 저장합니다. 최신 브라우저에서 JPG로 보낸 뒤 거부한 곳에서 여세요. 업로드 없음.", "Chrome hay lưu AVIF. Xuất JPG trong trình duyệt mới, mở nơi từng từ chối AVIF. Không tải lên.", "Chrome sering simpan AVIF. Ekspor JPG di peramban baru, buka di tempat yang menolak AVIF. Tidak diunggah.", "Chrome suele guardar AVIF. Exporte JPG en un navegador actual y ábralo donde lo rechazaron. Nada se sube."),
    "titleRotatePhoto": L("How to rotate or flip a photo | cv.cm", "怎么旋转或翻转照片 | cv.cm", "怎麼旋轉或翻轉照片 | cv.cm", "写真を回転・反転する方法 | cv.cm", "사진을 회전·뒤집는 법 | cv.cm", "Cách xoay hoặc lật ảnh | cv.cm", "Cara putar atau balik foto | cv.cm", "Cómo rotar o voltear una foto | cv.cm"),
    "descRotatePhoto": L("Turn 90° or 180°, or flip a mirror. Export writes pixels so a sideways EXIF photo can become actually upright. Nothing is uploaded.", "转 90° 或 180°，或镜像翻转。导出会把方向写进像素，横的 EXIF 照片可以真正立正。不上传。", "轉 90° 或 180°，或鏡像翻轉。匯出會把方向寫進像素，橫的 EXIF 照片可以真正立正。不上傳。", "90°か180°、または鏡反転。書き出しは画素に向きを焼くので、横のEXIF写真を正立にできる。アップロードなし。", "90° 또는 180°로 돌리거나 거울처럼 뒤집으세요. 보내면 픽셀에 방향이 들어가 가로 EXIF 사진이 바로 섭니다. 업로드 없음.", "Xoay 90° hoặc 180°, hoặc lật gương. Xuất ghi hướng vào pixel, ảnh EXIF nằm ngang có thể đứng thật. Không tải lên.", "Putar 90° atau 180°, atau balik cermin. Ekspor menulis piksel, foto EXIF miring bisa tegak. Tidak diunggah.", "Gire 90° o 180°, o voltee en espejo. Exportar escribe los píxeles para que una foto EXIF de lado quede derecha. Nada se sube."),
}


def inject() -> None:
    for loc, path in FILES.items():
        data = json.loads(path.read_text())
        data["faq"].setdefault("learn", {})
        for lesson_id, payload in LESSONS.items():
            data["learn"][lesson_id] = payload["copy"][loc]
            data["faq"]["learn"][lesson_id] = payload["faq"][loc]
        for key, by_loc in META.items():
            data["meta"][key] = by_loc[loc]
        path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n")
        print("patched", path.name, list(LESSONS))


if __name__ == "__main__":
    inject()
