#!/usr/bin/env python3
"""Inject collage / meme / word-count / trim-audio how-tos."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LOCS = ["en", "zh-CN", "zh-TW", "ja", "ko", "vi", "id", "es"]
FILES = {loc: ROOT / "src/locales" / f"{loc}.json" for loc in LOCS}


def L(*vals: str) -> dict[str, str]:
    if len(vals) != 8:
        raise ValueError(len(vals), vals[0] if vals else None)
    return dict(zip(LOCS, vals))


def lesson(fields: dict[str, dict[str, str]], faq: dict[str, dict[str, str]]) -> dict:
    return {
        "copy": {loc: {k: v[loc] for k, v in fields.items()} for loc in LOCS},
        "faq": {loc: {k: v[loc] for k, v in faq.items()} for loc in LOCS},
    }


LESSONS = {
    "make-collage": lesson(
        {
            "name": L("How to make a photo collage", "怎么做照片拼图", "怎麼做照片拼圖", "写真コラージュの作り方", "사진 콜라주 만드는 법", "Cách làm ảnh ghép", "Cara buat kolase foto", "Cómo hacer un collage de fotos"),
            "blurb": L("Pick a grid, drop photos, choose contain vs cover, download, then check faces.", "先选宫格，放入照片，选完整放入还是铺满，下载后再看脸有没有被切。", "先選宮格，放入照片，選完整放入還是鋪滿，下載後再看臉有沒有被切。", "先にグリッド、写真を入れ、containかcoverか。保存して顔が切れてないか見る。", "격자를 고르고 사진을 넣은 뒤 맞춤/채움을 고르고, 받은 뒤 얼굴이 잘렸는지 보세요.", "Chọn lưới, thả ảnh, contain hay cover, tải, kiểm mặt.", "Pilih kisi, letakkan foto, contain vs cover, unduh, cek wajah.", "Elija la cuadrícula, suelte fotos, contain o cover, descargue y mire las caras."),
            "title": L("How to make a photo collage", "怎么做照片拼图", "怎麼做照片拼圖", "写真コラージュの作り方", "사진 콜라주 만드는 법", "Cách làm ảnh ghép", "Cara buat kolase foto", "Cómo hacer un collage de fotos"),
            "lead": L("A collage is a layout first, then photos. You will pick a grid and a size, drop pictures in order, and check that faces were not cropped by Cover.", "拼图先定格子，再放图。选宫格和尺寸，按顺序放入，再确认 Cover 没有切到脸。", "拼圖先定格子，再放圖。選宮格和尺寸，按順序放入，再確認 Cover 沒有切到臉。", "コラージュは先にレイアウト。グリッドとサイズを選び、順に入れて、Coverで顔が切れていないか見る。", "콜라주는 레이아웃이 먼저입니다. 격자와 크기를 고르고 순서대로 넣은 뒤 Cover가 얼굴을 자르지 않았는지 보세요.", "Collage là bố cục trước. Chọn lưới và kích thước, thả ảnh theo thứ tự, kiểm Cover không cắt mặt.", "Kolase itu layout dulu. Pilih kisi dan ukuran, letakkan berurutan, cek Cover tidak memotong wajah.", "Un collage es primero una plantilla. Elija cuadrícula y tamaño, suelte en orden y compruebe que Cover no recortó caras."),
            "result": L("One image with the photos in the right cells, faces intact, sized for the place you will post.", "一张拼图：格子对、脸还在、尺寸对得上要发的地方。", "一張拼圖：格子對、臉還在、尺寸對得上要發的地方。", "セルが正しく、顔が残り、投稿先のサイズに合う1枚。", "칸이 맞고 얼굴이 남고 올릴 곳에 맞는 한 장.", "Một ảnh: ô đúng, mặt còn, đúng cỡ chỗ đăng.", "Satu gambar: sel benar, wajah utuh, ukuran sesuai tempat posting.", "Una imagen con las celdas bien, caras enteras y el tamaño del sitio donde la va a publicar."),
            "note": L("Open collage when the photos are on disk. Contain keeps the whole photo (bars). Cover fills the cell and may crop. Nothing is uploaded.", "照片在磁盘上再打开拼图。Contain 放下整张（会留边）。Cover 铺满格子，可能切到脸。不上传。", "照片在磁碟上再打開拼圖。Contain 放下整張（會留邊）。Cover 鋪滿格子，可能切到臉。不上傳。", "写真が手元にあってから開く。Containは全体（余白）。Coverはセルを埋め、顔を切ることがある。アップロードなし。", "사진이 디스크에 있으면 콜라주를 여세요. Contain은 전체를 넣고 여백이 생깁니다. Cover는 칸을 채우며 얼굴을 자를 수 있습니다. 업로드 없음.", "Có ảnh trên đĩa thì mở collage. Contain giữ cả ảnh (có lề). Cover lấp ô, có thể cắt mặt. Không tải lên.", "Foto di disk, baru buka kolase. Contain menjaga seluruh foto (ada bar). Cover mengisi sel, bisa memotong wajah. Tidak diunggah.", "Abra collage con las fotos en el disco. Contain deja la foto entera (bandas). Cover llena la celda y puede recortar. Nada se sube."),
            "s1t": L("Pick the grid and the size first", "先选宫格和尺寸", "先選宮格和尺寸", "先にグリッドとサイズ", "격자와 크기를 먼저", "Chọn lưới và cỡ trước", "Pilih kisi dan ukuran dulu", "Elija primero la cuadrícula y el tamaño"),
            "s1b": L("2×2 or 3×3 for a set. Square for a feed, 4:5 portrait, 9:16 stories, 16:9 cover. Changing size later re-crops every cell.", "一组图用 2×2 或 3×3。信息流正方形，竖图 4:5，故事 9:16，封面 16:9。后改尺寸会重切每一格。", "一組圖用 2×2 或 3×3。資訊流正方形，直圖 4:5，限時動態 9:16，封面 16:9。後改尺寸會重切每一格。", "セットは2×2や3×3。フィードは正方形、縦4:5、ストーリー9:16、カバー16:9。後からサイズを変えると全セルが再クロップ。", "세트는 2×2 또는 3×3. 피드는 정사각, 세로는 4:5, 스토리는 9:16, 커버는 16:9. 나중에 크기를 바꾸면 모든 칸이 다시 잘립니다.", "Bộ ảnh dùng 2×2 hoặc 3×3. Feed vuông, dọc 4:5, story 9:16, bìa 16:9. Đổi cỡ sau sẽ cắt lại mọi ô.", "Set: 2×2 atau 3×3. Feed persegi, 4:5 potret, 9:16 cerita, 16:9 sampul. Ubah ukuran nanti: semua sel dipotong ulang.", "Un set: 2×2 o 3×3. Feed cuadrado, 4:5 vertical, 9:16 stories, 16:9 portada. Cambiar el tamaño después recorta cada celda."),
            "s2t": L("Open collage on cv.cm", "打开 cv.cm 的拼图", "打開 cv.cm 的拼圖", "cv.cmのコラージュを開く", "cv.cm 콜라주를 열기", "Mở collage trên cv.cm", "Buka kolase di cv.cm", "Abra collage en cv.cm"),
            "s2b": L("Work stays in this tab. Nothing is uploaded.", "拼图留在当前标签页。不上传。", "拼圖留在目前分頁。不上傳。", "このタブで処理。アップロードなし。", "이 탭에서 만듭니다. 업로드 없음.", "Làm trong tab này. Không tải lên.", "Proses di tab ini. Tidak diunggah.", "El trabajo queda en esta pestaña. Nada se sube."),
            "s3t": L("Drop photos in the order they should appear", "按出现顺序拖入照片", "按出現順序拖入照片", "出したい順にドロップ", "나올 순서대로 사진을 넣기", "Thả ảnh theo thứ tự xuất hiện", "Letakkan foto berurutan", "Suelte las fotos en el orden de aparición"),
            "s3b": L("First file is the first cell. Reorder before you export if the grid looks wrong.", "第一张就是第一格。格子不对先改顺序再导出。", "第一張就是第一格。格子不對先改順序再匯出。", "先頭が最初のセル。違うなら並べ替えてから書き出す。", "첫 파일이 첫 칸입니다. 격자가 이상하면 보낸 전에 순서를 바꾸세요.", "File đầu là ô đầu. Sai thì sắp lại rồi mới xuất.", "File pertama = sel pertama. Salah: urutkan dulu baru ekspor.", "El primer archivo es la primera celda. Si el grid falla, reordene antes de exportar."),
            "s4t": L("Choose Contain or Cover", "选 Contain 还是 Cover", "選 Contain 還是 Cover", "ContainかCoverか", "Contain 또는 Cover", "Chọn Contain hay Cover", "Pilih Contain atau Cover", "Elija Contain o Cover"),
            "s4b": L("Contain keeps the whole photo and may add bars. Cover fills the cell and can cut a forehead or a chin. For faces, start with Contain.", "Contain 放下整张，可能留边。Cover 铺满格子，可能切到额或下巴。有人脸先用 Contain。", "Contain 放下整張，可能留邊。Cover 鋪滿格子，可能切到額或下巴。有人臉先用 Contain。", "Containは全体（余白あり）。Coverはセルを埋め額や顎を切ることがある。顔があるならContainから。", "Contain은 전체를 넣고 여백이 생길 수 있습니다. Cover는 칸을 채우며 이마나 턱을 자를 수 있습니다. 얼굴이면 Contain부터.", "Contain giữ cả ảnh, có thể có lề. Cover lấp ô, có thể cắt trán hoặc cằm. Có mặt thì bắt đầu Contain.", "Contain menjaga seluruh foto, bisa ada bar. Cover mengisi sel, bisa memotong dahi atau dagu. Ada wajah: mulai Contain.", "Contain deja la foto entera y puede dejar bandas. Cover llena la celda y puede cortar frente o barbilla. Con caras, empiece por Contain."),
            "s5t": L("Download PNG or JPEG", "下载 PNG 或 JPEG", "下載 PNG 或 JPEG", "PNGかJPEGを保存", "PNG 또는 JPEG 받기", "Tải PNG hoặc JPEG", "Unduh PNG atau JPEG", "Descargue PNG o JPEG"),
            "s5b": L("PNG for sharp edges. JPEG for a smaller feed upload.", "边缘要利用 PNG。上信息流要小就用 JPEG。", "邊緣要利用 PNG。上資訊流要小就用 JPEG。", "端をSharpにするならPNG。フィードを軽くするならJPEG。", "가장자리를 선명히: PNG. 피드 용량: JPEG.", "Mép sắc dùng PNG. Feed nhẹ dùng JPEG.", "Tepi tajam: PNG. Feed lebih kecil: JPEG.", "PNG para bordes nítidos. JPEG para un feed más liviano."),
            "s6t": L("Open at 100% and walk the cells", "用 100% 打开，逐格看", "用 100% 打開，逐格看", "100%で開きセルを歩く", "100%로 열고 칸을 보기", "Mở 100% và đi từng ô", "Buka 100% dan cek tiap sel", "Ábralo al 100% y recorra las celdas"),
            "s6b": L("If a face is cut, switch that cell to Contain or pick a different photo. If the order is wrong, reorder and export again. Keep the originals.", "脸被切了，就改 Contain 或换图。顺序错了，排好再导。原图留下。", "臉被切了，就改 Contain 或換圖。順序錯了，排好再導。原圖留下。", "顔が切れたらContainにするか写真を変える。順が違うなら並べ直して再書き出し。原版は残す。", "얼굴이 잘렸으면 Contain으로 바꾸거나 사진을 바꾸세요. 순서가 틀리면 다시 맞춰 보내세요. 원본은 남깁니다.", "Mặt bị cắt thì đổi Contain hoặc đổi ảnh. Sai thứ tự thì sắp lại rồi xuất. Giữ gốc.", "Wajah terpotong: ganti Contain atau foto. Urutan salah: urutkan, ekspor lagi. Simpan asli.", "Si una cara está cortada, pase a Contain o cambie la foto. Si el orden falla, reordene y exporte. Conserve los originales."),
            "diagram1": L("Layout first: 2×2, 3×3, square, 4:5, 9:16.", "先定格子：2×2、3×3、正方形、4:5、9:16。", "先定格子：2×2、3×3、正方形、4:5、9:16。", "先にレイアウト：2×2、3×3、正方形、4:5、9:16。", "레이아웃 먼저: 2×2, 3×3, 정사각, 4:5, 9:16.", "Bố cục trước: 2×2, 3×3, vuông, 4:5, 9:16.", "Layout dulu: 2×2, 3×3, persegi, 4:5, 9:16.", "Primero la plantilla: 2×2, 3×3, cuadrado, 4:5, 9:16."),
            "diagram2": L("Contain keeps the whole photo. Cover fills and may crop faces.", "Contain 放下整张。Cover 铺满，可能切脸。", "Contain 放下整張。Cover 鋪滿，可能切臉。", "Containは全体。Coverは埋めて顔を切ることがある。", "Contain은 전체. Cover는 채우며 얼굴을 자를 수 있습니다.", "Contain giữ cả ảnh. Cover lấp ô, có thể cắt mặt.", "Contain menjaga seluruh foto. Cover mengisi, bisa memotong wajah.", "Contain deja la foto entera. Cover llena y puede recortar caras."),
        },
        {
            "q1": L("Can I make a photo collage free online?", "可以免费在线做拼图吗？", "可以免費線上做拼圖嗎？", "無料でコラージュできる？", "무료로 콜라주 만들 수 있나요?", "Làm collage miễn phí online?", "Kolase gratis online?", "¿Puedo hacer un collage gratis en línea?"),
            "a1": L("Yes. cv.cm runs in this tab. Nothing is uploaded.", "可以。cv.cm 在当前标签页做，不上传。", "可以。cv.cm 在目前分頁做，不上傳。", "できる。このタブ。アップロードなし。", "됩니다. 이 탭에서 만듭니다. 업로드 없음.", "Được. Làm trong tab này, không tải lên.", "Ya. Di tab ini. Tidak diunggah.", "Sí. En esta pestaña. Nada se sube."),
            "q2": L("How do I make a 2×2 Instagram collage?", "怎么做 2×2 的 Instagram 拼图？", "怎麼做 2×2 的 Instagram 拼圖？", "Instagram用の2×2は？", "인스타 2×2 콜라주는?", "Collage 2×2 Instagram?", "Kolase 2×2 Instagram?", "¿Cómo hago un collage 2×2 de Instagram?"),
            "a2": L("Pick 2×2 and square (or 4:5). Drop four photos, check Contain vs Cover, download.", "选 2×2 和正方形（或 4:5）。放入四张，看 Contain/Cover，下载。", "選 2×2 和正方形（或 4:5）。放入四張，看 Contain/Cover，下載。", "2×2と正方形（または4:5）。4枚入れてContain/Coverを見て保存。", "2×2와 정사각(또는 4:5)을 고르고 네 장을 넣은 뒤 Contain/Cover를 보고 받으세요.", "Chọn 2×2 và vuông (hoặc 4:5). Thả bốn ảnh, xem Contain/Cover, tải.", "Pilih 2×2 dan persegi (atau 4:5). Empat foto, cek Contain/Cover, unduh.", "Elija 2×2 y cuadrado (o 4:5). Suelte cuatro, mire Contain/Cover y descargue."),
            "q3": L("Why did a face get cropped?", "为什么脸被切了？", "為什麼臉被切了？", "顔が切れたのはなぜ？", "얼굴이 잘린 이유는?", "Vì sao mặt bị cắt?", "Kenapa wajah terpotong?", "¿Por qué se recortó una cara?"),
            "a3": L("Cover fills the cell. Switch to Contain, or pick a photo with more room around the head.", "Cover 会铺满格子。改 Contain，或换一张头周围更空的图。", "Cover 會鋪滿格子。改 Contain，或換一張頭周圍更空的圖。", "Coverがセルを埋める。Containにするか、頭の周りに余白がある写真に変える。", "Cover가 칸을 채웁니다. Contain으로 바꾸거나 머리 주위에 공간이 있는 사진으로 바꾸세요.", "Cover lấp ô. Đổi Contain, hoặc chọn ảnh có chỗ quanh đầu.", "Cover mengisi sel. Ganti Contain, atau foto dengan ruang di sekitar kepala.", "Cover llena la celda. Pase a Contain, o elija una foto con más aire alrededor de la cabeza."),
            "q4": L("Are photos uploaded?", "会上传吗？", "會上傳嗎？", "アップロードされる？", "업로드되나요?", "Có tải lên không?", "Apakah diunggah?", "¿Se suben las fotos?"),
            "a4": L("No. Closing the tab discards them.", "不会。关掉标签页就没了。", "不會。關掉分頁就沒了。", "しない。タブを閉じると消える。", "아니요. 탭을 닫으면 사라집니다.", "Không. Đóng tab là mất.", "Tidak. Tutup tab, hilang.", "No. Al cerrar la pestaña se pierden."),
            "q5": L("Can I collage without Canva or Photoshop?", "不用 Canva 或 Photoshop 能拼吗？", "不用 Canva 或 Photoshop 能拼嗎？", "CanvaやPhotoshopなしで？", "캔바·포토샵 없이?", "Không cần Canva hay Photoshop?", "Tanpa Canva atau Photoshop?", "¿Sin Canva ni Photoshop?"),
            "a5": L("Yes. This page is the collage. No account.", "可以。本页就是拼图。不用账号。", "可以。本頁就是拼圖。不用帳號。", "できる。このページがコラージュ。アカウント不要。", "됩니다. 이 페이지가 콜라주입니다. 계정 없음.", "Được. Trang này là collage. Không tài khoản.", "Ya. Halaman ini kolasenya. Tanpa akun.", "Sí. Esta página es el collage. Sin cuenta."),
        },
    ),
    "make-meme": lesson(
        {
            "name": L("How to make a meme", "怎么做表情包", "怎麼做迷因圖", "ミームの作り方", "밈 만드는 법", "Cách làm meme", "Cara buat meme", "Cómo hacer un meme"),
            "blurb": L("Drop a photo, type top and bottom text, download a PNG, then check it at phone width.", "放入照片，上下打字，下载 PNG，再用手机宽度看一眼。", "放入照片，上下打字，下載 PNG，再用手機寬度看一眼。", "写真を入れ、上下に文字、PNGを保存し、スマホ幅で見る。", "사진을 넣고 위아래 글을 쓴 뒤 PNG를 받아 폰 너비로 보세요.", "Thả ảnh, chữ trên dưới, tải PNG, xem bề ngang điện thoại.", "Letakkan foto, teks atas/bawah, unduh PNG, cek lebar ponsel.", "Suelte una foto, texto arriba y abajo, descargue PNG y mírelo al ancho del teléfono."),
            "title": L("How to make a meme", "怎么做表情包", "怎麼做迷因圖", "ミームの作り方", "밈 만드는 법", "Cách làm meme", "Cara buat meme", "Cómo hacer un meme"),
            "lead": L("A meme is a photo plus two short lines. You will drop an image, type top and bottom, and check that the type still reads at the size of a chat bubble.", "表情包就是一张图加两行短字。拖入照片，打上下句，再按聊天气泡那么大看清不清。", "迷因圖就是一張圖加兩行短字。拖入照片，打上下句，再按聊天氣泡那麼大看清不清。", "ミームは写真と短い2行。画像を入れ、上下を打ち、チャットの大きさで読めるか見る。", "밈은 사진과 짧은 두 줄입니다. 이미지를 넣고 위아래를 쓴 뒤 채팅 크기에서 읽히는지 보세요.", "Meme là ảnh cộng hai dòng ngắn. Thả ảnh, gõ trên dưới, xem còn đọc được cỡ bong bóng chat.", "Meme adalah foto plus dua baris pendek. Letakkan gambar, ketik atas/bawah, cek kebaca seukuran gelembung chat.", "Un meme es una foto y dos líneas cortas. Suelte la imagen, escriba arriba y abajo, y compruebe que se lee al tamaño de un chat."),
            "result": L("A PNG with readable top and bottom lines that do not cover the face.", "一张 PNG：上下字能读，没有挡住脸。", "一張 PNG：上下字能讀，沒有擋住臉。", "上下が読めて顔を隠さないPNG。", "위아래가 읽히고 얼굴을 가리지 않는 PNG.", "PNG: chữ trên dưới đọc được, không che mặt.", "PNG: teks atas/bawah terbaca, tidak menutupi wajah.", "Un PNG con líneas legibles que no tapan la cara."),
            "note": L("Open the meme tool when the photo is on disk. Keep lines short. Nothing is uploaded.", "照片在磁盘上再打开表情包。句子要短。不上传。", "照片在磁碟上再打開迷因。句子要短。不上傳。", "写真が手元にあってから開く。文は短く。アップロードなし。", "사진이 디스크에 있으면 밈 도구를 여세요. 문장은 짧게. 업로드 없음.", "Có ảnh trên đĩa thì mở meme. Câu ngắn. Không tải lên.", "Foto di disk, baru buka meme. Kalimat pendek. Tidak diunggah.", "Abra el meme con la foto en el disco. Líneas cortas. Nada se sube."),
            "s1t": L("Pick a photo that still reads small", "选一张缩得很小仍能看懂的图", "選一張縮得很小仍能看懂的圖", "小さくても分かる写真", "작아도 알아보는 사진", "Chọn ảnh nhỏ vẫn đọc được", "Pilih foto yang masih kebaca kecil", "Elija una foto que se lea pequeña"),
            "s1b": L("A busy background fights the type. A face or a clear object works better than a landscape.", "背景太花会抢字。一张脸或一件清楚的东西，比风景好用。", "背景太花會搶字。一張臉或一件清楚的東西，比風景好用。", "賑やかな背景は文字と喧嘩する。顔やはっきりした物の方が風景より向く。", "복잡한 배경은 글자와 싸웁니다. 풍경보다 얼굴이나 또렷한 물건이 낫습니다.", "Nền rối tranh chữ. Mặt hoặc một vật rõ hơn phong cảnh.", "Latar ramai bertarung dengan teks. Wajah atau benda jelas lebih baik daripada lanskap.", "Un fondo ocupado pelea con el texto. Una cara o un objeto claro funciona mejor que un paisaje."),
            "s2t": L("Open meme on cv.cm", "打开 cv.cm 的表情包", "打開 cv.cm 的迷因", "cv.cmのミームを開く", "cv.cm 밈을 열기", "Mở meme trên cv.cm", "Buka meme di cv.cm", "Abra meme en cv.cm"),
            "s2b": L("Work stays in this tab.", "做图留在当前标签页。", "做圖留在目前分頁。", "このタブで処理。", "이 탭에서 만듭니다.", "Làm trong tab này.", "Proses di tab ini.", "El trabajo queda en esta pestaña."),
            "s3t": L("Drop the image", "拖入图片", "拖入圖片", "画像をドロップ", "이미지를 넣기", "Thả ảnh", "Letakkan gambar", "Suelte la imagen"),
            "s3b": L("If the preview is blank, convert HEIC first.", "预览空白，先把 HEIC 转成 JPG。", "預覽空白，先把 HEIC 轉成 JPG。", "プレビューが空なら先にHEICをJPGに。", "미리보기가 비면 HEIC를 JPG로 먼저 바꾸세요.", "Xem trước trống thì đổi HEIC sang JPG trước.", "Pratinjau kosong: ubah HEIC ke JPG dulu.", "Si la vista está en blanco, pase HEIC a JPG antes."),
            "s4t": L("Type a short top and bottom line", "上下各打一句短的", "上下各打一句短的", "上下に短い1行", "위아래에 짧은 한 줄", "Gõ một dòng trên và dưới, ngắn", "Ketik satu baris atas dan bawah, pendek", "Escriba una línea corta arriba y otra abajo"),
            "s4b": L("All caps is the usual look. Two to seven words per line. Do not write a paragraph.", "通常全大写。一行两到七个词。不要写成一段。", "通常全大寫。一行兩到七個詞。不要寫成一段。", "だいたい全部大文字。1行2–7語。段落を書かない。", "보통 모두 대문자. 한 줄에 두세 단어에서 일곱 단어. 문단을 쓰지 마세요.", "Thường viết hoa. Hai đến bảy từ một dòng. Đừng viết một đoạn.", "Biasanya huruf besar. Dua sampai tujuh kata per baris. Jangan paragraf.", "Suele ir en mayúsculas. De dos a siete palabras por línea. No escriba un párrafo."),
            "s5t": L("Check wrap and stroke", "看换行和描边", "看換行和描邊", "折り返しと縁を見る", "줄바꿈과 테두리 보기", "Xem xuống dòng và viền", "Cek bungkus dan stroke", "Revise el salto y el trazo"),
            "s5b": L("The outline is what keeps white type readable on a bright photo. If a line covers a face, shorten it.", "白字能读，靠的是描边。挡住脸了，就缩短。", "白字能讀，靠的是描邊。擋住臉了，就縮短。", "白い文字が読めるのは縁のおかげ。顔を隠すなら短くする。", "흰 글자가 읽히는 건 테두리 덕분입니다. 얼굴을 가리면 줄이세요.", "Chữ trắng đọc được nhờ viền. Che mặt thì rút ngắn.", "Teks putih kebaca karena stroke. Menutupi wajah: persingkat.", "El trazo hace legible el blanco sobre una foto clara. Si tapa una cara, acórtela."),
            "s6t": L("Download PNG and view at phone width", "下载 PNG，按手机宽度看", "下載 PNG，按手機寬度看", "PNGを保存しスマホ幅で見る", "PNG를 받아 폰 너비로 보기", "Tải PNG và xem bề ngang điện thoại", "Unduh PNG dan lihat lebar ponsel", "Descargue PNG y mírelo al ancho del teléfono"),
            "s6b": L("If it only reads full-screen, it will fail in a chat. Keep the original unmarked photo.", "只有全屏才看得清，发聊天就会失败。没字的原图留下。", "只有全螢幕才看得清，發聊天就會失敗。沒字的原圖留下。", "全画面でしか読めないならチャットで失敗する。無字の原版は残す。", "전체 화면에서만 읽히면 채팅에서 실패합니다. 글자 없는 원본을 남기세요.", "Chỉ đọc được full màn hình thì gửi chat sẽ fail. Giữ ảnh gốc chưa chữ.", "Hanya kebaca full screen: gagal di chat. Simpan foto asli tanpa teks.", "Si solo se lee a pantalla completa, fallará en el chat. Conserve la foto original sin texto."),
            "diagram1": L("Top line sets up. Bottom line pays off. Keep both short.", "上一句铺垫，下一句收束。都要短。", "上一句鋪墊，下一句收束。都要短。", "上は振り、下は落ち。どちらも短く。", "위는 깔고 아래는 받습니다. 둘 다 짧게.", "Dòng trên mở, dòng dưới chốt. Cả hai phải ngắn.", "Baris atas setup, bawah punch. Keduanya pendek.", "Arriba plantea, abajo cierra. Las dos, cortas."),
            "diagram2": L("Stroke keeps type readable. Do not cover the face.", "描边让字能读。不要挡住脸。", "描邊讓字能讀。不要擋住臉。", "縁で文字が読める。顔を隠さない。", "테두리가 글자를 읽히게 합니다. 얼굴을 가리지 마세요.", "Viền giúp chữ đọc được. Đừng che mặt.", "Stroke membuat teks kebaca. Jangan tutupi wajah.", "El trazo hace legible el texto. No tape la cara."),
        },
        {
            "q1": L("Can I make a meme free online?", "可以免费在线做表情包吗？", "可以免費線上做迷因嗎？", "無料でミームを作れる？", "무료로 밈 만들 수 있나요?", "Làm meme miễn phí online?", "Meme gratis online?", "¿Puedo hacer un meme gratis en línea?"),
            "a1": L("Yes. cv.cm draws in this tab. Nothing is uploaded.", "可以。cv.cm 在当前标签页画，不上传。", "可以。cv.cm 在目前分頁畫，不上傳。", "できる。このタブで描く。アップロードなし。", "됩니다. 이 탭에서 그립니다. 업로드 없음.", "Được. Vẽ trong tab này, không tải lên.", "Ya. Menggambar di tab ini. Tidak diunggah.", "Sí. Se dibuja en esta pestaña. Nada se sube."),
            "q2": L("Do I need Photoshop or an app?", "要 Photoshop 或 App 吗？", "要 Photoshop 或 App 嗎？", "Photoshopやアプリは要る？", "포토샵이나 앱이 필요하나요?", "Cần Photoshop hay app?", "Perlu Photoshop atau app?", "¿Necesito Photoshop o una app?"),
            "a2": L("No. A current browser is enough.", "不用。现在的浏览器就够。", "不用。現在的瀏覽器就夠。", "不要。今のブラウザで足りる。", "아니요. 지금 브라우저면 됩니다.", "Không. Trình duyệt hiện tại đủ.", "Tidak. Peramban sekarang cukup.", "No. Con el navegador actual basta."),
            "q3": L("What font should a meme use?", "表情包用什么字体？", "迷因用什麼字體？", "フォントは？", "글꼴은?", "Font nào?", "Font apa?", "¿Qué fuente?"),
            "a3": L("Heavy sans with a dark stroke, usually all caps. This tool uses that look.", "粗无衬线加深描边，通常全大写。本工具就是这种。", "粗無襯線加深描邊，通常全大寫。本工具就是這種。", "太いサンセリフに暗い縁。だいたい全部大文字。このツールがその見た目。", "두꺼운 고딕에 어두운 테두리, 보통 모두 대문자. 이 도구가 그 모양입니다.", "Sans đậm viền tối, thường viết hoa. Công cụ này đúng kiểu đó.", "Sans tebal dengan stroke gelap, biasanya kapital. Alat ini memakai tampilan itu.", "Sans gruesa con trazo oscuro, casi siempre en mayúsculas. Esta herramienta usa ese aspecto."),
            "q4": L("Are photos uploaded?", "会上传吗？", "會上傳嗎？", "アップロードされる？", "업로드되나요?", "Có tải lên không?", "Apakah diunggah?", "¿Se suben las fotos?"),
            "a4": L("No. Closing the tab discards them.", "不会。关掉标签页就没了。", "不會。關掉分頁就沒了。", "しない。タブを閉じると消える。", "아니요. 탭을 닫으면 사라집니다.", "Không. Đóng tab là mất.", "Tidak. Tutup tab, hilang.", "No. Al cerrar la pestaña se pierden."),
            "q5": L("Can I make a meme on iPhone?", "iPhone 能做吗？", "iPhone 能做嗎？", "iPhoneでも？", "아이폰에서도?", "Làm trên iPhone được không?", "Bisa di iPhone?", "¿Puedo hacerlo en el iPhone?"),
            "a5": L("Yes in Safari. If a HEIC will not preview, convert it to JPG first.", "Safari 可以。HEIC 预览不了，先转成 JPG。", "Safari 可以。HEIC 預覽不了，先轉成 JPG。", "Safariなら可。HEICがプレビューできないなら先にJPGへ。", "Safari에서 됩니다. HEIC가 안 보이면 먼저 JPG로 바꾸세요.", "Được trên Safari. HEIC không xem trước thì đổi JPG trước.", "Ya di Safari. HEIC tidak pratinjau: ubah ke JPG dulu.", "Sí en Safari. Si el HEIC no se ve, páselo a JPG primero."),
        },
    ),
    "count-words": lesson(
        {
            "name": L("How to count words and characters", "怎么统计字数和词数", "怎麼統計字數和詞數", "単語と文字数の数え方", "단어·글자 수 세는 법", "Cách đếm từ và ký tự", "Cara hitung kata dan karakter", "Cómo contar palabras y caracteres"),
            "blurb": L("Paste the text, read the matching number, trim if a form has a cap.", "贴上文字，看对得上的那个数字。表单有上限就删完再数。", "貼上文字，看對得上的那個數字。表單有上限就刪完再數。", "テキストを貼り、合う数字を見る。上限があれば削って再カウント。", "텍스트를 붙여 맞는 숫자를 보세요. 한도가 있으면 줄인 뒤 다시 세요.", "Dán chữ, đọc đúng chỉ số. Form có hạn thì cắt rồi đếm lại.", "Tempel teks, baca angka yang cocok. Ada batas: potong, hitung lagi.", "Pegue el texto, mire el número que corresponde. Si hay tope, recorte y vuelva a contar."),
            "title": L("How to count words and characters", "怎么统计字数和词数", "怎麼統計字數和詞數", "単語と文字数の数え方", "단어·글자 수 세는 법", "Cách đếm từ và ký tự", "Cara hitung kata dan karakter", "Cómo contar palabras y caracteres"),
            "lead": L("Essays want words. Forms often want characters. Chinese homework often wants characters with no spaces. You will paste the text and read the matching number.", "英文作业数词。表单多数数字符。中文作业常算不含空格的字。贴上文字，看对得上的那个数。", "英文作業數詞。表單多數數字元。中文作業常算不含空格的字。貼上文字，看對得上的那個數。", "英語の課題は単語。フォームは文字数。中国語の宿題は空白なしの文字が多い。貼って合う数字を見る。", "영어 과제는 단어. 폼은 글자. 중국어 숙제는 공백 없는 글자인 경우가 많습니다. 붙여 넣고 맞는 숫자를 보세요.", "Bài tiếng Anh đếm từ. Form thường đếm ký tự. Bài tiếng Trung thường đếm không khoảng trắng. Dán chữ và đọc đúng số.", "Esai Inggris: kata. Formulir: karakter. PR Tionghoa: karakter tanpa spasi. Tempel dan baca angka yang cocok.", "Los ensayos piden palabras. Los formularios, caracteres. Los deberes en chino, caracteres sin espacios. Pegue el texto y mire el número que toca."),
            "result": L("The number the form or teacher actually asked for, from text that never left this tab.", "表单或老师真正要的那个数字。文字没有离开当前标签页。", "表單或老師真正要的那個數字。文字沒有離開目前分頁。", "フォームや先生が本当に欲しい数字。テキストはこのタブから出ていない。", "폼이나 선생님이 실제로 원한 숫자. 텍스트는 이 탭을 떠나지 않았습니다.", "Đúng con số form hoặc giáo viên hỏi. Chữ không rời tab này.", "Angka yang diminta formulir atau guru. Teks tidak keluar tab ini.", "El número que pedía el formulario o el profesor. El texto no salió de esta pestaña."),
            "note": L("Open word count when the text is ready. Words, characters, and characters without spaces are three different counts. Nothing is uploaded.", "文字准备好再打开字数。词数、字符、不含空格的字符是三个数。不上传。", "文字準備好再打開字數。詞數、字元、不含空格的字元是三個數。不上傳。", "テキストが揃ってから開く。単語・文字・空白なし文字は別の数。アップロードなし。", "텍스트가 준비되면 여세요. 단어, 글자, 공백 없는 글자는 세 숫자입니다. 업로드 없음.", "Chữ sẵn thì mở đếm. Từ, ký tự, ký tự không khoảng là ba số khác. Không tải lên.", "Teks siap, baru buka hitung. Kata, karakter, karakter tanpa spasi: tiga angka. Tidak diunggah.", "Abra el contador con el texto listo. Palabras, caracteres y caracteres sin espacios son tres cifras. Nada se sube."),
            "s1t": L("Know which number you need", "先知道要哪一个数", "先知道要哪一個數", "欲しい数字を決める", "필요한 숫자를 정하기", "Biết cần số nào", "Tahu angka mana yang dibutuhkan", "Sepa qué número necesita"),
            "s1b": L("English essays: words. Twitter-style caps and many web forms: characters. Chinese homework: characters with spaces removed. Do not mix them.", "英文作业：词。很多网页表单：字符。中文作业：去掉空格的字。不要混用。", "英文作業：詞。很多網頁表單：字元。中文作業：去掉空格的字。不要混用。", "英語課題は単語。ウェブの上限は文字。中国語宿題は空白なし文字。混ぜない。", "영어 과제: 단어. 많은 웹 폼: 글자. 중국어 숙제: 공백 없는 글자. 섞지 마세요.", "Bài Anh: từ. Form web: ký tự. Bài Trung: ký tự không khoảng. Đừng trộn.", "Esai Inggris: kata. Formulir web: karakter. PR Tionghoa: karakter tanpa spasi. Jangan campur.", "Ensayos en inglés: palabras. Formularios: caracteres. Deberes en chino: caracteres sin espacios. No los mezcle."),
            "s2t": L("Open word count on cv.cm", "打开 cv.cm 的字数统计", "打開 cv.cm 的字數統計", "cv.cmの文字数を開く", "cv.cm 글자 수를 열기", "Mở đếm từ trên cv.cm", "Buka hitung kata di cv.cm", "Abra el contador en cv.cm"),
            "s2b": L("Counting stays in this tab.", "统计留在当前标签页。", "統計留在目前分頁。", "このタブで数える。", "이 탭에서 셉니다.", "Đếm trong tab này.", "Hitung di tab ini.", "El recuento queda en esta pestaña."),
            "s3t": L("Paste the text, or drop a .txt file", "贴上文字，或拖入 .txt", "貼上文字，或拖入 .txt", "貼るか.txtをドロップ", "텍스트를 붙이거나 .txt를 넣기", "Dán chữ, hoặc thả .txt", "Tempel teks, atau letakkan .txt", "Pegue el texto o suelte un .txt"),
            "s3b": L("Paste from the same draft you will submit. Counting a different copy is how people miss the cap.", "用你要交的那一稿来贴。数另一份，就容易超限。", "用你要交的那一稿來貼。數另一份，就容易超限。", "提出する原稿を貼る。別コピーを数えると上限を外す。", "제출할 그 초안을 붙이세요. 다른 복사본을 세면 한도를 놓칩니다.", "Dán đúng bản sẽ nộp. Đếm bản khác thì dễ vượt hạn.", "Tempel draf yang akan dikumpul. Menghitung salinan lain: mudah kelewatan batas.", "Pegue el mismo borrador que va a entregar. Contar otra copia es cómo se pasa el tope."),
            "s4t": L("Read the matching stat", "看对得上的那一项", "看對得上的那一項", "合う項目を読む", "맞는 항목을 읽기", "Đọc đúng chỉ số", "Baca statistik yang cocok", "Lea la cifra que corresponde"),
            "s4b": L("Words for English. Characters for most forms. Characters with no spaces for many CN assignments. CJK characters each count as a word here, so do not use Words for a 800-字 paper.", "英文看词。多数表单看字符。中文作业看不含空格。这里每个汉字也算一个词，八百字作文不要看词数。", "英文看詞。多數表單看字元。中文作業看不含空格。這裡每個漢字也算一個詞，八百字作文不要看詞數。", "英語は単語。フォームは文字。中国語課題は空白なし。ここでは漢字1字も1語なので800字の作文に単語を使わない。", "영어는 단어. 대부분 폼은 글자. 중국어 숙제는 공백 없는 글자. 여기선 한자 하나도 단어로 세니 800자 숙제에 단어를 쓰지 마세요.", "Tiếng Anh: từ. Form: ký tự. Bài Trung: không khoảng. Ở đây mỗi chữ Hán cũng là một từ — bài 800 chữ đừng nhìn Words.", "Inggris: kata. Formulir: karakter. PR Tionghoa: tanpa spasi. Di sini tiap hanzi dihitung kata: jangan pakai Words untuk 800 字.", "Inglés: palabras. Formularios: caracteres. Deberes en chino: sin espacios. Aquí cada hanzi cuenta como palabra: no use Words para 800 字."),
            "s5t": L("If there is a cap, trim and count again", "有上限就删完再数", "有上限就刪完再數", "上限があれば削って再カウント", "한도가 있으면 줄인 뒤 다시 세기", "Có hạn thì cắt rồi đếm lại", "Ada batas: potong, hitung lagi", "Si hay tope, recorte y vuelva a contar"),
            "s5b": L("Delete, then look at the same row. Do not switch from words to characters halfway.", "删完仍看同一行。不要中途从词改成字符。", "刪完仍看同一行。不要中途從詞改成字元。", "削ったら同じ行を見る。途中で単語から文字に切り替えない。", "지운 뒤 같은 줄을 보세요. 중간에 단어에서 글자로 바꾸지 마세요.", "Xóa xong vẫn nhìn cùng một hàng. Đừng đổi từ sang ký tự giữa chừng.", "Hapus, lalu lihat baris yang sama. Jangan pindah dari kata ke karakter di tengah jalan.", "Borre y mire la misma fila. No pase de palabras a caracteres a mitad."),
            "s6t": L("Do not trust a different app's count for this form", "别拿别的软件的数去填这个表", "別拿別的軟體的數去填這個表", "別アプリの数字をこのフォームに使わない", "다른 앱 숫자를 이 폼에 넣지 마세요", "Đừng lấy số app khác cho form này", "Jangan pakai hitungan app lain untuk formulir ini", "No use el recuento de otra app para este formulario"),
            "s6b": L("Word, Google Docs, and a web form often disagree. Count in the same place you will paste.", "Word、Docs 和网页表单经常对不上。在你要粘贴的地方数。", "Word、Docs 和網頁表單經常對不上。在你要貼上的地方數。", "Word、Docs、ウェブフォームは食い違う。貼る場所で数える。", "Word, Docs, 웹 폼은 자주 다릅니다. 붙여 넣을 곳에서 세요.", "Word, Docs và form web thường lệch. Đếm đúng chỗ sẽ dán.", "Word, Docs, dan formulir web sering beda. Hitung di tempat Anda akan menempel.", "Word, Docs y el formulario web suelen discrepar. Cuente donde vaya a pegar."),
            "diagram1": L("Words · characters · characters with no spaces. Three jobs, three numbers.", "词 · 字符 · 不含空格。三件事，三个数。", "詞 · 字元 · 不含空格。三件事，三個數。", "単語・文字・空白なし。3つの仕事、3つの数。", "단어 · 글자 · 공백 없는 글자. 세 일, 세 숫자.", "Từ · ký tự · không khoảng. Ba việc, ba số.", "Kata · karakter · tanpa spasi. Tiga kerja, tiga angka.", "Palabras · caracteres · sin espacios. Tres trabajos, tres cifras."),
            "diagram2": L("For Chinese homework use characters with no spaces, not Words.", "中文作业看不含空格的字，不要看词数。", "中文作業看不含空格的字，不要看詞數。", "中国語宿題は空白なし文字。単語は使わない。", "중국어 숙제는 공백 없는 글자. 단어를 쓰지 마세요.", "Bài Trung dùng ký tự không khoảng, đừng dùng Words.", "PR Tionghoa: karakter tanpa spasi, bukan Words.", "En los deberes en chino use caracteres sin espacios, no Words."),
        },
        {
            "q1": L("How do I count words online?", "怎么在线数字数？", "怎麼線上數字數？", "オンラインで単語を数えるには？", "온라인에서 단어를 세려면?", "Đếm từ online?", "Hitung kata online?", "¿Cómo cuento palabras en línea?"),
            "a1": L("Paste into cv.cm word count in this tab. Read Words. Nothing is uploaded.", "贴进 cv.cm 的字数，看词数。不上传。", "貼進 cv.cm 的字數，看詞數。不上傳。", "このタブに貼って単語を見る。アップロードなし。", "이 탭에 붙여 단어를 보세요. 업로드 없음.", "Dán vào đếm từ cv.cm trong tab này, đọc Words. Không tải lên.", "Tempel di hitung kata cv.cm di tab ini, baca Words. Tidak diunggah.", "Pegue en el contador de cv.cm y mire Words. Nada se sube."),
            "q2": L("What is the difference between words and characters?", "词和字符有什么差别？", "詞和字元有什麼差別？", "単語と文字の違いは？", "단어와 글자의 차이는?", "Từ khác ký tự thế nào?", "Beda kata dan karakter?", "¿Qué diferencia hay entre palabras y caracteres?"),
            "a2": L("Words split on spaces (and each CJK character counts as a word here). Characters count every letter, space, and punctuation.", "词按空格切（这里每个汉字也算一词）。字符把字母、空格、标点都算上。", "詞按空格切（這裡每個漢字也算一詞）。字元把字母、空格、標點都算上。", "単語は空白で切る（ここでは漢字1字も1語）。文字は字母・空白・句読点も数える。", "단어는 공백으로 나눕니다(여기선 한자 하나도 단어). 글자는 알파벳, 공백, 구두점까지 셉니다.", "Từ tách theo khoảng (ở đây mỗi chữ Hán cũng là một từ). Ký tự đếm cả chữ, khoảng, dấu.", "Kata dipisah spasi (di sini tiap hanzi = satu kata). Karakter menghitung huruf, spasi, tanda baca.", "Las palabras se parten por espacios (aquí cada hanzi cuenta como palabra). Los caracteres cuentan letras, espacios y signos."),
            "q3": L("How do I count Chinese characters?", "中文字怎么数？", "中文字怎麼數？", "中国語の文字数は？", "중국어 글자 수는?", "Đếm chữ Hán thế nào?", "Hitung karakter Tionghoa?", "¿Cómo cuento caracteres chinos?"),
            "a3": L("Use characters with no spaces if the teacher wants 字数. Do not use Words for an 800-字 paper.", "老师要字数，就看不含空格。八百字作文不要看词数。", "老師要字數，就看不含空格。八百字作文不要看詞數。", "先生が字数なら空白なし。800字の作文に単語を使わない。", "선생님이 자수라면 공백 없는 글자. 800자 숙제에 단어를 쓰지 마세요.", "Giáo viên cần 字数 thì dùng không khoảng. Bài 800 chữ đừng dùng Words.", "Guru minta 字数: karakter tanpa spasi. Jangan Words untuk 800 字.", "Si el profesor pide 字数, use caracteres sin espacios. No use Words para 800 字."),
            "q4": L("Is the text uploaded?", "文字会上传吗？", "文字會上傳嗎？", "テキストはアップロードされる？", "텍스트가 업로드되나요?", "Chữ có bị tải lên không?", "Teks diunggah?", "¿Se sube el texto?"),
            "a4": L("No. Closing the tab discards it.", "不会。关掉标签页就没了。", "不會。關掉分頁就沒了。", "しない。タブを閉じると消える。", "아니요. 탭을 닫으면 사라집니다.", "Không. Đóng tab là mất.", "Tidak. Tutup tab, hilang.", "No. Al cerrar la pestaña se pierde."),
            "q5": L("Why doesn't it match Microsoft Word?", "为什么和 Word 对不上？", "為什麼和 Word 對不上？", "Wordと合わないのはなぜ？", "워드와 안 맞는 이유는?", "Sao không khớp Word?", "Kenapa beda dengan Word?", "¿Por qué no coincide con Word?"),
            "a5": L("Each app splits words differently, especially with CJK, hyphens, and numbers. Count in the same tool as the cap.", "各软件切词不一样，汉字、连字符、数字更乱。上限用哪个工具数，就在哪个工具数。", "各軟體切詞不一樣，漢字、連字符、數字更亂。上限用哪個工具數，就在哪個工具數。", "アプリごとに切れ方が違う。漢字・ハイフン・数字は特に。上限を数える道具で数える。", "앱마다 나누는 법이 다릅니다. 한자, 하이픈, 숫자는 더. 한도를 센 도구에서 세요.", "Mỗi app tách từ khác, nhất là chữ Hán, gạch nối, số. Đếm đúng chỗ đặt hạn.", "Tiap app memotong kata beda, apalagi CJK, tanda hubung, angka. Hitung di alat yang sama dengan batas.", "Cada app parte las palabras distinto, sobre todo con CJK, guiones y números. Cuente en la misma herramienta que el tope."),
        },
    ),
    "trim-audio": lesson(
        {
            "name": L("How to trim audio / cut an MP3", "怎么裁剪音频 / 剪 MP3", "怎麼裁剪音訊 / 剪 MP3", "音声のトリム / MP3を切る", "오디오 자르기 / MP3 컷", "Cách cắt audio / cắt MP3", "Cara potong audio / potong MP3", "Cómo recortar audio / cortar un MP3"),
            "blurb": L("Set start and end, listen, download WAV, then play the file before you send it.", "定起点和终点，先听，下载 WAV，发出去之前再播一遍。", "定起點和終點，先聽，下載 WAV，寄出去之前再播一遍。", "開始と終了を決め、聴いて、WAVを保存し、送る前にもう一度再生。", "시작과 끝을 정하고 들어본 뒤 WAV를 받아, 보내기 전에 다시 재생하세요.", "Đặt đầu và cuối, nghe, tải WAV, phát lại trước khi gửi.", "Set awal dan akhir, dengar, unduh WAV, putar lagi sebelum kirim.", "Fije inicio y fin, escuche, descargue WAV y reprodúzcalo antes de enviarlo."),
            "title": L("How to trim audio / cut an MP3", "怎么裁剪音频 / 剪 MP3", "怎麼裁剪音訊 / 剪 MP3", "音声のトリム / MP3を切る方法", "오디오 자르기 / MP3 컷하는 법", "Cách cắt audio / cắt MP3", "Cara potong audio / potong MP3", "Cómo recortar audio / cortar un MP3"),
            "lead": L("You need a clip, not the whole file: a ring, a quote, a voicemail. You will mark start and end in this tab, listen, and download WAV. The original stays on disk.", "你要的是一段，不是整首：铃声、摘句、语音。在当前标签页标起点终点，先听，再下载 WAV。原文件还在。", "你要的是一段，不是整首：鈴聲、摘句、語音。在目前分頁標起點終點，先聽，再下載 WAV。原檔還在。", "欲しいのは一部。着信音、引用、留守電。このタブで開始と終了を付け、聴いてWAVを保存。元ファイルは残る。", "전체가 아니라 한 조각이 필요합니다. 벨소리, 인용, 음성. 이 탭에서 시작과 끝을 표시하고 들어본 뒤 WAV를 받으세요. 원본은 디스크에 남습니다.", "Bạn cần một đoạn, không cả file: nhạc chuông, trích, voicemail. Đánh đầu cuối trong tab này, nghe, tải WAV. Bản gốc còn trên đĩa.", "Anda butuh klip, bukan seluruh file: nada dering, kutipan, voicemail. Tandai awal/akhir di tab ini, dengar, unduh WAV. Asli tetap di disk.", "Necesita un recorte, no el archivo entero: tono, cita, buzón. Marque inicio y fin aquí, escuche y descargue WAV. El original sigue en el disco."),
            "result": L("A WAV that starts and ends where you marked, verified by playing it once.", "一份 WAV：起止就是你标的位置，播过一遍才算数。", "一份 WAV：起止就是你標的位置，播過一遍才算數。", "印を付けた位置で始まるWAV。一度再生して確認。", "표시한 곳에서 시작하고 끝나는 WAV. 한 번 재생해 확인.", "WAV bắt và kết đúng chỗ đánh, đã phát một lần.", "WAV yang mulai dan selesai di tanda Anda, sudah diputar sekali.", "Un WAV que empieza y acaba donde marcó, comprobado al reproducirlo una vez."),
            "note": L("Open trim when the audio is on disk. The download is WAV, even if you dropped an MP3. Listen before you send. Nothing is uploaded.", "音频在磁盘上再打开裁剪。下载是 WAV，即使拖进来的是 MP3。发出去之前先听。不上传。", "音訊在磁碟上再打開裁剪。下載是 WAV，即使拖進來的是 MP3。寄出去之前先聽。不上傳。", "音声が手元にあってから開く。保存はWAV。元がMP3でもWAV。送る前に聴く。アップロードなし。", "오디오가 디스크에 있으면 자르기를 여세요. 받은 파일은 WAV입니다. MP3를 넣어도 WAV. 보내기 전에 들으세요. 업로드 없음.", "Có audio trên đĩa thì mở cắt. File tải là WAV, dù thả MP3. Nghe trước khi gửi. Không tải lên.", "Audio di disk, baru buka potong. Unduhan WAV, meski Anda taruh MP3. Dengar sebelum kirim. Tidak diunggah.", "Abra recortar con el audio en el disco. La descarga es WAV, aunque haya soltado un MP3. Escuche antes de enviar. Nada se sube."),
            "s1t": L("Know the start and end you want", "先想清楚从哪切到哪", "先想清楚從哪切到哪", "開始と終了を決める", "시작과 끝을 정하기", "Biết cắt từ đâu đến đâu", "Tahu awal dan akhir", "Sepa el inicio y el fin"),
            "s1b": L("A ringtone is often 20–40 seconds. A quote is one sentence. Write the times down if the file is long.", "铃声常见 20–40 秒。摘句就一句。文件很长就把时间写下来。", "鈴聲常見 20–40 秒。摘句就一句。檔很長就把時間寫下來。", "着信音はだいたい20–40秒。引用は1文。長いファイルなら時刻を書く。", "벨소리는 흔히 20–40초. 인용은 한 문장. 파일이 길면 시간을 적으세요.", "Nhạc chuông thường 20–40 giây. Trích một câu. File dài thì ghi mốc.", "Nada dering sering 20–40 detik. Kutipan satu kalimat. File panjang: tulis waktunya.", "Un tono suele durar 20–40 s. Una cita, una frase. Si el archivo es largo, anote los tiempos."),
            "s2t": L("Open audio cutter on cv.cm", "打开 cv.cm 的音频裁剪", "打開 cv.cm 的音訊裁剪", "cv.cmの音声カットを開く", "cv.cm 오디오 자르기를 열기", "Mở cắt audio trên cv.cm", "Buka potong audio di cv.cm", "Abra recortar audio en cv.cm"),
            "s2b": L("Work stays in this tab.", "裁剪留在当前标签页。", "裁剪留在目前分頁。", "このタブで切る。", "이 탭에서 자릅니다.", "Cắt trong tab này.", "Potong di tab ini.", "El recorte queda en esta pestaña."),
            "s3t": L("Drop the MP3, WAV, or M4A", "拖入 MP3、WAV 或 M4A", "拖入 MP3、WAV 或 M4A", "MP3 / WAV / M4Aをドロップ", "MP3, WAV 또는 M4A 넣기", "Thả MP3, WAV hoặc M4A", "Letakkan MP3, WAV, atau M4A", "Suelte MP3, WAV o M4A"),
            "s3b": L("If nothing plays, the codec may be unsupported. Try WAV or another browser.", "播不了，可能是编码不支持。换 WAV 或换浏览器。", "播不了，可能是編碼不支援。換 WAV 或換瀏覽器。", "再生できないならコーデック不可。WAVか別ブラウザ。", "재생이 안 되면 코덱 문제일 수 있습니다. WAV나 다른 브라우저를 시도하세요.", "Không phát được thì codec không hỗ trợ. Thử WAV hoặc trình duyệt khác.", "Tidak diputar: codec mungkin tidak didukung. Coba WAV atau peramban lain.", "Si no suena, el códec puede no valer. Pruebe WAV u otro navegador."),
            "s4t": L("Set start and end, then listen", "定起点和终点，再听", "定起點和終點，再聽", "開始と終了を付けて聴く", "시작과 끝을 정한 뒤 듣기", "Đặt đầu và cuối, rồi nghe", "Set awal dan akhir, lalu dengar", "Fije inicio y fin, y escuche"),
            "s4b": L("Play the selection in the page. If the first word is clipped, nudge start earlier. If a breath hangs at the end, pull end in.", "在页面里先播选段。第一个字被切了，就把起点提前。结尾还在喘气，就把终点往回收。", "在頁面裡先播選段。第一個字被切了，就把起點提前。結尾還在喘氣，就把終點往回收。", "ページで範囲を再生。最初の語が切れたら開始を前に。末尾の息が残るなら終了を詰める。", "페이지에서 선택 구간을 재생하세요. 첫 단어가 잘리면 시작을 앞당기세요. 끝에 숨이 남으면 끝을 당기세요.", "Phát đoạn trong trang. Từ đầu bị cắt thì kéo start sớm hơn. Hơi thừa ở cuối thì kéo end vào.", "Putar pilihan di halaman. Kata pertama terpotong: geser awal lebih awal. Napas di akhir: tarik akhir masuk.", "Reproduzca la selección en la página. Si se corta la primera palabra, adelante el inicio. Si queda un respiro al final, recoja el fin."),
            "s5t": L("Download WAV", "下载 WAV", "下載 WAV", "WAVを保存", "WAV 받기", "Tải WAV", "Unduh WAV", "Descargue WAV"),
            "s5b": L("The export is WAV even if you started from MP3. If a form insists on MP3, convert the WAV afterwards. Keep the original.", "即使拖进来是 MP3，导出也是 WAV。表单只要 MP3，就再转一次。原文件留下。", "即使拖進來是 MP3，匯出也是 WAV。表單只要 MP3，就再轉一次。原檔留下。", "元がMP3でも書き出しはWAV。フォームがMP3なら後で変換。原版は残す。", "MP3를 넣어도 보낸 파일은 WAV입니다. 폼이 MP3만 받으면 나중에 변환하세요. 원본은 남깁니다.", "Dù thả MP3, xuất vẫn WAV. Form bắt MP3 thì đổi sau. Giữ gốc.", "Meski mulai dari MP3, ekspor WAV. Formulir minta MP3: konversi nanti. Simpan asli.", "La exportación es WAV aunque empezara en MP3. Si el formulario exige MP3, conviértalo después. Conserve el original."),
            "s6t": L("Play the downloaded file once", "把下载的文件播一遍", "把下載的檔播一遍", "保存したファイルを一度再生", "받은 파일을 한 번 재생", "Phát file đã tải một lần", "Putar file unduhan sekali", "Reproduzca el archivo descargado una vez"),
            "s6b": L("Do not send on the in-page preview alone. If the start is late or the end is early, trim again.", "不要只信页面里的预览。起点晚了或终点早了，就再裁一次。", "不要只信頁面裡的預覽。起點晚了或終點早了，就再裁一次。", "ページ内プレビューだけで送らない。開始が遅い・終了が早いなら切り直す。", "페이지 미리보기만 믿고 보내지 마세요. 시작이 늦거나 끝이 빠르면 다시 자르세요.", "Đừng gửi chỉ vì nghe trong trang. Đầu muộn hoặc cuối sớm thì cắt lại.", "Jangan kirim hanya dari pratinjau halaman. Awal terlambat atau akhir terlalu cepat: potong lagi.", "No envíe solo por la vista previa. Si el inicio llega tarde o el final se queda corto, recorte otra vez."),
            "diagram1": L("Start and end on the waveform. Listen to the selection before you download.", "在波形上标起点和终点。下载前先听选段。", "在波形上標起點和終點。下載前先聽選段。", "波形に開始と終了。保存前に範囲を聴く。", "파형에 시작과 끝. 받기 전에 선택 구간을 들으세요.", "Đầu và cuối trên sóng. Nghe đoạn trước khi tải.", "Awal dan akhir di gelombang. Dengar pilihan sebelum unduh.", "Inicio y fin en la forma de onda. Escuche la selección antes de descargar."),
            "diagram2": L("Export is WAV. Play the file. The original MP3 stays on disk.", "导出是 WAV。播文件。原来的 MP3 还在磁盘上。", "匯出是 WAV。播檔。原來的 MP3 還在磁碟上。", "書き出しはWAV。ファイルを再生。元のMP3は残る。", "보낸 파일은 WAV. 파일을 재생. 원래 MP3는 디스크에 남습니다.", "Xuất là WAV. Phát file. MP3 gốc còn trên đĩa.", "Ekspor WAV. Putar file. MP3 asli tetap di disk.", "La exportación es WAV. Reproduzca el archivo. El MP3 original sigue en el disco."),
        },
        {
            "q1": L("How do I cut an MP3 online for free?", "怎么免费在线剪 MP3？", "怎麼免費線上剪 MP3？", "MP3を無料で切るには？", "MP3를 무료로 자르려면?", "Cắt MP3 online miễn phí?", "Potong MP3 gratis online?", "¿Cómo recorto un MP3 gratis en línea?"),
            "a1": L("Drop it on cv.cm audio cutter in this tab, mark start and end, listen, download WAV. Nothing is uploaded.", "拖进 cv.cm 的音频裁剪，标起点终点，先听，再下载 WAV。不上传。", "拖進 cv.cm 的音訊裁剪，標起點終點，先聽，再下載 WAV。不上傳。", "このタブのカットにドロップし、開始と終了を付け、聴いてWAVを保存。アップロードなし。", "이 탭의 오디오 자르기에 넣고 시작과 끝을 표시한 뒤 들어보고 WAV를 받으세요. 업로드 없음.", "Thả vào cắt audio cv.cm trong tab này, đánh đầu cuối, nghe, tải WAV. Không tải lên.", "Letakkan di potong audio cv.cm di tab ini, tandai awal/akhir, dengar, unduh WAV. Tidak diunggah.", "Suelte el archivo en recortar audio de cv.cm, marque inicio y fin, escuche y descargue WAV. Nada se sube."),
            "q2": L("Why is the download WAV, not MP3?", "为什么下载是 WAV 不是 MP3？", "為什麼下載是 WAV 不是 MP3？", "保存がWAVなのはなぜ？", "받은 파일이 WAV인 이유는?", "Sao tải về là WAV không phải MP3?", "Kenapa unduhan WAV, bukan MP3?", "¿Por qué la descarga es WAV y no MP3?"),
            "a2": L("The cutter re-encodes the selection as WAV in the browser. If you need MP3, convert the WAV afterwards.", "裁剪在浏览器里把选段重编码成 WAV。还要 MP3，就再转一次。", "裁剪在瀏覽器裡把選段重編碼成 WAV。還要 MP3，就再轉一次。", "選択をブラウザでWAVに再エンコードする。MP3が要るなら後で変換。", "선택 구간을 브라우저에서 WAV로 다시 인코딩합니다. MP3가 필요하면 나중에 변환하세요.", "Công cụ mã hóa lại đoạn thành WAV trong trình duyệt. Cần MP3 thì đổi sau.", "Pemotong meng-encode ulang pilihan jadi WAV di peramban. Butuh MP3: konversi nanti.", "El recorte recodifica la selección a WAV en el navegador. Si necesita MP3, conviértalo después."),
            "q3": L("Can I trim M4A or voice memos?", "能剪 M4A 或语音备忘录吗？", "能剪 M4A 或語音備忘錄嗎？", "M4Aやボイスメモは？", "M4A나 음성 메모는?", "Cắt M4A hoặc ghi âm?", "Potong M4A atau memo suara?", "¿Puedo recortar M4A o notas de voz?"),
            "a3": L("If the browser can decode the file, yes. If playback fails, export WAV from the recorder first.", "浏览器解得开就可以。播不了，先从录音机导出 WAV。", "瀏覽器解得開就可以。播不了，先從錄音機匯出 WAV。", "ブラウザがデコードできれば可。再生できないなら先にWAVを書き出す。", "브라우저가 풀 수 있으면 됩니다. 재생이 안 되면 녹음기에서 WAV로 먼저 보내세요.", "Trình duyệt giải được thì được. Không phát được thì xuất WAV từ máy ghi trước.", "Jika peramban bisa decode, ya. Gagal diputar: ekspor WAV dari perekam dulu.", "Si el navegador lo decodifica, sí. Si no suena, exporte WAV desde la grabadora primero."),
            "q4": L("Is the audio uploaded?", "会上传吗？", "會上傳嗎？", "アップロードされる？", "업로드되나요?", "Có tải lên không?", "Apakah diunggah?", "¿Se sube el audio?"),
            "a4": L("No. Closing the tab discards it.", "不会。关掉标签页就没了。", "不會。關掉分頁就沒了。", "しない。タブを閉じると消える。", "아니요. 탭을 닫으면 사라집니다.", "Không. Đóng tab là mất.", "Tidak. Tutup tab, hilang.", "No. Al cerrar la pestaña se pierde."),
            "q5": L("Will this change the original file?", "会改原文件吗？", "會改原檔嗎？", "元ファイルは変わる？", "원본이 바뀌나요?", "Có sửa file gốc không?", "Apakah file asli berubah?", "¿Cambia el archivo original?"),
            "a5": L("No. You download a new WAV. The MP3 on disk stays.", "不会。你下载的是新 WAV。磁盘上的 MP3 还在。", "不會。你下載的是新 WAV。磁碟上的 MP3 還在。", "しない。新しいWAVを保存。元のMP3は残る。", "아니요. 새 WAV를 받습니다. 디스크의 MP3는 그대로입니다.", "Không. Bạn tải WAV mới. MP3 trên đĩa còn.", "Tidak. Anda mengunduh WAV baru. MP3 di disk tetap.", "No. Descarga un WAV nuevo. El MP3 del disco se queda."),
        },
    ),
}

META = {
    "titleMakeCollage": L("How to make a photo collage | cv.cm", "怎么做照片拼图 | cv.cm", "怎麼做照片拼圖 | cv.cm", "写真コラージュの作り方 | cv.cm", "사진 콜라주 만드는 법 | cv.cm", "Cách làm ảnh ghép | cv.cm", "Cara buat kolase foto | cv.cm", "Cómo hacer un collage de fotos | cv.cm"),
    "descMakeCollage": L("Pick a grid and size, drop photos, choose Contain vs Cover so faces stay intact, download, then check at 100%. Nothing is uploaded.", "先选宫格和尺寸，放入照片，用 Contain 还是 Cover 免得切脸，下载后用 100% 看。不上传。", "先選宮格和尺寸，放入照片，用 Contain 還是 Cover 免得切臉，下載後用 100% 看。不上傳。", "グリッドとサイズを選び、写真を入れ、Contain/Coverで顔を守り、100%で確認。アップロードなし。", "격자와 크기를 고르고 사진을 넣은 뒤 Contain/Cover로 얼굴을 지키고 100%로 확인하세요. 업로드 없음.", "Chọn lưới và cỡ, thả ảnh, Contain hay Cover để khỏi cắt mặt, tải, xem 100%. Không tải lên.", "Pilih kisi dan ukuran, letakkan foto, Contain vs Cover agar wajah utuh, unduh, cek 100%. Tidak diunggah.", "Elija cuadrícula y tamaño, suelte fotos, Contain o Cover para no cortar caras, descargue y mire al 100%. Nada se sube."),
    "titleMakeMeme": L("How to make a meme | cv.cm", "怎么做表情包 | cv.cm", "怎麼做迷因圖 | cv.cm", "ミームの作り方 | cv.cm", "밈 만드는 법 | cv.cm", "Cách làm meme | cv.cm", "Cara buat meme | cv.cm", "Cómo hacer un meme | cv.cm"),
    "descMakeMeme": L("Drop a photo, type short top and bottom lines, download a PNG, then check it at phone width. Nothing is uploaded.", "放入照片，上下打短句，下载 PNG，再用手机宽度看。不上传。", "放入照片，上下打短句，下載 PNG，再用手機寬度看。不上傳。", "写真を入れ、上下に短い行、PNGを保存しスマホ幅で見る。アップロードなし。", "사진을 넣고 위아래 짧은 줄을 쓴 뒤 PNG를 받아 폰 너비로 보세요. 업로드 없음.", "Thả ảnh, chữ trên dưới ngắn, tải PNG, xem bề ngang điện thoại. Không tải lên.", "Letakkan foto, baris atas/bawah pendek, unduh PNG, cek lebar ponsel. Tidak diunggah.", "Suelte una foto, líneas cortas arriba y abajo, descargue PNG y mírelo al ancho del teléfono. Nada se sube."),
    "titleCountWords": L("How to count words and characters | cv.cm", "怎么统计字数和词数 | cv.cm", "怎麼統計字數和詞數 | cv.cm", "単語と文字数の数え方 | cv.cm", "단어·글자 수 세는 법 | cv.cm", "Cách đếm từ và ký tự | cv.cm", "Cara hitung kata dan karakter | cv.cm", "Cómo contar palabras y caracteres | cv.cm"),
    "descCountWords": L("Paste the draft, read words or characters (or characters with no spaces for Chinese homework), trim to the cap, recount. Nothing is uploaded.", "贴上稿子，看词数或字符（中文作业看不含空格），按上限删完再数。不上传。", "貼上稿子，看詞數或字元（中文作業看不含空格），按上限刪完再數。不上傳。", "原稿を貼り、単語か文字（中国語宿題は空白なし）を見て、上限まで削って再カウント。アップロードなし。", "초안을 붙여 단어 또는 글자(중국어 숙제는 공백 없는 글자)를 보고 한도에 맞춰 줄인 뒤 다시 세요. 업로드 없음.", "Dán bản thảo, đọc từ hoặc ký tự (bài Trung: không khoảng), cắt theo hạn, đếm lại. Không tải lên.", "Tempel draf, baca kata atau karakter (PR Tionghoa: tanpa spasi), potong ke batas, hitung lagi. Tidak diunggah.", "Pegue el borrador, mire palabras o caracteres (sin espacios para deberes en chino), recorte al tope y vuelva a contar. Nada se sube."),
    "titleTrimAudio": L("How to trim audio / cut an MP3 | cv.cm", "怎么裁剪音频 / 剪 MP3 | cv.cm", "怎麼裁剪音訊 / 剪 MP3 | cv.cm", "音声のトリム / MP3を切る方法 | cv.cm", "오디오 자르기 / MP3 컷하는 법 | cv.cm", "Cách cắt audio / cắt MP3 | cv.cm", "Cara potong audio / potong MP3 | cv.cm", "Cómo recortar audio / cortar un MP3 | cv.cm"),
    "descTrimAudio": L("Mark start and end, listen in the page, download WAV, then play the file. The original stays on disk. Nothing is uploaded.", "标起点终点，在页面里先听，下载 WAV，再播文件。原文件还在。不上传。", "標起點終點，在頁面裡先聽，下載 WAV，再播檔。原檔還在。不上傳。", "開始と終了を付け、ページで聴き、WAVを保存して再生。元は残る。アップロードなし。", "시작과 끝을 표시하고 페이지에서 들은 뒤 WAV를 받아 파일을 재생하세요. 원본은 남습니다. 업로드 없음.", "Đánh đầu cuối, nghe trong trang, tải WAV, phát file. Bản gốc còn. Không tải lên.", "Tandai awal/akhir, dengar di halaman, unduh WAV, putar file. Asli tetap. Tidak diunggah.", "Marque inicio y fin, escuche en la página, descargue WAV y reprodúzcalo. El original se queda. Nada se sube."),
}

GROUPS = {
    "audio": L("Audio", "音频", "音訊", "音声", "오디오", "Âm thanh", "Audio", "Audio"),
    "text": L("Text", "文字", "文字", "テキスト", "텍스트", "Chữ", "Teks", "Texto"),
}


def inject() -> None:
    for loc, path in FILES.items():
        data = json.loads(path.read_text())
        data["faq"].setdefault("learn", {})
        data["learn"]["groups"]["audio"] = GROUPS["audio"][loc]
        data["learn"]["groups"]["text"] = GROUPS["text"][loc]
        for lesson_id, payload in LESSONS.items():
            data["learn"][lesson_id] = payload["copy"][loc]
            data["faq"]["learn"][lesson_id] = payload["faq"][loc]
        for key, by_loc in META.items():
            data["meta"][key] = by_loc[loc]
        path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n")
        print("patched", path.name, list(LESSONS))


if __name__ == "__main__":
    inject()
