#!/usr/bin/env python3
"""Inject JSON, Base64, Unix time, and JWT how-tos."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LOCS = ["en", "zh-CN", "zh-TW", "ja", "ko", "vi", "id", "es"]
FILES = {loc: ROOT / "src/locales" / f"{loc}.json" for loc in LOCS}
COPY_KEYS = [
    "name", "blurb", "title", "lead", "result", "note",
    "s1t", "s1b", "s2t", "s2b", "s3t", "s3b", "s4t", "s4b", "s5t", "s5b", "s6t", "s6b",
    "diagram1", "diagram2",
]
FAQ_KEYS = [f"{side}{i}" for i in range(1, 6) for side in ("q", "a")]


def L(*vals: str) -> dict[str, str]:
    if len(vals) != 8:
        raise ValueError(len(vals), vals[0] if vals else None)
    return dict(zip(LOCS, vals))


def lesson(fields: dict[str, dict[str, str]], faq: dict[str, dict[str, str]]) -> dict:
    missing = [k for k in COPY_KEYS if k not in fields]
    missing += [k for k in FAQ_KEYS if k not in faq]
    if missing:
        raise SystemExit(f"missing keys: {missing}")
    if not fields["title"]["en"].startswith("How to "):
        raise SystemExit(fields["title"]["en"])
    return {
        "copy": {loc: {k: v[loc] for k, v in fields.items()} for loc in LOCS},
        "faq": {loc: {k: v[loc] for k, v in faq.items()} for loc in LOCS},
    }


LESSONS = {
    "format-json": lesson(
        {
            "name": L("How to format JSON", "怎么格式化 JSON", "怎麼格式化 JSON", "JSONの整形方法", "JSON 포맷하는 법", "Cách định dạng JSON", "Cara format JSON", "Cómo formatear JSON"),
            "blurb": L("Pretty-print with two spaces or minify to one line, then copy the output. Comments and trailing commas are not JSON.", "用两个空格排开，或压成一行，再复制结果。注释和末尾逗号不是 JSON。", "用兩個空格排開，或壓成一行，再複製結果。註解和末尾逗號不是 JSON。", "2スペースで整形するか1行に圧縮し、結果をコピー。コメントと末尾カンマはJSONではない。", "두 칸 들여쓰기로 펼치거나 한 줄로 줄인 뒤 결과를 복사하세요. 주석과 끝의 쉼표는 JSON이 아닙니다.", "In hai dấu cách hoặc nén một dòng, rồi copy kết quả. Chú thích và dấu phẩy cuối không phải JSON.", "Rapihkan dengan dua spasi atau padatkan satu baris, lalu salin hasilnya. Komentar dan koma di akhir bukan JSON.", "Indente con dos espacios o minifique a una línea y copie el resultado. Los comentarios y la coma final no son JSON."),
            "title": L("How to format JSON", "怎么格式化 JSON", "怎麼格式化 JSON", "JSONの整形方法", "JSON 포맷하는 법", "Cách định dạng JSON", "Cara format JSON", "Cómo formatear JSON"),
            "lead": L("You have text that should be JSON. You will paste it in this tab, pick pretty or minify, and copy a result that parsed. A log prefix in front of the brace is not JSON yet.", "你手里是一段应该是 JSON 的文字。贴进当前标签页，选排开或压成一行，只复制能解析的结果。大括号前面的日志前缀还不是 JSON。", "你手上是一段應該是 JSON 的文字。貼進目前分頁，選排開或壓成一行，只複製能解析的結果。大括號前面的日誌前綴還不是 JSON。", "JSONであるはずのテキストがある。このタブに貼り、整形か圧縮を選び、解析できた結果だけコピーする。{ の前のログ接頭辞はまだJSONではない。", "JSON이어야 할 텍스트가 있습니다. 이 탭에 붙이고 펼치기나 한 줄 중 고른 뒤, 파싱된 결과만 복사하세요. 중괄호 앞의 로그 접두어는 아직 JSON이 아닙니다.", "Bạn có đoạn phải là JSON. Dán vào tab này, chọn giãn hoặc nén một dòng, chỉ copy kết quả phân tích được. Tiền tố log trước dấu ngoặc chưa phải JSON.", "Anda punya teks yang harusnya JSON. Tempel di tab ini, pilih rapi atau satu baris, salin hanya hasil yang terurai. Awalan log di depan kurung belum JSON.", "Tiene un texto que debería ser JSON. Péguelo aquí, elija expandir o minificar, y copie solo un resultado que se analizó. Un prefijo de log delante de la llave aún no es JSON."),
            "result": L("JSON that parsed: two-space indent, or one line, with the same keys and values you pasted.", "解析成功的 JSON：两个空格缩进，或一行。键和值与你贴进去的相同。", "解析成功的 JSON：兩個空格縮排，或一行。鍵和值與你貼進去的相同。", "解析できたJSON。2スペースか1行。キーと値は貼ったものと同じ。", "파싱된 JSON. 두 칸 들여쓰기 또는 한 줄. 키와 값은 붙인 것과 같습니다.", "JSON phân tích được: thụt hai dấu cách, hoặc một dòng. Khóa và giá trị như bạn dán.", "JSON yang terurai: indent dua spasi, atau satu baris. Kunci dan nilai sama dengan yang ditempel.", "JSON que se analizó: sangría de dos espacios, o una línea, con las mismas claves y valores que pegó."),
            "note": L("Open the JSON formatter when the text is in front of you. Pretty uses two spaces. Minify is one line. Nothing is uploaded.", "文字在眼前再打开 JSON 格式化。排开是两个空格。压成一行就是一行。不上传。", "文字在眼前再打開 JSON 格式化。排開是兩個空格。壓成一行就是一行。不上傳。", "テキストが手元にあってから開く。整形は2スペース。圧縮は1行。アップロードなし。", "텍스트가 앞에 있을 때 JSON 포맷을 여세요. 펼치기는 두 칸. 줄이기는 한 줄. 업로드 없음.", "Có sẵn chữ thì mở định dạng JSON. Giãn là hai dấu cách. Nén là một dòng. Không tải lên.", "Teks sudah di depan, baru buka format JSON. Rapi memakai dua spasi. Padat adalah satu baris. Tidak diunggah.", "Abra el formateador cuando el texto esté delante. Expandir usa dos espacios. Minificar es una línea. Nada se sube."),
            "s1t": L("Decide reading layout or one line", "先定是给读还是给发", "先定是給讀還是給發", "読む用か送る用か決める", "읽기용인지 보내기용인지 정하기", "Quyết để đọc hay để gửi", "Tentukan untuk dibaca atau dikirim", "Decida si es para leer o para enviar"),
            "s1b": L("Pretty is for reading. Minify is for a header, a query, or a small file. Both parse first. Invalid text is not repaired for you.", "给读就排开。给请求头、查询或小文件就压成一行。两种都先解析。无效文字不会替你改好。", "給讀就排開。給請求頭、查詢或小檔就壓成一行。兩種都先解析。無效文字不會替你改好。", "読むなら整形。ヘッダ・クエリ・小さいファイルなら1行。どちらも先に解析。壊れた文は直さない。", "읽으려면 펼치기. 헤더, 쿼리, 작은 파일이면 한 줄. 둘 다 먼저 파싱합니다. 잘못된 글을 고쳐 주지는 않습니다.", "Để đọc thì giãn. Cho header, query hoặc file nhỏ thì một dòng. Cả hai phân tích trước. Chữ sai sẽ không được sửa hộ.", "Untuk dibaca: rapi. Untuk header, query, atau file kecil: satu baris. Keduanya diurai dulu. Teks rusak tidak diperbaiki.", "Para leer, expanda. Para una cabecera, una consulta o un archivo pequeño, una línea. Ambos analizan primero. El texto inválido no se repara solo."),
            "s2t": L("Open the JSON formatter on cv.cm", "打开 cv.cm 的 JSON 格式化", "打開 cv.cm 的 JSON 格式化", "cv.cmのJSON整形を開く", "cv.cm JSON 포맷을 열기", "Mở định dạng JSON trên cv.cm", "Buka format JSON di cv.cm", "Abra el formateador JSON en cv.cm"),
            "s2b": L("Work stays in this tab.", "处理留在当前标签页。", "處理留在目前分頁。", "このタブで処理。", "이 탭에서 합니다.", "Làm trong tab này.", "Proses di tab ini.", "El trabajo queda en esta pestaña."),
            "s3t": L("Paste the value, not the log prefix", "只贴 JSON，不要贴日志前缀", "只貼 JSON，不要貼日誌前綴", "値だけ貼る。ログ接頭辞は貼らない", "값만 붙이기. 로그 접두어는 빼기", "Chỉ dán giá trị, đừng dán tiền tố log", "Tempel nilainya, bukan awalan log", "Pegue el valor, no el prefijo del log"),
            "s3b": L("Start at the first { or [ and stop at its match. A time or the word INFO in front makes the whole paste invalid.", "从第一个 { 或 [ 起，到它配对的结束。前面的时间或 INFO 会让整段无效。", "從第一個 { 或 [ 起，到它配對的結束。前面的時間或 INFO 會讓整段無效。", "最初の { か [ から、対応する閉じまで。前の時刻や INFO があると全体が無効。", "첫 { 또는 [ 부터 짝까지. 앞의 시각이나 INFO 가 있으면 전체가 무효입니다.", "Từ { hoặc [ đầu tiên đến dấu đóng cặp. Thời gian hoặc chữ INFO phía trước làm cả đoạn hỏng.", "Mulai dari { atau [ pertama sampai pasangan penutup. Waktu atau INFO di depan membuat seluruh tempelan gagal.", "Empiece en la primera { o [ y pare en su cierre. Una hora o la palabra INFO delante invalida todo el pegado."),
            "s4t": L("If it says invalid, fix the text", "显示无效就改文字", "顯示無效就改文字", "無効と言われたら文を直す", "무효라고 나오면 글을 고치기", "Báo không hợp lệ thì sửa chữ", "Jika tidak valid, perbaiki teksnya", "Si dice inválido, corrija el texto"),
            "s4b": L("JSON wants double quotes, no comments, and no comma after the last item. Single quotes, undefined, and NaN are not JSON. An integer longer than 15 digits must be a string in quotes, or the digits can change.", "JSON 要双引号，不能有注释，最后一项后面不能有逗号。单引号、undefined、NaN 都不是 JSON。超过 15 位的整数必须加引号，否则数字会变。", "JSON 要雙引號，不能有註解，最後一項後面不能有逗號。單引號、undefined、NaN 都不是 JSON。超過 15 位的整數必須加引號，否則數字會變。", "JSONは二重引用符。コメント不可。最後の後にカンマ不可。単引用符、undefined、NaNはJSONではない。15桁を超える整数は引用符で囲む。でないと桁が変わる。", "JSON은 큰따옴표, 주석 없음, 마지막 항목 뒤 쉼표 없음. 작은따옴표, undefined, NaN은 JSON이 아닙니다. 15자리를 넘는 정수는 따옴표 문자열이어야 합니다. 아니면 숫자가 바뀝니다.", "JSON cần ngoặc kép, không chú thích, không dấu phẩy sau mục cuối. Ngoặc đơn, undefined, NaN không phải JSON. Số nguyên dài hơn 15 chữ số phải nằm trong ngoặc kép, không thì các chữ số có thể đổi.", "JSON minta tanda kutip ganda, tanpa komentar, tanpa koma setelah item terakhir. Kutip tunggal, undefined, dan NaN bukan JSON. Bilangan bulat lebih dari 15 digit harus string dalam kutip, atau angkanya bisa berubah.", "JSON pide comillas dobles, sin comentarios y sin coma tras el último elemento. Comillas simples, undefined y NaN no son JSON. Un entero de más de 15 dígitos debe ir entre comillas, o los dígitos pueden cambiar."),
            "s5t": L("Copy the output", "复制结果", "複製結果", "結果をコピー", "결과 복사", "Copy kết quả", "Salin hasilnya", "Copie el resultado"),
            "s5b": L("Pretty is a two-space indent. Minify is one line. Copy that box, not the broken input.", "排开是两个空格。压成一行就是一行。复制那个框，不要复制坏掉的输入。", "排開是兩個空格。壓成一行就是一行。複製那個框，不要複製壞掉的輸入。", "整形は2スペース。圧縮は1行。その欄をコピー。壊れた入力はコピーしない。", "펼치기는 두 칸 들여쓰기. 줄이기는 한 줄. 그 칸을 복사하세요. 깨진 입력은 복사하지 마세요.", "Giãn là thụt hai dấu cách. Nén là một dòng. Copy ô đó, đừng copy phần nhập hỏng.", "Rapi adalah indent dua spasi. Padat adalah satu baris. Salin kotak itu, bukan masukan yang rusak.", "Expandir es sangría de dos espacios. Minificar es una línea. Copie esa caja, no la entrada rota."),
            "s6t": L("Check one value you already know", "核对一个你本来就知道的值", "核對一個你本來就知道的值", "知っている値を一つ照合", "이미 아는 값 하나를 대조", "Đối chiếu một giá trị bạn đã biết", "Cek satu nilai yang sudah Anda tahu", "Compruebe un valor que ya conoce"),
            "s6b": L("A name, a count, or an id. If a long number changed, it was a bare integer past the safe range. Put it in quotes and format again.", "一个名字、一个数量或一个 id。长数字变了，就是裸整数超出了安全范围。加上引号再格式化一次。", "一個名字、一個數量或一個 id。長數字變了，就是裸整數超出了安全範圍。加上引號再格式化一次。", "名前、個数、id。長い数字が変わったら、安全範囲を超えた裸の整数。引用符で囲んでやり直す。", "이름, 개수, 또는 id. 긴 숫자가 바뀌었다면 안전 범위를 넘은 맨 정수입니다. 따옴표를 넣고 다시 포맷하세요.", "Một tên, một số lượng hoặc một id. Số dài đổi thì đó là số nguyên trần vượt khoảng an toàn. Đặt trong ngoặc kép rồi định dạng lại.", "Nama, jumlah, atau id. Angka panjang berubah: itu bilangan bulat telanjang di luar rentang aman. Taruh dalam kutip dan format lagi.", "Un nombre, una cantidad o un id. Si un número largo cambió, era un entero desnudo fuera del rango seguro. Póngalo entre comillas y formatee otra vez."),
            "diagram1": L("Pretty is two spaces for reading. Minify is one line for sending. Both must parse.", "给读就两个空格。给发就一行。两种都要能解析。", "給讀就兩個空格。給發就一行。兩種都要能解析。", "読むなら2スペース。送るなら1行。どちらも解析できること。", "읽기는 두 칸. 보내기는 한 줄. 둘 다 파싱되어야 합니다.", "Để đọc: hai dấu cách. Để gửi: một dòng. Cả hai phải phân tích được.", "Untuk dibaca: dua spasi. Untuk dikirim: satu baris. Keduanya harus terurai.", "Para leer, dos espacios. Para enviar, una línea. Ambos deben analizarse."),
            "diagram2": L("Copy the output. An integer longer than 15 digits belongs in quotes.", "复制结果。超过 15 位的整数要加引号。", "複製結果。超過 15 位的整數要加引號。", "結果をコピー。15桁を超える整数は引用符で。", "결과를 복사하세요. 15자리를 넘는 정수는 따옴표 안에.", "Copy kết quả. Số nguyên dài hơn 15 chữ số phải trong ngoặc kép.", "Salin hasilnya. Bilangan bulat lebih dari 15 digit harus dalam kutip.", "Copie el resultado. Un entero de más de 15 dígitos va entre comillas."),
        },
        {
            "q1": L("Can I format JSON free online?", "可以免费在线格式化 JSON 吗？", "可以免費線上格式化 JSON 嗎？", "JSONを無料で整形できる？", "JSON을 무료로 포맷할 수 있나요?", "Định dạng JSON miễn phí online được không?", "Bisa format JSON gratis online?", "¿Puedo formatear JSON gratis en línea?"),
            "a1": L("Yes. cv.cm pretty-prints or minifies in this tab. Nothing is uploaded.", "可以。cv.cm 在当前标签页排开或压成一行。不上传。", "可以。cv.cm 在目前分頁排開或壓成一行。不上傳。", "できる。このタブで整形または1行にする。アップロードなし。", "됩니다. 이 탭에서 펼치거나 한 줄로 만듭니다. 업로드 없음.", "Được. Giãn hoặc nén trong tab này. Không tải lên.", "Ya. Merapikan atau memadatkan di tab ini. Tidak diunggah.", "Sí. Se expande o se minifica en esta pestaña. Nada se sube."),
            "q2": L("Why does my JSON fail?", "为什么我的 JSON 无效？", "為什麼我的 JSON 無效？", "なぜ無効？", "왜 JSON이 실패하나요?", "Sao JSON của tôi hỏng?", "Kenapa JSON saya gagal?", "¿Por qué falla mi JSON?"),
            "a2": L("Comments, a comma after the last item, and single quotes are not JSON. Strip a log prefix before the first brace.", "注释、最后一项后面的逗号、单引号都不是 JSON。去掉第一个大括号前面的日志前缀。", "註解、最後一項後面的逗號、單引號都不是 JSON。去掉第一個大括號前面的日誌前綴。", "コメント、最後の後のカンマ、単引用符はJSONではない。最初の括弧の前のログ接頭辞を取る。", "주석, 마지막 항목 뒤의 쉼표, 작은따옴표는 JSON이 아닙니다. 첫 중괄호 앞의 로그 접두어를 지우세요.", "Chú thích, dấu phẩy sau mục cuối và ngoặc đơn không phải JSON. Bỏ tiền tố log trước ngoặc đầu.", "Komentar, koma setelah item terakhir, dan kutip tunggal bukan JSON. Buang awalan log sebelum kurung pertama.", "Los comentarios, la coma tras el último elemento y las comillas simples no son JSON. Quite el prefijo de log antes de la primera llave."),
            "q3": L("What is the difference between pretty and minify?", "排开和压成一行有什么差别？", "排開和壓成一行有什麼差別？", "整形と圧縮の違いは？", "펼치기와 한 줄의 차이는?", "Giãn và nén khác gì?", "Apa beda rapi dan padat?", "¿Qué diferencia hay entre expandir y minificar?"),
            "a3": L("Pretty indents with two spaces. Minify is one line. The values stay the same when the text parsed.", "排开用两个空格缩进。压成一行就是一行。能解析时，值不变。", "排開用兩個空格縮排。壓成一行就是一行。能解析時，值不變。", "整形は2スペース。圧縮は1行。解析できれば値は同じ。", "펼치기는 두 칸 들여쓰기. 줄이기는 한 줄. 파싱되면 값은 같습니다.", "Giãn thụt hai dấu cách. Nén là một dòng. Phân tích được thì giá trị giữ nguyên.", "Rapi mengindent dua spasi. Padat adalah satu baris. Jika terurai, nilainya tetap.", "Expandir sangra con dos espacios. Minificar es una línea. Si se analizó, los valores siguen iguales."),
            "q4": L("Are long numbers safe?", "很长的数字安全吗？", "很長的數字安全嗎？", "長い数字は安全？", "긴 숫자는 안전한가요?", "Số dài có an toàn không?", "Angka panjang aman?", "¿Son seguros los números largos?"),
            "a4": L("An integer longer than 15 digits can change unless it is a string in quotes.", "超过 15 位的整数，除非加了引号，否则数字会变。", "超過 15 位的整數，除非加了引號，否則數字會變。", "15桁を超える整数は、引用符付き文字列でなければ桁が変わり得る。", "15자리를 넘는 정수는 따옴표 문자열이 아니면 바뀔 수 있습니다.", "Số nguyên dài hơn 15 chữ số có thể đổi nếu không nằm trong ngoặc kép.", "Bilangan bulat lebih dari 15 digit bisa berubah kecuali berupa string dalam kutip.", "Un entero de más de 15 dígitos puede cambiar si no es un texto entre comillas."),
            "q5": L("Is the text uploaded?", "文字会上传吗？", "文字會上傳嗎？", "アップロードされる？", "업로드되나요?", "Chữ có bị tải lên không?", "Apakah teks diunggah?", "¿Se sube el texto?"),
            "a5": L("No. Closing the tab discards it.", "不会。关掉标签页就没了。", "不會。關掉分頁就沒了。", "しない。タブを閉じると消える。", "아니요. 탭을 닫으면 사라집니다.", "Không. Đóng tab là mất.", "Tidak. Tutup tab, hilang.", "No. Al cerrar la pestaña se pierde."),
        },
    ),
    "decode-base64": lesson(
        {
            "name": L("How to decode Base64", "怎么解码 Base64", "怎麼解碼 Base64", "Base64のデコード方法", "Base64 디코딩하는 법", "Cách giải mã Base64", "Cara dekode Base64", "Cómo decodificar Base64"),
            "blurb": L("Decode standard Base64 to UTF-8 text, or encode text the other way. Minus and underscore are refused. A picture is not text.", "把标准 Base64 解成 UTF-8 文字，或反过来编码。减号和下划线会被拒绝。图片不是文字。", "把標準 Base64 解成 UTF-8 文字，或反過來編碼。減號和底線會被拒絕。圖片不是文字。", "標準Base64をUTF-8文字へ。または逆に符号化。マイナスとアンダースコアは拒否。画像は文字ではない。", "표준 Base64를 UTF-8 글로 풀거나, 글을 반대로 인코딩합니다. 빼기와 밑줄은 거부됩니다. 그림은 글이 아닙니다.", "Giải Base64 chuẩn thành chữ UTF-8, hoặc mã hóa chiều kia. Dấu trừ và gạch dưới bị từ chối. Ảnh không phải chữ.", "Dekode Base64 standar ke teks UTF-8, atau enkode sebaliknya. Tanda minus dan garis bawah ditolak. Gambar bukan teks.", "Decodifique Base64 estándar a texto UTF-8, o codifique al revés. El menos y el guion bajo se rechazan. Una imagen no es texto."),
            "title": L("How to decode Base64", "怎么解码 Base64", "怎麼解碼 Base64", "Base64のデコード方法", "Base64 디코딩하는 법", "Cách giải mã Base64", "Cara dekode Base64", "Cómo decodificar Base64"),
            "lead": L("You have a Base64 string, or text to encode. You will pick decode or encode in this tab and copy real text. This page prints UTF-8. It does not rebuild a PNG or a PDF.", "你有一段 Base64，或要编码的文字。在当前标签页选解码或编码，复制真正的文字。这一页打出 UTF-8。它不会把 PNG 或 PDF 还原成文件。", "你有一段 Base64，或要編碼的文字。在目前分頁選解碼或編碼，複製真正的文字。這一頁打出 UTF-8。它不會把 PNG 或 PDF 還原成檔案。", "Base64か、符号化したい文字がある。このタブでデコードかエンコードを選び、本物の文字をコピー。このページはUTF-8を出す。PNGやPDFをファイルに戻さない。", "Base64 문자열이나 인코딩할 글이 있습니다. 이 탭에서 디코드 또는 인코드를 고르고 실제 글을 복사하세요. 이 페이지는 UTF-8을 출력합니다. PNG나 PDF를 파일로 되돌리지 않습니다.", "Bạn có chuỗi Base64, hoặc chữ cần mã hóa. Chọn giải mã hoặc mã hóa trong tab này và copy chữ thật. Trang này in UTF-8. Nó không dựng lại PNG hay PDF.", "Anda punya string Base64, atau teks untuk dienkode. Pilih dekode atau enkode di tab ini dan salin teks yang nyata. Halaman ini mencetak UTF-8. Tidak membangun ulang PNG atau PDF.", "Tiene una cadena Base64, o texto para codificar. Elija decodificar o codificar aquí y copie texto real. Esta página imprime UTF-8. No reconstruye un PNG ni un PDF."),
            "result": L("UTF-8 text from standard Base64, or standard Base64 from the text you typed.", "从标准 Base64 得到的 UTF-8 文字，或从你输入的文字得到的标准 Base64。", "從標準 Base64 得到的 UTF-8 文字，或從你輸入的文字得到的標準 Base64。", "標準Base64から得たUTF-8、または入力した文字から得た標準Base64。", "표준 Base64에서 나온 UTF-8 글, 또는 입력한 글에서 나온 표준 Base64.", "Chữ UTF-8 từ Base64 chuẩn, hoặc Base64 chuẩn từ chữ bạn gõ.", "Teks UTF-8 dari Base64 standar, atau Base64 standar dari teks yang Anda ketik.", "Texto UTF-8 a partir de Base64 estándar, o Base64 estándar a partir del texto que escribió."),
            "note": L("Open Base64 when the string is in front of you. Decode wants A–Z, a–z, 0–9, plus, slash, and = padding. Nothing is uploaded.", "字符串在眼前再打开 Base64。解码要 A–Z、a–z、0–9、加号、斜杠和 = 填充。不上传。", "字串在眼前再打開 Base64。解碼要 A–Z、a–z、0–9、加號、斜線和 = 填充。不上傳。", "文字列が手元にあってから開く。デコードは A–Z、a–z、0–9、+、/、= のパディング。アップロードなし。", "문자열이 앞에 있을 때 Base64를 여세요. 디코드는 A–Z, a–z, 0–9, 더하기, 슬래시, = 패딩. 업로드 없음.", "Có chuỗi thì mở Base64. Giải mã cần A–Z, a–z, 0–9, dấu cộng, gạch chéo và đệm =. Không tải lên.", "String sudah di depan, baru buka Base64. Dekode minta A–Z, a–z, 0–9, plus, garis miring, dan padding =. Tidak diunggah.", "Abra Base64 cuando la cadena esté delante. Decodificar quiere A–Z, a–z, 0–9, más, barra y relleno =. Nada se sube."),
            "s1t": L("Look at the alphabet before you paste", "贴之前先看字母表", "貼之前先看字母表", "貼る前に文字種を見る", "붙이기 전에 알파벳을 보기", "Nhìn bảng chữ trước khi dán", "Lihat alfabet sebelum menempel", "Mire el alfabeto antes de pegar"),
            "s1b": L("Standard Base64 uses plus and slash. URL-safe uses minus and underscore. This page accepts only the standard alphabet. A data: prefix is not part of the payload.", "标准 Base64 用加号和斜杠。URL 安全用减号和下划线。这一页只接受标准字母表。data: 前缀不是内容的一部分。", "標準 Base64 用加號和斜線。URL 安全用減號和底線。這一頁只接受標準字母表。data: 前綴不是內容的一部分。", "標準は + と /。URLセーフは - と _。このページは標準だけ。data: 接頭辞は中身ではない。", "표준 Base64는 더하기와 슬래시. URL-safe는 빼기와 밑줄. 이 페이지는 표준만 받습니다. data: 접두어는 내용이 아닙니다.", "Base64 chuẩn dùng dấu cộng và gạch chéo. URL-safe dùng dấu trừ và gạch dưới. Trang này chỉ nhận bảng chuẩn. Tiền tố data: không thuộc nội dung.", "Base64 standar memakai plus dan garis miring. URL-safe memakai minus dan garis bawah. Halaman ini hanya menerima alfabet standar. Awalan data: bukan bagian isi.", "El Base64 estándar usa más y barra. El seguro para URL usa menos y guion bajo. Esta página solo acepta el alfabeto estándar. Un prefijo data: no es parte del contenido."),
            "s2t": L("Open Base64 on cv.cm", "打开 cv.cm 的 Base64", "打開 cv.cm 的 Base64", "cv.cmのBase64を開く", "cv.cm Base64를 열기", "Mở Base64 trên cv.cm", "Buka Base64 di cv.cm", "Abra Base64 en cv.cm"),
            "s2b": L("Work stays in this tab.", "处理留在当前标签页。", "處理留在目前分頁。", "このタブで処理。", "이 탭에서 합니다.", "Làm trong tab này.", "Proses di tab ini.", "El trabajo queda en esta pestaña."),
            "s3t": L("Choose decode or encode", "选解码或编码", "選解碼或編碼", "デコードかエンコードを選ぶ", "디코드 또는 인코드 고르기", "Chọn giải mã hoặc mã hóa", "Pilih dekode atau enkode", "Elija decodificar o codificar"),
            "s3b": L("Decode turns Base64 into text. Encode turns text into Base64 using UTF-8 bytes. Encoding a string that is already Base64 wraps it a second time.", "解码把 Base64 变成文字。编码用 UTF-8 字节把文字变成 Base64。已经是 Base64 的字符串再编码，会再包一层。", "解碼把 Base64 變成文字。編碼用 UTF-8 位元組把文字變成 Base64。已經是 Base64 的字串再編碼，會再包一層。", "デコードはBase64を文字に。エンコードはUTF-8バイトで文字をBase64に。既にBase64の文字列を符号化すると二重になる。", "디코드는 Base64를 글로. 인코드는 UTF-8 바이트로 글을 Base64로. 이미 Base64인 문자열을 인코드하면 한 번 더 감쌉니다.", "Giải mã biến Base64 thành chữ. Mã hóa biến chữ thành Base64 bằng byte UTF-8. Mã hóa chuỗi đã là Base64 sẽ bọc thêm một lần.", "Dekode mengubah Base64 menjadi teks. Enkode mengubah teks menjadi Base64 dengan byte UTF-8. Mengenkode string yang sudah Base64 membungkusnya sekali lagi.", "Decodificar convierte Base64 en texto. Codificar convierte texto en Base64 con bytes UTF-8. Codificar una cadena que ya es Base64 la envuelve otra vez."),
            "s4t": L("Paste the text", "贴上文字", "貼上文字", "テキストを貼る", "글 붙이기", "Dán chữ", "Tempel teksnya", "Pegue el texto"),
            "s4b": L("Line breaks and spaces are removed on decode. After that, the length must be a multiple of 4, with = only at the end.", "解码时会去掉换行和空格。去掉之后，长度必须是 4 的倍数，= 只能在末尾。", "解碼時會去掉換行和空格。去掉之後，長度必須是 4 的倍數，= 只能在末尾。", "デコード時に改行と空白は除く。その後の長さは4の倍数。= は末尾だけ。", "디코드할 때 줄바꿈과 공백은 빠집니다. 그 다음 길이는 4의 배수여야 하고 = 는 끝에만.", "Khi giải mã, xuống dòng và dấu cách bị bỏ. Sau đó độ dài phải chia hết cho 4, dấu = chỉ ở cuối.", "Saat dekode, baris baru dan spasi dihapus. Setelah itu panjang harus kelipatan 4, dan = hanya di akhir.", "Al decodificar se quitan saltos y espacios. Después, la longitud debe ser múltiplo de 4, con = solo al final."),
            "s5t": L("If decode fails, it is not UTF-8 text", "解码失败，就不是 UTF-8 文字", "解碼失敗，就不是 UTF-8 文字", "失敗したらUTF-8文字ではない", "디코드가 실패하면 UTF-8 글이 아님", "Giải mã thất bại thì không phải chữ UTF-8", "Jika dekode gagal, itu bukan teks UTF-8", "Si falla, no es texto UTF-8"),
            "s5b": L("Minus and underscore are refused. Missing = fails. A PNG, a PDF, or a data URL is bytes, so this page will not print it. Swap minus to plus and underscore to slash, and pad with =, only when you know the payload is text.", "减号和下划线会被拒绝。少了 = 也会失败。PNG、PDF 或 data URL 是字节，这一页不会把它打出来。只有确定内容是文字时，才把减号换成加号、下划线换成斜杠，并用 = 补齐。", "減號和底線會被拒絕。少了 = 也會失敗。PNG、PDF 或 data URL 是位元組，這一頁不會把它打出來。只有確定內容是文字時，才把減號換成加號、底線換成斜線，並用 = 補齊。", "- と _ は拒否。= 不足も失敗。PNG、PDF、data URL はバイトなのでこのページは出さない。中身が文字と分かっているときだけ - を + に、_ を / に替え、= で埋める。", "빼기와 밑줄은 거부됩니다. = 가 없어도 실패합니다. PNG, PDF, data URL은 바이트라 이 페이지는 출력하지 않습니다. 내용이 글이라는 것을 알 때만 빼기를 더하기로, 밑줄을 슬래시로 바꾸고 = 로 채우세요.", "Dấu trừ và gạch dưới bị từ chối. Thiếu = cũng thất bại. PNG, PDF hoặc data URL là byte, trang này không in ra. Chỉ khi biết nội dung là chữ mới đổi dấu trừ thành cộng, gạch dưới thành gạch chéo, và đệm bằng =.", "Minus dan garis bawah ditolak. = yang hilang juga gagal. PNG, PDF, atau data URL adalah byte, jadi halaman ini tidak mencetaknya. Ganti minus ke plus dan garis bawah ke garis miring, lalu isi dengan =, hanya jika Anda tahu isinya teks.", "El menos y el guion bajo se rechazan. Faltar = también falla. Un PNG, un PDF o un data URL son bytes, así que esta página no los imprime. Cambie menos por más y guion bajo por barra, y rellene con =, solo cuando sepa que el contenido es texto."),
            "s6t": L("Copy and check a word you expect", "复制，并核对一个你预期的词", "複製，並核對一個你預期的詞", "コピーして、予想した語を照合", "복사하고 예상한 단어를 대조", "Copy và đối chiếu một từ bạn chờ", "Salin dan cek satu kata yang Anda harapkan", "Copie y compruebe una palabra que espera"),
            "s6b": L("If the text is garbled, the bytes were not UTF-8. Drop that result. To check an encode, decode the output and you should see the same text.", "文字是乱码，就是字节不是 UTF-8。丢掉这个结果。要检查编码，就把结果再解码，应当看到同一段文字。", "文字是亂碼，就是位元組不是 UTF-8。丟掉這個結果。要檢查編碼，就把結果再解碼，應當看到同一段文字。", "文字化けならバイトはUTF-8ではない。その結果は捨てる。エンコードの確認は、出力をデコードして同じ文字が見えること。", "글이 깨졌다면 바이트가 UTF-8이 아닙니다. 그 결과는 버리세요. 인코드를 확인하려면 출력을 다시 디코드했을 때 같은 글이 보여야 합니다.", "Chữ vỡ nghĩa là byte không phải UTF-8. Bỏ kết quả đó. Muốn kiểm mã hóa, giải mã đầu ra và phải thấy cùng một đoạn.", "Jika teks berantakan, byte-nya bukan UTF-8. Buang hasil itu. Untuk cek enkode, dekode keluarannya dan Anda harus melihat teks yang sama.", "Si el texto está ilegible, los bytes no eran UTF-8. Tire ese resultado. Para comprobar una codificación, decodifique la salida y debe ver el mismo texto."),
            "diagram1": L("Standard uses plus and slash. URL-safe uses minus and underscore. This page wants standard Base64.", "标准用加号和斜杠。URL 安全用减号和下划线。这一页要标准 Base64。", "標準用加號和斜線。URL 安全用減號和底線。這一頁要標準 Base64。", "標準は + と /。URLセーフは - と _。このページは標準Base64。", "표준은 더하기와 슬래시. URL-safe는 빼기와 밑줄. 이 페이지는 표준 Base64.", "Chuẩn dùng dấu cộng và gạch chéo. URL-safe dùng dấu trừ và gạch dưới. Trang này cần Base64 chuẩn.", "Standar memakai plus dan garis miring. URL-safe memakai minus dan garis bawah. Halaman ini minta Base64 standar.", "El estándar usa más y barra. El seguro para URL usa menos y guion bajo. Esta página quiere Base64 estándar."),
            "diagram2": L("Decode prints UTF-8 text. A picture or a PDF fails. Copy a word you recognize.", "解码打出 UTF-8 文字。图片或 PDF 会失败。复制一个你认得的词。", "解碼打出 UTF-8 文字。圖片或 PDF 會失敗。複製一個你認得的詞。", "デコードはUTF-8を出す。画像やPDFは失敗。知っている語をコピー。", "디코드는 UTF-8 글을 출력합니다. 그림이나 PDF는 실패합니다. 알아보는 단어를 복사하세요.", "Giải mã in chữ UTF-8. Ảnh hoặc PDF sẽ thất bại. Copy một từ bạn nhận ra.", "Dekode mencetak teks UTF-8. Gambar atau PDF gagal. Salin kata yang Anda kenali.", "Decodificar imprime texto UTF-8. Una imagen o un PDF falla. Copie una palabra que reconozca."),
        },
        {
            "q1": L("Can I decode Base64 free online?", "可以免费在线解码 Base64 吗？", "可以免費線上解碼 Base64 嗎？", "Base64を無料でデコードできる？", "Base64를 무료로 디코딩할 수 있나요?", "Giải mã Base64 miễn phí online được không?", "Bisa dekode Base64 gratis online?", "¿Puedo decodificar Base64 gratis en línea?"),
            "a1": L("Yes. cv.cm encodes and decodes in this tab. Nothing is uploaded.", "可以。cv.cm 在当前标签页编码和解码。不上传。", "可以。cv.cm 在目前分頁編碼和解碼。不上傳。", "できる。このタブで符号化と復号。アップロードなし。", "됩니다. 이 탭에서 인코드하고 디코드합니다. 업로드 없음.", "Được. Mã hóa và giải mã trong tab này. Không tải lên.", "Ya. Enkode dan dekode di tab ini. Tidak diunggah.", "Sí. Se codifica y se decodifica en esta pestaña. Nada se sube."),
            "q2": L("Why does my string fail?", "为什么我的字符串失败？", "為什麼我的字串失敗？", "なぜ文字列が失敗する？", "왜 문자열이 실패하나요?", "Sao chuỗi của tôi thất bại?", "Kenapa string saya gagal?", "¿Por qué falla mi cadena?"),
            "a2": L("Minus and underscore are refused. The length must be a multiple of 4. Padding is =. Remove a data: prefix, and the payload must be text.", "减号和下划线会被拒绝。长度必须是 4 的倍数。填充是 =。去掉 data: 前缀，而且内容必须是文字。", "減號和底線會被拒絕。長度必須是 4 的倍數。填充是 =。去掉 data: 前綴，而且內容必須是文字。", "- と _ は拒否。長さは4の倍数。パディングは =。data: 接頭辞を外し、中身は文字であること。", "빼기와 밑줄은 거부됩니다. 길이는 4의 배수. 패딩은 =. data: 접두어를 지우고, 내용은 글이어야 합니다.", "Dấu trừ và gạch dưới bị từ chối. Độ dài phải chia hết cho 4. Đệm là =. Bỏ tiền tố data:, và nội dung phải là chữ.", "Minus dan garis bawah ditolak. Panjang harus kelipatan 4. Padding adalah =. Hapus awalan data:, dan isinya harus teks.", "El menos y el guion bajo se rechazan. La longitud debe ser múltiplo de 4. El relleno es =. Quite el prefijo data:, y el contenido debe ser texto."),
            "q3": L("Can I decode an image?", "能解码图片吗？", "能解碼圖片嗎？", "画像をデコードできる？", "이미지를 디코딩할 수 있나요?", "Giải mã được ảnh không?", "Bisa dekode gambar?", "¿Puedo decodificar una imagen?"),
            "a3": L("No. This page prints UTF-8 text. A PNG or a PDF is bytes, so decode fails on purpose.", "不能。这一页打出 UTF-8 文字。PNG 或 PDF 是字节，所以解码会故意失败。", "不能。這一頁打出 UTF-8 文字。PNG 或 PDF 是位元組，所以解碼會故意失敗。", "できない。このページはUTF-8を出す。PNGやPDFはバイトなので、デコードは意図して失敗する。", "아니요. 이 페이지는 UTF-8 글을 출력합니다. PNG나 PDF는 바이트라 디코드는 일부러 실패합니다.", "Không. Trang này in chữ UTF-8. PNG hoặc PDF là byte, nên giải mã cố ý thất bại.", "Tidak. Halaman ini mencetak teks UTF-8. PNG atau PDF adalah byte, jadi dekode gagal dengan sengaja.", "No. Esta página imprime texto UTF-8. Un PNG o un PDF son bytes, así que la decodificación falla a propósito."),
            "q4": L("Does encode use UTF-8?", "编码用 UTF-8 吗？", "編碼用 UTF-8 嗎？", "エンコードはUTF-8？", "인코드는 UTF-8을 쓰나요?", "Mã hóa có dùng UTF-8 không?", "Apakah enkode memakai UTF-8?", "¿La codificación usa UTF-8?"),
            "a4": L("Yes. Letters outside ASCII become their UTF-8 bytes, then standard Base64.", "是。ASCII 以外的字会先变成 UTF-8 字节，再变成标准 Base64。", "是。ASCII 以外的字會先變成 UTF-8 位元組，再變成標準 Base64。", "はい。ASCII外の文字はUTF-8バイトになり、それから標準Base64。", "예. ASCII 밖의 글자는 UTF-8 바이트가 된 뒤 표준 Base64가 됩니다.", "Có. Chữ ngoài ASCII thành byte UTF-8, rồi thành Base64 chuẩn.", "Ya. Huruf di luar ASCII menjadi byte UTF-8, lalu Base64 standar.", "Sí. Las letras fuera de ASCII pasan a bytes UTF-8 y luego a Base64 estándar."),
            "q5": L("Is the string uploaded?", "字符串会上传吗？", "字串會上傳嗎？", "アップロードされる？", "업로드되나요?", "Chuỗi có bị tải lên không?", "Apakah string diunggah?", "¿Se sube la cadena?"),
            "a5": L("No. Closing the tab discards it.", "不会。关掉标签页就没了。", "不會。關掉分頁就沒了。", "しない。タブを閉じると消える。", "아니요. 탭을 닫으면 사라집니다.", "Không. Đóng tab là mất.", "Tidak. Tutup tab, hilang.", "No. Al cerrar la pestaña se pierde."),
        },
    ),
    "unix-time": lesson(
        {
            "name": L("How to convert a Unix timestamp", "怎么换算 Unix 时间戳", "怎麼換算 Unix 時間戳", "Unixタイムスタンプの変換方法", "유닉스 타임스탬프 변환하는 법", "Cách đổi dấu thời gian Unix", "Cara ubah stempel waktu Unix", "Cómo convertir una marca de tiempo Unix"),
            "blurb": L("Count the digits, paste seconds or milliseconds, then read ISO and local time. Do not convert the number twice.", "先数位数，再贴秒或毫秒，然后看 ISO 和本地时间。不要把同一个数换算两次。", "先數位數，再貼秒或毫秒，然後看 ISO 和本地時間。不要把同一個數換算兩次。", "桁を数え、秒かミリ秒を貼り、ISOとローカルを読む。同じ数を二度変換しない。", "자릿수를 세고 초 또는 밀리초를 붙인 뒤 ISO와 로컬 시간을 읽으세요. 같은 수를 두 번 바꾸지 마세요.", "Đếm chữ số, dán giây hoặc mili giây, rồi đọc ISO và giờ máy. Đừng đổi cùng một số hai lần.", "Hitung digit, tempel detik atau milidetik, lalu baca ISO dan waktu lokal. Jangan ubah angka yang sama dua kali.", "Cuente los dígitos, pegue segundos o milisegundos y lea ISO y la hora local. No convierta el mismo número dos veces."),
            "title": L("How to convert a Unix timestamp", "怎么换算 Unix 时间戳", "怎麼換算 Unix 時間戳", "Unixタイムスタンプの変換方法", "유닉스 타임스탬프 변환하는 법", "Cách đổi dấu thời gian Unix", "Cara ubah stempel waktu Unix", "Cómo convertir una marca de tiempo Unix"),
            "lead": L("A log, an API, or a database gave you a number. You will count digits, paste it in this tab, and read UTC and local time. Ten digits are seconds. Thirteen are milliseconds.", "日志、接口或数据库给了你一个数。先数位数，贴进当前标签页，再看 UTC 和本地时间。十位是秒。十三位是毫秒。", "日誌、介面或資料庫給了你一個數。先數位數，貼進目前分頁，再看 UTC 和本地時間。十位是秒。十三位是毫秒。", "ログ、API、データベースが数を渡した。桁を数え、このタブに貼り、UTCとローカルを読む。10桁は秒。13桁はミリ秒。", "로그, API, 데이터베이스가 수를 줬습니다. 자릿수를 세고 이 탭에 붙인 뒤 UTC와 로컬 시간을 읽으세요. 열 자리는 초. 열세 자리는 밀리초.", "Log, API hoặc cơ sở dữ liệu đưa một số. Đếm chữ số, dán vào tab này, đọc UTC và giờ máy. Mười chữ số là giây. Mười ba là mili giây.", "Log, API, atau basis data memberi angka. Hitung digit, tempel di tab ini, baca UTC dan waktu lokal. Sepuluh digit adalah detik. Tiga belas adalah milidetik.", "Un log, una API o una base le dio un número. Cuente los dígitos, péguelo aquí y lea UTC y la hora local. Diez dígitos son segundos. Trece son milisegundos."),
            "result": L("Seconds, milliseconds, an ISO time in UTC, and local wall time for one instant, with a year you already expected.", "同一个瞬间的秒、毫秒、UTC 的 ISO 时间，以及本地时间，年份是你本来就预期的那一年。", "同一個瞬間的秒、毫秒、UTC 的 ISO 時間，以及本地時間，年份是你本來就預期的那一年。", "同じ瞬間の秒、ミリ秒、UTCのISO、ローカル時刻。年は最初から予想していた年。", "한 순간의 초, 밀리초, UTC의 ISO 시간, 그리고 로컬 시각. 연도는 처음부터 예상한 연도.", "Giây, mili giây, giờ ISO theo UTC, và giờ trên máy cho một khoảnh khắc, năm đúng như bạn đã chờ.", "Detik, milidetik, waktu ISO dalam UTC, dan waktu dinding lokal untuk satu saat, dengan tahun yang sudah Anda duga.", "Segundos, milisegundos, una hora ISO en UTC y la hora local de un instante, con el año que ya esperaba."),
            "note": L("Open the timestamp tool when you have the number or an ISO date. Now fills the current second. Nothing is uploaded.", "有数字或 ISO 日期再打开时间戳。现在会填入当前的秒。不上传。", "有數字或 ISO 日期再開時間戳。現在會填入目前的秒。不上傳。", "数かISO日付があってから開く。今は現在の秒を入れる。アップロードなし。", "숫자나 ISO 날짜가 있을 때 타임스탬프를 여세요. 지금은 현재 초를 채웁니다. 업로드 없음.", "Có số hoặc ngày ISO thì mở dấu thời gian. Nút bây giờ điền giây hiện tại. Không tải lên.", "Punya angka atau tanggal ISO, baru buka stempel waktu. Sekarang mengisi detik saat ini. Tidak diunggah.", "Abra la marca de tiempo cuando tenga el número o una fecha ISO. Ahora rellena el segundo actual. Nada se sube."),
            "s1t": L("Count the digits", "先数位数", "先數位數", "桁を数える", "자릿수를 세기", "Đếm chữ số", "Hitung digitnya", "Cuente los dígitos"),
            "s1b": L("Ten digits are seconds. Thirteen are milliseconds. Sixteen are microseconds, and this page divides those by 1,000 once. If you already multiplied by 1,000, leave the original number alone.", "十位是秒。十三位是毫秒。十六位是微秒，这一页会把它们除以 1,000 一次。你已经乘过 1,000，就贴原来的数。", "十位是秒。十三位是毫秒。十六位是微秒，這一頁會把它們除以 1,000 一次。你已經乘過 1,000，就貼原來的數。", "10桁は秒。13桁はミリ秒。16桁はマイクロ秒で、このページは1,000で一度割る。既に1,000倍したなら元の数を貼る。", "열 자리는 초. 열세 자리는 밀리초. 열여섯 자리는 마이크로초이며, 이 페이지는 1,000으로 한 번 나눕니다. 이미 1,000을 곱했다면 원래 수를 붙이세요.", "Mười chữ số là giây. Mười ba là mili giây. Mười sáu là micro giây, trang này chia cho 1.000 một lần. Đã nhân 1.000 thì dán số gốc.", "Sepuluh digit adalah detik. Tiga belas adalah milidetik. Enam belas adalah mikrodetik, dan halaman ini membaginya dengan 1.000 sekali. Jika sudah dikali 1.000, tempel angka aslinya.", "Diez dígitos son segundos. Trece son milisegundos. Dieciséis son microsegundos, y esta página los divide por 1.000 una vez. Si ya multiplicó por 1.000, pegue el número original."),
            "s2t": L("Open the timestamp tool on cv.cm", "打开 cv.cm 的时间戳", "打開 cv.cm 的時間戳", "cv.cmのタイムスタンプを開く", "cv.cm 타임스탬프를 열기", "Mở dấu thời gian trên cv.cm", "Buka stempel waktu di cv.cm", "Abra la marca de tiempo en cv.cm"),
            "s2b": L("Conversion stays in this tab.", "换算留在当前标签页。", "換算留在目前分頁。", "変換はこのタブ。", "변환은 이 탭에서.", "Đổi trong tab này.", "Konversi di tab ini.", "La conversión queda en esta pestaña."),
            "s3t": L("Paste the number, an ISO date, or tap Now", "贴数字、ISO 日期，或点现在", "貼數字、ISO 日期，或點現在", "数、ISO日付、または今を押す", "숫자, ISO 날짜를 붙이거나 지금을 누르기", "Dán số, ngày ISO, hoặc bấm Bây giờ", "Tempel angka, tanggal ISO, atau ketuk Sekarang", "Pegue el número, una fecha ISO, o pulse Ahora"),
            "s3b": L("1700000000 is seconds. 1700000000000 is milliseconds. 2023-11-14T22:13:20Z is a date. Now writes the current Unix second.", "1700000000 是秒。1700000000000 是毫秒。2023-11-14T22:13:20Z 是日期。现在会写入当前的 Unix 秒。", "1700000000 是秒。1700000000000 是毫秒。2023-11-14T22:13:20Z 是日期。現在會寫入目前的 Unix 秒。", "1700000000 は秒。1700000000000 はミリ秒。2023-11-14T22:13:20Z は日付。今は現在のUnix秒を書く。", "1700000000 은 초. 1700000000000 은 밀리초. 2023-11-14T22:13:20Z 는 날짜. 지금은 현재 유닉스 초를 씁니다.", "1700000000 là giây. 1700000000000 là mili giây. 2023-11-14T22:13:20Z là ngày. Bây giờ ghi giây Unix hiện tại.", "1700000000 adalah detik. 1700000000000 adalah milidetik. 2023-11-14T22:13:20Z adalah tanggal. Sekarang menulis detik Unix saat ini.", "1700000000 son segundos. 1700000000000 son milisegundos. 2023-11-14T22:13:20Z es una fecha. Ahora escribe el segundo Unix actual."),
            "s4t": L("Read seconds, milliseconds, ISO, UTC, and local", "看秒、毫秒、ISO、UTC 和本地", "看秒、毫秒、ISO、UTC 和本地", "秒、ミリ秒、ISO、UTC、ローカルを読む", "초, 밀리초, ISO, UTC, 로컬을 읽기", "Đọc giây, mili giây, ISO, UTC và giờ máy", "Baca detik, milidetik, ISO, UTC, dan lokal", "Lea segundos, milisegundos, ISO, UTC y local"),
            "s4b": L("ISO and the UTC line are the same instant in UTC. Local is that instant on this computer. Copy puts all of them on the clipboard.", "ISO 和 UTC 那一行是同一个 UTC 瞬间。本地是这台电脑上的那个瞬间。复制会把它们都放进剪贴板。", "ISO 和 UTC 那一行是同一個 UTC 瞬間。本地是這台電腦上的那個瞬間。複製會把它們都放進剪貼簿。", "ISOとUTC行は同じUTCの瞬間。ローカルはこのコンピュータ上のその瞬間。コピーは全部をクリップボードへ。", "ISO와 UTC 줄은 같은 UTC 순간입니다. 로컬은 이 컴퓨터의 그 순간입니다. 복사는 전부를 클립보드에 넣습니다.", "ISO và dòng UTC là cùng một khoảnh khắc UTC. Giờ máy là khoảnh khắc đó trên máy này. Copy đưa tất cả vào clipboard.", "ISO dan baris UTC adalah saat yang sama dalam UTC. Lokal adalah saat itu di komputer ini. Salin menaruh semuanya di papan klip.", "ISO y la línea UTC son el mismo instante en UTC. Local es ese instante en este equipo. Copiar pone todo en el portapapeles."),
            "s5t": L("A wild year means the digits were wrong", "年份离谱，就是位数错了", "年份離譜，就是位數錯了", "年が変なら桁が違う", "연도가 이상하면 자릿수가 틀린 것", "Năm kỳ lạ nghĩa là đếm sai chữ số", "Tahun yang aneh berarti digitnya salah", "Un año disparatado significa que los dígitos estaban mal"),
            "s5b": L("A year like 50000 means milliseconds were read as seconds, or you converted twice. A year in 1970 means the number was divided too far. Paste the original number again.", "年份像 50000，就是把毫秒当成了秒，或换算了两次。年份停在 1970，就是除得太狠。把原来的数再贴一次。", "年份像 50000，就是把毫秒當成了秒，或換算了兩次。年份停在 1970，就是除得太狠。把原來的數再貼一次。", "50000のような年は、ミリ秒を秒として読んだか二度変換した。1970年なら割りすぎ。元の数を貼り直す。", "50000 같은 연도는 밀리초를 초로 읽었거나 두 번 바꾼 것입니다. 1970년이면 너무 나눈 것입니다. 원래 수를 다시 붙이세요.", "Năm kiểu 50000 nghĩa là đọc mili giây thành giây, hoặc đổi hai lần. Năm 1970 nghĩa là chia quá tay. Dán lại số gốc.", "Tahun seperti 50000 berarti milidetik dibaca sebagai detik, atau Anda mengubah dua kali. Tahun 1970 berarti angkanya dibagi terlalu jauh. Tempel angka asli lagi.", "Un año como 50000 significa que los milisegundos se leyeron como segundos, o que convirtió dos veces. Un año en 1970 significa que el número se dividió de más. Pegue el número original otra vez."),
            "s6t": L("Copy the line the other system asked for", "复制对方要的那一行", "複製對方要的那一行", "相手が求めた行をコピー", "상대가 요구한 줄을 복사", "Copy dòng hệ thống kia yêu cầu", "Salin baris yang diminta sistem lain", "Copie la línea que pidió el otro sistema"),
            "s6b": L("An API that wants seconds does not want the ISO string. A spreadsheet that wants a date does not want thirteen digits. Match the field.", "要秒的接口不要 ISO 字符串。要日期的表格不要十三位数字。对着字段来。", "要秒的介面不要 ISO 字串。要日期的表格不要十三位數字。對著欄位來。", "秒を求めるAPIにISO文字列は渡さない。日付を求める表に13桁は渡さない。欄に合わせる。", "초를 원하는 API에 ISO 문자열을 주지 마세요. 날짜를 원하는 표에 열세 자리를 주지 마세요. 칸에 맞추세요.", "API cần giây thì đừng đưa chuỗi ISO. Bảng tính cần ngày thì đừng đưa mười ba chữ số. Khớp với ô.", "API yang minta detik tidak minta string ISO. Spreadsheet yang minta tanggal tidak minta tiga belas digit. Cocokkan kolomnya.", "Una API que pide segundos no quiere la cadena ISO. Una hoja que pide una fecha no quiere trece dígitos. Iguale el campo."),
            "diagram1": L("10 digits: seconds. 13 digits: milliseconds. 16 digits: microseconds, divided by 1,000 once.", "10 位：秒。13 位：毫秒。16 位：微秒，除以 1,000 一次。", "10 位：秒。13 位：毫秒。16 位：微秒，除以 1,000 一次。", "10桁は秒。13桁はミリ秒。16桁はマイクロ秒。1,000で一度割る。", "10자리: 초. 13자리: 밀리초. 16자리: 마이크로초, 1,000으로 한 번 나눔.", "10 chữ số: giây. 13: mili giây. 16: micro giây, chia 1.000 một lần.", "10 digit: detik. 13 digit: milidetik. 16 digit: mikrodetik, dibagi 1.000 sekali.", "10 dígitos: segundos. 13: milisegundos. 16: microsegundos, divididos por 1.000 una vez."),
            "diagram2": L("Read ISO and local time. A wild year means the digits were wrong.", "看 ISO 和本地时间。年份离谱就是位数错了。", "看 ISO 和本地時間。年份離譜就是位數錯了。", "ISOとローカルを読む。年が変なら桁が違う。", "ISO와 로컬 시간을 읽으세요. 연도가 이상하면 자릿수가 틀린 것입니다.", "Đọc ISO và giờ máy. Năm kỳ lạ là đếm sai chữ số.", "Baca ISO dan waktu lokal. Tahun aneh berarti digitnya salah.", "Lea ISO y la hora local. Un año disparatado significa que los dígitos estaban mal."),
        },
        {
            "q1": L("Can I convert a Unix timestamp free online?", "可以免费在线换算 Unix 时间戳吗？", "可以免費線上換算 Unix 時間戳嗎？", "Unixタイムスタンプを無料で変換できる？", "유닉스 타임스탬프를 무료로 변환할 수 있나요?", "Đổi dấu thời gian Unix miễn phí online được không?", "Bisa ubah stempel waktu Unix gratis online?", "¿Puedo convertir una marca de tiempo Unix gratis en línea?"),
            "a1": L("Yes. cv.cm converts in this tab. Nothing is uploaded.", "可以。cv.cm 在当前标签页换算。不上传。", "可以。cv.cm 在目前分頁換算。不上傳。", "できる。このタブで変換。アップロードなし。", "됩니다. 이 탭에서 변환합니다. 업로드 없음.", "Được. Đổi trong tab này. Không tải lên.", "Ya. Mengubah di tab ini. Tidak diunggah.", "Sí. Se convierte en esta pestaña. Nada se sube."),
            "q2": L("How do you tell seconds from milliseconds?", "怎么区分秒和毫秒？", "怎麼區分秒和毫秒？", "秒とミリ秒の見分けは？", "초와 밀리초는 어떻게 구분하나요?", "Phân biệt giây và mili giây thế nào?", "Bagaimana membedakan detik dan milidetik?", "¿Cómo se distinguen segundos y milisegundos?"),
            "a2": L("Ten digits are seconds. Thirteen are milliseconds. Sixteen are microseconds and are divided by 1,000 once.", "十位是秒。十三位是毫秒。十六位是微秒，会除以 1,000 一次。", "十位是秒。十三位是毫秒。十六位是微秒，會除以 1,000 一次。", "10桁は秒。13桁はミリ秒。16桁はマイクロ秒で、1,000で一度割る。", "열 자리는 초. 열세 자리는 밀리초. 열여섯 자리는 마이크로초이며 1,000으로 한 번 나눕니다.", "Mười chữ số là giây. Mười ba là mili giây. Mười sáu là micro giây và được chia cho 1.000 một lần.", "Sepuluh digit adalah detik. Tiga belas adalah milidetik. Enam belas adalah mikrodetik dan dibagi 1.000 sekali.", "Diez dígitos son segundos. Trece son milisegundos. Dieciséis son microsegundos y se dividen por 1.000 una vez."),
            "q3": L("What if the year is wrong?", "年份错了怎么办？", "年份錯了怎麼辦？", "年が違うときは？", "연도가 틀리면?", "Năm sai thì sao?", "Kalau tahunnya salah?", "¿Qué hago si el año está mal?"),
            "a3": L("You converted twice, or the digit count was wrong. Paste the original number. Leave a 13-digit value as it is.", "你换算了两次，或位数数错了。贴原来的数。十三位的数保持原样。", "你換算了兩次，或位數數錯了。貼原來的數。十三位的數保持原樣。", "二度変換したか、桁数が違う。元の数を貼る。13桁はそのまま。", "두 번 바꿨거나 자릿수를 잘못 센 것입니다. 원래 수를 붙이세요. 13자리는 그대로 두세요.", "Bạn đổi hai lần, hoặc đếm sai chữ số. Dán số gốc. Số 13 chữ số để nguyên.", "Anda mengubah dua kali, atau hitungan digit salah. Tempel angka asli. Biarkan nilai 13 digit apa adanya.", "Convirtió dos veces, o contó mal los dígitos. Pegue el número original. Deje un valor de 13 dígitos tal cual."),
            "q4": L("Can I paste a date?", "能贴日期吗？", "能貼日期嗎？", "日付を貼れる？", "날짜를 붙일 수 있나요?", "Dán được ngày không?", "Bisa tempel tanggal?", "¿Puedo pegar una fecha?"),
            "a4": L("Yes. An ISO date such as 2023-11-14T22:13:20Z works. Now fills the current Unix second.", "可以。像 2023-11-14T22:13:20Z 这样的 ISO 日期可以。现在会填入当前的 Unix 秒。", "可以。像 2023-11-14T22:13:20Z 這樣的 ISO 日期可以。現在會填入目前的 Unix 秒。", "できる。2023-11-14T22:13:20Z のようなISO日付。今は現在のUnix秒を入れる。", "됩니다. 2023-11-14T22:13:20Z 같은 ISO 날짜가 됩니다. 지금은 현재 유닉스 초를 채웁니다.", "Được. Ngày ISO như 2023-11-14T22:13:20Z dùng được. Bây giờ điền giây Unix hiện tại.", "Ya. Tanggal ISO seperti 2023-11-14T22:13:20Z berlaku. Sekarang mengisi detik Unix saat ini.", "Sí. Una fecha ISO como 2023-11-14T22:13:20Z sirve. Ahora rellena el segundo Unix actual."),
            "q5": L("Is the value uploaded?", "这个数会上传吗？", "這個數會上傳嗎？", "アップロードされる？", "업로드되나요?", "Giá trị có bị tải lên không?", "Apakah nilainya diunggah?", "¿Se sube el valor?"),
            "a5": L("No. Closing the tab discards it.", "不会。关掉标签页就没了。", "不會。關掉分頁就沒了。", "しない。タブを閉じると消える。", "아니요. 탭을 닫으면 사라집니다.", "Không. Đóng tab là mất.", "Tidak. Tutup tab, hilang.", "No. Al cerrar la pestaña se pierde."),
        },
    ),
    "read-jwt": lesson(
        {
            "name": L("How to read a JWT", "怎么读 JWT", "怎麼讀 JWT", "JWTの読み方", "JWT 읽는 법", "Cách đọc JWT", "Cara baca JWT", "Cómo leer un JWT"),
            "blurb": L("Paste a token, read the header and payload, and look at exp. The signature stays unchecked. A decoded token is only JSON you can see.", "贴上令牌，看头部和载荷，再看 exp。签名不会被校验。解出来的令牌只是你能看见的 JSON。", "貼上權杖，看頭部和載荷，再看 exp。簽名不會被校驗。解出來的權杖只是你能看見的 JSON。", "トークンを貼り、ヘッダとペイロードと exp を見る。署名は検証されない。復号した結果は見えるJSONにすぎない。", "토큰을 붙이고 헤더와 페이로드, exp를 보세요. 서명은 확인되지 않습니다. 디코드된 토큰은 보이는 JSON일 뿐입니다.", "Dán token, đọc header và payload, rồi xem exp. Chữ ký không được kiểm. Token đã giải chỉ là JSON bạn nhìn thấy.", "Tempel token, baca header dan payload, lalu lihat exp. Tanda tangan tidak diperiksa. Token yang terurai hanya JSON yang Anda lihat.", "Pegue un token, lea el encabezado y la carga, y mire exp. La firma no se comprueba. Un token decodificado es solo JSON que puede ver."),
            "title": L("How to read a JWT", "怎么读 JWT", "怎麼讀 JWT", "JWTの読み方", "JWT 읽는 법", "Cách đọc JWT", "Cara baca JWT", "Cómo leer un JWT"),
            "lead": L("You need to see the claims. You will paste the token in this tab, read alg and the payload, and close the tab. Decoding shows JSON. It leaves the signature unchecked.", "你要看见声明。把令牌贴进当前标签页，看 alg 和载荷，然后关掉标签页。解码显示 JSON。签名不会被校验。", "你要看見宣告。把權杖貼進目前分頁，看 alg 和載荷，然後關掉分頁。解碼顯示 JSON。簽名不會被校驗。", "クレームを見たい。このタブにトークンを貼り、alg とペイロードを読み、タブを閉じる。復号はJSONを見せる。署名は検証しない。", "클레임을 봐야 합니다. 이 탭에 토큰을 붙이고 alg와 페이로드를 읽은 뒤 탭을 닫으세요. 디코드는 JSON을 보여 줍니다. 서명은 확인하지 않습니다.", "Bạn cần thấy các claim. Dán token vào tab này, đọc alg và payload, rồi đóng tab. Giải mã hiện JSON. Chữ ký không được kiểm.", "Anda perlu melihat klaim. Tempel token di tab ini, baca alg dan payload, lalu tutup tab. Dekode menampilkan JSON. Tanda tangan tidak diperiksa.", "Necesita ver las reclamaciones. Pegue el token aquí, lea alg y la carga, y cierre la pestaña. Decodificar muestra JSON. La firma queda sin comprobar."),
            "result": L("A header and a payload you can read, plus an expiry line that only compares exp with the clock.", "你能读的头部和载荷，外加一行到期说明：它只拿 exp 和时钟比较。", "你能讀的頭部和載荷，外加一行到期說明：它只拿 exp 和時鐘比較。", "読めるヘッダとペイロード。期限の行は exp と時計を比べるだけ。", "읽을 수 있는 헤더와 페이로드, 그리고 exp를 시계와만 비교하는 만료 줄.", "Header và payload bạn đọc được, cộng một dòng hết hạn chỉ so exp với đồng hồ.", "Header dan payload yang bisa Anda baca, plus baris kedaluwarsa yang hanya membandingkan exp dengan jam.", "Un encabezado y una carga que puede leer, y una línea de caducidad que solo compara exp con el reloj."),
            "note": L("Open the JWT decoder when the token is on the clipboard. Three parts separated by dots is the usual shape. The signature stays unchecked. Nothing is uploaded.", "令牌在剪贴板上再打开 JWT 解码。常见形状是用点分开的三段。签名不会被校验。不上传。", "權杖在剪貼簿上再開 JWT 解碼。常見形狀是用點分開的三段。簽名不會被校驗。不上傳。", "トークンがクリップボードにあってから開く。普通は点で区切った3部。署名は検証されない。アップロードなし。", "토큰이 클립보드에 있을 때 JWT 디코더를 여세요. 보통은 점으로 나뉜 세 부분입니다. 서명은 확인되지 않습니다. 업로드 없음.", "Token đang ở clipboard thì mở bộ giải JWT. Dạng thường gặp là ba phần cách nhau bằng dấu chấm. Chữ ký không được kiểm. Không tải lên.", "Token ada di papan klip, baru buka dekoder JWT. Bentuk biasa adalah tiga bagian dipisah titik. Tanda tangan tidak diperiksa. Tidak diunggah.", "Abra el decodificador JWT cuando el token esté en el portapapeles. La forma habitual son tres partes separadas por puntos. La firma queda sin comprobar. Nada se sube."),
            "s1t": L("Reading shows JSON. The signature stays unchecked", "阅读只显示 JSON。签名不会被校验", "閱讀只顯示 JSON。簽名不會被校驗", "読むとJSONが見える。署名は検証されない", "읽으면 JSON이 보입니다. 서명은 확인되지 않습니다", "Đọc thì thấy JSON. Chữ ký không được kiểm", "Membaca menampilkan JSON. Tanda tangan tidak diperiksa", "Leer muestra JSON. La firma queda sin comprobar"),
            "s1b": L("Anyone can change the payload and encode it again. This page shows the JSON. It does not check the signature, the issuer, or the audience. A tidy payload is a reason to read it, and a reason to verify it somewhere that holds the key.", "任何人都能改载荷再编码。这一页显示 JSON。它不校验签名、签发者或受众。载荷看起来整齐，是拿来读的理由，也是去持有密钥的地方再校验的理由。", "任何人都能改載荷再編碼。這一頁顯示 JSON。它不校驗簽名、簽發者或受眾。載荷看起來整齊，是拿來讀的理由，也是去持有金鑰的地方再校驗的理由。", "誰でもペイロードを変えて再符号化できる。このページはJSONを見せる。署名も発行者もオーディエンスも検証しない。整ったペイロードは読む理由であり、鍵を持つ場所で検証する理由でもある。", "누구든 페이로드를 고쳐 다시 인코드할 수 있습니다. 이 페이지는 JSON을 보여 줍니다. 서명, 발급자, 대상은 확인하지 않습니다. 단정한 페이로드는 읽을 이유이고, 키를 가진 곳에서 다시 확인할 이유입니다.", "Ai cũng có thể sửa payload rồi mã hóa lại. Trang này hiện JSON. Nó không kiểm chữ ký, bên phát hành hay đối tượng. Payload gọn là lý do để đọc, và là lý do để kiểm ở nơi giữ khóa.", "Siapa pun bisa mengubah payload lalu mengenkodenya lagi. Halaman ini menampilkan JSON. Tanda tangan, penerbit, dan audiens tidak diperiksa. Payload yang rapi adalah alasan untuk membacanya, dan alasan untuk memeriksanya di tempat yang memegang kunci.", "Cualquiera puede cambiar la carga y codificarla otra vez. Esta página muestra el JSON. No comprueba la firma, el emisor ni la audiencia. Una carga ordenada es motivo para leerla, y motivo para verificarla donde esté la clave."),
            "s2t": L("Open the JWT decoder on cv.cm", "打开 cv.cm 的 JWT 解码", "打開 cv.cm 的 JWT 解碼", "cv.cmのJWTデコーダを開く", "cv.cm JWT 디코더를 열기", "Mở bộ giải JWT trên cv.cm", "Buka dekoder JWT di cv.cm", "Abra el decodificador JWT en cv.cm"),
            "s2b": L("Decoding stays in this tab.", "解码留在当前标签页。", "解碼留在目前分頁。", "復号はこのタブ。", "디코드는 이 탭에서.", "Giải mã trong tab này.", "Dekode di tab ini.", "La decodificación queda en esta pestaña."),
            "s3t": L("Paste the token", "贴上令牌", "貼上權杖", "トークンを貼る", "토큰 붙이기", "Dán token", "Tempel tokennya", "Pegue el token"),
            "s3b": L("The usual shape is three parts separated by dots. Two parts can still decode. A live access token can hold an email or a user id. Keep it off chat, and keep this tab off a shared screen.", "常见形状是用点分开的三段。两段也能解码。正在用的访问令牌里可能有邮箱或用户 id。不要发到聊天里，也不要在共享屏幕上打开这个标签页。", "常見形狀是用點分開的三段。兩段也能解碼。正在用的存取權杖裡可能有信箱或使用者 id。不要發到聊天裡，也不要在共用螢幕上打開這個分頁。", "普通は点で区切った3部。2部でも復号できる。使用中のアクセストークンにはメールやユーザーidがあり得る。チャットに出さない。共有画面でこのタブを開かない。", "보통은 점으로 나뉜 세 부분입니다. 두 부분도 디코드될 수 있습니다. 사용 중인 액세스 토큰에는 이메일이나 사용자 id가 있을 수 있습니다. 채팅에 넣지 말고, 공유 화면에서 이 탭을 열지 마세요.", "Dạng thường gặp là ba phần cách nhau bằng dấu chấm. Hai phần vẫn có thể giải. Token truy cập đang dùng có thể chứa email hoặc id người dùng. Đừng đưa vào chat, và đừng mở tab này trên màn hình dùng chung.", "Bentuk biasa adalah tiga bagian dipisah titik. Dua bagian tetap bisa didekode. Token akses yang sedang dipakai bisa berisi email atau id pengguna. Jauhkan dari chat, dan jauhkan tab ini dari layar bersama.", "La forma habitual son tres partes separadas por puntos. Dos partes también pueden decodificarse. Un token de acceso en uso puede llevar un correo o un id de usuario. Fuera del chat, y fuera de una pantalla compartida."),
            "s4t": L("Read alg and the claims", "看 alg 和各项声明", "看 alg 和各項宣告", "alg とクレームを読む", "alg와 클레임 읽기", "Đọc alg và các claim", "Baca alg dan klaim", "Lea alg y las reclamaciones"),
            "s4b": L("alg is a label, including the word none. It is a label only. Look for iss, aud, sub, and exp. If the page cannot decode it, the header or the payload is not base64url JSON.", "alg 是一个标签，包括 none 这个词。它只是标签。看 iss、aud、sub 和 exp。这一页解不了，就是头部或载荷不是 base64url 的 JSON。", "alg 是一個標籤，包括 none 這個詞。它只是標籤。看 iss、aud、sub 和 exp。這一頁解不了，就是頭部或載荷不是 base64url 的 JSON。", "alg はラベル。none という語も含む。ラベルでしかない。iss、aud、sub、exp を見る。復号できないなら、ヘッダかペイロードが base64url の JSON ではない。", "alg는 라벨입니다. none 이라는 말도 포함합니다. 라벨일 뿐입니다. iss, aud, sub, exp를 보세요. 이 페이지가 풀지 못하면 헤더나 페이로드가 base64url JSON이 아닙니다.", "alg là một nhãn, kể cả chữ none. Nó chỉ là nhãn. Xem iss, aud, sub và exp. Trang không giải được thì header hoặc payload không phải JSON base64url.", "alg adalah label, termasuk kata none. Itu hanya label. Lihat iss, aud, sub, dan exp. Jika halaman tidak bisa mendekode, header atau payload bukan JSON base64url.", "alg es una etiqueta, incluida la palabra none. Es solo una etiqueta. Busque iss, aud, sub y exp. Si la página no puede decodificarlo, el encabezado o la carga no son JSON en base64url."),
            "s5t": L("Expired compares exp with the clock", "过期只是拿 exp 和时钟比", "過期只是拿 exp 和時鐘比", "期限切れは exp と時計の比較", "만료는 exp와 시계의 비교", "Hết hạn là so exp với đồng hồ", "Kedaluwarsa membandingkan exp dengan jam", "Caducado compara exp con el reloj"),
            "s5b": L("exp is seconds. If that instant is in the past, the line says expired. Missing exp means there is no expiry claim to compare. In both cases the signature stayed unchecked.", "exp 是秒。那个瞬间已经过去，这一行就写过期。没有 exp，就是没有可比较的到期声明。两种情况签名都没有被校验。", "exp 是秒。那個瞬間已經過去，這一行就寫過期。沒有 exp，就是沒有可比較的到期宣告。兩種情況簽名都沒有被校驗。", "exp は秒。その瞬間が過去なら行は期限切れと書く。exp が無いのは、比べる期限クレームが無いということ。どちらも署名は検証されていない。", "exp는 초입니다. 그 순간이 지났으면 줄에 만료라고 나옵니다. exp가 없으면 비교할 만료 클레임이 없는 것입니다. 두 경우 모두 서명은 확인되지 않았습니다.", "exp là giây. Khoảnh khắc đó đã qua thì dòng ghi hết hạn. Không có exp nghĩa là không có claim hết hạn để so. Cả hai trường hợp chữ ký đều không được kiểm.", "exp adalah detik. Jika saat itu sudah lewat, barisnya menulis kedaluwarsa. Tidak ada exp berarti tidak ada klaim kedaluwarsa untuk dibandingkan. Dalam kedua kasus tanda tangan tidak diperiksa.", "exp son segundos. Si ese instante ya pasó, la línea dice caducado. Sin exp no hay una reclamación de caducidad que comparar. En ambos casos la firma quedó sin comprobar."),
            "s6t": L("Close the tab", "关掉标签页", "關掉分頁", "タブを閉じる", "탭을 닫기", "Đóng tab", "Tutup tab", "Cierre la pestaña"),
            "s6b": L("Closing discards the token from this page. When you need a trusted token, verify it where the secret or the public key lives. This page has neither.", "关掉后，这一页上的令牌就没了。你需要可信任的令牌时，到存放密钥或公钥的地方去校验。这一页两边都没有。", "關掉後，這一頁上的權杖就沒了。你需要可信任的權杖時，到存放密鑰或公鑰的地方去校驗。這一頁兩邊都沒有。", "閉じるとこのページのトークンは消える。信頼できるトークンが要るなら、秘密か公開鍵がある場所で検証する。このページにはどちらもない。", "닫으면 이 페이지의 토큰은 사라집니다. 신뢰할 토큰이 필요하면 비밀이나 공개 키가 있는 곳에서 확인하세요. 이 페이지에는 둘 다 없습니다.", "Đóng thì token trên trang mất. Khi cần token đáng tin, hãy kiểm ở nơi giữ bí mật hoặc khóa công khai. Trang này không có cái nào.", "Menutup membuang token dari halaman ini. Saat Anda butuh token tepercaya, periksa di tempat rahasia atau kunci publik berada. Halaman ini tidak punya keduanya.", "Al cerrar, el token desaparece de esta página. Cuando necesite un token de confianza, verifíquelo donde esté el secreto o la clave pública. Esta página no tiene ninguno de los dos."),
            "diagram1": L("Decode shows JSON. The signature stays unchecked. Verify where the key lives.", "解码显示 JSON。签名不会被校验。到密钥所在的地方再校验。", "解碼顯示 JSON。簽名不會被校驗。到金鑰所在的地方再校驗。", "復号はJSONを見せる。署名は検証されない。鍵がある場所で検証する。", "디코드는 JSON을 보여 줍니다. 서명은 확인되지 않습니다. 키가 있는 곳에서 확인하세요.", "Giải mã hiện JSON. Chữ ký không được kiểm. Kiểm ở nơi giữ khóa.", "Dekode menampilkan JSON. Tanda tangan tidak diperiksa. Periksa di tempat kuncinya berada.", "Decodificar muestra JSON. La firma queda sin comprobar. Verifique donde esté la clave."),
            "diagram2": L("Expired compares exp with the clock. The signature stayed unchecked.", "过期只是拿 exp 和时钟比。签名仍然没有被校验。", "過期只是拿 exp 和時鐘比。簽名仍然沒有被校驗。", "期限切れは exp と時計の比較。署名は未検証のまま。", "만료는 exp와 시계의 비교입니다. 서명은 여전히 확인되지 않았습니다.", "Hết hạn là so exp với đồng hồ. Chữ ký vẫn không được kiểm.", "Kedaluwarsa membandingkan exp dengan jam. Tanda tangan tetap tidak diperiksa.", "Caducado compara exp con el reloj. La firma siguió sin comprobar."),
        },
        {
            "q1": L("Can I decode a JWT free online?", "可以免费在线解码 JWT 吗？", "可以免費線上解碼 JWT 嗎？", "JWTを無料で読める？", "JWT를 무료로 디코딩할 수 있나요?", "Giải mã JWT miễn phí online được không?", "Bisa dekode JWT gratis online?", "¿Puedo decodificar un JWT gratis en línea?"),
            "a1": L("Yes. cv.cm reads the header and payload in this tab. Nothing is uploaded.", "可以。cv.cm 在当前标签页读头部和载荷。不上传。", "可以。cv.cm 在目前分頁讀頭部和載荷。不上傳。", "できる。このタブでヘッダとペイロードを読む。アップロードなし。", "됩니다. 이 탭에서 헤더와 페이로드를 읽습니다. 업로드 없음.", "Được. Đọc header và payload trong tab này. Không tải lên.", "Ya. Membaca header dan payload di tab ini. Tidak diunggah.", "Sí. Lee el encabezado y la carga en esta pestaña. Nada se sube."),
            "q2": L("Do you verify the signature?", "会校验签名吗？", "會校驗簽名嗎？", "署名は検証される？", "서명을 확인하나요?", "Có kiểm chữ ký không?", "Apakah tanda tangan diperiksa?", "¿Comprueban la firma?"),
            "a2": L("No. You get JSON you can read. The signature, the issuer, and the audience stay unchecked.", "不会。你得到的是能读的 JSON。签名、签发者和受众都不会被校验。", "不會。你得到的是能讀的 JSON。簽名、簽發者和受眾都不會被校驗。", "しない。読めるJSONが得られる。署名も発行者もオーディエンスも未検証。", "아니요. 읽을 수 있는 JSON을 받습니다. 서명, 발급자, 대상은 확인되지 않습니다.", "Không. Bạn nhận JSON đọc được. Chữ ký, bên phát hành và đối tượng không được kiểm.", "Tidak. Anda mendapat JSON yang bisa dibaca. Tanda tangan, penerbit, dan audiens tidak diperiksa.", "No. Obtiene JSON que puede leer. La firma, el emisor y la audiencia quedan sin comprobar."),
            "q3": L("What does expired mean?", "过期是什么意思？", "過期是什麼意思？", "期限切れとは？", "만료는 무슨 뜻인가요?", "Hết hạn nghĩa là gì?", "Apa arti kedaluwarsa?", "¿Qué significa caducado?"),
            "a3": L("The exp claim, in seconds, is before now. It is a clock compare. Missing exp means there is no expiry claim. Neither case checks the signature.", "exp 声明以秒计，早于现在。这是和时钟比较。没有 exp，就是没有到期声明。两种情况都不校验签名。", "exp 宣告以秒計，早於現在。這是和時鐘比較。沒有 exp，就是沒有到期宣告。兩種情況都不校驗簽名。", "exp クレームは秒で、今より前。時計との比較。exp が無いのは期限クレームが無いこと。どちらも署名は見ない。", "exp 클레임은 초 단위이며 지금보다 앞섭니다. 시계와의 비교입니다. exp가 없으면 만료 클레임이 없는 것입니다. 두 경우 모두 서명을 보지 않습니다.", "Claim exp, tính bằng giây, nằm trước lúc này. Đó là so với đồng hồ. Không có exp nghĩa là không có claim hết hạn. Cả hai đều không kiểm chữ ký.", "Klaim exp, dalam detik, berada sebelum sekarang. Itu perbandingan dengan jam. Tidak ada exp berarti tidak ada klaim kedaluwarsa. Keduanya tidak memeriksa tanda tangan.", "La reclamación exp, en segundos, es anterior a ahora. Es una comparación con el reloj. Sin exp no hay reclamación de caducidad. Ninguno de los dos casos comprueba la firma."),
            "q4": L("Why did decode fail?", "为什么解码失败？", "為什麼解碼失敗？", "なぜ復号に失敗する？", "왜 디코드가 실패하나요?", "Sao giải mã thất bại?", "Kenapa dekode gagal?", "¿Por qué falló la decodificación?"),
            "a4": L("The value needs two or three parts separated by dots, and the header and payload must be base64url JSON.", "这段值需要用点分开的两段或三段，而且头部和载荷必须是 base64url 的 JSON。", "這段值需要用點分開的兩段或三段，而且頭部和載荷必須是 base64url 的 JSON。", "値は点で区切った2部か3部。ヘッダとペイロードは base64url の JSON であること。", "값은 점으로 나뉜 두 부분 또는 세 부분이어야 하고, 헤더와 페이로드는 base64url JSON이어야 합니다.", "Giá trị cần hai hoặc ba phần cách nhau bằng dấu chấm, và header cùng payload phải là JSON base64url.", "Nilainya perlu dua atau tiga bagian dipisah titik, dan header serta payload harus JSON base64url.", "El valor necesita dos o tres partes separadas por puntos, y el encabezado y la carga deben ser JSON en base64url."),
            "q5": L("Is the token uploaded?", "令牌会上传吗？", "權杖會上傳嗎？", "アップロードされる？", "업로드되나요?", "Token có bị tải lên không?", "Apakah token diunggah?", "¿Se sube el token?"),
            "a5": L("No. Closing the tab discards it. Keep a live access token off chat and off a shared screen.", "不会。关掉标签页就没了。正在用的访问令牌不要发到聊天里，也不要出现在共享屏幕上。", "不會。關掉分頁就沒了。正在用的存取權杖不要發到聊天裡，也不要出現在共用螢幕上。", "しない。タブを閉じると消える。使用中のアクセストークンはチャットにも共有画面にも出さない。", "아니요. 탭을 닫으면 사라집니다. 사용 중인 액세스 토큰은 채팅과 공유 화면에 두지 마세요.", "Không. Đóng tab là mất. Token truy cập đang dùng đừng đưa vào chat hoặc màn hình dùng chung.", "Tidak. Tutup tab, hilang. Jauhkan token akses yang sedang dipakai dari chat dan layar bersama.", "No. Al cerrar la pestaña se pierde. Mantenga un token de acceso en uso fuera del chat y de una pantalla compartida."),
        },
    ),
}

META = {
    "titleFormatJson": L("How to format JSON | cv.cm", "怎么格式化 JSON | cv.cm", "怎麼格式化 JSON | cv.cm", "JSONの整形方法 | cv.cm", "JSON 포맷하는 법 | cv.cm", "Cách định dạng JSON | cv.cm", "Cara format JSON | cv.cm", "Cómo formatear JSON | cv.cm"),
    "descFormatJson": L("Pretty-print JSON with two spaces or minify it to one line. Strip log prefixes, comments, and trailing commas. Long integers belong in quotes. Nothing is uploaded.", "用两个空格排开 JSON，或压成一行。去掉日志前缀、注释和末尾逗号。超长整数要加引号。不上传。", "用兩個空格排開 JSON，或壓成一行。去掉日誌前綴、註解和末尾逗號。超長整數要加引號。不上傳。", "JSONを2スペースで整形するか1行にする。ログ接頭辞・コメント・末尾カンマを除く。長い整数は引用符で。アップロードなし。", "JSON을 두 칸으로 펼치거나 한 줄로 줄이세요. 로그 접두어, 주석, 끝의 쉼표를 지우세요. 긴 정수는 따옴표 안에. 업로드 없음.", "Giãn JSON bằng hai dấu cách hoặc nén một dòng. Bỏ tiền tố log, chú thích và dấu phẩy cuối. Số nguyên dài phải trong ngoặc kép. Không tải lên.", "Rapihkan JSON dengan dua spasi atau padatkan satu baris. Buang awalan log, komentar, dan koma akhir. Bilangan bulat panjang harus dalam kutip. Tidak diunggah.", "Expanda JSON con dos espacios o minifíquelo a una línea. Quite prefijos de log, comentarios y comas finales. Los enteros largos van entre comillas. Nada se sube."),
    "titleDecodeBase64": L("How to decode Base64 | cv.cm", "怎么解码 Base64 | cv.cm", "怎麼解碼 Base64 | cv.cm", "Base64のデコード方法 | cv.cm", "Base64 디코딩하는 법 | cv.cm", "Cách giải mã Base64 | cv.cm", "Cara dekode Base64 | cv.cm", "Cómo decodificar Base64 | cv.cm"),
    "descDecodeBase64": L("Decode standard Base64 to UTF-8 text, or encode text the other way. URL-safe minus and underscore are refused. Pictures and PDFs are not printed. Nothing is uploaded.", "把标准 Base64 解成 UTF-8 文字，或反过来编码。URL 安全的减号和下划线会被拒绝。图片和 PDF 不会被打出来。不上传。", "把標準 Base64 解成 UTF-8 文字，或反過來編碼。URL 安全的減號和底線會被拒絕。圖片和 PDF 不會被打出來。不上傳。", "標準Base64をUTF-8へ、または逆に符号化。URLセーフの - と _ は拒否。画像とPDFは出さない。アップロードなし。", "표준 Base64를 UTF-8 글로 풀거나 글을 인코딩하세요. URL-safe 빼기와 밑줄은 거부됩니다. 그림과 PDF는 출력되지 않습니다. 업로드 없음.", "Giải Base64 chuẩn thành chữ UTF-8, hoặc mã hóa chiều kia. Dấu trừ và gạch dưới kiểu URL-safe bị từ chối. Ảnh và PDF không được in. Không tải lên.", "Dekode Base64 standar ke teks UTF-8, atau enkode sebaliknya. Minus dan garis bawah URL-safe ditolak. Gambar dan PDF tidak dicetak. Tidak diunggah.", "Decodifique Base64 estándar a texto UTF-8, o codifique al revés. El menos y el guion bajo de URL se rechazan. Las imágenes y los PDF no se imprimen. Nada se sube."),
    "titleUnixTime": L("How to convert a Unix timestamp | cv.cm", "怎么换算 Unix 时间戳 | cv.cm", "怎麼換算 Unix 時間戳 | cv.cm", "Unixタイムスタンプの変換方法 | cv.cm", "유닉스 타임스탬프 변환하는 법 | cv.cm", "Cách đổi dấu thời gian Unix | cv.cm", "Cara ubah stempel waktu Unix | cv.cm", "Cómo convertir una marca de tiempo Unix | cv.cm"),
    "descUnixTime": L("Ten digits are seconds, thirteen are milliseconds, sixteen are microseconds divided by 1,000 once. Read ISO, UTC, and local time. Paste an ISO date or tap Now. Nothing is uploaded.", "十位是秒，十三位是毫秒，十六位是微秒并除以 1,000 一次。看 ISO、UTC 和本地时间。可以贴 ISO 日期或点现在。不上传。", "十位是秒，十三位是毫秒，十六位是微秒並除以 1,000 一次。看 ISO、UTC 和本地時間。可以貼 ISO 日期或點現在。不上傳。", "10桁は秒、13桁はミリ秒、16桁はマイクロ秒で1,000で一度割る。ISO、UTC、ローカルを読む。ISO日付を貼るか今を押す。アップロードなし。", "열 자리는 초, 열세 자리는 밀리초, 열여섯 자리는 마이크로초이며 1,000으로 한 번 나눕니다. ISO, UTC, 로컬 시간을 읽으세요. ISO 날짜를 붙이거나 지금을 누르세요. 업로드 없음.", "Mười chữ số là giây, mười ba là mili giây, mười sáu là micro giây chia 1.000 một lần. Đọc ISO, UTC và giờ máy. Dán ngày ISO hoặc bấm Bây giờ. Không tải lên.", "Sepuluh digit adalah detik, tiga belas adalah milidetik, enam belas adalah mikrodetik dibagi 1.000 sekali. Baca ISO, UTC, dan waktu lokal. Tempel tanggal ISO atau ketuk Sekarang. Tidak diunggah.", "Diez dígitos son segundos, trece son milisegundos, dieciséis son microsegundos divididos por 1.000 una vez. Lea ISO, UTC y la hora local. Pegue una fecha ISO o pulse Ahora. Nada se sube."),
    "titleReadJwt": L("How to read a JWT | cv.cm", "怎么读 JWT | cv.cm", "怎麼讀 JWT | cv.cm", "JWTの読み方 | cv.cm", "JWT 읽는 법 | cv.cm", "Cách đọc JWT | cv.cm", "Cara baca JWT | cv.cm", "Cómo leer un JWT | cv.cm"),
    "descReadJwt": L("Read a JWT header and payload in this tab. alg is a label. Expired only compares exp with the clock. The signature stays unchecked. Nothing is uploaded.", "在当前标签页读 JWT 的头部和载荷。alg 只是标签。过期只拿 exp 和时钟比较。签名不会被校验。不上传。", "在目前分頁讀 JWT 的頭部和載荷。alg 只是標籤。過期只拿 exp 和時鐘比較。簽名不會被校驗。不上傳。", "このタブでJWTのヘッダとペイロードを読む。alg はラベル。期限切れは exp と時計の比較だけ。署名は検証されない。アップロードなし。", "이 탭에서 JWT 헤더와 페이로드를 읽으세요. alg는 라벨입니다. 만료는 exp와 시계만 비교합니다. 서명은 확인되지 않습니다. 업로드 없음.", "Đọc header và payload JWT trong tab này. alg chỉ là nhãn. Hết hạn chỉ so exp với đồng hồ. Chữ ký không được kiểm. Không tải lên.", "Baca header dan payload JWT di tab ini. alg hanya label. Kedaluwarsa hanya membandingkan exp dengan jam. Tanda tangan tidak diperiksa. Tidak diunggah.", "Lea el encabezado y la carga de un JWT en esta pestaña. alg es una etiqueta. Caducado solo compara exp con el reloj. La firma queda sin comprobar. Nada se sube."),
}


def inject() -> None:
    if set(LESSONS) != {"format-json", "decode-base64", "unix-time", "read-jwt"}:
        raise SystemExit("lesson ids")
    for loc, path in FILES.items():
        data = json.loads(path.read_text())
        data["faq"].setdefault("learn", {})
        for lesson_id, payload in LESSONS.items():
            data["learn"][lesson_id] = payload["copy"][loc]
            data["faq"]["learn"][lesson_id] = payload["faq"][loc]
        for key, by_loc in META.items():
            data["meta"][key] = by_loc[loc]
        path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n")
        print("patched", path.name, list(LESSONS))


if __name__ == "__main__":
    inject()
