#!/usr/bin/env python3
"""Inject discount, URL, age, and aspect-ratio how-tos."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LOCS = ["en", "zh-CN", "zh-TW", "ja", "ko", "vi", "id", "es"]
FILES = {loc: ROOT / "src/locales" / f"{loc}.json" for loc in LOCS}
COPY_KEYS = [
    "name", "blurb", "title", "lead", "result", "note",
    "s1t", "s1b", "s2t", "s2b", "s3t", "s3b", "s4t", "s4b", "s5t", "s5b", "s6t", "s6b",
    "diagram1", "diagram2",
]
FAQ_KEYS = [f"{side}{i}" for i in range(1, 6) for side in ("q", "a")]


def L(*vals: str) -> dict[str, str]:
    if len(vals) != 8:
        raise ValueError(len(vals), vals[0] if vals else None)
    return dict(zip(LOCS, vals))


def lesson(fields, faq):
    missing = [k for k in COPY_KEYS if k not in fields] + [k for k in FAQ_KEYS if k not in faq]
    if missing:
        raise SystemExit(f"missing {missing}")
    if not fields["title"]["en"].startswith("How to "):
        raise SystemExit(fields["title"]["en"])
    return {
        "copy": {loc: {k: v[loc] for k, v in fields.items()} for loc in LOCS},
        "faq": {loc: {k: v[loc] for k, v in faq.items()} for loc in LOCS},
    }


LESSONS = {
    "percent-off": lesson(
        {
            "name": L("How to calculate a discount", "怎么算折扣", "怎麼算折扣", "割引の計算方法", "할인 계산하는 법", "Cách tính giảm giá", "Cara hitung diskon", "Cómo calcular un descuento"),
            "blurb": L("20% off 100 is a sale price of 80.00 and a saving of 20.00. That is not a 20% profit margin. 120% off can go below zero.", "100 打八折是售价 80.00、省下 20.00。这不是 20% 的利润率。120% 的折扣可以低于零。", "100 打八折是售價 80.00、省下 20.00。這不是 20% 的利潤率。120% 的折扣可以低於零。", "100 の 20% 引きは売価 80.00、割引額 20.00。利益率 20% ではない。120% 引きはゼロを下回り得る。", "100에서 20% 할인은 판매가 80.00, 절약 20.00. 이익률 20%가 아닙니다. 120% 할인은 0 아래로 갈 수 있습니다.", "Giảm 20% trên 100 là giá bán 80,00 và tiết kiệm 20,00. Không phải biên lợi nhuận 20%. Giảm 120% có thể xuống dưới 0.", "Diskon 20% dari 100 adalah harga jual 80,00 dan hemat 20,00. Bukan margin laba 20%. Diskon 120% bisa di bawah nol.", "Un 20% de descuento sobre 100 es un precio de 80,00 y un ahorro de 20,00. No es un margen del 20%. Un 120% puede bajar de cero."),
            "title": L("How to calculate a discount", "怎么算折扣", "怎麼算折扣", "割引の計算方法", "할인 계산하는 법", "Cách tính giảm giá", "Cara hitung diskon", "Cómo calcular un descuento"),
            "lead": L("You have a list price and a percent off. You will read the sale price and the saving in this tab. 20% off 100 leaves 80.00. A 20% margin on a selling price of 100 is a different question: that one is about cost.", "你有标价和折扣百分比。在当前标签页看售价和省下的钱。100 的 20% 折扣剩下 80.00。售价 100 的 20% 利润率是另一个问题：那个问的是成本。", "你有標價和折扣百分比。在目前分頁看售價和省下的錢。100 的 20% 折扣剩下 80.00。售價 100 的 20% 利潤率是另一個問題：那個問的是成本。", "定価と割引率がある。このタブで売価と割引額を読む。100 の 20% 引きは 80.00。売価 100 の利益率 20% は別の問いで、原価の話。", "정가와 할인율이 있습니다. 이 탭에서 판매가와 절약액을 읽으세요. 100의 20% 할인은 80.00이 남습니다. 판매가 100의 이익률 20%는 다른 질문이고 원가에 관한 것입니다.", "Bạn có giá niêm yết và phần trăm giảm. Đọc giá bán và số tiết kiệm trong tab này. Giảm 20% trên 100 còn 80,00. Biên 20% trên giá bán 100 là câu khác: câu đó hỏi giá vốn.", "Anda punya harga daftar dan persen diskon. Baca harga jual dan penghematan di tab ini. Diskon 20% dari 100 menyisakan 80,00. Margin 20% pada harga jual 100 adalah pertanyaan lain: itu tentang biaya.", "Tiene un precio de lista y un porcentaje de descuento. Lea el precio de venta y el ahorro aquí. Un 20% sobre 100 deja 80,00. Un margen del 20% sobre un precio de 100 es otra pregunta: esa trata del coste."),
            "result": L("A sale price and a saving, both to two decimals, from one list price and one percent off.", "一个售价和一个节省额，都到两位小数，来自一个标价和一个折扣百分比。", "一個售價和一個節省額，都到兩位小數，來自一個標價和一個折扣百分比。", "売価と割引額。どちらも小数第2位。定価一つと割引率一つから。", "판매가와 절약액. 둘 다 소수 둘째 자리. 정가 하나와 할인율 하나에서.", "Một giá bán và một khoản tiết kiệm, hai chữ số thập phân, từ một giá niêm yết và một phần trăm giảm.", "Satu harga jual dan satu penghematan, dua desimal, dari satu harga daftar dan satu persen diskon.", "Un precio de venta y un ahorro, ambos a dos decimales, a partir de un precio de lista y un porcentaje de descuento."),
            "note": L("Open discount when you know the list price and the percent off. The page does not name a currency. Nothing is uploaded.", "知道标价和折扣再打开折扣。这一页不标明货币。不上传。", "知道標價和折扣再開折扣。這一頁不標明貨幣。不上傳。", "定価と割引率が分かってから開く。通貨名は出さない。アップロードなし。", "정가와 할인율을 알 때 할인을 여세요. 이 페이지는 통화를 적지 않습니다. 업로드 없음.", "Biết giá niêm yết và phần trăm giảm thì mở giảm giá. Trang không ghi đơn vị tiền. Không tải lên.", "Tahu harga daftar dan persen diskon, baru buka diskon. Halaman tidak menyebut mata uang. Tidak diunggah.", "Abra el descuento cuando sepa el precio de lista y el porcentaje. La página no nombra una moneda. Nada se sube."),
            "s1t": L("Separate a discount from a margin", "先把折扣和利润率分开", "先把折扣和利潤率分開", "割引と利益率を分ける", "할인과 이익률을 나누기", "Tách giảm giá khỏi biên lợi nhuận", "Pisahkan diskon dari margin", "Separe el descuento del margen"),
            "s1b": L("20% off 100 means the buyer pays 80.00. A 20% margin on a selling price of 100 means the cost was 80 and the profit is 20. Same digits, different job.", "100 的 20% 折扣是买方付 80.00。售价 100 的 20% 利润率是成本 80、利润 20。数字一样，事情不同。", "100 的 20% 折扣是買方付 80.00。售價 100 的 20% 利潤率是成本 80、利潤 20。數字一樣，事情不同。", "100 の 20% 引きは買い手が 80.00 を払う。売価 100 の利益率 20% は原価 80、利益 20。数字は同じで仕事は違う。", "100의 20% 할인은 구매자가 80.00을 냅니다. 판매가 100의 이익률 20%는 원가 80, 이익 20. 숫자는 같고 일은 다릅니다.", "Giảm 20% trên 100 nghĩa là người mua trả 80,00. Biên 20% trên giá bán 100 nghĩa là giá vốn 80 và lợi nhuận 20. Cùng các chữ số, việc khác.", "Diskon 20% dari 100 berarti pembeli membayar 80,00. Margin 20% pada harga jual 100 berarti biaya 80 dan laba 20. Angka sama, pekerjaan berbeda.", "Un 20% de descuento sobre 100 significa que el comprador paga 80,00. Un margen del 20% sobre un precio de 100 significa que el coste fue 80 y el beneficio 20. Mismos dígitos, otro trabajo."),
            "s2t": L("Open discount on cv.cm", "打开 cv.cm 的折扣", "打開 cv.cm 的折扣", "cv.cmの割引を開く", "cv.cm 할인을 열기", "Mở giảm giá trên cv.cm", "Buka diskon di cv.cm", "Abra el descuento en cv.cm"),
            "s2b": L("The arithmetic stays in this tab.", "计算留在当前标签页。", "計算留在目前分頁。", "計算はこのタブ。", "계산은 이 탭에서.", "Phép tính ở trong tab này.", "Hitungan di tab ini.", "La cuenta queda en esta pestaña."),
            "s3t": L("Enter the list price and the percent off", "填标价和折扣百分比", "填標價和折扣百分比", "定価と割引率を入れる", "정가와 할인율 넣기", "Nhập giá niêm yết và phần trăm giảm", "Isi harga daftar dan persen diskon", "Escriba el precio de lista y el porcentaje"),
            "s3b": L("The price must be zero or more. 100 at 20% off is a sale price of 80.00 and a saving of 20.00. 80 at 25% off is 60.00 and 20.00.", "标价要大于或等于 0。100 打 20% 折扣是售价 80.00、节省 20.00。80 打 25% 折扣是 60.00 和 20.00。", "標價要大於或等於 0。100 打 20% 折扣是售價 80.00、節省 20.00。80 打 25% 折扣是 60.00 和 20.00。", "定価は 0 以上。100 の 20% 引きは売価 80.00、割引額 20.00。80 の 25% 引きは 60.00 と 20.00。", "정가는 0 이상. 100의 20% 할인은 판매가 80.00, 절약 20.00. 80의 25% 할인은 60.00과 20.00.", "Giá niêm yết từ 0 trở lên. 100 giảm 20% là giá bán 80,00 và tiết kiệm 20,00. 80 giảm 25% là 60,00 và 20,00.", "Harga daftar nol atau lebih. 100 diskon 20% adalah harga jual 80,00 dan hemat 20,00. 80 diskon 25% adalah 60,00 dan 20,00.", "El precio debe ser cero o más. 100 con 20% de descuento es un precio de 80,00 y un ahorro de 20,00. 80 con 25% es 60,00 y 20,00."),
            "s4t": L("Read sale price and saving", "看售价和节省额", "看售價和節省額", "売価と割引額を読む", "판매가와 절약액 읽기", "Đọc giá bán và số tiết kiệm", "Baca harga jual dan penghematan", "Lea el precio de venta y el ahorro"),
            "s4b": L("Both lines use two decimals. There is no currency. Copy both, then use the line the form named.", "两行都是两位小数。没有货币。两行都复制，再用表单点名的那一行。", "兩行都是兩位小數。沒有貨幣。兩行都複製，再用表單點名的那一行。", "両行とも小数第2位。通貨はない。両方コピーし、書類が名指しした行を使う。", "두 줄 모두 소수 둘째 자리. 통화는 없습니다. 둘 다 복사한 뒤 서류가 지목한 줄을 쓰세요.", "Cả hai dòng đều hai chữ số thập phân. Không có đơn vị tiền. Copy cả hai, rồi dùng dòng biểu mẫu chỉ.", "Kedua baris dua desimal. Tidak ada mata uang. Salin keduanya, lalu pakai baris yang disebut formulir.", "Ambas líneas van a dos decimales. No hay moneda. Copie ambas y use la línea que nombró el formulario."),
            "s5t": L("A percent over 100 can go below zero", "超过 100% 的折扣可以低于零", "超過 100% 的折扣可以低於零", "100% を超える割引はゼロを下回り得る", "100%를 넘는 할인은 0 아래로 갈 수 있음", "Phần trăm trên 100 có thể xuống dưới 0", "Persen di atas 100 bisa di bawah nol", "Un porcentaje mayor que 100 puede bajar de cero"),
            "s5b": L("120% off 100 is a sale price of -20.00 and a saving of 120.00. That is arithmetic. A shop tag that cannot go below zero needs a different rule.", "100 的 120% 折扣是售价 -20.00、节省 120.00。这是运算。价签不能低于零，就要用另一条规则。", "100 的 120% 折扣是售價 -20.00、節省 120.00。這是運算。價簽不能低於零，就要用另一條規則。", "100 の 120% 引きは売価 -20.00、割引額 120.00。これは計算。値札がゼロを下回れないなら別の規則。", "100의 120% 할인은 판매가 -20.00, 절약 120.00. 이것은 연산입니다. 가격표가 0 아래로 갈 수 없으면 다른 규칙이 필요합니다.", "Giảm 120% trên 100 là giá bán -20,00 và tiết kiệm 120,00. Đó là phép tính. Nhãn giá không được dưới 0 thì cần quy tắc khác.", "Diskon 120% dari 100 adalah harga jual -20,00 dan hemat 120,00. Itu hitungan. Label toko yang tidak boleh di bawah nol perlu aturan lain.", "Un 120% de descuento sobre 100 es un precio de -20,00 y un ahorro de 120,00. Es aritmética. Una etiqueta que no puede bajar de cero necesita otra regla."),
            "s6t": L("A negative percent raises the price", "负的百分比会把价格抬高", "負的百分比會把價格抬高", "負のパーセントは価格を上げる", "음수 퍼센트는 가격을 올림", "Phần trăm âm làm giá tăng", "Persen negatif menaikkan harga", "Un porcentaje negativo sube el precio"),
            "s6b": L("Minus 10% on 100 is a sale price of 110.00. The saving line is -10.00. If the tag says 10% off, the percent is 10, not -10.", "100 的 -10% 是售价 110.00。节省那一行是 -10.00。价签写九折或 10% 折扣，百分比是 10，不是 -10。", "100 的 -10% 是售價 110.00。節省那一行是 -10.00。價簽寫九折或 10% 折扣，百分比是 10，不是 -10。", "100 の -10% は売価 110.00。割引額の行は -10.00。値札が 10% 引きならパーセントは 10 であり -10 ではない。", "100의 -10%는 판매가 110.00. 절약 줄은 -10.00. 가격표가 10% 할인이면 퍼센트는 10이지 -10이 아닙니다.", "−10% trên 100 là giá bán 110,00. Dòng tiết kiệm là −10,00. Nhãn ghi giảm 10% thì phần trăm là 10, không phải −10.", "−10% pada 100 adalah harga jual 110,00. Baris hemat adalah −10,00. Jika label menulis diskon 10%, persennya 10, bukan −10.", "Un −10% sobre 100 es un precio de 110,00. La línea de ahorro es −10,00. Si la etiqueta dice 10% de descuento, el porcentaje es 10, no −10."),
            "diagram1": L("20% off 100: sale 80.00, saving 20.00. Not a 20% margin.", "100 的 20% 折扣：售价 80.00，节省 20.00。不是 20% 利润率。", "100 的 20% 折扣：售價 80.00，節省 20.00。不是 20% 利潤率。", "100 の 20% 引き：売価 80.00、割引額 20.00。利益率 20% ではない。", "100의 20% 할인: 판매가 80.00, 절약 20.00. 이익률 20%가 아님.", "Giảm 20% trên 100: giá 80,00, tiết kiệm 20,00. Không phải biên 20%.", "Diskon 20% dari 100: jual 80,00, hemat 20,00. Bukan margin 20%.", "20% sobre 100: precio 80,00, ahorro 20,00. No es un margen del 20%."),
            "diagram2": L("120% off 100 is -20.00. Minus 10% raises the price to 110.00.", "100 的 120% 折扣是 -20.00。-10% 把价格抬到 110.00。", "100 的 120% 折扣是 -20.00。-10% 把價格抬到 110.00。", "100 の 120% 引きは -20.00。-10% は 110.00 に上げる。", "100의 120% 할인은 -20.00. −10%는 가격을 110.00으로 올림.", "Giảm 120% trên 100 là −20,00. −10% đưa giá lên 110,00.", "Diskon 120% dari 100 adalah −20,00. −10% menaikkan harga ke 110,00.", "120% sobre 100 es −20,00. Un −10% sube el precio a 110,00."),
        },
        {
            "q1": L("Can I calculate a discount free online?", "可以免费在线算折扣吗？", "可以免費線上算折扣嗎？", "割引を無料で計算できる？", "할인을 무료로 계산할 수 있나요?", "Tính giảm giá miễn phí online được không?", "Bisa hitung diskon gratis online?", "¿Puedo calcular un descuento gratis en línea?"),
            "a1": L("Yes. cv.cm shows the sale price and the saving in this tab. Nothing is uploaded.", "可以。cv.cm 在当前标签页显示售价和节省额。不上传。", "可以。cv.cm 在目前分頁顯示售價和節省額。不上傳。", "できる。このタブで売価と割引額を出す。アップロードなし。", "됩니다. 이 탭에서 판매가와 절약액을 보여 줍니다. 업로드 없음.", "Được. Hiện giá bán và số tiết kiệm trong tab này. Không tải lên.", "Ya. Menampilkan harga jual dan penghematan di tab ini. Tidak diunggah.", "Sí. Muestra el precio de venta y el ahorro en esta pestaña. Nada se sube."),
            "q2": L("What is 20% off 100?", "100 的 20% 折扣是多少？", "100 的 20% 折扣是多少？", "100 の 20% 引きは？", "100의 20% 할인은?", "Giảm 20% trên 100 là bao nhiêu?", "Diskon 20% dari 100 berapa?", "¿Cuánto es un 20% de descuento sobre 100?"),
            "a2": L("Sale price 80.00, saving 20.00. That is not a 20% profit margin.", "售价 80.00，节省 20.00。这不是 20% 的利润率。", "售價 80.00，節省 20.00。這不是 20% 的利潤率。", "売価 80.00、割引額 20.00。利益率 20% ではない。", "판매가 80.00, 절약 20.00. 이익률 20%가 아닙니다.", "Giá bán 80,00, tiết kiệm 20,00. Không phải biên lợi nhuận 20%.", "Harga jual 80,00, hemat 20,00. Bukan margin laba 20%.", "Precio 80,00, ahorro 20,00. No es un margen de beneficio del 20%."),
            "q3": L("Can the percent be over 100?", "百分比可以超过 100 吗？", "百分比可以超過 100 嗎？", "100% を超えられる？", "100%를 넘을 수 있나요?", "Phần trăm có thể trên 100 không?", "Bolehkah persen di atas 100?", "¿El porcentaje puede pasar de 100?"),
            "a3": L("Yes. 120% off 100 is a sale price of -20.00. That is arithmetic, not a shop rule.", "可以。100 的 120% 折扣是售价 -20.00。这是运算，不是商店规则。", "可以。100 的 120% 折扣是售價 -20.00。這是運算，不是商店規則。", "できる。100 の 120% 引きは売価 -20.00。計算であり店の規則ではない。", "됩니다. 100의 120% 할인은 판매가 -20.00. 연산이지 가게 규칙이 아닙니다.", "Được. Giảm 120% trên 100 là giá bán −20,00. Đó là phép tính, không phải quy tắc cửa hàng.", "Ya. Diskon 120% dari 100 adalah harga jual −20,00. Itu hitungan, bukan aturan toko.", "Sí. Un 120% sobre 100 es un precio de −20,00. Es aritmética, no una regla de tienda."),
            "q4": L("What does a negative percent do?", "负的百分比会怎样？", "負的百分比會怎樣？", "負のパーセントは？", "음수 퍼센트는 어떻게 되나요?", "Phần trăm âm thì sao?", "Apa yang dilakukan persen negatif?", "¿Qué hace un porcentaje negativo?"),
            "a4": L("It raises the price. Minus 10% on 100 is 110.00. A tag that says 10% off uses 10.", "它会抬高价格。100 的 -10% 是 110.00。价签写 10% 折扣，用的是 10。", "它會抬高價格。100 的 -10% 是 110.00。價簽寫 10% 折扣，用的是 10。", "価格が上がる。100 の -10% は 110.00。10% 引きの値札は 10 を使う。", "가격이 올라갑니다. 100의 −10%는 110.00. 10% 할인이라고 쓴 가격표는 10을 씁니다.", "Nó làm giá tăng. −10% trên 100 là 110,00. Nhãn ghi giảm 10% thì dùng 10.", "Itu menaikkan harga. −10% pada 100 adalah 110,00. Label diskon 10% memakai 10.", "Sube el precio. Un −10% sobre 100 es 110,00. Una etiqueta de 10% de descuento usa 10."),
            "q5": L("Is the price uploaded?", "价格会上传吗？", "價格會上傳嗎？", "アップロードされる？", "업로드되나요?", "Giá có bị tải lên không?", "Apakah harga diunggah?", "¿Se sube el precio?"),
            "a5": L("No. Closing the tab discards it. The numbers have no currency.", "不会。关掉标签页就没了。这些数字没有货币。", "不會。關掉分頁就沒了。這些數字沒有貨幣。", "しない。タブを閉じると消える。数に通貨はない。", "아니요. 탭을 닫으면 사라집니다. 숫자에는 통화가 없습니다.", "Không. Đóng tab là mất. Các số không có đơn vị tiền.", "Tidak. Tutup tab, hilang. Angkanya tidak punya mata uang.", "No. Al cerrar la pestaña se pierde. Los números no tienen moneda."),
        },
    ),
    "encode-url": lesson(
        {
            "name": L("How to encode a URL", "怎么做网址编码", "怎麼做網址編碼", "URLエンコードの方法", "URL 인코딩하는 법", "Cách mã hóa URL", "Cara enkode URL", "Cómo codificar una URL"),
            "blurb": L("Encoding turns a space into %20 and also encodes slashes. Decoding turns + into a space. A broken % sequence fails.", "编码把空格变成 %20，斜杠也会被编码。解码把 + 变成空格。坏掉的 % 序列会失败。", "編碼把空格變成 %20，斜線也會被編碼。解碼把 + 變成空格。壞掉的 % 序列會失敗。", "符号化は空白を %20 にし、スラッシュも符号化する。復号は + を空白にする。壊れた % は失敗。", "인코딩은 공백을 %20으로 만들고 슬래시도 인코딩합니다. 디코딩은 +를 공백으로 바꿉니다. 깨진 % 서열은 실패합니다.", "Mã hóa biến dấu cách thành %20 và cả dấu gạch chéo. Giải mã biến + thành dấu cách. Chuỗi % hỏng thì thất bại.", "Enkode mengubah spasi menjadi %20 dan juga mengenkode garis miring. Dekode mengubah + menjadi spasi. Rangkaian % yang rusak gagal.", "Codificar convierte un espacio en %20 y también codifica las barras. Decodificar convierte + en un espacio. Una secuencia % rota falla."),
            "title": L("How to encode a URL", "怎么做网址编码", "怎麼做網址編碼", "URLエンコードの方法", "URL 인코딩하는 법", "Cách mã hóa URL", "Cara enkode URL", "Cómo codificar una URL"),
            "lead": L("You have a string that must travel inside a URL. You will encode or decode it in this tab. Encoding the whole address also encodes the slashes. A query that uses + for a space decodes that plus as a space.", "你有一段必须放进网址里的文字。在当前标签页编码或解码。把整段地址编码，斜杠也会被编码。查询串用 + 表示空格时，解码会把这个加号当成空格。", "你有一段必須放進網址裡的文字。在目前分頁編碼或解碼。把整段地址編碼，斜線也會被編碼。查詢串用 + 表示空格時，解碼會把這個加號當成空格。", "URL の中を通す文字列がある。このタブで符号化か復号。アドレス全体を符号化するとスラッシュも符号化される。空白に + を使うクエリは、その + を空白として復号する。", "URL 안에 실어야 할 문자열이 있습니다. 이 탭에서 인코딩하거나 디코딩하세요. 주소 전체를 인코딩하면 슬래시도 인코딩됩니다. 공백에 +를 쓰는 쿼리는 그 더하기를 공백으로 디코딩합니다.", "Bạn có một chuỗi phải đi trong URL. Mã hóa hoặc giải mã trong tab này. Mã hóa cả địa chỉ thì dấu gạch chéo cũng bị mã hóa. Query dùng + cho dấu cách sẽ giải mã dấu cộng đó thành dấu cách.", "Anda punya string yang harus lewat di dalam URL. Enkode atau dekode di tab ini. Mengenkode seluruh alamat juga mengenkode garis miring. Query yang memakai + untuk spasi mendekode plus itu sebagai spasi.", "Tiene un texto que debe viajar dentro de una URL. Codifíquelo o decodifíquelo aquí. Codificar la dirección entera también codifica las barras. Una consulta que usa + para un espacio decodifica ese más como un espacio."),
            "result": L("A percent-encoded string, or the text decoded from one, including spaces that arrived as +.", "一段百分号编码，或从中解出的文字，包括以 + 到来的空格。", "一段百分號編碼，或從中解出的文字，包括以 + 到來的空格。", "パーセント符号化された文字列、またはそこから復号した文字。+ で来た空白も含む。", "퍼센트 인코딩된 문자열, 또는 거기서 푼 글. +로 온 공백도 포함.", "Một chuỗi mã hóa phần trăm, hoặc chữ giải từ đó, kể cả dấu cách đến dưới dạng +.", "String terenkode persen, atau teks yang didekode darinya, termasuk spasi yang datang sebagai +.", "Una cadena con codificación porcentual, o el texto decodificado, incluidos los espacios que llegaron como +."),
            "note": L("Open URL encode when the string is in front of you. Encode uses encodeURIComponent. Decode turns + into a space before reading % sequences. Nothing is uploaded.", "字符串在眼前再打开网址编码。编码用 encodeURIComponent。解码先把 + 变成空格，再读 % 序列。不上传。", "字串在眼前再開網址編碼。編碼用 encodeURIComponent。解碼先把 + 變成空格，再讀 % 序列。不上傳。", "文字列が手元にあってから開く。符号化は encodeURIComponent。復号は % を読む前に + を空白にする。アップロードなし。", "문자열이 앞에 있을 때 URL 인코딩을 여세요. 인코딩은 encodeURIComponent. 디코딩은 % 서열을 읽기 전에 +를 공백으로 바꿉니다. 업로드 없음.", "Có chuỗi thì mở mã hóa URL. Mã hóa dùng encodeURIComponent. Giải mã đổi + thành dấu cách trước khi đọc chuỗi %. Không tải lên.", "String sudah di depan, baru buka enkode URL. Enkode memakai encodeURIComponent. Dekode mengubah + menjadi spasi sebelum membaca rangkaian %. Tidak diunggah.", "Abra la codificación URL cuando el texto esté delante. Codificar usa encodeURIComponent. Decodificar convierte + en un espacio antes de leer las secuencias %. Nada se sube."),
            "s1t": L("Decide whether slashes must survive", "先定斜杠要不要留下来", "先定斜線要不要留下來", "スラッシュを残すか決める", "슬래시를 남겨야 하는지 정하기", "Quyết dấu gạch chéo có phải giữ không", "Tentukan apakah garis miring harus tetap", "Decida si las barras deben sobrevivir"),
            "s1b": L("Encoding a query value is the usual job. Encoding https://cv.cm/a b also turns : and / into %3A and %2F. The result is one component, not an address you can open as-is.", "通常要编码的是查询值。把 https://cv.cm/a b 整段编码，冒号和斜杠也会变成 %3A 和 %2F。结果是一个组件，不是能直接打开的地址。", "通常要編碼的是查詢值。把 https://cv.cm/a b 整段編碼，冒號和斜線也會變成 %3A 和 %2F。結果是一個元件，不是能直接打開的地址。", "普通はクエリ値を符号化する。https://cv.cm/a b 全体を符号化すると : と / も %3A と %2F になる。結果は一つの部品であり、そのまま開けるアドレスではない。", "보통은 쿼리 값을 인코딩합니다. https://cv.cm/a b 전체를 인코딩하면 : 와 / 도 %3A 와 %2F 가 됩니다. 결과는 한 조각이지 그대로 열 수 있는 주소가 아닙니다.", "Việc thường gặp là mã hóa giá trị query. Mã hóa cả https://cv.cm/a b thì : và / cũng thành %3A và %2F. Kết quả là một thành phần, không phải địa chỉ mở nguyên si.", "Pekerjaan yang biasa adalah mengenkode nilai query. Mengenkode seluruh https://cv.cm/a b juga mengubah : dan / menjadi %3A dan %2F. Hasilnya satu komponen, bukan alamat yang bisa dibuka apa adanya.", "Lo habitual es codificar un valor de consulta. Codificar https://cv.cm/a b entero también convierte : y / en %3A y %2F. El resultado es un componente, no una dirección que se pueda abrir tal cual."),
            "s2t": L("Open URL encode on cv.cm", "打开 cv.cm 的网址编码", "打開 cv.cm 的網址編碼", "cv.cmのURLエンコードを開く", "cv.cm URL 인코딩을 열기", "Mở mã hóa URL trên cv.cm", "Buka enkode URL di cv.cm", "Abra la codificación URL en cv.cm"),
            "s2b": L("The string stays in this tab.", "字符串留在当前标签页。", "字串留在目前分頁。", "文字列はこのタブ。", "문자열은 이 탭에 있습니다.", "Chuỗi ở trong tab này.", "String tetap di tab ini.", "El texto queda en esta pestaña."),
            "s3t": L("Choose encode or decode", "选编码或解码", "選編碼或解碼", "符号化か復号を選ぶ", "인코드 또는 디코드 고르기", "Chọn mã hóa hoặc giải mã", "Pilih enkode atau dekode", "Elija codificar o decodificar"),
            "s3b": L("Encode turns text into percent-encoding. Decode turns percent-encoding back into text. Encoding a string that is already encoded wraps it a second time.", "编码把文字变成百分号编码。解码把百分号编码变回文字。已经编码过的字符串再编码，会再包一层。", "編碼把文字變成百分號編碼。解碼把百分號編碼變回文字。已經編碼過的字串再編碼，會再包一層。", "符号化は文字をパーセント符号に。復号はそれを文字に戻す。すでに符号化された文字列を再び符号化すると二重になる。", "인코드는 글을 퍼센트 인코딩으로. 디코드는 퍼센트 인코딩을 글로. 이미 인코딩된 문자열을 다시 인코드하면 한 번 더 감쌉니다.", "Mã hóa biến chữ thành mã phần trăm. Giải mã biến mã phần trăm thành chữ. Mã hóa chuỗi đã mã hóa sẽ bọc thêm một lần.", "Enkode mengubah teks menjadi pengodean persen. Dekode mengubahnya kembali menjadi teks. Mengenkode string yang sudah terenkode membungkusnya sekali lagi.", "Codificar convierte texto en codificación porcentual. Decodificar la vuelve texto. Codificar un texto que ya está codificado lo envuelve otra vez."),
            "s4t": L("Watch the space", "盯住空格", "盯住空格", "空白に注目する", "공백을 보기", "Để ý dấu cách", "Perhatikan spasinya", "Fíjese en el espacio"),
            "s4b": L("Encode writes a space as %20, not as +. Decode turns both %20 and + into a space. a+b decodes as a b.", "编码把空格写成 %20，不写成 +。解码把 %20 和 + 都变成空格。a+b 解出来是 a b。", "編碼把空格寫成 %20，不寫成 +。解碼把 %20 和 + 都變成空格。a+b 解出來是 a b。", "符号化は空白を + ではなく %20 と書く。復号は %20 も + も空白にする。a+b は a b になる。", "인코드는 공백을 +가 아니라 %20으로 씁니다. 디코드는 %20과 +를 모두 공백으로 바꿉니다. a+b는 a b가 됩니다.", "Mã hóa viết dấu cách thành %20, không thành +. Giải mã biến cả %20 và + thành dấu cách. a+b giải ra a b.", "Enkode menulis spasi sebagai %20, bukan +. Dekode mengubah %20 dan + menjadi spasi. a+b menjadi a b.", "Codificar escribe un espacio como %20, no como +. Decodificar convierte tanto %20 como + en un espacio. a+b se decodifica como a b."),
            "s5t": L("A broken percent sequence fails", "坏掉的百分号序列会失败", "壞掉的百分號序列會失敗", "壊れたパーセント列は失敗", "깨진 퍼센트 서열은 실패", "Chuỗi phần trăm hỏng thì thất bại", "Rangkaian persen yang rusak gagal", "Una secuencia porcentual rota falla"),
            "s5b": L("Each % must be followed by two hex digits. %zz and a lone % fail. Fix the pairs, then decode again.", "每个 % 后面必须是两位十六进制。%zz 和单独的 % 会失败。把这对数字改好，再解码。", "每個 % 後面必須是兩位十六進制。%zz 和單獨的 % 會失敗。把這對數字改好，再解碼。", "各 % の後は 16進が二桁。%zz と単独の % は失敗。組を直してから再び復号。", "각 % 뒤에는 16진 두 자리가 있어야 합니다. %zz와 홀로 있는 %는 실패합니다. 쌍을 고친 뒤 다시 디코드하세요.", "Mỗi % phải theo sau bởi hai chữ số hex. %zz và một % đơn độc thì thất bại. Sửa cặp rồi giải mã lại.", "Setiap % harus diikuti dua digit heksa. %zz dan % sendirian gagal. Perbaiki pasangannya, lalu dekode lagi.", "Cada % debe ir seguido de dos dígitos hexadecimales. %zz y un % solo fallan. Corrija los pares y decodifique otra vez."),
            "s6t": L("Check one character you expect", "核对一个你预期的字符", "核對一個你預期的字元", "予想した文字を一つ照合", "예상한 문자 하나 대조", "Đối chiếu một ký tự bạn chờ", "Cek satu karakter yang Anda harapkan", "Compruebe un carácter que espera"),
            "s6b": L("A space should come back as a space. A slash you encoded on purpose should come back as /. If the text is still full of % signs, it was encoded twice.", "空格应当变回空格。你故意编码的斜杠应当变回 /。文字里还满是 %，就是编码了两次。", "空格應當變回空格。你故意編碼的斜線應當變回 /。文字裡還滿是 %，就是編碼了兩次。", "空白は空白に戻る。意図して符号化したスラッシュは / に戻る。まだ % だらけなら二度符号化されている。", "공백은 공백으로 돌아와야 합니다. 일부러 인코딩한 슬래시는 /로 돌아와야 합니다. 글에 %가 그대로 가득하면 두 번 인코딩된 것입니다.", "Dấu cách phải trở lại thành dấu cách. Gạch chéo bạn cố ý mã hóa phải trở lại thành /. Nếu chữ vẫn đầy dấu %, đó là mã hóa hai lần.", "Spasi harus kembali menjadi spasi. Garis miring yang sengaja dienkode harus kembali menjadi /. Jika teks masih penuh tanda %, itu dienkode dua kali.", "Un espacio debe volver a ser un espacio. Una barra que codificó a propósito debe volver a ser /. Si el texto sigue lleno de %, se codificó dos veces."),
            "diagram1": L("A space encodes as %20. A slash encodes as %2F. + decodes as a space.", "空格编码成 %20。斜杠编码成 %2F。+ 解码成空格。", "空格編碼成 %20。斜線編碼成 %2F。+ 解碼成空格。", "空白は %20。スラッシュは %2F。+ は空白に復号。", "공백은 %20. 슬래시는 %2F. +는 공백으로 디코드.", "Dấu cách thành %20. Gạch chéo thành %2F. + giải thành dấu cách.", "Spasi menjadi %20. Garis miring menjadi %2F. + menjadi spasi.", "Un espacio se codifica como %20. Una barra como %2F. + se decodifica como espacio."),
            "diagram2": L("% must have two hex digits. Encoding twice leaves the % signs in place.", "% 后面要有两位十六进制。编码两次，% 还会留在文字里。", "% 後面要有兩位十六進制。編碼兩次，% 還會留在文字裡。", "% の後は 16進二桁。二度符号化すると % が残る。", "% 뒤에는 16진 두 자리. 두 번 인코딩하면 %가 글에 남습니다.", "% phải có hai chữ số hex. Mã hóa hai lần thì dấu % còn trong chữ.", "% harus punya dua digit heksa. Enkode dua kali meninggalkan tanda %.", "% debe tener dos dígitos hex. Codificar dos veces deja los % en el texto."),
        },
        {
            "q1": L("Can I encode a URL free online?", "可以免费在线做网址编码吗？", "可以免費線上做網址編碼嗎？", "URLを無料で符号化できる？", "URL을 무료로 인코딩할 수 있나요?", "Mã hóa URL miễn phí online được không?", "Bisa enkode URL gratis online?", "¿Puedo codificar una URL gratis en línea?"),
            "a1": L("Yes. cv.cm encodes and decodes the string in this tab. Nothing is uploaded.", "可以。cv.cm 在当前标签页编码和解码这段文字。不上传。", "可以。cv.cm 在目前分頁編碼和解碼這段文字。不上傳。", "できる。このタブで文字列を符号化・復号。アップロードなし。", "됩니다. 이 탭에서 문자열을 인코딩하고 디코딩합니다. 업로드 없음.", "Được. Mã hóa và giải mã chuỗi trong tab này. Không tải lên.", "Ya. Mengenkode dan mendekode string di tab ini. Tidak diunggah.", "Sí. Codifica y decodifica el texto en esta pestaña. Nada se sube."),
            "q2": L("What happens to a space?", "空格会怎样？", "空格會怎樣？", "空白はどうなる？", "공백은 어떻게 되나요?", "Dấu cách thì sao?", "Apa yang terjadi pada spasi?", "¿Qué pasa con un espacio?"),
            "a2": L("Encode writes %20. Decode turns %20 and + into a space.", "编码写成 %20。解码把 %20 和 + 变成空格。", "編碼寫成 %20。解碼把 %20 和 + 變成空格。", "符号化は %20。復号は %20 と + を空白にする。", "인코드는 %20으로 씁니다. 디코드는 %20과 +를 공백으로 바꿉니다.", "Mã hóa viết %20. Giải mã biến %20 và + thành dấu cách.", "Enkode menulis %20. Dekode mengubah %20 dan + menjadi spasi.", "Codificar escribe %20. Decodificar convierte %20 y + en un espacio."),
            "q3": L("Will slashes stay if I encode a whole address?", "整段地址编码后斜杠还在吗？", "整段地址編碼後斜線還在嗎？", "アドレス全体を符号化するとスラッシュは残る？", "주소 전체를 인코딩하면 슬래시가 남나요?", "Mã hóa cả địa chỉ thì gạch chéo còn không?", "Jika enkode seluruh alamat, apakah garis miring tetap?", "¿Las barras se quedan si codifico una dirección entera?"),
            "a3": L("No. : and / become %3A and %2F. Encode a query value when the address itself must stay openable.", "不在。冒号和斜杠会变成 %3A 和 %2F。地址本身还要能打开时，只编码查询值。", "不在。冒號和斜線會變成 %3A 和 %2F。地址本身還要能打開時，只編碼查詢值。", "残らない。: と / は %3A と %2F。アドレス自体を開けるままにするならクエリ値だけ符号化する。", "남지 않습니다. : 와 / 는 %3A 와 %2F 가 됩니다. 주소 자체가 열려야 하면 쿼리 값만 인코딩하세요.", "Không. : và / thành %3A và %2F. Khi địa chỉ vẫn phải mở được, chỉ mã hóa giá trị query.", "Tidak. : dan / menjadi %3A dan %2F. Jika alamatnya sendiri harus tetap bisa dibuka, enkode hanya nilai query.", "No. : y / pasan a %3A y %2F. Codifique un valor de consulta cuando la dirección deba seguir pudiendo abrirse."),
            "q4": L("Why did decode fail?", "为什么解码失败？", "為什麼解碼失敗？", "なぜ復号に失敗する？", "왜 디코드가 실패하나요?", "Sao giải mã thất bại?", "Kenapa dekode gagal?", "¿Por qué falló la decodificación?"),
            "a4": L("A % needs two hex digits after it. %zz and a lone % fail.", "% 后面要有两位十六进制。%zz 和单独的 % 会失败。", "% 後面要有兩位十六進制。%zz 和單獨的 % 會失敗。", "% の後に 16進二桁が要る。%zz と単独の % は失敗。", "% 뒤에는 16진 두 자리가 필요합니다. %zz와 홀로 있는 %는 실패합니다.", "% cần hai chữ số hex phía sau. %zz và % đơn độc thì thất bại.", "% perlu dua digit heksa sesudahnya. %zz dan % sendirian gagal.", "% necesita dos dígitos hex detrás. %zz y un % solo fallan."),
            "q5": L("Is the string uploaded?", "字符串会上传吗？", "字串會上傳嗎？", "アップロードされる？", "업로드되나요?", "Chuỗi có bị tải lên không?", "Apakah string diunggah?", "¿Se sube el texto?"),
            "a5": L("No. Closing the tab discards it.", "不会。关掉标签页就没了。", "不會。關掉分頁就沒了。", "しない。タブを閉じると消える。", "아니요. 탭을 닫으면 사라집니다.", "Không. Đóng tab là mất.", "Tidak. Tutup tab, hilang.", "No. Al cerrar la pestaña se pierde."),
        },
    ),
    "calculate-age": lesson(
        {
            "name": L("How to calculate age", "怎么算年龄", "怎麼算年齡", "年齢の計算方法", "나이 계산하는 법", "Cách tính tuổi", "Cara hitung umur", "Cómo calcular la edad"),
            "blurb": L("Count civil years, months, and days. Born 15 March 2000, on 14 March 2026 the age is still 25 years, 11 months, and 27 days.", "按公历算年、月、日。2000 年 3 月 15 日出生，到 2026 年 3 月 14 日仍是 25 岁 11 个月 27 天。", "按公曆算年、月、日。2000 年 3 月 15 日出生，到 2026 年 3 月 14 日仍是 25 歲 11 個月 27 天。", "暦の年・月・日で数える。2000年3月15日生まれは、2026年3月14日でもまだ 25歳11か月27日。", "민법상 연, 월, 일로 셉니다. 2000년 3월 15일생은 2026년 3월 14일에도 아직 25세 11개월 27일입니다.", "Đếm năm, tháng, ngày dương lịch. Sinh 15/3/2000, đến 14/3/2026 vẫn là 25 năm, 11 tháng và 27 ngày.", "Hitung tahun, bulan, dan hari sipil. Lahir 15 Maret 2000, pada 14 Maret 2026 umurnya masih 25 tahun, 11 bulan, dan 27 hari.", "Cuente años, meses y días civiles. Nacido el 15 de marzo de 2000, el 14 de marzo de 2026 la edad sigue siendo 25 años, 11 meses y 27 días."),
            "title": L("How to calculate age", "怎么算年龄", "怎麼算年齡", "年齢の計算方法", "나이 계산하는 법", "Cách tính tuổi", "Cara hitung umur", "Cómo calcular la edad"),
            "lead": L("You have a birth date and a later date. You will read years, months, days, and total days in this tab. The birthday that has not arrived yet does not add a year. A date before the birth date fails.", "你有出生日期和之后的一个日期。在当前标签页看年、月、日和总天数。还没到的生日不会加上一岁。早于出生日期的日期会失败。", "你有出生日期和之後的一個日期。在目前分頁看年、月、日和總天數。還沒到的生日不會加上一歲。早於出生日期的日期會失敗。", "生年月日とその後の日付がある。このタブで年・月・日と総日数を読む。まだ来ていない誕生日は一歳を足さない。生年月日より前の日付は失敗。", "출생일과 그 이후 날짜가 있습니다. 이 탭에서 연, 월, 일, 총일수를 읽으세요. 아직 오지 않은 생일은 한 살을 더하지 않습니다. 출생일보다 앞선 날짜는 실패합니다.", "Bạn có ngày sinh và một ngày sau đó. Đọc năm, tháng, ngày và tổng số ngày trong tab này. Sinh nhật chưa tới thì không cộng thêm một tuổi. Ngày trước ngày sinh thì thất bại.", "Anda punya tanggal lahir dan tanggal sesudahnya. Baca tahun, bulan, hari, dan total hari di tab ini. Ulang tahun yang belum tiba tidak menambah satu tahun. Tanggal sebelum lahir gagal.", "Tiene una fecha de nacimiento y una fecha posterior. Lea años, meses, días y días totales aquí. El cumpleaños que aún no llega no suma un año. Una fecha anterior al nacimiento falla."),
            "result": L("Years, months, and days on the civil calendar, plus the total day gap from the birth date to the later date.", "公历上的年、月、日，以及从出生日到后面那个日期的总天数间隔。", "公曆上的年、月、日，以及從出生日到後面那個日期的總天數間隔。", "暦の年・月・日と、生年月日から後の日付までの総日数の間隔。", "민법 달력의 연, 월, 일, 그리고 출생일부터 나중 날짜까지의 총일수 간격.", "Năm, tháng, ngày trên lịch dương, cộng khoảng tổng số ngày từ ngày sinh đến ngày sau.", "Tahun, bulan, dan hari pada kalender sipil, plus jarak total hari dari tanggal lahir ke tanggal sesudahnya.", "Años, meses y días del calendario civil, más el hueco total de días desde el nacimiento hasta la fecha posterior."),
            "note": L("Open age when both dates are real civil dates. The later date cannot be before the birth date. Nothing is uploaded.", "两个日期都是真实公历日期再打开年龄。后面的日期不能早于出生日。不上传。", "兩個日期都是真實公曆日期再開年齡。後面的日期不能早於出生日。不上傳。", "両方とも実在する暦日になってから開く。後の日付は生年月日より前にできない。アップロードなし。", "두 날짜가 실제 민법 날짜일 때 나이를 여세요. 나중 날짜는 출생일보다 앞설 수 없습니다. 업로드 없음.", "Cả hai ngày là ngày dương lịch thật thì mở tuổi. Ngày sau không thể trước ngày sinh. Không tải lên.", "Kedua tanggal adalah tanggal sipil yang nyata, baru buka umur. Tanggal sesudahnya tidak boleh sebelum tanggal lahir. Tidak diunggah.", "Abra la edad cuando ambas fechas sean fechas civiles reales. La fecha posterior no puede ser anterior al nacimiento. Nada se sube."),
            "s1t": L("Wait for the birthday before adding a year", "生日到了再加一岁", "生日到了再加一歲", "誕生日が来てから一歳足す", "생일이 온 뒤에 한 살 더하기", "Đợi đến sinh nhật rồi mới cộng một tuổi", "Tunggu ulang tahun sebelum menambah satu tahun", "Espere el cumpleaños antes de sumar un año"),
            "s1b": L("Born 15 March 2000, on 14 March 2026 the age is 25 years, 11 months, and 27 days. On 15 March 2026 it is 26 years, 0 months, and 0 days.", "2000 年 3 月 15 日出生，到 2026 年 3 月 14 日是 25 岁 11 个月 27 天。到 2026 年 3 月 15 日是 26 岁 0 个月 0 天。", "2000 年 3 月 15 日出生，到 2026 年 3 月 14 日是 25 歲 11 個月 27 天。到 2026 年 3 月 15 日是 26 歲 0 個月 0 天。", "2000年3月15日生まれは、2026年3月14日で 25歳11か月27日。2026年3月15日で 26歳0か月0日。", "2000년 3월 15일생은 2026년 3월 14일에 25세 11개월 27일. 2026년 3월 15일에는 26세 0개월 0일.", "Sinh 15/3/2000, đến 14/3/2026 là 25 năm, 11 tháng, 27 ngày. Đến 15/3/2026 là 26 năm, 0 tháng, 0 ngày.", "Lahir 15 Maret 2000, pada 14 Maret 2026 umurnya 25 tahun, 11 bulan, 27 hari. Pada 15 Maret 2026 menjadi 26 tahun, 0 bulan, 0 hari.", "Nacido el 15 de marzo de 2000, el 14 de marzo de 2026 tiene 25 años, 11 meses y 27 días. El 15 de marzo de 2026 tiene 26 años, 0 meses y 0 días."),
            "s2t": L("Open age on cv.cm", "打开 cv.cm 的年龄", "打開 cv.cm 的年齡", "cv.cmの年齢を開く", "cv.cm 나이를 열기", "Mở tuổi trên cv.cm", "Buka umur di cv.cm", "Abra la edad en cv.cm"),
            "s2b": L("The count stays in this tab.", "计算留在当前标签页。", "計算留在目前分頁。", "計算はこのタブ。", "계산은 이 탭에서.", "Tính trong tab này.", "Hitungan di tab ini.", "La cuenta queda en esta pestaña."),
            "s3t": L("Enter the birth date and the later date", "填出生日和后面的日期", "填出生日和後面的日期", "生年月日と後の日付を入れる", "출생일과 나중 날짜 넣기", "Nhập ngày sinh và ngày sau", "Isi tanggal lahir dan tanggal sesudahnya", "Escriba el nacimiento y la fecha posterior"),
            "s3b": L("Both are civil dates, YYYY-MM-DD. A later date before the birth date fails. Today on this page is the calendar date of this computer, not a UTC clock time.", "两个都是公历日期，YYYY-MM-DD。后面的日期早于出生日会失败。这一页的今天是这台电脑的日历日期，不是 UTC 钟点。", "兩個都是公曆日期，YYYY-MM-DD。後面的日期早於出生日會失敗。這一頁的今天是這台電腦的日曆日期，不是 UTC 鐘點。", "両方とも暦日 YYYY-MM-DD。後の日付が生年月日より前だと失敗。このページの今日はこのコンピュータの暦日であり UTC の時刻ではない。", "둘 다 민법 날짜 YYYY-MM-DD. 나중 날짜가 출생일보다 앞이면 실패합니다. 이 페이지의 오늘은 이 컴퓨터의 달력 날짜이지 UTC 시계 시각이 아닙니다.", "Cả hai là ngày dương lịch YYYY-MM-DD. Ngày sau trước ngày sinh thì thất bại. Hôm nay trên trang này là ngày lịch của máy này, không phải giờ UTC.", "Keduanya tanggal sipil YYYY-MM-DD. Tanggal sesudahnya yang sebelum lahir gagal. Hari ini di halaman ini adalah tanggal kalender komputer ini, bukan jam UTC.", "Ambas son fechas civiles, YYYY-MM-DD. Una fecha posterior anterior al nacimiento falla. Hoy en esta página es la fecha de calendario de este equipo, no una hora UTC."),
            "s4t": L("Read years, months, and days", "看年、月、日", "看年、月、日", "年・月・日を読む", "연, 월, 일 읽기", "Đọc năm, tháng, ngày", "Baca tahun, bulan, dan hari", "Lea años, meses y días"),
            "s4b": L("If the day of the month has not been reached, the count borrows the previous month. 14 March has not reached a 15 March birthday, so the years stay 25 and the months are 11.", "这个月的那一天还没到，就借上一个月。3 月 14 日还没到 3 月 15 日的生日，所以岁数停在 25，月份是 11。", "這個月的那一天還沒到，就借上一個月。3 月 14 日還沒到 3 月 15 日的生日，所以歲數停在 25，月份是 11。", "その月の日にまだ届いていなければ前の月を借りる。3月14日は 3月15日の誕生日に届いていないので、歳は 25 のまま、月は 11。", "그달의 그 날에 아직 닿지 않았으면 이전 달을 빌립니다. 3월 14일은 3월 15일 생일에 닿지 않았으므로 나이는 25에 머물고 개월은 11입니다.", "Nếu chưa tới ngày trong tháng, phép đếm mượn tháng trước. 14/3 chưa tới sinh nhật 15/3, nên tuổi vẫn 25 và tháng là 11.", "Jika hari dalam bulan belum tercapai, hitungan meminjam bulan sebelumnya. 14 Maret belum mencapai ulang tahun 15 Maret, jadi tahun tetap 25 dan bulannya 11.", "Si aún no se ha llegado al día del mes, la cuenta toma prestado el mes anterior. El 14 de marzo no ha llegado al cumpleaños del 15 de marzo, así que los años siguen en 25 y los meses son 11."),
            "s5t": L("Read total days as a gap", "把总天数当成间隔来读", "把總天數當成間隔來讀", "総日数は間隔として読む", "총일수는 간격으로 읽기", "Đọc tổng số ngày như một khoảng", "Baca total hari sebagai jarak", "Lea los días totales como un hueco"),
            "s5b": L("Total days do not count both ends. From 15 March 2000 to 14 March 2026 is 9,495 days. The next day, the birthday, is 9,496.", "总天数不把两头都算进去。从 2000 年 3 月 15 日到 2026 年 3 月 14 日是 9,495 天。第二天生日是 9,496 天。", "總天數不把兩頭都算進去。從 2000 年 3 月 15 日到 2026 年 3 月 14 日是 9,495 天。第二天生日是 9,496 天。", "総日数は両端を含まない。2000年3月15日から 2026年3月14日は 9,495 日。翌日の誕生日は 9,496 日。", "총일수는 양쪽을 포함하지 않습니다. 2000년 3월 15일부터 2026년 3월 14일까지는 9,495일. 다음 날 생일은 9,496일.", "Tổng số ngày không tính cả hai đầu. Từ 15/3/2000 đến 14/3/2026 là 9.495 ngày. Ngày hôm sau, sinh nhật, là 9.496.", "Total hari tidak menghitung kedua ujung. Dari 15 Maret 2000 sampai 14 Maret 2026 adalah 9.495 hari. Hari berikutnya, ulang tahun, adalah 9.496.", "Los días totales no cuentan ambos extremos. Del 15 de marzo de 2000 al 14 de marzo de 2026 hay 9.495 días. Al día siguiente, el cumpleaños, hay 9.496."),
            "s6t": L("Keep 29 February as a real birth date", "2 月 29 日仍是真实的出生日", "2 月 29 日仍是真實的出生日", "2月29日も実在する誕生日", "2월 29일도 실제 출생일", "29 tháng Hai vẫn là ngày sinh thật", "29 Februari tetap tanggal lahir yang nyata", "El 29 de febrero sigue siendo una fecha de nacimiento real"),
            "s6b": L("A leap-day birth is a civil date. On 28 February 2025, someone born 29 February 2000 is 24 years, 11 months, and 30 days. The birthday has not arrived.", "闰日出生也是公历日期。2025 年 2 月 28 日，2000 年 2 月 29 日出生的人是 24 岁 11 个月 30 天。生日还没到。", "閏日出生也是公曆日期。2025 年 2 月 28 日，2000 年 2 月 29 日出生的人是 24 歲 11 個月 30 天。生日還沒到。", "うるう日の誕生も暦日。2025年2月28日、2000年2月29日生まれは 24歳11か月30日。誕生日はまだ来ていない。", "윤일 출생도 민법 날짜입니다. 2025년 2월 28일, 2000년 2월 29일생은 24세 11개월 30일. 생일은 아직 오지 않았습니다.", "Sinh ngày nhuận cũng là ngày dương lịch. Ngày 28/2/2025, người sinh 29/2/2000 là 24 năm, 11 tháng và 30 ngày. Sinh nhật chưa tới.", "Kelahiran hari kabisat juga tanggal sipil. Pada 28 Februari 2025, orang lahir 29 Februari 2000 berumur 24 tahun, 11 bulan, dan 30 hari. Ulang tahunnya belum tiba.", "Un nacimiento en día bisiesto también es una fecha civil. El 28 de febrero de 2025, quien nació el 29 de febrero de 2000 tiene 24 años, 11 meses y 30 días. El cumpleaños no ha llegado."),
            "diagram1": L("15 Mar 2000 to 14 Mar 2026: 25 years, 11 months, 27 days.", "2000-03-15 到 2026-03-14：25 岁 11 个月 27 天。", "2000-03-15 到 2026-03-14：25 歲 11 個月 27 天。", "2000-03-15 から 2026-03-14：25歳11か月27日。", "2000-03-15부터 2026-03-14: 25세 11개월 27일.", "15/3/2000 đến 14/3/2026: 25 năm, 11 tháng, 27 ngày.", "15 Mar 2000 sampai 14 Mar 2026: 25 tahun, 11 bulan, 27 hari.", "15 mar 2000 al 14 mar 2026: 25 años, 11 meses, 27 días."),
            "diagram2": L("The next day is 26 years, 0 months, 0 days. Total days are a gap.", "第二天是 26 岁 0 个月 0 天。总天数是间隔。", "第二天是 26 歲 0 個月 0 天。總天數是間隔。", "翌日は 26歳0か月0日。総日数は間隔。", "다음 날은 26세 0개월 0일. 총일수는 간격.", "Ngày hôm sau là 26 năm, 0 tháng, 0 ngày. Tổng số ngày là khoảng.", "Hari berikutnya adalah 26 tahun, 0 bulan, 0 hari. Total hari adalah jarak.", "Al día siguiente: 26 años, 0 meses, 0 días. Los días totales son un hueco."),
        },
        {
            "q1": L("Can I calculate age free online?", "可以免费在线算年龄吗？", "可以免費線上算年齡嗎？", "年齢を無料で計算できる？", "나이를 무료로 계산할 수 있나요?", "Tính tuổi miễn phí online được không?", "Bisa hitung umur gratis online?", "¿Puedo calcular la edad gratis en línea?"),
            "a1": L("Yes. cv.cm shows years, months, days, and total days in this tab. Nothing is uploaded.", "可以。cv.cm 在当前标签页显示年、月、日和总天数。不上传。", "可以。cv.cm 在目前分頁顯示年、月、日和總天數。不上傳。", "できる。このタブで年・月・日と総日数を出す。アップロードなし。", "됩니다. 이 탭에서 연, 월, 일, 총일수를 보여 줍니다. 업로드 없음.", "Được. Hiện năm, tháng, ngày và tổng số ngày trong tab này. Không tải lên.", "Ya. Menampilkan tahun, bulan, hari, dan total hari di tab ini. Tidak diunggah.", "Sí. Muestra años, meses, días y días totales en esta pestaña. Nada se sube."),
            "q2": L("Does the year increase before the birthday?", "生日之前会加一岁吗？", "生日之前會加一歲嗎？", "誕生日の前に一歳増える？", "생일 전에 한 살이 늘나요?", "Trước sinh nhật đã tăng một tuổi chưa?", "Apakah tahun bertambah sebelum ulang tahun?", "¿El año aumenta antes del cumpleaños?"),
            "a2": L("No. Born 15 March 2000, on 14 March 2026 the age is still 25 years, 11 months, and 27 days.", "不会。2000 年 3 月 15 日出生，到 2026 年 3 月 14 日仍是 25 岁 11 个月 27 天。", "不會。2000 年 3 月 15 日出生，到 2026 年 3 月 14 日仍是 25 歲 11 個月 27 天。", "増えない。2000年3月15日生まれは 2026年3月14日でも 25歳11か月27日。", "늘지 않습니다. 2000년 3월 15일생은 2026년 3월 14일에도 25세 11개월 27일입니다.", "Không. Sinh 15/3/2000, đến 14/3/2026 vẫn là 25 năm, 11 tháng và 27 ngày.", "Tidak. Lahir 15 Maret 2000, pada 14 Maret 2026 umurnya masih 25 tahun, 11 bulan, dan 27 hari.", "No. Nacido el 15 de marzo de 2000, el 14 de marzo de 2026 sigue teniendo 25 años, 11 meses y 27 días."),
            "q3": L("What if the later date is before the birth date?", "后面的日期早于出生日呢？", "後面的日期早於出生日呢？", "後の日付が生年月日より前なら？", "나중 날짜가 출생일보다 앞이면?", "Ngày sau trước ngày sinh thì sao?", "Jika tanggal sesudahnya sebelum lahir?", "¿Y si la fecha posterior es anterior al nacimiento?"),
            "a3": L("The page fails. Age counts forward from the birth date.", "这一页会失败。年龄从出生日往后数。", "這一頁會失敗。年齡從出生日往後數。", "失敗する。年齢は生年月日から先へ数える。", "페이지가 실패합니다. 나이는 출생일부터 앞으로 셉니다.", "Trang thất bại. Tuổi đếm từ ngày sinh về sau.", "Halaman gagal. Umur dihitung maju dari tanggal lahir.", "La página falla. La edad cuenta hacia adelante desde el nacimiento."),
            "q4": L("Is 29 February a real birth date?", "2 月 29 日是真实的出生日吗？", "2 月 29 日是真實的出生日嗎？", "2月29日は実在する誕生日？", "2월 29일은 실제 출생일인가요?", "29 tháng Hai có phải ngày sinh thật?", "Apakah 29 Februari tanggal lahir yang nyata?", "¿El 29 de febrero es una fecha de nacimiento real?"),
            "a4": L("Yes. On 28 February 2025, a 29 February 2000 birth is 24 years, 11 months, and 30 days.", "是。2025 年 2 月 28 日，2000 年 2 月 29 日出生是 24 岁 11 个月 30 天。", "是。2025 年 2 月 28 日，2000 年 2 月 29 日出生是 24 歲 11 個月 30 天。", "はい。2025年2月28日、2000年2月29日生まれは 24歳11か月30日。", "예. 2025년 2월 28일, 2000년 2월 29일생은 24세 11개월 30일입니다.", "Có. Ngày 28/2/2025, sinh 29/2/2000 là 24 năm, 11 tháng và 30 ngày.", "Ya. Pada 28 Februari 2025, kelahiran 29 Februari 2000 berumur 24 tahun, 11 bulan, dan 30 hari.", "Sí. El 28 de febrero de 2025, un nacimiento del 29 de febrero de 2000 tiene 24 años, 11 meses y 30 días."),
            "q5": L("Are the dates uploaded?", "日期会上传吗？", "日期會上傳嗎？", "アップロードされる？", "업로드되나요?", "Ngày có bị tải lên không?", "Apakah tanggal diunggah?", "¿Se suben las fechas?"),
            "a5": L("No. Closing the tab discards them.", "不会。关掉标签页就没了。", "不會。關掉分頁就沒了。", "しない。タブを閉じると消える。", "아니요. 탭을 닫으면 사라집니다.", "Không. Đóng tab là mất.", "Tidak. Tutup tab, hilang.", "No. Al cerrar la pestaña se pierden."),
        },
    ),
    "aspect-ratio": lesson(
        {
            "name": L("How to find an aspect ratio", "怎么算宽高比", "怎麼算寬高比", "アスペクト比の求め方", "화면 비율 구하는 법", "Cách tìm tỉ lệ khung", "Cara cari rasio aspek", "Cómo hallar una relación de aspecto"),
            "blurb": L("Reduce whole pixels. 1920 by 1080 is 16:9. 1080 by 1920 is 9:16. Decimals are rounded before the ratio. This does not crop a photo.", "先把像素收成整数再约分。1920 比 1080 是 16:9。1080 比 1920 是 9:16。小数会先四舍五入。这不会裁照片。", "先把像素收成整數再約分。1920 比 1080 是 16:9。1080 比 1920 是 9:16。小數會先四捨五入。這不會裁照片。", "整数ピクセルにしてから約分。1920 対 1080 は 16:9。1080 対 1920 は 9:16。小数は先に丸める。写真は切らない。", "정수 픽셀로 줄인 뒤 약분합니다. 1920 대 1080은 16:9. 1080 대 1920은 9:16. 소수는 비율 전에 반올림됩니다. 사진을 자르지 않습니다.", "Rút gọn pixel nguyên. 1920 trên 1080 là 16:9. 1080 trên 1920 là 9:16. Số lẻ được làm tròn trước tỉ lệ. Việc này không cắt ảnh.", "Sederhanakan piksel bulat. 1920 banding 1080 adalah 16:9. 1080 banding 1920 adalah 9:16. Desimal dibulatkan sebelum rasio. Ini tidak memotong foto.", "Reduzca píxeles enteros. 1920 por 1080 es 16:9. 1080 por 1920 es 9:16. Los decimales se redondean antes de la relación. Esto no recorta una foto."),
            "title": L("How to find an aspect ratio", "怎么算宽高比", "怎麼算寬高比", "アスペクト比の求め方", "화면 비율 구하는 법", "Cách tìm tỉ lệ khung", "Cara cari rasio aspek", "Cómo hallar una relación de aspecto"),
            "lead": L("You have a width and a height in pixels. You will reduce them in this tab. The order matters: 1920×1080 is 16:9, and 1080×1920 is 9:16. The page rounds to whole pixels first. It does not cut the picture.", "你有像素宽和像素高。在当前标签页把它们约分。顺序要紧：1920×1080 是 16:9，1080×1920 是 9:16。这一页先把数收成整数像素。它不裁图片。", "你有像素寬和像素高。在目前分頁把它們約分。順序要緊：1920×1080 是 16:9，1080×1920 是 9:16。這一頁先把數收成整數像素。它不裁圖片。", "ピクセルの幅と高さがある。このタブで約分する。順序が大事。1920×1080 は 16:9、1080×1920 は 9:16。先に整数ピクセルへ丸める。絵は切らない。", "픽셀 너비와 높이가 있습니다. 이 탭에서 약분하세요. 순서가 중요합니다. 1920×1080은 16:9이고 1080×1920은 9:16. 페이지는 먼저 정수 픽셀로 반올림합니다. 그림을 자르지 않습니다.", "Bạn có chiều rộng và chiều cao bằng pixel. Rút gọn trong tab này. Thứ tự quan trọng: 1920×1080 là 16:9, 1080×1920 là 9:16. Trang làm tròn thành pixel nguyên trước. Nó không cắt ảnh.", "Anda punya lebar dan tinggi dalam piksel. Sederhanakan di tab ini. Urutannya penting: 1920×1080 adalah 16:9, dan 1080×1920 adalah 9:16. Halaman membulatkan ke piksel utuh dulu. Tidak memotong gambar.", "Tiene un ancho y un alto en píxeles. Redúzcalos aquí. El orden importa: 1920×1080 es 16:9, y 1080×1920 es 9:16. La página redondea primero a píxeles enteros. No recorta la imagen."),
            "result": L("A reduced ratio such as 16:9, plus the decimal width divided by height.", "一个约好的比，例如 16:9，外加宽度除以高度的小数。", "一個約好的比，例如 16:9，外加寬度除以高度的小數。", "16:9 のような既約比と、幅÷高さの小数。", "16:9 같은 기약 비율과, 너비를 높이로 나눈 소수.", "Một tỉ lệ đã rút như 16:9, cộng số thập phân chiều rộng chia chiều cao.", "Rasio yang disederhanakan seperti 16:9, plus desimal lebar dibagi tinggi.", "Una relación reducida como 16:9, más el decimal del ancho dividido por el alto."),
            "note": L("Open aspect ratio when you know the two pixel counts. Width and height must be greater than zero. Nothing is uploaded.", "两个像素数都清楚再打开宽高比。宽和高都要大于 0。不上传。", "兩個像素數都清楚再開寬高比。寬和高都要大於 0。不上傳。", "二つのピクセル数が分かってから開く。幅も高さも 0 より大きいこと。アップロードなし。", "두 픽셀 수를 알 때 화면 비율을 여세요. 너비와 높이는 0보다 커야 합니다. 업로드 없음.", "Biết hai số pixel thì mở tỉ lệ khung. Rộng và cao phải lớn hơn 0. Không tải lên.", "Tahu dua jumlah piksel, baru buka rasio aspek. Lebar dan tinggi harus lebih dari nol. Tidak diunggah.", "Abra la relación de aspecto cuando sepa los dos conteos de píxeles. El ancho y el alto deben ser mayores que cero. Nada se sube."),
            "s1t": L("Keep width and height in order", "宽和高不要对调", "寬和高不要對調", "幅と高さの順を守る", "너비와 높이 순서를 지키기", "Giữ đúng thứ tự rộng và cao", "Jaga urutan lebar dan tinggi", "Mantenga el ancho y el alto en orden"),
            "s1b": L("1920 wide and 1080 tall is 16:9. 1080 wide and 1920 tall is 9:16. A portrait frame and a landscape frame are not the same ratio.", "宽 1920、高 1080 是 16:9。宽 1080、高 1920 是 9:16。竖幅和横幅不是同一个比。", "寬 1920、高 1080 是 16:9。寬 1080、高 1920 是 9:16。直幅和橫幅不是同一個比。", "幅 1920・高さ 1080 は 16:9。幅 1080・高さ 1920 は 9:16。縦位置と横位置は同じ比ではない。", "너비 1920, 높이 1080은 16:9. 너비 1080, 높이 1920은 9:16. 세로 프레임과 가로 프레임은 같은 비율이 아닙니다.", "Rộng 1920, cao 1080 là 16:9. Rộng 1080, cao 1920 là 9:16. Khung dọc và khung ngang không phải cùng một tỉ lệ.", "Lebar 1920 dan tinggi 1080 adalah 16:9. Lebar 1080 dan tinggi 1920 adalah 9:16. Bingkai potret dan bingkai lanskap bukan rasio yang sama.", "1920 de ancho y 1080 de alto es 16:9. 1080 de ancho y 1920 de alto es 9:16. Un marco vertical y uno horizontal no son la misma relación."),
            "s2t": L("Open aspect ratio on cv.cm", "打开 cv.cm 的宽高比", "打開 cv.cm 的寬高比", "cv.cmのアスペクト比を開く", "cv.cm 화면 비율을 열기", "Mở tỉ lệ khung trên cv.cm", "Buka rasio aspek di cv.cm", "Abra la relación de aspecto en cv.cm"),
            "s2b": L("The reduction stays in this tab.", "约分留在当前标签页。", "約分留在目前分頁。", "約分はこのタブ。", "약분은 이 탭에서.", "Việc rút gọn ở trong tab này.", "Penyederhanaan di tab ini.", "La reducción queda en esta pestaña."),
            "s3t": L("Enter width and height in pixels", "填像素宽和像素高", "填像素寬和像素高", "幅と高さをピクセルで入れる", "너비와 높이를 픽셀로 넣기", "Nhập rộng và cao bằng pixel", "Isi lebar dan tinggi dalam piksel", "Escriba el ancho y el alto en píxeles"),
            "s3b": L("Both must be greater than zero. The page rounds each number to a whole pixel before it reduces. 1920 and 1080 become 16 and 9.", "两个都要大于 0。这一页先把每个数收成整数像素，再约分。1920 和 1080 变成 16 和 9。", "兩個都要大於 0。這一頁先把每個數收成整數像素，再約分。1920 和 1080 變成 16 和 9。", "両方 0 より大きいこと。約分の前に各数を整数ピクセルへ丸める。1920 と 1080 は 16 と 9。", "둘 다 0보다 커야 합니다. 페이지는 약분하기 전에 각 수를 정수 픽셀로 반올림합니다. 1920과 1080은 16과 9가 됩니다.", "Cả hai phải lớn hơn 0. Trang làm tròn từng số thành pixel nguyên trước khi rút. 1920 và 1080 thành 16 và 9.", "Keduanya harus lebih dari nol. Halaman membulatkan tiap angka ke piksel utuh sebelum menyederhanakan. 1920 dan 1080 menjadi 16 dan 9.", "Ambos deben ser mayores que cero. La página redondea cada número a un píxel entero antes de reducir. 1920 y 1080 pasan a 16 y 9."),
            "s4t": L("Read the reduced ratio and the decimal", "看约好的比和小数", "看約好的比和小數", "既約比と小数を読む", "기약 비율과 소수 읽기", "Đọc tỉ lệ đã rút và số thập phân", "Baca rasio yang disederhanakan dan desimalnya", "Lea la relación reducida y el decimal"),
            "s4b": L("16:9 is the reduced pair. The decimal is width divided by height, about 1.7778 for 1920×1080. Copy keeps the ratio text.", "16:9 是约好的那一对。小数是宽除以高，1920×1080 大约是 1.7778。复制留下的是比的文字。", "16:9 是約好的那一對。小數是寬除以高，1920×1080 大約是 1.7778。複製留下的是比的文字。", "16:9 が既約の組。小数は幅÷高さ。1920×1080 は約 1.7778。コピーは比の文字。", "16:9이 기약 쌍입니다. 소수는 너비 나누기 높이이며 1920×1080은 약 1.7778. 복사는 비율 글을 남깁니다.", "16:9 là cặp đã rút. Số thập phân là rộng chia cao, khoảng 1,7778 với 1920×1080. Bản copy giữ chữ tỉ lệ.", "16:9 adalah pasangan yang disederhanakan. Desimal adalah lebar dibagi tinggi, sekitar 1,7778 untuk 1920×1080. Salinan menyimpan teks rasionya.", "16:9 es el par reducido. El decimal es el ancho dividido por el alto, cerca de 1,7778 para 1920×1080. Copiar conserva el texto de la relación."),
            "s5t": L("Rounding happens before the ratio", "先四舍五入，再算比", "先四捨五入，再算比", "比の前に丸める", "비율 전에 반올림", "Làm tròn trước khi tính tỉ lệ", "Pembulatan terjadi sebelum rasio", "El redondeo ocurre antes de la relación"),
            "s5b": L("A decimal pixel count becomes the nearest whole pixel. If the rounded pair is not the frame you meant, type the whole pixels from the file.", "带小数的像素会变成最接近的整数像素。约出来的一对不是你要的画幅，就改填文件里的整数像素。", "帶小數的像素會變成最接近的整數像素。約出來的一對不是你要的畫幅，就改填檔案裡的整數像素。", "小数のピクセル数は最も近い整数ピクセルになる。丸めた組が意図した画面でないなら、ファイルの整数ピクセルを入れる。", "소수 픽셀 수는 가장 가까운 정수 픽셀이 됩니다. 반올림된 쌍이 원하는 프레임이 아니면 파일의 정수 픽셀을 입력하세요.", "Số pixel lẻ thành pixel nguyên gần nhất. Nếu cặp đã làm tròn không phải khung bạn muốn, hãy gõ pixel nguyên từ tệp.", "Jumlah piksel desimal menjadi piksel utuh terdekat. Jika pasangan yang dibulatkan bukan bingkai yang Anda maksud, ketik piksel utuh dari berkas.", "Un conteo de píxeles decimal pasa al píxel entero más cercano. Si el par redondeado no es el marco que quería, escriba los píxeles enteros del archivo."),
            "s6t": L("Leave the photo uncut", "照片先不要裁", "照片先不要裁", "写真はまだ切らない", "사진은 아직 자르지 않기", "Chưa cắt ảnh", "Jangan potong fotonya dulu", "Deje la foto sin recortar"),
            "s6b": L("This page only reduces two numbers. 1920×1080 becomes 16:9 on the page, and the picture stays 1920 by 1080. Cropping is the crop tool.", "这一页只约分两个数。1920×1080 在页面上变成 16:9，图片仍是 1920 乘 1080。裁切用裁切工具。", "這一頁只約分兩個數。1920×1080 在頁面上變成 16:9，圖片仍是 1920 乘 1080。裁切用裁切工具。", "このページは二つの数を約分するだけ。1920×1080 はページ上で 16:9 になり、絵は 1920×1080 のまま。切り取りは切り取りツール。", "이 페이지는 두 수만 약분합니다. 1920×1080은 페이지에서 16:9이 되고 그림은 1920×1080으로 남습니다. 자르기는 자르기 도구입니다.", "Trang này chỉ rút hai số. 1920×1080 thành 16:9 trên trang, ảnh vẫn 1920 nhân 1080. Cắt ảnh dùng công cụ cắt.", "Halaman ini hanya menyederhanakan dua angka. 1920×1080 menjadi 16:9 di halaman, dan gambar tetap 1920 kali 1080. Memotong memakai alat potong.", "Esta página solo reduce dos números. 1920×1080 pasa a 16:9 en la página, y la imagen sigue siendo 1920 por 1080. Recortar es la herramienta de recorte."),
            "diagram1": L("1920×1080 is 16:9. 1080×1920 is 9:16.", "1920×1080 是 16:9。1080×1920 是 9:16。", "1920×1080 是 16:9。1080×1920 是 9:16。", "1920×1080 は 16:9。1080×1920 は 9:16。", "1920×1080은 16:9. 1080×1920은 9:16.", "1920×1080 là 16:9. 1080×1920 là 9:16.", "1920×1080 adalah 16:9. 1080×1920 adalah 9:16.", "1920×1080 es 16:9. 1080×1920 es 9:16."),
            "diagram2": L("Round to whole pixels first. The photo is not cropped.", "先收成整数像素。照片不会被裁。", "先收成整數像素。照片不會被裁。", "先に整数ピクセルへ。写真は切らない。", "먼저 정수 픽셀로. 사진은 잘리지 않음.", "Làm tròn pixel nguyên trước. Ảnh không bị cắt.", "Bulatkan ke piksel utuh dulu. Foto tidak dipotong.", "Redondee primero a píxeles enteros. La foto no se recorta."),
        },
        {
            "q1": L("Can I find an aspect ratio free online?", "可以免费在线算宽高比吗？", "可以免費線上算寬高比嗎？", "アスペクト比を無料で求められる？", "화면 비율을 무료로 구할 수 있나요?", "Tìm tỉ lệ khung miễn phí online được không?", "Bisa cari rasio aspek gratis online?", "¿Puedo hallar una relación de aspecto gratis en línea?"),
            "a1": L("Yes. cv.cm reduces width and height in this tab. Nothing is uploaded.", "可以。cv.cm 在当前标签页约分宽和高。不上传。", "可以。cv.cm 在目前分頁約分寬和高。不上傳。", "できる。このタブで幅と高さを約分。アップロードなし。", "됩니다. 이 탭에서 너비와 높이를 약분합니다. 업로드 없음.", "Được. Rút rộng và cao trong tab này. Không tải lên.", "Ya. Menyederhanakan lebar dan tinggi di tab ini. Tidak diunggah.", "Sí. Reduce el ancho y el alto en esta pestaña. Nada se sube."),
            "q2": L("What is 1920 by 1080?", "1920 比 1080 是多少？", "1920 比 1080 是多少？", "1920 対 1080 は？", "1920 대 1080은?", "1920 trên 1080 là bao nhiêu?", "1920 banding 1080 berapa?", "¿Cuánto es 1920 por 1080?"),
            "a2": L("16:9. Swap them and it is 9:16.", "16:9。对调之后是 9:16。", "16:9。對調之後是 9:16。", "16:9。入れ替えると 9:16。", "16:9. 바꾸면 9:16입니다.", "16:9. Đổi chỗ thì là 9:16.", "16:9. Ditukar menjadi 9:16.", "16:9. Si se intercambian, es 9:16."),
            "q3": L("Does this crop the photo?", "这会裁照片吗？", "這會裁照片嗎？", "写真は切られる？", "사진을 자르나요?", "Việc này có cắt ảnh không?", "Apakah ini memotong foto?", "¿Esto recorta la foto?"),
            "a3": L("No. It only reduces the two numbers. The picture stays the size you typed.", "不会。它只约分两个数。图片仍是你输入的尺寸。", "不會。它只約分兩個數。圖片仍是你輸入的尺寸。", "切らない。二つの数を約分するだけ。絵は入力した大きさのまま。", "자르지 않습니다. 두 수만 약분합니다. 그림은 입력한 크기로 남습니다.", "Không. Nó chỉ rút hai số. Ảnh vẫn đúng kích thước bạn gõ.", "Tidak. Hanya menyederhanakan dua angka. Gambar tetap seukuran yang Anda ketik.", "No. Solo reduce los dos números. La imagen sigue en el tamaño que escribió."),
            "q4": L("What happens to decimals?", "小数会怎样？", "小數會怎樣？", "小数はどうなる？", "소수는 어떻게 되나요?", "Số lẻ thì sao?", "Apa yang terjadi pada desimal?", "¿Qué pasa con los decimales?"),
            "a4": L("Each side is rounded to a whole pixel before the ratio.", "每一边先收成整数像素，再算比。", "每一邊先收成整數像素，再算比。", "各辺を整数ピクセルに丸めてから比を出す。", "각 변을 정수 픽셀로 반올림한 뒤 비율을 냅니다.", "Mỗi cạnh được làm tròn thành pixel nguyên trước khi tính tỉ lệ.", "Setiap sisi dibulatkan ke piksel utuh sebelum rasio.", "Cada lado se redondea a un píxel entero antes de la relación."),
            "q5": L("Are the numbers uploaded?", "这些数会上传吗？", "這些數會上傳嗎？", "アップロードされる？", "업로드되나요?", "Các số có bị tải lên không?", "Apakah angkanya diunggah?", "¿Se suben los números?"),
            "a5": L("No. Closing the tab discards them.", "不会。关掉标签页就没了。", "不會。關掉分頁就沒了。", "しない。タブを閉じると消える。", "아니요. 탭을 닫으면 사라집니다.", "Không. Đóng tab là mất.", "Tidak. Tutup tab, hilang.", "No. Al cerrar la pestaña se pierden."),
        },
    ),
}

META = {
    "titlePercentOff": L("How to calculate a discount | cv.cm", "怎么算折扣 | cv.cm", "怎麼算折扣 | cv.cm", "割引の計算方法 | cv.cm", "할인 계산하는 법 | cv.cm", "Cách tính giảm giá | cv.cm", "Cara hitung diskon | cv.cm", "Cómo calcular un descuento | cv.cm"),
    "descPercentOff": L("20% off 100 is a sale price of 80.00 and a saving of 20.00. That is not a 20% margin. 120% off can go below zero. A negative percent raises the price. Nothing is uploaded.", "100 的 20% 折扣是售价 80.00、节省 20.00。这不是 20% 利润率。120% 折扣可以低于零。负的百分比会抬高价格。不上传。", "100 的 20% 折扣是售價 80.00、節省 20.00。這不是 20% 利潤率。120% 折扣可以低於零。負的百分比會抬高價格。不上傳。", "100 の 20% 引きは売価 80.00、割引額 20.00。利益率 20% ではない。120% 引きはゼロを下回り得る。負のパーセントは価格を上げる。アップロードなし。", "100의 20% 할인은 판매가 80.00, 절약 20.00. 이익률 20%가 아닙니다. 120% 할인은 0 아래로 갈 수 있습니다. 음수 퍼센트는 가격을 올립니다. 업로드 없음.", "Giảm 20% trên 100 là giá 80,00 và tiết kiệm 20,00. Không phải biên 20%. Giảm 120% có thể dưới 0. Phần trăm âm làm giá tăng. Không tải lên.", "Diskon 20% dari 100 adalah harga 80,00 dan hemat 20,00. Bukan margin 20%. Diskon 120% bisa di bawah nol. Persen negatif menaikkan harga. Tidak diunggah.", "Un 20% sobre 100 es un precio de 80,00 y un ahorro de 20,00. No es un margen del 20%. Un 120% puede bajar de cero. Un porcentaje negativo sube el precio. Nada se sube."),
    "titleEncodeUrl": L("How to encode a URL | cv.cm", "怎么做网址编码 | cv.cm", "怎麼做網址編碼 | cv.cm", "URLエンコードの方法 | cv.cm", "URL 인코딩하는 법 | cv.cm", "Cách mã hóa URL | cv.cm", "Cara enkode URL | cv.cm", "Cómo codificar una URL | cv.cm"),
    "descEncodeUrl": L("Encode turns a space into %20 and also encodes slashes. Decode turns + into a space. A % needs two hex digits. Nothing is uploaded.", "编码把空格变成 %20，斜杠也会被编码。解码把 + 变成空格。% 后面要有两位十六进制。不上传。", "編碼把空格變成 %20，斜線也會被編碼。解碼把 + 變成空格。% 後面要有兩位十六進制。不上傳。", "符号化は空白を %20 にし、スラッシュも符号化する。復号は + を空白にする。% の後は 16進二桁。アップロードなし。", "인코딩은 공백을 %20으로 만들고 슬래시도 인코딩합니다. 디코딩은 +를 공백으로. % 뒤에는 16진 두 자리. 업로드 없음.", "Mã hóa biến dấu cách thành %20 và cả gạch chéo. Giải mã biến + thành dấu cách. % cần hai chữ số hex. Không tải lên.", "Enkode mengubah spasi menjadi %20 dan juga garis miring. Dekode mengubah + menjadi spasi. % perlu dua digit heksa. Tidak diunggah.", "Codificar convierte un espacio en %20 y también las barras. Decodificar convierte + en un espacio. % necesita dos dígitos hex. Nada se sube."),
    "titleCalculateAge": L("How to calculate age | cv.cm", "怎么算年龄 | cv.cm", "怎麼算年齡 | cv.cm", "年齢の計算方法 | cv.cm", "나이 계산하는 법 | cv.cm", "Cách tính tuổi | cv.cm", "Cara hitung umur | cv.cm", "Cómo calcular la edad | cv.cm"),
    "descCalculateAge": L("Born 15 March 2000, on 14 March 2026 the age is 25 years, 11 months, and 27 days. The birthday adds the year. Total days are a gap. Nothing is uploaded.", "2000 年 3 月 15 日出生，到 2026 年 3 月 14 日是 25 岁 11 个月 27 天。生日到了才加这一岁。总天数是间隔。不上传。", "2000 年 3 月 15 日出生，到 2026 年 3 月 14 日是 25 歲 11 個月 27 天。生日到了才加這一歲。總天數是間隔。不上傳。", "2000年3月15日生まれは 2026年3月14日で 25歳11か月27日。誕生日が来てからその一歳を足す。総日数は間隔。アップロードなし。", "2000년 3월 15일생은 2026년 3월 14일에 25세 11개월 27일. 생일이 와야 그 한 살이 더해집니다. 총일수는 간격. 업로드 없음.", "Sinh 15/3/2000, đến 14/3/2026 là 25 năm, 11 tháng, 27 ngày. Sinh nhật tới mới cộng tuổi đó. Tổng số ngày là khoảng. Không tải lên.", "Lahir 15 Maret 2000, pada 14 Maret 2026 umurnya 25 tahun, 11 bulan, 27 hari. Ulang tahun menambah tahun itu. Total hari adalah jarak. Tidak diunggah.", "Nacido el 15 de marzo de 2000, el 14 de marzo de 2026 tiene 25 años, 11 meses y 27 días. El cumpleaños suma el año. Los días totales son un hueco. Nada se sube."),
    "titleAspectRatio": L("How to find an aspect ratio | cv.cm", "怎么算宽高比 | cv.cm", "怎麼算寬高比 | cv.cm", "アスペクト比の求め方 | cv.cm", "화면 비율 구하는 법 | cv.cm", "Cách tìm tỉ lệ khung | cv.cm", "Cara cari rasio aspek | cv.cm", "Cómo hallar una relación de aspecto | cv.cm"),
    "descAspectRatio": L("1920 by 1080 is 16:9. 1080 by 1920 is 9:16. Decimals round to whole pixels first. The page does not crop the photo. Nothing is uploaded.", "1920 比 1080 是 16:9。1080 比 1920 是 9:16。小数先收成整数像素。这一页不裁照片。不上传。", "1920 比 1080 是 16:9。1080 比 1920 是 9:16。小數先收成整數像素。這一頁不裁照片。不上傳。", "1920 対 1080 は 16:9。1080 対 1920 は 9:16。小数は先に整数ピクセルへ。このページは写真を切らない。アップロードなし。", "1920 대 1080은 16:9. 1080 대 1920은 9:16. 소수는 먼저 정수 픽셀로. 이 페이지는 사진을 자르지 않습니다. 업로드 없음.", "1920 trên 1080 là 16:9. 1080 trên 1920 là 9:16. Số lẻ làm tròn thành pixel nguyên trước. Trang không cắt ảnh. Không tải lên.", "1920 banding 1080 adalah 16:9. 1080 banding 1920 adalah 9:16. Desimal dibulatkan ke piksel utuh dulu. Halaman tidak memotong foto. Tidak diunggah.", "1920 por 1080 es 16:9. 1080 por 1920 es 9:16. Los decimales se redondean primero a píxeles enteros. La página no recorta la foto. Nada se sube."),
}


def inject() -> None:
    if set(LESSONS) != {"percent-off", "encode-url", "calculate-age", "aspect-ratio"}:
        raise SystemExit("ids")
    for loc, path in FILES.items():
        data = json.loads(path.read_text())
        data["faq"].setdefault("learn", {})
        for lesson_id, payload in LESSONS.items():
            data["learn"][lesson_id] = payload["copy"][loc]
            data["faq"]["learn"][lesson_id] = payload["faq"][loc]
        for key, by_loc in META.items():
            data["meta"][key] = by_loc[loc]
        path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n")
        print("patched", path.name)


if __name__ == "__main__":
    inject()
