#!/usr/bin/env python3
"""Inject margin, base, duration, and percentage how-tos."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LOCS = ["en", "zh-CN", "zh-TW", "ja", "ko", "vi", "id", "es"]
FILES = {loc: ROOT / "src/locales" / f"{loc}.json" for loc in LOCS}
COPY_KEYS = [
    "name", "blurb", "title", "lead", "result", "note",
    "s1t", "s1b", "s2t", "s2b", "s3t", "s3b", "s4t", "s4b", "s5t", "s5b", "s6t", "s6b",
    "diagram1", "diagram2",
]
FAQ_KEYS = [f"{side}{i}" for i in range(1, 6) for side in ("q", "a")]


def L(*vals: str) -> dict[str, str]:
    if len(vals) != 8:
        raise ValueError(len(vals), vals[0] if vals else None)
    return dict(zip(LOCS, vals))


def lesson(fields: dict[str, dict[str, str]], faq: dict[str, dict[str, str]]) -> dict:
    missing = [k for k in COPY_KEYS if k not in fields]
    missing += [k for k in FAQ_KEYS if k not in faq]
    if missing:
        raise SystemExit(f"missing keys: {missing}")
    if not fields["title"]["en"].startswith("How to "):
        raise SystemExit(fields["title"]["en"])
    return {
        "copy": {loc: {k: v[loc] for k, v in fields.items()} for loc in LOCS},
        "faq": {loc: {k: v[loc] for k, v in faq.items()} for loc in LOCS},
    }


LESSONS = {
    "profit-margin": lesson(
        {
            "name": L("How to calculate a profit margin", "怎么算利润率", "怎麼算利潤率", "利益率の計算方法", "이익률 계산하는 법", "Cách tính biên lợi nhuận", "Cara hitung margin laba", "Cómo calcular un margen de beneficio"),
            "blurb": L("Divide profit by the selling price for margin, and by the cost for markup. Cost 50 and price 80 is a 37.50% margin and a 60.00% markup.", "利润除以售价是利润率，除以成本是加价率。成本 50、售价 80，利润率 37.50%，加价率 60.00%。", "利潤除以售價是利潤率，除以成本是加價率。成本 50、售價 80，利潤率 37.50%，加價率 60.00%。", "利益÷売価が利益率、利益÷原価がマークアップ。原価 50・売価 80 なら利益率 37.50%、マークアップ 60.00%。", "이익을 판매가로 나누면 이익률, 원가로 나누면 마크업입니다. 원가 50, 판매가 80이면 이익률 37.50%, 마크업 60.00%.", "Lợi nhuận chia giá bán là biên, chia giá vốn là markup. Vốn 50, giá 80: biên 37,50% và markup 60,00%.", "Laba dibagi harga jual adalah margin, dibagi biaya adalah markup. Biaya 50, harga 80: margin 37,50% dan markup 60,00%.", "El beneficio partido por el precio es el margen, y partido por el coste es el markup. Coste 50 y precio 80: margen 37,50% y markup 60,00%."),
            "title": L("How to calculate a profit margin", "怎么算利润率", "怎麼算利潤率", "利益率の計算方法", "이익률 계산하는 법", "Cách tính biên lợi nhuận", "Cara hitung margin laba", "Cómo calcular un margen de beneficio"),
            "lead": L("You have a cost and a selling price. You will read profit, margin, and markup in this tab. Margin divides by the price. Markup divides by the cost. They are not the same percent.", "你有成本和售价。在当前标签页看利润、利润率和加价率。利润率除以售价。加价率除以成本。这两个百分比不是同一个。", "你有成本和售價。在目前分頁看利潤、利潤率和加價率。利潤率除以售價。加價率除以成本。這兩個百分比不是同一個。", "原価と売価がある。このタブで利益・利益率・マークアップを読む。利益率は売価で割る。マークアップは原価で割る。同じパーセントではない。", "원가와 판매가가 있습니다. 이 탭에서 이익, 이익률, 마크업을 읽으세요. 이익률은 판매가로 나눕니다. 마크업은 원가로 나눕니다. 같은 퍼센트가 아닙니다.", "Bạn có giá vốn và giá bán. Đọc lợi nhuận, biên và markup trong tab này. Biên chia cho giá bán. Markup chia cho giá vốn. Không phải cùng một phần trăm.", "Anda punya biaya dan harga jual. Baca laba, margin, dan markup di tab ini. Margin membagi harga jual. Markup membagi biaya. Bukan persen yang sama.", "Tiene un coste y un precio de venta. Lea beneficio, margen y markup aquí. El margen divide por el precio. El markup divide por el coste. No son el mismo porcentaje."),
            "result": L("Profit, a margin percent of the selling price, and a markup percent of the cost, for amounts that are zero or more.", "利润、占售价的利润率、占成本的加价率。成本和售价都要大于或等于 0。", "利潤、占售價的利潤率、占成本的加價率。成本和售價都要大於或等於 0。", "利益、売価に対する利益率、原価に対するマークアップ。金額は 0 以上。", "이익, 판매가 대비 이익률, 원가 대비 마크업. 금액은 0 이상.", "Lợi nhuận, biên trên giá bán, và markup trên giá vốn. Các số từ 0 trở lên.", "Laba, persen margin dari harga jual, dan persen markup dari biaya. Jumlahnya nol atau lebih.", "Beneficio, un margen sobre el precio de venta y un markup sobre el coste, con importes de cero o más."),
            "note": L("Open profit margin when you know both amounts. A zero price has no margin percent. A zero cost has no markup percent. Nothing is uploaded.", "两个金额都清楚再打开利润率。售价为 0 就没有利润率。成本为 0 就没有加价率。不上传。", "兩個金額都清楚再開利潤率。售價為 0 就沒有利潤率。成本為 0 就沒有加價率。不上傳。", "両方の金額が分かってから開く。売価 0 には利益率がない。原価 0 にはマークアップがない。アップロードなし。", "두 금액을 알 때 이익률을 여세요. 판매가 0이면 이익률이 없습니다. 원가 0이면 마크업이 없습니다. 업로드 없음.", "Biết cả hai số thì mở biên lợi nhuận. Giá bán 0 thì không có phần trăm biên. Giá vốn 0 thì không có phần trăm markup. Không tải lên.", "Tahu kedua jumlah, baru buka margin laba. Harga 0 tidak punya persen margin. Biaya 0 tidak punya persen markup. Tidak diunggah.", "Abra el margen cuando sepa ambos importes. Un precio 0 no tiene porcentaje de margen. Un coste 0 no tiene porcentaje de markup. Nada se sube."),
            "s1t": L("Name cost and selling price", "先分清成本和售价", "先分清成本和售價", "原価と売価を分ける", "원가와 판매가를 나누기", "Tách giá vốn và giá bán", "Pisahkan biaya dan harga jual", "Distinga coste y precio de venta"),
            "s1b": L("Cost is what you paid. Price is what the buyer pays. Profit is price minus cost. A 30% margin is not a 30% markup.", "成本是你付出的。售价是买方付的。利润是售价减成本。30% 的利润率不是 30% 的加价率。", "成本是你付出的。售價是買方付的。利潤是售價減成本。30% 的利潤率不是 30% 的加價率。", "原価は払った額。売価は買い手が払う額。利益は売価−原価。利益率 30% はマークアップ 30% ではない。", "원가는 당신이 낸 돈. 판매가는 구매자가 내는 돈. 이익은 판매가 빼기 원가. 이익률 30%는 마크업 30%가 아닙니다.", "Giá vốn là số bạn trả. Giá bán là số người mua trả. Lợi nhuận là giá bán trừ giá vốn. Biên 30% không phải markup 30%.", "Biaya adalah yang Anda bayar. Harga adalah yang pembeli bayar. Laba adalah harga kurang biaya. Margin 30% bukan markup 30%.", "El coste es lo que usted pagó. El precio es lo que paga el comprador. El beneficio es precio menos coste. Un margen del 30% no es un markup del 30%."),
            "s2t": L("Open profit margin on cv.cm", "打开 cv.cm 的利润率", "打開 cv.cm 的利潤率", "cv.cmの利益率を開く", "cv.cm 이익률을 열기", "Mở biên lợi nhuận trên cv.cm", "Buka margin laba di cv.cm", "Abra el margen en cv.cm"),
            "s2b": L("The math stays in this tab.", "计算留在当前标签页。", "計算留在目前分頁。", "計算はこのタブ。", "계산은 이 탭에서.", "Tính trong tab này.", "Hitungan di tab ini.", "La cuenta queda en esta pestaña."),
            "s3t": L("Enter cost and selling price", "填成本和售价", "填成本和售價", "原価と売価を入れる", "원가와 판매가 넣기", "Nhập giá vốn và giá bán", "Isi biaya dan harga jual", "Escriba coste y precio de venta"),
            "s3b": L("Both amounts must be zero or more. Both zero fails. Cost 50 and price 80 is the check: profit 30.00.", "两个数都要大于或等于 0。两个都是 0 会失败。成本 50、售价 80 可以核对：利润 30.00。", "兩個數都要大於或等於 0。兩個都是 0 會失敗。成本 50、售價 80 可以核對：利潤 30.00。", "両方 0 以上。両方 0 は失敗。原価 50・売価 80 なら利益 30.00。", "둘 다 0 이상이어야 합니다. 둘 다 0이면 실패합니다. 원가 50, 판매가 80이면 이익 30.00.", "Cả hai số từ 0 trở lên. Cả hai bằng 0 thì thất bại. Vốn 50, giá 80: lợi nhuận 30,00.", "Keduanya nol atau lebih. Keduanya nol gagal. Biaya 50 dan harga 80: laba 30,00.", "Ambos importes deben ser cero o más. Los dos en cero fallan. Coste 50 y precio 80: beneficio 30,00."),
            "s4t": L("Read margin and markup as different percents", "把利润率和加价率当成两个百分比", "把利潤率和加價率當成兩個百分比", "利益率とマークアップは別のパーセント", "이익률과 마크업은 다른 퍼센트", "Đọc biên và markup như hai phần trăm khác nhau", "Baca margin dan markup sebagai persen yang berbeda", "Lea margen y markup como porcentajes distintos"),
            "s4b": L("Margin is profit divided by the price: 30 / 80 is 37.50%. Markup is profit divided by the cost: 30 / 50 is 60.00%. Copy the line the form asked for.", "利润率是利润除以售价：30 / 80 是 37.50%。加价率是利润除以成本：30 / 50 是 60.00%。复制表单要的那一行。", "利潤率是利潤除以售價：30 / 80 是 37.50%。加價率是利潤除以成本：30 / 50 是 60.00%。複製表單要的那一行。", "利益率は利益÷売価。30/80 は 37.50%。マークアップは利益÷原価。30/50 は 60.00%。書類が求めた行をコピー。", "이익률은 이익 나누기 판매가: 30/80은 37.50%. 마크업은 이익 나누기 원가: 30/50은 60.00%. 서류가 요구한 줄을 복사하세요.", "Biên là lợi nhuận chia giá bán: 30/80 là 37,50%. Markup là lợi nhuận chia giá vốn: 30/50 là 60,00%. Copy dòng biểu mẫu hỏi.", "Margin adalah laba dibagi harga: 30/80 adalah 37,50%. Markup adalah laba dibagi biaya: 30/50 adalah 60,00%. Salin baris yang diminta formulir.", "El margen es beneficio dividido por el precio: 30/80 es 37,50%. El markup es beneficio dividido por el coste: 30/50 es 60,00%. Copie la línea que pide el formulario."),
            "s5t": L("A zero price or a zero cost drops one percent", "售价或成本为 0，就缺一个百分比", "售價或成本為 0，就缺一個百分比", "売価か原価が 0 なら片方のパーセントが無い", "판매가나 원가가 0이면 퍼센트 하나가 없음", "Giá bán hoặc giá vốn bằng 0 thì thiếu một phần trăm", "Harga atau biaya nol menghilangkan satu persen", "Un precio o un coste en cero quita un porcentaje"),
            "s5b": L("A zero price has profit and markup, and the margin line is a dash. A zero cost has profit and margin, and the markup line is a dash.", "售价为 0 时有利润和加价率，利润率那一行是横线。成本为 0 时有利润和利润率，加价率那一行是横线。", "售價為 0 時有利潤和加價率，利潤率那一行是橫線。成本為 0 時有利潤和利潤率，加價率那一行是橫線。", "売価 0 なら利益とマークアップがあり、利益率は横線。原価 0 なら利益と利益率があり、マークアップは横線。", "판매가 0이면 이익과 마크업이 있고 이익률 줄은 대시입니다. 원가 0이면 이익과 이익률이 있고 마크업 줄은 대시입니다.", "Giá bán 0 thì có lợi nhuận và markup, dòng biên là gạch. Giá vốn 0 thì có lợi nhuận và biên, dòng markup là gạch.", "Harga 0 punya laba dan markup, baris margin adalah garis. Biaya 0 punya laba dan margin, baris markup adalah garis.", "Un precio 0 tiene beneficio y markup, y la línea de margen es una raya. Un coste 0 tiene beneficio y margen, y la línea de markup es una raya."),
            "s6t": L("A price below cost is a loss", "售价低于成本就是亏损", "售價低於成本就是虧損", "売価が原価より低いと損失", "판매가가 원가보다 낮으면 손실", "Giá bán thấp hơn giá vốn là lỗ", "Harga di bawah biaya adalah rugi", "Un precio por debajo del coste es una pérdida"),
            "s6b": L("Profit, margin, and markup are then negative. Do not send a negative margin to a form that asked for a discount percent. A discount is a cut from a list price, which is a different job.", "这时利润、利润率和加价率都是负的。表单要的是折扣百分比时，不要把负的利润率填进去。折扣是从标价上减，那是另一件事。", "這時利潤、利潤率和加價率都是負的。表單要的是折扣百分比時，不要把負的利潤率填進去。折扣是從標價上減，那是另一件事。", "このとき利益・利益率・マークアップは負。割引率を求める書類に負の利益率を入れない。割引は定価からの値引きで、別の仕事。", "이때 이익, 이익률, 마크업은 음수입니다. 할인율을 묻는 서류에 음의 이익률을 넣지 마세요. 할인은 정가에서 깎는 것이고 다른 일입니다.", "Lúc đó lợi nhuận, biên và markup đều âm. Đừng điền biên âm vào biểu mẫu hỏi phần trăm giảm giá. Giảm giá là cắt từ giá niêm yết, việc khác.", "Saat itu laba, margin, dan markup negatif. Jangan kirim margin negatif ke formulir yang minta persen diskon. Diskon memotong harga daftar, pekerjaan lain.", "Entonces beneficio, margen y markup son negativos. No envíe un margen negativo a un formulario que pidió un porcentaje de descuento. Un descuento es un recorte del precio de lista, y es otro trabajo."),
            "diagram1": L("Cost 50, price 80. Profit 30.00. Margin 37.50%. Markup 60.00%.", "成本 50，售价 80。利润 30.00。利润率 37.50%。加价率 60.00%。", "成本 50，售價 80。利潤 30.00。利潤率 37.50%。加價率 60.00%。", "原価 50、売価 80。利益 30.00。利益率 37.50%。マークアップ 60.00%。", "원가 50, 판매가 80. 이익 30.00. 이익률 37.50%. 마크업 60.00%.", "Vốn 50, giá 80. Lợi nhuận 30,00. Biên 37,50%. Markup 60,00%.", "Biaya 50, harga 80. Laba 30,00. Margin 37,50%. Markup 60,00%.", "Coste 50, precio 80. Beneficio 30,00. Margen 37,50%. Markup 60,00%."),
            "diagram2": L("Margin divides by the price. Markup divides by the cost.", "利润率除以售价。加价率除以成本。", "利潤率除以售價。加價率除以成本。", "利益率は売価で割る。マークアップは原価で割る。", "이익률은 판매가로 나눔. 마크업은 원가로 나눔.", "Biên chia giá bán. Markup chia giá vốn.", "Margin membagi harga. Markup membagi biaya.", "El margen divide por el precio. El markup divide por el coste."),
        },
        {
            "q1": L("Can I calculate a profit margin free online?", "可以免费在线算利润率吗？", "可以免費線上算利潤率嗎？", "利益率を無料で計算できる？", "이익률을 무료로 계산할 수 있나요?", "Tính biên lợi nhuận miễn phí online được không?", "Bisa hitung margin laba gratis online?", "¿Puedo calcular un margen de beneficio gratis en línea?"),
            "a1": L("Yes. cv.cm shows profit, margin, and markup in this tab. Nothing is uploaded.", "可以。cv.cm 在当前标签页显示利润、利润率和加价率。不上传。", "可以。cv.cm 在目前分頁顯示利潤、利潤率和加價率。不上傳。", "できる。このタブで利益・利益率・マークアップを出す。アップロードなし。", "됩니다. 이 탭에서 이익, 이익률, 마크업을 보여 줍니다. 업로드 없음.", "Được. Hiện lợi nhuận, biên và markup trong tab này. Không tải lên.", "Ya. Menampilkan laba, margin, dan markup di tab ini. Tidak diunggah.", "Sí. Muestra beneficio, margen y markup en esta pestaña. Nada se sube."),
            "q2": L("What is the difference between margin and markup?", "利润率和加价率有什么差别？", "利潤率和加價率有什麼差別？", "利益率とマークアップの違いは？", "이익률과 마크업의 차이는?", "Biên và markup khác gì?", "Apa beda margin dan markup?", "¿Qué diferencia hay entre margen y markup?"),
            "a2": L("Margin is profit divided by the selling price. Markup is profit divided by the cost. Cost 50 and price 80 is 37.50% margin and 60.00% markup.", "利润率是利润除以售价。加价率是利润除以成本。成本 50、售价 80 是利润率 37.50%、加价率 60.00%。", "利潤率是利潤除以售價。加價率是利潤除以成本。成本 50、售價 80 是利潤率 37.50%、加價率 60.00%。", "利益率は利益÷売価。マークアップは利益÷原価。原価 50・売価 80 は利益率 37.50%、マークアップ 60.00%。", "이익률은 이익 나누기 판매가. 마크업은 이익 나누기 원가. 원가 50, 판매가 80이면 이익률 37.50%, 마크업 60.00%.", "Biên là lợi nhuận chia giá bán. Markup là lợi nhuận chia giá vốn. Vốn 50, giá 80: biên 37,50% và markup 60,00%.", "Margin adalah laba dibagi harga jual. Markup adalah laba dibagi biaya. Biaya 50, harga 80: margin 37,50% dan markup 60,00%.", "El margen es beneficio dividido por el precio. El markup es beneficio dividido por el coste. Coste 50 y precio 80: margen 37,50% y markup 60,00%."),
            "q3": L("What if the price is below the cost?", "售价低于成本呢？", "售價低於成本呢？", "売価が原価より低いときは？", "판매가가 원가보다 낮으면?", "Giá bán thấp hơn giá vốn thì sao?", "Jika harga di bawah biaya?", "¿Y si el precio está por debajo del coste?"),
            "a3": L("Profit, margin, and markup are negative.", "利润、利润率和加价率都是负的。", "利潤、利潤率和加價率都是負的。", "利益・利益率・マークアップは負。", "이익, 이익률, 마크업이 음수입니다.", "Lợi nhuận, biên và markup đều âm.", "Laba, margin, dan markup negatif.", "Beneficio, margen y markup son negativos."),
            "q4": L("What if the price or the cost is zero?", "售价或成本是 0 呢？", "售價或成本是 0 呢？", "売価か原価が 0 なら？", "판매가나 원가가 0이면?", "Giá bán hoặc giá vốn bằng 0 thì sao?", "Jika harga atau biaya nol?", "¿Y si el precio o el coste es cero?"),
            "a4": L("A zero price has no margin percent. A zero cost has no markup percent. Both zero fails.", "售价为 0 就没有利润率。成本为 0 就没有加价率。两个都是 0 会失败。", "售價為 0 就沒有利潤率。成本為 0 就沒有加價率。兩個都是 0 會失敗。", "売価 0 には利益率がない。原価 0 にはマークアップがない。両方 0 は失敗。", "판매가 0이면 이익률이 없습니다. 원가 0이면 마크업이 없습니다. 둘 다 0이면 실패합니다.", "Giá bán 0 thì không có biên. Giá vốn 0 thì không có markup. Cả hai bằng 0 thì thất bại.", "Harga 0 tidak punya margin. Biaya 0 tidak punya markup. Keduanya nol gagal.", "Un precio 0 no tiene margen. Un coste 0 no tiene markup. Los dos en cero fallan."),
            "q5": L("Is this uploaded?", "会上传吗？", "會上傳嗎？", "アップロードされる？", "업로드되나요?", "Có bị tải lên không?", "Apakah diunggah?", "¿Se sube?"),
            "a5": L("No. Closing the tab discards it.", "不会。关掉标签页就没了。", "不會。關掉分頁就沒了。", "しない。タブを閉じると消える。", "아니요. 탭을 닫으면 사라집니다.", "Không. Đóng tab là mất.", "Tidak. Tutup tab, hilang.", "No. Al cerrar la pestaña se pierde."),
        },
    ),
    "convert-base": lesson(
        {
            "name": L("How to convert a number between bases", "怎么在进制之间换算", "怎麼在進制之間換算", "進数を変換する方法", "진법 사이 변환하는 법", "Cách đổi số giữa các cơ số", "Cara ubah bilangan antar basis", "Cómo convertir un número entre bases"),
            "blurb": L("Convert one whole number between bases 2 and 36. 255 in base 10 is FF in base 16. No 0x prefix and no fraction.", "把一个整数在 2 到 36 进制之间换算。十进制 255 是十六进制 FF。不要 0x 前缀，也不要小数。", "把一個整數在 2 到 36 進制之間換算。十進制 255 是十六進制 FF。不要 0x 前綴，也不要小數。", "一つの整数を 2 から 36 進の間で変換。10進の 255 は 16進の FF。0x も小数も付けない。", "정수 하나를 2진부터 36진 사이로 바꿉니다. 10진 255는 16진 FF. 0x 접두어와 소수는 안 됩니다.", "Đổi một số nguyên giữa cơ số 2 và 36. 255 ở cơ số 10 là FF ở cơ số 16. Không tiền tố 0x, không phần thập phân.", "Ubah satu bilangan bulat antara basis 2 dan 36. 255 di basis 10 adalah FF di basis 16. Tanpa awalan 0x dan tanpa pecahan.", "Convierta un entero entre las bases 2 y 36. 255 en base 10 es FF en base 16. Sin prefijo 0x y sin parte fraccionaria."),
            "title": L("How to convert a number between bases", "怎么在进制之间换算", "怎麼在進制之間換算", "進数を変換する方法", "진법 사이 변환하는 법", "Cách đổi số giữa các cơ số", "Cara ubah bilangan antar basis", "Cómo convertir un número entre bases"),
            "lead": L("You have one integer in one base and you need another base. You will set both bases in this tab. This page does not turn letters into groups of 8 bits, and it does not accept a 0x prefix.", "你有一个进制里的整数，要换成另一个进制。在当前标签页设定两个进制。这一页不会把字母变成 8 位一组，也不接受 0x 前缀。", "你有一個進制裡的整數，要換成另一個進制。在目前分頁設定兩個進制。這一頁不會把字母變成 8 位一組，也不接受 0x 前綴。", "ある進数の整数を別の進数にしたい。このタブで両方の基数を決める。文字を 8 ビットの組にはしない。0x も受け付けない。", "한 진법의 정수를 다른 진법으로 바꾸고 싶습니다. 이 탭에서 두 진법을 정하세요. 이 페이지는 글자를 8비트 묶음으로 만들지 않고 0x 접두어도 받지 않습니다.", "Bạn có một số nguyên ở một cơ số và cần cơ số khác. Đặt cả hai cơ số trong tab này. Trang này không biến chữ thành nhóm 8 bit, và không nhận tiền tố 0x.", "Anda punya satu bilangan bulat di satu basis dan butuh basis lain. Atur kedua basis di tab ini. Halaman ini tidak mengubah huruf menjadi kelompok 8 bit, dan tidak menerima awalan 0x.", "Tiene un entero en una base y necesita otra. Fije ambas bases aquí. Esta página no convierte letras en grupos de 8 bits, y no acepta un prefijo 0x."),
            "result": L("The same integer written in the destination base, with letters in uppercase.", "同一个整数写成目标进制，字母是大写。", "同一個整數寫成目標進制，字母是大寫。", "同じ整数を変換先の進数で書いたもの。英字は大文字。", "같은 정수를 대상 진법으로 쓴 것. 글자는 대문자.", "Cùng số nguyên viết ở cơ số đích, chữ cái viết hoa.", "Bilangan bulat yang sama ditulis di basis tujuan, huruf besar.", "El mismo entero escrito en la base de destino, con letras en mayúsculas."),
            "note": L("Open the base converter when the integer and both bases are known. Bases are 2 through 36. Nothing is uploaded.", "整数和两个进制都清楚再打开进制转换。进制是 2 到 36。不上传。", "整數和兩個進制都清楚再開進制轉換。進制是 2 到 36。不上傳。", "整数と両方の基数が分かってから開く。基数は 2 から 36。アップロードなし。", "정수와 두 진법을 알 때 진법 변환을 여세요. 진법은 2부터 36. 업로드 없음.", "Biết số nguyên và cả hai cơ số thì mở bộ đổi cơ số. Cơ số từ 2 đến 36. Không tải lên.", "Tahu bilangan dan kedua basis, baru buka pengubah basis. Basis 2 sampai 36. Tidak diunggah.", "Abra el conversor cuando sepa el entero y ambas bases. Las bases van de 2 a 36. Nada se sube."),
            "s1t": L("Write the integer without a prefix", "先写下不带前缀的整数", "先寫下不帶前綴的整數", "接頭辞なしの整数を書く", "접두어 없는 정수를 쓰기", "Viết số nguyên không tiền tố", "Tulis bilangan tanpa awalan", "Escriba el entero sin prefijo"),
            "s1b": L("255 is a decimal integer. FF is hex. 11111111 is binary. Do not type 0x, 0b, or a dot. A fraction is a different job.", "255 是十进制整数。FF 是十六进制。11111111 是二进制。不要写 0x、0b 或小数点。小数是另一件事。", "255 是十進制整數。FF 是十六進制。11111111 是二進制。不要寫 0x、0b 或小數點。小數是另一件事。", "255 は 10進。FF は 16進。11111111 は 2進。0x、0b、小数点は書かない。小数は別の仕事。", "255는 10진 정수. FF는 16진. 11111111은 2진. 0x, 0b, 소수점은 쓰지 마세요. 소수는 다른 일입니다.", "255 là số nguyên thập phân. FF là hex. 11111111 là nhị phân. Đừng gõ 0x, 0b hoặc dấu chấm. Phần thập phân là việc khác.", "255 adalah bilangan desimal. FF adalah heksa. 11111111 adalah biner. Jangan ketik 0x, 0b, atau titik. Pecahan adalah kerja lain.", "255 es un entero decimal. FF es hexadecimal. 11111111 es binario. No escriba 0x, 0b ni un punto. Una fracción es otro trabajo."),
            "s2t": L("Open the base converter on cv.cm", "打开 cv.cm 的进制转换", "打開 cv.cm 的進制轉換", "cv.cmの進数変換を開く", "cv.cm 진법 변환을 열기", "Mở đổi cơ số trên cv.cm", "Buka pengubah basis di cv.cm", "Abra el conversor de bases en cv.cm"),
            "s2b": L("Conversion stays in this tab.", "换算留在当前标签页。", "換算留在目前分頁。", "変換はこのタブ。", "변환은 이 탭에서.", "Đổi trong tab này.", "Konversi di tab ini.", "La conversión queda en esta pestaña."),
            "s3t": L("Set the source base and the destination base", "设定来源进制和目标进制", "設定來源進制和目標進制", "変換元と変換先の基数を入れる", "출발 진법과 도착 진법 정하기", "Đặt cơ số nguồn và cơ số đích", "Atur basis asal dan basis tujuan", "Fije la base de origen y la de destino"),
            "s3b": L("Bases run from 2 to 36. Decimal to hex is 10 and 16. A digit must exist in the source base, so 2 is not a binary digit.", "进制从 2 到 36。十进制到十六进制是 10 和 16。数字必须在来源进制里存在，所以 2 不是二进制数字。", "進制從 2 到 36。十進制到十六進制是 10 和 16。數字必須在來源進制裡存在，所以 2 不是二進制數字。", "基数は 2 から 36。10進から 16進は 10 と 16。桁は変換元の基数に存在すること。2 は 2進の桁ではない。", "진법은 2부터 36. 10진에서 16진은 10과 16. 숫자는 출발 진법에 있어야 합니다. 2는 2진 숫자가 아닙니다.", "Cơ số từ 2 đến 36. Thập phân sang hex là 10 và 16. Chữ số phải có trong cơ số nguồn, nên 2 không phải chữ số nhị phân.", "Basis dari 2 sampai 36. Desimal ke heksa adalah 10 dan 16. Digit harus ada di basis asal, jadi 2 bukan digit biner.", "Las bases van de 2 a 36. De decimal a hex son 10 y 16. Un dígito tiene que existir en la base de origen, así que 2 no es un dígito binario."),
            "s4t": L("Paste the integer", "贴上整数", "貼上整數", "整数を貼る", "정수 붙이기", "Dán số nguyên", "Tempel bilangannya", "Pegue el entero"),
            "s4b": L("A leading plus or minus is allowed. Letters may be upper or lower on input. The body can be at most 64 digits.", "开头可以有加号或减号。输入的字母大小写都可以。数字本体最多 64 位。", "開頭可以有加號或減號。輸入的字母大小寫都可以。數字本體最多 64 位。", "先頭の + か - は可。入力の英字は大文字でも小文字でもよい。本体は最大 64 桁。", "앞에 더하기나 빼기가 있어도 됩니다. 입력 글자는 대소문자 모두 됩니다. 본문은 최대 64자리.", "Dấu cộng hoặc trừ ở đầu được phép. Chữ hoa hay thường đều được khi nhập. Phần số tối đa 64 chữ số.", "Tanda plus atau minus di depan boleh. Huruf besar atau kecil saat mengetik. Badan angka paling banyak 64 digit.", "Se permite un más o un menos al principio. Las letras pueden ir en mayúsculas o minúsculas al escribir. El cuerpo puede tener como máximo 64 dígitos."),
            "s5t": L("Read the uppercase result", "看大写的结果", "看大寫的結果", "大文字の結果を読む", "대문자 결과 읽기", "Đọc kết quả viết hoa", "Baca hasil huruf besar", "Lea el resultado en mayúsculas"),
            "s5b": L("255 in base 10 is FF in base 16, and 11111111 in base 2. Zero stays 0. Copy is that integer, not a 0x prefix.", "十进制 255 是十六进制 FF，也是二进制 11111111。零仍是 0。复制的是这个整数，不是 0x 前缀。", "十進制 255 是十六進制 FF，也是二進制 11111111。零仍是 0。複製的是這個整數，不是 0x 前綴。", "10進の 255 は 16進の FF、2進の 11111111。ゼロは 0 のまま。コピーはその整数であり 0x ではない。", "10진 255는 16진 FF이고 2진 11111111입니다. 0은 0으로 남습니다. 복사는 그 정수이지 0x 접두어가 아닙니다.", "255 ở cơ số 10 là FF ở cơ số 16, và 11111111 ở cơ số 2. Số 0 vẫn là 0. Bản copy là số nguyên đó, không phải tiền tố 0x.", "255 di basis 10 adalah FF di basis 16, dan 11111111 di basis 2. Nol tetap 0. Salinan adalah bilangan itu, bukan awalan 0x.", "255 en base 10 es FF en base 16, y 11111111 en base 2. El cero sigue siendo 0. Lo copiado es ese entero, no un prefijo 0x."),
            "s6t": L("Keep this separate from text-to-binary", "这和文字转二进制是两件事", "這和文字轉二進制是兩件事", "文字から二進とは別", "글자를 이진으로 바꾸는 일과 구분하기", "Việc này khác chuyển chữ sang nhị phân", "Ini terpisah dari teks ke biner", "Sepárelo de texto a binario"),
            "s6b": L("A word such as hi is not an integer in base 16 unless every letter fits that base. The binary tool turns letters into 8-bit groups. This page converts one integer.", "像 hi 这样的词，除非每个字母都属于那个进制，否则不是十六进制整数。二进制工具把字母变成 8 位一组。这一页只换算一个整数。", "像 hi 這樣的詞，除非每個字母都屬於那個進制，否則不是十六進制整數。二進制工具把字母變成 8 位一組。這一頁只換算一個整數。", "hi のような語は、すべての文字がその基数に入るとき以外、16進の整数ではない。バイナリツールは文字を 8 ビットの組にする。このページは整数を一つ変換する。", "hi 같은 단어는 모든 글자가 그 진법에 들어갈 때만 16진 정수입니다. 이진 도구는 글자를 8비트 묶음으로 바꿉니다. 이 페이지는 정수 하나를 변환합니다.", "Một từ như hi không phải số nguyên cơ số 16 trừ khi mọi chữ cái thuộc cơ số đó. Công cụ nhị phân biến chữ thành nhóm 8 bit. Trang này đổi một số nguyên.", "Kata seperti hi bukan bilangan basis 16 kecuali setiap huruf muat di basis itu. Alat biner mengubah huruf menjadi kelompok 8 bit. Halaman ini mengubah satu bilangan.", "Una palabra como hi no es un entero en base 16 salvo que cada letra quepa en esa base. La herramienta binaria convierte letras en grupos de 8 bits. Esta página convierte un entero."),
            "diagram1": L("Bases 2–36. 255 decimal is FF hex. No 0x and no dot.", "进制 2–36。十进制 255 是十六进制 FF。不要 0x，也不要小数点。", "進制 2–36。十進制 255 是十六進制 FF。不要 0x，也不要小數點。", "基数 2–36。10進 255 は 16進 FF。0x も小数点も無し。", "진법 2–36. 10진 255는 16진 FF. 0x도 소수점도 없음.", "Cơ số 2–36. 255 thập phân là FF hex. Không 0x, không dấu chấm.", "Basis 2–36. 255 desimal adalah FF heksa. Tanpa 0x dan tanpa titik.", "Bases 2–36. 255 decimal es FF en hex. Sin 0x y sin punto."),
            "diagram2": L("Output letters are uppercase. This page converts one integer.", "结果字母是大写。这一页只换算一个整数。", "結果字母是大寫。這一頁只換算一個整數。", "出力の英字は大文字。このページは整数を一つ変換する。", "결과 글자는 대문자. 이 페이지는 정수 하나를 변환합니다.", "Chữ kết quả viết hoa. Trang này đổi một số nguyên.", "Huruf hasil adalah kapital. Halaman ini mengubah satu bilangan.", "Las letras de salida van en mayúsculas. Esta página convierte un entero."),
        },
        {
            "q1": L("Can I convert between bases free online?", "可以免费在线换算进制吗？", "可以免費線上換算進制嗎？", "進数を無料で変換できる？", "진법을 무료로 변환할 수 있나요?", "Đổi cơ số miễn phí online được không?", "Bisa ubah basis gratis online?", "¿Puedo convertir entre bases gratis en línea?"),
            "a1": L("Yes. cv.cm converts one integer between bases 2 and 36 in this tab. Nothing is uploaded.", "可以。cv.cm 在当前标签页把一个整数在 2 到 36 进制之间换算。不上传。", "可以。cv.cm 在目前分頁把一個整數在 2 到 36 進制之間換算。不上傳。", "できる。このタブで一つの整数を 2 から 36 進の間で変換。アップロードなし。", "됩니다. 이 탭에서 정수 하나를 2진부터 36진 사이로 바꿉니다. 업로드 없음.", "Được. Đổi một số nguyên giữa cơ số 2 và 36 trong tab này. Không tải lên.", "Ya. Mengubah satu bilangan antara basis 2 dan 36 di tab ini. Tidak diunggah.", "Sí. Convierte un entero entre las bases 2 y 36 en esta pestaña. Nada se sube."),
            "q2": L("What is 255 in hex?", "255 的十六进制是什么？", "255 的十六進制是什麼？", "255 の 16進は？", "255의 16진은?", "255 ở hex là gì?", "255 dalam heksa adalah apa?", "¿Qué es 255 en hexadecimal?"),
            "a2": L("FF. From base 10 to base 16. The letters are uppercase.", "FF。从 10 进制到 16 进制。字母是大写。", "FF。從 10 進制到 16 進制。字母是大寫。", "FF。10進から 16進。英字は大文字。", "FF. 10진에서 16진. 글자는 대문자.", "FF. Từ cơ số 10 sang cơ số 16. Chữ viết hoa.", "FF. Dari basis 10 ke basis 16. Hurufnya besar.", "FF. De base 10 a base 16. Las letras van en mayúsculas."),
            "q3": L("Can I type 0x or a decimal point?", "能写 0x 或小数点吗？", "能寫 0x 或小數點嗎？", "0x や小数点は書ける？", "0x나 소수점을 쓸 수 있나요?", "Gõ 0x hoặc dấu chấm được không?", "Boleh ketik 0x atau titik desimal?", "¿Puedo escribir 0x o un punto decimal?"),
            "a3": L("No. Type the digits only. A fraction is not an integer in a base.", "不能。只写数字。小数不是某个进制里的整数。", "不能。只寫數字。小數不是某個進制裡的整數。", "書けない。桁だけ。小数はある基数の整数ではない。", "안 됩니다. 숫자만 쓰세요. 소수는 어떤 진법의 정수가 아닙니다.", "Không. Chỉ gõ chữ số. Phần thập phân không phải số nguyên của một cơ số.", "Tidak. Ketik digit saja. Pecahan bukan bilangan bulat di suatu basis.", "No. Escriba solo los dígitos. Una fracción no es un entero en una base."),
            "q4": L("Is this the tool that turns text into binary?", "这是把文字变成二进制的工具吗？", "這是把文字變成二進制的工具嗎？", "文字を二進にするツール？", "글자를 이진으로 바꾸는 도구인가요?", "Đây có phải công cụ biến chữ thành nhị phân?", "Ini alat yang mengubah teks menjadi biner?", "¿Es la herramienta que convierte texto en binario?"),
            "a4": L("No. This converts one integer. The binary tool turns letters into 8-bit groups.", "不是。这一页换算一个整数。二进制工具把字母变成 8 位一组。", "不是。這一頁換算一個整數。二進制工具把字母變成 8 位一組。", "違う。これは整数を一つ変換する。バイナリツールは文字を 8 ビットの組にする。", "아니요. 여기는 정수 하나를 변환합니다. 이진 도구는 글자를 8비트 묶음으로 바꿉니다.", "Không. Trang này đổi một số nguyên. Công cụ nhị phân biến chữ thành nhóm 8 bit.", "Tidak. Ini mengubah satu bilangan. Alat biner mengubah huruf menjadi kelompok 8 bit.", "No. Esto convierte un entero. La herramienta binaria convierte letras en grupos de 8 bits."),
            "q5": L("Is the number uploaded?", "这个数会上传吗？", "這個數會上傳嗎？", "アップロードされる？", "업로드되나요?", "Số có bị tải lên không?", "Apakah angkanya diunggah?", "¿Se sube el número?"),
            "a5": L("No. Closing the tab discards it.", "不会。关掉标签页就没了。", "不會。關掉分頁就沒了。", "しない。タブを閉じると消える。", "아니요. 탭을 닫으면 사라집니다.", "Không. Đóng tab là mất.", "Tidak. Tutup tab, hilang.", "No. Al cerrar la pestaña se pierde."),
        },
    ),
    "add-duration": lesson(
        {
            "name": L("How to add hours and minutes", "怎么把小时和分钟相加", "怎麼把小時和分鐘相加", "時間と分を足す方法", "시간과 분 더하는 법", "Cách cộng giờ và phút", "Cara jumlahkan jam dan menit", "Cómo sumar horas y minutos"),
            "blurb": L("Add or subtract two lengths written as hours:minutes:seconds. Minutes and seconds must be 0–59. 0:90:00 is not a valid length.", "把两段写成「时:分:秒」的时长相加或相减。分和秒必须是 0–59。0:90:00 不是合法时长。", "把兩段寫成「時:分:秒」的時長相加或相減。分和秒必須是 0–59。0:90:00 不是合法時長。", "時:分:秒で書いた二つの長さを足すか引く。分と秒は 0–59。0:90:00 は長さとして無効。", "시:분:초로 쓴 두 길이를 더하거나 뺍니다. 분과 초는 0–59. 0:90:00은 올바른 길이가 아닙니다.", "Cộng hoặc trừ hai khoảng viết dạng giờ:phút:giây. Phút và giây phải từ 0–59. 0:90:00 không phải khoảng hợp lệ.", "Tambah atau kurangi dua durasi ditulis jam:menit:detik. Menit dan detik harus 0–59. 0:90:00 bukan durasi yang sah.", "Sume o reste dos duraciones escritas como horas:minutos:segundos. Minutos y segundos deben ser 0–59. 0:90:00 no es una duración válida."),
            "title": L("How to add hours and minutes", "怎么把小时和分钟相加", "怎麼把小時和分鐘相加", "時間と分を足す方法", "시간과 분 더하는 법", "Cách cộng giờ và phút", "Cara jumlahkan jam dan menit", "Cómo sumar horas y minutos"),
            "lead": L("You have two lengths of time, not two clock times. You will add them, or subtract the second from the first, in this tab. 1:30:00 plus 0:45:00 is 2:15:00. This is not a time zone.", "你有两段时长，不是两个钟点。在当前标签页把它们相加，或用第一段减去第二段。1:30:00 加 0:45:00 是 2:15:00。这不是时区。", "你有兩段時長，不是兩個鐘點。在目前分頁把它們相加，或用第一段減去第二段。1:30:00 加 0:45:00 是 2:15:00。這不是時區。", "二つの長さであり、二つの時刻ではない。このタブで足すか、一つ目から二つ目を引く。1:30:00 足す 0:45:00 は 2:15:00。タイムゾーンではない。", "시계 시각 둘이 아니라 시간의 길이 둘입니다. 이 탭에서 더하거나, 첫 길이에서 둘째를 빼세요. 1:30:00 더하기 0:45:00은 2:15:00. 시간대가 아닙니다.", "Bạn có hai khoảng thời gian, không phải hai giờ đồng hồ. Cộng chúng, hoặc lấy khoảng thứ nhất trừ khoảng thứ hai, trong tab này. 1:30:00 cộng 0:45:00 là 2:15:00. Đây không phải múi giờ.", "Anda punya dua durasi, bukan dua jam dinding. Jumlahkan, atau kurangi yang kedua dari yang pertama, di tab ini. 1:30:00 ditambah 0:45:00 adalah 2:15:00. Ini bukan zona waktu.", "Tiene dos duraciones, no dos horas de reloj. Súmelas, o reste la segunda de la primera, aquí. 1:30:00 más 0:45:00 es 2:15:00. Esto no es una zona horaria."),
            "result": L("One length in H:MM:SS, plus the same length as a total number of seconds.", "一段 H:MM:SS 的时长，以及同一段换成的总秒数。", "一段 H:MM:SS 的時長，以及同一段換成的總秒數。", "H:MM:SS の長さ一つと、同じ長さの合計秒数。", "H:MM:SS 길이 하나와, 같은 길이를 초로 센 총합.", "Một khoảng dạng H:MM:SS, cộng cùng khoảng đó tính bằng tổng số giây.", "Satu durasi H:MM:SS, plus durasi yang sama sebagai jumlah detik.", "Una duración en H:MM:SS, y la misma duración como número total de segundos."),
            "note": L("Open time duration when both lengths are written as hours:minutes:seconds. Minutes and seconds must be 0–59. Nothing is uploaded.", "两段都写成「时:分:秒」再打开时长。分和秒必须是 0–59。不上传。", "兩段都寫成「時:分:秒」再開時長。分和秒必須是 0–59。不上傳。", "両方を時:分:秒で書いてから開く。分と秒は 0–59。アップロードなし。", "두 길이를 시:분:초로 쓴 뒤 시간을 여세요. 분과 초는 0–59. 업로드 없음.", "Viết cả hai khoảng dạng giờ:phút:giây rồi mở thời lượng. Phút và giây phải 0–59. Không tải lên.", "Tulis kedua durasi sebagai jam:menit:detik, baru buka durasi. Menit dan detik harus 0–59. Tidak diunggah.", "Abra la duración cuando ambas longitudes estén escritas como horas:minutos:segundos. Minutos y segundos deben ser 0–59. Nada se sube."),
            "s1t": L("Write each length as H:MM:SS", "每一段都写成 H:MM:SS", "每一段都寫成 H:MM:SS", "各長さを H:MM:SS で書く", "각 길이를 H:MM:SS로 쓰기", "Viết mỗi khoảng dạng H:MM:SS", "Tulis tiap durasi sebagai H:MM:SS", "Escriba cada duración como H:MM:SS"),
            "s1b": L("1 hour 30 minutes is 1:30:00. 45 minutes is 0:45:00. 90 minutes is 1:30:00, not 0:90:00. Minutes and seconds above 59 fail.", "1 小时 30 分是 1:30:00。45 分是 0:45:00。90 分是 1:30:00，不是 0:90:00。分或秒超过 59 会失败。", "1 小時 30 分是 1:30:00。45 分是 0:45:00。90 分是 1:30:00，不是 0:90:00。分或秒超過 59 會失敗。", "1時間30分は 1:30:00。45分は 0:45:00。90分は 1:30:00 であり 0:90:00 ではない。分か秒が 59 を超えると失敗。", "1시간 30분은 1:30:00. 45분은 0:45:00. 90분은 1:30:00이지 0:90:00이 아닙니다. 분이나 초가 59를 넘으면 실패합니다.", "1 giờ 30 phút là 1:30:00. 45 phút là 0:45:00. 90 phút là 1:30:00, không phải 0:90:00. Phút hoặc giây trên 59 thì thất bại.", "1 jam 30 menit adalah 1:30:00. 45 menit adalah 0:45:00. 90 menit adalah 1:30:00, bukan 0:90:00. Menit atau detik di atas 59 gagal.", "1 hora 30 minutos es 1:30:00. 45 minutos es 0:45:00. 90 minutos es 1:30:00, no 0:90:00. Minutos o segundos por encima de 59 fallan."),
            "s2t": L("Open time duration on cv.cm", "打开 cv.cm 的时长", "打開 cv.cm 的時長", "cv.cmの時間の長さを開く", "cv.cm 시간 길이를 열기", "Mở thời lượng trên cv.cm", "Buka durasi di cv.cm", "Abra la duración en cv.cm"),
            "s2b": L("The math stays in this tab.", "计算留在当前标签页。", "計算留在目前分頁。", "計算はこのタブ。", "계산은 이 탭에서.", "Tính trong tab này.", "Hitungan di tab ini.", "La cuenta queda en esta pestaña."),
            "s3t": L("Choose add or subtract", "选相加或相减", "選相加或相減", "足すか引くか選ぶ", "더하기 또는 빼기 고르기", "Chọn cộng hoặc trừ", "Pilih tambah atau kurang", "Elija sumar o restar"),
            "s3b": L("Add joins the two lengths. Subtract takes the second away from the first. 1:30:00 minus 0:45:00 is 0:45:00.", "相加是两段接在一起。相减是用第一段去掉第二段。1:30:00 减 0:45:00 是 0:45:00。", "相加是兩段接在一起。相減是用第一段去掉第二段。1:30:00 減 0:45:00 是 0:45:00。", "足すは二つの長さをつなぐ。引くは一つ目から二つ目を除く。1:30:00 引く 0:45:00 は 0:45:00。", "더하기는 두 길이를 잇습니다. 빼기는 첫 길이에서 둘째를 뺍니다. 1:30:00 빼기 0:45:00은 0:45:00.", "Cộng là nối hai khoảng. Trừ là lấy khoảng thứ nhất bỏ khoảng thứ hai. 1:30:00 trừ 0:45:00 là 0:45:00.", "Tambah menyambung dua durasi. Kurang mengambil yang kedua dari yang pertama. 1:30:00 kurang 0:45:00 adalah 0:45:00.", "Sumar une las dos duraciones. Restar quita la segunda de la primera. 1:30:00 menos 0:45:00 es 0:45:00."),
            "s4t": L("Read the clock-style result and the total seconds", "看时钟样式的结果和总秒数", "看時鐘樣式的結果和總秒數", "時計風の結果と合計秒を読む", "시계 모양 결과와 총초 읽기", "Đọc kết quả kiểu đồng hồ và tổng giây", "Baca hasil gaya jam dan total detik", "Lea el resultado con forma de reloj y los segundos totales"),
            "s4b": L("1:30:00 plus 0:45:00 is 2:15:00, which is 8,100 seconds. Copy includes both lines. An API that wants seconds wants the second line.", "1:30:00 加 0:45:00 是 2:15:00，也就是 8,100 秒。复制包含两行。要秒数的接口要第二行。", "1:30:00 加 0:45:00 是 2:15:00，也就是 8,100 秒。複製包含兩行。要秒數的介面要第二行。", "1:30:00 足す 0:45:00 は 2:15:00、8,100 秒。コピーは両行。秒を求める API は二行目。", "1:30:00 더하기 0:45:00은 2:15:00, 즉 8,100초. 복사는 두 줄을 포함합니다. 초를 원하는 API는 둘째 줄.", "1:30:00 cộng 0:45:00 là 2:15:00, tức 8.100 giây. Bản copy gồm cả hai dòng. API cần giây thì cần dòng thứ hai.", "1:30:00 tambah 0:45:00 adalah 2:15:00, yaitu 8.100 detik. Salinan mencakup kedua baris. API yang minta detik menginginkan baris kedua.", "1:30:00 más 0:45:00 es 2:15:00, es decir 8.100 segundos. Copiar incluye ambas líneas. Una API que pide segundos quiere la segunda línea."),
            "s5t": L("A longer second length makes a negative result", "第二段更长，结果就是负的", "第二段更長，結果就是負的", "二つ目が長いと結果は負", "둘째가 더 길면 결과는 음수", "Khoảng thứ hai dài hơn thì kết quả âm", "Durasi kedua lebih panjang membuat hasil negatif", "Si la segunda es más larga, el resultado es negativo"),
            "s5b": L("0:30:00 minus 0:45:00 is -0:15:00. The minus is a direction on a length. It is not a clock time before midnight.", "0:30:00 减 0:45:00 是 -0:15:00。这个减号是时长的方向。它不是午夜前的钟点。", "0:30:00 減 0:45:00 是 -0:15:00。這個減號是時長的方向。它不是午夜前的鐘點。", "0:30:00 引く 0:45:00 は -0:15:00。マイナスは長さの向き。真夜中前の時刻ではない。", "0:30:00 빼기 0:45:00은 -0:15:00. 빼기는 길이의 방향입니다. 자정 전의 시계 시각이 아닙니다.", "0:30:00 trừ 0:45:00 là -0:15:00. Dấu trừ là hướng của một khoảng. Không phải giờ đồng hồ trước nửa đêm.", "0:30:00 kurang 0:45:00 adalah -0:15:00. Tanda minus adalah arah pada durasi. Bukan jam dinding sebelum tengah malam.", "0:30:00 menos 0:45:00 es -0:15:00. El menos es una dirección en una duración. No es una hora de reloj anterior a la medianoche."),
            "s6t": L("Keep this separate from a clock and a time zone", "这和钟点、时区是两件事", "這和鐘點、時區是兩件事", "時刻やタイムゾーンとは別", "시계 시각, 시간대와 구분하기", "Việc này khác giờ đồng hồ và múi giờ", "Ini terpisah dari jam dinding dan zona waktu", "Sepárelo de un reloj y de una zona horaria"),
            "s6b": L("1:30:00 here is a length of 90 minutes. It is not 1:30 in the morning, and it does not move between New York and Shanghai.", "这里的 1:30:00 是 90 分钟的长度。它不是凌晨 1:30，也不会在纽约和上海之间搬动。", "這裡的 1:30:00 是 90 分鐘的長度。它不是凌晨 1:30，也不會在紐約和上海之間搬動。", "ここでの 1:30:00 は 90 分の長さ。午前 1:30 ではなく、ニューヨークと上海の間も動かない。", "여기의 1:30:00은 90분의 길이입니다. 새벽 1:30이 아니고, 뉴욕과 상하이 사이를 옮기지도 않습니다.", "1:30:00 ở đây là khoảng 90 phút. Không phải 1:30 sáng, và không chuyển giữa New York và Thượng Hải.", "1:30:00 di sini adalah durasi 90 menit. Bukan pukul 1:30 pagi, dan tidak berpindah antara New York dan Shanghai.", "1:30:00 aquí es una duración de 90 minutos. No son las 1:30 de la madrugada, y no se mueve entre Nueva York y Shanghái."),
            "diagram1": L("1:30:00 + 0:45:00 = 2:15:00. 0:90:00 is not valid.", "1:30:00 + 0:45:00 = 2:15:00。0:90:00 不合法。", "1:30:00 + 0:45:00 = 2:15:00。0:90:00 不合法。", "1:30:00 + 0:45:00 = 2:15:00。0:90:00 は無効。", "1:30:00 + 0:45:00 = 2:15:00. 0:90:00은 안 됩니다.", "1:30:00 + 0:45:00 = 2:15:00. 0:90:00 không hợp lệ.", "1:30:00 + 0:45:00 = 2:15:00. 0:90:00 tidak sah.", "1:30:00 + 0:45:00 = 2:15:00. 0:90:00 no es válido."),
            "diagram2": L("A longer second length gives a minus. This is a length, not a clock.", "第二段更长就出现减号。这是时长，不是钟点。", "第二段更長就出現減號。這是時長，不是鐘點。", "二つ目が長いとマイナス。長さであり時刻ではない。", "둘째가 더 길면 빼기. 이것은 길이지 시계가 아닙니다.", "Khoảng thứ hai dài hơn thì có dấu trừ. Đây là khoảng, không phải đồng hồ.", "Durasi kedua lebih panjang memberi tanda minus. Ini durasi, bukan jam.", "Si la segunda es más larga, aparece un menos. Es una duración, no un reloj."),
        },
        {
            "q1": L("Can I add hours and minutes free online?", "可以免费在线把小时和分钟相加吗？", "可以免費線上把小時和分鐘相加嗎？", "時間と分を無料で足せる？", "시간과 분을 무료로 더할 수 있나요?", "Cộng giờ và phút miễn phí online được không?", "Bisa jumlahkan jam dan menit gratis online?", "¿Puedo sumar horas y minutos gratis en línea?"),
            "a1": L("Yes. cv.cm adds or subtracts two H:MM:SS lengths in this tab. Nothing is uploaded.", "可以。cv.cm 在当前标签页把两段 H:MM:SS 相加或相减。不上传。", "可以。cv.cm 在目前分頁把兩段 H:MM:SS 相加或相減。不上傳。", "できる。このタブで二つの H:MM:SS を足すか引く。アップロードなし。", "됩니다. 이 탭에서 H:MM:SS 길이 둘을 더하거나 뺍니다. 업로드 없음.", "Được. Cộng hoặc trừ hai khoảng H:MM:SS trong tab này. Không tải lên.", "Ya. Menambah atau mengurangi dua durasi H:MM:SS di tab ini. Tidak diunggah.", "Sí. Suma o resta dos duraciones H:MM:SS en esta pestaña. Nada se sube."),
            "q2": L("What format do the times use?", "时间用什么格式？", "時間用什麼格式？", "形式は？", "형식은?", "Định dạng là gì?", "Formatnya apa?", "¿Qué formato usan los tiempos?"),
            "a2": L("Hours:minutes:seconds, such as 1:30:00. Minutes and seconds must be 0–59. 0:90:00 fails. Write 1:30:00.", "时:分:秒，例如 1:30:00。分和秒必须是 0–59。0:90:00 会失败。写成 1:30:00。", "時:分:秒，例如 1:30:00。分和秒必須是 0–59。0:90:00 會失敗。寫成 1:30:00。", "時:分:秒。例は 1:30:00。分と秒は 0–59。0:90:00 は失敗。1:30:00 と書く。", "시:분:초, 예를 들어 1:30:00. 분과 초는 0–59. 0:90:00은 실패합니다. 1:30:00으로 쓰세요.", "Giờ:phút:giây, như 1:30:00. Phút và giây phải 0–59. 0:90:00 thất bại. Viết 1:30:00.", "Jam:menit:detik, seperti 1:30:00. Menit dan detik harus 0–59. 0:90:00 gagal. Tulis 1:30:00.", "Horas:minutos:segundos, como 1:30:00. Minutos y segundos deben ser 0–59. 0:90:00 falla. Escriba 1:30:00."),
            "q3": L("What is 1:30:00 plus 0:45:00?", "1:30:00 加 0:45:00 是多少？", "1:30:00 加 0:45:00 是多少？", "1:30:00 足す 0:45:00 は？", "1:30:00 더하기 0:45:00은?", "1:30:00 cộng 0:45:00 là bao nhiêu?", "1:30:00 tambah 0:45:00 berapa?", "¿Cuánto es 1:30:00 más 0:45:00?"),
            "a3": L("2:15:00, which is 8,100 seconds.", "2:15:00，也就是 8,100 秒。", "2:15:00，也就是 8,100 秒。", "2:15:00。8,100 秒。", "2:15:00, 즉 8,100초.", "2:15:00, tức 8.100 giây.", "2:15:00, yaitu 8.100 detik.", "2:15:00, es decir 8.100 segundos."),
            "q4": L("What if the second time is longer?", "第二段更长呢？", "第二段更長呢？", "二つ目が長いときは？", "둘째가 더 길면?", "Khoảng thứ hai dài hơn thì sao?", "Jika yang kedua lebih panjang?", "¿Y si la segunda es más larga?"),
            "a4": L("Subtracting it gives a negative length, such as -0:15:00. That is a direction, not a clock time.", "相减会得到负的时长，例如 -0:15:00。那是方向，不是钟点。", "相減會得到負的時長，例如 -0:15:00。那是方向，不是鐘點。", "引くと -0:15:00 のような負の長さ。向きであり時刻ではない。", "빼면 -0:15:00 같은 음의 길이가 됩니다. 방향이지 시계 시각이 아닙니다.", "Trừ sẽ ra khoảng âm, như -0:15:00. Đó là hướng, không phải giờ đồng hồ.", "Mengurangi memberi durasi negatif, seperti -0:15:00. Itu arah, bukan jam dinding.", "Restarla da una duración negativa, como -0:15:00. Es una dirección, no una hora de reloj."),
            "q5": L("Is this a time zone converter?", "这是时区转换吗？", "這是時區轉換嗎？", "タイムゾーン変換？", "시간대 변환인가요?", "Đây có phải đổi múi giờ?", "Apakah ini pengubah zona waktu?", "¿Es un conversor de zona horaria?"),
            "a5": L("No. These are lengths of time. A clock time in a city is the time-zone tool.", "不是。这里是时长。某个城市的钟点用时区工具。", "不是。這裡是時長。某個城市的鐘點用時區工具。", "違う。これは時間の長さ。ある都市の時刻はタイムゾーンのツール。", "아니요. 여기는 시간의 길이입니다. 한 도시의 시계 시각은 시간대 도구입니다.", "Không. Đây là khoảng thời gian. Giờ đồng hồ ở một thành phố là công cụ múi giờ.", "Tidak. Ini durasi. Jam di sebuah kota adalah alat zona waktu.", "No. Son duraciones. Una hora de reloj en una ciudad es la herramienta de zona horaria."),
        },
    ),
    "calculate-percent": lesson(
        {
            "name": L("How to calculate a percentage", "怎么算百分比", "怎麼算百分比", "パーセントの計算方法", "백분율 계산하는 법", "Cách tính phần trăm", "Cara hitung persentase", "Cómo calcular un porcentaje"),
            "blurb": L("Read four lines from the same two numbers. 25% of 200 is 50. 25 is 12.5% of 200. 200 plus 25% is 250.", "同一对数字读出四行。200 的 25% 是 50。25 是 200 的 12.5%。200 加上 25% 是 250。", "同一對數字讀出四行。200 的 25% 是 50。25 是 200 的 12.5%。200 加上 25% 是 250。", "同じ二つの数から四行。200 の 25% は 50。25 は 200 の 12.5%。200 に 25% を足すと 250。", "같은 두 수에서 네 줄을 읽습니다. 200의 25%는 50. 25는 200의 12.5%. 200 더하기 25%는 250.", "Đọc bốn dòng từ cùng hai số. 25% của 200 là 50. 25 là 12,5% của 200. 200 cộng 25% là 250.", "Baca empat baris dari dua angka yang sama. 25% dari 200 adalah 50. 25 adalah 12,5% dari 200. 200 ditambah 25% adalah 250.", "Lea cuatro líneas de los mismos dos números. El 25% de 200 es 50. 25 es el 12,5% de 200. 200 más 25% es 250."),
            "title": L("How to calculate a percentage", "怎么算百分比", "怎麼算百分比", "パーセントの計算方法", "백분율 계산하는 법", "Cách tính phần trăm", "Cara hitung persentase", "Cómo calcular un porcentaje"),
            "lead": L("You have two numbers and four possible questions. You will enter them in this tab and copy the line that matches the question. 25% of 200, 25 as a percent of 200, and 200 increased by 25% are three different answers.", "你有两个数，和四种可能的问题。在当前标签页填进去，复制对上那个问题的一行。200 的 25%、25 占 200 的百分比、200 增加 25%，是三个不同的答案。", "你有兩個數，和四種可能的問題。在目前分頁填進去，複製對上那個問題的一行。200 的 25%、25 占 200 的百分比、200 增加 25%，是三個不同的答案。", "二つの数と四種類の問いがある。このタブに入れ、問いに合う行をコピー。200 の 25%、25 が 200 の何%、200 を 25% 増やす、は三つの別の答え。", "수 둘과 가능한 질문 넷이 있습니다. 이 탭에 넣고 질문에 맞는 줄을 복사하세요. 200의 25%, 25가 200의 몇 퍼센트인지, 200을 25% 늘린 값은 서로 다른 답입니다.", "Bạn có hai số và bốn câu hỏi có thể. Nhập trong tab này và copy dòng khớp câu hỏi. 25% của 200, 25 là bao nhiêu phần trăm của 200, và 200 tăng 25% là ba đáp án khác nhau.", "Anda punya dua angka dan empat pertanyaan yang mungkin. Masukkan di tab ini dan salin baris yang cocok dengan pertanyaan. 25% dari 200, 25 sebagai persen dari 200, dan 200 ditambah 25% adalah tiga jawaban berbeda.", "Tiene dos números y cuatro preguntas posibles. Escríbalos aquí y copie la línea que coincide con la pregunta. El 25% de 200, 25 como porcentaje de 200, y 200 aumentado un 25% son tres respuestas distintas."),
            "result": L("The one line that matches the question: a percent of a number, what percent one number is of another, a number plus a percent, or the percent change from one number to the other.", "对上问题的那一行：一个数的百分之几、一个数是另一个数的百分之几、一个数加上百分之几，或从一个数到另一个数的变化百分比。", "對上問題的那一行：一個數的百分之幾、一個數是另一個數的百分之幾、一個數加上百分之幾，或從一個數到另一個數的變化百分比。", "問いに合う一行。ある数の何%、ある数がもう一つの何%、ある数に何%を足した値、またはある数から別の数への変化率。", "질문에 맞는 한 줄. 한 수의 몇 퍼센트, 한 수가 다른 수의 몇 퍼센트인지, 한 수에 퍼센트를 더한 값, 또는 한 수에서 다른 수로의 변화율.", "Đúng một dòng khớp câu hỏi: phần trăm của một số, một số là bao nhiêu phần trăm của số kia, một số cộng phần trăm, hoặc phần trăm thay đổi từ số này sang số kia.", "Satu baris yang cocok dengan pertanyaan: persen dari suatu angka, berapa persen satu angka dari angka lain, angka ditambah persen, atau perubahan persen dari satu angka ke angka lain.", "La línea que coincide con la pregunta: un porcentaje de un número, qué porcentaje es un número de otro, un número más un porcentaje, o el cambio porcentual de un número a otro."),
            "note": L("Open percentage when you can point at the two numbers. A zero in the second box leaves two of the lines as a dash. Nothing is uploaded.", "能指出这两个数再打开百分比。第二个框是 0，其中两行会变成横线。不上传。", "能指出這兩個數再開百分比。第二個框是 0，其中兩行會變成橫線。不上傳。", "二つの数を指せるようになってから開く。二つ目が 0 だと二行が横線になる。アップロードなし。", "두 수를 가리킬 수 있을 때 백분율을 여세요. 둘째 칸이 0이면 두 줄이 대시가 됩니다. 업로드 없음.", "Chỉ được hai số thì mở phần trăm. Ô thứ hai bằng 0 thì hai dòng thành gạch. Không tải lên.", "Bisa menunjuk kedua angka, baru buka persentase. Nol di kotak kedua membuat dua baris menjadi garis. Tidak diunggah.", "Abra el porcentaje cuando pueda señalar los dos números. Un cero en la segunda casilla deja dos líneas como una raya. Nada se sube."),
            "s1t": L("Name which question you are answering", "先点名你在回答哪个问题", "先點名你在回答哪個問題", "どの問いに答えるか名指しする", "어떤 질문에 답하는지 지목하기", "Chỉ đúng câu hỏi bạn đang trả lời", "Sebut pertanyaan yang sedang dijawab", "Nombre qué pregunta está respondiendo"),
            "s1b": L("25% of 200 is 50. 25 is 12.5% of 200. 200 plus 25% is 250. The change from 200 to 25 is -87.5%. Copying the wrong line answers a different question.", "200 的 25% 是 50。25 是 200 的 12.5%。200 加上 25% 是 250。从 200 到 25 的变化是 -87.5%。复制错行，答的就是另一个问题。", "200 的 25% 是 50。25 是 200 的 12.5%。200 加上 25% 是 250。從 200 到 25 的變化是 -87.5%。複製錯行，答的就是另一個問題。", "200 の 25% は 50。25 は 200 の 12.5%。200 に 25% を足すと 250。200 から 25 への変化は -87.5%。違う行をコピーすると別の問いの答えになる。", "200의 25%는 50. 25는 200의 12.5%. 200 더하기 25%는 250. 200에서 25로의 변화는 -87.5%. 잘못된 줄을 복사하면 다른 질문의 답이 됩니다.", "25% của 200 là 50. 25 là 12,5% của 200. 200 cộng 25% là 250. Thay đổi từ 200 sang 25 là -87,5%. Copy nhầm dòng là trả lời câu khác.", "25% dari 200 adalah 50. 25 adalah 12,5% dari 200. 200 ditambah 25% adalah 250. Perubahan dari 200 ke 25 adalah -87,5%. Menyalin baris yang salah menjawab pertanyaan lain.", "El 25% de 200 es 50. 25 es el 12,5% de 200. 200 más 25% es 250. El cambio de 200 a 25 es -87,5%. Copiar la línea equivocada responde otra pregunta."),
            "s2t": L("Open percentage on cv.cm", "打开 cv.cm 的百分比", "打開 cv.cm 的百分比", "cv.cmのパーセントを開く", "cv.cm 백분율을 열기", "Mở phần trăm trên cv.cm", "Buka persentase di cv.cm", "Abra el porcentaje en cv.cm"),
            "s2b": L("The four lines stay in this tab.", "四行都留在当前标签页。", "四行都留在目前分頁。", "四行はこのタブ。", "네 줄은 이 탭에 있습니다.", "Bốn dòng ở trong tab này.", "Empat baris tetap di tab ini.", "Las cuatro líneas quedan en esta pestaña."),
            "s3t": L("Enter the two numbers in order", "按顺序填两个数", "按順序填兩個數", "二つの数を順に入れる", "두 수를 순서대로 넣기", "Nhập hai số đúng thứ tự", "Masukkan dua angka sesuai urutan", "Escriba los dos números en orden"),
            "s3b": L("The first box is the percent, or the part, or the new number, depending on the line. The second box is the whole, or the starting number. With 25 and 200, the first line is 25% of 200.", "第一个框是百分比、部分，或新的数，看你读哪一行。第二个框是整体，或起始的数。填 25 和 200 时，第一行是 200 的 25%。", "第一個框是百分比、部分，或新的數，看你讀哪一行。第二個框是整體，或起始的數。填 25 和 200 時，第一行是 200 的 25%。", "一つ目は、読む行によってパーセントか部分か新しい数。二つ目は全体か開始の数。25 と 200 なら一行目は 200 の 25%。", "첫 칸은 읽는 줄에 따라 퍼센트, 부분, 또는 새 수입니다. 둘째 칸은 전체 또는 시작 수입니다. 25와 200이면 첫 줄은 200의 25%입니다.", "Ô thứ nhất là phần trăm, phần, hoặc số mới, tùy dòng bạn đọc. Ô thứ hai là toàn bộ, hoặc số bắt đầu. Với 25 và 200, dòng đầu là 25% của 200.", "Kotak pertama adalah persen, bagian, atau angka baru, tergantung baris yang dibaca. Kotak kedua adalah keseluruhan, atau angka awal. Dengan 25 dan 200, baris pertama adalah 25% dari 200.", "La primera casilla es el porcentaje, la parte o el número nuevo, según la línea. La segunda es el total, o el número de partida. Con 25 y 200, la primera línea es el 25% de 200."),
            "s4t": L("Match the line to the question", "让那一行对上问题", "讓那一行對上問題", "行を問いに合わせる", "줄을 질문에 맞추기", "Khớp dòng với câu hỏi", "Cocokkan baris dengan pertanyaan", "Haga coincidir la línea con la pregunta"),
            "s4b": L("Percent of a number uses the first line. What percent one number is of another uses the second. A number plus a percent uses the third. The change from the second number to the first uses the fourth.", "一个数的百分之几用第一行。一个数是另一个数的百分之几用第二行。一个数加上百分之几用第三行。从第二个数变到第一个数用第四行。", "一個數的百分之幾用第一行。一個數是另一個數的百分之幾用第二行。一個數加上百分之幾用第三行。從第二個數變到第一個數用第四行。", "ある数の何%は一行目。ある数がもう一つの何%かは二行目。ある数に何%を足すのは三行目。二つ目から一つ目への変化は四行目。", "한 수의 몇 퍼센트는 첫 줄. 한 수가 다른 수의 몇 퍼센트인지는 둘째 줄. 한 수에 퍼센트를 더하는 것은 셋째 줄. 둘째 수에서 첫째 수로의 변화는 넷째 줄.", "Phần trăm của một số dùng dòng một. Một số là bao nhiêu phần trăm của số kia dùng dòng hai. Một số cộng phần trăm dùng dòng ba. Thay đổi từ số thứ hai sang số thứ nhất dùng dòng bốn.", "Persen dari suatu angka memakai baris pertama. Berapa persen satu angka dari angka lain memakai baris kedua. Angka ditambah persen memakai baris ketiga. Perubahan dari angka kedua ke angka pertama memakai baris keempat.", "Un porcentaje de un número usa la primera línea. Qué porcentaje es un número de otro usa la segunda. Un número más un porcentaje usa la tercera. El cambio del segundo número al primero usa la cuarta."),
            "s5t": L("A zero whole leaves two lines blank", "整体是 0，就有两行是横线", "整體是 0，就有兩行是橫線", "全体が 0 なら二行が横線", "전체가 0이면 두 줄이 대시", "Toàn bộ bằng 0 thì hai dòng là gạch", "Keseluruhan nol membuat dua baris kosong", "Un total en cero deja dos líneas en blanco"),
            "s5b": L("You cannot ask what percent something is of zero, and you cannot ask the percent change from zero. The first and third lines still run, because they do not divide by the second number.", "不能问某数是 0 的百分之几，也不能问从 0 变过来的百分比。第一行和第三行仍然有结果，因为它们不用第二个数做除数。", "不能問某數是 0 的百分之幾，也不能問從 0 變過來的百分比。第一行和第三行仍然有結果，因為它們不用第二個數做除數。", "ゼロの何%か、ゼロからの変化率は問えない。一行目と三行目は残る。二つ目で割らないから。", "무엇이 0의 몇 퍼센트인지, 0에서의 변화율은 물을 수 없습니다. 첫 줄과 셋째 줄은 그대로 나옵니다. 둘째 수로 나누지 않기 때문입니다.", "Không hỏi một số là bao nhiêu phần trăm của 0, và không hỏi phần trăm thay đổi từ 0. Dòng một và dòng ba vẫn chạy, vì chúng không chia cho số thứ hai.", "Anda tidak bisa bertanya berapa persen sesuatu dari nol, dan tidak bisa bertanya perubahan persen dari nol. Baris pertama dan ketiga tetap jalan, karena tidak membagi dengan angka kedua.", "No puede preguntar qué porcentaje es algo de cero, ni el cambio porcentual desde cero. La primera y la tercera línea siguen, porque no dividen por el segundo número."),
            "s6t": L("Copy only the line you named", "只复制你点名的那一行", "只複製你點名的那一行", "名指しした行だけコピー", "지목한 줄만 복사", "Chỉ copy dòng bạn đã chỉ", "Salin hanya baris yang Anda sebut", "Copie solo la línea que nombró"),
            "s6b": L("The clipboard gets all four lines. Paste the one that matches. 50, 12.5%, 250, and -87.5% must not be swapped.", "剪贴板会放上全部四行。贴对上问题的那一行。50、12.5%、250 和 -87.5% 不能互换。", "剪貼簿會放上全部四行。貼對上問題的那一行。50、12.5%、250 和 -87.5% 不能互換。", "クリップボードには四行入る。合う一行を貼る。50、12.5%、250、-87.5% を取り違えない。", "클립보드에는 네 줄이 들어갑니다. 맞는 한 줄을 붙이세요. 50, 12.5%, 250, -87.5%를 바꾸지 마세요.", "Clipboard nhận cả bốn dòng. Dán đúng dòng khớp. 50, 12,5%, 250 và -87,5% không được tráo.", "Papan klip mendapat keempat baris. Tempel yang cocok. 50, 12,5%, 250, dan -87,5% tidak boleh tertukar.", "El portapapeles recibe las cuatro líneas. Pegue la que coincide. 50, 12,5%, 250 y -87,5% no deben intercambiarse."),
            "diagram1": L("25 and 200: 50, 12.5%, 250, and -87.5% are four different answers.", "25 和 200：50、12.5%、250 和 -87.5% 是四个不同的答案。", "25 和 200：50、12.5%、250 和 -87.5% 是四個不同的答案。", "25 と 200。50、12.5%、250、-87.5% は四つの別の答え。", "25와 200: 50, 12.5%, 250, -87.5%는 서로 다른 네 답.", "25 và 200: 50, 12,5%, 250 và -87,5% là bốn đáp án khác nhau.", "25 dan 200: 50, 12,5%, 250, dan -87,5% adalah empat jawaban berbeda.", "25 y 200: 50, 12,5%, 250 y -87,5% son cuatro respuestas distintas."),
            "diagram2": L("Copy the line that matches the question. A zero whole blanks two lines.", "复制对上问题的那一行。整体是 0，就有两行是横线。", "複製對上問題的那一行。整體是 0，就有兩行是橫線。", "問いに合う行をコピー。全体が 0 なら二行が横線。", "질문에 맞는 줄을 복사. 전체가 0이면 두 줄이 대시.", "Copy dòng khớp câu hỏi. Toàn bộ bằng 0 thì hai dòng là gạch.", "Salin baris yang cocok. Keseluruhan nol membuat dua baris garis.", "Copie la línea que coincide. Un total en cero deja dos líneas en blanco."),
        },
        {
            "q1": L("Can I calculate a percentage free online?", "可以免费在线算百分比吗？", "可以免費線上算百分比嗎？", "パーセントを無料で計算できる？", "백분율을 무료로 계산할 수 있나요?", "Tính phần trăm miễn phí online được không?", "Bisa hitung persentase gratis online?", "¿Puedo calcular un porcentaje gratis en línea?"),
            "a1": L("Yes. cv.cm shows four readings of the same two numbers in this tab. Nothing is uploaded.", "可以。cv.cm 在当前标签页用同一对数字给出四种读法。不上传。", "可以。cv.cm 在目前分頁用同一對數字給出四種讀法。不上傳。", "できる。このタブで同じ二つの数を四通りに読む。アップロードなし。", "됩니다. 이 탭에서 같은 두 수를 네 가지로 읽습니다. 업로드 없음.", "Được. Hiện bốn cách đọc cùng hai số trong tab này. Không tải lên.", "Ya. Menampilkan empat bacaan dari dua angka yang sama di tab ini. Tidak diunggah.", "Sí. Muestra cuatro lecturas de los mismos dos números en esta pestaña. Nada se sube."),
            "q2": L("What is 25% of 200?", "200 的 25% 是多少？", "200 的 25% 是多少？", "200 の 25% は？", "200의 25%는?", "25% của 200 là bao nhiêu?", "25% dari 200 berapa?", "¿Cuánto es el 25% de 200?"),
            "a2": L("50. That is the first line when the boxes are 25 and 200.", "50。两个框是 25 和 200 时，这是第一行。", "50。兩個框是 25 和 200 時，這是第一行。", "50。枠が 25 と 200 のとき一行目。", "50. 칸이 25와 200일 때 첫 줄입니다.", "50. Đó là dòng đầu khi hai ô là 25 và 200.", "50. Itu baris pertama saat kotaknya 25 dan 200.", "50. Es la primera línea cuando las casillas son 25 y 200."),
            "q3": L("What percent is 25 of 200?", "25 是 200 的百分之几？", "25 是 200 的百分之幾？", "25 は 200 の何%？", "25는 200의 몇 퍼센트인가요?", "25 là bao nhiêu phần trăm của 200?", "25 adalah berapa persen dari 200?", "¿Qué porcentaje es 25 de 200?"),
            "a3": L("12.5%. That is the second line, not the first.", "12.5%。那是第二行，不是第一行。", "12.5%。那是第二行，不是第一行。", "12.5%。二行目であり一行目ではない。", "12.5%. 둘째 줄이지 첫 줄이 아닙니다.", "12,5%. Đó là dòng hai, không phải dòng một.", "12,5%. Itu baris kedua, bukan yang pertama.", "12,5%. Es la segunda línea, no la primera."),
            "q4": L("What is 200 increased by 25%?", "200 增加 25% 是多少？", "200 增加 25% 是多少？", "200 を 25% 増やすと？", "200을 25% 늘리면?", "200 tăng 25% là bao nhiêu?", "200 ditambah 25% berapa?", "¿Cuánto es 200 aumentado un 25%?"),
            "a4": L("250. That is the third line. The change from 200 down to 25 is -87.5%, which is the fourth line.", "250。那是第三行。从 200 降到 25 的变化是 -87.5%，那是第四行。", "250。那是第三行。從 200 降到 25 的變化是 -87.5%，那是第四行。", "250。三行目。200 から 25 への変化は -87.5% で四行目。", "250. 셋째 줄입니다. 200에서 25로 내려간 변화는 -87.5%이고 넷째 줄입니다.", "250. Đó là dòng ba. Thay đổi từ 200 xuống 25 là -87,5%, dòng bốn.", "250. Itu baris ketiga. Perubahan dari 200 turun ke 25 adalah -87,5%, baris keempat.", "250. Es la tercera línea. El cambio de 200 a 25 es -87,5%, que es la cuarta línea."),
            "q5": L("What if the second number is zero?", "第二个数是 0 呢？", "第二個數是 0 呢？", "二つ目が 0 なら？", "둘째 수가 0이면?", "Số thứ hai bằng 0 thì sao?", "Jika angka kedua nol?", "¿Y si el segundo número es cero?"),
            "a5": L("What-percent and percent-change become a dash. You cannot divide by zero. The other two lines still run.", "「是百分之几」和「变化百分比」变成横线。不能除以 0。另外两行仍然有结果。", "「是百分之幾」和「變化百分比」變成橫線。不能除以 0。另外兩行仍然有結果。", "何%かと変化率は横線。ゼロでは割れない。残りの二行は出る。", "몇 퍼센트인지와 변화율은 대시가 됩니다. 0으로 나눌 수 없습니다. 나머지 두 줄은 나옵니다.", "Dòng phần trăm và dòng thay đổi thành gạch. Không chia cho 0. Hai dòng kia vẫn chạy.", "Berapa persen dan perubahan persen menjadi garis. Tidak bisa dibagi nol. Dua baris lain tetap jalan.", "Qué-porcentaje y cambio-porcentual pasan a una raya. No se puede dividir por cero. Las otras dos líneas siguen."),
        },
    ),
}

META = {
    "titleProfitMargin": L("How to calculate a profit margin | cv.cm", "怎么算利润率 | cv.cm", "怎麼算利潤率 | cv.cm", "利益率の計算方法 | cv.cm", "이익률 계산하는 법 | cv.cm", "Cách tính biên lợi nhuận | cv.cm", "Cara hitung margin laba | cv.cm", "Cómo calcular un margen de beneficio | cv.cm"),
    "descProfitMargin": L("Margin is profit divided by the selling price. Markup is profit divided by the cost. Cost 50 and price 80 is 37.50% margin and 60.00% markup. Nothing is uploaded.", "利润率是利润除以售价。加价率是利润除以成本。成本 50、售价 80 是利润率 37.50%、加价率 60.00%。不上传。", "利潤率是利潤除以售價。加價率是利潤除以成本。成本 50、售價 80 是利潤率 37.50%、加價率 60.00%。不上傳。", "利益率は利益÷売価。マークアップは利益÷原価。原価 50・売価 80 は利益率 37.50%、マークアップ 60.00%。アップロードなし。", "이익률은 이익 나누기 판매가. 마크업은 이익 나누기 원가. 원가 50, 판매가 80이면 이익률 37.50%, 마크업 60.00%. 업로드 없음.", "Biên là lợi nhuận chia giá bán. Markup là lợi nhuận chia giá vốn. Vốn 50, giá 80: biên 37,50% và markup 60,00%. Không tải lên.", "Margin adalah laba dibagi harga jual. Markup adalah laba dibagi biaya. Biaya 50, harga 80: margin 37,50% dan markup 60,00%. Tidak diunggah.", "El margen es beneficio dividido por el precio. El markup es beneficio dividido por el coste. Coste 50 y precio 80: margen 37,50% y markup 60,00%. Nada se sube."),
    "titleConvertBase": L("How to convert a number between bases | cv.cm", "怎么在进制之间换算 | cv.cm", "怎麼在進制之間換算 | cv.cm", "進数を変換する方法 | cv.cm", "진법 사이 변환하는 법 | cv.cm", "Cách đổi số giữa các cơ số | cv.cm", "Cara ubah bilangan antar basis | cv.cm", "Cómo convertir un número entre bases | cv.cm"),
    "descConvertBase": L("Convert one integer between bases 2 and 36. 255 in base 10 is FF in base 16. No 0x prefix and no fraction. Letters come out uppercase. Nothing is uploaded.", "把一个整数在 2 到 36 进制之间换算。十进制 255 是十六进制 FF。不要 0x 前缀，也不要小数。结果字母是大写。不上传。", "把一個整數在 2 到 36 進制之間換算。十進制 255 是十六進制 FF。不要 0x 前綴，也不要小數。結果字母是大寫。不上傳。", "一つの整数を 2 から 36 進の間で変換。10進の 255 は 16進の FF。0x も小数も無し。英字は大文字。アップロードなし。", "정수 하나를 2진부터 36진 사이로 바꿉니다. 10진 255는 16진 FF. 0x 접두어와 소수는 안 됩니다. 글자는 대문자. 업로드 없음.", "Đổi một số nguyên giữa cơ số 2 và 36. 255 ở cơ số 10 là FF ở cơ số 16. Không 0x, không phần thập phân. Chữ viết hoa. Không tải lên.", "Ubah satu bilangan antara basis 2 dan 36. 255 di basis 10 adalah FF di basis 16. Tanpa 0x dan tanpa pecahan. Huruf keluar kapital. Tidak diunggah.", "Convierta un entero entre las bases 2 y 36. 255 en base 10 es FF en base 16. Sin prefijo 0x y sin fracción. Las letras salen en mayúsculas. Nada se sube."),
    "titleAddDuration": L("How to add hours and minutes | cv.cm", "怎么把小时和分钟相加 | cv.cm", "怎麼把小時和分鐘相加 | cv.cm", "時間と分を足す方法 | cv.cm", "시간과 분 더하는 법 | cv.cm", "Cách cộng giờ và phút | cv.cm", "Cara jumlahkan jam dan menit | cv.cm", "Cómo sumar horas y minutos | cv.cm"),
    "descAddDuration": L("Add or subtract two lengths as H:MM:SS. 1:30:00 plus 0:45:00 is 2:15:00. Minutes and seconds must be 0–59. A longer second length gives a minus. Nothing is uploaded.", "把两段 H:MM:SS 相加或相减。1:30:00 加 0:45:00 是 2:15:00。分和秒必须是 0–59。第二段更长就出现减号。不上传。", "把兩段 H:MM:SS 相加或相減。1:30:00 加 0:45:00 是 2:15:00。分和秒必須是 0–59。第二段更長就出現減號。不上傳。", "二つの H:MM:SS を足すか引く。1:30:00 足す 0:45:00 は 2:15:00。分と秒は 0–59。二つ目が長いとマイナス。アップロードなし。", "두 H:MM:SS 길이를 더하거나 뺍니다. 1:30:00 더하기 0:45:00은 2:15:00. 분과 초는 0–59. 둘째가 더 길면 빼기. 업로드 없음.", "Cộng hoặc trừ hai khoảng H:MM:SS. 1:30:00 cộng 0:45:00 là 2:15:00. Phút và giây phải 0–59. Khoảng thứ hai dài hơn thì có dấu trừ. Không tải lên.", "Tambah atau kurangi dua durasi H:MM:SS. 1:30:00 tambah 0:45:00 adalah 2:15:00. Menit dan detik harus 0–59. Durasi kedua lebih panjang memberi tanda minus. Tidak diunggah.", "Sume o reste dos duraciones H:MM:SS. 1:30:00 más 0:45:00 es 2:15:00. Minutos y segundos deben ser 0–59. Si la segunda es más larga, aparece un menos. Nada se sube."),
    "titleCalculatePercent": L("How to calculate a percentage | cv.cm", "怎么算百分比 | cv.cm", "怎麼算百分比 | cv.cm", "パーセントの計算方法 | cv.cm", "백분율 계산하는 법 | cv.cm", "Cách tính phần trăm | cv.cm", "Cara hitung persentase | cv.cm", "Cómo calcular un porcentaje | cv.cm"),
    "descCalculatePercent": L("25% of 200 is 50. 25 is 12.5% of 200. 200 plus 25% is 250. The change from 200 to 25 is -87.5%. Copy the line that matches the question. Nothing is uploaded.", "200 的 25% 是 50。25 是 200 的 12.5%。200 加上 25% 是 250。从 200 到 25 的变化是 -87.5%。复制对上问题的那一行。不上传。", "200 的 25% 是 50。25 是 200 的 12.5%。200 加上 25% 是 250。從 200 到 25 的變化是 -87.5%。複製對上問題的那一行。不上傳。", "200 の 25% は 50。25 は 200 の 12.5%。200 に 25% を足すと 250。200 から 25 への変化は -87.5%。問いに合う行をコピー。アップロードなし。", "200의 25%는 50. 25는 200의 12.5%. 200 더하기 25%는 250. 200에서 25로의 변화는 -87.5%. 질문에 맞는 줄을 복사하세요. 업로드 없음.", "25% của 200 là 50. 25 là 12,5% của 200. 200 cộng 25% là 250. Từ 200 sang 25 là -87,5%. Copy dòng khớp câu hỏi. Không tải lên.", "25% dari 200 adalah 50. 25 adalah 12,5% dari 200. 200 ditambah 25% adalah 250. Perubahan dari 200 ke 25 adalah -87,5%. Salin baris yang cocok. Tidak diunggah.", "El 25% de 200 es 50. 25 es el 12,5% de 200. 200 más 25% es 250. El cambio de 200 a 25 es -87,5%. Copie la línea que coincide. Nada se sube."),
}


def inject() -> None:
    if set(LESSONS) != {"profit-margin", "convert-base", "add-duration", "calculate-percent"}:
        raise SystemExit("lesson ids")
    for loc, path in FILES.items():
        data = json.loads(path.read_text())
        data["faq"].setdefault("learn", {})
        for lesson_id, payload in LESSONS.items():
            data["learn"][lesson_id] = payload["copy"][loc]
            data["faq"]["learn"][lesson_id] = payload["faq"][loc]
        for key, by_loc in META.items():
            data["meta"][key] = by_loc[loc]
        path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n")
        print("patched", path.name)


if __name__ == "__main__":
    inject()
