#!/usr/bin/env python3
"""Inject day-count, date shift, ISO week, and VAT how-tos."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LOCS = ["en", "zh-CN", "zh-TW", "ja", "ko", "vi", "id", "es"]
FILES = {loc: ROOT / "src/locales" / f"{loc}.json" for loc in LOCS}
COPY_KEYS = [
    "name", "blurb", "title", "lead", "result", "note",
    "s1t", "s1b", "s2t", "s2b", "s3t", "s3b", "s4t", "s4b", "s5t", "s5b", "s6t", "s6b",
    "diagram1", "diagram2",
]
FAQ_KEYS = [f"{side}{i}" for i in range(1, 6) for side in ("q", "a")]


def L(*vals: str) -> dict[str, str]:
    if len(vals) != 8:
        raise ValueError(len(vals), vals[0] if vals else None)
    return dict(zip(LOCS, vals))


def lesson(fields: dict[str, dict[str, str]], faq: dict[str, dict[str, str]]) -> dict:
    missing = [k for k in COPY_KEYS if k not in fields]
    missing += [k for k in FAQ_KEYS if k not in faq]
    if missing:
        raise SystemExit(f"missing keys: {missing}")
    if not fields["title"]["en"].startswith("How to "):
        raise SystemExit(fields["title"]["en"])
    return {
        "copy": {loc: {k: v[loc] for k, v in fields.items()} for loc in LOCS},
        "faq": {loc: {k: v[loc] for k, v in faq.items()} for loc in LOCS},
    }


LESSONS = {
    "days-between": lesson(
        {
            "name": L("How to count days between two dates", "怎么数两个日期之间的天数", "怎麼數兩個日期之間的天數", "二つの日付の日数の数え方", "두 날짜 사이 일수 세는 법", "Cách đếm số ngày giữa hai ngày", "Cara hitung hari di antara dua tanggal", "Cómo contar los días entre dos fechas"),
            "blurb": L("The signed difference does not include both ends. Monday 5 January 2026 to Friday 9 January is 4 days. The same span is 5 business days on the other page.", "有符号的日差不把两头都算进去。2026 年 1 月 5 日周一到 1 月 9 日周五是 4 天。同一段在工作日那一页是 5 个工作日。", "有符號的日差不把兩頭都算進去。2026 年 1 月 5 日週一到 1 月 9 日週五是 4 天。同一段在工作日那一頁是 5 個工作日。", "符号付きの日数差は両端を含まない。2026年1月5日月曜から1月9日金曜は 4 日。同じ期間は営業日のページでは 5。", "부호 있는 일수 차이는 양쪽을 포함하지 않습니다. 2026년 1월 5일 월요일부터 1월 9일 금요일은 4일입니다. 같은 구간은 근무일 페이지에서 5일입니다.", "Hiệu có dấu không tính cả hai đầu. Thứ Hai 5/1/2026 đến thứ Sáu 9/1 là 4 ngày. Cùng khoảng đó ở trang ngày làm việc là 5.", "Selisih bertanda tidak mencakup kedua ujung. Senin 5 Januari 2026 sampai Jumat 9 Januari adalah 4 hari. Rentang yang sama di halaman hari kerja adalah 5.", "La diferencia con signo no incluye ambos extremos. Del lunes 5 de enero de 2026 al viernes 9 de enero hay 4 días. El mismo tramo son 5 días laborables en la otra página."),
            "title": L("How to count days between two dates", "怎么数两个日期之间的天数", "怎麼數兩個日期之間的天數", "二つの日付の日数の数え方", "두 날짜 사이 일수 세는 법", "Cách đếm số ngày giữa hai ngày", "Cara hitung hari di antara dua tanggal", "Cómo contar los días entre dos fechas"),
            "lead": L("You need the calendar gap, not the weekday count. You will pick two civil dates in this tab. The same day is 0. Monday through Friday of one week is 4, because Friday is four midnights after Monday.", "你要的是日历间隔，不是工作日个数。在当前标签页选两个公历日期。同一天是 0。一周里的周一到周五是 4，因为周五在周一之后四个午夜。", "你要的是日曆間隔，不是工作日個數。在目前分頁選兩個公曆日期。同一天是 0。一週裡的週一到週五是 4，因為週五在週一之後四個午夜。", "欲しいのは暦の間隔であり平日の個数ではない。このタブで二つの暦日を選ぶ。同じ日は 0。一週間の月曜から金曜は 4。金曜は月曜の四半夜後。", "필요한 것은 달력 간격이지 근무일 개수가 아닙니다. 이 탭에서 두 민법 날짜를 고르세요. 같은 날은 0입니다. 한 주의 월요일부터 금요일은 4입니다. 금요일이 월요일에서 자정 네 번 뒤이기 때문입니다.", "Bạn cần khoảng lịch, không phải số ngày làm việc. Chọn hai ngày dương lịch trong tab này. Cùng một ngày là 0. Thứ Hai đến thứ Sáu một tuần là 4, vì thứ Sáu cách thứ Hai bốn nửa đêm.", "Anda perlu jarak kalender, bukan jumlah hari kerja. Pilih dua tanggal sipil di tab ini. Hari yang sama adalah 0. Senin sampai Jumat dalam satu minggu adalah 4, karena Jumat empat tengah malam setelah Senin.", "Necesita el hueco del calendario, no el conteo de días laborables. Elija dos fechas civiles aquí. El mismo día es 0. De lunes a viernes de una semana hay 4, porque el viernes está cuatro medianoches después del lunes."),
            "result": L("A signed day count, the absolute days, and the whole weeks left after dropping leftover days.", "一个有符号的天数、绝对天数，以及丢掉零头之后的整周数。", "一個有符號的天數、絕對天數，以及丟掉零頭之後的整週數。", "符号付き日数、絶対日数、余りを落とした後の整週。", "부호 있는 일수, 절대 일수, 그리고 나머지를 버린 뒤의 온전한 주.", "Số ngày có dấu, số ngày tuyệt đối, và số tuần tròn sau khi bỏ ngày lẻ.", "Jumlah hari bertanda, hari absolut, dan minggu utuh setelah sisa hari dibuang.", "Un conteo con signo, los días absolutos y las semanas enteras tras quitar los días que sobran."),
            "note": L("Open days between dates when you have two YYYY-MM-DD dates. This page does not skip weekends. Nothing is uploaded.", "有两个 YYYY-MM-DD 日期再打开日期间隔。这一页不去掉周末。不上传。", "有兩個 YYYY-MM-DD 日期再開日期間隔。這一頁不去掉週末。不上傳。", "YYYY-MM-DD が二つ分かってから開く。このページは週末を除かない。アップロードなし。", "YYYY-MM-DD 날짜 둘이 있을 때 일수 계산을 여세요. 이 페이지는 주말을 빼지 않습니다. 업로드 없음.", "Có hai ngày YYYY-MM-DD thì mở số ngày. Trang này không bỏ cuối tuần. Không tải lên.", "Punya dua tanggal YYYY-MM-DD, baru buka selisih hari. Halaman ini tidak melewatkan akhir pekan. Tidak diunggah.", "Abra los días entre fechas cuando tenga dos fechas YYYY-MM-DD. Esta página no salta los fines de semana. Nada se sube."),
            "s1t": L("Decide gap or inclusive count", "先定是间隔还是两头都算", "先定是間隔還是兩頭都算", "間隔か両端含むかを決める", "간격인지 양쪽 포함인지 정하기", "Quyết khoảng cách hay tính cả hai đầu", "Tentukan jarak atau hitungan inklusif", "Decida si es un hueco o un conteo inclusivo"),
            "s1b": L("A hotel night from Monday to Friday is 4. A form that says “including both dates” wants 5. This page is the 4. The business-day page is a different count: it includes both ends and skips Saturday and Sunday.", "周一住到周五是 4 个晚上。表单写「含起止两天」要的是 5。这一页是 4。工作日那一页是另一种数法：两头都算，并且去掉周六和周日。", "週一住到週五是 4 個晚上。表單寫「含起止兩天」要的是 5。這一頁是 4。工作日那一頁是另一種數法：兩頭都算，並且去掉週六和週日。", "月曜から金曜の宿泊は 4 泊。「両端を含む」書類は 5。このページは 4。営業日のページは別の数え方で、両端を含み土曜と日曜を除く。", "월요일부터 금요일까지 숙박은 4박. 「양쪽 포함」이라고 쓴 서류는 5를 원합니다. 이 페이지는 4입니다. 근무일 페이지는 다른 셈법으로, 양쪽을 포함하고 토요일과 일요일을 뺍니다.", "Ở từ thứ Hai đến thứ Sáu là 4 đêm. Biểu mẫu ghi «tính cả hai đầu» muốn 5. Trang này là 4. Trang ngày làm việc là cách đếm khác: tính cả hai đầu và bỏ thứ Bảy, Chủ nhật.", "Menginap Senin sampai Jumat adalah 4 malam. Formulir yang menulis «termasuk kedua tanggal» menginginkan 5. Halaman ini adalah 4. Halaman hari kerja menghitung lain: mencakup kedua ujung dan melewatkan Sabtu serta Minggu.", "Una noche de hotel de lunes a viernes son 4. Un formulario que dice «incluidas ambas fechas» quiere 5. Esta página es el 4. La de días laborables cuenta de otro modo: incluye ambos extremos y salta sábado y domingo."),
            "s2t": L("Open days between dates on cv.cm", "打开 cv.cm 的日期间隔", "打開 cv.cm 的日期間隔", "cv.cmの日数差を開く", "cv.cm 일수 계산을 열기", "Mở số ngày trên cv.cm", "Buka selisih hari di cv.cm", "Abra los días entre fechas en cv.cm"),
            "s2b": L("The count stays in this tab.", "计算留在当前标签页。", "計算留在目前分頁。", "計算はこのタブ。", "계산은 이 탭에서.", "Tính trong tab này.", "Hitungan di tab ini.", "La cuenta queda en esta pestaña."),
            "s3t": L("Pick the start and the end", "选开始和结束", "選開始和結束", "開始と終了を選ぶ", "시작과 끝 고르기", "Chọn ngày đầu và ngày cuối", "Pilih awal dan akhir", "Elija el inicio y el fin"),
            "s3b": L("Use calendar dates, not clock times. If the end is before the start, the signed count is negative. The absolute line stays zero or positive.", "用日历日期，不用钟点。结束早于开始，有符号的天数是负的。绝对天数仍是零或正数。", "用日曆日期，不用鐘點。結束早於開始，有符號的天數是負的。絕對天數仍是零或正數。", "暦日を使う。時刻は使わない。終了が開始より前なら符号付き日数は負。絶対日数は 0 か正。", "달력 날짜를 쓰세요. 시계 시각은 쓰지 마세요. 끝이 시작보다 앞이면 부호 있는 일수는 음수입니다. 절대 일수는 0이거나 양수입니다.", "Dùng ngày lịch, không dùng giờ đồng hồ. Ngày cuối trước ngày đầu thì số có dấu là âm. Số tuyệt đối vẫn là 0 hoặc dương.", "Pakai tanggal kalender, bukan jam. Jika akhir sebelum awal, hitungan bertanda negatif. Baris absolut tetap nol atau positif.", "Use fechas de calendario, no horas de reloj. Si el fin es anterior al inicio, el conteo con signo es negativo. La línea absoluta sigue en cero o positiva."),
            "s4t": L("Read signed days, absolute days, and whole weeks", "看有符号天数、绝对天数和整周", "看有符號天數、絕對天數和整週", "符号付き・絶対・整週を読む", "부호 있는 일수, 절대 일수, 온전한 주 읽기", "Đọc ngày có dấu, ngày tuyệt đối và tuần tròn", "Baca hari bertanda, absolut, dan minggu utuh", "Lea días con signo, absolutos y semanas enteras"),
            "s4b": L("Whole weeks drop the leftover. 10 days is 1 whole week. 4 days is 0 whole weeks. Copy all three lines, then use the one the form named.", "整周丢掉零头。10 天是 1 个整周。4 天是 0 个整周。三行都复制，再用表单点名的那一行。", "整週丟掉零頭。10 天是 1 個整週。4 天是 0 個整週。三行都複製，再用表單點名的那一行。", "整週は余りを落とす。10 日は 1 週。4 日は 0 週。三行をコピーし、書類が名指しした行を使う。", "온전한 주는 나머지를 버립니다. 10일은 1주. 4일은 0주. 세 줄을 복사한 뒤 서류가 지목한 줄을 쓰세요.", "Tuần tròn bỏ ngày lẻ. 10 ngày là 1 tuần tròn. 4 ngày là 0 tuần tròn. Copy cả ba dòng, rồi dùng dòng biểu mẫu chỉ.", "Minggu utuh membuang sisa. 10 hari adalah 1 minggu utuh. 4 hari adalah 0 minggu utuh. Salin ketiga baris, lalu pakai yang disebut formulir.", "Las semanas enteras tiran el resto. 10 días son 1 semana entera. 4 días son 0 semanas enteras. Copie las tres líneas y use la que nombró el formulario."),
            "s5t": L("Count the leap day when it sits in the gap", "闰日落在间隔里就要算上", "閏日落在間隔裡就要算上", "うるう日が間隔にあれば数える", "윤일이 간격 안에 있으면 세기", "Ngày nhuận nằm trong khoảng thì phải tính", "Hitung hari kabisat jika ada di dalam jarak", "Cuente el día bisiesto si cae en el hueco"),
            "s5b": L("28 February 2024 to 1 March 2024 is 2 days, because 29 February is in the gap. 28 February 2023 to 1 March 2023 is 1 day.", "2024 年 2 月 28 日到 3 月 1 日是 2 天，因为 2 月 29 日在间隔里。2023 年 2 月 28 日到 3 月 1 日是 1 天。", "2024 年 2 月 28 日到 3 月 1 日是 2 天，因為 2 月 29 日在間隔裡。2023 年 2 月 28 日到 3 月 1 日是 1 天。", "2024年2月28日から3月1日は 2 日。2月29日が間隔にある。2023年2月28日から3月1日は 1 日。", "2024년 2월 28일부터 3월 1일은 2일입니다. 2월 29일이 간격 안에 있습니다. 2023년 2월 28일부터 3월 1일은 1일입니다.", "28/2/2024 đến 1/3/2024 là 2 ngày, vì 29/2 nằm trong khoảng. 28/2/2023 đến 1/3/2023 là 1 ngày.", "28 Februari 2024 sampai 1 Maret 2024 adalah 2 hari, karena 29 Februari ada di dalam jarak. 28 Februari 2023 sampai 1 Maret 2023 adalah 1 hari.", "Del 28 de febrero de 2024 al 1 de marzo de 2024 hay 2 días, porque el 29 de febrero está en el hueco. Del 28 de febrero de 2023 al 1 de marzo de 2023 hay 1 día."),
            "s6t": L("Leave weekends in this count", "周末留在这个计数里", "週末留在這個計數裡", "週末はこの数に残す", "주말은 이 세에 남기기", "Để cuối tuần trong số đếm này", "Biarkan akhir pekan di hitungan ini", "Deje los fines de semana en este conteo"),
            "s6b": L("Saturday and Sunday are ordinary calendar days here. If the form wants Monday through Friday only, use the business-day page and remember that page includes both ends.", "周六和周日在这里是普通日历日。表单只要周一到周五，就用工作日那一页，并且记住那一页两头都算。", "週六和週日在這裡是普通日曆日。表單只要週一到週五，就用工作日那一頁，並且記住那一頁兩頭都算。", "土曜と日曜はここでは普通の暦日。月曜から金曜だけなら営業日のページを使い、そちらは両端を含むと覚える。", "토요일과 일요일은 여기서 보통 달력 일입니다. 서류가 월~금만 원하면 근무일 페이지를 쓰고, 그 페이지는 양쪽을 포함한다는 점을 기억하세요.", "Thứ Bảy và Chủ nhật ở đây là ngày lịch thường. Biểu mẫu chỉ muốn thứ Hai đến thứ Sáu thì dùng trang ngày làm việc, và nhớ trang đó tính cả hai đầu.", "Sabtu dan Minggu di sini adalah hari kalender biasa. Jika formulir hanya ingin Senin sampai Jumat, pakai halaman hari kerja, dan ingat halaman itu mencakup kedua ujung.", "Sábado y domingo aquí son días de calendario normales. Si el formulario solo quiere de lunes a viernes, use la página de días laborables y recuerde que esa página incluye ambos extremos."),
            "diagram1": L("Mon 5 Jan to Fri 9 Jan 2026 is 4 days. Both ends are not included.", "2026 年 1 月 5 日周一到 9 日周五是 4 天。两头不算进间隔。", "2026 年 1 月 5 日週一到 9 日週五是 4 天。兩頭不算進間隔。", "2026年1月5日月曜〜9日金曜は 4 日。両端は間隔に入らない。", "2026년 1월 5일 월~9일 금은 4일. 양쪽은 간격에 넣지 않습니다.", "Thứ Hai 5/1 đến thứ Sáu 9/1/2026 là 4 ngày. Hai đầu không nằm trong khoảng.", "Senin 5 Jan sampai Jumat 9 Jan 2026 adalah 4 hari. Kedua ujung tidak masuk jarak.", "Del lun 5 al vie 9 de enero de 2026 hay 4 días. Los extremos no entran en el hueco."),
            "diagram2": L("28 Feb 2024 to 1 Mar 2024 is 2 days. The leap day is in the gap.", "2024 年 2 月 28 日到 3 月 1 日是 2 天。闰日在间隔里。", "2024 年 2 月 28 日到 3 月 1 日是 2 天。閏日在間隔裡。", "2024年2月28日〜3月1日は 2 日。うるう日が間隔にある。", "2024년 2월 28일~3월 1일은 2일. 윤일이 간격 안에 있습니다.", "28/2/2024 đến 1/3/2024 là 2 ngày. Ngày nhuận nằm trong khoảng.", "28 Feb 2024 sampai 1 Mar 2024 adalah 2 hari. Hari kabisat ada di dalam jarak.", "Del 28 feb 2024 al 1 mar 2024 hay 2 días. El bisiesto está en el hueco."),
        },
        {
            "q1": L("Can I count days between two dates free online?", "可以免费在线数两个日期之间的天数吗？", "可以免費線上數兩個日期之間的天數嗎？", "二つの日付の日数を無料で数えられる？", "두 날짜 사이 일수를 무료로 셀 수 있나요?", "Đếm số ngày giữa hai ngày miễn phí online được không?", "Bisa hitung hari di antara dua tanggal gratis online?", "¿Puedo contar los días entre dos fechas gratis en línea?"),
            "a1": L("Yes. cv.cm shows the signed days, the absolute days, and whole weeks in this tab. Nothing is uploaded.", "可以。cv.cm 在当前标签页显示有符号天数、绝对天数和整周。不上传。", "可以。cv.cm 在目前分頁顯示有符號天數、絕對天數和整週。不上傳。", "できる。このタブで符号付き日数・絶対日数・整週を出す。アップロードなし。", "됩니다. 이 탭에서 부호 있는 일수, 절대 일수, 온전한 주를 보여 줍니다. 업로드 없음.", "Được. Hiện ngày có dấu, ngày tuyệt đối và tuần tròn trong tab này. Không tải lên.", "Ya. Menampilkan hari bertanda, hari absolut, dan minggu utuh di tab ini. Tidak diunggah.", "Sí. Muestra los días con signo, los absolutos y las semanas enteras en esta pestaña. Nada se sube."),
            "q2": L("Does the count include both dates?", "两头都算吗？", "兩頭都算嗎？", "両端を含む？", "양쪽 날짜를 포함하나요?", "Có tính cả hai đầu không?", "Apakah kedua tanggal dihitung?", "¿El conteo incluye ambas fechas?"),
            "a2": L("No. The same day is 0. Monday 5 January 2026 to Friday 9 January is 4. A form that includes both dates wants 5.", "不算。同一天是 0。2026 年 1 月 5 日周一到 1 月 9 日周五是 4。表单要含起止两天，那是 5。", "不算。同一天是 0。2026 年 1 月 5 日週一到 1 月 9 日週五是 4。表單要含起止兩天，那是 5。", "含まない。同じ日は 0。2026年1月5日月曜から1月9日金曜は 4。両端を含む書類は 5。", "포함하지 않습니다. 같은 날은 0입니다. 2026년 1월 5일 월요일부터 1월 9일 금요일은 4일입니다. 양쪽을 포함하는 서류는 5를 원합니다.", "Không. Cùng một ngày là 0. Thứ Hai 5/1/2026 đến thứ Sáu 9/1 là 4. Biểu mẫu tính cả hai đầu muốn 5.", "Tidak. Hari yang sama adalah 0. Senin 5 Januari 2026 sampai Jumat 9 Januari adalah 4. Formulir yang mencakup kedua tanggal menginginkan 5.", "No. El mismo día es 0. Del lunes 5 de enero de 2026 al viernes 9 de enero hay 4. Un formulario que incluye ambas fechas quiere 5."),
            "q3": L("Is this the business-day count?", "这是工作日计数吗？", "這是工作日計數嗎？", "営業日の数え方？", "근무일 계산인가요?", "Đây có phải đếm ngày làm việc?", "Apakah ini hitungan hari kerja?", "¿Es el conteo de días laborables?"),
            "a3": L("No. Weekends stay in this count. The business-day page skips Saturday and Sunday and includes both ends.", "不是。周末留在这个计数里。工作日那一页去掉周六和周日，并且两头都算。", "不是。週末留在這個計數裡。工作日那一頁去掉週六和週日，並且兩頭都算。", "違う。週末はこの数に残る。営業日のページは土曜と日曜を除き、両端を含む。", "아니요. 주말은 이 세에 남습니다. 근무일 페이지는 토요일과 일요일을 빼고 양쪽을 포함합니다.", "Không. Cuối tuần vẫn trong số này. Trang ngày làm việc bỏ thứ Bảy, Chủ nhật và tính cả hai đầu.", "Tidak. Akhir pekan tetap di hitungan ini. Halaman hari kerja melewatkan Sabtu dan Minggu serta mencakup kedua ujung.", "No. Los fines de semana siguen en este conteo. La página de días laborables salta sábado y domingo e incluye ambos extremos."),
            "q4": L("Do leap days count?", "闰日算吗？", "閏日算嗎？", "うるう日は数える？", "윤일을 세나요?", "Ngày nhuận có tính không?", "Apakah hari kabisat dihitung?", "¿Se cuentan los días bisiestos?"),
            "a4": L("Yes, when the leap day sits in the gap. 28 February 2024 to 1 March 2024 is 2 days.", "算，只要闰日在间隔里。2024 年 2 月 28 日到 3 月 1 日是 2 天。", "算，只要閏日在間隔裡。2024 年 2 月 28 日到 3 月 1 日是 2 天。", "間隔にあれば数える。2024年2月28日から3月1日は 2 日。", "윤일이 간격 안에 있으면 셉니다. 2024년 2월 28일부터 3월 1일은 2일입니다.", "Có, khi ngày nhuận nằm trong khoảng. 28/2/2024 đến 1/3/2024 là 2 ngày.", "Ya, jika hari kabisat ada di dalam jarak. 28 Februari 2024 sampai 1 Maret 2024 adalah 2 hari.", "Sí, cuando el bisiesto está en el hueco. Del 28 de febrero de 2024 al 1 de marzo de 2024 hay 2 días."),
            "q5": L("Is this uploaded?", "会上传吗？", "會上傳嗎？", "アップロードされる？", "업로드되나요?", "Có bị tải lên không?", "Apakah diunggah?", "¿Se sube?"),
            "a5": L("No. Closing the tab discards it.", "不会。关掉标签页就没了。", "不會。關掉分頁就沒了。", "しない。タブを閉じると消える。", "아니요. 탭을 닫으면 사라집니다.", "Không. Đóng tab là mất.", "Tidak. Tutup tab, hilang.", "No. Al cerrar la pestaña se pierde."),
        },
    ),
    "shift-date": lesson(
        {
            "name": L("How to add days to a date", "怎么给日期加减天数", "怎麼給日期加減天數", "日付に日数を足す方法", "날짜에 일수 더하는 법", "Cách cộng ngày vào một ngày", "Cara tambah hari ke tanggal", "Cómo sumar días a una fecha"),
            "blurb": L("Add a whole number of calendar days. 28 February 2024 plus 1 is 29 February 2024. A fraction of a day fails. Friday plus 1 is Saturday.", "加上整数个日历日。2024 年 2 月 28 日加 1 是 2024 年 2 月 29 日。不满一天的小数会失败。周五加 1 是周六。", "加上整數個日曆日。2024 年 2 月 28 日加 1 是 2024 年 2 月 29 日。不滿一天的小數會失敗。週五加 1 是週六。", "整数の暦日を足す。2024年2月28日に 1 を足すと 2024年2月29日。端数の日は失敗。金曜に 1 を足すと土曜。", "정수 달력 일을 더합니다. 2024년 2월 28일에 1을 더하면 2024년 2월 29일. 하루의 소수부는 실패합니다. 금요일에 1을 더하면 토요일.", "Cộng một số nguyên ngày lịch. 28/2/2024 cộng 1 là 29/2/2024. Phần lẻ của một ngày thì thất bại. Thứ Sáu cộng 1 là thứ Bảy.", "Tambahkan bilangan bulat hari kalender. 28 Februari 2024 ditambah 1 adalah 29 Februari 2024. Pecahan hari gagal. Jumat ditambah 1 adalah Sabtu.", "Sume un número entero de días de calendario. El 28 de febrero de 2024 más 1 es el 29 de febrero de 2024. Una fracción de día falla. Viernes más 1 es sábado."),
            "title": L("How to add days to a date", "怎么给日期加减天数", "怎麼給日期加減天數", "日付に日数を足す方法", "날짜에 일수 더하는 법", "Cách cộng ngày vào một ngày", "Cara tambah hari ke tanggal", "Cómo sumar días a una fecha"),
            "lead": L("You have a calendar date and a whole number of days. You will shift that date in this tab. Negative numbers go backward. The shift does not skip Saturday or Sunday.", "你有一个日历日期和一个整数天数。在当前标签页把日期挪过去。负数往回走。这个挪动不会跳过周六或周日。", "你有一個日曆日期和一個整數天數。在目前分頁把日期挪過去。負數往回走。這個挪動不會跳過週六或週日。", "暦日と整数の日数がある。このタブで日付を動かす。負の数は戻る。土曜も日曜も飛ばさない。", "달력 날짜와 정수 일수가 있습니다. 이 탭에서 날짜를 옮기세요. 음수는 뒤로 갑니다. 토요일이나 일요일을 건너뛰지 않습니다.", "Bạn có một ngày lịch và một số nguyên ngày. Dời ngày đó trong tab này. Số âm đi ngược. Việc dời không bỏ thứ Bảy hay Chủ nhật.", "Anda punya tanggal kalender dan jumlah hari bulat. Geser tanggal itu di tab ini. Angka negatif berjalan mundur. Geseran tidak melewatkan Sabtu atau Minggu.", "Tiene una fecha de calendario y un número entero de días. Desplace esa fecha aquí. Los números negativos van hacia atrás. El desplazamiento no salta sábado ni domingo."),
            "result": L("One new civil date, YYYY-MM-DD, after a whole number of calendar days.", "一个新的公历日期，YYYY-MM-DD，经过整数个日历日之后。", "一個新的公曆日期，YYYY-MM-DD，經過整數個日曆日之後。", "整数の暦日を経たあとの新しい暦日。YYYY-MM-DD。", "정수 달력 일 뒤의 새 민법 날짜, YYYY-MM-DD.", "Một ngày dương lịch mới, YYYY-MM-DD, sau một số nguyên ngày lịch.", "Satu tanggal sipil baru, YYYY-MM-DD, setelah sejumlah hari kalender bulat.", "Una fecha civil nueva, YYYY-MM-DD, después de un número entero de días de calendario."),
            "note": L("Open add days when the start date and the whole number are known. 1.5 days fails. Nothing is uploaded.", "开始日期和整数天数都清楚再打开日期加减。1.5 天会失败。不上传。", "開始日期和整數天數都清楚再開日期加減。1.5 天會失敗。不上傳。", "開始日と整数の日数が分かってから開く。1.5 日は失敗。アップロードなし。", "시작 날짜와 정수 일수를 알 때 날짜 가감을 여세요. 1.5일은 실패합니다. 업로드 없음.", "Biết ngày bắt đầu và số nguyên thì mở cộng ngày. 1,5 ngày thì thất bại. Không tải lên.", "Tahu tanggal awal dan bilangan bulat, baru buka tambah hari. 1,5 hari gagal. Tidak diunggah.", "Abra sumar días cuando sepa la fecha inicial y el número entero. 1,5 días falla. Nada se sube."),
            "s1t": L("Use a whole number of days", "用整数天数", "用整數天數", "整数の日数を使う", "정수 일수 쓰기", "Dùng số nguyên ngày", "Pakai jumlah hari bulat", "Use un número entero de días"),
            "s1b": L("1 moves one calendar day. 1.5 is rejected. A negative number walks backward. This is not a business-day skip.", "1 是挪一个日历日。1.5 会被拒绝。负数往回走。这不是跳过工作日。", "1 是挪一個日曆日。1.5 會被拒絕。負數往回走。這不是跳過工作日。", "1 は暦日を一つ動かす。1.5 は拒否。負の数は戻る。営業日を飛ばす操作ではない。", "1은 달력 하루를 옮깁니다. 1.5는 거부됩니다. 음수는 뒤로 갑니다. 근무일을 건너뛰는 일이 아닙니다.", "1 dời một ngày lịch. 1,5 bị từ chối. Số âm đi ngược. Đây không phải bỏ ngày làm việc.", "1 menggeser satu hari kalender. 1,5 ditolak. Angka negatif berjalan mundur. Ini bukan melewatkan hari kerja.", "1 mueve un día de calendario. 1,5 se rechaza. Un número negativo camina hacia atrás. Esto no es saltar días laborables."),
            "s2t": L("Open add days on cv.cm", "打开 cv.cm 的日期加减", "打開 cv.cm 的日期加減", "cv.cmの日付加算を開く", "cv.cm 날짜 가감을 열기", "Mở cộng ngày trên cv.cm", "Buka tambah hari di cv.cm", "Abra sumar días en cv.cm"),
            "s2b": L("The shift stays in this tab.", "挪动留在当前标签页。", "挪動留在目前分頁。", "移動はこのタブ。", "이동은 이 탭에서.", "Việc dời ở trong tab này.", "Geseran di tab ini.", "El desplazamiento queda en esta pestaña."),
            "s3t": L("Enter the start date", "填开始日期", "填開始日期", "開始日を入れる", "시작 날짜 넣기", "Nhập ngày bắt đầu", "Isi tanggal awal", "Escriba la fecha inicial"),
            "s3b": L("Use a real civil date. 31 January plus 1 day is 1 February. The month length is already in the calendar.", "用真实的公历日期。1 月 31 日加 1 天是 2 月 1 日。月份的长短已经在日历里。", "用真實的公曆日期。1 月 31 日加 1 天是 2 月 1 日。月份的長短已經在日曆裡。", "実在する暦日を使う。1月31日に 1 日足すと 2月1日。月の長さは暦に入っている。", "실제 민법 날짜를 쓰세요. 1월 31일에 1일을 더하면 2월 1일. 달의 길이는 이미 달력에 있습니다.", "Dùng ngày dương lịch thật. 31/1 cộng 1 ngày là 1/2. Độ dài tháng đã nằm trong lịch.", "Pakai tanggal sipil yang nyata. 31 Januari ditambah 1 hari adalah 1 Februari. Panjang bulan sudah ada di kalender.", "Use una fecha civil real. El 31 de enero más 1 día es el 1 de febrero. La longitud del mes ya está en el calendario."),
            "s4t": L("Let the leap day appear when the year has one", "这一年有闰日，就让它出现", "這一年有閏日，就讓它出現", "その年にうるう日があれば出す", "그해에 윤일이 있으면 나타나게 하기", "Năm có ngày nhuận thì để nó xuất hiện", "Biarkan hari kabisat muncul jika tahun memilikinya", "Deje aparecer el bisiesto si el año lo tiene"),
            "s4b": L("28 February 2024 plus 1 day is 29 February 2024. 28 February 2023 plus 1 day is 1 March 2023.", "2024 年 2 月 28 日加 1 天是 2024 年 2 月 29 日。2023 年 2 月 28 日加 1 天是 2023 年 3 月 1 日。", "2024 年 2 月 28 日加 1 天是 2024 年 2 月 29 日。2023 年 2 月 28 日加 1 天是 2023 年 3 月 1 日。", "2024年2月28日に 1 日足すと 2024年2月29日。2023年2月28日に 1 日足すと 2023年3月1日。", "2024년 2월 28일에 1일을 더하면 2024년 2월 29일. 2023년 2월 28일에 1일을 더하면 2023년 3월 1일.", "28/2/2024 cộng 1 ngày là 29/2/2024. 28/2/2023 cộng 1 ngày là 1/3/2023.", "28 Februari 2024 ditambah 1 hari adalah 29 Februari 2024. 28 Februari 2023 ditambah 1 hari adalah 1 Maret 2023.", "El 28 de febrero de 2024 más 1 día es el 29 de febrero de 2024. El 28 de febrero de 2023 más 1 día es el 1 de marzo de 2023."),
            "s5t": L("Read the new date before you copy it", "复制前先看新日期", "複製前先看新日期", "コピー前に新しい日付を読む", "복사하기 전에 새 날짜 읽기", "Đọc ngày mới trước khi copy", "Baca tanggal baru sebelum menyalin", "Lea la fecha nueva antes de copiarla"),
            "s5b": L("Copy puts that YYYY-MM-DD on the clipboard. Check the year when the shift crosses 31 December.", "复制把那个 YYYY-MM-DD 放进剪贴板。跨过 12 月 31 日时，核对年份。", "複製把那個 YYYY-MM-DD 放進剪貼簿。跨過 12 月 31 日時，核對年份。", "コピーはその YYYY-MM-DD をクリップボードへ。12月31日をまたぐときは年を照合する。", "복사는 그 YYYY-MM-DD를 클립보드에 넣습니다. 12월 31일을 넘을 때 연도를 대조하세요.", "Copy đưa YYYY-MM-DD đó vào clipboard. Khi dời qua 31/12, hãy đối chiếu năm.", "Salin menaruh YYYY-MM-DD itu di papan klip. Saat geseran melewati 31 Desember, cek tahunnya.", "Copiar pone ese YYYY-MM-DD en el portapapeles. Cuando el desplazamiento cruza el 31 de diciembre, compruebe el año."),
            "s6t": L("Friday plus 1 is Saturday", "周五加 1 是周六", "週五加 1 是週六", "金曜に 1 を足すと土曜", "금요일 더하기 1은 토요일", "Thứ Sáu cộng 1 là thứ Bảy", "Jumat ditambah 1 adalah Sabtu", "Viernes más 1 es sábado"),
            "s6b": L("This page does not skip the weekend. If the form wants the next Monday after a Friday, add 3, or use the business-day page for a count that skips Saturday and Sunday.", "这一页不跳过周末。表单要周五之后的下周一，就加 3，或者用工作日那一页，那边的计数会去掉周六和周日。", "這一頁不跳過週末。表單要週五之後的下週一，就加 3，或者用工作日那一頁，那邊的計數會去掉週六和週日。", "このページは週末を飛ばさない。金曜の次の月曜が要るなら 3 を足す。土曜と日曜を除く数え方は営業日のページ。", "이 페이지는 주말을 건너뛰지 않습니다. 서류가 금요일 다음 월요일을 원하면 3을 더하거나, 토요일과 일요일을 빼는 근무일 페이지를 쓰세요.", "Trang này không bỏ cuối tuần. Biểu mẫu muốn thứ Hai sau thứ Sáu thì cộng 3, hoặc dùng trang ngày làm việc, nơi số đếm bỏ thứ Bảy và Chủ nhật.", "Halaman ini tidak melewatkan akhir pekan. Jika formulir ingin Senin setelah Jumat, tambah 3, atau pakai halaman hari kerja, yang hitungannya melewatkan Sabtu dan Minggu.", "Esta página no salta el fin de semana. Si el formulario quiere el lunes siguiente a un viernes, sume 3, o use la página de días laborables, cuyo conteo salta sábado y domingo."),
            "diagram1": L("28 Feb 2024 + 1 = 29 Feb 2024. 28 Feb 2023 + 1 = 1 Mar 2023.", "2024-02-28 + 1 = 2024-02-29。2023-02-28 + 1 = 2023-03-01。", "2024-02-28 + 1 = 2024-02-29。2023-02-28 + 1 = 2023-03-01。", "2024-02-28 + 1 = 2024-02-29。2023-02-28 + 1 = 2023-03-01。", "2024-02-28 + 1 = 2024-02-29. 2023-02-28 + 1 = 2023-03-01.", "2024-02-28 + 1 = 2024-02-29. 2023-02-28 + 1 = 2023-03-01.", "2024-02-28 + 1 = 2024-02-29. 2023-02-28 + 1 = 2023-03-01.", "2024-02-28 + 1 = 2024-02-29. 2023-02-28 + 1 = 2023-03-01."),
            "diagram2": L("A whole number only. Friday + 1 is Saturday.", "只要整数。周五加 1 是周六。", "只要整數。週五加 1 是週六。", "整数だけ。金曜 + 1 は土曜。", "정수만. 금요일 + 1은 토요일.", "Chỉ số nguyên. Thứ Sáu + 1 là thứ Bảy.", "Hanya bilangan bulat. Jumat + 1 adalah Sabtu.", "Solo un entero. Viernes + 1 es sábado."),
        },
        {
            "q1": L("Can I add days to a date free online?", "可以免费在线给日期加减天数吗？", "可以免費線上給日期加減天數嗎？", "日付に日数を無料で足せる？", "날짜에 일수를 무료로 더할 수 있나요?", "Cộng ngày vào một ngày miễn phí online được không?", "Bisa tambah hari ke tanggal gratis online?", "¿Puedo sumar días a una fecha gratis en línea?"),
            "a1": L("Yes. cv.cm shifts a civil date by a whole number of days in this tab. Nothing is uploaded.", "可以。cv.cm 在当前标签页把公历日期按整数天挪动。不上传。", "可以。cv.cm 在目前分頁把公曆日期按整數天挪動。不上傳。", "できる。このタブで暦日を整数日動かす。アップロードなし。", "됩니다. 이 탭에서 민법 날짜를 정수 일만큼 옮깁니다. 업로드 없음.", "Được. Dời ngày dương lịch một số nguyên ngày trong tab này. Không tải lên.", "Ya. Menggeser tanggal sipil sejumlah hari bulat di tab ini. Tidak diunggah.", "Sí. Desplaza una fecha civil un número entero de días en esta pestaña. Nada se sube."),
            "q2": L("Can the number be negative or a fraction?", "天数可以是负数或小数吗？", "天數可以是負數或小數嗎？", "負の数や端数は使える？", "음수나 소수도 되나요?", "Số ngày có thể âm hoặc lẻ không?", "Boleh negatif atau pecahan?", "¿El número puede ser negativo o una fracción?"),
            "a2": L("Negative numbers go backward. 1.5 is rejected. Only a whole number of days works.", "负数往回走。1.5 会被拒绝。只有整数天可以。", "負數往回走。1.5 會被拒絕。只有整數天可以。", "負の数は戻る。1.5 は拒否。整数の日数だけ。", "음수는 뒤로 갑니다. 1.5는 거부됩니다. 정수 일수만 됩니다.", "Số âm đi ngược. 1,5 bị từ chối. Chỉ số nguyên ngày mới được.", "Angka negatif berjalan mundur. 1,5 ditolak. Hanya jumlah hari bulat yang jalan.", "Los negativos van hacia atrás. 1,5 se rechaza. Solo funciona un número entero de días."),
            "q3": L("What is 28 February 2024 plus 1 day?", "2024 年 2 月 28 日加 1 天是哪天？", "2024 年 2 月 28 日加 1 天是哪天？", "2024年2月28日に 1 日足すと？", "2024년 2월 28일에 1일을 더하면?", "28/2/2024 cộng 1 ngày là ngày nào?", "28 Februari 2024 ditambah 1 hari tanggal berapa?", "¿Qué día es el 28 de febrero de 2024 más 1 día?"),
            "a3": L("29 February 2024. In 2023 the same step lands on 1 March.", "2024 年 2 月 29 日。2023 年同样加 1 天会落到 3 月 1 日。", "2024 年 2 月 29 日。2023 年同樣加 1 天會落到 3 月 1 日。", "2024年2月29日。2023年の同じ一歩は 3月1日。", "2024년 2월 29일. 2023년의 같은 한 걸음은 3월 1일입니다.", "29/2/2024. Năm 2023 cùng một bước rơi vào 1/3.", "29 Februari 2024. Pada 2023 langkah yang sama jatuh pada 1 Maret.", "El 29 de febrero de 2024. En 2023 el mismo paso cae en el 1 de marzo."),
            "q4": L("Does Friday plus 1 skip the weekend?", "周五加 1 会跳过周末吗？", "週五加 1 會跳過週末嗎？", "金曜に 1 を足すと週末を飛ばす？", "금요일에 1을 더하면 주말을 건너뛰나요?", "Thứ Sáu cộng 1 có bỏ cuối tuần không?", "Jumat ditambah 1 melewatkan akhir pekan?", "¿Viernes más 1 salta el fin de semana?"),
            "a4": L("No. Friday plus 1 is Saturday. Add 3 to land on Monday.", "不会。周五加 1 是周六。要落到周一就加 3。", "不會。週五加 1 是週六。要落到週一就加 3。", "飛ばさない。金曜に 1 を足すと土曜。月曜にするなら 3。", "아니요. 금요일 더하기 1은 토요일입니다. 월요일에 닿으려면 3을 더하세요.", "Không. Thứ Sáu cộng 1 là thứ Bảy. Muốn tới thứ Hai thì cộng 3.", "Tidak. Jumat ditambah 1 adalah Sabtu. Tambah 3 untuk sampai Senin.", "No. Viernes más 1 es sábado. Sume 3 para caer en lunes."),
            "q5": L("Is the date uploaded?", "日期会上传吗？", "日期會上傳嗎？", "アップロードされる？", "업로드되나요?", "Ngày có bị tải lên không?", "Apakah tanggal diunggah?", "¿Se sube la fecha?"),
            "a5": L("No. Closing the tab discards it.", "不会。关掉标签页就没了。", "不會。關掉分頁就沒了。", "しない。タブを閉じると消える。", "아니요. 탭을 닫으면 사라집니다.", "Không. Đóng tab là mất.", "Tidak. Tutup tab, hilang.", "No. Al cerrar la pestaña se pierde."),
        },
    ),
    "iso-week": lesson(
        {
            "name": L("How to find the ISO week number", "怎么查 ISO 周数", "怎麼查 ISO 週數", "ISO週番号の調べ方", "ISO 주 번호 찾는 법", "Cách tìm số tuần ISO", "Cara cari nomor minggu ISO", "Cómo hallar el número de semana ISO"),
            "blurb": L("ISO weeks start on Monday. Week 1 contains the year's first Thursday. 1 January 2021 is Friday of 2020-W53.", "ISO 周从周一开始。第 1 周包含这一年的第一个周四。2021 年 1 月 1 日是 2020-W53 的周五。", "ISO 週從週一開始。第 1 週包含這一年的第一個週四。2021 年 1 月 1 日是 2020-W53 的週五。", "ISO 週は月曜始まり。第1週はその年の最初の木曜を含む。2021年1月1日は 2020-W53 の金曜。", "ISO 주는 월요일에 시작합니다. 1주는 그해의 첫 목요일을 포함합니다. 2021년 1월 1일은 2020-W53의 금요일입니다.", "Tuần ISO bắt đầu vào thứ Hai. Tuần 1 chứa thứ Năm đầu tiên của năm. 1/1/2021 là thứ Sáu của 2020-W53.", "Minggu ISO mulai Senin. Minggu 1 memuat Kamis pertama tahun itu. 1 Januari 2021 adalah Jumat dari 2020-W53.", "Las semanas ISO empiezan en lunes. La semana 1 contiene el primer jueves del año. El 1 de enero de 2021 es viernes de 2020-W53."),
            "title": L("How to find the ISO week number", "怎么查 ISO 周数", "怎麼查 ISO 週數", "ISO週番号の調べ方", "ISO 주 번호 찾는 법", "Cách tìm số tuần ISO", "Cara cari nomor minggu ISO", "Cómo hallar el número de semana ISO"),
            "lead": L("You need the ISO week of a civil date. You will read the week label and the weekday in this tab. Monday is 1 and Sunday is 7. A date in late December can belong to next year's week 1.", "你要一个公历日期的 ISO 周。在当前标签页看周标签和星期。周一是 1，周日是 7。十二月下旬的日期可以属于下一年的第 1 周。", "你要一個公曆日期的 ISO 週。在目前分頁看週標籤和星期。週一是 1，週日是 7。十二月下旬的日期可以屬於下一年的第 1 週。", "暦日の ISO 週が欲しい。このタブで週ラベルと曜日を読む。月曜は 1、日曜は 7。12月下旬の日付は翌年の第1週に属し得る。", "민법 날짜의 ISO 주가 필요합니다. 이 탭에서 주 라벨과 요일을 읽으세요. 월요일은 1, 일요일은 7. 12월 말 날짜는 다음 해 1주에 속할 수 있습니다.", "Bạn cần tuần ISO của một ngày dương lịch. Đọc nhãn tuần và thứ trong tab này. Thứ Hai là 1, Chủ nhật là 7. Một ngày cuối tháng Mười Hai có thể thuộc tuần 1 của năm sau.", "Anda perlu minggu ISO dari sebuah tanggal sipil. Baca label minggu dan hari di tab ini. Senin adalah 1 dan Minggu adalah 7. Tanggal akhir Desember bisa masuk minggu 1 tahun berikutnya.", "Necesita la semana ISO de una fecha civil. Lea la etiqueta de la semana y el día aquí. El lunes es 1 y el domingo es 7. Una fecha de finales de diciembre puede pertenecer a la semana 1 del año siguiente."),
            "result": L("An ISO year, a week from 1 to 53, and a weekday from 1 to 7, with the label such as 2020-W53.", "一个 ISO 年、一个 1 到 53 的周，以及一个 1 到 7 的星期，标签像 2020-W53。", "一個 ISO 年、一個 1 到 53 的週，以及一個 1 到 7 的星期，標籤像 2020-W53。", "ISO 年、1 から 53 の週、1 から 7 の曜日。ラベルは 2020-W53 のような形。", "ISO 연도, 1부터 53까지의 주, 1부터 7까지의 요일. 라벨은 2020-W53 같은 형태.", "Một năm ISO, một tuần từ 1 đến 53, và một thứ từ 1 đến 7, nhãn như 2020-W53.", "Satu tahun ISO, satu minggu dari 1 sampai 53, dan satu hari dari 1 sampai 7, dengan label seperti 2020-W53.", "Un año ISO, una semana del 1 al 53 y un día del 1 al 7, con una etiqueta como 2020-W53."),
            "note": L("Open week number when you have a civil date. This is not a week that starts on Sunday. Nothing is uploaded.", "有公历日期再打开周数。这不是从周日开始的周。不上传。", "有公曆日期再開週數。這不是從週日開始的週。不上傳。", "暦日があってから開く。日曜始まりの週ではない。アップロードなし。", "민법 날짜가 있을 때 주 번호를 여세요. 일요일에 시작하는 주가 아닙니다. 업로드 없음.", "Có ngày dương lịch thì mở số tuần. Đây không phải tuần bắt đầu Chủ nhật. Không tải lên.", "Punya tanggal sipil, baru buka nomor minggu. Ini bukan minggu yang mulai Minggu. Tidak diunggah.", "Abra el número de semana cuando tenga una fecha civil. No es una semana que empieza en domingo. Nada se sube."),
            "s1t": L("Use the week that starts on Monday", "用从周一开始的那一周", "用從週一開始的那一週", "月曜始まりの週を使う", "월요일에 시작하는 주를 쓰기", "Dùng tuần bắt đầu thứ Hai", "Pakai minggu yang mulai Senin", "Use la semana que empieza en lunes"),
            "s1b": L("Monday is weekday 1. Sunday is weekday 7. A week number that starts on Sunday is a different system. This page will not produce that number.", "周一是星期 1。周日是星期 7。从周日开始的周数是另一套。这一页不会给出那个数。", "週一是星期 1。週日是星期 7。從週日開始的週數是另一套。這一頁不會給出那個數。", "月曜は曜日 1。日曜は曜日 7。日曜始まりの週番号は別の方式。このページはその番号を出さない。", "월요일은 요일 1. 일요일은 요일 7. 일요일에 시작하는 주 번호는 다른 체계입니다. 이 페이지는 그 번호를 내지 않습니다.", "Thứ Hai là ngày 1. Chủ nhật là ngày 7. Số tuần bắt đầu Chủ nhật là hệ khác. Trang này không ra số đó.", "Senin adalah hari 1. Minggu adalah hari 7. Nomor minggu yang mulai Minggu adalah sistem lain. Halaman ini tidak menghasilkan nomor itu.", "El lunes es el día 1. El domingo es el día 7. Un número de semana que empieza en domingo es otro sistema. Esta página no produce ese número."),
            "s2t": L("Open week number on cv.cm", "打开 cv.cm 的周数", "打開 cv.cm 的週數", "cv.cmの週番号を開く", "cv.cm 주 번호를 열기", "Mở số tuần trên cv.cm", "Buka nomor minggu di cv.cm", "Abra el número de semana en cv.cm"),
            "s2b": L("The week stays in this tab.", "周数留在当前标签页。", "週數留在目前分頁。", "週番号はこのタブ。", "주 번호는 이 탭에서.", "Số tuần ở trong tab này.", "Nomor minggu di tab ini.", "El número de semana queda en esta pestaña."),
            "s3t": L("Pick the civil date", "选公历日期", "選公曆日期", "暦日を選ぶ", "민법 날짜 고르기", "Chọn ngày dương lịch", "Pilih tanggal sipil", "Elija la fecha civil"),
            "s3b": L("The date is YYYY-MM-DD. Clock time does not move the week. 1 January 2026 is Thursday, weekday 4, and it is 2026-W01.", "日期是 YYYY-MM-DD。钟点不会改动这一周。2026 年 1 月 1 日是周四，星期 4，属于 2026-W01。", "日期是 YYYY-MM-DD。鐘點不會改動這一週。2026 年 1 月 1 日是週四，星期 4，屬於 2026-W01。", "日付は YYYY-MM-DD。時刻は週を動かさない。2026年1月1日は木曜、曜日 4、2026-W01。", "날짜는 YYYY-MM-DD. 시계 시각은 주를 옮기지 않습니다. 2026년 1월 1일은 목요일, 요일 4, 2026-W01입니다.", "Ngày là YYYY-MM-DD. Giờ đồng hồ không đổi tuần. 1/1/2026 là thứ Năm, ngày 4, thuộc 2026-W01.", "Tanggalnya YYYY-MM-DD. Jam dinding tidak menggeser minggu. 1 Januari 2026 adalah Kamis, hari 4, dan itu 2026-W01.", "La fecha es YYYY-MM-DD. La hora de reloj no mueve la semana. El 1 de enero de 2026 es jueves, día 4, y es 2026-W01."),
            "s4t": L("Read the ISO year separately from the calendar year", "把 ISO 年和日历年分开读", "把 ISO 年和日曆年分開讀", "ISO 年と暦年を分けて読む", "ISO 연도와 달력 연도를 따로 읽기", "Đọc năm ISO tách khỏi năm lịch", "Baca tahun ISO terpisah dari tahun kalender", "Lea el año ISO aparte del año civil"),
            "s4b": L("Week 1 is the week that contains the year's first Thursday. 1 January 2021 is a Friday, so it stays in 2020-W53. 30 December 2024 is a Monday in 2025-W01.", "第 1 周是包含这一年第一个周四的那一周。2021 年 1 月 1 日是周五，所以它仍在 2020-W53。2024 年 12 月 30 日是周一，属于 2025-W01。", "第 1 週是包含這一年第一個週四的那一週。2021 年 1 月 1 日是週五，所以它仍在 2020-W53。2024 年 12 月 30 日是週一，屬於 2025-W01。", "第1週はその年の最初の木曜を含む週。2021年1月1日は金曜なので 2020-W53 に残る。2024年12月30日は月曜で 2025-W01。", "1주는 그해 첫 목요일이 들어 있는 주입니다. 2021년 1월 1일은 금요일이라 2020-W53에 남습니다. 2024년 12월 30일은 월요일이고 2025-W01입니다.", "Tuần 1 là tuần chứa thứ Năm đầu tiên của năm. 1/1/2021 là thứ Sáu, nên nó ở 2020-W53. 30/12/2024 là thứ Hai của 2025-W01.", "Minggu 1 adalah minggu yang memuat Kamis pertama tahun itu. 1 Januari 2021 adalah Jumat, jadi tetap di 2020-W53. 30 Desember 2024 adalah Senin di 2025-W01.", "La semana 1 es la que contiene el primer jueves del año. El 1 de enero de 2021 es viernes, así que sigue en 2020-W53. El 30 de diciembre de 2024 es lunes de 2025-W01."),
            "s5t": L("Copy the label and the weekday", "复制标签和星期", "複製標籤和星期", "ラベルと曜日をコピー", "라벨과 요일 복사", "Copy nhãn và thứ", "Salin label dan hari", "Copie la etiqueta y el día"),
            "s5b": L("The label looks like 2020-W53. The weekday is a number from 1 to 7. A spreadsheet that wants a Sunday-start week cannot use this label as-is.", "标签像 2020-W53。星期是 1 到 7 的数字。要从周日开始计周的表格，不能直接用这个标签。", "標籤像 2020-W53。星期是 1 到 7 的數字。要從週日開始計週的表格，不能直接用這個標籤。", "ラベルは 2020-W53 のような形。曜日は 1 から 7。日曜始まりを求める表はこのラベルをそのまま使えない。", "라벨은 2020-W53처럼 보입니다. 요일은 1부터 7까지의 수입니다. 일요일에 주를 시작하는 표는 이 라벨을 그대로 쓸 수 없습니다.", "Nhãn trông như 2020-W53. Thứ là số từ 1 đến 7. Bảng tính muốn tuần bắt đầu Chủ nhật thì không dùng nhãn này nguyên si.", "Labelnya seperti 2020-W53. Hari adalah angka 1 sampai 7. Spreadsheet yang ingin minggu mulai Minggu tidak bisa memakai label ini apa adanya.", "La etiqueta se ve como 2020-W53. El día es un número del 1 al 7. Una hoja que quiere la semana empezando en domingo no puede usar esta etiqueta tal cual."),
            "s6t": L("Check one Thursday you already know", "用一个你本来就知道的周四核对", "用一個你本來就知道的週四核對", "知っている木曜で照合する", "이미 아는 목요일로 대조하기", "Đối chiếu một thứ Năm bạn đã biết", "Cek satu Kamis yang sudah Anda tahu", "Compruebe un jueves que ya conoce"),
            "s6b": L("The first Thursday of the year is inside week 1. If 1 January is a Thursday, that date is weekday 4 of week 1 of the same year, as 2026-01-01 is 2026-W01.", "这一年的第一个周四在第 1 周里。如果 1 月 1 日是周四，这一天就是同一年第 1 周的星期 4，就像 2026-01-01 是 2026-W01。", "這一年的第一個週四在第 1 週裡。如果 1 月 1 日是週四，這一天就是同一年第 1 週的星期 4，就像 2026-01-01 是 2026-W01。", "その年の最初の木曜は第1週の中。1月1日が木曜なら、その日は同じ年の第1週の曜日 4。2026-01-01 は 2026-W01。", "그해의 첫 목요일은 1주 안에 있습니다. 1월 1일이 목요일이면 그날은 같은 해 1주의 요일 4입니다. 2026-01-01은 2026-W01입니다.", "Thứ Năm đầu tiên của năm nằm trong tuần 1. Nếu 1/1 là thứ Năm, ngày đó là ngày 4 của tuần 1 cùng năm, như 2026-01-01 là 2026-W01.", "Kamis pertama tahun itu ada di minggu 1. Jika 1 Januari adalah Kamis, tanggal itu adalah hari 4 minggu 1 tahun yang sama, seperti 2026-01-01 adalah 2026-W01.", "El primer jueves del año está dentro de la semana 1. Si el 1 de enero es jueves, esa fecha es el día 4 de la semana 1 del mismo año, como 2026-01-01 es 2026-W01."),
            "diagram1": L("Monday is 1. Sunday is 7. Week 1 holds the first Thursday.", "周一是 1。周日是 7。第 1 周装着第一个周四。", "週一是 1。週日是 7。第 1 週裝著第一個週四。", "月曜は 1。日曜は 7。第1週は最初の木曜を含む。", "월요일은 1. 일요일은 7. 1주가 첫 목요일을 담습니다.", "Thứ Hai là 1. Chủ nhật là 7. Tuần 1 chứa thứ Năm đầu tiên.", "Senin adalah 1. Minggu adalah 7. Minggu 1 memuat Kamis pertama.", "El lunes es 1. El domingo es 7. La semana 1 contiene el primer jueves."),
            "diagram2": L("1 Jan 2021 is 2020-W53. 30 Dec 2024 is 2025-W01.", "2021-01-01 是 2020-W53。2024-12-30 是 2025-W01。", "2021-01-01 是 2020-W53。2024-12-30 是 2025-W01。", "2021-01-01 は 2020-W53。2024-12-30 は 2025-W01。", "2021-01-01은 2020-W53. 2024-12-30은 2025-W01.", "2021-01-01 là 2020-W53. 2024-12-30 là 2025-W01.", "2021-01-01 adalah 2020-W53. 2024-12-30 adalah 2025-W01.", "2021-01-01 es 2020-W53. 2024-12-30 es 2025-W01."),
        },
        {
            "q1": L("Can I find an ISO week number free online?", "可以免费在线查 ISO 周数吗？", "可以免費線上查 ISO 週數嗎？", "ISO週番号を無料で調べられる？", "ISO 주 번호를 무료로 찾을 수 있나요?", "Tìm số tuần ISO miễn phí online được không?", "Bisa cari nomor minggu ISO gratis online?", "¿Puedo hallar un número de semana ISO gratis en línea?"),
            "a1": L("Yes. cv.cm shows the ISO year, week, and weekday in this tab. Nothing is uploaded.", "可以。cv.cm 在当前标签页显示 ISO 年、周和星期。不上传。", "可以。cv.cm 在目前分頁顯示 ISO 年、週和星期。不上傳。", "できる。このタブで ISO 年・週・曜日を出す。アップロードなし。", "됩니다. 이 탭에서 ISO 연도, 주, 요일을 보여 줍니다. 업로드 없음.", "Được. Hiện năm ISO, tuần và thứ trong tab này. Không tải lên.", "Ya. Menampilkan tahun ISO, minggu, dan hari di tab ini. Tidak diunggah.", "Sí. Muestra el año ISO, la semana y el día en esta pestaña. Nada se sube."),
            "q2": L("Which day starts the week?", "一周从哪一天开始？", "一週從哪一天開始？", "週の始まりは？", "주는 어느 날에 시작하나요?", "Tuần bắt đầu ngày nào?", "Minggu mulai hari apa?", "¿Qué día empieza la semana?"),
            "a2": L("Monday. Monday is 1 and Sunday is 7. A Sunday-start week is a different number.", "周一。周一是 1，周日是 7。从周日开始的周是另一个数。", "週一。週一是 1，週日是 7。從週日開始的週是另一個數。", "月曜。月曜は 1、日曜は 7。日曜始まりは別の番号。", "월요일. 월요일은 1, 일요일은 7. 일요일에 시작하는 주는 다른 번호입니다.", "Thứ Hai. Thứ Hai là 1, Chủ nhật là 7. Tuần bắt đầu Chủ nhật là số khác.", "Senin. Senin adalah 1 dan Minggu adalah 7. Minggu yang mulai Minggu adalah nomor lain.", "El lunes. El lunes es 1 y el domingo es 7. Una semana que empieza en domingo es otro número."),
            "q3": L("Can January belong to the previous year?", "一月可以属于上一年吗？", "一月可以屬於上一年嗎？", "1月が前年に属することはある？", "1월이 전년도에 속할 수 있나요?", "Tháng Một có thể thuộc năm trước không?", "Bisakah Januari masuk tahun sebelumnya?", "¿Enero puede pertenecer al año anterior?"),
            "a3": L("Yes. 1 January 2021 is a Friday in 2020-W53. Week 1 is the week with the first Thursday.", "可以。2021 年 1 月 1 日是 2020-W53 的周五。第 1 周是有第一个周四的那一周。", "可以。2021 年 1 月 1 日是 2020-W53 的週五。第 1 週是有第一個週四的那一週。", "ある。2021年1月1日は 2020-W53 の金曜。第1週は最初の木曜がある週。", "있습니다. 2021년 1월 1일은 2020-W53의 금요일입니다. 1주는 첫 목요일이 있는 주입니다.", "Có. 1/1/2021 là thứ Sáu của 2020-W53. Tuần 1 là tuần có thứ Năm đầu tiên.", "Ya. 1 Januari 2021 adalah Jumat di 2020-W53. Minggu 1 adalah minggu dengan Kamis pertama.", "Sí. El 1 de enero de 2021 es viernes de 2020-W53. La semana 1 es la del primer jueves."),
            "q4": L("Can late December belong to the next year?", "十二月下旬可以属于下一年吗？", "十二月下旬可以屬於下一年嗎？", "12月下旬が翌年に属することはある？", "12월 말이 다음 해에 속할 수 있나요?", "Cuối tháng Mười Hai có thể thuộc năm sau không?", "Bisakah akhir Desember masuk tahun berikutnya?", "¿Finales de diciembre pueden pertenecer al año siguiente?"),
            "a4": L("Yes. 30 December 2024 is a Monday in 2025-W01.", "可以。2024 年 12 月 30 日是 2025-W01 的周一。", "可以。2024 年 12 月 30 日是 2025-W01 的週一。", "ある。2024年12月30日は 2025-W01 の月曜。", "있습니다. 2024년 12월 30일은 2025-W01의 월요일입니다.", "Có. 30/12/2024 là thứ Hai của 2025-W01.", "Ya. 30 Desember 2024 adalah Senin di 2025-W01.", "Sí. El 30 de diciembre de 2024 es lunes de 2025-W01."),
            "q5": L("Is the date uploaded?", "日期会上传吗？", "日期會上傳嗎？", "アップロードされる？", "업로드되나요?", "Ngày có bị tải lên không?", "Apakah tanggal diunggah?", "¿Se sube la fecha?"),
            "a5": L("No. Closing the tab discards it.", "不会。关掉标签页就没了。", "不會。關掉分頁就沒了。", "しない。タブを閉じると消える。", "아니요. 탭을 닫으면 사라집니다.", "Không. Đóng tab là mất.", "Tidak. Tutup tab, hilang.", "No. Al cerrar la pestaña se pierde."),
        },
    ),
    "vat-price": lesson(
        {
            "name": L("How to add VAT to a price", "怎么给价格加增值税", "怎麼給價格加增值稅", "価格に消費税を足す方法", "가격에 부가세를 더하는 법", "Cách cộng VAT vào giá", "Cara tambah PPN ke harga", "Cómo añadir el IVA a un precio"),
            "blurb": L("Exclusive adds the tax. 100 at 20% becomes 120.00. Inclusive splits a gross price. 120 at 20% is 100.00 net and 20.00 tax, not 24.00.", "不含税是把税加上去。100 按 20% 变成 120.00。含税是把总价拆开。120 按 20% 是净额 100.00、税 20.00，不是 24.00。", "不含稅是把稅加上去。100 按 20% 變成 120.00。含稅是把總價拆開。120 按 20% 是淨額 100.00、稅 20.00，不是 24.00。", "税別は税を足す。100 の 20% は 120.00。税込は総額を分ける。120 の 20% は税抜 100.00、税 20.00。24.00 ではない。", "별도는 세금을 더합니다. 100에 20%면 120.00. 포함은 총액을 나눕니다. 120에 20%면 순액 100.00, 세금 20.00이지 24.00이 아닙니다.", "Chưa gồm thuế thì cộng thuế. 100 với 20% thành 120,00. Đã gồm thuế thì tách tổng. 120 với 20% là net 100,00 và thuế 20,00, không phải 24,00.", "Eksklusif menambahkan pajak. 100 dengan 20% menjadi 120,00. Inklusif memecah harga kotor. 120 dengan 20% adalah net 100,00 dan pajak 20,00, bukan 24,00.", "Exclusivo suma el impuesto. 100 al 20% pasa a 120,00. Inclusivo parte un precio bruto. 120 al 20% es 100,00 neto y 20,00 de impuesto, no 24,00."),
            "title": L("How to add VAT to a price", "怎么给价格加增值税", "怎麼給價格加增值稅", "価格に消費税を足す方法", "가격에 부가세를 더하는 법", "Cách cộng VAT vào giá", "Cara tambah PPN ke harga", "Cómo añadir el IVA a un precio"),
            "lead": L("You have an amount and a rate you already chose. You will pick exclusive or inclusive in this tab. Exclusive adds tax to a net price. Inclusive takes tax out of a gross price. 120 times 20% is the wrong tax on a price that already includes 20%.", "你有一个金额和一个已经选定的税率。在当前标签页选不含税或含税。不含税是把税加到净价上。含税是从总价里把税拆出来。120 乘 20% 是已经含了 20% 的价格上的错误税额。", "你有一個金額和一個已經選定的稅率。在目前分頁選不含稅或含稅。不含稅是把稅加到淨價上。含稅是從總價裡把稅拆出來。120 乘 20% 是已經含了 20% 的價格上的錯誤稅額。", "金額と、すでに選んだ税率がある。このタブで税別か税込を選ぶ。税別は税抜に税を足す。税込は総額から税を取り出す。120 の 20% は、すでに 20% を含む価格に対する誤った税額。", "금액과 이미 고른 세율이 있습니다. 이 탭에서 별도 또는 포함을 고르세요. 별도는 순액에 세금을 더합니다. 포함은 총액에서 세금을 꺼냅니다. 120 곱하기 20%는 이미 20%가 들어 있는 가격에 대한 잘못된 세금입니다.", "Bạn có một số tiền và một thuế suất đã chọn. Chọn chưa gồm hoặc đã gồm trong tab này. Chưa gồm thì cộng thuế vào giá net. Đã gồm thì tách thuế khỏi tổng. 120 nhân 20% là số thuế sai trên một giá đã gồm 20%.", "Anda punya jumlah dan tarif yang sudah dipilih. Pilih eksklusif atau inklusif di tab ini. Eksklusif menambah pajak ke harga net. Inklusif mengeluarkan pajak dari harga kotor. 120 kali 20% adalah pajak yang salah pada harga yang sudah termasuk 20%.", "Tiene un importe y una tasa que ya eligió. Elija exclusivo o inclusivo aquí. Exclusivo suma el impuesto a un precio neto. Inclusivo saca el impuesto de un precio bruto. 120 por 20% es el impuesto equivocado en un precio que ya incluye el 20%."),
            "result": L("Net, tax, and gross to two decimals, for the rate you typed.", "净额、税额和总额，都到两位小数，用的是你输入的税率。", "淨額、稅額和總額，都到兩位小數，用的是你輸入的稅率。", "税抜・税・総額。小数第2位まで。入力した税率。", "순액, 세금, 총액. 소수 둘째 자리까지. 입력한 세율.", "Net, thuế và tổng, hai chữ số thập phân, theo thuế suất bạn gõ.", "Net, pajak, dan kotor, dua desimal, dengan tarif yang Anda ketik.", "Neto, impuesto y bruto a dos decimales, con la tasa que escribió."),
            "note": L("Open VAT when you know whether the amount already includes tax. The page does not look up a country rate. Nothing is uploaded.", "知道金额里是否已经含税，再打开增值税。这一页不查某个国家的税率。不上传。", "知道金額裡是否已經含稅，再開增值稅。這一頁不查某個國家的稅率。不上傳。", "金額が税込か分かってから開く。このページは国の税率を調べない。アップロードなし。", "금액에 세금이 이미 들어 있는지 알 때 부가세를 여세요. 이 페이지는 나라 세율을 찾지 않습니다. 업로드 없음.", "Biết số tiền đã gồm thuế chưa thì mở VAT. Trang không tra thuế suất của một nước. Không tải lên.", "Tahu apakah jumlah sudah termasuk pajak, baru buka PPN. Halaman tidak mencari tarif negara. Tidak diunggah.", "Abra el IVA cuando sepa si el importe ya incluye el impuesto. La página no busca la tasa de un país. Nada se sube."),
            "s1t": L("Say whether the amount already includes tax", "先说这个金额里有没有税", "先說這個金額裡有沒有稅", "金額がすでに税込か言う", "금액에 세금이 이미 있는지 말하기", "Nói số tiền đã gồm thuế chưa", "Sebut apakah jumlah sudah termasuk pajak", "Diga si el importe ya incluye el impuesto"),
            "s1b": L("A net price uses exclusive. A shelf price that already includes tax uses inclusive. Mixing them changes the tax.", "净价用不含税。价签上已经含税的价格用含税。把两者弄混，税额就会变。", "淨價用不含稅。價簽上已經含稅的價格用含稅。把兩者弄混，稅額就會變。", "税抜価格は税別。すでに税を含む店頭価格は税込。混ぜると税額が変わる。", "순액은 별도. 이미 세금이 들어 있는 진열가는 포함. 둘을 섞으면 세금이 바뀝니다.", "Giá net dùng chưa gồm. Giá kệ đã gồm thuế dùng đã gồm. Trộn hai cách thì số thuế đổi.", "Harga net memakai eksklusif. Harga rak yang sudah termasuk pajak memakai inklusif. Mencampur keduanya mengubah pajak.", "Un precio neto usa exclusivo. Un precio de estante que ya incluye el impuesto usa inclusivo. Mezclarlos cambia el impuesto."),
            "s2t": L("Open VAT on cv.cm", "打开 cv.cm 的增值税", "打開 cv.cm 的增值稅", "cv.cmの消費税を開く", "cv.cm 부가세를 열기", "Mở VAT trên cv.cm", "Buka PPN di cv.cm", "Abra el IVA en cv.cm"),
            "s2b": L("The arithmetic stays in this tab.", "计算留在当前标签页。", "計算留在目前分頁。", "計算はこのタブ。", "계산은 이 탭에서.", "Phép tính ở trong tab này.", "Hitungan di tab ini.", "La cuenta queda en esta pestaña."),
            "s3t": L("Type the amount and the rate you were given", "填上给你的金额和税率", "填上給你的金額和稅率", "渡された金額と税率を入れる", "받은 금액과 세율 넣기", "Nhập số tiền và thuế suất được đưa", "Isi jumlah dan tarif yang diberikan", "Escriba el importe y la tasa que le dieron"),
            "s3b": L("The rate is the number you type. This page does not choose 20% or 10% for a country. A negative amount or a negative rate fails.", "税率就是你输入的那个数。这一页不会替某个国家选 20% 或 10%。负数金额或负数税率会失败。", "稅率就是你輸入的那個數。這一頁不會替某個國家選 20% 或 10%。負數金額或負數稅率會失敗。", "税率は入力した数。このページは国のために 20% や 10% を選ばない。負の金額や負の税率は失敗。", "세율은 입력한 수입니다. 이 페이지는 나라를 위해 20%나 10%를 고르지 않습니다. 음수 금액이나 음수 세율은 실패합니다.", "Thuế suất là số bạn gõ. Trang không chọn 20% hay 10% cho một nước. Số tiền âm hoặc thuế suất âm thì thất bại.", "Tarif adalah angka yang Anda ketik. Halaman ini tidak memilih 20% atau 10% untuk suatu negara. Jumlah negatif atau tarif negatif gagal.", "La tasa es el número que escribe. Esta página no elige 20% o 10% para un país. Un importe negativo o una tasa negativa fallan."),
            "s4t": L("Add tax when the price is net", "价格是净价，就把税加上", "價格是淨價，就把稅加上", "価格が税抜なら税を足す", "가격이 순액이면 세금 더하기", "Giá là net thì cộng thuế", "Harga net maka tambahkan pajak", "Sume el impuesto cuando el precio es neto"),
            "s4b": L("Exclusive on 100 at 20% is net 100.00, tax 20.00, gross 120.00. Gross is the amount plus the tax.", "100 按 20% 用不含税：净额 100.00，税 20.00，总额 120.00。总额是金额加上税。", "100 按 20% 用不含稅：淨額 100.00，稅 20.00，總額 120.00。總額是金額加上稅。", "100 の 20% を税別にする。税抜 100.00、税 20.00、総額 120.00。総額は金額に税を足したもの。", "100에 20%를 별도로. 순액 100.00, 세금 20.00, 총액 120.00. 총액은 금액에 세금을 더한 것.", "100 với 20% ở chế độ chưa gồm: net 100,00, thuế 20,00, tổng 120,00. Tổng là số tiền cộng thuế.", "100 dengan 20% eksklusif: net 100,00, pajak 20,00, kotor 120,00. Kotor adalah jumlah ditambah pajak.", "100 al 20% en exclusivo: neto 100,00, impuesto 20,00, bruto 120,00. El bruto es el importe más el impuesto."),
            "s5t": L("Split the price when tax is already inside", "税已经在价格里，就把价格拆开", "稅已經在價格裡，就把價格拆開", "税がすでに入っているなら価格を分ける", "세금이 이미 가격 안에 있으면 가격을 나누기", "Thuế đã nằm trong giá thì tách giá", "Pajak sudah di dalam harga, maka pecah harganya", "Parta el precio cuando el impuesto ya está dentro"),
            "s5b": L("Inclusive on 120 at 20% is net 100.00, tax 20.00, gross 120.00. Tax is not 120 times 20%. That product is 24.00, which is the tax you would add to a net 120.", "120 按 20% 用含税：净额 100.00，税 20.00，总额 120.00。税不是 120 乘 20%。那个乘积是 24.00，那是加到净价 120 上的税。", "120 按 20% 用含稅：淨額 100.00，稅 20.00，總額 120.00。稅不是 120 乘 20%。那個乘積是 24.00，那是加到淨價 120 上的稅。", "120 の 20% を税込にする。税抜 100.00、税 20.00、総額 120.00。税は 120×20% ではない。その積は 24.00 で、税抜 120 に足す税。", "120에 20%를 포함으로. 순액 100.00, 세금 20.00, 총액 120.00. 세금은 120 곱하기 20%가 아닙니다. 그 곱은 24.00이고, 순액 120에 더하는 세금입니다.", "120 với 20% ở chế độ đã gồm: net 100,00, thuế 20,00, tổng 120,00. Thuế không phải 120 nhân 20%. Tích đó là 24,00, là thuế cộng vào net 120.", "120 dengan 20% inklusif: net 100,00, pajak 20,00, kotor 120,00. Pajak bukan 120 kali 20%. Hasil kali itu 24,00, yaitu pajak yang ditambahkan ke net 120.", "120 al 20% en inclusivo: neto 100,00, impuesto 20,00, bruto 120,00. El impuesto no es 120 por 20%. Ese producto es 24,00, el impuesto que se sumaría a un neto de 120."),
            "s6t": L("Copy net, tax, and gross", "复制净额、税额和总额", "複製淨額、稅額和總額", "税抜・税・総額をコピー", "순액, 세금, 총액 복사", "Copy net, thuế và tổng", "Salin net, pajak, dan kotor", "Copie neto, impuesto y bruto"),
            "s6b": L("All three are two decimals. This is arithmetic on the numbers you typed. It is not a tax filing, and it does not name a currency.", "三个数都是两位小数。这是你输入的数字上的运算。它不是报税，也不标明货币。", "三個數都是兩位小數。這是你輸入的數字上的運算。它不是報稅，也不標明貨幣。", "三つとも小数第2位。入力した数の計算。申告ではなく、通貨名もない。", "셋 다 소수 둘째 자리입니다. 입력한 수에 대한 연산입니다. 세금 신고가 아니고 통화도 적지 않습니다.", "Cả ba đều hai chữ số thập phân. Đây là phép tính trên số bạn gõ. Không phải tờ khai thuế, và không ghi đơn vị tiền.", "Ketiganya dua desimal. Ini hitungan pada angka yang Anda ketik. Bukan pelaporan pajak, dan tidak menyebut mata uang.", "Los tres van a dos decimales. Es aritmética sobre los números que escribió. No es una declaración de impuestos, y no nombra una moneda."),
            "diagram1": L("Net 100 at 20% exclusive: tax 20.00, gross 120.00.", "净价 100、税率 20%、不含税：税 20.00，总额 120.00。", "淨價 100、稅率 20%、不含稅：稅 20.00，總額 120.00。", "税抜 100、税率 20%、税別：税 20.00、総額 120.00。", "순액 100, 세율 20%, 별도: 세금 20.00, 총액 120.00.", "Net 100, thuế 20%, chưa gồm: thuế 20,00, tổng 120,00.", "Net 100, tarif 20%, eksklusif: pajak 20,00, kotor 120,00.", "Neto 100 al 20% exclusivo: impuesto 20,00, bruto 120,00."),
            "diagram2": L("Gross 120 at 20% inclusive: tax 20.00, not 24.00.", "总价 120、税率 20%、含税：税 20.00，不是 24.00。", "總價 120、稅率 20%、含稅：稅 20.00，不是 24.00。", "総額 120、税率 20%、税込：税 20.00。24.00 ではない。", "총액 120, 세율 20%, 포함: 세금 20.00, 24.00이 아님.", "Tổng 120, thuế 20%, đã gồm: thuế 20,00, không phải 24,00.", "Kotor 120, tarif 20%, inklusif: pajak 20,00, bukan 24,00.", "Bruto 120 al 20% inclusivo: impuesto 20,00, no 24,00."),
        },
        {
            "q1": L("Can I add VAT to a price free online?", "可以免费在线给价格加增值税吗？", "可以免費線上給價格加增值稅嗎？", "価格に消費税を無料で足せる？", "가격에 부가세를 무료로 더할 수 있나요?", "Cộng VAT vào giá miễn phí online được không?", "Bisa tambah PPN ke harga gratis online?", "¿Puedo añadir el IVA a un precio gratis en línea?"),
            "a1": L("Yes. cv.cm shows net, tax, and gross in this tab. Nothing is uploaded.", "可以。cv.cm 在当前标签页显示净额、税额和总额。不上传。", "可以。cv.cm 在目前分頁顯示淨額、稅額和總額。不上傳。", "できる。このタブで税抜・税・総額を出す。アップロードなし。", "됩니다. 이 탭에서 순액, 세금, 총액을 보여 줍니다. 업로드 없음.", "Được. Hiện net, thuế và tổng trong tab này. Không tải lên.", "Ya. Menampilkan net, pajak, dan kotor di tab ini. Tidak diunggah.", "Sí. Muestra neto, impuesto y bruto en esta pestaña. Nada se sube."),
            "q2": L("What is 100 at 20% exclusive?", "100 按 20% 不含税是多少？", "100 按 20% 不含稅是多少？", "100 の 20% 税別は？", "100에 20% 별도는?", "100 với 20% chưa gồm là bao nhiêu?", "100 dengan 20% eksklusif berapa?", "¿Cuánto es 100 al 20% exclusivo?"),
            "a2": L("Net 100.00, tax 20.00, gross 120.00.", "净额 100.00，税 20.00，总额 120.00。", "淨額 100.00，稅 20.00，總額 120.00。", "税抜 100.00、税 20.00、総額 120.00。", "순액 100.00, 세금 20.00, 총액 120.00.", "Net 100,00, thuế 20,00, tổng 120,00.", "Net 100,00, pajak 20,00, kotor 120,00.", "Neto 100,00, impuesto 20,00, bruto 120,00."),
            "q3": L("What is 120 at 20% inclusive?", "120 按 20% 含税是多少？", "120 按 20% 含稅是多少？", "120 の 20% 税込は？", "120에 20% 포함은?", "120 với 20% đã gồm là bao nhiêu?", "120 dengan 20% inklusif berapa?", "¿Cuánto es 120 al 20% inclusivo?"),
            "a3": L("Net 100.00, tax 20.00, gross 120.00. The tax is not 24.00.", "净额 100.00，税 20.00，总额 120.00。税不是 24.00。", "淨額 100.00，稅 20.00，總額 120.00。稅不是 24.00。", "税抜 100.00、税 20.00、総額 120.00。税は 24.00 ではない。", "순액 100.00, 세금 20.00, 총액 120.00. 세금은 24.00이 아닙니다.", "Net 100,00, thuế 20,00, tổng 120,00. Thuế không phải 24,00.", "Net 100,00, pajak 20,00, kotor 120,00. Pajaknya bukan 24,00.", "Neto 100,00, impuesto 20,00, bruto 120,00. El impuesto no es 24,00."),
            "q4": L("Does the page look up a country rate?", "这一页会查某个国家的税率吗？", "這一頁會查某個國家的稅率嗎？", "国の税率を調べる？", "나라 세율을 찾나요?", "Trang có tra thuế suất của một nước không?", "Apakah halaman mencari tarif negara?", "¿La página busca la tasa de un país?"),
            "a4": L("No. You type the rate. The three lines are arithmetic, not a tax filing, and they do not name a currency.", "不会。税率由你输入。三行是运算，不是报税，也不标明货币。", "不會。稅率由你輸入。三行是運算，不是報稅，也不標明貨幣。", "調べない。税率は入力する。三行は計算であり申告ではなく、通貨名もない。", "찾지 않습니다. 세율은 직접 입력합니다. 세 줄은 연산이지 세금 신고가 아니고 통화도 적지 않습니다.", "Không. Bạn gõ thuế suất. Ba dòng là phép tính, không phải tờ khai, và không ghi đơn vị tiền.", "Tidak. Anda mengetik tarifnya. Tiga baris itu hitungan, bukan pelaporan pajak, dan tidak menyebut mata uang.", "No. Usted escribe la tasa. Las tres líneas son aritmética, no una declaración, y no nombran una moneda."),
            "q5": L("Is the amount uploaded?", "金额会上传吗？", "金額會上傳嗎？", "アップロードされる？", "업로드되나요?", "Số tiền có bị tải lên không?", "Apakah jumlah diunggah?", "¿Se sube el importe?"),
            "a5": L("No. Closing the tab discards it.", "不会。关掉标签页就没了。", "不會。關掉分頁就沒了。", "しない。タブを閉じると消える。", "아니요. 탭을 닫으면 사라집니다.", "Không. Đóng tab là mất.", "Tidak. Tutup tab, hilang.", "No. Al cerrar la pestaña se pierde."),
        },
    ),
}

META = {
    "titleDaysBetween": L("How to count days between two dates | cv.cm", "怎么数两个日期之间的天数 | cv.cm", "怎麼數兩個日期之間的天數 | cv.cm", "二つの日付の日数の数え方 | cv.cm", "두 날짜 사이 일수 세는 법 | cv.cm", "Cách đếm số ngày giữa hai ngày | cv.cm", "Cara hitung hari di antara dua tanggal | cv.cm", "Cómo contar los días entre dos fechas | cv.cm"),
    "descDaysBetween": L("The signed difference does not include both ends. Monday 5 January 2026 to Friday 9 January is 4 days. 28 February 2024 to 1 March 2024 is 2. Weekends stay in the count. Nothing is uploaded.", "有符号的日差不把两头都算进去。2026 年 1 月 5 日周一到 1 月 9 日周五是 4 天。2024 年 2 月 28 日到 3 月 1 日是 2 天。周末留在计数里。不上传。", "有符號的日差不把兩頭都算進去。2026 年 1 月 5 日週一到 1 月 9 日週五是 4 天。2024 年 2 月 28 日到 3 月 1 日是 2 天。週末留在計數裡。不上傳。", "符号付きの日数差は両端を含まない。2026年1月5日月曜から1月9日金曜は 4 日。2024年2月28日から3月1日は 2 日。週末は数に残る。アップロードなし。", "부호 있는 일수 차이는 양쪽을 포함하지 않습니다. 2026년 1월 5일 월요일부터 1월 9일 금요일은 4일. 2024년 2월 28일부터 3월 1일은 2일. 주말은 세에 남습니다. 업로드 없음.", "Hiệu có dấu không tính cả hai đầu. Thứ Hai 5/1/2026 đến thứ Sáu 9/1 là 4 ngày. 28/2/2024 đến 1/3/2024 là 2 ngày. Cuối tuần vẫn trong số đếm. Không tải lên.", "Selisih bertanda tidak mencakup kedua ujung. Senin 5 Januari 2026 sampai Jumat 9 Januari adalah 4 hari. 28 Februari 2024 sampai 1 Maret 2024 adalah 2 hari. Akhir pekan tetap di hitungan. Tidak diunggah.", "La diferencia con signo no incluye ambos extremos. Del lunes 5 de enero de 2026 al viernes 9 de enero hay 4 días. Del 28 de febrero de 2024 al 1 de marzo de 2024 hay 2. Los fines de semana siguen en el conteo. Nada se sube."),
    "titleShiftDate": L("How to add days to a date | cv.cm", "怎么给日期加减天数 | cv.cm", "怎麼給日期加減天數 | cv.cm", "日付に日数を足す方法 | cv.cm", "날짜에 일수 더하는 법 | cv.cm", "Cách cộng ngày vào một ngày | cv.cm", "Cara tambah hari ke tanggal | cv.cm", "Cómo sumar días a una fecha | cv.cm"),
    "descShiftDate": L("Add a whole number of calendar days. 28 February 2024 plus 1 is 29 February 2024. Friday plus 1 is Saturday. A fraction of a day fails. Nothing is uploaded.", "加上整数个日历日。2024 年 2 月 28 日加 1 是 2024 年 2 月 29 日。周五加 1 是周六。不满一天的小数会失败。不上传。", "加上整數個日曆日。2024 年 2 月 28 日加 1 是 2024 年 2 月 29 日。週五加 1 是週六。不滿一天的小數會失敗。不上傳。", "整数の暦日を足す。2024年2月28日に 1 を足すと 2024年2月29日。金曜に 1 を足すと土曜。端数の日は失敗。アップロードなし。", "정수 달력 일을 더합니다. 2024년 2월 28일에 1을 더하면 2024년 2월 29일. 금요일에 1을 더하면 토요일. 하루의 소수부는 실패합니다. 업로드 없음.", "Cộng một số nguyên ngày lịch. 28/2/2024 cộng 1 là 29/2/2024. Thứ Sáu cộng 1 là thứ Bảy. Phần lẻ của một ngày thì thất bại. Không tải lên.", "Tambahkan bilangan bulat hari kalender. 28 Februari 2024 ditambah 1 adalah 29 Februari 2024. Jumat ditambah 1 adalah Sabtu. Pecahan hari gagal. Tidak diunggah.", "Sume un número entero de días de calendario. El 28 de febrero de 2024 más 1 es el 29 de febrero de 2024. Viernes más 1 es sábado. Una fracción de día falla. Nada se sube."),
    "titleIsoWeek": L("How to find the ISO week number | cv.cm", "怎么查 ISO 周数 | cv.cm", "怎麼查 ISO 週數 | cv.cm", "ISO週番号の調べ方 | cv.cm", "ISO 주 번호 찾는 법 | cv.cm", "Cách tìm số tuần ISO | cv.cm", "Cara cari nomor minggu ISO | cv.cm", "Cómo hallar el número de semana ISO | cv.cm"),
    "descIsoWeek": L("ISO weeks start on Monday. Week 1 contains the first Thursday. 1 January 2021 is 2020-W53. 30 December 2024 is 2025-W01. Sunday is weekday 7. Nothing is uploaded.", "ISO 周从周一开始。第 1 周包含第一个周四。2021 年 1 月 1 日是 2020-W53。2024 年 12 月 30 日是 2025-W01。周日是星期 7。不上传。", "ISO 週從週一開始。第 1 週包含第一個週四。2021 年 1 月 1 日是 2020-W53。2024 年 12 月 30 日是 2025-W01。週日是星期 7。不上傳。", "ISO 週は月曜始まり。第1週は最初の木曜を含む。2021年1月1日は 2020-W53。2024年12月30日は 2025-W01。日曜は曜日 7。アップロードなし。", "ISO 주는 월요일에 시작합니다. 1주는 첫 목요일을 포함합니다. 2021년 1월 1일은 2020-W53. 2024년 12월 30일은 2025-W01. 일요일은 요일 7. 업로드 없음.", "Tuần ISO bắt đầu thứ Hai. Tuần 1 chứa thứ Năm đầu tiên. 1/1/2021 là 2020-W53. 30/12/2024 là 2025-W01. Chủ nhật là ngày 7. Không tải lên.", "Minggu ISO mulai Senin. Minggu 1 memuat Kamis pertama. 1 Januari 2021 adalah 2020-W53. 30 Desember 2024 adalah 2025-W01. Minggu adalah hari 7. Tidak diunggah.", "Las semanas ISO empiezan en lunes. La semana 1 contiene el primer jueves. El 1 de enero de 2021 es 2020-W53. El 30 de diciembre de 2024 es 2025-W01. El domingo es el día 7. Nada se sube."),
    "titleVatPrice": L("How to add VAT to a price | cv.cm", "怎么给价格加增值税 | cv.cm", "怎麼給價格加增值稅 | cv.cm", "価格に消費税を足す方法 | cv.cm", "가격에 부가세를 더하는 법 | cv.cm", "Cách cộng VAT vào giá | cv.cm", "Cara tambah PPN ke harga | cv.cm", "Cómo añadir el IVA a un precio | cv.cm"),
    "descVatPrice": L("Exclusive on 100 at 20% is tax 20.00 and gross 120.00. Inclusive on 120 at 20% is tax 20.00, not 24.00. You type the rate. Nothing is uploaded.", "100 按 20% 不含税：税 20.00，总额 120.00。120 按 20% 含税：税 20.00，不是 24.00。税率由你输入。不上传。", "100 按 20% 不含稅：稅 20.00，總額 120.00。120 按 20% 含稅：稅 20.00，不是 24.00。稅率由你輸入。不上傳。", "100 の 20% 税別は税 20.00、総額 120.00。120 の 20% 税込は税 20.00。24.00 ではない。税率は入力。アップロードなし。", "100에 20% 별도는 세금 20.00, 총액 120.00. 120에 20% 포함은 세금 20.00, 24.00이 아닙니다. 세율은 직접 입력. 업로드 없음.", "100 với 20% chưa gồm: thuế 20,00, tổng 120,00. 120 với 20% đã gồm: thuế 20,00, không phải 24,00. Bạn gõ thuế suất. Không tải lên.", "100 dengan 20% eksklusif: pajak 20,00, kotor 120,00. 120 dengan 20% inklusif: pajak 20,00, bukan 24,00. Anda mengetik tarifnya. Tidak diunggah.", "100 al 20% exclusivo: impuesto 20,00 y bruto 120,00. 120 al 20% inclusivo: impuesto 20,00, no 24,00. Usted escribe la tasa. Nada se sube."),
}


def inject() -> None:
    if set(LESSONS) != {"days-between", "shift-date", "iso-week", "vat-price"}:
        raise SystemExit("lesson ids")
    for loc, path in FILES.items():
        data = json.loads(path.read_text())
        data["faq"].setdefault("learn", {})
        for lesson_id, payload in LESSONS.items():
            data["learn"][lesson_id] = payload["copy"][loc]
            data["faq"]["learn"][lesson_id] = payload["faq"][loc]
        for key, by_loc in META.items():
            data["meta"][key] = by_loc[loc]
        path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n")
        print("patched", path.name)


if __name__ == "__main__":
    inject()
