#!/usr/bin/env python3
"""Inject second-batch how-to copy into locale JSON files."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LOCS = ["en", "zh-CN", "zh-TW", "ja", "ko", "vi", "id", "es"]
FILES = {loc: ROOT / "src/locales" / f"{loc}.json" for loc in LOCS}


def L(*vals: str) -> dict[str, str]:
    if len(vals) != 8:
        raise ValueError(len(vals), vals[0] if vals else None)
    return dict(zip(LOCS, vals))


def lesson(fields: dict[str, dict[str, str]], faq: dict[str, dict[str, str]]) -> dict:
    copy = {loc: {k: v[loc] for k, v in fields.items()} for loc in LOCS}
    faq_out = {loc: {k: v[loc] for k, v in faq.items()} for loc in LOCS}
    return {"copy": copy, "faq": faq_out}


LESSONS = {
    "webp-to-png": lesson(
        {
            "name": L("How to convert WebP to PNG", "怎么把 WebP 转成 PNG", "怎麼把 WebP 轉成 PNG", "WebPをPNGにする", "WebP를 PNG로", "Cách đổi WebP sang PNG", "Cara ubah WebP ke PNG", "Cómo pasar WebP a PNG"),
            "blurb": L("Chrome often saves WebP. Export PNG, then open it in the app that rejected WebP.", "Chrome 常存 WebP。导出 PNG，再到打不开 WebP 的软件里打开看。", "Chrome 常存 WebP。匯出 PNG，再到打不開 WebP 的軟體裡打開看。", "ChromeはWebPを保存しがち。PNGを書き出し、拒否したアプリで開く。", "Chrome은 WebP를 자주 저장합니다. PNG로 보낸 뒤 거부한 앱에서 여세요.", "Chrome hay lưu WebP. Xuất PNG rồi mở trong app từng từ chối WebP.", "Chrome sering simpan WebP. Ekspor PNG, buka di app yang menolak WebP.", "Chrome suele guardar WebP. Exporte PNG y ábralo en la app que lo rechazó."),
            "title": L("How to convert WebP to PNG", "怎么把 WebP 转成 PNG", "怎麼把 WebP 轉成 PNG", "WebPをPNGにする方法", "WebP를 PNG로 변환하는 법", "Cách đổi WebP sang PNG", "Cara ubah WebP ke PNG", "Cómo pasar WebP a PNG"),
            "lead": L("Chrome and many sites save WebP. PNG opens in more apps and can keep a clear background. You will convert a copy in this tab and check the edges.", "Chrome 和不少网站存 WebP。PNG 更通用，还能留透明底。你要在当前标签页转一份，再看边缘。", "Chrome 和不少網站存 WebP。PNG 更通用，還能留透明底。在目前分頁轉一份，再看邊緣。", "Chromeや多くのサイトはWebPを保存する。PNGの方が通り、透明も残せる。このタブでコピーを変換し端を見る。", "Chrome과 많은 사이트가 WebP를 저장합니다. PNG가 더 통하고 투명도 남깁니다. 이 탭에서 복사본을 변환한 뒤 가장자리를 보세요.", "Chrome và nhiều site lưu WebP. PNG mở được nhiều hơn và giữ nền trong. Đổi một bản trong tab này rồi kiểm mép.", "Chrome dan banyak situs menyimpan WebP. PNG lebih diterima dan bisa jaga latar tembus. Ubah salinan di tab ini, cek tepinya.", "Chrome y muchos sitios guardan WebP. El PNG abre en más apps y puede conservar el fondo transparente. Convierta una copia aquí y mire los bordes."),
            "result": L("PNG files that open in the app that rejected WebP, with transparency intact if the original had it.", "能在拒收 WebP 的软件里打开的 PNG；原图有透明底就还在。", "能在拒收 WebP 的軟體裡打開的 PNG；原圖有透明底就還在。", "WebPを拒んだアプリで開くPNG。元が透明なら残る。", "WebP를 거부한 앱에서 열리는 PNG. 원본에 투명이 있으면 남습니다.", "PNG mở được trong app từng từ chối WebP; nền trong còn nếu bản gốc có.", "PNG yang terbuka di app yang menolak WebP; transparansi utuh jika aslinya ada.", "PNG que abren en la app que rechazó WebP, con transparencia si el original la tenía."),
            "note": L("Open convert when the .webp is on disk. Pick PNG, not JPG, if you need a clear background. Nothing is uploaded.", "文件在磁盘上再打开格式转换。要透明底就选 PNG，不要选 JPG。不上传。", "檔在磁碟上再打開格式轉換。要透明底就選 PNG，不要選 JPG。不上傳。", "ファイルが手元にあってから変換を開く。透明が要るならJPGではなくPNG。アップロードなし。", "파일이 디스크에 있으면 변환을 여세요. 투명이 필요하면 JPG가 아니라 PNG. 업로드 없음.", "Có file .webp trên đĩa thì mở chuyển đổi. Cần nền trong thì chọn PNG, đừng JPG. Không tải lên.", "File .webp di disk, baru buka konversi. Butuh latar tembus: pilih PNG, bukan JPG. Tidak diunggah.", "Abra convertir cuando el .webp esté en el disco. Si necesita fondo transparente, elija PNG, no JPG. Nada se sube."),
            "s1t": L("Decide why you need PNG", "先想清楚为什么要 PNG", "先想清楚為什麼要 PNG", "なぜPNGか決める", "왜 PNG인지 정하기", "Quyết định vì sao cần PNG", "Tentukan kenapa perlu PNG", "Decida por qué necesita PNG"),
            "s1b": L("Some forms and older apps reject WebP. PNG keeps sharp edges and can keep transparency. JPG is smaller but fills a clear background.", "有的表单和老软件不认 WebP。PNG 边缘利，还能留透明。JPG 更小，但会填死透明底。", "有的表單和老軟體不認 WebP。PNG 邊緣利，還能留透明。JPG 更小，但會填死透明底。", "提出や古いアプリはWebPを拒む。PNGは端がSharpで透明も残る。JPGは小さいが透明を潰す。", "일부 서류와 옛 앱은 WebP를 거부합니다. PNG는 가장자리가 선명하고 투명을 남깁니다. JPG는 작지만 투명 배경을 메웁니다.", "Một số form và app cũ từ chối WebP. PNG giữ mép sắc và nền trong. JPG nhỏ hơn nhưng lấp nền trong.", "Formulir dan app lama menolak WebP. PNG jaga tepi tajam dan transparansi. JPG lebih kecil tapi mengisi latar tembus.", "Algunos formularios y apps viejas rechazan WebP. PNG conserva bordes nítidos y transparencia. JPG pesa menos pero rellena el fondo."),
            "s2t": L("Open image formats on cv.cm", "打开 cv.cm 的图片格式", "打開 cv.cm 的圖片格式", "cv.cmの画像形式を開く", "cv.cm 이미지 형식을 열기", "Mở định dạng ảnh trên cv.cm", "Buka format gambar di cv.cm", "Abra formatos de imagen en cv.cm"),
            "s2b": L("Work stays in this tab. Closing it discards the file.", "转换留在当前标签页。关掉就没了。", "轉換留在目前分頁。關掉就沒了。", "このタブで処理。閉じると消える。", "이 탭에서 변환합니다. 닫으면 사라집니다.", "Xử lý trong tab này. Đóng là mất.", "Proses di tab ini. Tutup, hilang.", "El trabajo queda en esta pestaña. Al cerrarla se pierde."),
            "s3t": L("Drop the .webp file", "拖入 .webp", "拖入 .webp", ".webpをドロップ", ".webp 넣기", "Thả file .webp", "Letakkan .webp", "Suelte el .webp"),
            "s3b": L("One file or a batch. If the preview is blank, the browser cannot decode that WebP — try another browser.", "一张或一批。预览空白，就是这款浏览器解不了，换一个。", "一張或一批。預覽空白，就是這款瀏覽器解不了，換一個。", "1枚でもまとめてでも。プレビューが空ならこのブラウザは不可。乗り換える。", "한 장 또는 여러 장. 미리보기가 비면 이 브라우저는 못 엽니다. 바꾸세요.", "Một hoặc nhiều. Xem trước trống thì trình duyệt không đọc được — đổi trình duyệt.", "Satu atau batch. Pratinjau kosong: peramban ini gagal. Ganti.", "Uno o varios. Si la vista está en blanco, este navegador no lo decodifica: cambie."),
            "s4t": L("Choose PNG, not JPG, if you need transparency", "要透明底就选 PNG，不要选 JPG", "要透明底就選 PNG，不要選 JPG", "透明が要るならJPGではなくPNG", "투명이 필요하면 JPG가 아니라 PNG", "Cần nền trong thì chọn PNG, đừng JPG", "Butuh transparansi: pilih PNG, bukan JPG", "Si necesita transparencia, elija PNG, no JPG"),
            "s4b": L("PNG keeps a clear background. JPG will fill it with white or a matte. Optional resize only if a form has a pixel cap.", "PNG 留下透明。JPG 会填成白底。表单有像素上限再缩小。", "PNG 留下透明。JPG 會填成白底。表單有像素上限再縮小。", "PNGは透明を残す。JPGは白などで埋める。画素上限があるときだけ縮小。", "PNG는 투명을 남깁니다. JPG는 흰 바탕으로 메웁니다. 서류에 픽셀 한도가 있을 때만 줄이세요.", "PNG giữ nền trong. JPG sẽ lấp trắng. Chỉ thu nhỏ nếu form có giới hạn pixel.", "PNG menjaga latar tembus. JPG mengisinya. Perkecil hanya jika formulir punya batas piksel.", "PNG conserva el fondo. JPG lo rellena de blanco. Reduzca solo si el formulario limita los píxeles."),
            "s5t": L("Download the PNG", "下载 PNG", "下載 PNG", "PNGを保存", "PNG 받기", "Tải PNG", "Unduh PNG", "Descargue el PNG"),
            "s5b": L("Keep the WebP until you have opened the PNG.", "打开 PNG 之前留着 WebP。", "打開 PNG 之前留著 WebP。", "PNGを開くまでWebPを残す。", "PNG를 열 때까지 WebP를 남기세요.", "Giữ WebP đến khi đã mở PNG.", "Simpan WebP sampai PNG terbuka.", "Conserve el WebP hasta haber abierto el PNG."),
            "s6t": L("Open it in the destination app", "在目标软件里打开", "在目標軟體裡打開", "送り先のアプリで開く", "받는 앱에서 열기", "Mở trong app đích", "Buka di app tujuan", "Ábralo en la app de destino"),
            "s6b": L("If it still fails, you sent the WebP by mistake. If the background turned solid, you exported JPG.", "还是打不开，多半发错成 WebP。底变成实色，就是导出成 JPG 了。", "還是打不開，多半傳錯成 WebP。底變成實色，就是匯出成 JPG 了。", "まだダメならWebPを送っている。背景が塗りつぶされたらJPGで出した。", "여전히 안 열리면 WebP를 보낸 것입니다. 배경이 꽉 찼으면 JPG로 보낸 것입니다.", "Vẫn fail thì bạn gửi nhầm WebP. Nền đặc thì bạn xuất JPG.", "Masih gagal: Anda kirim WebP. Latar jadi solid: Anda ekspor JPG.", "Si sigue fallando, envió el WebP. Si el fondo se rellenó, exportó JPG."),
            "diagram1": L("WebP is smaller. PNG is accepted more widely and can keep a clear background.", "WebP 更小。PNG 更通用，还能留透明底。", "WebP 更小。PNG 更通用，還能留透明底。", "WebPは小さい。PNGは通り、透明も残せる。", "WebP는 작고 PNG는 더 통하며 투명을 남길 수 있습니다.", "WebP nhỏ hơn. PNG phổ biến hơn và giữ nền trong.", "WebP lebih kecil. PNG lebih diterima dan bisa jaga latar tembus.", "WebP pesa menos. PNG se acepta más y puede conservar el fondo."),
            "diagram2": L("Drop WebP, pick PNG, open the result. Do not pick JPG if you need transparency.", "拖入 WebP，选 PNG，打开结果。要透明就不要选 JPG。", "拖入 WebP，選 PNG，打開結果。要透明就不要選 JPG。", "WebPを入れPNGを選び開く。透明が要るならJPGは選ばない。", "WebP를 넣고 PNG를 고른 뒤 여세요. 투명이 필요하면 JPG를 고르지 마세요.", "Thả WebP, chọn PNG, mở kết quả. Cần trong thì đừng chọn JPG.", "Letakkan WebP, pilih PNG, buka. Butuh tembus: jangan pilih JPG.", "Suelte el WebP, elija PNG y ábralo. No elija JPG si necesita transparencia."),
        },
        {
            "q1": L("Can I convert WebP to PNG free online?", "可以免费在线把 WebP 转成 PNG 吗？", "可以免費線上把 WebP 轉成 PNG 嗎？", "WebPをPNGに無料で変換できる？", "WebP를 PNG로 무료 변환할 수 있나요?", "Đổi WebP sang PNG miễn phí online được không?", "Bisa ubah WebP ke PNG gratis online?", "¿Puedo pasar WebP a PNG gratis en línea?"),
            "a1": L("Yes. cv.cm converts in this tab. Nothing is uploaded.", "可以。cv.cm 在当前标签页转换，不上传。", "可以。cv.cm 在目前分頁轉換，不上傳。", "できる。このタブで変換。アップロードなし。", "됩니다. 이 탭에서 변환합니다. 업로드 없음.", "Được. cv.cm đổi trong tab này, không tải lên.", "Ya. cv.cm mengubah di tab ini. Tidak diunggah.", "Sí. cv.cm convierte en esta pestaña. Nada se sube."),
            "q2": L("Why did Chrome save a WebP?", "为什么 Chrome 存成了 WebP？", "為什麼 Chrome 存成了 WebP？", "ChromeがWebPを保存するのはなぜ？", "Chrome이 WebP를 저장하는 이유는?", "Vì sao Chrome lưu WebP?", "Kenapa Chrome menyimpan WebP?", "¿Por qué Chrome guardó un WebP?"),
            "a2": L("Many sites serve WebP because it is smaller. Save as PNG here when the destination rejects WebP.", "网站为了体积常用 WebP。对方不认时，在这里另存 PNG。", "網站為了體積常用 WebP。對方不認時，在這裡另存 PNG。", "サイトが小さいWebPを出す。先が拒むならここでPNGにする。", "사이트가 용량 때문에 WebP를 줍니다. 상대가 거부하면 여기서 PNG로 저장하세요.", "Nhiều site dùng WebP vì nhẹ. Đích từ chối thì lưu PNG ở đây.", "Situs memakai WebP karena lebih kecil. Jika ditolak, simpan PNG di sini.", "Muchos sitios sirven WebP porque pesa menos. Si el destino lo rechaza, guárdelo como PNG aquí."),
            "q3": L("Will transparency survive?", "透明底还在吗？", "透明底還在嗎？", "透明は残る？", "투명이 남나요?", "Nền trong còn không?", "Transparansi tetap ada?", "¿Se conserva la transparencia?"),
            "a3": L("Yes if you export PNG. JPG will fill the background.", "导出 PNG 就还在。JPG 会填死背景。", "匯出 PNG 就還在。JPG 會填死背景。", "PNGなら残る。JPGは背景を埋める。", "PNG로 보내면 남습니다. JPG는 배경을 메웁니다.", "Xuất PNG thì còn. JPG sẽ lấp nền.", "Ya jika ekspor PNG. JPG mengisi latar.", "Sí si exporta PNG. JPG rellena el fondo."),
            "q4": L("Are files uploaded?", "会上传吗？", "會上傳嗎？", "アップロードされる？", "업로드되나요?", "Có tải lên không?", "Apakah diunggah?", "¿Se suben los archivos?"),
            "a4": L("No. Closing the tab discards them.", "不会。关掉标签页就没了。", "不會。關掉分頁就沒了。", "しない。タブを閉じると消える。", "아니요. 탭을 닫으면 사라집니다.", "Không. Đóng tab là mất.", "Tidak. Tutup tab, hilang.", "No. Al cerrar la pestaña se pierden."),
            "q5": L("Can I convert WebP to JPG instead?", "能不能转成 JPG？", "能不能轉成 JPG？", "JPGにもできる？", "JPG로도 되나요?", "Đổi WebP sang JPG được không?", "Bisa WebP ke JPG?", "¿Puedo pasar WebP a JPG?"),
            "a5": L("Yes. Pick JPG if you want a smaller photo and do not need transparency.", "可以。要更小、不要透明就选 JPG。", "可以。要更小、不要透明就選 JPG。", "できる。小さくて透明が不要ならJPG。", "됩니다. 더 작고 투명이 필요 없으면 JPG를 고르세요.", "Được. Muốn nhỏ hơn và không cần nền trong thì chọn JPG.", "Ya. Pilih JPG jika ingin lebih kecil dan tanpa transparansi.", "Sí. Elija JPG si quiere menos peso y no necesita transparencia."),
        },
    ),
    "resize-image": lesson(
        {
            "name": L("How to resize or compress an image", "怎么缩放或压缩图片", "怎麼縮放或壓縮圖片", "画像のリサイズと圧縮", "이미지 크기 조절·압축", "Cách thu nhỏ hoặc nén ảnh", "Cara ubah ukuran atau kompres gambar", "Cómo redimensionar o comprimir una imagen"),
            "blurb": L("Set a real pixel cap or file-size cap, then open the download at 100%.", "对准真实的像素或体积上限，下载后用 100% 打开看。", "對準真實的像素或體積上限，下載後用 100% 打開看。", "本当の画素または容量の上限に合わせ、100%で開く。", "실제 픽셀 또는 용량 한도에 맞춘 뒤 100%로 여세요.", "Khớp giới hạn pixel hoặc dung lượng thật, rồi mở bản tải ở 100%.", "Cocokkan batas piksel atau ukuran nyata, lalu buka unduhan di 100%.", "Ajuste a un tope real de píxeles o de peso y ábralo al 100%."),
            "title": L("How to resize or compress an image", "怎么缩放或压缩图片", "怎麼縮放或壓縮圖片", "画像をリサイズ・圧縮する方法", "이미지 크기 조절·압축하는 법", "Cách thu nhỏ hoặc nén ảnh", "Cara ubah ukuran atau kompres gambar", "Cómo redimensionar o comprimir una imagen"),
            "lead": L("Smaller pixels and a smaller file are different jobs. You will set a real size, pick JPEG quality if needed, then compare the download to the original.", "像素变小和文件变小不是一回事。对准真实上限，必要时调 JPEG 质量，再和原图比。", "像素變小和檔變小不是一回事。對準真實上限，必要時調 JPEG 品質，再和原圖比。", "画素を小さくすることとファイルを小さくすることは別。上限を決め、必要ならJPEG品質を下げ、元と比べる。", "픽셀을 줄이는 일과 용량을 줄이는 일은 다릅니다. 실제 한도를 정하고 필요하면 JPEG 품질을 낮춘 뒤 원본과 비교하세요.", "Pixel nhỏ hơn và file nhẹ hơn là hai việc. Đặt kích thước thật, chỉnh JPEG nếu cần, rồi so với bản gốc.", "Piksel lebih kecil dan file lebih kecil adalah pekerjaan berbeda. Set ukuran nyata, turunkan JPEG jika perlu, bandingkan dengan aslinya.", "Menos píxeles y menos peso son trabajos distintos. Fije un tamaño real, baje el JPEG si hace falta y compare con el original."),
            "result": L("An image that meets a pixel cap or a file-size cap, still sharp enough to read.", "符合像素或体积上限、放大仍能读的图。", "符合像素或體積上限、放大仍能讀的圖。", "画素または容量の上限に入り、まだ読める画像。", "픽셀 또는 용량 한도를 지키면서 여전히 읽을 수 있는 이미지.", "Ảnh đạt giới hạn pixel hoặc dung lượng, vẫn đủ nét để đọc.", "Gambar yang muat di batas piksel atau ukuran, masih cukup tajam.", "Una imagen que cabe en el tope de píxeles o de peso y sigue siendo legible."),
            "note": L("Open resize when the photo is on disk. Do not upscale a small photo and expect more detail. Nothing is uploaded.", "照片在磁盘上再打开缩放。不要把小图放大指望更清晰。不上传。", "照片在磁碟上再打開縮放。不要把小圖放大指望更清晰。不上傳。", "写真が手元にあってからリサイズを開く。小さい写真を拡大しても細部は増えない。アップロードなし。", "사진이 디스크에 있으면 크기 조절을 여세요. 작은 사진을 키운다고 디테일이 늘지 않습니다. 업로드 없음.", "Có ảnh trên đĩa thì mở thu nhỏ. Đừng phóng ảnh nhỏ rồi chờ nét hơn. Không tải lên.", "Foto di disk, baru buka resize. Jangan perbesar foto kecil mengharap lebih tajam. Tidak diunggah.", "Abra redimensionar cuando la foto esté en el disco. No agrande una foto pequeña esperando más detalle. Nada se sube."),
            "s1t": L("Write down the real limit", "写下真实上限", "寫下真實上限", "本当の上限を書く", "실제 한도를 적기", "Ghi giới hạn thật", "Tulis batas nyata", "Anote el límite real"),
            "s1b": L("A form may want 1920 on the long edge. Email may want under 2 MB. An avatar may want 400×400. Pixels and kilobytes are not the same knob.", "表单常要长边 1920。邮箱可能要小于 2 MB。头像可能是 400×400。像素和体积不是一个旋钮。", "表單常要長邊 1920。信箱可能要小於 2 MB。頭像可能是 400×400。像素和體積不是一個旋鈕。", "提出は長辺1920、メールは2MB未満、アイコンは400×400など。画素とキロバイトは別のつまみ。", "서류는 긴 변 1920, 이메일은 2MB 이하, 아바타는 400×400일 수 있습니다. 픽셀과 용량은 다른 조절입니다.", "Form có thể cần cạnh dài 1920. Email dưới 2 MB. Avatar 400×400. Pixel và kilobyte không cùng một núm.", "Formulir mungkin 1920 di sisi panjang. Email di bawah 2 MB. Avatar 400×400. Piksel dan kilobyte bukan tombol yang sama.", "Un formulario puede pedir 1920 en el lado largo. El correo, menos de 2 MB. Un avatar, 400×400. Píxeles y kilos no son la misma perilla."),
            "s2t": L("Open resize & compress on cv.cm", "打开 cv.cm 的缩放压缩", "打開 cv.cm 的縮放壓縮", "cv.cmのリサイズを開く", "cv.cm 크기 조절을 열기", "Mở thu nhỏ & nén trên cv.cm", "Buka resize di cv.cm", "Abra redimensionar en cv.cm"),
            "s2b": L("Work stays in this tab. Closing it discards the photo.", "处理留在当前标签页。关掉就没了。", "處理留在目前分頁。關掉就沒了。", "このタブで処理。閉じると消える。", "이 탭에서 처리합니다. 닫으면 사라집니다.", "Xử lý trong tab này. Đóng là mất.", "Proses di tab ini. Tutup, hilang.", "El trabajo queda en esta pestaña. Al cerrarla se pierde."),
            "s3t": L("Drop the photo", "拖入照片", "拖入照片", "写真をドロップ", "사진을 넣기", "Thả ảnh", "Letakkan foto", "Suelte la foto"),
            "s3b": L("If the preview is blank, convert HEIC to JPG first, then come back.", "预览空白，先把 HEIC 转成 JPG 再回来。", "預覽空白，先把 HEIC 轉成 JPG 再回來。", "プレビューが空なら先にHEICをJPGにして戻る。", "미리보기가 비면 HEIC를 JPG로 바꾼 뒤 돌아오세요.", "Xem trước trống thì đổi HEIC sang JPG rồi quay lại.", "Pratinjau kosong: ubah HEIC ke JPG dulu, lalu kembali.", "Si la vista está en blanco, pase HEIC a JPG y vuelva."),
            "s4t": L("Set width and height with the lock on", "开着锁定设宽高", "開著鎖定設寬高", "ロックしたまま幅と高さを入れる", "잠금을 켠 채 너비와 높이 설정", "Đặt rộng và cao khi khóa tỉ lệ", "Set lebar dan tinggi dengan gembok menyala", "Fije ancho y alto con el candado puesto"),
            "s4b": L("Or cap the long edge. Unlock only if you mean to stretch. Upscaling will not invent detail.", "或限制长边。只有故意拉扁才解锁。放大不会凭空变清晰。", "或限制長邊。只有故意拉扁才解鎖。放大不會憑空變清晰。", "または長辺を上限に。伸ばすつもりだけロック解除。拡大しても細部は増えない。", "또는 긴 변을 제한하세요. 늘리려는 때만 잠금을 끄세요. 키운다고 디테일이 생기지 않습니다.", "Hoặc giới hạn cạnh dài. Chỉ mở khóa nếu cố ý kéo méo. Phóng to không tạo thêm chi tiết.", "Atau batasi sisi panjang. Buka gembok hanya jika memang meregang. Membesar tidak menambah detail.", "O limite el lado largo. Quite el candado solo si quiere estirar. Ampliar no inventa detalle."),
            "s5t": L("If you need a smaller file, export JPEG and lower quality until it fits", "要更小的文件，就导出 JPEG，把质量降到刚够塞进上限", "要更小的檔，就匯出 JPEG，把品質降到剛夠塞進上限", "ファイルを小さくするならJPEGで品質を下げ、上限に入れる。", "용량을 줄이려면 JPEG로 보내고 한도에 들어갈 때까지 품질을 낮추세요.", "Cần file nhẹ thì xuất JPEG và hạ chất lượng đến khi lọt giới hạn.", "Butuh file lebih kecil: ekspor JPEG dan turunkan kualitas sampai muat.", "Si necesita menos peso, exporte JPEG y baje la calidad hasta que quepa."),
            "s5b": L("Watch the size estimate. PNG will not shrink much. Pick the largest file that still fits.", "看体积估算。PNG 压不了多少。选还能塞进上限的最大文件。", "看體積估算。PNG 壓不了多少。選還能塞進上限的最大檔。", "サイズ見積もりを見る。PNGはあまり小さくならない。上限に入る最大を選ぶ。", "용량 추정을 보세요. PNG는 잘 안 줄어듭니다. 한도에 들어가는 가장 큰 파일을 고르세요.", "Xem ước lượng dung lượng. PNG hầu như không nhỏ. Chọn file lớn nhất vẫn lọt.", "Lihat perkiraan ukuran. PNG hampir tidak mengecil. Pilih file terbesar yang masih muat.", "Mire el tamaño estimado. PNG apenas encoge. Elija el archivo más grande que aún cabe."),
            "s6t": L("Download and compare at 100%", "下载，用 100% 对比", "下載，用 100% 對比", "保存して100%で比べる", "받아 100%로 비교", "Tải về và so ở 100%", "Unduh dan bandingkan di 100%", "Descargue y compare al 100%"),
            "s6b": L("If type smears, go back one quality step. A thumbnail can look fine while the full image does not.", "字发糊就回退一档质量。缩略图好看，全图不一定好看。", "字發糊就回退一檔品質。縮圖好看，全圖不一定好看。", "文字が潰れたら品質を一段戻す。サムネは良くても実寸は違う。", "글자가 뭉개지면 품질을 한 단계 올리세요. 썸네일은 괜찮은데 원본은 아닐 수 있습니다.", "Chữ nhòe thì lùi một nấc chất lượng. Hình nhỏ ổn chưa chắc bản đầy đủ ổn.", "Teks pecah: naikkan satu tingkat kualitas. Thumbnail bagus, penuh belum tentu.", "Si el texto se corre, suba un punto de calidad. La miniatura puede verse bien y la imagen no."),
            "diagram1": L("Pixels vs kilobytes. A 4000px photo can still be a huge JPEG.", "像素对上体积。4000 像素的照片仍可能是很大的 JPEG。", "像素對上體積。4000 像素的照片仍可能是很大的 JPEG。", "画素とキロバイト。4000pxでもJPEGは重いことがある。", "픽셀 대 용량. 4000px 사진도 JPEG가 클 수 있습니다.", "Pixel khác kilobyte. Ảnh 4000px vẫn có thể là JPEG rất nặng.", "Piksel vs kilobyte. Foto 4000px masih bisa JPEG besar.", "Píxeles frente a kilos. Una foto de 4000 px aún puede ser un JPEG enorme."),
            "diagram2": L("Keep the aspect lock. Then pick the largest file that still fits.", "锁住比例。再选还能塞进上限的最大文件。", "鎖住比例。再選還能塞進上限的最大檔。", "比率ロックを維持。上限に入る最大を選ぶ。", "비율 잠금을 유지한 뒤 한도에 들어가는 가장 큰 파일을 고르세요.", "Khóa tỉ lệ. Rồi chọn file lớn nhất vẫn lọt.", "Kunci rasio. Lalu pilih file terbesar yang masih muat.", "Mantenga el candado de proporción. Luego elija el archivo más grande que aún cabe."),
        },
        {
            "q1": L("How do I resize an image without Photoshop?", "不用 Photoshop 怎么改尺寸？", "不用 Photoshop 怎麼改尺寸？", "Photoshopなしでリサイズは？", "포토샵 없이 크기 조절하려면?", "Thu nhỏ ảnh không cần Photoshop?", "Resize tanpa Photoshop?", "¿Cómo redimensiono sin Photoshop?"),
            "a1": L("Drop the photo on cv.cm resize in this tab. Set pixels, download. Nothing is uploaded.", "把照片拖进 cv.cm 的缩放，设像素，下载。不上传。", "把照片拖進 cv.cm 的縮放，設像素，下載。不上傳。", "このタブのリサイズにドロップし画素を入れて保存。アップロードなし。", "이 탭의 크기 조절에 사진을 넣고 픽셀을 정한 뒤 받으세요. 업로드 없음.", "Thả ảnh vào thu nhỏ cv.cm trong tab này, đặt pixel, tải. Không tải lên.", "Letakkan foto di resize cv.cm di tab ini, set piksel, unduh. Tidak diunggah.", "Suelte la foto en redimensionar de cv.cm, fije píxeles y descargue. Nada se sube."),
            "q2": L("How do I compress a JPG for email?", "怎么把 JPG 压到能发邮件？", "怎麼把 JPG 壓到能發郵件？", "メール用にJPGを小さくするには？", "이메일용으로 JPG를 줄이려면?", "Nén JPG để gửi email?", "Kompres JPG untuk email?", "¿Cómo comprimo un JPG para el correo?"),
            "a2": L("Export JPEG and lower quality until it is under the cap. Then open a real pixel at 100%.", "导出 JPEG，把质量降到低于上限，再用 100% 看一个真实像素。", "匯出 JPEG，把品質降到低於上限，再用 100% 看一個真實像素。", "JPEGで品質を下げ上限以下にし、100%で実画素を見る。", "JPEG로 보내고 한도 아래로 품질을 낮춘 뒤 100%로 보세요.", "Xuất JPEG, hạ chất lượng đến dưới hạn, rồi mở 100%.", "Ekspor JPEG, turunkan kualitas sampai di bawah batas, buka 100%.", "Exporte JPEG, baje la calidad hasta el tope y mírelo al 100%."),
            "q3": L("Should I unlock the aspect ratio?", "要不要解开比例锁定？", "要不要解開比例鎖定？", "比率ロックは外す？", "비율 잠금을 끌까요?", "Có nên mở khóa tỉ lệ?", "Lepas gembok rasio?", "¿Debo quitar el candado de proporción?"),
            "a3": L("No, unless you mean to stretch. Stretching looks wrong on faces and logos.", "不要，除非你故意拉扁。人脸和 Logo 一拉就难看。", "不要，除非你故意拉扁。人臉和 Logo 一拉就難看。", "伸ばすつもり以外は外さない。顔やロゴが歪む。", "늘리려는 게 아니면 끄지 마세요. 얼굴과 로고가 찌그러집니다.", "Đừng, trừ khi cố ý kéo méo. Mặt và logo sẽ xấu.", "Jangan, kecuali memang meregang. Wajah dan logo jadi jelek.", "No, salvo que quiera estirar. Caras y logos se ven mal."),
            "q4": L("Are photos uploaded?", "会上传吗？", "會上傳嗎？", "アップロードされる？", "업로드되나요?", "Có tải lên không?", "Apakah diunggah?", "¿Se suben las fotos?"),
            "a4": L("No. Closing the tab discards them.", "不会。关掉标签页就没了。", "不會。關掉分頁就沒了。", "しない。タブを閉じると消える。", "아니요. 탭을 닫으면 사라집니다.", "Không. Đóng tab là mất.", "Tidak. Tutup tab, hilang.", "No. Al cerrar la pestaña se pierden."),
            "q5": L("Can I resize several photos at once?", "能一次缩多张吗？", "能一次縮多張嗎？", "まとめてリサイズできる？", "여러 장을 한 번에?", "Thu nhỏ nhiều ảnh một lúc?", "Resize banyak foto sekaligus?", "¿Puedo redimensionar varias a la vez?"),
            "a5": L("This lesson covers one photo. Convert or watermark can batch; come back per file if you need exact pixels.", "这篇按一张讲。格式转换和水印能批量；要精确像素就一张张来。", "這篇按一張講。格式轉換和水印能批量；要精確像素就一張張來。", "このレッスンは1枚。一括は変換や透かし。正確な画素なら1枚ずつ。", "이 레슨은 한 장입니다. 일괄은 변환이나 워터마크. 정확한 픽셀이면 한 장씩.", "Bài này cho một ảnh. Đổi định dạng và watermark làm hàng loạt; cần đúng pixel thì từng tấm.", "Pelajaran ini satu foto. Batch ada di konversi atau watermark; piksel tepat: satu-satu.", "Esta guía es de una foto. El lote está en convertir o marca de agua; píxeles exactos, una a una."),
        },
    ),
    "split-pdf": lesson(
        {
            "name": L("How to split a PDF", "怎么拆分 PDF", "怎麼拆分 PDF", "PDFを分割する方法", "PDF 나누는 법", "Cách tách PDF", "Cara pecah PDF", "Cómo dividir un PDF"),
            "blurb": L("Every page as a file, or just pages 1–3. Download, then count.", "每一页一份文件，或只要 1–3 页。下载后再数。", "每一頁一份檔，或只要 1–3 頁。下載後再數。", "全ページを別ファイル、または1–3ページだけ。保存して数える。", "페이지마다 파일, 또는 1–3페이지만. 받은 뒤 세세요.", "Mỗi trang một file, hoặc chỉ trang 1–3. Tải rồi đếm.", "Tiap halaman satu file, atau hanya 1–3. Unduh, lalu hitung.", "Cada página en un archivo, o solo 1–3. Descargue y cuente."),
            "title": L("How to split a PDF", "怎么拆分 PDF", "怎麼拆分 PDF", "PDFを分割する方法", "PDF 나누는 법", "Cách tách PDF", "Cara pecah PDF", "Cómo dividir un PDF"),
            "lead": L("You need pages as separate files, or only a range. Split in this tab, then open the download and count.", "你要每一页单独成文件，或只要一段页码。在当前标签页拆完，再打开下载数页数。", "你要每一頁單獨成檔，或只要一段頁碼。在目前分頁拆完，再打開下載數頁數。", "ページを別ファイルにするか、範囲だけ残す。このタブで分割し、保存して数える。", "페이지를 따로 두거나 구간만 남깁니다. 이 탭에서 나눈 뒤 받은 파일을 열고 세세요.", "Bạn cần mỗi trang một file, hoặc chỉ một khoảng. Tách trong tab này, mở bản tải và đếm.", "Anda butuh halaman terpisah, atau hanya rentang. Pecah di tab ini, buka unduhan dan hitung.", "Necesita páginas sueltas, o solo un rango. Divida aquí, abra la descarga y cuente."),
            "result": L("One PDF per page in a ZIP, or one PDF with just the range you typed.", "ZIP 里每页一份 PDF，或一份只含你输入页码的 PDF。", "ZIP 裡每頁一份 PDF，或一份只含你輸入頁碼的 PDF。", "ZIPにページごとのPDF、または指定範囲だけの1ファイル。", "ZIP 안에 페이지마다 PDF, 또는 입력한 구간만 있는 PDF 하나.", "ZIP với mỗi trang một PDF, hoặc một PDF chỉ gồm khoảng bạn gõ.", "ZIP berisi satu PDF per halaman, atau satu PDF hanya berisi rentang yang diketik.", "Un PDF por página en un ZIP, o un PDF solo con el rango escrito."),
            "note": L("Open split PDF when the file is on disk. Locked PDFs often cannot split until unlocked. Nothing is uploaded.", "文件在磁盘上再打开拆分。加密 PDF 要先解锁。不上传。", "檔在磁碟上再打開拆分。加密 PDF 要先解鎖。不上傳。", "ファイルが手元にあってから分割を開く。暗号化は先に解除。アップロードなし。", "파일이 디스크에 있으면 나누기를 여세요. 암호 PDF는 먼저 해제. 업로드 없음.", "Có file trên đĩa thì mở tách PDF. PDF khóa phải mở khóa trước. Không tải lên.", "File di disk, baru buka pecah PDF. PDF terkunci harus dibuka dulu. Tidak diunggah.", "Abra dividir PDF cuando el archivo esté en el disco. Los cifrados hay que desbloquearlos. Nada se sube."),
            "s1t": L("Decide every page vs a range", "先选逐页拆，还是只要一段", "先選逐頁拆，還是只要一段", "全ページか範囲か", "페이지마다인지 구간인지", "Chọn từng trang hay một khoảng", "Pilih tiap halaman atau rentang", "Decida todas las páginas o un rango"),
            "s1b": L("Each page as its own PDF if you will send them around. A range like 1-3,5 if you only need those pages in one file.", "要分头发送就逐页拆。只要 1-3 和 5 页，就填范围，合成一份。", "要分頭傳送就逐頁拆。只要 1-3 和 5 頁，就填範圍，合成一份。", "ばらして送るならページごと。1-3と5だけなら範囲を1ファイルに。", "따로 보낼 거면 페이지마다. 1-3과 5만 필요하면 구간을 한 파일로.", "Gửi rải thì tách từng trang. Chỉ cần 1-3 và 5 thì gõ khoảng, một file.", "Kirim terpisah: tiap halaman. Hanya 1-3 dan 5: ketik rentang, satu file.", "Si las va a enviar sueltas, una por página. Si solo quiere 1-3 y 5, un rango en un archivo."),
            "s2t": L("Open split PDF on cv.cm", "打开 cv.cm 的拆分 PDF", "打開 cv.cm 的拆分 PDF", "cv.cmのPDF分割を開く", "cv.cm PDF 나누기를 열기", "Mở tách PDF trên cv.cm", "Buka pecah PDF di cv.cm", "Abra dividir PDF en cv.cm"),
            "s2b": L("Work stays in this tab.", "拆分留在当前标签页。", "拆分留在目前分頁。", "このタブで分割。", "이 탭에서 나눕니다.", "Tách trong tab này.", "Pecah di tab ini.", "La división queda en esta pestaña."),
            "s3t": L("Drop the PDF and note the page count", "拖入 PDF，看总页数", "拖入 PDF，看總頁數", "PDFを入れてページ数を見る", "PDF를 넣고 쪽수를 보기", "Thả PDF và xem số trang", "Letakkan PDF dan lihat jumlah halaman", "Suelte el PDF y mire el recuento"),
            "s3b": L("If nothing appears, the file may be locked. Unlock it first.", "什么都没有，多半是加密。先解锁。", "什麼都沒有，多半是加密。先解鎖。", "何も出なければ暗号化。先に解除。", "아무 것도 안 나오면 암호입니다. 먼저 해제하세요.", "Không hiện gì thì file bị khóa. Mở khóa trước.", "Tidak muncul: terkunci. Buka dulu.", "Si no aparece nada, está cifrado. Desbloquéelo."),
            "s4t": L("Choose every page, or type 1-3,5", "选逐页，或输入 1-3,5", "選逐頁，或輸入 1-3,5", "全ページか、1-3,5と入力", "페이지마다, 또는 1-3,5 입력", "Chọn từng trang, hoặc gõ 1-3,5", "Pilih tiap halaman, atau ketik 1-3,5", "Elija cada página, o escriba 1-3,5"),
            "s4b": L("Ranges are inclusive. 1-3 is three pages. A comma starts another span.", "范围含两端。1-3 是三页。逗号另起一段。", "範圍含兩端。1-3 是三頁。逗號另起一段。", "範囲は両端を含む。1-3は3ページ。カンマで次の区間。", "구간은 양끝을 포함합니다. 1-3은 3쪽. 쉼표는 다음 구간.", "Khoảng gồm hai đầu. 1-3 là ba trang. Dấu phẩy mở đoạn khác.", "Rentang inklusif. 1-3 adalah tiga halaman. Koma memulai rentang lain.", "Los rangos incluyen los extremos. 1-3 son tres páginas. La coma abre otro tramo."),
            "s5t": L("Download", "下载", "下載", "保存", "받기", "Tải", "Unduh", "Descargue"),
            "s5b": L("Each-page mode packs a ZIP. A range is usually one PDF.", "逐页会打成 ZIP。范围通常是一份 PDF。", "逐頁會打成 ZIP。範圍通常是一份 PDF。", "ページごとはZIP。範囲はだいたい1つのPDF。", "페이지마다는 ZIP. 구간은 보통 PDF 하나.", "Từng trang ra ZIP. Một khoảng thường là một PDF.", "Mode tiap halaman: ZIP. Rentang biasanya satu PDF.", "Cada página va en un ZIP. Un rango suele ser un PDF."),
            "s6t": L("Open and count", "打开再数", "打開再數", "開いて数える", "열고 세기", "Mở và đếm", "Buka dan hitung", "Abra y cuente"),
            "s6b": L("Ten pages split each-page should be ten files. A range 1-3 should be three pages in one PDF.", "10 页逐页拆应是 10 个文件。范围 1-3 应是一份 3 页的 PDF。", "10 頁逐頁拆應是 10 個檔。範圍 1-3 應是一份 3 頁的 PDF。", "10ページをページごとなら10ファイル。1-3なら3ページの1PDF。", "10쪽을 페이지마다면 파일 10개. 1-3이면 3쪽짜리 PDF 하나.", "10 trang tách từng trang phải ra 10 file. Khoảng 1-3 phải là PDF 3 trang.", "10 halaman tiap-halaman: 10 file. Rentang 1-3: satu PDF 3 halaman.", "Diez páginas sueltas deben ser diez archivos. El rango 1-3, un PDF de tres páginas."),
            "diagram1": L("Every page as its own PDF, packed in a ZIP.", "每一页一份 PDF，打进 ZIP。", "每一頁一份 PDF，打進 ZIP。", "各ページがPDFになりZIPに入る。", "페이지마다 PDF가 되어 ZIP에 들어갑니다.", "Mỗi trang một PDF, gói trong ZIP.", "Tiap halaman jadi PDF, dikemas ZIP.", "Cada página es un PDF, empaquetado en un ZIP."),
            "diagram2": L("A range like 1-3,5 keeps those pages in one file.", "1-3,5 这种范围，页还在同一份文件里。", "1-3,5 這種範圍，頁還在同一份檔裡。", "1-3,5のような範囲は1ファイルに残る。", "1-3,5 같은 구간은 한 파일에 남습니다.", "Khoảng 1-3,5 giữ các trang đó trong một file.", "Rentang 1-3,5 menjaga halaman itu dalam satu file.", "Un rango como 1-3,5 deja esas páginas en un archivo."),
        },
        {
            "q1": L("How do I split a PDF without Adobe?", "不用 Adobe 怎么拆 PDF？", "不用 Adobe 怎麼拆 PDF？", "AdobeなしでPDF分割は？", "어도비 없이 PDF를 나누려면?", "Tách PDF không cần Adobe?", "Pecah PDF tanpa Adobe?", "¿Cómo divido un PDF sin Adobe?"),
            "a1": L("Drop it on cv.cm split in this tab. Choose each page or a range. Nothing is uploaded.", "拖进 cv.cm 的拆分，选逐页或范围。不上传。", "拖進 cv.cm 的拆分，選逐頁或範圍。不上傳。", "このタブの分割にドロップし、全ページか範囲。アップロードなし。", "이 탭의 나누기에 넣고 페이지마다 또는 구간을 고르세요. 업로드 없음.", "Thả vào tách cv.cm trong tab này. Chọn từng trang hoặc khoảng. Không tải lên.", "Letakkan di pecah cv.cm di tab ini. Pilih tiap halaman atau rentang. Tidak diunggah.", "Suelte el PDF en dividir de cv.cm. Elija cada página o un rango. Nada se sube."),
            "q2": L("Can I extract just pages 1 to 3?", "能不能只要第 1 到 3 页？", "能不能只要第 1 到 3 頁？", "1–3ページだけ抜ける？", "1–3페이지만 빼나요?", "Lấy đúng trang 1 đến 3?", "Ambil hanya halaman 1–3?", "¿Puedo extraer solo las páginas 1 a 3?"),
            "a2": L("Yes. Type 1-3 and download one PDF with those pages.", "可以。输入 1-3，下载一份只含这三页的 PDF。", "可以。輸入 1-3，下載一份只含這三頁的 PDF。", "できる。1-3と入れてそのページだけのPDFを保存。", "됩니다. 1-3을 입력하고 그 페이지만 있는 PDF를 받으세요.", "Được. Gõ 1-3, tải một PDF chỉ gồm các trang đó.", "Ya. Ketik 1-3 dan unduh satu PDF berisi halaman itu.", "Sí. Escriba 1-3 y descargue un PDF con esas páginas."),
            "q3": L("What about a password-protected PDF?", "有密码的 PDF 呢？", "有密碼的 PDF 呢？", "パスワード付きは？", "암호 PDF는?", "PDF có mật khẩu thì sao?", "PDF berkatasandi?", "¿Y un PDF con contraseña?"),
            "a3": L("Encrypted files often cannot split here. Unlock them first.", "加密文件这里经常拆不了。请先解锁。", "加密檔這裡經常拆不了。請先解鎖。", "暗号化はここで失敗しやすい。先に解除。", "암호화 파일은 여기서 자주 안 나뉩니다. 먼저 해제하세요.", "File mã hóa thường không tách được. Mở khóa trước.", "Terenkripsi sering gagal. Buka dulu.", "Los cifrados suelen fallar aquí. Desbloquéelos primero."),
            "q4": L("Are files uploaded?", "会上传吗？", "會上傳嗎？", "アップロードされる？", "업로드되나요?", "Có tải lên không?", "Apakah diunggah?", "¿Se suben los archivos?"),
            "a4": L("No. Splitting uses pdf-lib in this tab.", "不会。用 pdf-lib 在当前标签页拆。", "不會。用 pdf-lib 在目前分頁拆。", "しない。このタブのpdf-lib。", "아니요. 이 탭의 pdf-lib로 나눕니다.", "Không. pdf-lib trong tab này.", "Tidak. pdf-lib di tab ini.", "No. pdf-lib en esta pestaña."),
            "q5": L("Will bookmarks survive?", "书签还在吗？", "書籤還在嗎？", "しおりは残る？", "북마크가 남나요?", "Bookmark còn không?", "Bookmark tetap ada?", "¿Se conservan los marcadores?"),
            "a5": L("Pages are copied. Bookmarks and forms may be dropped.", "会复制页面。书签和表单可能会丢掉。", "會複製頁面。書籤和表單可能會丟掉。", "ページはコピー。しおりやフォームは落ちることがある。", "페이지는 복사됩니다. 북마크와 폼은 빠질 수 있습니다.", "Trang được chép. Bookmark và form có thể mất.", "Halaman disalin. Bookmark dan formulir bisa hilang.", "Se copian las páginas. Marcadores y formularios pueden perderse."),
        },
    ),
    "add-watermark": lesson(
        {
            "name": L("How to add a watermark to a photo", "怎么给照片加水印", "怎麼給照片加水印", "写真に透かしを入れる", "사진에 워터마크 넣기", "Cách gắn watermark lên ảnh", "Cara beri watermark pada foto", "Cómo añadir una marca de agua"),
            "blurb": L("Stamp a shop name or logo, set opacity, download, then check at 100%.", "盖店名或 Logo，调透明度，下载后用 100% 看一眼。", "蓋店名或 Logo，調透明度，下載後用 100% 看一眼。", "店名やロゴを入れ、不透明度を決め、100%で確認。", "가게 이름이나 로고를 찍고 투명도를 맞춘 뒤 100%로 보세요.", "Đóng tên shop hoặc logo, chỉnh mờ, tải, xem 100%.", "Cap nama toko atau logo, atur opacity, unduh, cek 100%.", "Ponga el nombre o el logo, ajuste la opacidad, descargue y mire al 100%."),
            "title": L("How to add a watermark to a photo", "怎么给照片加水印", "怎麼給照片加水印", "写真に透かしを入れる方法", "사진에 워터마크 넣는 법", "Cách gắn watermark lên ảnh", "Cara beri watermark pada foto", "Cómo añadir una marca de agua a una foto"),
            "lead": L("A mark nobody can read is useless; a mark that hides the product is also useless. You will stamp text or a logo in this tab and check it at 100%.", "看不清的印没用，挡住货的印也没用。在当前标签页盖文字或 Logo，再用 100% 看。", "看不清的印沒用，擋住貨的印也沒用。在目前分頁蓋文字或 Logo，再用 100% 看。", "読めない透かしは無用。商品を隠す透かしも無用。このタブで文字かロゴを入れ、100%で見る。", "안 읽히는 표시는 소용없고, 상품을 가리는 표시도 소용없습니다. 이 탭에서 글자나 로고를 찍고 100%로 보세요.", "Dấu không đọc được thì vô dụng; dấu che hàng cũng vô dụng. Đóng chữ hoặc logo trong tab này rồi xem 100%.", "Tanda yang tak terbaca sia-sia; yang menutupi barang juga. Cap teks atau logo di tab ini, cek 100%.", "Una marca ilegible no sirve; una que tapa el producto tampoco. Estampe texto o un logo aquí y mírelo al 100%."),
            "result": L("Photos with a readable mark. The unmarked originals stay on disk.", "带着能读印记的照片。没盖印的原图还在磁盘上。", "帶著能讀印記的照片。沒蓋印的原圖還在磁碟上。", "読める透かし入り。無印の原版はディスクに残る。", "읽히는 표시가 있는 사진. 표시 없는 원본은 디스크에 남습니다.", "Ảnh có dấu đọc được. Bản gốc chưa đóng vẫn trên đĩa.", "Foto dengan tanda terbaca. Asli tanpa cap tetap di disk.", "Fotos con una marca legible. Los originales sin marca siguen en el disco."),
            "note": L("This tool adds a mark. It will not remove someone else's watermark. Open it when the photos are on disk. Nothing is uploaded.", "这是盖印，不是去印。别人的水印去不掉。照片在磁盘上再打开。不上传。", "這是蓋印，不是去印。別人的浮水印去不掉。照片在磁碟上再打開。不上傳。", "入れる道具。他人の透かしは消せない。写真が手元にあってから開く。アップロードなし。", "넣는 도구입니다. 남의 워터마크는 못 지웁니다. 사진이 디스크에 있으면 여세요. 업로드 없음.", "Công cụ này gắn dấu, không gỡ dấu người khác. Có ảnh trên đĩa thì mở. Không tải lên.", "Alat ini menambah tanda, bukan menghapus milik orang. Foto di disk, baru buka. Tidak diunggah.", "Esta herramienta añade una marca. No quita la de otro. Ábrala con las fotos en el disco. Nada se sube."),
            "s1t": L("Decide text vs logo, corner vs tiled", "先选文字还是 Logo，角落还是斜铺", "先選文字還是 Logo，角落還是斜鋪", "文字かロゴか、隅かタイルか", "글자인지 로고인지, 모서리인지 타일인지", "Chữ hay logo, góc hay lát chéo", "Teks atau logo, sudut atau ubin", "Texto o logo, esquina o mosaico"),
            "s1b": L("Shop listings often tile a diagonal name. A single corner mark is quieter for a portrait. Do not copy another shop's mark.", "店主图常斜铺店名。人像用角落一枚更干净。不要盖别人的印。", "店主圖常斜鋪店名。人像用角落一枚更乾淨。不要蓋別人的印。", "出品写真は斜めタイルが多い。肖像は隅の1つが静か。他人の印は使わない。", "상품 사진은 가게 이름을 대각선으로 깔 때가 많습니다. 인물은 모서리 하나가 덜 시끄럽습니다. 남의 표시를 베끼지 마세요.", "Ảnh bán hàng thường lát chéo tên shop. Chân dung dùng một góc cho nhẹ. Đừng copy dấu shop khác.", "Listing toko sering ubin diagonal. Potret: satu sudut lebih tenang. Jangan salin tanda toko lain.", "Los anuncios suelen teselar el nombre en diagonal. Un retrato queda más limpio con una esquina. No copie la marca de otro."),
            "s2t": L("Open watermark on cv.cm", "打开 cv.cm 的水印", "打開 cv.cm 的浮水印", "cv.cmの透かしを開く", "cv.cm 워터마크를 열기", "Mở watermark trên cv.cm", "Buka watermark di cv.cm", "Abra marca de agua en cv.cm"),
            "s2b": L("Work stays in this tab. Batch is allowed.", "处理留在当前标签页。可以一次多张。", "處理留在目前分頁。可以一次多張。", "このタブで処理。まとめて可。", "이 탭에서 처리합니다. 여러 장 가능.", "Xử lý trong tab này. Được làm hàng loạt.", "Proses di tab ini. Boleh batch.", "El trabajo queda en esta pestaña. Se puede por lotes."),
            "s3t": L("Drop one photo or a batch", "拖入一张或一批", "拖入一張或一批", "1枚またはまとめてドロップ", "한 장 또는 여러 장 넣기", "Thả một ảnh hoặc một lô", "Letakkan satu foto atau batch", "Suelte una foto o un lote"),
            "s3b": L("Keep the unmarked originals. You are making copies.", "留着没盖印的原图。你在做副本。", "留著沒蓋印的原圖。你在做副本。", "無印の原版を残す。コピーを作っている。", "표시 없는 원본을 남기세요. 복사본을 만드는 일입니다.", "Giữ bản gốc chưa đóng. Bạn đang làm bản sao.", "Simpan asli tanpa cap. Anda membuat salinan.", "Conserve los originales sin marca. Está haciendo copias."),
            "s4t": L("Type the name or drop a logo, then set opacity", "输入店名或放入 Logo，再调透明度", "輸入店名或放入 Logo，再調透明度", "名前を入れるかロゴをドロップし、不透明度を決める", "이름 입력 또는 로고를 넣고 투명도 맞추기", "Gõ tên hoặc thả logo, rồi chỉnh độ mờ", "Ketik nama atau letakkan logo, lalu atur opacity", "Escriba el nombre o suelte un logo y ajuste la opacidad"),
            "s4b": L("High enough to read on a busy photo. Low enough to see the product. Tile if a corner mark is easy to crop off.", "花照片上也要能读，又不能挡住货。角落印容易被裁掉，就斜铺。", "花照片上也要能讀，又不能擋住貨。角落印容易被裁掉，就斜鋪。", "賑やかな写真でも読めて、商品は見える。隅は切られやすいのでタイル。", "복잡한 사진에서도 읽히고, 상품은 보여야 합니다. 모서리는 잘리기 쉬우니 타일로.", "Đủ đọc trên ảnh rối, đủ thấp để thấy hàng. Dấu góc dễ bị cắt thì lát chéo.", "Cukup terbaca di foto ramai, cukup rendah agar barang kelihatan. Tanda sudut gampang dipotong: pakai ubin.", "Lo bastante alta para leerse en una foto ocupada, lo bastante baja para ver el producto. Si la esquina se recorta fácil, tesélela."),
            "s5t": L("Download PNG, JPEG, or a ZIP", "下载 PNG、JPEG 或 ZIP", "下載 PNG、JPEG 或 ZIP", "PNG / JPEG / ZIPを保存", "PNG, JPEG 또는 ZIP 받기", "Tải PNG, JPEG hoặc ZIP", "Unduh PNG, JPEG, atau ZIP", "Descargue PNG, JPEG o un ZIP"),
            "s5b": L("JPEG is smaller for shop listings. PNG if the mark has a clear background.", "上架用 JPEG 更小。印本身有透明底就用 PNG。", "上架用 JPEG 更小。印本身有透明底就用 PNG。", "出品はJPEGが小さい。透かしに透明があるならPNG。", "상품 등록은 JPEG가 더 작습니다. 표시에 투명이 있으면 PNG.", "Đăng bán dùng JPEG nhẹ hơn. Dấu có nền trong thì PNG.", "Listing: JPEG lebih kecil. Tanda berlatar tembus: PNG.", "JPEG pesa menos para anuncios. PNG si la marca tiene fondo transparente."),
            "s6t": L("Open at 100%", "用 100% 打开", "用 100% 打開", "100%で開く", "100%로 열기", "Mở ở 100%", "Buka di 100%", "Ábralo al 100%"),
            "s6b": L("If the mark vanishes on a busy photo, raise contrast or tile it. If it hides the product, lower opacity.", "花照片上看不见，就提高对比或改斜铺。挡住货了，就降低透明度。", "花照片上看不見，就提高對比或改斜鋪。擋住貨了，就降低透明度。", "賑やかで消えるならコントラストかタイル。商品を隠すなら不透明度を下げる。", "복잡한 사진에서 사라지면 대비를 높이거나 타일로. 상품을 가리면 투명도를 낮추세요.", "Ảnh rối mà dấu biến thì tăng tương phản hoặc lát. Che hàng thì hạ mờ.", "Hilang di foto ramai: naikkan kontras atau ubin. Menutupi barang: turunkan opacity.", "Si desaparece en una foto ocupada, suba el contraste o tesélela. Si tapa el producto, baje la opacidad."),
            "diagram1": L("Corner mark vs tiled diagonal. Shop listings often tile.", "角落一枚对上斜铺。店主图常斜铺。", "角落一枚對上斜鋪。店主圖常斜鋪。", "隅の1つ対タイル。出品はタイルが多い。", "모서리 하나 대 대각선 타일. 상품 사진은 타일이 많습니다.", "Một góc so với lát chéo. Ảnh bán hàng thường lát.", "Satu sudut vs ubin diagonal. Listing toko sering ubin.", "Una esquina frente a un mosaico en diagonal. Los anuncios suelen teselar."),
            "diagram2": L("Opacity high enough to read, low enough to see the product.", "透明度：能读，又不挡货。", "透明度：能讀，又不擋貨。", "読めて商品が見える不透明度。", "읽히되 상품이 보이는 투명도.", "Đủ đọc, đủ thấp để thấy hàng.", "Cukup terbaca, cukup rendah agar barang kelihatan.", "Opacidad bastante para leerse, bastante baja para ver el producto."),
        },
        {
            "q1": L("How do I add a watermark without Photoshop?", "不用 Photoshop 怎么加水印？", "不用 Photoshop 怎麼加浮水印？", "Photoshopなしで透かしは？", "포토샵 없이 워터마크는?", "Gắn watermark không cần Photoshop?", "Watermark tanpa Photoshop?", "¿Cómo añado una marca sin Photoshop?"),
            "a1": L("Drop photos on cv.cm watermark in this tab. Type text or a logo, download. Nothing is uploaded.", "把照片拖进 cv.cm 水印，输入文字或 Logo，下载。不上传。", "把照片拖進 cv.cm 浮水印，輸入文字或 Logo，下載。不上傳。", "このタブの透かしにドロップし、文字かロゴを入れて保存。アップロードなし。", "이 탭의 워터마크에 사진을 넣고 글자나 로고를 입력한 뒤 받으세요. 업로드 없음.", "Thả ảnh vào watermark cv.cm trong tab này, gõ chữ hoặc logo, tải. Không tải lên.", "Letakkan foto di watermark cv.cm di tab ini, ketik teks atau logo, unduh. Tidak diunggah.", "Suelte las fotos en marca de agua de cv.cm, escriba texto o un logo y descargue. Nada se sube."),
            "q2": L("Can I watermark a batch of shop photos?", "能一批店图一起盖吗？", "能一批店圖一起蓋嗎？", "出品写真をまとめて？", "상품 사진을 한꺼번에?", "Gắn hàng loạt ảnh shop?", "Watermark batch foto toko?", "¿Puedo marcar un lote de fotos de tienda?"),
            "a2": L("Yes. Drop several, set one mark, download a ZIP.", "可以。拖入多张，盖同一枚印，下载 ZIP。", "可以。拖入多張，蓋同一枚印，下載 ZIP。", "できる。複数入れて同じ透かし、ZIPで保存。", "됩니다. 여러 장을 넣고 같은 표시를 찍은 뒤 ZIP으로 받으세요.", "Được. Thả nhiều ảnh, một dấu, tải ZIP.", "Ya. Letakkan beberapa, satu tanda, unduh ZIP.", "Sí. Suelte varias, una marca, descargue un ZIP."),
            "q3": L("Will this remove a watermark?", "能去水印吗？", "能去浮水印嗎？", "透かしは消せる？", "워터마크를 지울 수 있나요?", "Gỡ được watermark không?", "Bisa hapus watermark?", "¿Quita una marca de agua?"),
            "a3": L("No. This lesson only adds a mark. Removing someone else's mark is a different, often unwelcome, job.", "不能。这篇只盖印。去掉别人的印是另一件事，而且经常不该做。", "不能。這篇只蓋印。去掉別人的印是另一件事，而且經常不該做。", "できない。入れるだけ。他人の印を消す仕事ではない。", "아니요. 이 레슨은 넣기만 합니다. 남의 표시를 지우는 일은 다른 문제입니다.", "Không. Bài này chỉ gắn dấu. Gỡ dấu người khác là việc khác, thường không nên.", "Tidak. Pelajaran ini hanya menambah. Menghapus milik orang adalah pekerjaan lain.", "No. Esta guía solo añade. Quitar la marca de otro es otro trabajo, a menudo indeseable."),
            "q4": L("Are photos uploaded?", "会上传吗？", "會上傳嗎？", "アップロードされる？", "업로드되나요?", "Có tải lên không?", "Apakah diunggah?", "¿Se suben las fotos?"),
            "a4": L("No. Closing the tab discards them.", "不会。关掉标签页就没了。", "不會。關掉分頁就沒了。", "しない。タブを閉じると消える。", "아니요. 탭을 닫으면 사라집니다.", "Không. Đóng tab là mất.", "Tidak. Tutup tab, hilang.", "No. Al cerrar la pestaña se pierden."),
            "q5": L("Should I tile or use a corner?", "斜铺还是角落？", "斜鋪還是角落？", "タイルか隅か？", "타일인가요 모서리인가요?", "Lát chéo hay một góc?", "Ubin atau sudut?", "¿Teselar o una esquina?"),
            "a5": L("Tile if someone might crop the corner. A single corner is quieter on a portrait.", "怕被裁角落就斜铺。人像用角落一枚更干净。", "怕被裁角落就斜鋪。人像用角落一枚更乾淨。", "隅を切られそうならタイル。肖像は隅の1つが静か。", "모서리를 자를 수 있으면 타일. 인물은 모서리 하나가 덜 시끄럽습니다.", "Sợ bị cắt góc thì lát. Chân dung dùng một góc cho nhẹ.", "Kalau sudut bisa dipotong, ubin. Potret: satu sudut lebih tenang.", "Tesélela si pueden recortar la esquina. Un retrato queda más limpio con una sola."),
        },
    ),
    "remove-exif": lesson(
        {
            "name": L("How to remove EXIF / location from a photo", "怎么去掉照片里的定位和 EXIF", "怎麼去掉照片裡的定位和 EXIF", "写真から位置情報とEXIFを除く", "사진에서 위치·EXIF 제거", "Cách gỡ GPS / EXIF khỏi ảnh", "Cara hapus EXIF / lokasi dari foto", "Cómo quitar EXIF y la ubicación de una foto"),
            "blurb": L("Phones store GPS in the file. Export a clean copy, then drop the export to prove it is gone.", "手机把定位写进文件。导出一份干净的，再拖回来确认没了。", "手機把定位寫進檔。匯出一份乾淨的，再拖回來確認沒了。", "電話はGPSをファイルに書く。きれいなコピーを書き出し、再ドロップして消えたことを確認。", "폰은 GPS를 파일에 넣습니다. 깨끗한 복사본을 보낸 뒤 다시 넣어 없어졌는지 확인하세요.", "Điện thoại ghi GPS vào file. Xuất bản sạch, thả lại để chứng minh đã mất.", "Ponsel menyimpan GPS di file. Ekspor salinan bersih, taruh lagi untuk membuktikan hilang.", "El teléfono guarda GPS en el archivo. Exporte una copia limpia y suéltela otra vez para comprobarlo."),
            "title": L("How to remove EXIF / location from a photo", "怎么去掉照片里的定位和 EXIF", "怎麼去掉照片裡的定位和 EXIF", "位置情報とEXIFを除く方法", "사진에서 위치와 EXIF를 지우는 법", "Cách gỡ GPS / EXIF khỏi ảnh", "Cara hapus EXIF / lokasi dari foto", "Cómo quitar EXIF y la ubicación de una foto"),
            "lead": L("Phones store GPS in the file. A listing or a chat can leak your address. You will export a clean copy in this tab and keep the original if you still need the map pin.", "手机把定位写进文件。上架或发聊天可能泄露住址。在当前标签页导出一份干净的；自己还要地图钉就留着原图。", "手機把定位寫進檔。上架或發聊天可能洩漏住址。在目前分頁匯出一份乾淨的；自己還要地圖釘就留著原圖。", "電話はGPSをファイルに書く。出品やチャットで住所が漏れる。このタブできれいなコピーを書き出し、ピンが要るなら原版を残す。", "폰은 GPS를 파일에 넣습니다. 상품 등록이나 채팅에서 주소가 샐 수 있습니다. 이 탭에서 깨끗한 복사본을 보내고, 지도 핀이 필요하면 원본을 남기세요.", "Điện thoại ghi GPS vào file. Đăng bán hoặc chat có thể lộ địa chỉ. Xuất bản sạch trong tab này; còn cần ghim bản đồ thì giữ gốc.", "Ponsel menyimpan GPS di file. Listing atau chat bisa membocorkan alamat. Ekspor salinan bersih di tab ini; simpan asli jika masih butuh pin peta.", "El teléfono guarda GPS en el archivo. Un anuncio o un chat puede filtrar la dirección. Exporte una copia limpia aquí y conserve el original si aún quiere el pin."),
            "result": L("A photo that no longer carries GPS or camera EXIF, plus the original still on disk.", "一份不再带定位和相机 EXIF 的照片，原图还在磁盘上。", "一份不再帶定位和相機 EXIF 的照片，原圖還在磁碟上。", "GPSもカメラEXIFもない写真。原版はディスクに残る。", "GPS와 카메라 EXIF가 없는 사진. 원본은 디스크에 남습니다.", "Ảnh không còn GPS hay EXIF máy ảnh; bản gốc vẫn trên đĩa.", "Foto tanpa GPS atau EXIF kamera, plus asli masih di disk.", "Una foto sin GPS ni EXIF de cámara, y el original sigue en el disco."),
            "note": L("Open the EXIF tool when the photo is on disk. Re-encoding in this tab strips metadata. Screenshots often have none to begin with.", "照片在磁盘上再打开 EXIF 工具。在本页重编码会去掉元数据。截图往往本来就没有。", "照片在磁碟上再打開 EXIF 工具。在本頁重編碼會去掉中繼資料。截圖往往本來就沒有。", "写真が手元にあってからEXIFを開く。このタブの再エンコードでメタデータが落ちる。スクショは最初からないことが多い。", "사진이 디스크에 있으면 EXIF 도구를 여세요. 이 탭에서 다시 인코딩하면 메타데이터가 빠집니다. 스크린샷은 원래 없는 경우가 많습니다.", "Có ảnh trên đĩa thì mở EXIF. Mã hóa lại trong tab này gỡ metadata. Ảnh chụp màn hình thường vốn không có.", "Foto di disk, baru buka EXIF. Encode ulang di tab ini menghapus metadata. Tangkapan layar sering memang tidak punya.", "Abra EXIF cuando la foto esté en el disco. Recodificar aquí quita los metadatos. Las capturas a menudo no tienen ninguno."),
            "s1t": L("Check whether the file even has GPS", "先看文件里有没有定位", "先看檔裡有沒有定位", "そもそもGPSがあるか見る", "파일에 GPS가 있는지 보기", "Xem file có GPS không", "Cek apakah file punya GPS", "Compruebe si el archivo tiene GPS"),
            "s1b": L("The tool shows if it is tagged. Screenshots and many chat exports already have none.", "工具会显示有没有标记。截图和不少聊天导出本来就没有。", "工具會顯示有沒有標記。截圖和不少聊天匯出本來就沒有。", "ツールがタグの有無を出す。スクショやチャット書き出しは最初からないことが多い。", "도구가 태그가 있는지 보여 줍니다. 스크린샷과 많은 채팅 내보내기는 원래 없습니다.", "Công cụ hiện đã gắn hay chưa. Ảnh chụp màn hình và nhiều bản chat vốn không có.", "Alat menampilkan apakah tertandai. Tangkapan layar dan banyak ekspor chat memang tidak punya.", "La herramienta indica si está etiquetada. Las capturas y muchos chats ya no traen nada."),
            "s2t": L("Open the EXIF tool on cv.cm", "打开 cv.cm 的 EXIF 工具", "打開 cv.cm 的 EXIF 工具", "cv.cmのEXIFを開く", "cv.cm EXIF 도구를 열기", "Mở công cụ EXIF trên cv.cm", "Buka alat EXIF di cv.cm", "Abra EXIF en cv.cm"),
            "s2b": L("Work stays in this tab. Nothing is uploaded.", "处理留在当前标签页。不上传。", "處理留在目前分頁。不上傳。", "このタブで処理。アップロードなし。", "이 탭에서 처리합니다. 업로드 없음.", "Xử lý trong tab này. Không tải lên.", "Proses di tab ini. Tidak diunggah.", "El trabajo queda en esta pestaña. Nada se sube."),
            "s3t": L("Drop the photo", "拖入照片", "拖入照片", "写真をドロップ", "사진을 넣기", "Thả ảnh", "Letakkan foto", "Suelte la foto"),
            "s3b": L("If it shows a location, that is the pin you are about to strip.", "如果显示定位，那就是你要去掉的钉。", "如果顯示定位，那就是你要去掉的釘。", "位置が出れば、それが消すピン。", "위치가 보이면 그게 지울 핀입니다.", "Hiện vị trí thì đó là ghim bạn sắp gỡ.", "Kalau ada lokasi, itu pin yang akan dihapus.", "Si muestra una ubicación, ese es el pin que va a quitar."),
            "s4t": L("Export JPEG or PNG", "导出 JPEG 或 PNG", "匯出 JPEG 或 PNG", "JPEGかPNGを書き出す", "JPEG 또는 PNG로 보내기", "Xuất JPEG hoặc PNG", "Ekspor JPEG atau PNG", "Exporte JPEG o PNG"),
            "s4b": L("The canvas write does not copy EXIF. Keep the original if you still want the pin for yourself.", "画布写出不会带上 EXIF。自己还要定位就留着原图。", "畫布寫出不會帶上 EXIF。自己還要定位就留著原圖。", "キャンバス書き出しはEXIFをコピーしない。ピンが要るなら原版を残す。", "캔버스 저장은 EXIF를 복사하지 않습니다. 핀이 필요하면 원본을 남기세요.", "Ghi canvas không chép EXIF. Còn cần ghim thì giữ gốc.", "Tulisan kanvas tidak menyalin EXIF. Jika masih butuh pin, simpan asli.", "Escribir en el lienzo no copia EXIF. Si aún quiere el pin, conserve el original."),
            "s5t": L("Drop the export back into the same tool", "把导出的文件再拖进同一个工具", "把匯出的檔再拖進同一個工具", "書き出したファイルを同じツールに再ドロップ", "보낸 파일을 같은 도구에 다시 넣기", "Thả bản xuất vào lại cùng công cụ", "Letakkan hasil ekspor ke alat yang sama lagi", "Suelte la exportación otra vez en la misma herramienta"),
            "s5b": L("The second pass should show no location. If it still shows GPS, you opened the original by mistake.", "第二次不应再显示定位。还在，就是打开了原图。", "第二次不應再顯示定位。還在，就是打開了原圖。", "2回目は位置なし。まだ出るなら原版を開いている。", "두 번째에는 위치가 없어야 합니다. 있으면 원본을 연 것입니다.", "Lần hai không còn vị trí. Vẫn còn thì bạn mở nhầm bản gốc.", "Pass kedua tidak boleh ada lokasi. Masih ada: Anda membuka aslinya.", "La segunda pasada no debe mostrar ubicación. Si sigue, abrió el original."),
            "s6t": L("Send the clean copy, keep the original if you need the pin", "发出去用干净的那份；自己要钉就留原图", "寄出去用乾淨的那份；自己要釘就留原圖", "送るのはきれいなコピー。ピンが要る原版は残す。", "보낼 때는 깨끗한 복사본. 핀이 필요하면 원본을 남기세요.", "Gửi bản sạch; còn cần ghim thì giữ gốc.", "Kirim salinan bersih; simpan asli jika butuh pin.", "Envíe la copia limpia; conserve el original si quiere el pin."),
            "s6b": L("A chat app may strip GPS on its own. Do not trust that for a public listing — prove it with the second drop.", "聊天软件有时会自己去掉定位。上架别赌这个——用第二次拖入来证明。", "聊天軟體有時會自己去掉定位。上架別賭這個——用第二次拖入來證明。", "チャットは勝手にGPSを落とすこともある。公開出品では当てにせず、再ドロップで証明。", "채팅 앱이 알아서 GPS를 뺄 수도 있습니다. 공개 등록에서는 믿지 말고 두 번째 넣기로 증명하세요.", "Chat đôi khi tự gỡ GPS. Đừng tin khi đăng công khai — chứng minh bằng lần thả thứ hai.", "Chat kadang menghapus GPS sendiri. Jangan percaya untuk listing publik — buktikan dengan drop kedua.", "Un chat a veces quita el GPS solo. No se fíe en un anuncio público: pruébelo con la segunda suelta."),
            "diagram1": L("Photo file = pixels + GPS. Export = pixels only.", "照片文件 = 像素 + 定位。导出 = 只剩像素。", "照片檔 = 像素 + 定位。匯出 = 只剩像素。", "写真ファイル＝画素+GPS。書き出し＝画素だけ。", "사진 파일 = 픽셀 + GPS. 보내기 = 픽셀만.", "File ảnh = pixel + GPS. Xuất = chỉ pixel.", "File foto = piksel + GPS. Ekspor = piksel saja.", "Archivo = píxeles + GPS. Exportación = solo píxeles."),
            "diagram2": L("Drop, export, drop the export again. The second pass should be clean.", "拖入，导出，再把导出拖回来。第二次应该是干净的。", "拖入，匯出，再把匯出拖回來。第二次應該是乾淨的。", "ドロップ→書き出し→再ドロップ。2回目はきれい。", "넣고, 보내고, 보낸 파일을 다시 넣기. 두 번째는 깨끗해야 합니다.", "Thả, xuất, thả bản xuất lại. Lần hai phải sạch.", "Letakkan, ekspor, letakkan hasilnya lagi. Pass kedua harus bersih.", "Suelte, exporte, suelte la exportación. La segunda pasada debe estar limpia."),
        },
        {
            "q1": L("How do I remove GPS from an iPhone photo?", "怎么去掉 iPhone 照片里的定位？", "怎麼去掉 iPhone 照片裡的定位？", "iPhone写真の位置情報を消すには？", "아이폰 사진에서 위치를 지우려면?", "Gỡ GPS khỏi ảnh iPhone?", "Hapus GPS dari foto iPhone?", "¿Cómo quito el GPS de una foto de iPhone?"),
            "a1": L("Drop it on cv.cm EXIF in this tab, export, then drop the export to confirm. Keep the original if you still want the pin.", "拖进 cv.cm 的 EXIF，导出，再把导出拖回来确认。自己还要钉就留原图。", "拖進 cv.cm 的 EXIF，匯出，再把匯出拖回來確認。自己還要釘就留原圖。", "このタブのEXIFにドロップして書き出し、再ドロップで確認。ピンが要る原版は残す。", "이 탭의 EXIF에 넣고 보낸 뒤 보낸 파일을 다시 넣어 확인하세요. 핀이 필요하면 원본을 남기세요.", "Thả vào EXIF cv.cm trong tab này, xuất, thả bản xuất để xác nhận. Còn cần ghim thì giữ gốc.", "Letakkan di EXIF cv.cm di tab ini, ekspor, letakkan hasilnya untuk konfirmasi. Simpan asli jika butuh pin.", "Suelte la foto en EXIF de cv.cm, exporte y suelte la exportación para confirmar. Conserve el original si quiere el pin."),
            "q2": L("Does WhatsApp already strip location?", "微信或 WhatsApp 会自己去掉定位吗？", "微信或 WhatsApp 會自己去掉定位嗎？", "WhatsAppは位置を落とす？", "WhatsApp이 위치를 빼 주나요?", "WhatsApp tự gỡ vị trí?", "WhatsApp sudah menghapus lokasi?", "¿WhatsApp ya quita la ubicación?"),
            "a2": L("Some chats compress and strip. Public listings and email attachments often do not. Prove it with a second drop.", "有的聊天会压缩并去掉。上架和邮件附件经常还在。用第二次拖入证明。", "有的聊天會壓縮並去掉。上架和郵件附件經常還在。用第二次拖入證明。", "チャットは落とすこともある。公開出品やメール添付は残ることが多い。再ドロップで証明。", "어떤 채팅은 압축하며 뺍니다. 공개 등록과 이메일 첨부는 남는 경우가 많습니다. 두 번째 넣기로 증명하세요.", "Một số chat nén và gỡ. Đăng công khai và đính email thường còn. Chứng minh bằng lần thả thứ hai.", "Beberapa chat mengompres dan menghapus. Listing publik dan lampiran email sering tetap ada. Buktikan dengan drop kedua.", "Algunos chats comprimen y quitan. Los anuncios y los adjuntos de correo a menudo no. Pruébelo con la segunda suelta."),
            "q3": L("Are photos uploaded?", "会上传吗？", "會上傳嗎？", "アップロードされる？", "업로드되나요?", "Có tải lên không?", "Apakah diunggah?", "¿Se suben las fotos?"),
            "a3": L("No. Closing the tab discards them.", "不会。关掉标签页就没了。", "不會。關掉分頁就沒了。", "しない。タブを閉じると消える。", "아니요. 탭을 닫으면 사라집니다.", "Không. Đóng tab là mất.", "Tidak. Tutup tab, hilang.", "No. Al cerrar la pestaña se pierden."),
            "q4": L("Does this delete the original?", "会删原图吗？", "會刪原圖嗎？", "原版は消える？", "원본이 삭제되나요?", "Có xóa bản gốc không?", "Apakah aslinya terhapus?", "¿Borra el original?"),
            "a4": L("No. You download a new file. Keep or delete the original yourself.", "不会。你下载的是新文件。原图留不留你自己决定。", "不會。你下載的是新檔。原圖留不留你自己決定。", "しない。新しいファイルを保存する。原版は自分で残すか消す。", "아니요. 새 파일을 받습니다. 원본은 직접 남기거나 지우세요.", "Không. Bạn tải file mới. Giữ hay xóa gốc do bạn.", "Tidak. Anda mengunduh file baru. Asli Anda yang simpan atau hapus.", "No. Descarga un archivo nuevo. El original lo guarda o borra usted."),
            "q5": L("What about PNG screenshots?", "PNG 截图呢？", "PNG 截圖呢？", "PNGのスクショは？", "PNG 스크린샷은?", "Còn ảnh chụp PNG?", "Tangkapan PNG?", "¿Y las capturas PNG?"),
            "a5": L("They often have no GPS. Drop one in; if it is already clean, you are done.", "往往没有定位。拖进去看一眼，已经干净就不用转。", "往往沒有定位。拖進去看一眼，已經乾淨就不用轉。", "GPSがないことが多い。入れてきれいなら終わり。", "GPS가 없는 경우가 많습니다. 넣어 보고 이미 깨끗하면 끝입니다.", "Thường không có GPS. Thả vào; đã sạch thì xong.", "Sering tidak punya GPS. Letakkan; kalau sudah bersih, selesai.", "A menudo no tienen GPS. Suelte una; si ya está limpia, listo."),
        },
    ),
}

META = {
    "titleWebpToPng": L("How to convert WebP to PNG | cv.cm", "怎么把 WebP 转成 PNG | cv.cm", "怎麼把 WebP 轉成 PNG | cv.cm", "WebPをPNGにする方法 | cv.cm", "WebP를 PNG로 변환하는 법 | cv.cm", "Cách đổi WebP sang PNG | cv.cm", "Cara ubah WebP ke PNG | cv.cm", "Cómo pasar WebP a PNG | cv.cm"),
    "descWebpToPng": L("Chrome often saves WebP. Export PNG in this tab, keep transparency if you need it, then open the file in the app that rejected WebP.", "Chrome 常存 WebP。在本页导出 PNG，要透明就别选 JPG，再到打不开 WebP 的软件里打开。", "Chrome 常存 WebP。在本頁匯出 PNG，要透明就別選 JPG，再到打不開 WebP 的軟體裡打開。", "ChromeはWebPを保存しがち。このタブでPNGを書き出し、拒否したアプリで開く。", "Chrome은 WebP를 자주 저장합니다. 이 탭에서 PNG로 보낸 뒤 거부한 앱에서 여세요.", "Chrome hay lưu WebP. Xuất PNG trong tab này, giữ nền trong nếu cần, mở trong app từng từ chối WebP.", "Chrome sering simpan WebP. Ekspor PNG di tab ini, jaga transparansi jika perlu, buka di app yang menolak.", "Chrome suele guardar WebP. Exporte PNG aquí, conserve la transparencia si hace falta y ábralo en la app que lo rechazó."),
    "titleResizeImage": L("How to resize or compress an image | cv.cm", "怎么缩放或压缩图片 | cv.cm", "怎麼縮放或壓縮圖片 | cv.cm", "画像のリサイズと圧縮 | cv.cm", "이미지 크기 조절·압축하는 법 | cv.cm", "Cách thu nhỏ hoặc nén ảnh | cv.cm", "Cara ubah ukuran atau kompres gambar | cv.cm", "Cómo redimensionar o comprimir una imagen | cv.cm"),
    "descResizeImage": L("Set a real pixel cap or file-size cap, keep aspect lock, export, then open the download at 100%. Nothing is uploaded.", "对准真实的像素或体积上限，锁住比例，导出后用 100% 打开。不上传。", "對準真實的像素或體積上限，鎖住比例，匯出後用 100% 打開。不上傳。", "本当の画素または容量の上限に合わせ、比率ロックを維持し、100%で開く。アップロードなし。", "실제 픽셀 또는 용량 한도에 맞추고 비율 잠금을 유지한 뒤 100%로 여세요. 업로드 없음.", "Khớp giới hạn pixel hoặc dung lượng thật, khóa tỉ lệ, xuất, mở 100%. Không tải lên.", "Cocokkan batas piksel atau ukuran nyata, kunci rasio, ekspor, buka 100%. Tidak diunggah.", "Ajuste a un tope real de píxeles o de peso, mantenga el candado, exporte y ábralo al 100%. Nada se sube."),
    "titleLearnSplitPdf": L("How to split a PDF | cv.cm", "怎么拆分 PDF | cv.cm", "怎麼拆分 PDF | cv.cm", "PDFを分割する方法 | cv.cm", "PDF 나누는 법 | cv.cm", "Cách tách PDF | cv.cm", "Cara pecah PDF | cv.cm", "Cómo dividir un PDF | cv.cm"),
    "descLearnSplitPdf": L("Split every page into a ZIP, or extract a range like 1-3, then reopen and count. Locked files stay out. Nothing is uploaded.", "逐页打成 ZIP，或抽出 1-3 这种范围，再打开数页数。加密文件先解锁。不上传。", "逐頁打成 ZIP，或抽出 1-3 這種範圍，再打開數頁數。加密檔先解鎖。不上傳。", "全ページをZIPにするか1-3のような範囲を抜き、開いて数える。暗号化は先に解除。アップロードなし。", "페이지마다 ZIP으로 나누거나 1-3 같은 구간을 뺀 뒤 열고 세세요. 암호 파일은 먼저 해제. 업로드 없음.", "Tách từng trang thành ZIP, hoặc lấy khoảng 1-3, mở lại và đếm. File khóa để ngoài. Không tải lên.", "Pecah tiap halaman ke ZIP, atau ambil rentang 1-3, buka dan hitung. Terkunci tetap di luar. Tidak diunggah.", "Divida cada página en un ZIP, o extraiga un rango como 1-3, reabra y cuente. Los cifrados se quedan fuera. Nada se sube."),
    "titleAddWatermark": L("How to add a watermark to a photo | cv.cm", "怎么给照片加水印 | cv.cm", "怎麼給照片加水印 | cv.cm", "写真に透かしを入れる方法 | cv.cm", "사진에 워터마크 넣는 법 | cv.cm", "Cách gắn watermark lên ảnh | cv.cm", "Cara beri watermark pada foto | cv.cm", "Cómo añadir una marca de agua a una foto | cv.cm"),
    "descAddWatermark": L("Stamp a shop name or logo, set opacity, download a batch ZIP, then check at 100%. Adds a mark; does not remove one. Nothing is uploaded.", "盖店名或 Logo，调透明度，批量下载 ZIP，再用 100% 看。只盖印，不去印。不上传。", "蓋店名或 Logo，調透明度，批量下載 ZIP，再用 100% 看。只蓋印，不去印。不上傳。", "店名やロゴを入れ、不透明度を決め、ZIPで保存し100%で見る。入れるだけで消さない。アップロードなし。", "가게 이름이나 로고를 찍고 투명도를 맞춘 뒤 ZIP으로 받아 100%로 보세요. 넣기만 하고 지우지는 않습니다. 업로드 없음.", "Đóng tên shop hoặc logo, chỉnh mờ, tải ZIP, xem 100%. Chỉ gắn, không gỡ. Không tải lên.", "Cap nama toko atau logo, atur opacity, unduh ZIP, cek 100%. Hanya menambah, tidak menghapus. Tidak diunggah.", "Estampe un nombre o logo, ajuste la opacidad, descargue un ZIP y mire al 100%. Añade; no quita. Nada se sube."),
    "titleRemoveExif": L("How to remove EXIF / location from a photo | cv.cm", "怎么去掉照片里的定位和 EXIF | cv.cm", "怎麼去掉照片裡的定位和 EXIF | cv.cm", "位置情報とEXIFを除く方法 | cv.cm", "사진에서 위치와 EXIF를 지우는 법 | cv.cm", "Cách gỡ GPS / EXIF khỏi ảnh | cv.cm", "Cara hapus EXIF / lokasi dari foto | cv.cm", "Cómo quitar EXIF y la ubicación de una foto | cv.cm"),
    "descRemoveExif": L("Export a clean copy in this tab, drop the export again to prove GPS is gone, and keep the original if you still need the pin.", "在本页导出一份干净的，再拖回来确认定位没了。自己还要地图钉就留着原图。", "在本頁匯出一份乾淨的，再拖回來確認定位沒了。自己還要地圖釘就留著原圖。", "このタブできれいなコピーを書き出し、再ドロップでGPSが消えたことを確認。ピンが要る原版は残す。", "이 탭에서 깨끗한 복사본을 보낸 뒤 다시 넣어 GPS가 없어졌는지 확인하세요. 핀이 필요하면 원본을 남기세요.", "Xuất bản sạch trong tab này, thả lại để chứng minh GPS đã mất; còn cần ghim thì giữ gốc.", "Ekspor salinan bersih di tab ini, letakkan lagi untuk membuktikan GPS hilang; simpan asli jika butuh pin.", "Exporte una copia limpia aquí, suéltela otra vez para probar que el GPS se fue, y conserve el original si quiere el pin."),
}

HUB = {}



def inject() -> None:
    for loc, path in FILES.items():
        data = json.loads(path.read_text())
        data["faq"].setdefault("learn", {})
        for lesson_id, payload in LESSONS.items():
            data["learn"][lesson_id] = payload["copy"][loc]
            data["faq"]["learn"][lesson_id] = payload["faq"][loc]
        for key, by_loc in META.items():
            data["meta"][key] = by_loc[loc]
        if loc in HUB:
            data["learn"]["hub"].update(HUB[loc])
        path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n")
        print("patched", path.name, "lessons", list(LESSONS))


if __name__ == "__main__":
    inject()

