#!/usr/bin/env python3
"""Inject business-day, fraction, hourly-pay, and time-zone how-tos."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LOCS = ["en", "zh-CN", "zh-TW", "ja", "ko", "vi", "id", "es"]
FILES = {loc: ROOT / "src/locales" / f"{loc}.json" for loc in LOCS}
COPY_KEYS = [
    "name", "blurb", "title", "lead", "result", "note",
    "s1t", "s1b", "s2t", "s2b", "s3t", "s3b", "s4t", "s4b", "s5t", "s5b", "s6t", "s6b",
    "diagram1", "diagram2",
]
FAQ_KEYS = [f"{side}{i}" for i in range(1, 6) for side in ("q", "a")]


def L(*vals: str) -> dict[str, str]:
    if len(vals) != 8:
        raise ValueError(len(vals), vals[0] if vals else None)
    return dict(zip(LOCS, vals))


def lesson(fields: dict[str, dict[str, str]], faq: dict[str, dict[str, str]]) -> dict:
    missing = [k for k in COPY_KEYS if k not in fields]
    missing += [k for k in FAQ_KEYS if k not in faq]
    if missing:
        raise SystemExit(f"missing keys: {missing}")
    if not fields["title"]["en"].startswith("How to "):
        raise SystemExit(fields["title"]["en"])
    return {
        "copy": {loc: {k: v[loc] for k, v in fields.items()} for loc in LOCS},
        "faq": {loc: {k: v[loc] for k, v in faq.items()} for loc in LOCS},
    }


LESSONS = {
    "count-workdays": lesson(
        {
            "name": L("How to count business days", "怎么数工作日", "怎麼數工作日", "営業日の数え方", "근무일 세는 법", "Cách đếm ngày làm việc", "Cara hitung hari kerja", "Cómo contar días laborables"),
            "blurb": L("Count Monday through Friday between two dates, including both ends. A Wednesday holiday stays in the count.", "数两个日期之间的周一到周五，两头都算。周三的假日仍算在里面。", "數兩個日期之間的週一到週五，兩頭都算。週三的假日仍算在裡面。", "二つの日付の月曜から金曜を数える。両端を含む。水曜の祝日も数に入る。", "두 날짜 사이의 월~금을 셉니다. 양쪽 날짜를 포함합니다. 수요일 공휴일도 세에 남습니다.", "Đếm thứ Hai đến thứ Sáu giữa hai ngày, tính cả hai đầu. Ngày lễ rơi vào thứ Tư vẫn được tính.", "Hitung Senin sampai Jumat di antara dua tanggal, termasuk kedua ujung. Hari libur di hari Rabu tetap terhitung.", "Cuente de lunes a viernes entre dos fechas, incluidos ambos extremos. Un festivo en miércoles sigue en la cuenta."),
            "title": L("How to count business days", "怎么数工作日", "怎麼數工作日", "営業日の数え方", "근무일 세는 법", "Cách đếm ngày làm việc", "Cara hitung hari kerja", "Cómo contar días laborables"),
            "lead": L("You need the weekdays in a span. You will pick two dates in this tab and read the business-day number. Saturdays and Sundays are the only days left out. A public holiday on Wednesday still counts.", "你要的是一段里的工作日。在当前标签页选两个日期，看工作日数字。只有周六和周日被去掉。周三的公共假日仍然算。", "你要的是一段裡的工作日。在目前分頁選兩個日期，看工作日數字。只有週六和週日被去掉。週三的公共假日仍然算。", "期間の平日が欲しい。このタブで二つの日付を選び、営業日を読む。外れるのは土曜と日曜だけ。水曜の祝日も数える。", "구간의 평일이 필요합니다. 이 탭에서 두 날짜를 고르고 근무일 수를 읽으세요. 빠지는 날은 토요일과 일요일뿐입니다. 수요일 공휴일도 셉니다.", "Bạn cần các ngày trong tuần của một khoảng. Chọn hai ngày trong tab này và đọc số ngày làm việc. Chỉ thứ Bảy và Chủ nhật bị loại. Ngày lễ thứ Tư vẫn tính.", "Anda perlu hari kerja dalam satu rentang. Pilih dua tanggal di tab ini dan baca jumlah hari kerja. Hanya Sabtu dan Minggu yang dikeluarkan. Hari libur di Rabu tetap dihitung.", "Necesita los días de semana de un tramo. Elija dos fechas aquí y lea el número de días laborables. Solo se dejan fuera sábados y domingos. Un festivo en miércoles sigue contando."),
            "result": L("A business-day number that includes both dates when they are weekdays, plus the weekend days in that same span.", "一个工作日数字：两端如果是工作日就都算上，外加同一段里的周末天数。", "一個工作日數字：兩端如果是工作日就都算上，外加同一段裡的週末天數。", "両端が平日なら両方を含む営業日数。同じ期間の週末日数も付く。", "양쪽이 평일이면 둘 다 포함한 근무일 수, 그리고 같은 구간의 주말 일수.", "Số ngày làm việc tính cả hai đầu nếu là ngày trong tuần, cộng số ngày cuối tuần trong cùng khoảng.", "Jumlah hari kerja yang mencakup kedua tanggal jika hari kerja, plus hari akhir pekan di rentang yang sama.", "Un número de días laborables que incluye ambas fechas si son días de semana, y los días de fin de semana de ese mismo tramo."),
            "note": L("Open business days when you know the two calendar dates. The span includes both ends. Nothing is uploaded.", "两个日期确定再打开工作日。这一段两头都算。不上传。", "兩個日期確定再開工作日。這一段兩頭都算。不上傳。", "二つの日付が分かってから開く。期間は両端を含む。アップロードなし。", "두 날짜를 알 때 근무일을 여세요. 구간은 양쪽을 포함합니다. 업로드 없음.", "Biết hai ngày thì mở ngày làm việc. Khoảng tính cả hai đầu. Không tải lên.", "Tahu dua tanggal, baru buka hari kerja. Rentang mencakup kedua ujung. Tidak diunggah.", "Abra días laborables cuando sepa las dos fechas. El tramo incluye ambos extremos. Nada se sube."),
            "s1t": L("Include both dates", "两头都算", "兩頭都算", "両端を含める", "양쪽 날짜를 포함하기", "Tính cả hai đầu", "Sertakan kedua tanggal", "Incluya ambas fechas"),
            "s1b": L("Monday 5 January 2026 through Friday 9 January 2026 is five business days. Friday through the next Monday is two, because Saturday and Sunday sit in the middle.", "2026 年 1 月 5 日周一到 1 月 9 日周五是五个工作日。周五到下周一是两个，因为中间有周六和周日。", "2026 年 1 月 5 日週一到 1 月 9 日週五是五個工作日。週五到下週一是兩個，因為中間有週六和週日。", "2026年1月5日月曜から1月9日金曜は営業日5。金曜から次の月曜は2。間に土曜と日曜がある。", "2026년 1월 5일 월요일부터 1월 9일 금요일은 근무일 5일입니다. 금요일부터 다음 월요일은 2일입니다. 사이에 토요일과 일요일이 있습니다.", "Thứ Hai 5/1/2026 đến thứ Sáu 9/1/2026 là năm ngày làm việc. Thứ Sáu đến thứ Hai tuần sau là hai, vì thứ Bảy và Chủ nhật nằm giữa.", "Senin 5 Januari 2026 sampai Jumat 9 Januari 2026 adalah lima hari kerja. Jumat sampai Senin berikutnya adalah dua, karena Sabtu dan Minggu ada di tengah.", "Del lunes 5 de enero de 2026 al viernes 9 de enero de 2026 hay cinco días laborables. Del viernes al lunes siguiente hay dos, porque el sábado y el domingo quedan en medio."),
            "s2t": L("Open business days on cv.cm", "打开 cv.cm 的工作日", "打開 cv.cm 的工作日", "cv.cmの営業日を開く", "cv.cm 근무일을 열기", "Mở ngày làm việc trên cv.cm", "Buka hari kerja di cv.cm", "Abra días laborables en cv.cm"),
            "s2b": L("The count stays in this tab.", "计算留在当前标签页。", "計算留在目前分頁。", "計算はこのタブ。", "계산은 이 탭에서.", "Tính trong tab này.", "Hitungan di tab ini.", "La cuenta queda en esta pestaña."),
            "s3t": L("Pick the start and the end", "选开始和结束", "選開始和結束", "開始と終了を選ぶ", "시작과 끝을 고르기", "Chọn ngày đầu và ngày cuối", "Pilih awal dan akhir", "Elija el inicio y el fin"),
            "s3b": L("Use the calendar dates on the form. If the end is before the start, the business-day number is negative. The weekend count stays zero or positive.", "用表单上的日历日期。结束早于开始，工作日数字是负的。周末天数仍是零或正数。", "用表單上的日曆日期。結束早於開始，工作日數字是負的。週末天數仍是零或正數。", "書類の暦日を使う。終了が開始より前なら営業日は負。週末日数は0か正。", "서류의 달력 날짜를 쓰세요. 끝이 시작보다 앞이면 근무일 수는 음수입니다. 주말 일수는 0이거나 양수입니다.", "Dùng ngày trên biểu mẫu. Nếu ngày cuối trước ngày đầu, số ngày làm việc là số âm. Số ngày cuối tuần vẫn là 0 hoặc dương.", "Pakai tanggal kalender di formulir. Jika akhir sebelum awal, jumlah hari kerja negatif. Hitungan akhir pekan tetap nol atau positif.", "Use las fechas del formulario. Si el fin es anterior al inicio, el número de días laborables es negativo. El conteo de fin de semana sigue en cero o positivo."),
            "s4t": L("Read business days and weekend days", "看工作日和周末天数", "看工作日和週末天數", "営業日と週末日数を読む", "근무일과 주말 일수 읽기", "Đọc ngày làm việc và ngày cuối tuần", "Baca hari kerja dan hari akhir pekan", "Lea días laborables y días de fin de semana"),
            "s4b": L("Business days are Monday through Friday. Weekend days are the Saturdays and Sundays inside the same inclusive span.", "工作日是周一到周五。周末天数是同一段里、两头都算的周六和周日。", "工作日是週一到週五。週末天數是同一段裡、兩頭都算的週六和週日。", "営業日は月曜から金曜。週末日数は同じ両端含む期間の土曜と日曜。", "근무일은 월~금입니다. 주말 일수는 같은 구간에 양쪽을 포함하고 들어 있는 토요일과 일요일입니다.", "Ngày làm việc là thứ Hai đến thứ Sáu. Ngày cuối tuần là thứ Bảy và Chủ nhật trong cùng khoảng, tính cả hai đầu.", "Hari kerja adalah Senin sampai Jumat. Hari akhir pekan adalah Sabtu dan Minggu di rentang inklusif yang sama.", "Los días laborables son de lunes a viernes. Los de fin de semana son los sábados y domingos de ese mismo tramo inclusivo."),
            "s5t": L("Leave holidays in the count", "假日仍留在计数里", "假日仍留在計數裡", "祝日は数に残す", "공휴일은 세에 남기기", "Để ngày lễ trong số đếm", "Biarkan hari libur di dalam hitungan", "Deje los festivos en la cuenta"),
            "s5b": L("A holiday on Wednesday is still a business day here. If the form skips holidays, subtract those dates after you copy the number.", "周三的假日在这里仍是工作日。表单要跳过假日，就在复制数字之后自己减掉那些日期。", "週三的假日在這裡仍是工作日。表單要跳過假日，就在複製數字之後自己減掉那些日期。", "水曜の祝日もここでは営業日。書類が祝日を除くなら、数字をコピーしたあと自分で引く。", "수요일 공휴일도 여기서는 근무일입니다. 서류가 공휴일을 빼라면 수를 복사한 뒤 그 날짜를 직접 빼세요.", "Ngày lễ thứ Tư ở đây vẫn là ngày làm việc. Biểu mẫu bỏ ngày lễ thì sau khi copy hãy tự trừ những ngày đó.", "Hari libur di Rabu tetap hari kerja di sini. Jika formulir melewatkan hari libur, kurangi tanggal itu setelah menyalin angkanya.", "Un festivo en miércoles sigue siendo día laborable aquí. Si el formulario salta festivos, reste esas fechas después de copiar el número."),
            "s6t": L("Copy and match the form", "复制，并对上表单", "複製，並對上表單", "コピーして書類に合わせる", "복사하고 서류에 맞추기", "Copy và khớp với biểu mẫu", "Salin dan cocokkan dengan formulir", "Copie y iguale el formulario"),
            "s6b": L("A same-day weekday is 1. A same-day Saturday or Sunday is 0. This page includes both ends. A plain day difference of the same dates is one smaller when the span is positive.", "同一天如果是工作日，就是 1。同一天是周六或周日，就是 0。这一页两头都算。同一对日期的普通日差，在跨度为正时会少 1。", "同一天如果是工作日，就是 1。同一天是週六或週日，就是 0。這一頁兩頭都算。同一對日期的普通日差，在跨度為正時會少 1。", "同じ日が平日なら1。土曜か日曜なら0。このページは両端を含む。同じ日付の単純な日数差は、期間が正なら1少ない。", "같은 날이 평일이면 1입니다. 토요일이나 일요일이면 0입니다. 이 페이지는 양쪽을 포함합니다. 같은 날짜의 일반 일수 차이는 구간이 양수일 때 1이 적습니다.", "Cùng một ngày trong tuần là 1. Cùng một thứ Bảy hoặc Chủ nhật là 0. Trang này tính cả hai đầu. Hiệu ngày thường của cùng cặp ngày nhỏ hơn 1 khi khoảng là số dương.", "Hari yang sama dan hari kerja adalah 1. Sabtu atau Minggu di hari yang sama adalah 0. Halaman ini mencakup kedua ujung. Selisih hari biasa dari tanggal yang sama lebih kecil 1 saat rentangnya positif.", "El mismo día laborable es 1. El mismo sábado o domingo es 0. Esta página incluye ambos extremos. La diferencia simple de las mismas fechas es uno menos cuando el tramo es positivo."),
            "diagram1": L("Both ends count. Monday 5 Jan through Friday 9 Jan 2026 is 5 business days.", "两头都算。2026 年 1 月 5 日周一到 9 日周五是 5 个工作日。", "兩頭都算。2026 年 1 月 5 日週一到 9 日週五是 5 個工作日。", "両端を含む。2026年1月5日月曜〜9日金曜は営業日5。", "양쪽 포함. 2026년 1월 5일 월~9일 금은 근무일 5.", "Tính cả hai đầu. Thứ Hai 5/1 đến thứ Sáu 9/1/2026 là 5 ngày làm việc.", "Kedua ujung dihitung. Senin 5 Jan sampai Jumat 9 Jan 2026 adalah 5 hari kerja.", "Ambos extremos cuentan. Del lunes 5 al viernes 9 de enero de 2026 hay 5 días laborables."),
            "diagram2": L("Weekends drop out. A Wednesday holiday stays in the count.", "周末去掉。周三的假日仍留在计数里。", "週末去掉。週三的假日仍留在計數裡。", "週末は外す。水曜の祝日は数に残る。", "주말은 빠집니다. 수요일 공휴일은 세에 남습니다.", "Cuối tuần bị loại. Ngày lễ thứ Tư vẫn nằm trong số đếm.", "Akhir pekan keluar. Hari libur Rabu tetap di hitungan.", "El fin de semana sale. Un festivo en miércoles sigue en la cuenta."),
        },
        {
            "q1": L("Can I count business days free online?", "可以免费在线数工作日吗？", "可以免費線上數工作日嗎？", "営業日を無料で数えられる？", "근무일을 무료로 셀 수 있나요?", "Đếm ngày làm việc miễn phí online được không?", "Bisa hitung hari kerja gratis online?", "¿Puedo contar días laborables gratis en línea?"),
            "a1": L("Yes. cv.cm counts Monday through Friday in this tab, including both dates. Nothing is uploaded.", "可以。cv.cm 在当前标签页数周一到周五，两头都算。不上传。", "可以。cv.cm 在目前分頁數週一到週五，兩頭都算。不上傳。", "できる。このタブで月曜から金曜を数える。両端を含む。アップロードなし。", "됩니다. 이 탭에서 월~금을 세고 양쪽을 포함합니다. 업로드 없음.", "Được. Đếm thứ Hai đến thứ Sáu trong tab này, tính cả hai đầu. Không tải lên.", "Ya. Menghitung Senin sampai Jumat di tab ini, termasuk kedua ujung. Tidak diunggah.", "Sí. Cuenta de lunes a viernes en esta pestaña, incluidos ambos extremos. Nada se sube."),
            "q2": L("Are public holidays skipped?", "公共假日会跳过吗？", "公共假日會跳過嗎？", "祝日は除かれる？", "공휴일은 빠지나요?", "Ngày lễ có bị bỏ không?", "Apakah hari libur nasional dilewati?", "¿Se saltan los festivos?"),
            "a2": L("No. Only Saturdays and Sundays are left out. Subtract a Wednesday holiday yourself if the form requires it.", "不会。只有周六和周日被去掉。表单要求的话，周三的假日要自己减。", "不會。只有週六和週日被去掉。表單要求的話，週三的假日要自己減。", "しない。外れるのは土曜と日曜だけ。書類が求めるなら水曜の祝日は自分で引く。", "아니요. 토요일과 일요일만 빠집니다. 서류가 요구하면 수요일 공휴일은 직접 빼세요.", "Không. Chỉ thứ Bảy và Chủ nhật bị loại. Tự trừ ngày lễ thứ Tư nếu biểu mẫu yêu cầu.", "Tidak. Hanya Sabtu dan Minggu yang dikeluarkan. Kurangi sendiri hari libur Rabu jika formulir memintanya.", "No. Solo se dejan fuera sábados y domingos. Reste usted un festivo en miércoles si el formulario lo pide."),
            "q3": L("Does the count include both dates?", "两头都算吗？", "兩頭都算嗎？", "両端を含む？", "양쪽 날짜를 포함하나요?", "Có tính cả hai đầu không?", "Apakah kedua tanggal dihitung?", "¿La cuenta incluye ambas fechas?"),
            "a3": L("Yes. A weekday that is both the start and the end counts as 1. A Saturday or Sunday that is both counts as 0.", "算。开始和结束是同一个工作日，就是 1。同一个周六或周日，就是 0。", "算。開始和結束是同一個工作日，就是 1。同一個週六或週日，就是 0。", "含む。開始と終了が同じ平日なら1。同じ土曜か日曜なら0。", "포함합니다. 시작과 끝이 같은 평일이면 1입니다. 같은 토요일이나 일요일이면 0입니다.", "Có. Cùng một ngày trong tuần làm đầu và cuối thì là 1. Cùng một thứ Bảy hoặc Chủ nhật thì là 0.", "Ya. Hari kerja yang menjadi awal sekaligus akhir dihitung 1. Sabtu atau Minggu yang menjadi keduanya dihitung 0.", "Sí. Un día laborable que es inicio y fin cuenta como 1. Un sábado o domingo que es ambos cuenta como 0."),
            "q4": L("What if the end is before the start?", "结束早于开始呢？", "結束早於開始呢？", "終了が開始より前なら？", "끝이 시작보다 앞이면?", "Ngày cuối trước ngày đầu thì sao?", "Jika akhir sebelum awal?", "¿Y si el fin es anterior al inicio?"),
            "a4": L("The business-day number is negative. The weekend count stays zero or positive.", "工作日数字是负的。周末天数仍是零或正数。", "工作日數字是負的。週末天數仍是零或正數。", "営業日は負。週末日数は0か正。", "근무일 수는 음수입니다. 주말 일수는 0이거나 양수입니다.", "Số ngày làm việc là số âm. Số ngày cuối tuần vẫn là 0 hoặc dương.", "Jumlah hari kerja negatif. Hitungan akhir pekan tetap nol atau positif.", "El número de días laborables es negativo. El conteo de fin de semana sigue en cero o positivo."),
            "q5": L("Is this uploaded?", "会上传吗？", "會上傳嗎？", "アップロードされる？", "업로드되나요?", "Có bị tải lên không?", "Apakah diunggah?", "¿Se sube?"),
            "a5": L("No. Closing the tab discards it.", "不会。关掉标签页就没了。", "不會。關掉分頁就沒了。", "しない。タブを閉じると消える。", "아니요. 탭을 닫으면 사라집니다.", "Không. Đóng tab là mất.", "Tidak. Tutup tab, hilang.", "No. Al cerrar la pestaña se pierde."),
        },
    ),
    "simplify-fraction": lesson(
        {
            "name": L("How to simplify a fraction", "怎么约分", "怎麼約分", "分数を約分する方法", "분수 약분하는 법", "Cách rút gọn phân số", "Cara sederhanakan pecahan", "Cómo simplificar una fracción"),
            "blurb": L("Reduce a whole numerator and denominator, or turn a decimal into a fraction. 4/6 becomes 2/3. A decimal stops at denominator 10,000.", "把整数分子和分母约分，或把小数变成分数。4/6 变成 2/3。小数的分母停在 10,000。", "把整數分子和分母約分，或把小數變成分數。4/6 變成 2/3。小數的分母停在 10,000。", "整数の分子と分母を約分するか、小数を分数にする。4/6 は 2/3。小数の分母は 10,000 で止まる。", "정수 분자와 분모를 약분하거나 소수를 분수로 바꿉니다. 4/6은 2/3. 소수의 분모는 10,000에서 멈춥니다.", "Rút gọn tử và mẫu nguyên, hoặc đổi số thập phân thành phân số. 4/6 thành 2/3. Số thập phân dừng ở mẫu 10.000.", "Sederhanakan pembilang dan penyebut bulat, atau ubah desimal menjadi pecahan. 4/6 menjadi 2/3. Desimal berhenti di penyebut 10.000.", "Reduzca un numerador y un denominador enteros, o convierta un decimal en fracción. 4/6 pasa a 2/3. Un decimal se detiene en el denominador 10.000."),
            "title": L("How to simplify a fraction", "怎么约分", "怎麼約分", "分数を約分する方法", "분수 약분하는 법", "Cách rút gọn phân số", "Cara sederhanakan pecahan", "Cómo simplificar una fracción"),
            "lead": L("You have 4/6 or 0.75 and you need the short fraction. You will simplify in this tab and copy the fraction text. 5/2 stays 5/2. This page does not print a mixed number such as 2 1/2.", "你有 4/6 或 0.75，要的是约分后的分数。在当前标签页约分，复制分数文字。5/2 仍是 5/2。这一页不会打出 2 1/2 这样的带分数。", "你有 4/6 或 0.75，要的是約分後的分數。在目前分頁約分，複製分數文字。5/2 仍是 5/2。這一頁不會打出 2 1/2 這樣的帶分數。", "4/6 か 0.75 があり、短い分数が欲しい。このタブで約分し、分数の文字をコピー。5/2 は 5/2 のまま。帯分数 2 1/2 は出さない。", "4/6이나 0.75가 있고 짧은 분수가 필요합니다. 이 탭에서 약분하고 분수 글을 복사하세요. 5/2는 5/2로 남습니다. 이 페이지는 2 1/2 같은 대분수를 출력하지 않습니다.", "Bạn có 4/6 hoặc 0.75 và cần phân số ngắn. Rút gọn trong tab này và copy chữ phân số. 5/2 vẫn là 5/2. Trang này không in số hỗn như 2 1/2.", "Anda punya 4/6 atau 0.75 dan butuh pecahan pendek. Sederhanakan di tab ini dan salin teks pecahannya. 5/2 tetap 5/2. Halaman ini tidak mencetak bilangan campuran seperti 2 1/2.", "Tiene 4/6 o 0.75 y necesita la fracción corta. Simplifique aquí y copie el texto de la fracción. 5/2 sigue siendo 5/2. Esta página no imprime un número mixto como 2 1/2."),
            "result": L("A reduced fraction such as 2/3 or 3/4, with the sign on the numerator, and a decimal line you can check.", "一个约好的分数，例如 2/3 或 3/4，符号在分子上，外加一行可以核对的小数。", "一個約好的分數，例如 2/3 或 3/4，符號在分子上，外加一行可以核對的小數。", "2/3 や 3/4 のような既約分数。符号は分子。照合できる小数の行も付く。", "2/3이나 3/4 같은 기약분수. 부호는 분자에 있습니다. 대조할 소수 줄도 있습니다.", "Một phân số đã rút, như 2/3 hoặc 3/4, dấu ở tử số, và một dòng thập phân để đối chiếu.", "Pecahan yang disederhanakan seperti 2/3 atau 3/4, tanda di pembilang, plus baris desimal untuk dicek.", "Una fracción reducida como 2/3 o 3/4, con el signo en el numerador, y una línea decimal para comprobar."),
            "note": L("Open the fraction calculator when you have the two whole numbers or the decimal. Denominator 0 fails. Nothing is uploaded.", "有两个整数或一个小数再打开分数。分母 0 会失败。不上传。", "有兩個整數或一個小數再開分數。分母 0 會失敗。不上傳。", "二つの整数か小数があってから開く。分母 0 は失敗。アップロードなし。", "정수 둘이나 소수가 있을 때 분수를 여세요. 분모 0은 실패합니다. 업로드 없음.", "Có hai số nguyên hoặc một số thập phân thì mở phân số. Mẫu 0 thì thất bại. Không tải lên.", "Punya dua bilangan bulat atau satu desimal, baru buka pecahan. Penyebut 0 gagal. Tidak diunggah.", "Abra la calculadora de fracciones cuando tenga los dos enteros o el decimal. El denominador 0 falla. Nada se sube."),
            "s1t": L("Decide simplify or from a decimal", "先定是约分还是从小数来", "先定是約分還是從小數來", "約分か小数からか決める", "약분인지 소수에서인지 정하기", "Quyết rút gọn hay từ số thập phân", "Tentukan sederhanakan atau dari desimal", "Decida simplificar o partir de un decimal"),
            "s1b": L("Whole numbers use simplify. 4 and 6 become 2/3. A decimal such as 0.75 uses the other mode and becomes 3/4. The sign stays on the numerator. A negative denominator flips.", "整数用约分。4 和 6 变成 2/3。0.75 这样的小数用另一种模式，变成 3/4。符号留在分子上。分母是负的会翻转。", "整數用約分。4 和 6 變成 2/3。0.75 這樣的小數用另一種模式，變成 3/4。符號留在分子上。分母是負的會翻轉。", "整数は約分。4 と 6 は 2/3。0.75 のような小数は別モードで 3/4。符号は分子。負の分母は反転する。", "정수는 약분. 4와 6은 2/3. 0.75 같은 소수는 다른 모드에서 3/4. 부호는 분자에 남습니다. 음수 분모는 뒤집힙니다.", "Số nguyên thì rút gọn. 4 và 6 thành 2/3. Số thập phân như 0.75 dùng chế độ kia và thành 3/4. Dấu ở tử số. Mẫu âm thì đảo.", "Bilangan bulat memakai sederhanakan. 4 dan 6 menjadi 2/3. Desimal seperti 0.75 memakai mode lain dan menjadi 3/4. Tanda di pembilang. Penyebut negatif membalik.", "Los enteros usan simplificar. 4 y 6 pasan a 2/3. Un decimal como 0.75 usa el otro modo y pasa a 3/4. El signo queda en el numerador. Un denominador negativo se invierte."),
            "s2t": L("Open the fraction calculator on cv.cm", "打开 cv.cm 的分数", "打開 cv.cm 的分數", "cv.cmの分数を開く", "cv.cm 분수를 열기", "Mở phân số trên cv.cm", "Buka pecahan di cv.cm", "Abra la calculadora de fracciones en cv.cm"),
            "s2b": L("The math stays in this tab.", "计算留在当前标签页。", "計算留在目前分頁。", "計算はこのタブ。", "계산은 이 탭에서.", "Tính trong tab này.", "Hitungan di tab ini.", "La cuenta queda en esta pestaña."),
            "s3t": L("Enter whole numbers, or one decimal", "输入整数，或一个小数", "輸入整數，或一個小數", "整数か、小数を一つ入れる", "정수 또는 소수 하나 넣기", "Nhập số nguyên, hoặc một số thập phân", "Masukkan bilangan bulat, atau satu desimal", "Escriba enteros, o un decimal"),
            "s3b": L("Denominator 0 fails. A decimal typed into the numerator is rejected in simplify mode. Switch mode instead of rounding it yourself first.", "分母 0 会失败。约分模式里，分子填小数会被拒绝。先换模式，不要自己先四舍五入。", "分母 0 會失敗。約分模式裡，分子填小數會被拒絕。先換模式，不要自己先四捨五入。", "分母 0 は失敗。約分モードで分子に小数を入れると拒否。先にモードを替える。自分で丸めない。", "분모 0은 실패합니다. 약분 모드에서 분자에 소수를 넣으면 거부됩니다. 먼저 모드를 바꾸세요. 직접 반올림하지 마세요.", "Mẫu 0 thì thất bại. Ở chế độ rút gọn, tử số là số thập phân sẽ bị từ chối. Đổi chế độ, đừng tự làm tròn trước.", "Penyebut 0 gagal. Desimal di pembilang ditolak pada mode sederhanakan. Ganti mode, jangan dibulatkan sendiri dulu.", "El denominador 0 falla. Un decimal en el numerador se rechaza en modo simplificar. Cambie de modo en lugar de redondearlo usted primero."),
            "s4t": L("Read the fraction and the decimal line", "看分数和那一行小数", "看分數和那一行小數", "分数と小数の行を読む", "분수와 소수 줄 읽기", "Đọc phân số và dòng thập phân", "Baca pecahan dan baris desimal", "Lea la fracción y la línea decimal"),
            "s4b": L("Copy keeps the fraction text, such as 2/3. The decimal line is the check. If it does not match the number you meant, the input was only approximated.", "复制留下的是分数文字，例如 2/3。小数那一行是核对。对不上你要的数，输入就只是近似。", "複製留下的是分數文字，例如 2/3。小數那一行是核對。對不上你要的數，輸入就只是近似。", "コピーは 2/3 のような分数の文字。小数の行が照合。意図した数と違うなら、入力は近似にすぎない。", "복사는 2/3 같은 분수 글을 남깁니다. 소수 줄이 대조입니다. 의도한 수와 다르면 입력은 근사일 뿐입니다.", "Copy giữ chữ phân số, như 2/3. Dòng thập phân là chỗ đối chiếu. Không khớp số bạn muốn thì đầu vào chỉ là xấp xỉ.", "Salin menyimpan teks pecahan, seperti 2/3. Baris desimal adalah cek. Jika tidak cocok dengan angka yang Anda maksud, masukan hanya aproksimasi.", "Copiar conserva el texto de la fracción, como 2/3. La línea decimal es la comprobación. Si no coincide con el número que quería, la entrada solo era una aproximación."),
            "s5t": L("A long decimal stops at denominator 10,000", "很长的小数，分母停在 10,000", "很長的小數，分母停在 10,000", "長い小数は分母 10,000 で止まる", "긴 소수는 분모 10,000에서 멈춤", "Số thập phân dài dừng ở mẫu 10.000", "Desimal panjang berhenti di penyebut 10.000", "Un decimal largo se detiene en el denominador 10.000"),
            "s5b": L("0.333333 becomes 1/3. A decimal that is not a short fraction stays close once the denominator would pass 10,000. Read the decimal line again.", "0.333333 变成 1/3。不是短分数的小数，分母一旦要超过 10,000，就只是接近。再看一次小数那一行。", "0.333333 變成 1/3。不是短分數的小數，分母一旦要超過 10,000，就只是接近。再看一次小數那一行。", "0.333333 は 1/3。短い分数でない小数は、分母が 10,000 を超えそうになると近似のまま。小数の行をもう一度読む。", "0.333333은 1/3이 됩니다. 짧은 분수가 아닌 소수는 분모가 10,000을 넘으려 하면 가까운 값으로 남습니다. 소수 줄을 다시 읽으세요.", "0.333333 thành 1/3. Số thập phân không phải phân số ngắn sẽ chỉ gần đúng khi mẫu sắp vượt 10.000. Đọc lại dòng thập phân.", "0.333333 menjadi 1/3. Desimal yang bukan pecahan pendek tetap mendekati begitu penyebut akan melewati 10.000. Baca lagi baris desimal.", "0.333333 pasa a 1/3. Un decimal que no es una fracción corta se queda cerca cuando el denominador pasaría de 10.000. Lea otra vez la línea decimal."),
            "s6t": L("Keep it as an improper fraction", "保持为假分数", "保持為假分數", "仮分数のままにする", "가분수로 두기", "Giữ dạng phân số không thực sự", "Biarkan sebagai pecahan tidak wajar", "Déjela como fracción impropia"),
            "s6b": L("5/2 stays 5/2. If a worksheet wants 2 1/2, split the whole part after you copy.", "5/2 仍是 5/2。作业本要 2 1/2，就在复制之后自己拆出整数部分。", "5/2 仍是 5/2。作業本要 2 1/2，就在複製之後自己拆出整數部分。", "5/2 は 5/2 のまま。ワークシートが 2 1/2 を求めるなら、コピーしたあと整数部を自分で分ける。", "5/2는 5/2로 남습니다. 연습장이 2 1/2를 원하면 복사한 뒤 정수 부분을 직접 나누세요.", "5/2 vẫn là 5/2. Vở muốn 2 1/2 thì sau khi copy hãy tự tách phần nguyên.", "5/2 tetap 5/2. Jika lembar kerja minta 2 1/2, pisahkan bagian bulat setelah menyalin.", "5/2 sigue siendo 5/2. Si una hoja pide 2 1/2, separe la parte entera después de copiar."),
            "diagram1": L("4/6 becomes 2/3. The sign stays on the numerator.", "4/6 变成 2/3。符号留在分子上。", "4/6 變成 2/3。符號留在分子上。", "4/6 は 2/3。符号は分子。", "4/6은 2/3. 부호는 분자에.", "4/6 thành 2/3. Dấu ở tử số.", "4/6 menjadi 2/3. Tanda di pembilang.", "4/6 pasa a 2/3. El signo queda en el numerador."),
            "diagram2": L("0.75 becomes 3/4. A long decimal stops at denominator 10,000.", "0.75 变成 3/4。很长的小数，分母停在 10,000。", "0.75 變成 3/4。很長的小數，分母停在 10,000。", "0.75 は 3/4。長い小数は分母 10,000 で止まる。", "0.75는 3/4. 긴 소수는 분모 10,000에서 멈춥니다.", "0.75 thành 3/4. Số thập phân dài dừng ở mẫu 10.000.", "0.75 menjadi 3/4. Desimal panjang berhenti di penyebut 10.000.", "0.75 pasa a 3/4. Un decimal largo se detiene en el denominador 10.000."),
        },
        {
            "q1": L("Can I simplify a fraction free online?", "可以免费在线约分吗？", "可以免費線上約分嗎？", "分数を無料で約分できる？", "분수를 무료로 약분할 수 있나요?", "Rút gọn phân số miễn phí online được không?", "Bisa sederhanakan pecahan gratis online?", "¿Puedo simplificar una fracción gratis en línea?"),
            "a1": L("Yes. cv.cm reduces whole numbers or a decimal in this tab. Nothing is uploaded.", "可以。cv.cm 在当前标签页约分整数或小数。不上传。", "可以。cv.cm 在目前分頁約分整數或小數。不上傳。", "できる。このタブで整数か小数を約分。アップロードなし。", "됩니다. 이 탭에서 정수나 소수를 약분합니다. 업로드 없음.", "Được. Rút gọn số nguyên hoặc số thập phân trong tab này. Không tải lên.", "Ya. Menyederhanakan bilangan bulat atau desimal di tab ini. Tidak diunggah.", "Sí. Reduce enteros o un decimal en esta pestaña. Nada se sube."),
            "q2": L("What does 4/6 become?", "4/6 会变成什么？", "4/6 會變成什麼？", "4/6 は何になる？", "4/6은 무엇이 되나요?", "4/6 thành gì?", "4/6 menjadi apa?", "¿En qué se convierte 4/6?"),
            "a2": L("2/3. The sign stays on the numerator. A negative denominator flips.", "2/3。符号留在分子上。分母是负的会翻转。", "2/3。符號留在分子上。分母是負的會翻轉。", "2/3。符号は分子。負の分母は反転する。", "2/3. 부호는 분자에 남습니다. 음수 분모는 뒤집힙니다.", "2/3. Dấu ở tử số. Mẫu âm thì đảo.", "2/3. Tanda di pembilang. Penyebut negatif membalik.", "2/3. El signo queda en el numerador. Un denominador negativo se invierte."),
            "q3": L("Can I start from a decimal?", "能从小数开始吗？", "能從小數開始嗎？", "小数から始められる？", "소수에서 시작할 수 있나요?", "Bắt đầu từ số thập phân được không?", "Bisa mulai dari desimal?", "¿Puedo empezar desde un decimal?"),
            "a3": L("Yes. 0.75 becomes 3/4. The denominator stops at 10,000, so a long decimal may be close rather than exact.", "可以。0.75 变成 3/4。分母停在 10,000，所以很长的小数可能只是接近，不是精确。", "可以。0.75 變成 3/4。分母停在 10,000，所以很長的小數可能只是接近，不是精確。", "できる。0.75 は 3/4。分母は 10,000 で止まるので、長い小数は正確でなく近いことがある。", "됩니다. 0.75는 3/4. 분모는 10,000에서 멈추므로 긴 소수는 정확하지 않고 가까울 수 있습니다.", "Được. 0.75 thành 3/4. Mẫu dừng ở 10.000, nên số thập phân dài có thể chỉ gần đúng.", "Ya. 0.75 menjadi 3/4. Penyebut berhenti di 10.000, jadi desimal panjang bisa hanya mendekati.", "Sí. 0.75 pasa a 3/4. El denominador se detiene en 10.000, así que un decimal largo puede quedar cerca y no exacto."),
            "q4": L("Will I get a mixed number?", "会得到带分数吗？", "會得到帶分數嗎？", "帯分数になる？", "대분수가 나오나요?", "Có ra số hỗn không?", "Apakah dapat bilangan campuran?", "¿Obtendré un número mixto?"),
            "a4": L("No. 5/2 stays 5/2. Split the whole part yourself if a worksheet wants 2 1/2.", "不会。5/2 仍是 5/2。作业本要 2 1/2，就自己拆出整数部分。", "不會。5/2 仍是 5/2。作業本要 2 1/2，就自己拆出整數部分。", "ならない。5/2 は 5/2 のまま。2 1/2 が要るなら整数部は自分で分ける。", "아니요. 5/2는 5/2로 남습니다. 2 1/2가 필요하면 정수 부분을 직접 나누세요.", "Không. 5/2 vẫn là 5/2. Tự tách phần nguyên nếu vở muốn 2 1/2.", "Tidak. 5/2 tetap 5/2. Pisahkan sendiri bagian bulat jika lembar kerja minta 2 1/2.", "No. 5/2 sigue siendo 5/2. Separe usted la parte entera si una hoja pide 2 1/2."),
            "q5": L("Is this uploaded?", "会上传吗？", "會上傳嗎？", "アップロードされる？", "업로드되나요?", "Có bị tải lên không?", "Apakah diunggah?", "¿Se sube?"),
            "a5": L("No. Closing the tab discards it.", "不会。关掉标签页就没了。", "不會。關掉分頁就沒了。", "しない。タブを閉じると消える。", "아니요. 탭을 닫으면 사라집니다.", "Không. Đóng tab là mất.", "Tidak. Tutup tab, hilang.", "No. Al cerrar la pestaña se pierde."),
        },
    ),
    "hourly-pay": lesson(
        {
            "name": L("How to convert hourly pay to a yearly salary", "怎么把时薪换成年薪", "怎麼把時薪換成年薪", "時給を年収に換算する方法", "시급을 연봉으로 바꾸는 법", "Cách đổi lương giờ sang lương năm", "Cara ubah upah per jam jadi gaji tahunan", "Cómo convertir el pago por hora en un sueldo anual"),
            "blurb": L("Multiply one hourly rate by hours per week and weeks per year. The default is 40 by 52, which is 2,080 hours. The result is gross pay.", "用一个时薪乘每周小时和每年周数。默认是 40 乘 52，即 2,080 小时。结果是税前。", "用一個時薪乘每週小時和每年週數。預設是 40 乘 52，即 2,080 小時。結果是稅前。", "一つの時給に週の時間と年の週数をかける。初期値は 40×52 で 2,080 時間。結果は税引前。", "시급 하나에 주당 시간과 연간 주를 곱합니다. 기본은 40×52, 즉 2,080시간. 결과는 세전입니다.", "Nhân một lương giờ với giờ mỗi tuần và số tuần mỗi năm. Mặc định là 40 nhân 52, tức 2.080 giờ. Kết quả là lương trước thuế.", "Kalikan satu upah per jam dengan jam per minggu dan minggu per tahun. Bawaan adalah 40 kali 52, yaitu 2.080 jam. Hasilnya gaji kotor.", "Multiplique una tarifa por hora por las horas semanales y las semanas al año. El valor por defecto es 40 por 52, es decir 2.080 horas. El resultado es el bruto."),
            "title": L("How to convert hourly pay to a yearly salary", "怎么把时薪换成年薪", "怎麼把時薪換成年薪", "時給を年収に換算する方法", "시급을 연봉으로 바꾸는 법", "Cách đổi lương giờ sang lương năm", "Cara ubah upah per jam jadi gaji tahunan", "Cómo convertir el pago por hora en un sueldo anual"),
            "lead": L("You want the yearly gross from an hourly rate, or the hourly rate from a yearly gross. You will set hours and weeks in this tab. Tax, insurance, and a higher overtime rate stay outside this number.", "你要把时薪换成税前年薪，或把税前年薪换成时薪。在当前标签页设定每周小时和每年周数。税、保险和更高的加班费率不在这个数字里。", "你要把時薪換成稅前年薪，或把稅前年薪換成時薪。在目前分頁設定每週小時和每年週數。稅、保險和更高的加班費率不在這個數字裡。", "時給から税引前年収、または年収から時給が欲しい。このタブで時間と週数を決める。税、保険、高い残業単価はこの数字の外。", "시급에서 세전 연봉을, 또는 세전 연봉에서 시급을 원합니다. 이 탭에서 시간과 주를 정하세요. 세금, 보험, 더 높은 초과근무 수당은 이 수 밖에 있습니다.", "Bạn muốn lương năm trước thuế từ lương giờ, hoặc lương giờ từ lương năm. Đặt giờ và số tuần trong tab này. Thuế, bảo hiểm và hệ số làm thêm cao hơn nằm ngoài số này.", "Anda ingin gaji tahunan kotor dari upah per jam, atau upah per jam dari gaji tahunan. Atur jam dan minggu di tab ini. Pajak, asuransi, dan tarif lembur yang lebih tinggi ada di luar angka ini.", "Quiere el bruto anual a partir de una tarifa por hora, o la tarifa por hora a partir del bruto anual. Fije horas y semanas aquí. El impuesto, el seguro y una tarifa de horas extra más alta quedan fuera de este número."),
            "result": L("Hourly, weekly, and yearly gross pay from one rate, one hours-per-week, and one weeks-per-year.", "由一个费率、一个每周小时、一个每年周数得到的时薪、周薪和年薪，都是税前。", "由一個費率、一個每週小時、一個每年週數得到的時薪、週薪和年薪，都是稅前。", "一つの単価、週の時間、年の週数から出た時給・週給・年収。すべて税引前。", "하나의 단가, 주당 시간, 연간 주로 나온 시급, 주급, 연봉. 모두 세전입니다.", "Lương giờ, tuần và năm trước thuế từ một mức, một số giờ mỗi tuần và một số tuần mỗi năm.", "Upah per jam, mingguan, dan tahunan kotor dari satu tarif, satu jam per minggu, dan satu minggu per tahun.", "Pago por hora, semanal y anual en bruto, a partir de una tarifa, unas horas por semana y unas semanas al año."),
            "note": L("Open hourly to yearly when you know the rate. Defaults are 40 hours and 52 weeks. Gross pay only. Nothing is uploaded.", "知道费率再打开时薪换年薪。默认是 40 小时和 52 周。只有税前。不上传。", "知道費率再開時薪換年薪。預設是 40 小時和 52 週。只有稅前。不上傳。", "単価が分かってから開く。初期値は 40 時間と 52 週。税引前だけ。アップロードなし。", "단가를 알 때 시급 환산을 여세요. 기본은 40시간과 52주. 세전만. 업로드 없음.", "Biết mức lương thì mở đổi giờ sang năm. Mặc định 40 giờ và 52 tuần. Chỉ lương trước thuế. Không tải lên.", "Tahu tarif, baru buka upah per jam ke tahunan. Bawaan 40 jam dan 52 minggu. Hanya gaji kotor. Tidak diunggah.", "Abra de hora a año cuando sepa la tarifa. Los valores por defecto son 40 horas y 52 semanas. Solo el bruto. Nada se sube."),
            "s1t": L("Use one rate and the real weeks", "用一个费率，和真实的周数", "用一個費率，和真實的週數", "一つの単価と実際の週数を使う", "단가 하나와 실제 주를 쓰기", "Dùng một mức và số tuần thật", "Pakai satu tarif dan minggu yang nyata", "Use una tarifa y las semanas reales"),
            "s1b": L("20 an hour, 40 hours a week, 52 weeks, is 41,600.00 gross. Two unpaid weeks make it 50 weeks, not 52. Overtime at time-and-a-half is a second rate. This page uses one.", "每小时 20，每周 40 小时，52 周，税前是 41,600.00。两周无薪就改成 50 周，不是 52。1.5 倍加班是第二个费率。这一页只用一个。", "每小時 20，每週 40 小時，52 週，稅前是 41,600.00。兩週無薪就改成 50 週，不是 52。1.5 倍加班是第二個費率。這一頁只用一個。", "時給 20、週 40 時間、52 週で税引前 41,600.00。無給が2週なら 50 週であり 52 ではない。1.5 倍の残業は別単価。このページは一つ。", "시급 20, 주 40시간, 52주면 세전 41,600.00입니다. 무급 2주면 50주지 52주가 아닙니다. 1.5배 초과근무는 두 번째 단가입니다. 이 페이지는 하나를 씁니다.", "20 mỗi giờ, 40 giờ một tuần, 52 tuần, là 41.600,00 trước thuế. Hai tuần không lương thì là 50 tuần, không phải 52. Làm thêm 1,5 lần là mức thứ hai. Trang này chỉ dùng một mức.", "20 per jam, 40 jam seminggu, 52 minggu, adalah 41.600,00 kotor. Dua minggu tidak dibayar berarti 50 minggu, bukan 52. Lembur 1,5 kali adalah tarif kedua. Halaman ini memakai satu.", "20 por hora, 40 horas a la semana, 52 semanas, son 41.600,00 en bruto. Dos semanas sin pagar son 50 semanas, no 52. Las horas extra a 1,5 son una segunda tarifa. Esta página usa una."),
            "s2t": L("Open hourly to yearly on cv.cm", "打开 cv.cm 的时薪换年薪", "打開 cv.cm 的時薪換年薪", "cv.cmの時給換算を開く", "cv.cm 시급 환산을 열기", "Mở đổi lương giờ trên cv.cm", "Buka upah per jam ke tahunan di cv.cm", "Abra de hora a año en cv.cm"),
            "s2b": L("The math stays in this tab.", "计算留在当前标签页。", "計算留在目前分頁。", "計算はこのタブ。", "계산은 이 탭에서.", "Tính trong tab này.", "Hitungan di tab ini.", "La cuenta queda en esta pestaña."),
            "s3t": L("Pick the direction", "选方向", "選方向", "方向を選ぶ", "방향 고르기", "Chọn chiều", "Pilih arahnya", "Elija la dirección"),
            "s3b": L("Hourly to yearly multiplies. Yearly to hourly divides the yearly gross by hours times weeks. A blank field fails.", "时薪到年薪是相乘。年到时薪是用年薪税前除以小时乘周数。有一栏空着就会失败。", "時薪到年薪是相乘。年到時薪是用年薪稅前除以小時乘週數。有一欄空著就會失敗。", "時給から年収は掛け算。年から時給は年収を時間×週数で割る。空欄があると失敗。", "시급에서 연봉은 곱셈입니다. 연봉에서 시급은 세전 연봉을 시간×주로 나눕니다. 빈 칸이 있으면 실패합니다.", "Giờ sang năm là nhân. Năm sang giờ là chia lương năm trước thuế cho giờ nhân số tuần. Ô trống thì thất bại.", "Per jam ke tahunan mengalikan. Tahunan ke per jam membagi gaji tahunan kotor dengan jam kali minggu. Kolom kosong gagal.", "De hora a año multiplica. De año a hora divide el bruto anual entre horas por semanas. Un campo en blanco falla."),
            "s4t": L("Set hours and weeks", "设定小时和周数", "設定小時和週數", "時間と週数を入れる", "시간과 주를 정하기", "Đặt giờ và số tuần", "Atur jam dan minggu", "Fije horas y semanas"),
            "s4b": L("Hours must be greater than 0 and at most 168. Weeks must be greater than 0 and at most 52. 40 and 52 are the defaults: 2,080 hours.", "每周小时要大于 0，最多 168。每年周数要大于 0，最多 52。默认 40 和 52，即 2,080 小时。", "每週小時要大於 0，最多 168。每年週數要大於 0，最多 52。預設 40 和 52，即 2,080 小時。", "週の時間は 0 より大きく 168 以下。年の週数は 0 より大きく 52 以下。初期値は 40 と 52 で 2,080 時間。", "주당 시간은 0보다 크고 최대 168. 연간 주는 0보다 크고 최대 52. 기본 40과 52는 2,080시간입니다.", "Giờ phải lớn hơn 0 và tối đa 168. Số tuần phải lớn hơn 0 và tối đa 52. Mặc định 40 và 52: 2.080 giờ.", "Jam harus lebih dari 0 dan paling banyak 168. Minggu harus lebih dari 0 dan paling banyak 52. Bawaan 40 dan 52: 2.080 jam.", "Las horas deben ser mayores que 0 y como máximo 168. Las semanas, mayores que 0 y como máximo 52. 40 y 52 son los valores por defecto: 2.080 horas."),
            "s5t": L("Read hourly, weekly, and yearly", "看时薪、周薪和年薪", "看時薪、週薪和年薪", "時給・週給・年収を読む", "시급, 주급, 연봉 읽기", "Đọc lương giờ, tuần và năm", "Baca per jam, mingguan, dan tahunan", "Lea por hora, semanal y anual"),
            "s5b": L("All three are gross, shown to two decimals. Weekly is the hourly rate times hours per week. Yearly is weekly times weeks.", "三个都是税前，显示到两位小数。周薪是时薪乘每周小时。年薪是周薪乘周数。", "三個都是稅前，顯示到兩位小數。週薪是時薪乘每週小時。年薪是週薪乘週數。", "三つとも税引前。小数第2位まで。週給は時給×週の時間。年収は週給×週数。", "셋 다 세전이며 소수 둘째 자리까지입니다. 주급은 시급 곱하기 주당 시간. 연봉은 주급 곱하기 주입니다.", "Cả ba đều trước thuế, hai chữ số thập phân. Lương tuần là lương giờ nhân giờ mỗi tuần. Lương năm là lương tuần nhân số tuần.", "Ketiganya kotor, dua desimal. Mingguan adalah upah per jam kali jam per minggu. Tahunan adalah mingguan kali minggu.", "Los tres son brutos, con dos decimales. El semanal es la tarifa por hora por las horas semanales. El anual es el semanal por las semanas."),
            "s6t": L("Leave tax off this number", "税不要算进这个数字", "稅不要算進這個數字", "税はこの数字に入れない", "세금은 이 수에 넣지 않기", "Đừng tính thuế vào số này", "Jangan masukkan pajak ke angka ini", "Deje el impuesto fuera de este número"),
            "s6b": L("Copy the three lines. Subtract tax, insurance, or pension on the form that asks for net pay. This gross figure is not take-home.", "复制这三行。要净收入的表单上，再去减税、保险或养老金。这个税前数字不是到手收入。", "複製這三行。要淨收入的表單上，再去減稅、保險或退休金。這個稅前數字不是到手收入。", "三行をコピー。手取りを求める書類で税・保険・年金を引く。この税引前は手取りではない。", "세 줄을 복사하세요. 실수령을 묻는 서류에서 세금, 보험, 연금을 빼세요. 이 세전 숫자는 실수령이 아닙니다.", "Copy ba dòng. Trừ thuế, bảo hiểm hoặc lương hưu trên biểu mẫu hỏi lương thực nhận. Số trước thuế này không phải tiền mang về.", "Salin tiga baris. Kurangi pajak, asuransi, atau pensiun di formulir yang minta gaji bersih. Angka kotor ini bukan uang dibawa pulang.", "Copie las tres líneas. Reste impuesto, seguro o pensión en el formulario que pide el neto. Esta cifra bruta no es lo que se lleva a casa."),
            "diagram1": L("20 × 40 hours × 52 weeks = 41,600.00 gross. Unpaid weeks lower the 52.", "20 × 每周 40 小时 × 52 周 = 税前 41,600.00。无薪周要改掉这个 52。", "20 × 每週 40 小時 × 52 週 = 稅前 41,600.00。無薪週要改掉這個 52。", "20 × 週40時間 × 52週 = 税引前 41,600.00。無給の週は 52 を下げる。", "20 × 주 40시간 × 52주 = 세전 41,600.00. 무급 주는 52를 낮춥니다.", "20 × 40 giờ × 52 tuần = 41.600,00 trước thuế. Tuần không lương thì hạ số 52.", "20 × 40 jam × 52 minggu = 41.600,00 kotor. Minggu tidak dibayar menurunkan 52.", "20 × 40 horas × 52 semanas = 41.600,00 en bruto. Las semanas sin pagar bajan el 52."),
            "diagram2": L("One rate. Gross only. Tax and overtime premiums stay outside.", "一个费率。只有税前。税和加班加成留在外面。", "一個費率。只有稅前。稅和加班加成留在外面。", "単価は一つ。税引前だけ。税と残業割増は外。", "단가는 하나. 세전만. 세금과 초과근무 가산은 밖에.", "Một mức. Chỉ trước thuế. Thuế và phụ cấp làm thêm ở ngoài.", "Satu tarif. Hanya kotor. Pajak dan premi lembur di luar.", "Una tarifa. Solo el bruto. El impuesto y el plus de horas extra quedan fuera."),
        },
        {
            "q1": L("Can I convert hourly pay to a yearly salary free online?", "可以免费在线把时薪换成年薪吗？", "可以免費線上把時薪換成年薪嗎？", "時給を年収に無料で換算できる？", "시급을 연봉으로 무료로 바꿀 수 있나요?", "Đổi lương giờ sang năm miễn phí online được không?", "Bisa ubah upah per jam ke tahunan gratis online?", "¿Puedo convertir el pago por hora en sueldo anual gratis en línea?"),
            "a1": L("Yes. cv.cm multiplies or divides in this tab. Nothing is uploaded.", "可以。cv.cm 在当前标签页相乘或相除。不上传。", "可以。cv.cm 在目前分頁相乘或相除。不上傳。", "できる。このタブで掛け算か割り算。アップロードなし。", "됩니다. 이 탭에서 곱하거나 나눕니다. 업로드 없음.", "Được. Nhân hoặc chia trong tab này. Không tải lên.", "Ya. Mengalikan atau membagi di tab ini. Tidak diunggah.", "Sí. Multiplica o divide en esta pestaña. Nada se sube."),
            "q2": L("What are the defaults?", "默认是多少？", "預設是多少？", "初期値は？", "기본값은?", "Mặc định là bao nhiêu?", "Bawaannya berapa?", "¿Cuáles son los valores por defecto?"),
            "a2": L("40 hours a week and 52 weeks a year, which is 2,080 hours. 20 an hour is then 41,600.00 gross.", "每周 40 小时，每年 52 周，即 2,080 小时。时薪 20 就是税前 41,600.00。", "每週 40 小時，每年 52 週，即 2,080 小時。時薪 20 就是稅前 41,600.00。", "週 40 時間、年 52 週で 2,080 時間。時給 20 なら税引前 41,600.00。", "주 40시간, 연 52주, 즉 2,080시간. 시급 20이면 세전 41,600.00입니다.", "40 giờ một tuần và 52 tuần một năm, tức 2.080 giờ. Lương giờ 20 thì là 41.600,00 trước thuế.", "40 jam seminggu dan 52 minggu setahun, yaitu 2.080 jam. Upah 20 per jam lalu menjadi 41.600,00 kotor.", "40 horas a la semana y 52 semanas al año, es decir 2.080 horas. 20 por hora son entonces 41.600,00 en bruto."),
            "q3": L("Does it subtract tax?", "会扣税吗？", "會扣稅嗎？", "税は引かれる？", "세금을 빼나요?", "Có trừ thuế không?", "Apakah mengurangi pajak?", "¿Resta el impuesto?"),
            "a3": L("No. The three lines are gross. Subtract tax, insurance, and pension on the form that asks for net pay.", "不会。三行都是税前。要净收入的表单上再减税、保险和养老金。", "不會。三行都是稅前。要淨收入的表單上再減稅、保險和退休金。", "しない。三行は税引前。手取りを求める書類で税・保険・年金を引く。", "아니요. 세 줄은 세전입니다. 실수령을 묻는 서류에서 세금, 보험, 연금을 빼세요.", "Không. Ba dòng đều trước thuế. Trừ thuế, bảo hiểm và lương hưu trên biểu mẫu hỏi lương thực nhận.", "Tidak. Tiga baris itu kotor. Kurangi pajak, asuransi, dan pensiun di formulir yang minta gaji bersih.", "No. Las tres líneas son brutas. Reste impuesto, seguro y pensión en el formulario que pide el neto."),
            "q4": L("What if I have unpaid weeks or overtime?", "有无薪周或加班呢？", "有無薪週或加班呢？", "無給の週や残業は？", "무급 주나 초과근무가 있으면?", "Có tuần không lương hoặc làm thêm thì sao?", "Jika ada minggu tidak dibayar atau lembur?", "¿Y si hay semanas sin pagar u horas extra?"),
            "a4": L("Lower the weeks for unpaid time. Overtime at a higher rate is a second calculation. This page uses one rate, and weeks cannot pass 52.", "无薪就降低周数。更高费率的加班要另算一次。这一页只用一个费率，周数不能超过 52。", "無薪就降低週數。更高費率的加班要另算一次。這一頁只用一個費率，週數不能超過 52。", "無給は週数を下げる。高い単価の残業は別計算。このページは単価一つ。週数は 52 を超えられない。", "무급은 주를 낮추세요. 더 높은 단가의 초과근무는 따로 계산합니다. 이 페이지는 단가 하나이고 주는 52를 넘을 수 없습니다.", "Tuần không lương thì hạ số tuần. Làm thêm với mức cao hơn là một phép tính thứ hai. Trang này dùng một mức, và số tuần không quá 52.", "Turunkan minggu untuk waktu tidak dibayar. Lembur dengan tarif lebih tinggi adalah hitungan kedua. Halaman ini memakai satu tarif, dan minggu tidak boleh lewat 52.", "Baje las semanas por el tiempo sin pagar. Las horas extra a una tarifa mayor son un segundo cálculo. Esta página usa una tarifa, y las semanas no pueden pasar de 52."),
            "q5": L("Is this uploaded?", "会上传吗？", "會上傳嗎？", "アップロードされる？", "업로드되나요?", "Có bị tải lên không?", "Apakah diunggah?", "¿Se sube?"),
            "a5": L("No. Closing the tab discards it.", "不会。关掉标签页就没了。", "不會。關掉分頁就沒了。", "しない。タブを閉じると消える。", "아니요. 탭을 닫으면 사라집니다.", "Không. Đóng tab là mất.", "Tidak. Tutup tab, hilang.", "No. Al cerrar la pestaña se pierde."),
        },
    ),
    "convert-timezone": lesson(
        {
            "name": L("How to convert a time zone", "怎么换算时区", "怎麼換算時區", "タイムゾーンの変換方法", "시간대 변환하는 법", "Cách đổi múi giờ", "Cara ubah zona waktu", "Cómo convertir una zona horaria"),
            "blurb": L("Pick the zone that owns the clock you were given, then the other zone. Daylight saving follows the date. Copy is the UTC instant.", "先选你拿到的那个钟所属的时区，再选另一个时区。夏令时跟着日期走。复制的是 UTC 瞬间。", "先選你拿到的那個鐘所屬的時區，再選另一個時區。日光節約跟著日期走。複製的是 UTC 瞬間。", "渡された時計の属するゾーンを先に選び、次にもう一方。夏時間はその日付に従う。コピーは UTC の瞬間。", "받은 시계가 속한 시간대를 먼저 고르고, 그다음 다른 시간대를 고르세요. 일광 절약 시간은 날짜를 따릅니다. 복사는 UTC 순간입니다.", "Chọn múi giờ của chiếc đồng hồ bạn nhận được, rồi múi giờ kia. Giờ mùa hè theo ngày. Bản copy là khoảnh khắc UTC.", "Pilih zona yang memiliki jam yang Anda terima, lalu zona yang lain. Waktu musim panas mengikuti tanggal. Salinan adalah saat UTC.", "Elija la zona del reloj que le dieron y luego la otra zona. El horario de verano sigue la fecha. Lo que se copia es el instante UTC."),
            "title": L("How to convert a time zone", "怎么换算时区", "怎麼換算時區", "タイムゾーンの変換方法", "시간대 변환하는 법", "Cách đổi múi giờ", "Cara ubah zona waktu", "Cómo convertir una zona horaria"),
            "lead": L("Someone named a clock time in one city. You will choose that zone as the source and the other zone as the destination, then read the offset. Adding the offset again after the page has converted the time moves the meeting.", "有人给了一个城市的钟点。你把那个时区当作来源，把另一个时区当作目的地，再看偏移。页面已经换算之后再加一次偏移，会议时间就会被挪走。", "有人給了一個城市的鐘點。你把那個時區當作來源，把另一個時區當作目的地，再看偏移。頁面已經換算之後再加一次偏移，會議時間就會被挪走。", "ある都市の時計の時刻を渡された。そのゾーンを変換元、もう一方を変換先にし、オフセットを読む。ページが変換したあとオフセットを足すと、会議の時刻がずれる。", "누군가 한 도시의 시계 시각을 알려 줬습니다. 그 시간대를 출발로, 다른 시간대를 도착으로 고른 뒤 오프셋을 읽으세요. 페이지가 바꾼 뒤에 오프셋을 다시 더하면 회의 시각이 밀립니다.", "Ai đó đưa một giờ đồng hồ ở một thành phố. Chọn múi giờ đó làm nguồn, múi giờ kia làm đích, rồi đọc độ lệch. Cộng thêm độ lệch sau khi trang đã đổi sẽ dời cuộc họp.", "Seseorang menyebut jam di satu kota. Pilih zona itu sebagai asal dan zona lain sebagai tujuan, lalu baca offset. Menambah offset lagi setelah halaman mengubah waktu akan menggeser rapat.", "Alguien dio una hora de reloj en una ciudad. Elija esa zona como origen y la otra como destino, y lea el desfase. Sumar el desfase otra vez después de que la página convirtió la hora mueve la reunión."),
            "result": L("The same instant on the other zone's clock, with the offset for that date, and a UTC instant you can copy.", "同一个瞬间在另一个时区的钟上，带上那个日期的偏移，以及可以复制的 UTC 瞬间。", "同一個瞬間在另一個時區的鐘上，帶上那個日期的偏移，以及可以複製的 UTC 瞬間。", "同じ瞬間が相手ゾーンの時計に載る。その日付のオフセットと、コピーできる UTC の瞬間付き。", "같은 순간이 다른 시간대의 시계에 나타납니다. 그 날짜의 오프셋과 복사할 수 있는 UTC 순간이 있습니다.", "Cùng một khoảnh khắc trên đồng hồ múi giờ kia, với độ lệch của ngày đó, và một khoảnh khắc UTC để copy.", "Saat yang sama pada jam zona lain, dengan offset tanggal itu, dan saat UTC yang bisa disalin.", "El mismo instante en el reloj de la otra zona, con el desfase de esa fecha, y un instante UTC que puede copiar."),
            "note": L("Open the timezone converter when you know which zone owns the clock. Now fills the current wall time in the source zone. Nothing is uploaded.", "知道那个钟属于哪个时区再打开时区转换。现在会填入来源时区的当前墙钟时间。不上传。", "知道那個鐘屬於哪個時區再開時區轉換。現在會填入來源時區的目前牆鐘時間。不上傳。", "時計がどのゾーンのものか分かってから開く。今は変換元ゾーンの現在の壁時計を入れる。アップロードなし。", "그 시계가 어느 시간대 것인지 알 때 시간대 변환을 여세요. 지금은 출발 시간대의 현재 벽시계를 채웁니다. 업로드 없음.", "Biết chiếc đồng hồ thuộc múi giờ nào thì mở đổi múi giờ. Bây giờ điền giờ tường hiện tại của múi nguồn. Không tải lên.", "Tahu zona pemilik jam itu, baru buka pengubah zona. Sekarang mengisi waktu dinding saat ini di zona asal. Tidak diunggah.", "Abra el conversor cuando sepa qué zona posee el reloj. Ahora rellena la hora de pared actual en la zona de origen. Nada se sube."),
            "s1t": L("Name the zone that owns the clock", "先点名这个钟属于哪个时区", "先點名這個鐘屬於哪個時區", "その時計のゾーンを名指しする", "그 시계의 시간대를 지목하기", "Chỉ đúng múi giờ của chiếc đồng hồ", "Sebut zona pemilik jam itu", "Nombre la zona dueña del reloj"),
            "s1b": L("A 9:00 from a New York calendar belongs to America/New_York, even if you are in Shanghai. The source is their clock. The destination is the clock you need.", "纽约日历上的 9:00 属于 America/New_York，即使你人在上海。来源是他们的钟。目的地是你需要的那个钟。", "紐約日曆上的 9:00 屬於 America/New_York，即使你人在上海。來源是他們的鐘。目的地是你需要的那個鐘。", "ニューヨークの暦の 9:00 は America/New_York。上海にいても。変換元は相手の時計。変換先は必要な時計。", "뉴욕 달력의 9:00은 당신이 상하이에 있어도 America/New_York입니다. 출발은 그들의 시계. 도착은 당신이 필요한 시계입니다.", "9:00 trên lịch New York thuộc America/New_York, dù bạn đang ở Thượng Hải. Nguồn là đồng hồ của họ. Đích là đồng hồ bạn cần.", "9:00 dari kalender New York milik America/New_York, meski Anda di Shanghai. Asal adalah jam mereka. Tujuan adalah jam yang Anda butuhkan.", "Las 9:00 de un calendario de Nueva York pertenecen a America/New_York, aunque usted esté en Shanghái. El origen es su reloj. El destino es el reloj que necesita."),
            "s2t": L("Open the timezone converter on cv.cm", "打开 cv.cm 的时区转换", "打開 cv.cm 的時區轉換", "cv.cmのタイムゾーン変換を開く", "cv.cm 시간대 변환을 열기", "Mở đổi múi giờ trên cv.cm", "Buka pengubah zona di cv.cm", "Abra el conversor de zona en cv.cm"),
            "s2b": L("Conversion stays in this tab.", "换算留在当前标签页。", "換算留在目前分頁。", "変換はこのタブ。", "변환은 이 탭에서.", "Đổi trong tab này.", "Konversi di tab ini.", "La conversión queda en esta pestaña."),
            "s3t": L("Set both zones and the date-time", "设定两个时区和日期时间", "設定兩個時區和日期時間", "両方のゾーンと日時を入れる", "두 시간대와 날짜·시각 넣기", "Đặt cả hai múi giờ và ngày giờ", "Atur kedua zona dan tanggal-waktu", "Fije ambas zonas y la fecha y hora"),
            "s3b": L("Now fills the current wall time in the source zone. The date matters because the offset can change.", "现在会填入来源时区的当前墙钟时间。日期要紧，因为偏移会变。", "現在會填入來源時區的目前牆鐘時間。日期要緊，因為偏移會變。", "今は変換元ゾーンの現在の壁時計を入れる。日付が大事。オフセットは変わり得る。", "지금은 출발 시간대의 현재 벽시계를 채웁니다. 날짜가 중요합니다. 오프셋은 바뀔 수 있습니다.", "Bây giờ điền giờ tường hiện tại của múi nguồn. Ngày quan trọng vì độ lệch có thể đổi.", "Sekarang mengisi waktu dinding saat ini di zona asal. Tanggal penting karena offset bisa berubah.", "Ahora rellena la hora de pared actual en la zona de origen. La fecha importa porque el desfase puede cambiar."),
            "s4t": L("Read the offset on that date", "看那个日期上的偏移", "看那個日期上的偏移", "その日付のオフセットを読む", "그 날짜의 오프셋 읽기", "Đọc độ lệch của ngày đó", "Baca offset pada tanggal itu", "Lea el desfase de esa fecha"),
            "s4b": L("New York in January is UTC−05:00. In July it is UTC−04:00. The page uses the IANA rule for the date you picked. A skipped hour in spring does not exist. A repeated hour in autumn happens twice. If your time sits in that gap or overlap, read the offset before you trust the wall time.", "纽约在一月是 UTC−05:00。在七月是 UTC−04:00。这一页用你选的日期对应的 IANA 规则。春天被跳过的那一小时不存在。秋天重复的那一小时出现两次。你的时间落在缺口或重叠里，先看偏移，再信墙钟时间。", "紐約在一月是 UTC−05:00。在七月是 UTC−04:00。這一頁用你選的日期對應的 IANA 規則。春天被跳過的那一小時不存在。秋天重複的那一小時出現兩次。你的時間落在缺口或重疊裡，先看偏移，再信牆鐘時間。", "ニューヨークは1月が UTC−05:00、7月が UTC−04:00。このページは選んだ日付の IANA 規則を使う。春に飛ばされる1時間は存在しない。秋に繰り返される1時間は二度ある。その隙間か重なりなら、壁時計を信じる前にオフセットを読む。", "뉴욕은 1월에 UTC−05:00, 7월에 UTC−04:00입니다. 이 페이지는 고른 날짜의 IANA 규칙을 씁니다. 봄에 건너뛴 한 시간은 없습니다. 가을에 반복되는 한 시간은 두 번 있습니다. 시각이 그 빈틈이나 겹침에 있으면 벽시계를 믿기 전에 오프셋을 읽으세요.", "New York tháng Một là UTC−05:00. Tháng Bảy là UTC−04:00. Trang dùng quy tắc IANA của ngày bạn chọn. Giờ bị nhảy vào mùa xuân không tồn tại. Giờ lặp vào mùa thu xảy ra hai lần. Nếu giờ của bạn nằm trong khoảng trống hoặc chồng đó, hãy đọc độ lệch trước khi tin giờ tường.", "New York pada Januari adalah UTC−05:00. Pada Juli UTC−04:00. Halaman memakai aturan IANA untuk tanggal yang Anda pilih. Jam yang dilewati di musim semi tidak ada. Jam yang berulang di musim gugur terjadi dua kali. Jika waktu Anda jatuh di celah atau tumpang tindih itu, baca offset sebelum memercayai waktu dinding.", "Nueva York en enero es UTC−05:00. En julio es UTC−04:00. La página usa la regla IANA de la fecha elegida. Una hora saltada en primavera no existe. Una hora repetida en otoño ocurre dos veces. Si su hora cae en ese hueco o solapamiento, lea el desfase antes de fiarse de la hora de pared."),
            "s5t": L("Copy the UTC instant", "复制 UTC 瞬间", "複製 UTC 瞬間", "UTC の瞬間をコピー", "UTC 순간 복사", "Copy khoảnh khắc UTC", "Salin saat UTC", "Copie el instante UTC"),
            "s5b": L("Copy puts the ISO time in UTC on the clipboard. That is the same moment. It is the instant, and the wall-clock line stays on the page. An API that wants UTC wants that ISO string.", "复制把 UTC 的 ISO 时间放进剪贴板。那是同一个瞬间。它是瞬间本身，墙钟那一行留在页面上。要 UTC 的接口要的就是这个 ISO 字符串。", "複製把 UTC 的 ISO 時間放進剪貼簿。那是同一個瞬間。它是瞬間本身，牆鐘那一行留在頁面上。要 UTC 的介面要的就是這個 ISO 字串。", "コピーは UTC の ISO 時刻をクリップボードへ。同じ瞬間。瞬間そのものであり、壁時計の行はページに残る。UTC を求める API はその ISO 文字列を求める。", "복사는 UTC의 ISO 시각을 클립보드에 넣습니다. 같은 순간입니다. 순간 그 자체이고, 벽시계 줄은 페이지에 남습니다. UTC를 원하는 API는 그 ISO 문자열을 원합니다.", "Copy đưa giờ ISO theo UTC vào clipboard. Đó là cùng một khoảnh khắc. Đó là khoảnh khắc, dòng giờ tường ở lại trên trang. API cần UTC thì cần chuỗi ISO đó.", "Salin menaruh waktu ISO dalam UTC di papan klip. Itu saat yang sama. Itu adalah saatnya, dan baris waktu dinding tetap di halaman. API yang minta UTC menginginkan string ISO itu.", "Copiar pone la hora ISO en UTC en el portapapeles. Es el mismo momento. Es el instante, y la línea de la hora de pared se queda en la página. Una API que pide UTC quiere esa cadena ISO."),
            "s6t": L("Leave the offset where the page put it", "偏移留在页面已经放好的地方", "偏移留在頁面已經放好的地方", "オフセットはページが置いた場所に残す", "오프셋은 페이지가 둔 자리에 두기", "Để độ lệch ở chỗ trang đã đặt", "Biarkan offset di tempat halaman menaruhnya", "Deje el desfase donde la página lo puso"),
            "s6b": L("The result is already the other zone's clock. Adding +8 or −5 again moves the meeting. Compare one known moment, such as 12:00 in the source zone, before you send the time.", "结果已经是另一个时区的钟。再加一次 +8 或 −5，会议就被挪走。发出去之前，用一个已知瞬间核对，例如来源时区的 12:00。", "結果已經是另一個時區的鐘。再加一次 +8 或 −5，會議就被挪走。寄出去之前，用一個已知瞬間核對，例如來源時區的 12:00。", "結果はすでに相手ゾーンの時計。+8 や −5 を足すと会議がずれる。送る前に、変換元の 12:00 のような既知の瞬間で照合する。", "결과는 이미 다른 시간대의 시계입니다. +8이나 −5를 다시 더하면 회의가 밀립니다. 보내기 전에 출발 시간대의 12:00 같은 아는 순간으로 대조하세요.", "Kết quả đã là đồng hồ múi giờ kia. Cộng thêm +8 hoặc −5 sẽ dời cuộc họp. Trước khi gửi, đối chiếu một khoảnh khắc đã biết, chẳng hạn 12:00 ở múi nguồn.", "Hasilnya sudah jam zona lain. Menambah +8 atau −5 lagi menggeser rapat. Sebelum mengirim, bandingkan satu saat yang diketahui, misalnya 12:00 di zona asal.", "El resultado ya es el reloj de la otra zona. Sumar +8 o −5 otra vez mueve la reunión. Antes de enviarla, compare un momento conocido, como las 12:00 en la zona de origen."),
            "diagram1": L("Source is the zone that owns the clock. Destination is the clock you need.", "来源是这个钟所属的时区。目的地是你需要的那个钟。", "來源是這個鐘所屬的時區。目的地是你需要的那個鐘。", "変換元はその時計のゾーン。変換先は必要な時計。", "출발은 그 시계의 시간대. 도착은 필요한 시계.", "Nguồn là múi giờ của chiếc đồng hồ. Đích là đồng hồ bạn cần.", "Asal adalah zona pemilik jam. Tujuan adalah jam yang Anda butuhkan.", "El origen es la zona dueña del reloj. El destino es el reloj que necesita."),
            "diagram2": L("January in New York is UTC−05:00. July is UTC−04:00. Copy the UTC instant.", "纽约一月是 UTC−05:00。七月是 UTC−04:00。复制 UTC 瞬间。", "紐約一月是 UTC−05:00。七月是 UTC−04:00。複製 UTC 瞬間。", "ニューヨークは1月 UTC−05:00、7月 UTC−04:00。UTC の瞬間をコピー。", "뉴욕 1월은 UTC−05:00. 7월은 UTC−04:00. UTC 순간을 복사하세요.", "New York tháng Một là UTC−05:00. Tháng Bảy là UTC−04:00. Copy khoảnh khắc UTC.", "New York Januari UTC−05:00. Juli UTC−04:00. Salin saat UTC.", "Nueva York en enero es UTC−05:00. En julio, UTC−04:00. Copie el instante UTC."),
        },
        {
            "q1": L("Can I convert a time zone free online?", "可以免费在线换算时区吗？", "可以免費線上換算時區嗎？", "タイムゾーンを無料で変換できる？", "시간대를 무료로 변환할 수 있나요?", "Đổi múi giờ miễn phí online được không?", "Bisa ubah zona waktu gratis online?", "¿Puedo convertir una zona horaria gratis en línea?"),
            "a1": L("Yes. cv.cm converts a wall time between two IANA zones in this tab. Nothing is uploaded.", "可以。cv.cm 在当前标签页把墙钟时间在两个 IANA 时区之间换算。不上传。", "可以。cv.cm 在目前分頁把牆鐘時間在兩個 IANA 時區之間換算。不上傳。", "できる。このタブで二つの IANA ゾーンの壁時計を変換。アップロードなし。", "됩니다. 이 탭에서 두 IANA 시간대 사이의 벽시계를 변환합니다. 업로드 없음.", "Được. Đổi giờ tường giữa hai múi IANA trong tab này. Không tải lên.", "Ya. Mengubah waktu dinding antara dua zona IANA di tab ini. Tidak diunggah.", "Sí. Convierte una hora de pared entre dos zonas IANA en esta pestaña. Nada se sube."),
            "q2": L("Does daylight saving apply?", "夏令时算进去吗？", "日光節約算進去嗎？", "夏時間は入る？", "일광 절약 시간이 적용되나요?", "Có tính giờ mùa hè không?", "Apakah waktu musim panas berlaku?", "¿Se aplica el horario de verano?"),
            "a2": L("Yes. New York in January is UTC−05:00. In July it is UTC−04:00. The offset follows the date you picked.", "算。纽约在一月是 UTC−05:00。在七月是 UTC−04:00。偏移跟着你选的日期。", "算。紐約在一月是 UTC−05:00。在七月是 UTC−04:00。偏移跟著你選的日期。", "入る。ニューヨークは1月が UTC−05:00、7月が UTC−04:00。オフセットは選んだ日付に従う。", "적용됩니다. 뉴욕은 1월에 UTC−05:00, 7월에 UTC−04:00입니다. 오프셋은 고른 날짜를 따릅니다.", "Có. New York tháng Một là UTC−05:00. Tháng Bảy là UTC−04:00. Độ lệch theo ngày bạn chọn.", "Ya. New York pada Januari adalah UTC−05:00. Pada Juli UTC−04:00. Offset mengikuti tanggal yang Anda pilih.", "Sí. Nueva York en enero es UTC−05:00. En julio es UTC−04:00. El desfase sigue la fecha que eligió."),
            "q3": L("Which zone is the source?", "哪个时区是来源？", "哪個時區是來源？", "変換元はどのゾーン？", "출발 시간대는 어느 쪽인가요?", "Múi giờ nào là nguồn?", "Zona mana yang menjadi asal?", "¿Qué zona es el origen?"),
            "a3": L("The zone that owns the clock you were given. A New York 9:00 stays America/New_York even if you are somewhere else.", "你拿到的那个钟所属的时区。纽约的 9:00 仍是 America/New_York，即使你在别的地方。", "你拿到的那個鐘所屬的時區。紐約的 9:00 仍是 America/New_York，即使你在別的地方。", "渡された時計のゾーン。ニューヨークの 9:00 は、別の場所にいても America/New_York。", "받은 시계가 속한 시간대입니다. 뉴욕의 9:00은 다른 곳에 있어도 America/New_York입니다.", "Múi giờ của chiếc đồng hồ bạn nhận được. 9:00 ở New York vẫn là America/New_York dù bạn ở nơi khác.", "Zona pemilik jam yang Anda terima. 9:00 New York tetap America/New_York meski Anda di tempat lain.", "La zona dueña del reloj que le dieron. Las 9:00 de Nueva York siguen siendo America/New_York aunque usted esté en otro sitio."),
            "q4": L("What does copy put on the clipboard?", "复制放进剪贴板的是什么？", "複製放進剪貼簿的是什麼？", "コピーは何を入れる？", "복사는 무엇을 넣나요?", "Copy đưa gì vào clipboard?", "Salin menaruh apa di papan klip?", "¿Qué pone copiar en el portapapeles?"),
            "a4": L("The ISO time of that instant in UTC. The wall-clock line stays on the page.", "那个瞬间的 UTC ISO 时间。墙钟那一行留在页面上。", "那個瞬間的 UTC ISO 時間。牆鐘那一行留在頁面上。", "その瞬間の UTC の ISO 時刻。壁時計の行はページに残る。", "그 순간의 UTC ISO 시각입니다. 벽시계 줄은 페이지에 남습니다.", "Giờ ISO của khoảnh khắc đó theo UTC. Dòng giờ tường ở lại trên trang.", "Waktu ISO saat itu dalam UTC. Baris waktu dinding tetap di halaman.", "La hora ISO de ese instante en UTC. La línea de la hora de pared se queda en la página."),
            "q5": L("Is the time uploaded?", "时间会上传吗？", "時間會上傳嗎？", "アップロードされる？", "업로드되나요?", "Giờ có bị tải lên không?", "Apakah waktunya diunggah?", "¿Se sube la hora?"),
            "a5": L("No. Closing the tab discards it.", "不会。关掉标签页就没了。", "不會。關掉分頁就沒了。", "しない。タブを閉じると消える。", "아니요. 탭을 닫으면 사라집니다.", "Không. Đóng tab là mất.", "Tidak. Tutup tab, hilang.", "No. Al cerrar la pestaña se pierde."),
        },
    ),
}

META = {
    "titleCountWorkdays": L("How to count business days | cv.cm", "怎么数工作日 | cv.cm", "怎麼數工作日 | cv.cm", "営業日の数え方 | cv.cm", "근무일 세는 법 | cv.cm", "Cách đếm ngày làm việc | cv.cm", "Cara hitung hari kerja | cv.cm", "Cómo contar días laborables | cv.cm"),
    "descCountWorkdays": L("Count Monday through Friday between two dates, including both ends. Holidays stay in the count. A same-day weekday is 1. Nothing is uploaded.", "数两个日期之间的周一到周五，两头都算。假日仍留在计数里。同一个工作日是 1。不上传。", "數兩個日期之間的週一到週五，兩頭都算。假日仍留在計數裡。同一個工作日是 1。不上傳。", "二つの日付の月曜から金曜を両端含めて数える。祝日は数に残る。同じ平日は 1。アップロードなし。", "두 날짜 사이의 월~금을 양쪽 포함해 셉니다. 공휴일은 세에 남습니다. 같은 평일은 1. 업로드 없음.", "Đếm thứ Hai đến thứ Sáu giữa hai ngày, tính cả hai đầu. Ngày lễ vẫn trong số đếm. Cùng một ngày trong tuần là 1. Không tải lên.", "Hitung Senin sampai Jumat di antara dua tanggal, termasuk kedua ujung. Hari libur tetap di hitungan. Hari kerja yang sama adalah 1. Tidak diunggah.", "Cuente de lunes a viernes entre dos fechas, incluidos ambos extremos. Los festivos siguen en la cuenta. El mismo día laborable es 1. Nada se sube."),
    "titleSimplifyFraction": L("How to simplify a fraction | cv.cm", "怎么约分 | cv.cm", "怎麼約分 | cv.cm", "分数を約分する方法 | cv.cm", "분수 약분하는 법 | cv.cm", "Cách rút gọn phân số | cv.cm", "Cara sederhanakan pecahan | cv.cm", "Cómo simplificar una fracción | cv.cm"),
    "descSimplifyFraction": L("Reduce a whole numerator and denominator, or turn a decimal into a fraction. 4/6 becomes 2/3. A decimal stops at denominator 10,000. Nothing is uploaded.", "把整数分子和分母约分，或把小数变成分数。4/6 变成 2/3。小数的分母停在 10,000。不上传。", "把整數分子和分母約分，或把小數變成分數。4/6 變成 2/3。小數的分母停在 10,000。不上傳。", "整数の分子と分母を約分するか、小数を分数にする。4/6 は 2/3。小数の分母は 10,000 で止まる。アップロードなし。", "정수 분자와 분모를 약분하거나 소수를 분수로 바꿉니다. 4/6은 2/3. 소수의 분모는 10,000에서 멈춥니다. 업로드 없음.", "Rút gọn tử và mẫu nguyên, hoặc đổi số thập phân thành phân số. 4/6 thành 2/3. Số thập phân dừng ở mẫu 10.000. Không tải lên.", "Sederhanakan pembilang dan penyebut bulat, atau ubah desimal menjadi pecahan. 4/6 menjadi 2/3. Desimal berhenti di penyebut 10.000. Tidak diunggah.", "Reduzca numerador y denominador enteros, o convierta un decimal en fracción. 4/6 pasa a 2/3. Un decimal se detiene en el denominador 10.000. Nada se sube."),
    "titleHourlyPay": L("How to convert hourly pay to a yearly salary | cv.cm", "怎么把时薪换成年薪 | cv.cm", "怎麼把時薪換成年薪 | cv.cm", "時給を年収に換算する方法 | cv.cm", "시급을 연봉으로 바꾸는 법 | cv.cm", "Cách đổi lương giờ sang lương năm | cv.cm", "Cara ubah upah per jam jadi gaji tahunan | cv.cm", "Cómo convertir el pago por hora en un sueldo anual | cv.cm"),
    "descHourlyPay": L("Multiply one hourly rate by hours per week and weeks per year. 40 by 52 is 2,080 hours. The result is gross pay, not take-home. Nothing is uploaded.", "用一个时薪乘每周小时和每年周数。40 乘 52 是 2,080 小时。结果是税前，不是到手。不上传。", "用一個時薪乘每週小時和每年週數。40 乘 52 是 2,080 小時。結果是稅前，不是到手。不上傳。", "一つの時給に週の時間と年の週数をかける。40×52 は 2,080 時間。結果は税引前であり手取りではない。アップロードなし。", "시급 하나에 주당 시간과 연간 주를 곱합니다. 40×52는 2,080시간. 결과는 세전이지 실수령이 아닙니다. 업로드 없음.", "Nhân một lương giờ với giờ mỗi tuần và số tuần mỗi năm. 40 nhân 52 là 2.080 giờ. Kết quả là trước thuế, không phải tiền mang về. Không tải lên.", "Kalikan satu upah per jam dengan jam per minggu dan minggu per tahun. 40 kali 52 adalah 2.080 jam. Hasilnya gaji kotor, bukan dibawa pulang. Tidak diunggah.", "Multiplique una tarifa por hora por horas semanales y semanas al año. 40 por 52 son 2.080 horas. El resultado es el bruto, no lo que se lleva a casa. Nada se sube."),
    "titleConvertTimezone": L("How to convert a time zone | cv.cm", "怎么换算时区 | cv.cm", "怎麼換算時區 | cv.cm", "タイムゾーンの変換方法 | cv.cm", "시간대 변환하는 법 | cv.cm", "Cách đổi múi giờ | cv.cm", "Cara ubah zona waktu | cv.cm", "Cómo convertir una zona horaria | cv.cm"),
    "descConvertTimezone": L("Convert a wall time between two IANA zones. Daylight saving follows the date. Copy is the UTC instant. Do not add the offset twice. Nothing is uploaded.", "在两个 IANA 时区之间换算墙钟时间。夏令时跟着日期走。复制的是 UTC 瞬间。不要把偏移加两次。不上传。", "在兩個 IANA 時區之間換算牆鐘時間。日光節約跟著日期走。複製的是 UTC 瞬間。不要把偏移加兩次。不上傳。", "二つの IANA ゾーンの壁時計を変換。夏時間はその日付に従う。コピーは UTC の瞬間。オフセットを二度足さない。アップロードなし。", "두 IANA 시간대 사이의 벽시계를 변환합니다. 일광 절약 시간은 날짜를 따릅니다. 복사는 UTC 순간. 오프셋을 두 번 더하지 마세요. 업로드 없음.", "Đổi giờ tường giữa hai múi IANA. Giờ mùa hè theo ngày. Bản copy là khoảnh khắc UTC. Đừng cộng độ lệch hai lần. Không tải lên.", "Ubah waktu dinding antara dua zona IANA. Waktu musim panas mengikuti tanggal. Salinan adalah saat UTC. Jangan menambah offset dua kali. Tidak diunggah.", "Convierta una hora de pared entre dos zonas IANA. El horario de verano sigue la fecha. Lo copiado es el instante UTC. No sume el desfase dos veces. Nada se sube."),
}


def inject() -> None:
    if set(LESSONS) != {"count-workdays", "simplify-fraction", "hourly-pay", "convert-timezone"}:
        raise SystemExit("lesson ids")
    for loc, path in FILES.items():
        data = json.loads(path.read_text())
        data["faq"].setdefault("learn", {})
        for lesson_id, payload in LESSONS.items():
            data["learn"][lesson_id] = payload["copy"][loc]
            data["faq"]["learn"][lesson_id] = payload["faq"][loc]
        for key, by_loc in META.items():
            data["meta"][key] = by_loc[loc]
        path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n")
        print("patched", path.name)


if __name__ == "__main__":
    inject()
