#!/usr/bin/env python3
"""Inject PNG→WebP, MP3→WAV, join-audio, and favicon how-tos."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LOCS = ["en", "zh-CN", "zh-TW", "ja", "ko", "vi", "id", "es"]
FILES = {loc: ROOT / "src/locales" / f"{loc}.json" for loc in LOCS}


def L(*vals: str) -> dict[str, str]:
    if len(vals) != 8:
        raise ValueError(len(vals), vals[0] if vals else None)
    return dict(zip(LOCS, vals))


def lesson(fields: dict[str, dict[str, str]], faq: dict[str, dict[str, str]]) -> dict:
    return {
        "copy": {loc: {k: v[loc] for k, v in fields.items()} for loc in LOCS},
        "faq": {loc: {k: v[loc] for k, v in faq.items()} for loc in LOCS},
    }


LESSONS = {
    "png-to-webp": lesson(
        {
            "name": L("How to convert PNG to WebP", "怎么把 PNG 转成 WebP", "怎麼把 PNG 轉成 WebP", "PNGをWebPにする", "PNG를 WebP로", "Cách đổi PNG sang WebP", "Cara ubah PNG ke WebP", "Cómo pasar PNG a WebP"),
            "blurb": L("Pick WebP for a smaller file that can keep a clear background. Then open it in a browser, not in an old form.", "要更小还能留透明底，就选 WebP。再用浏览器打开看，不要丢进不认 WebP 的老表单。", "要更小還能留透明底，就選 WebP。再用瀏覽器打開看，不要丟進不認 WebP 的老表單。", "小さくて透明も残すならWebP。ブラウザで開く。WebPを拒む提出には入れない。", "더 작으면서 투명을 남기려면 WebP. 브라우저에서 여세요. WebP를 거부하는 옛 서류에는 넣지 마세요.", "Muốn nhẹ mà còn nền trong thì chọn WebP. Mở bằng trình duyệt, đừng thả vào form cũ từ chối WebP.", "Lebih kecil dan bisa jaga latar tembus: pilih WebP. Buka di peramban, jangan ke formulir lama yang menolak WebP.", "Elija WebP para menos peso y fondo transparente. Ábralo en un navegador, no en un formulario viejo que lo rechace."),
            "title": L("How to convert PNG to WebP", "怎么把 PNG 转成 WebP", "怎麼把 PNG 轉成 WebP", "PNGをWebPにする方法", "PNG를 WebP로 변환하는 법", "Cách đổi PNG sang WebP", "Cara ubah PNG ke WebP", "Cómo pasar PNG a WebP"),
            "lead": L("WebP is smaller than PNG and can keep transparency, unlike JPG. You convert a copy for the web, then check the file in a current browser.", "WebP 比 PNG 小，还能留透明，JPG 做不到。给网页转一份，再用现在的浏览器打开核对。", "WebP 比 PNG 小，還能留透明，JPG 做不到。給網頁轉一份，再用現在的瀏覽器打開核對。", "WebPはPNGより小さく透明も残せる。JPGにはできない。ウェブ用にコピーを変換し、今のブラウザで確認。", "WebP는 PNG보다 작고 투명을 남길 수 있습니다. JPG는 못 합니다. 웹용 복사본을 변환한 뒤 최신 브라우저에서 확인하세요.", "WebP nhẹ hơn PNG và giữ nền trong, JPG thì không. Đổi một bản cho web, mở bằng trình duyệt hiện tại.", "WebP lebih kecil dari PNG dan bisa jaga transparansi, JPG tidak. Ubah salinan untuk web, cek di peramban baru.", "WebP pesa menos que PNG y puede conservar transparencia; JPG no. Convierta una copia para la web y compruébela en un navegador actual."),
            "result": L("A WebP that is smaller than the PNG, with transparency intact if the original had it, plus the PNG still on disk.", "一份比 PNG 更小的 WebP；原图有透明底就还在。原 PNG 还在磁盘上。", "一份比 PNG 更小的 WebP；原圖有透明底就還在。原 PNG 還在磁碟上。", "PNGより小さいWebP。元が透明なら残る。元のPNGは残る。", "PNG보다 작은 WebP. 원본에 투명이 있으면 남습니다. 원본 PNG는 디스크에 남습니다.", "WebP nhẹ hơn PNG; nền trong còn nếu bản gốc có. PNG gốc còn trên đĩa.", "WebP lebih kecil dari PNG; transparansi utuh jika aslinya ada. PNG asli tetap di disk.", "Un WebP más liviano que el PNG, con transparencia si el original la tenía, y el PNG en el disco."),
            "note": L("Open convert when the .png is on disk. Pick WebP, not JPG, if you need a clear background. Old forms may still reject WebP. Nothing is uploaded.", "文件在磁盘上再打开格式转换。要透明底就选 WebP，不要选 JPG。老表单可能仍不认 WebP。不上传。", "檔在磁碟上再打開格式轉換。要透明底就選 WebP，不要選 JPG。老表單可能仍不認 WebP。不上傳。", "ファイルが手元にあってから変換を開く。透明が要るならJPGではなくWebP。古い提出はまだ拒むことがある。アップロードなし。", "파일이 디스크에 있으면 변환을 여세요. 투명이 필요하면 JPG가 아니라 WebP. 옛 서류는 여전히 WebP를 거부할 수 있습니다. 업로드 없음.", "Có file .png trên đĩa thì mở chuyển đổi. Cần nền trong thì chọn WebP, đừng JPG. Form cũ vẫn có thể từ chối WebP. Không tải lên.", "File .png di disk, baru buka konversi. Butuh latar tembus: pilih WebP, bukan JPG. Formulir lama mungkin menolak WebP. Tidak diunggah.", "Abra convertir con el .png en el disco. Si necesita fondo transparente, elija WebP, no JPG. Los formularios viejos aún pueden rechazar WebP. Nada se sube."),
            "s1t": L("Decide why you need WebP", "先想清楚为什么要 WebP", "先想清楚為什麼要 WebP", "なぜWebPか決める", "왜 WebP인지 정하기", "Quyết định vì sao cần WebP", "Tentukan kenapa perlu WebP", "Decida por qué necesita WebP"),
            "s1b": L("A site or a chat that accepts WebP will load faster. Email and many school forms still want PNG or JPG. Do not convert if the destination rejects WebP.", "网站或聊天认 WebP，就会更快。邮件和不少学校表单仍要 PNG 或 JPG。对方不认就别转。", "網站或聊天認 WebP，就會更快。郵件和不少學校表單仍要 PNG 或 JPG。對方不認就別轉。", "WebPを受け入れるサイトやチャットは軽い。メールや提出はまだPNG/JPG。先が拒むなら変換しない。", "WebP를 받는 사이트나 채팅은 더 빠릅니다. 이메일과 많은 서류는 아직 PNG나 JPG. 상대가 거부하면 바꾸지 마세요.", "Site hoặc chat nhận WebP sẽ nhẹ hơn. Email và nhiều form vẫn cần PNG hoặc JPG. Đích từ chối thì đừng đổi.", "Situs atau chat yang menerima WebP lebih cepat. Email dan banyak formulir masih PNG/JPG. Jika ditolak, jangan ubah.", "Un sitio o un chat que acepta WebP carga más rápido. El correo y muchos formularios siguen pidiendo PNG o JPG. No convierta si el destino rechaza WebP."),
            "s2t": L("Open image formats on cv.cm", "打开 cv.cm 的图片格式", "打開 cv.cm 的圖片格式", "cv.cmの画像形式を開く", "cv.cm 이미지 형식을 열기", "Mở định dạng ảnh trên cv.cm", "Buka format gambar di cv.cm", "Abra formatos de imagen en cv.cm"),
            "s2b": L("Work stays in this tab. Closing it discards the file.", "转换留在当前标签页。关掉就没了。", "轉換留在目前分頁。關掉就沒了。", "このタブで処理。閉じると消える。", "이 탭에서 변환합니다. 닫으면 사라집니다.", "Xử lý trong tab này. Đóng là mất.", "Proses di tab ini. Tutup, hilang.", "El trabajo queda en esta pestaña. Al cerrarla se pierde."),
            "s3t": L("Drop the .png file", "拖入 .png", "拖入 .png", ".pngをドロップ", ".png 넣기", "Thả file .png", "Letakkan .png", "Suelte el .png"),
            "s3b": L("One file or a batch. If the preview is blank, try another browser.", "一张或一批。预览空白，换浏览器。", "一張或一批。預覽空白，換瀏覽器。", "1枚でもまとめてでも。プレビューが空ならブラウザを変える。", "한 장 또는 여러 장. 미리보기가 비면 브라우저를 바꾸세요.", "Một hoặc nhiều. Xem trước trống thì đổi trình duyệt.", "Satu atau batch. Pratinjau kosong: ganti peramban.", "Uno o varios. Si la vista está en blanco, cambie de navegador."),
            "s4t": L("Pick WebP, not JPG, if you need transparency", "要透明底就选 WebP，不要选 JPG", "要透明底就選 WebP，不要選 JPG", "透明が要るならJPGではなくWebP", "투명이 필요하면 JPG가 아니라 WebP", "Cần nền trong thì chọn WebP, đừng JPG", "Butuh transparansi: pilih WebP, bukan JPG", "Si necesita transparencia, elija WebP, no JPG"),
            "s4b": L("WebP can keep a clear background. JPG will fill it. Start quality near 0.9. Optional max edge only if a page has a pixel cap.", "WebP 能留透明。JPG 会填死。质量先从 0.9。页面有像素上限再限制长边。", "WebP 能留透明。JPG 會填死。品質先從 0.9。頁面有像素上限再限制長邊。", "WebPは透明を残せる。JPGは埋める。品質は0.9前後。画素上限があるときだけ長辺を制限。", "WebP는 투명을 남길 수 있습니다. JPG는 메웁니다. 품질은 0.9 근처. 페이지에 픽셀 한도가 있을 때만 긴 변을 제한하세요.", "WebP giữ nền trong. JPG sẽ lấp. Chất lượng khoảng 0.9. Chỉ giới hạn cạnh dài nếu trang có trần pixel.", "WebP menjaga latar tembus. JPG mengisi. Kualitas sekitar 0.9. Batasi sisi hanya jika halaman punya batas piksel.", "WebP puede conservar el fondo. JPG lo rellena. Calidad cerca de 0.9. Limite el lado largo solo si hay tope de píxeles."),
            "s5t": L("Download the WebP", "下载 WebP", "下載 WebP", "WebPを保存", "WebP 받기", "Tải WebP", "Unduh WebP", "Descargue el WebP"),
            "s5b": L("Keep the PNG until you have opened the WebP.", "打开 WebP 之前留着 PNG。", "打開 WebP 之前留著 PNG。", "WebPを開くまでPNGを残す。", "WebP를 열 때까지 PNG를 남기세요.", "Giữ PNG đến khi đã mở WebP.", "Simpan PNG sampai WebP terbuka.", "Conserve el PNG hasta haber abierto el WebP."),
            "s6t": L("Open it in a current browser", "用现在的浏览器打开", "用現在的瀏覽器打開", "今のブラウザで開く", "최신 브라우저에서 열기", "Mở bằng trình duyệt hiện tại", "Buka di peramban baru", "Ábralo en un navegador actual"),
            "s6b": L("Check the edges and the file size against the PNG. If a form still rejects it, send the PNG. Converting does not add sharpness.", "看边缘，再和 PNG 比体积。表单仍拒收，就发 PNG。转换不会让图更清晰。", "看邊緣，再和 PNG 比體積。表單仍拒收，就傳 PNG。轉換不會讓圖更清晰。", "端とサイズをPNGと比べる。提出が拒むならPNGを送る。変換してもSharpにはならない。", "가장자리와 용량을 PNG와 비교하세요. 서류가 거부하면 PNG를 보내세요. 변환한다고 더 선명해지지 않습니다.", "Kiểm mép và dung lượng so với PNG. Form vẫn từ chối thì gửi PNG. Đổi định dạng không làm nét hơn.", "Cek tepi dan ukuran dibanding PNG. Formulir menolak: kirim PNG. Konversi tidak menambah ketajaman.", "Mire los bordes y el peso frente al PNG. Si el formulario lo rechaza, envíe el PNG. Convertir no añade nitidez."),
            "diagram1": L("WebP is smaller than PNG and can keep a clear background. JPG cannot.", "WebP 比 PNG 小，还能留透明。JPG 不行。", "WebP 比 PNG 小，還能留透明。JPG 不行。", "WebPはPNGより小さく透明も残せる。JPGは不可。", "WebP는 PNG보다 작고 투명을 남길 수 있습니다. JPG는 안 됩니다.", "WebP nhẹ hơn PNG và giữ nền trong. JPG thì không.", "WebP lebih kecil dari PNG dan bisa jaga latar tembus. JPG tidak.", "WebP pesa menos que PNG y puede conservar el fondo. JPG no."),
            "diagram2": L("Pick WebP to keep alpha. Open it in a browser. Old forms may still want PNG.", "要透明就选 WebP。用浏览器打开。老表单可能仍要 PNG。", "要透明就選 WebP。用瀏覽器打開。老表單可能仍要 PNG。", "透明ならWebP。ブラウザで開く。古い提出はまだPNG。", "투명이면 WebP. 브라우저에서 여세요. 옛 서류는 아직 PNG일 수 있습니다.", "Cần trong thì chọn WebP. Mở bằng trình duyệt. Form cũ vẫn có thể cần PNG.", "Butuh alpha: pilih WebP. Buka di peramban. Formulir lama mungkin masih PNG.", "Elija WebP para el alfa. Ábralo en un navegador. Los formularios viejos aún pueden pedir PNG."),
        },
        {
            "q1": L("Can I convert PNG to WebP free online?", "可以免费在线把 PNG 转成 WebP 吗？", "可以免費線上把 PNG 轉成 WebP 嗎？", "PNGをWebPに無料で変換できる？", "PNG를 WebP로 무료 변환할 수 있나요?", "Đổi PNG sang WebP miễn phí online được không?", "Bisa ubah PNG ke WebP gratis online?", "¿Puedo pasar PNG a WebP gratis en línea?"),
            "a1": L("Yes. cv.cm converts in this tab. Nothing is uploaded.", "可以。cv.cm 在当前标签页转换，不上传。", "可以。cv.cm 在目前分頁轉換，不上傳。", "できる。このタブで変換。アップロードなし。", "됩니다. 이 탭에서 변환합니다. 업로드 없음.", "Được. cv.cm đổi trong tab này, không tải lên.", "Ya. cv.cm mengubah di tab ini. Tidak diunggah.", "Sí. cv.cm convierte en esta pestaña. Nada se sube."),
            "q2": L("Will transparency survive in WebP?", "WebP 还能留透明底吗？", "WebP 還能留透明底嗎？", "WebPでも透明は残る？", "WebP에서도 투명이 남나요?", "WebP còn nền trong không?", "Transparansi tetap ada di WebP?", "¿Se conserva la transparencia en WebP?"),
            "a2": L("Yes if you export WebP. JPG will fill the background. Keep PNG if a form rejects WebP.", "导出 WebP 就还在。JPG 会填死背景。表单不认 WebP，就留 PNG。", "匯出 WebP 就還在。JPG 會填死背景。表單不認 WebP，就留 PNG。", "WebPなら残る。JPGは背景を埋める。提出がWebPを拒むならPNGを残す。", "WebP로 보내면 남습니다. JPG는 배경을 메웁니다. 서류가 WebP를 거부하면 PNG를 남기세요.", "Xuất WebP thì còn. JPG sẽ lấp nền. Form từ chối WebP thì giữ PNG.", "Ya jika ekspor WebP. JPG mengisi latar. Formulir menolak WebP: simpan PNG.", "Sí si exporta WebP. JPG rellena el fondo. Si el formulario rechaza WebP, quédese en PNG."),
            "q3": L("Are files uploaded?", "会上传吗？", "會上傳嗎？", "アップロードされる？", "업로드되나요?", "Có tải lên không?", "Apakah diunggah?", "¿Se suben los archivos?"),
            "a3": L("No. Closing the tab discards them.", "不会。关掉标签页就没了。", "不會。關掉分頁就沒了。", "しない。タブを閉じると消える。", "아니요. 탭을 닫으면 사라집니다.", "Không. Đóng tab là mất.", "Tidak. Tutup tab, hilang.", "No. Al cerrar la pestaña se pierden."),
            "q4": L("WebP or JPG for a smaller photo?", "要更小的照片，选 WebP 还是 JPG？", "要更小的照片，選 WebP 還是 JPG？", "小さくするならWebPとJPGどちら？", "더 작은 사진이면 WebP와 JPG 중?", "Muốn ảnh nhẹ thì WebP hay JPG?", "Foto lebih kecil: WebP atau JPG?", "¿WebP o JPG para menos peso?"),
            "a4": L("WebP if you need transparency or a web page. JPG if email or a form that rejects WebP.", "要透明或上网页，用 WebP。邮件或不认 WebP 的表单，用 JPG。", "要透明或上網頁，用 WebP。郵件或不認 WebP 的表單，用 JPG。", "透明やウェブならWebP。メールやWebP拒否の提出ならJPG。", "투명이 필요하거나 웹이면 WebP. 이메일이나 WebP를 거부하는 서류면 JPG.", "Cần nền trong hoặc lên web thì WebP. Email hoặc form từ chối WebP thì JPG.", "Transparansi atau web: WebP. Email atau formulir yang menolak WebP: JPG.", "WebP si necesita transparencia o una página. JPG si es correo o un formulario que rechaza WebP."),
            "q5": L("Can I convert PNG to WebP without Photoshop?", "不用 Photoshop 能转吗？", "不用 Photoshop 能轉嗎？", "Photoshopなしで？", "포토샵 없이?", "Không cần Photoshop?", "Tanpa Photoshop?", "¿Sin Photoshop?"),
            "a5": L("Yes. This page is the converter. No account.", "可以。本页就是转换。不用账号。", "可以。本頁就是轉換。不用帳號。", "できる。このページが変換。アカウント不要。", "됩니다. 이 페이지가 변환기입니다. 계정 없음.", "Được. Trang này là bộ chuyển. Không tài khoản.", "Ya. Halaman ini konverternya. Tanpa akun.", "Sí. Esta página es el conversor. Sin cuenta."),
        },
    ),
    "mp3-to-wav": lesson(
        {
            "name": L("How to convert MP3 to WAV", "怎么把 MP3 转成 WAV", "怎麼把 MP3 轉成 WAV", "MP3をWAVにする", "MP3를 WAV로", "Cách đổi MP3 sang WAV", "Cara ubah MP3 ke WAV", "Cómo pasar MP3 a WAV"),
            "blurb": L("Drop the MP3, pick a sample rate if you need one, download WAV, then play the file. The original stays on disk.", "拖入 MP3，必要时选采样率，下载 WAV，再播文件。原文件还在。", "拖入 MP3，必要時選取樣率，下載 WAV，再播檔。原檔還在。", "MP3を入れ、必要ならサンプリング周波数を選び、WAVを保存して再生。元は残る。", "MP3를 넣고 필요하면 샘플레이트를 고른 뒤 WAV를 받아 파일을 재생하세요. 원본은 남습니다.", "Thả MP3, chọn tần số lấy mẫu nếu cần, tải WAV, phát file. Bản gốc còn.", "Letakkan MP3, pilih sample rate jika perlu, unduh WAV, putar file. Asli tetap.", "Suelte el MP3, elija una frecuencia si hace falta, descargue WAV y reprodúzcalo. El original se queda."),
            "title": L("How to convert MP3 to WAV", "怎么把 MP3 转成 WAV", "怎麼把 MP3 轉成 WAV", "MP3をWAVにする方法", "MP3를 WAV로 변환하는 법", "Cách đổi MP3 sang WAV", "Cara ubah MP3 ke WAV", "Cómo pasar MP3 a WAV"),
            "lead": L("A DAW, an editor, or a form may want WAV, not MP3. You will decode a copy in this tab, pick 44.1 or 48 kHz if you need a target, and play the download.", "DAW、编辑器或表单可能只要 WAV，不要 MP3。在当前标签页解码一份，必要时选 44.1 或 48 kHz，再把下载播一遍。", "DAW、編輯器或表單可能只要 WAV，不要 MP3。在目前分頁解碼一份，必要時選 44.1 或 48 kHz，再把下載播一遍。", "DAWや提出はWAVを欲し、MP3を拒むことがある。このタブでコピーをデコードし、必要なら44.1または48kHzを選び、保存ファイルを再生。", "DAW, 편집기, 서류가 MP3가 아니라 WAV를 원할 수 있습니다. 이 탭에서 복사본을 푼 뒤 필요하면 44.1 또는 48kHz를 고르고 받은 파일을 재생하세요.", "DAW, editor hoặc form có thể cần WAV, không phải MP3. Giải một bản trong tab này, chọn 44.1 hoặc 48 kHz nếu cần, rồi phát file tải.", "DAW, editor, atau formulir mungkin minta WAV, bukan MP3. Decode salinan di tab ini, pilih 44.1 atau 48 kHz jika perlu, putar unduhan.", "Un DAW, un editor o un formulario puede pedir WAV, no MP3. Decodifique una copia aquí, elija 44.1 o 48 kHz si hace falta, y reproduzca la descarga."),
            "result": L("A WAV that plays, at the sample rate you chose, with the original MP3 still on disk.", "一份能播的 WAV，采样率是你选的，原来的 MP3 还在。", "一份能播的 WAV，取樣率是你選的，原來的 MP3 還在。", "選んだ周波数の、再生できるWAV。元のMP3は残る。", "고른 샘플레이트의, 재생되는 WAV. 원래 MP3는 남습니다.", "WAV phát được, đúng tần số bạn chọn, MP3 gốc còn.", "WAV yang bisa diputar, di sample rate yang Anda pilih, MP3 asli tetap ada.", "Un WAV que suena, a la frecuencia que eligió, con el MP3 original en el disco."),
            "note": L("Open MP3 to WAV when the audio is on disk. The download is WAV even if you dropped M4A. Listen before you send. Nothing is uploaded.", "音频在磁盘上再打开 MP3 转 WAV。即使拖进来是 M4A，下载也是 WAV。发出去之前先听。不上传。", "音訊在磁碟上再打開 MP3 轉 WAV。即使拖進來是 M4A，下載也是 WAV。寄出去之前先聽。不上傳。", "音声が手元にあってから開く。元がM4Aでも保存はWAV。送る前に聴く。アップロードなし。", "오디오가 디스크에 있으면 MP3→WAV를 여세요. M4A를 넣어도 받은 파일은 WAV. 보내기 전에 들으세요. 업로드 없음.", "Có audio trên đĩa thì mở MP3 sang WAV. Dù thả M4A, tải về vẫn WAV. Nghe trước khi gửi. Không tải lên.", "Audio di disk, baru buka MP3 ke WAV. Meski taruh M4A, unduhan WAV. Dengar sebelum kirim. Tidak diunggah.", "Abra MP3 a WAV con el audio en el disco. Aunque suelte M4A, la descarga es WAV. Escuche antes de enviar. Nada se sube."),
            "s1t": L("Know why you need WAV", "先知道为什么要 WAV", "先知道為什麼要 WAV", "なぜWAVか決める", "왜 WAV인지 정하기", "Biết vì sao cần WAV", "Tahu kenapa perlu WAV", "Sepa por qué necesita WAV"),
            "s1b": L("WAV is uncompressed PCM. Editors and some upload forms want it. It will be much larger than the MP3. Do not convert just to 'improve quality' — you cannot get back what MP3 already threw away.", "WAV 是未压缩的 PCM。编辑器和有的上传表单要它。体积会比 MP3 大很多。不要指望这一步能让音质变好——MP3 丢掉的回不来。", "WAV 是未壓縮的 PCM。編輯器和有的上傳表單要它。體積會比 MP3 大很多。不要指望這一步能讓音質變好——MP3 丟掉的回不來。", "WAVは非圧縮PCM。編集ソフトや提出が欲しがる。MP3よりずっと大きい。「音質を上げる」ためではない。MP3が捨てたものは戻らない。", "WAV는 비압축 PCM입니다. 편집기와 일부 업로드 서류가 원합니다. MP3보다 훨씬 큽니다. 음질을 '올리려고' 바꾸지 마세요. MP3가 버린 것은 돌아오지 않습니다.", "WAV là PCM không nén. Editor và một số form upload cần nó. Sẽ nặng hơn MP3 nhiều. Đừng đổi để 'cải thiện chất lượng' — MP3 đã bỏ thì không lấy lại.", "WAV adalah PCM tanpa kompresi. Editor dan beberapa formulir menginginkannya. Jauh lebih besar dari MP3. Jangan ubah untuk 'menaikkan kualitas' — yang dibuang MP3 tidak kembali.", "WAV es PCM sin comprimir. Editores y algunos formularios lo piden. Pesará mucho más que el MP3. No convierta para 'mejorar calidad': lo que el MP3 tiró no vuelve."),
            "s2t": L("Open MP3 to WAV on cv.cm", "打开 cv.cm 的 MP3 转 WAV", "打開 cv.cm 的 MP3 轉 WAV", "cv.cmのMP3→WAVを開く", "cv.cm MP3→WAV를 열기", "Mở MP3 sang WAV trên cv.cm", "Buka MP3 ke WAV di cv.cm", "Abra MP3 a WAV en cv.cm"),
            "s2b": L("Work stays in this tab.", "转换留在当前标签页。", "轉換留在目前分頁。", "このタブで処理。", "이 탭에서 변환합니다.", "Xử lý trong tab này.", "Proses di tab ini.", "El trabajo queda en esta pestaña."),
            "s3t": L("Drop the MP3, M4A, or WAV", "拖入 MP3、M4A 或 WAV", "拖入 MP3、M4A 或 WAV", "MP3 / M4A / WAVをドロップ", "MP3, M4A 또는 WAV 넣기", "Thả MP3, M4A hoặc WAV", "Letakkan MP3, M4A, atau WAV", "Suelte MP3, M4A o WAV"),
            "s3b": L("If nothing plays, this browser cannot decode that codec. Try WAV or another browser. Safari and Chrome usually handle MP3.", "播不了，就是这款浏览器解不了。换 WAV 或换浏览器。Safari 和 Chrome 一般能解 MP3。", "播不了，就是這款瀏覽器解不了。換 WAV 或換瀏覽器。Safari 和 Chrome 一般能解 MP3。", "再生できないならこのブラウザは不可。WAVか別ブラウザ。SafariとChromeはだいたいMP3可。", "재생이 안 되면 이 브라우저가 못 풉니다. WAV나 다른 브라우저. Safari와 Chrome은 보통 MP3를 엽니다.", "Không phát được thì trình duyệt không giải được. Thử WAV hoặc trình duyệt khác. Safari và Chrome thường đọc được MP3.", "Tidak diputar: peramban ini gagal. Coba WAV atau peramban lain. Safari dan Chrome biasanya bisa MP3.", "Si no suena, este navegador no lo decodifica. Pruebe WAV u otro navegador. Safari y Chrome suelen abrir MP3."),
            "s4t": L("Pick original, 44.1 kHz, or 48 kHz", "选原始、44.1 kHz 或 48 kHz", "選原始、44.1 kHz 或 48 kHz", "元のまま、44.1kHz、48kHz", "원본, 44.1kHz 또는 48kHz", "Chọn gốc, 44.1 kHz hoặc 48 kHz", "Pilih asli, 44.1 kHz, atau 48 kHz", "Elija original, 44.1 kHz o 48 kHz"),
            "s4b": L("Leave original if you are unsure. 44.1 is the CD / music default. 48 is the video default. Resampling does not add highs.", "不确定就留原始。44.1 是 CD / 音乐默认。48 是视频默认。重采样不会凭空变亮。", "不確定就留原始。44.1 是 CD / 音樂預設。48 是影片預設。重取樣不會憑空變亮。", "不明なら元のまま。44.1はCD/音楽。48は映像。リサンプルしても高域は増えない。", "모르면 원본을 두세요. 44.1은 CD/음악 기본. 48은 영상 기본. 리샘플한다고 고음이 생기지 않습니다.", "Không chắc thì để gốc. 44.1 là mặc định CD/nhạc. 48 là mặc định video. Đổi tần số không thêm treble.", "Ragu: biarkan asli. 44.1 default CD/musik. 48 default video. Resample tidak menambah treble.", "Si no está seguro, deje original. 44.1 es el default de CD/música. 48, el de vídeo. Remuestrear no añade agudos."),
            "s5t": L("Download WAV", "下载 WAV", "下載 WAV", "WAVを保存", "WAV 받기", "Tải WAV", "Unduh WAV", "Descargue WAV"),
            "s5b": L("Keep the MP3 until you have played the WAV.", "播过 WAV 之前留着 MP3。", "播過 WAV 之前留著 MP3。", "WAVを再生するまでMP3を残す。", "WAV를 재생할 때까지 MP3를 남기세요.", "Giữ MP3 đến khi đã phát WAV.", "Simpan MP3 sampai WAV diputar.", "Conserve el MP3 hasta haber reproducido el WAV."),
            "s6t": L("Play the downloaded file once", "把下载的文件播一遍", "把下載的檔播一遍", "保存したファイルを一度再生", "받은 파일을 한 번 재생", "Phát file đã tải một lần", "Putar file unduhan sekali", "Reproduzca el archivo descargado una vez"),
            "s6b": L("Do not send on the in-page player alone. If it is silent, the codec failed. If a form still wants MP3, send the original.", "不要只信页面里的播放器。没声音，就是解码失败。表单其实要 MP3，就发原文件。", "不要只信頁面裡的播放器。沒聲音，就是解碼失敗。表單其實要 MP3，就傳原檔。", "ページ内プレーヤーだけで送らない。無音ならデコード失敗。提出がMP3なら元を送る。", "페이지 플레이어만 믿고 보내지 마세요. 무음이면 디코드 실패. 서류가 MP3를 원하면 원본을 보내세요.", "Đừng gửi chỉ vì nghe trong trang. Im lặng thì decode fail. Form cần MP3 thì gửi bản gốc.", "Jangan kirim hanya dari pemutar halaman. Senyap: decode gagal. Formulir minta MP3: kirim asli.", "No envíe solo por el reproductor de la página. Si no suena, falló el códec. Si el formulario pide MP3, envíe el original."),
            "diagram1": L("WAV is uncompressed. MP3 already threw data away. Converting does not restore it.", "WAV 未压缩。MP3 已经丢掉数据。转回去找不回来。", "WAV 未壓縮。MP3 已經丟掉資料。轉回去找不回來。", "WAVは非圧縮。MP3はすでに捨てている。戻しても復元しない。", "WAV는 비압축. MP3는 이미 버린 데이터가 있습니다. 바꿔도 돌아오지 않습니다.", "WAV không nén. MP3 đã bỏ dữ liệu. Đổi lại không lấy được.", "WAV tanpa kompresi. MP3 sudah membuang data. Konversi tidak mengembalikan.", "WAV no está comprimido. El MP3 ya tiró datos. Convertir no los restaura."),
            "diagram2": L("44.1 kHz for music. 48 kHz for video. Play the downloaded WAV.", "音乐用 44.1 kHz。视频用 48 kHz。播下载的 WAV。", "音樂用 44.1 kHz。影片用 48 kHz。播下載的 WAV。", "音楽は44.1kHz。映像は48kHz。保存したWAVを再生。", "음악은 44.1kHz. 영상은 48kHz. 받은 WAV를 재생하세요.", "Nhạc 44.1 kHz. Video 48 kHz. Phát WAV đã tải.", "Musik 44.1 kHz. Video 48 kHz. Putar WAV unduhan.", "44.1 kHz para música. 48 kHz para vídeo. Reproduzca el WAV descargado."),
        },
        {
            "q1": L("Can I convert MP3 to WAV free online?", "可以免费在线把 MP3 转成 WAV 吗？", "可以免費線上把 MP3 轉成 WAV 嗎？", "MP3をWAVに無料で変換できる？", "MP3를 WAV로 무료 변환할 수 있나요?", "Đổi MP3 sang WAV miễn phí online được không?", "Bisa ubah MP3 ke WAV gratis online?", "¿Puedo pasar MP3 a WAV gratis en línea?"),
            "a1": L("Yes. cv.cm decodes in this tab and downloads WAV. Nothing is uploaded.", "可以。cv.cm 在当前标签页解码，下载 WAV。不上传。", "可以。cv.cm 在目前分頁解碼，下載 WAV。不上傳。", "できる。このタブでデコードしWAVを保存。アップロードなし。", "됩니다. 이 탭에서 풀고 WAV를 받습니다. 업로드 없음.", "Được. cv.cm giải trong tab này, tải WAV. Không tải lên.", "Ya. cv.cm men-decode di tab ini dan mengunduh WAV. Tidak diunggah.", "Sí. cv.cm decodifica en esta pestaña y descarga WAV. Nada se sube."),
            "q2": L("Will converting MP3 to WAV improve quality?", "转成 WAV 音质会变好吗？", "轉成 WAV 音質會變好嗎？", "WAVにすると音質は上がる？", "WAV로 바꾸면 음질이 좋아지나요?", "Đổi WAV có nghe hay hơn không?", "MP3 ke WAV menaikkan kualitas?", "¿Mejora la calidad pasar MP3 a WAV?"),
            "a2": L("No. WAV only stores what is left after MP3 compression. The file gets larger.", "不会。WAV 只是把 MP3 压缩后剩下的存下来。文件会变大。", "不會。WAV 只是把 MP3 壓縮後剩下的存下來。檔會變大。", "上がらない。WAVはMP3圧縮の残りを入れるだけ。ファイルは大きくなる。", "아니요. WAV는 MP3 압축 뒤에 남은 것만 담습니다. 파일은 커집니다.", "Không. WAV chỉ lưu những gì MP3 còn lại. File nặng hơn.", "Tidak. WAV hanya menyimpan sisa kompresi MP3. File membesar.", "No. WAV solo guarda lo que quedó tras el MP3. El archivo crece."),
            "q3": L("44.1 or 48 kHz?", "选 44.1 还是 48 kHz？", "選 44.1 還是 48 kHz？", "44.1と48kHzどちら？", "44.1과 48kHz 중?", "44.1 hay 48 kHz?", "44.1 atau 48 kHz?", "¿44.1 o 48 kHz?"),
            "a3": L("44.1 for music and CD-style work. 48 for video. Leave original if you are unsure.", "音乐和 CD 用 44.1。视频用 48。不确定就留原始。", "音樂和 CD 用 44.1。影片用 48。不確定就留原始。", "音楽・CDは44.1。映像は48。不明なら元のまま。", "음악·CD는 44.1. 영상은 48. 모르면 원본.", "Nhạc/CD: 44.1. Video: 48. Không chắc thì để gốc.", "Musik/CD: 44.1. Video: 48. Ragu: asli.", "44.1 para música y CD. 48 para vídeo. Si no está seguro, deje original."),
            "q4": L("Is the audio uploaded?", "会上传吗？", "會上傳嗎？", "アップロードされる？", "업로드되나요?", "Có tải lên không?", "Apakah diunggah?", "¿Se sube el audio?"),
            "a4": L("No. Closing the tab discards it.", "不会。关掉标签页就没了。", "不會。關掉分頁就沒了。", "しない。タブを閉じると消える。", "아니요. 탭을 닫으면 사라집니다.", "Không. Đóng tab là mất.", "Tidak. Tutup tab, hilang.", "No. Al cerrar la pestaña se pierde."),
            "q5": L("Can I convert M4A or voice memos?", "能转 M4A 或语音备忘录吗？", "能轉 M4A 或語音備忘錄嗎？", "M4Aやボイスメモは？", "M4A나 음성 메모는?", "Đổi M4A hoặc ghi âm?", "Ubah M4A atau memo suara?", "¿Puedo convertir M4A o notas de voz?"),
            "a5": L("If the browser can decode the file, yes. Output is still WAV.", "浏览器解得开就可以。导出仍是 WAV。", "瀏覽器解得開就可以。匯出仍是 WAV。", "ブラウザがデコードできれば可。書き出しはWAV。", "브라우저가 풀 수 있으면 됩니다. 보낸 파일은 WAV입니다.", "Trình duyệt giải được thì được. Xuất vẫn WAV.", "Jika peramban bisa decode, ya. Ekspor tetap WAV.", "Si el navegador lo decodifica, sí. La salida sigue siendo WAV."),
        },
    ),
    "join-audio": lesson(
        {
            "name": L("How to join audio files / merge MP3s", "怎么拼接音频 / 合并 MP3", "怎麼拼接音訊 / 合併 MP3", "音声をつなぐ / MP3を結合", "오디오 이어붙이기 / MP3 합치기", "Cách ghép audio / gộp MP3", "Cara gabung audio / gabung MP3", "Cómo unir archivos de audio / fusionar MP3"),
            "blurb": L("Drop two or more clips in order, download one WAV, then play the file from start to end.", "按顺序放入两段或更多，下载一份 WAV，从头到尾播一遍。", "按順序放入兩段或更多，下載一份 WAV，從頭到尾播一遍。", "2本以上を順に入れ、1つのWAVを保存し、最初から最後まで再生。", "두 개 이상을 순서대로 넣고 WAV 하나를 받은 뒤 처음부터 끝까지 재생하세요.", "Thả hai đoạn trở lên theo thứ tự, tải một WAV, phát từ đầu đến cuối.", "Letakkan dua klip atau lebih berurutan, unduh satu WAV, putar dari awal sampai akhir.", "Suelte dos o más clips en orden, descargue un WAV y reprodúzcalo de principio a fin."),
            "title": L("How to join audio files / merge MP3s", "怎么拼接音频 / 合并 MP3", "怎麼拼接音訊 / 合併 MP3", "音声をつなぐ / MP3を結合する方法", "오디오 이어붙이기 / MP3 합치는 법", "Cách ghép audio / gộp MP3", "Cara gabung audio / gabung MP3", "Cómo unir archivos de audio / fusionar MP3"),
            "lead": L("You need one file, not a playlist: intro then song, two voice notes, a bed under a voicemail. List order is playback order. Export is WAV.", "你要的是一份文件，不是播放列表：前奏再接歌、两段语音、垫乐加留言。列表顺序就是播放顺序。导出是 WAV。", "你要的是一份檔，不是播放列表：前奏再接歌、兩段語音、墊樂加留言。列表順序就是播放順序。匯出是 WAV。", "欲しいのは1ファイル。イントロのあと曲、2本のボイス、BGMの上に留守電。リスト順が再生順。書き出しはWAV。", "재생목록이 아니라 파일 하나가 필요합니다. 인트로 다음 곡, 음성 두 개, 깔린 음악 위 음성. 목록 순서가 재생 순서. 보낸 파일은 WAV.", "Bạn cần một file, không phải playlist: intro rồi bài, hai voice, nền dưới voicemail. Thứ tự list là thứ tự phát. Xuất WAV.", "Anda butuh satu file, bukan playlist: intro lalu lagu, dua memo, bed di bawah voicemail. Urutan daftar = urutan putar. Ekspor WAV.", "Necesita un archivo, no una lista: intro y luego la canción, dos notas de voz. El orden de la lista es el de reproducción. La exportación es WAV."),
            "result": L("One WAV that plays the clips in the order you set, verified from start to end, with the originals still on disk.", "一份 WAV：按你排的顺序播完，从头到尾核对过，原文件还在。", "一份 WAV：按你排的順序播完，從頭到尾核對過，原檔還在。", "並べた順で全部鳴る1つのWAV。最初から最後まで確認。元は残る。", "정한 순서로 모두 재생되는 WAV 하나. 처음부터 끝까지 확인. 원본은 남습니다.", "Một WAV phát các đoạn đúng thứ tự bạn xếp, đã nghe hết, bản gốc còn.", "Satu WAV yang memutar klip sesuai urutan, sudah dicek awal sampai akhir, asli tetap ada.", "Un WAV que reproduce los clips en el orden que fijó, comprobado de punta a punta, con los originales en el disco."),
            "note": L("Open join when the clips are on disk. You need two or more. Later clips are resampled to the first clip's rate. Download is WAV. Nothing is uploaded.", "音频在磁盘上再打开拼接。至少两段。后面的会重采样到第一段的采样率。下载是 WAV。不上传。", "音訊在磁碟上再打開拼接。至少兩段。後面的會重取樣到第一段的取樣率。下載是 WAV。不上傳。", "クリップが手元にあってから結合を開く。2本以上。後続は先頭の周波数にリサンプル。保存はWAV。アップロードなし。", "클립이 디스크에 있으면 이어붙이기를 여세요. 두 개 이상. 뒤 클립은 첫 클립의 레이트로 리샘플됩니다. 받은 파일은 WAV. 업로드 없음.", "Có clip trên đĩa thì mở ghép. Cần từ hai đoạn. Đoạn sau resample theo tần số đoạn đầu. Tải về WAV. Không tải lên.", "Klip di disk, baru buka gabung. Minimal dua. Klip berikutnya di-resample ke rate klip pertama. Unduhan WAV. Tidak diunggah.", "Abra unir con los clips en el disco. Hacen falta dos o más. Los siguientes se remuestrean a la frecuencia del primero. La descarga es WAV. Nada se sube."),
            "s1t": L("Put the clips in playback order", "先按播放顺序排好", "先按播放順序排好", "再生順に並べる", "재생 순서로 맞추기", "Xếp clip theo thứ tự phát", "Urutkan klip sesuai putar", "Ponga los clips en orden de reproducción"),
            "s1b": L("Intro first, bed last. Rename if it helps. You will still be able to move rows after you drop them.", "前奏在前，垫乐在后。改名也行。拖进去以后还能上下移动。", "前奏在前，墊樂在後。改名也行。拖進去以後還能上下移動。", "イントロが先、BGMが後。リネームしてもよい。ドロップ後も上下できる。", "인트로가 먼저, 깔린 음악이 나중. 이름 바꿔도 됩니다. 넣은 뒤에도 위아래로 옮길 수 있습니다.", "Intro trước, nền sau. Đổi tên cũng được. Thả xong vẫn kéo lên xuống.", "Intro dulu, bed terakhir. Ganti nama boleh. Setelah diletakkan masih bisa geser.", "Intro primero, cama al final. Renombre si ayuda. Después de soltar aún puede mover filas."),
            "s2t": L("Open audio joiner on cv.cm", "打开 cv.cm 的音频拼接", "打開 cv.cm 的音訊拼接", "cv.cmの音声結合を開く", "cv.cm 오디오 이어붙이기를 열기", "Mở ghép audio trên cv.cm", "Buka gabung audio di cv.cm", "Abra unir audio en cv.cm"),
            "s2b": L("Work stays in this tab.", "拼接留在当前标签页。", "拼接留在目前分頁。", "このタブでつなぐ。", "이 탭에서 이어붙입니다.", "Ghép trong tab này.", "Gabung di tab ini.", "La unión queda en esta pestaña."),
            "s3t": L("Drop two or more files", "拖入两段或更多", "拖入兩段或更多", "2本以上をドロップ", "두 개 이상 넣기", "Thả từ hai file", "Letakkan dua file atau lebih", "Suelte dos o más archivos"),
            "s3b": L("One file is not a join. If a row shows an error, that codec failed — convert that clip to WAV first, or skip it.", "一段算不上拼接。某一行报错，就是解码失败——先转成 WAV，或先跳过。", "一段算不上拼接。某一行報錯，就是解碼失敗——先轉成 WAV，或先跳過。", "1本では結合にならない。行がエラーならデコード失敗。先にWAVにするか外す。", "하나로는 이어붙일 수 없습니다. 한 줄이 오류면 디코드 실패. 먼저 WAV로 바꾸거나 빼세요.", "Một file không phải ghép. Hàng báo lỗi thì codec fail — đổi WAV trước, hoặc bỏ.", "Satu file bukan gabungan. Baris error: decode gagal. Ubah ke WAV dulu, atau lewati.", "Un solo archivo no es una unión. Si una fila falla, ese códec no vale: páselo a WAV o sáltelo."),
            "s4t": L("Reorder if the list is wrong", "顺序不对就上下移动", "順序不對就上下移動", "順が違うなら並べ替える", "순서가 틀리면 위아래로", "Sai thứ tự thì sắp lại", "Urutan salah: geser", "Si el orden falla, reordene"),
            "s4b": L("The first row plays first. Later clips are resampled to the first clip's sample rate so the join does not drift.", "第一行先播。后面的会重采样到第一段的采样率，免得越接越飘。", "第一行先播。後面的會重取樣到第一段的取樣率，免得越接越飄。", "先頭が最初に鳴る。後続は先頭の周波数に合わせるので、つなぎがずれない。", "첫 줄이 먼저 재생됩니다. 뒤 클립은 첫 클립의 레이트로 맞춰 이어붙일 때 밀리지 않습니다.", "Hàng đầu phát trước. Đoạn sau resample theo tần số đoạn đầu, khỏi lệch.", "Baris pertama diputar dulu. Klip berikutnya di-resample ke rate klip pertama agar sambungan tidak geser.", "La primera fila suena primero. Los siguientes se remuestrean a la frecuencia del primero para que no deriven."),
            "s5t": L("Download one WAV", "下载一份 WAV", "下載一份 WAV", "WAVを1つ保存", "WAV 하나 받기", "Tải một WAV", "Unduh satu WAV", "Descargue un WAV"),
            "s5b": L("Export is WAV even if every source was MP3. Keep the originals until you have listened through.", "即使全是 MP3，导出也是 WAV。听完之前留着原文件。", "即使全是 MP3，匯出也是 WAV。聽完之前留著原檔。", "全部MP3でも書き出しはWAV。通しで聴くまで原版を残す。", "모두 MP3여도 보낸 파일은 WAV. 끝까지 듣기 전에 원본을 남기세요.", "Dù toàn MP3, xuất vẫn WAV. Giữ gốc đến khi đã nghe hết.", "Meski semua MP3, ekspor WAV. Simpan asli sampai selesai didengar.", "Aunque todas sean MP3, la exportación es WAV. Conserve los originales hasta haber escuchado entero."),
            "s6t": L("Play the file from start to end", "从头到尾播这份文件", "從頭到尾播這份檔", "ファイルを最初から最後まで再生", "파일을 처음부터 끝까지 재생", "Phát file từ đầu đến cuối", "Putar file dari awal sampai akhir", "Reproduzca el archivo de principio a fin"),
            "s6b": L("Listen for a missing clip, a gap, or a pitch change at a join. If the order is wrong, move rows and export again. Do not send on the in-page list alone.", "听有没有缺一段、中间空一截、接头变调。顺序错了，排好再导。不要只信页面上的列表。", "聽有沒有缺一段、中間空一截、接頭變調。順序錯了，排好再導。不要只信頁面上的列表。", "欠け、無音、つなぎのピッチを聴く。順が違うなら並べ直して再書き出し。リスト見ただけで送らない。", "빠진 클립, 공백, 이음부의 음높이를 들으세요. 순서가 틀리면 다시 맞춰 보내세요. 페이지 목록만 보고 보내지 마세요.", "Nghe đoạn thiếu, khoảng trống, hoặc lệch cao độ ở chỗ ghép. Sai thứ tự thì sắp lại rồi xuất. Đừng gửi chỉ vì nhìn list.", "Dengar klip hilang, jeda, atau pitch berubah di sambungan. Urutan salah: urutkan, ekspor lagi. Jangan kirim hanya dari daftar halaman.", "Escuche un clip faltante, un hueco o un cambio de tono en el empalme. Si el orden falla, reordene y exporte. No envíe solo por la lista."),
            "diagram1": L("List order is playback order. You need two or more clips.", "列表顺序就是播放顺序。至少两段。", "列表順序就是播放順序。至少兩段。", "リスト順が再生順。2本以上。", "목록 순서가 재생 순서. 두 개 이상.", "Thứ tự list là thứ tự phát. Cần từ hai đoạn.", "Urutan daftar = urutan putar. Minimal dua klip.", "El orden de la lista es el de reproducción. Hacen falta dos o más."),
            "diagram2": L("Export is one WAV. Later clips match the first clip's sample rate.", "导出是一份 WAV。后面的对齐第一段的采样率。", "匯出是一份 WAV。後面的對齊第一段的取樣率。", "書き出しはWAV1つ。後続は先頭の周波数に合わせる。", "보낸 파일은 WAV 하나. 뒤 클립은 첫 클립의 레이트에 맞춥니다.", "Xuất một WAV. Đoạn sau khớp tần số đoạn đầu.", "Ekspor satu WAV. Klip berikutnya mengikuti rate klip pertama.", "La exportación es un WAV. Los siguientes coinciden con la frecuencia del primero."),
        },
        {
            "q1": L("Can I merge MP3 files free online?", "可以免费在线合并 MP3 吗？", "可以免費線上合併 MP3 嗎？", "MP3を無料で結合できる？", "MP3를 무료로 합칠 수 있나요?", "Gộp MP3 miễn phí online được không?", "Bisa gabung MP3 gratis online?", "¿Puedo fusionar MP3 gratis en línea?"),
            "a1": L("Yes. Drop two or more on cv.cm audio joiner in this tab, reorder, download WAV. Nothing is uploaded.", "可以。在当前标签页拖入两段或更多，排好顺序，下载 WAV。不上传。", "可以。在目前分頁拖入兩段或更多，排好順序，下載 WAV。不上傳。", "できる。このタブに2本以上入れ、並べてWAVを保存。アップロードなし。", "됩니다. 이 탭에 두 개 이상을 넣고 순서를 맞춘 뒤 WAV를 받으세요. 업로드 없음.", "Được. Thả từ hai đoạn vào ghép audio cv.cm trong tab này, sắp, tải WAV. Không tải lên.", "Ya. Letakkan dua atau lebih di gabung audio cv.cm di tab ini, urutkan, unduh WAV. Tidak diunggah.", "Sí. Suelte dos o más en unir audio de cv.cm, reordene y descargue WAV. Nada se sube."),
            "q2": L("Why is the download WAV, not MP3?", "为什么下载是 WAV 不是 MP3？", "為什麼下載是 WAV 不是 MP3？", "保存がWAVなのはなぜ？", "받은 파일이 WAV인 이유는?", "Sao tải về là WAV không phải MP3?", "Kenapa unduhan WAV, bukan MP3?", "¿Por qué la descarga es WAV y no MP3?"),
            "a2": L("The joiner concatenates decoded PCM and writes WAV in the browser. If you need MP3, convert the WAV afterwards.", "拼接在浏览器里把解码后的 PCM 接起来写成 WAV。还要 MP3，就再转一次。", "拼接在瀏覽器裡把解碼後的 PCM 接起來寫成 WAV。還要 MP3，就再轉一次。", "デコードしたPCMをつないでブラウザでWAVにする。MP3が要るなら後で変換。", "이어붙이기가 디코드된 PCM을 연결해 브라우저에서 WAV로 씁니다. MP3가 필요하면 나중에 변환하세요.", "Công cụ nối PCM đã giải rồi ghi WAV trong trình duyệt. Cần MP3 thì đổi sau.", "Penggabung menyambung PCM ter-decode dan menulis WAV di peramban. Butuh MP3: konversi nanti.", "El unidor concatena PCM decodificado y escribe WAV en el navegador. Si necesita MP3, conviértalo después."),
            "q3": L("Do I need two files?", "一定要两段吗？", "一定要兩段嗎？", "2本必要？", "두 개가 필요한가요?", "Bắt buộc hai file?", "Harus dua file?", "¿Hacen falta dos archivos?"),
            "a3": L("Yes. One clip is not a join. Add a second file or go to trim if you only need a slice.", "对。一段算不上拼接。只要切一段，去裁剪。", "對。一段算不上拼接。只要切一段，去裁剪。", "そう。1本は結合ではない。切り出しだけならトリムへ。", "네. 하나로는 이어붙일 수 없습니다. 한 조각만 필요하면 자르기로 가세요.", "Phải. Một đoạn không phải ghép. Chỉ cần cắt thì sang cắt audio.", "Ya. Satu klip bukan gabungan. Hanya butuh potongan: ke potong audio.", "Sí. Un clip no es una unión. Si solo necesita un recorte, vaya a recortar."),
            "q4": L("Is the audio uploaded?", "会上传吗？", "會上傳嗎？", "アップロードされる？", "업로드되나요?", "Có tải lên không?", "Apakah diunggah?", "¿Se sube el audio?"),
            "a4": L("No. Closing the tab discards it.", "不会。关掉标签页就没了。", "不會。關掉分頁就沒了。", "しない。タブを閉じると消える。", "아니요. 탭을 닫으면 사라집니다.", "Không. Đóng tab là mất.", "Tidak. Tutup tab, hilang.", "No. Al cerrar la pestaña se pierde."),
            "q5": L("Will this change the original files?", "会改原文件吗？", "會改原檔嗎？", "元ファイルは変わる？", "원본이 바뀌나요?", "Có sửa file gốc không?", "Apakah file asli berubah?", "¿Cambia los archivos originales?"),
            "a5": L("No. You download a new WAV. The MP3s on disk stay.", "不会。你下载的是新 WAV。磁盘上的 MP3 还在。", "不會。你下載的是新 WAV。磁碟上的 MP3 還在。", "しない。新しいWAVを保存。元のMP3は残る。", "아니요. 새 WAV를 받습니다. 디스크의 MP3는 그대로입니다.", "Không. Bạn tải WAV mới. MP3 trên đĩa còn.", "Tidak. Anda mengunduh WAV baru. MP3 di disk tetap.", "No. Descarga un WAV nuevo. Los MP3 del disco se quedan."),
        },
    ),
    "make-favicon": lesson(
        {
            "name": L("How to make a favicon", "怎么做网站图标 / favicon", "怎麼做網站圖示 / favicon", "ファビコンの作り方", "파비콘 만드는 법", "Cách làm favicon", "Cara buat favicon", "Cómo hacer un favicon"),
            "blurb": L("Crop to a square, pick Cover or Contain, download ICO plus PNG sizes, then check the 16-pixel version.", "裁成正方形，选铺满还是完整放入，下载 ICO 和各尺寸 PNG，再看 16 像素那一档。", "裁成正方形，選鋪滿還是完整放入，下載 ICO 和各尺寸 PNG，再看 16 像素那一檔。", "正方形にしてCoverかContain、ICOとPNGサイズを保存し、16pxを見る。", "정사각으로 맞추고 Cover 또는 Contain을 고른 뒤 ICO와 PNG 크기를 받고 16픽셀을 보세요.", "Cắt vuông, chọn Cover hay Contain, tải ICO và các cỡ PNG, xem bản 16 pixel.", "Potong persegi, pilih Cover atau Contain, unduh ICO plus PNG, cek versi 16 piksel.", "Recorte a cuadrado, elija Cover o Contain, descargue ICO y PNG, y mire la de 16 píxeles."),
            "title": L("How to make a favicon", "怎么做网站图标 / favicon", "怎麼做網站圖示 / favicon", "ファビコンの作り方", "파비콘 만드는 법", "Cách làm favicon", "Cara buat favicon", "Cómo hacer un favicon"),
            "lead": L("A favicon has to read at 16 pixels. You will square the mark, choose Cover or Contain, and download an ICO for classic tabs plus a PNG zip for touch icons.", "网站图标要在 16 像素还能认出来。把标志裁成正方形，选铺满还是完整放入，再下载经典标签页用的 ICO，以及触摸图标用的 PNG 压缩包。", "網站圖示要在 16 像素還能認出來。把標誌裁成正方形，選鋪滿還是完整放入，再下載經典分頁用的 ICO，以及觸控圖示用的 PNG 壓縮檔。", "ファビコンは16pxで読めないとダメ。マークを正方形にし、CoverかContainを選び、タブ用ICOとタッチ用PNGのZIPを保存。", "파비콘은 16픽셀에서도 알아봐야 합니다. 마크를 정사각으로 맞추고 Cover 또는 Contain을 고른 뒤 탭용 ICO와 터치 아이콘용 PNG zip을 받으세요.", "Favicon phải đọc được ở 16 pixel. Cắt dấu thành vuông, chọn Cover hay Contain, tải ICO cho tab cổ điển và zip PNG cho icon chạm.", "Favicon harus kebaca di 16 piksel. Buat tanda jadi persegi, pilih Cover atau Contain, unduh ICO untuk tab klasik plus zip PNG untuk ikon sentuh.", "Un favicon tiene que leerse a 16 píxeles. Cuadre la marca, elija Cover o Contain y descargue un ICO para pestañas clásicas más un zip PNG para iconos táctiles."),
            "result": L("A favicon.ico (16/32/48) and a PNG zip (including 180/192/512) that still reads at tab size.", "一份 favicon.ico（16/32/48）和一份 PNG 压缩包（含 180/192/512），在标签页那么大仍能认出来。", "一份 favicon.ico（16/32/48）和一份 PNG 壓縮檔（含 180/192/512），在分頁那麼大仍能認出來。", "favicon.ico（16/32/48）とPNGのZIP（180/192/512含む）。タブサイズでも読める。", "favicon.ico(16/32/48)와 PNG zip(180/192/512 포함). 탭 크기에서도 알아봅니다.", "favicon.ico (16/32/48) và zip PNG (gồm 180/192/512) vẫn đọc được cỡ tab.", "favicon.ico (16/32/48) dan zip PNG (termasuk 180/192/512) yang masih kebaca seukuran tab.", "Un favicon.ico (16/32/48) y un zip PNG (con 180/192/512) que aún se lee al tamaño de una pestaña."),
            "note": L("Open favicon when the mark is on disk. Cover fills the square and may crop. Contain letterboxes. White background is on by default. Nothing is uploaded.", "标志在磁盘上再打开网站图标。Cover 铺满正方形，可能裁切。Contain 留边。默认白底。不上传。", "標誌在磁碟上再打開網站圖示。Cover 鋪滿正方形，可能裁切。Contain 留邊。預設白底。不上傳。", "マークが手元にあってから開く。Coverは正方形を埋め切ることがある。Containは余白。白背景が初期値。アップロードなし。", "마크가 디스크에 있으면 파비콘을 여세요. Cover는 정사각을 채우며 자를 수 있습니다. Contain은 여백. 흰 배경이 기본입니다. 업로드 없음.", "Có dấu trên đĩa thì mở favicon. Cover lấp ô vuông, có thể cắt. Contain để lề. Nền trắng bật sẵn. Không tải lên.", "Tanda di disk, baru buka favicon. Cover mengisi persegi, bisa memotong. Contain ada bar. Latar putih default. Tidak diunggah.", "Abra favicon con la marca en el disco. Cover llena el cuadrado y puede recortar. Contain deja bandas. El fondo blanco viene activado. Nada se sube."),
            "s1t": L("Start from a mark that still reads tiny", "选一个缩得很小仍能认的标志", "選一個縮得很小仍能認的標誌", "小さくても分かるマーク", "작아도 알아보는 마크", "Chọn dấu nhỏ vẫn đọc được", "Pilih tanda yang masih kebaca kecil", "Empiece por una marca que se lea minúscula"),
            "s1b": L("A busy photo dies at 16 pixels. A letter, a simple shape, or a high-contrast logo works. Crop the subject before you come here if the frame is wide.", "花的照片缩到 16 像素就没了。一个字母、简单形状或高对比 logo 才行。画面太宽，先裁到主体再过来。", "花的照片縮到 16 像素就沒了。一個字母、簡單形狀或高對比 logo 才行。畫面太寬，先裁到主體再過來。", "賑やかな写真は16pxで死ぬ。1文字、単純な形、コントラストの高いロゴ。横長なら先にクロップ。", "복잡한 사진은 16픽셀에서 죽습니다. 글자 하나, 단순한 도형, 대비 높은 로고. 프레임이 넓으면 먼저 자르고 오세요.", "Ảnh rối chết ở 16 pixel. Một chữ, hình đơn hoặc logo tương phản cao mới được. Khung rộng thì crop chủ thể trước.", "Foto ramai mati di 16 piksel. Huruf, bentuk sederhana, atau logo kontras tinggi. Frame lebar: crop subjek dulu.", "Una foto ocupada muere a 16 px. Una letra, una forma simple o un logo de alto contraste. Si el encuadre es ancho, recorte el sujeto antes."),
            "s2t": L("Open favicon on cv.cm", "打开 cv.cm 的网站图标", "打開 cv.cm 的網站圖示", "cv.cmのファビコンを開く", "cv.cm 파비콘을 열기", "Mở favicon trên cv.cm", "Buka favicon di cv.cm", "Abra favicon en cv.cm"),
            "s2b": L("Work stays in this tab.", "做图标留在当前标签页。", "做圖示留在目前分頁。", "このタブで処理。", "이 탭에서 만듭니다.", "Làm trong tab này.", "Proses di tab ini.", "El trabajo queda en esta pestaña."),
            "s3t": L("Drop the image", "拖入图片", "拖入圖片", "画像をドロップ", "이미지를 넣기", "Thả ảnh", "Letakkan gambar", "Suelte la imagen"),
            "s3b": L("If the preview is blank, convert HEIC first.", "预览空白，先把 HEIC 转成 JPG。", "預覽空白，先把 HEIC 轉成 JPG。", "プレビューが空なら先にHEICをJPGに。", "미리보기가 비면 HEIC를 JPG로 먼저 바꾸세요.", "Xem trước trống thì đổi HEIC sang JPG trước.", "Pratinjau kosong: ubah HEIC ke JPG dulu.", "Si la vista está en blanco, pase HEIC a JPG antes."),
            "s4t": L("Choose Cover or Contain, and white background", "选 Cover 还是 Contain，以及要不要白底", "選 Cover 還是 Contain，以及要不要白底", "CoverかContain、白背景の有無", "Cover 또는 Contain, 그리고 흰 배경", "Chọn Cover hay Contain, và nền trắng", "Pilih Cover atau Contain, dan latar putih", "Elija Cover o Contain, y el fondo blanco"),
            "s4b": L("Cover fills the square and may crop. Contain keeps the whole mark and letterboxes. Leave white background on for a classic tab. Uncheck it if you need a transparent PNG.", "Cover 铺满正方形，可能裁切。Contain 放下整个标志，会留边。经典标签页就留着白底。要透明 PNG 再关掉。", "Cover 鋪滿正方形，可能裁切。Contain 放下整個標誌，會留邊。經典分頁就留著白底。要透明 PNG 再關掉。", "Coverは正方形を埋め切ることがある。Containは全体（余白）。クラシックなタブは白背景のまま。透明PNGが要るなら外す。", "Cover는 정사각을 채우며 자를 수 있습니다. Contain은 전체를 넣고 여백이 생깁니다. 고전 탭은 흰 배경을 켜 두세요. 투명 PNG가 필요하면 끄세요.", "Cover lấp ô vuông, có thể cắt. Contain giữ cả dấu, có lề. Tab cổ điển để nền trắng. Cần PNG trong thì tắt.", "Cover mengisi persegi, bisa memotong. Contain menjaga seluruh tanda, ada bar. Tab klasik: biarkan latar putih. Butuh PNG tembus: matikan.", "Cover llena el cuadrado y puede recortar. Contain deja la marca entera y añade bandas. Deje el fondo blanco para una pestaña clásica. Quítelo si necesita PNG transparente."),
            "s5t": L("Download ICO and the PNG zip", "下载 ICO 和 PNG 压缩包", "下載 ICO 和 PNG 壓縮檔", "ICOとPNGのZIPを保存", "ICO와 PNG zip 받기", "Tải ICO và zip PNG", "Unduh ICO dan zip PNG", "Descargue ICO y el zip PNG"),
            "s5b": L("ICO packs 16, 32, and 48 for classic tabs. The zip also has 180, 192, and 512 for Apple touch and PWA icons. Keep the original mark.", "ICO 里是 16、32、48，给经典标签页。压缩包还有 180、192、512，给苹果触摸图标和 PWA。原标志留下。", "ICO 裡是 16、32、48，給經典分頁。壓縮檔還有 180、192、512，給蘋果觸控圖示和 PWA。原標誌留下。", "ICOは16/32/48（クラシックなタブ）。ZIPには180/192/512（AppleタッチとPWA）も入る。元のマークは残す。", "ICO는 16, 32, 48(고전 탭). zip에는 180, 192, 512(애플 터치와 PWA)도 있습니다. 원본 마크는 남깁니다.", "ICO gồm 16, 32, 48 cho tab cổ điển. Zip còn 180, 192, 512 cho Apple touch và PWA. Giữ dấu gốc.", "ICO berisi 16, 32, 48 untuk tab klasik. Zip juga 180, 192, 512 untuk Apple touch dan PWA. Simpan tanda asli.", "El ICO empaqueta 16, 32 y 48 para pestañas clásicas. El zip también tiene 180, 192 y 512 para Apple touch y PWA. Conserve la marca original."),
            "s6t": L("Open the 16-pixel PNG", "打开 16 像素的 PNG", "打開 16 像素的 PNG", "16pxのPNGを開く", "16픽셀 PNG 열기", "Mở PNG 16 pixel", "Buka PNG 16 piksel", "Abra el PNG de 16 píxeles"),
            "s6b": L("The 256 preview lies. If the 16px file is a blur, simplify the mark or switch to Contain. Put favicon.ico at the site root and link the PNGs in the HTML.", "256 的预览会骗人。16 像素糊了，就简化标志或改 Contain。把 favicon.ico 放到网站根目录，并在 HTML 里链上 PNG。", "256 的預覽會騙人。16 像素糊了，就簡化標誌或改 Contain。把 favicon.ico 放到網站根目錄，並在 HTML 裡鏈上 PNG。", "256のプレビューは嘘。16pxがボケるならマークを単純にするかContain。favicon.icoをルートに置き、HTMLでPNGをリンク。", "256 미리보기는 거짓말입니다. 16px가 흐리면 마크를 단순화하거나 Contain으로 바꾸세요. favicon.ico를 사이트 루트에 두고 HTML에서 PNG를 연결하세요.", "Xem trước 256 nói dối. File 16px mờ thì đơn giản hóa dấu hoặc đổi Contain. Đặt favicon.ico ở gốc site và link PNG trong HTML.", "Pratinjau 256 berbohong. File 16px buram: sederhanakan tanda atau ganti Contain. Taruh favicon.ico di root situs dan tautkan PNG di HTML.", "La vista de 256 miente. Si el de 16 px es un borrón, simplifique la marca o pase a Contain. Ponga favicon.ico en la raíz y enlace los PNG en el HTML."),
            "diagram1": L("Cover fills and may crop. Contain keeps the whole mark and letterboxes.", "Cover 铺满，可能裁切。Contain 放下整个标志，会留边。", "Cover 鋪滿，可能裁切。Contain 放下整個標誌，會留邊。", "Coverは埋めて切ることがある。Containは全体（余白）。", "Cover는 채우며 자를 수 있습니다. Contain은 전체를 넣고 여백이 생깁니다.", "Cover lấp ô, có thể cắt. Contain giữ cả dấu, có lề.", "Cover mengisi, bisa memotong. Contain menjaga seluruh tanda, ada bar.", "Cover llena y puede recortar. Contain deja la marca entera y añade bandas."),
            "diagram2": L("ICO is 16/32/48. PNG zip adds 180/192/512. Check the 16px file.", "ICO 是 16/32/48。PNG 压缩包还有 180/192/512。看 16 像素那份。", "ICO 是 16/32/48。PNG 壓縮檔還有 180/192/512。看 16 像素那份。", "ICOは16/32/48。PNGのZIPに180/192/512。16pxを見る。", "ICO는 16/32/48. PNG zip에 180/192/512. 16px 파일을 보세요.", "ICO là 16/32/48. Zip PNG thêm 180/192/512. Xem file 16px.", "ICO 16/32/48. Zip PNG menambah 180/192/512. Cek file 16px.", "El ICO es 16/32/48. El zip PNG añade 180/192/512. Mire el de 16 px."),
        },
        {
            "q1": L("Can I make a favicon free online?", "可以免费在线做网站图标吗？", "可以免費線上做網站圖示嗎？", "ファビコンを無料で作れる？", "파비콘을 무료로 만들 수 있나요?", "Làm favicon miễn phí online được không?", "Bisa buat favicon gratis online?", "¿Puedo hacer un favicon gratis en línea?"),
            "a1": L("Yes. cv.cm draws in this tab. Nothing is uploaded.", "可以。cv.cm 在当前标签页画，不上传。", "可以。cv.cm 在目前分頁畫，不上傳。", "できる。このタブで描く。アップロードなし。", "됩니다. 이 탭에서 그립니다. 업로드 없음.", "Được. Vẽ trong tab này, không tải lên.", "Ya. Menggambar di tab ini. Tidak diunggah.", "Sí. Se dibuja en esta pestaña. Nada se sube."),
            "q2": L("What sizes are in the ICO?", "ICO 里有哪些尺寸？", "ICO 裡有哪些尺寸？", "ICOのサイズは？", "ICO에는 어떤 크기가?", "ICO có cỡ nào?", "Ukuran apa di ICO?", "¿Qué tamaños lleva el ICO?"),
            "a2": L("16, 32, and 48 pixel PNG images packed into one favicon.ico.", "16、32、48 像素的 PNG，打进一份 favicon.ico。", "16、32、48 像素的 PNG，打進一份 favicon.ico。", "16/32/48pxのPNGを1つのfavicon.icoに入れる。", "16, 32, 48픽셀 PNG를 favicon.ico 하나에 넣습니다.", "PNG 16, 32 và 48 pixel đóng trong một favicon.ico.", "PNG 16, 32, dan 48 piksel dalam satu favicon.ico.", "PNG de 16, 32 y 48 píxeles empaquetados en un favicon.ico."),
            "q3": L("Do I need Apple touch icons too?", "还要苹果触摸图标吗？", "還要蘋果觸控圖示嗎？", "Appleタッチアイコンも要る？", "애플 터치 아이콘도 필요하나요?", "Cần thêm Apple touch icon?", "Perlu ikon Apple touch juga?", "¿También iconos Apple touch?"),
            "a3": L("The PNG zip includes 180, 192, and 512. Link those in HTML for home-screen icons.", "PNG 压缩包里有 180、192、512。在 HTML 里链上，给主屏图标用。", "PNG 壓縮檔裡有 180、192、512。在 HTML 裡鏈上，給主畫面圖示用。", "PNGのZIPに180/192/512。HTMLでリンクしてホーム画面用。", "PNG zip에 180, 192, 512가 있습니다. HTML에서 연결해 홈 화면 아이콘으로 쓰세요.", "Zip PNG có 180, 192, 512. Link trong HTML cho icon màn hình chính.", "Zip PNG berisi 180, 192, 512. Tautkan di HTML untuk ikon layar utama.", "El zip PNG incluye 180, 192 y 512. Enlácelos en el HTML para iconos de inicio."),
            "q4": L("Are photos uploaded?", "会上传吗？", "會上傳嗎？", "アップロードされる？", "업로드되나요?", "Có tải lên không?", "Apakah diunggah?", "¿Se suben las fotos?"),
            "a4": L("No. Closing the tab discards them.", "不会。关掉标签页就没了。", "不會。關掉分頁就沒了。", "しない。タブを閉じると消える。", "아니요. 탭을 닫으면 사라집니다.", "Không. Đóng tab là mất.", "Tidak. Tutup tab, hilang.", "No. Al cerrar la pestaña se pierden."),
            "q5": L("Can I keep a transparent background?", "能留透明底吗？", "能留透明底嗎？", "透明背景にできる？", "투명 배경을 남길 수 있나요?", "Giữ nền trong được không?", "Bisa jaga latar tembus?", "¿Puedo dejar el fondo transparente?"),
            "a5": L("Yes. Uncheck white background. Contain then letterboxes on transparency.", "可以。关掉白底。Contain 会在透明底上留边。", "可以。關掉白底。Contain 會在透明底上留邊。", "できる。白背景を外す。Containなら透明の余白。", "됩니다. 흰 배경을 끄세요. Contain이면 투명 위에 여백이 생깁니다.", "Được. Tắt nền trắng. Contain sẽ để lề trên nền trong.", "Ya. Matikan latar putih. Contain lalu membuat bar di atas transparansi.", "Sí. Quite el fondo blanco. Contain entonces deja bandas sobre transparencia."),
        },
    ),
}

META = {
    "titlePngToWebp": L("How to convert PNG to WebP | cv.cm", "怎么把 PNG 转成 WebP | cv.cm", "怎麼把 PNG 轉成 WebP | cv.cm", "PNGをWebPにする方法 | cv.cm", "PNG를 WebP로 변환하는 법 | cv.cm", "Cách đổi PNG sang WebP | cv.cm", "Cara ubah PNG ke WebP | cv.cm", "Cómo pasar PNG a WebP | cv.cm"),
    "descPngToWebp": L("Pick WebP for a smaller file that can keep a clear background. Open it in a current browser. Old forms may still want PNG. Nothing is uploaded.", "要更小还能留透明底，就选 WebP。用现在的浏览器打开。老表单可能仍要 PNG。不上传。", "要更小還能留透明底，就選 WebP。用現在的瀏覽器打開。老表單可能仍要 PNG。不上傳。", "小さくて透明も残すならWebP。今のブラウザで開く。古い提出はまだPNG。アップロードなし。", "더 작으면서 투명을 남기려면 WebP. 최신 브라우저에서 여세요. 옛 서류는 아직 PNG일 수 있습니다. 업로드 없음.", "Muốn nhẹ mà còn nền trong thì chọn WebP. Mở bằng trình duyệt mới. Form cũ vẫn có thể cần PNG. Không tải lên.", "Lebih kecil dan bisa jaga latar tembus: pilih WebP. Buka di peramban baru. Formulir lama mungkin masih PNG. Tidak diunggah.", "Elija WebP para menos peso y fondo transparente. Ábralo en un navegador actual. Los formularios viejos aún pueden pedir PNG. Nada se sube."),
    "titleMp3ToWav": L("How to convert MP3 to WAV | cv.cm", "怎么把 MP3 转成 WAV | cv.cm", "怎麼把 MP3 轉成 WAV | cv.cm", "MP3をWAVにする方法 | cv.cm", "MP3를 WAV로 변환하는 법 | cv.cm", "Cách đổi MP3 sang WAV | cv.cm", "Cara ubah MP3 ke WAV | cv.cm", "Cómo pasar MP3 a WAV | cv.cm"),
    "descMp3ToWav": L("Drop the MP3, pick 44.1 or 48 kHz if you need a target, download WAV, then play the file. The original stays on disk. Nothing is uploaded.", "拖入 MP3，必要时选 44.1 或 48 kHz，下载 WAV，再播文件。原文件还在。不上传。", "拖入 MP3，必要時選 44.1 或 48 kHz，下載 WAV，再播檔。原檔還在。不上傳。", "MP3を入れ、必要なら44.1または48kHz、WAVを保存して再生。元は残る。アップロードなし。", "MP3를 넣고 필요하면 44.1 또는 48kHz를 고른 뒤 WAV를 받아 재생하세요. 원본은 남습니다. 업로드 없음.", "Thả MP3, chọn 44.1 hoặc 48 kHz nếu cần, tải WAV, phát file. Bản gốc còn. Không tải lên.", "Letakkan MP3, pilih 44.1 atau 48 kHz jika perlu, unduh WAV, putar. Asli tetap. Tidak diunggah.", "Suelte el MP3, elija 44.1 o 48 kHz si hace falta, descargue WAV y reprodúzcalo. El original se queda. Nada se sube."),
    "titleJoinAudio": L("How to join audio files / merge MP3s | cv.cm", "怎么拼接音频 / 合并 MP3 | cv.cm", "怎麼拼接音訊 / 合併 MP3 | cv.cm", "音声をつなぐ / MP3を結合する方法 | cv.cm", "오디오 이어붙이기 / MP3 합치는 법 | cv.cm", "Cách ghép audio / gộp MP3 | cv.cm", "Cara gabung audio / gabung MP3 | cv.cm", "Cómo unir archivos de audio / fusionar MP3 | cv.cm"),
    "descJoinAudio": L("Drop two or more clips in order, download one WAV, then play it from start to end. Later clips match the first clip's sample rate. Nothing is uploaded.", "按顺序放入两段或更多，下载一份 WAV，从头到尾播一遍。后面的对齐第一段的采样率。不上传。", "按順序放入兩段或更多，下載一份 WAV，從頭到尾播一遍。後面的對齊第一段的取樣率。不上傳。", "2本以上を順に入れ、WAVを1つ保存し通しで再生。後続は先頭の周波数に合わせる。アップロードなし。", "두 개 이상을 순서대로 넣고 WAV 하나를 받은 뒤 처음부터 끝까지 재생하세요. 뒤 클립은 첫 클립의 레이트에 맞춥니다. 업로드 없음.", "Thả từ hai đoạn theo thứ tự, tải một WAV, phát hết. Đoạn sau khớp tần số đoạn đầu. Không tải lên.", "Letakkan dua atau lebih berurutan, unduh satu WAV, putar sampai akhir. Klip berikutnya mengikuti rate klip pertama. Tidak diunggah.", "Suelte dos o más en orden, descargue un WAV y reprodúzcalo entero. Los siguientes coinciden con la frecuencia del primero. Nada se sube."),
    "titleMakeFavicon": L("How to make a favicon | cv.cm", "怎么做网站图标 / favicon | cv.cm", "怎麼做網站圖示 / favicon | cv.cm", "ファビコンの作り方 | cv.cm", "파비콘 만드는 법 | cv.cm", "Cách làm favicon | cv.cm", "Cara buat favicon | cv.cm", "Cómo hacer un favicon | cv.cm"),
    "descMakeFavicon": L("Square the mark, pick Cover or Contain, download ICO (16/32/48) and a PNG zip (180/192/512), then check the 16-pixel file. Nothing is uploaded.", "裁成正方形，选 Cover 或 Contain，下载 ICO（16/32/48）和 PNG 压缩包（180/192/512），再看 16 像素那份。不上传。", "裁成正方形，選 Cover 或 Contain，下載 ICO（16/32/48）和 PNG 壓縮檔（180/192/512），再看 16 像素那份。不上傳。", "正方形にしてCoverかContain、ICO（16/32/48）とPNGのZIP（180/192/512）を保存し16pxを見る。アップロードなし。", "정사각으로 맞추고 Cover 또는 Contain을 고른 뒤 ICO(16/32/48)와 PNG zip(180/192/512)을 받고 16픽셀을 보세요. 업로드 없음.", "Cắt vuông, chọn Cover hay Contain, tải ICO (16/32/48) và zip PNG (180/192/512), xem file 16px. Không tải lên.", "Potong persegi, pilih Cover atau Contain, unduh ICO (16/32/48) dan zip PNG (180/192/512), cek 16px. Tidak diunggah.", "Cuadre la marca, elija Cover o Contain, descargue ICO (16/32/48) y un zip PNG (180/192/512) y mire el de 16 px. Nada se sube."),
}


def inject() -> None:
    for loc, path in FILES.items():
        data = json.loads(path.read_text())
        data["faq"].setdefault("learn", {})
        for lesson_id, payload in LESSONS.items():
            data["learn"][lesson_id] = payload["copy"][loc]
            data["faq"]["learn"][lesson_id] = payload["faq"][loc]
        for key, by_loc in META.items():
            data["meta"][key] = by_loc[loc]
        path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n")
        print("patched", path.name, list(LESSONS))


if __name__ == "__main__":
    inject()
