#!/usr/bin/env python3
"""Inject BMI, tip, loan, and cron how-tos."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LOCS = ["en", "zh-CN", "zh-TW", "ja", "ko", "vi", "id", "es"]
FILES = {loc: ROOT / "src/locales" / f"{loc}.json" for loc in LOCS}
COPY_KEYS = [
    "name", "blurb", "title", "lead", "result", "note",
    "s1t", "s1b", "s2t", "s2b", "s3t", "s3b", "s4t", "s4b", "s5t", "s5b", "s6t", "s6b",
    "diagram1", "diagram2",
]
FAQ_KEYS = [f"{side}{i}" for i in range(1, 6) for side in ("q", "a")]


def L(*vals: str) -> dict[str, str]:
    if len(vals) != 8:
        raise ValueError(len(vals), vals[0] if vals else None)
    return dict(zip(LOCS, vals))


def lesson(fields, faq):
    missing = [k for k in COPY_KEYS if k not in fields] + [k for k in FAQ_KEYS if k not in faq]
    if missing:
        raise SystemExit(f"missing {missing}")
    if not fields["title"]["en"].startswith("How to "):
        raise SystemExit(fields["title"]["en"])
    return {
        "copy": {loc: {k: v[loc] for k, v in fields.items()} for loc in LOCS},
        "faq": {loc: {k: v[loc] for k, v in faq.items()} for loc in LOCS},
    }


LESSONS = {
    "calculate-bmi": lesson(
        {
            "name": L("How to calculate BMI", "怎么算 BMI", "怎麼算 BMI", "BMIの計算方法", "BMI 계산하는 법", "Cách tính BMI", "Cara hitung BMI", "Cómo calcular el IMC"),
            "blurb": L("70 kg and 170 cm is a BMI of 24.2, in the Normal band. 1.70 in the centimetre box is 242214.5. 25 is Overweight and 30 is Obesity.", "70 公斤、170 厘米是 BMI 24.2，档位是 Normal。厘米那一格填 1.70 会得到 242214.5。25 起是 Overweight，30 起是 Obesity。", "70 公斤、170 公分是 BMI 24.2，檔位是 Normal。公分那一格填 1.70 會得到 242214.5。25 起是 Overweight，30 起是 Obesity。", "70 kg と 170 cm は BMI 24.2 で、区分は Normal。センチの欄に 1.70 と入れると 242214.5。25 から Overweight、30 から Obesity。", "70 kg와 170 cm는 BMI 24.2이고 구간은 Normal. 센티미터 칸에 1.70을 넣으면 242214.5. 25부터 Overweight, 30부터 Obesity.", "70 kg và 170 cm là BMI 24,2, mức Normal. Điền 1,70 vào ô xentimét được 242214,5. Từ 25 là Overweight, từ 30 là Obesity.", "70 kg dan 170 cm adalah BMI 24,2, pita Normal. 1,70 di kotak sentimeter menjadi 242214,5. 25 adalah Overweight, 30 adalah Obesity.", "70 kg y 170 cm es un IMC de 24,2, en la banda Normal. 1,70 en la casilla de centímetros es 242214,5. 25 es Overweight y 30 es Obesity."),
            "title": L("How to calculate BMI", "怎么算 BMI", "怎麼算 BMI", "BMIの計算方法", "BMI 계산하는 법", "Cách tính BMI", "Cara hitung BMI", "Cómo calcular el IMC"),
            "lead": L("You have a weight and a height. You will read a BMI to one decimal and a band in this tab. The weight is kilograms. The height is centimetres. 70 kg and 170 cm is 24.2. The same weight with 1.70 in the centimetre box is 242214.5.", "你有体重和身高。在当前标签页看一位小数的 BMI 和档位。体重是公斤。身高是厘米。70 公斤、170 厘米是 24.2。同样的体重，厘米那一格填 1.70，会得到 242214.5。", "你有體重和身高。在目前分頁看一位小數的 BMI 和檔位。體重是公斤。身高是公分。70 公斤、170 公分是 24.2。同樣的體重，公分那一格填 1.70，會得到 242214.5。", "体重と身長がある。このタブで小数第1位の BMI と区分を読む。体重はキログラム。身長はセンチメートル。70 kg と 170 cm は 24.2。同じ体重でセンチの欄に 1.70 と入れると 242214.5。", "몸무게와 키가 있습니다. 이 탭에서 소수 한 자리 BMI와 구간을 읽으세요. 몸무게는 킬로그램. 키는 센티미터. 70 kg와 170 cm는 24.2. 같은 몸무게로 센티미터 칸에 1.70을 넣으면 242214.5.", "Bạn có cân nặng và chiều cao. Đọc BMI một chữ số thập phân và mức trong tab này. Cân nặng là kilôgam. Chiều cao là xentimét. 70 kg và 170 cm là 24,2. Cùng cân nặng mà điền 1,70 vào ô xentimét thì được 242214,5.", "Anda punya berat dan tinggi. Baca BMI satu desimal dan pitanya di tab ini. Berat adalah kilogram. Tinggi adalah sentimeter. 70 kg dan 170 cm adalah 24,2. Berat yang sama dengan 1,70 di kotak sentimeter adalah 242214,5.", "Tiene un peso y una estatura. Lea un IMC a un decimal y una banda aquí. El peso va en kilogramos. La estatura va en centímetros. 70 kg y 170 cm es 24,2. El mismo peso con 1,70 en la casilla de centímetros es 242214,5."),
            "result": L("A BMI to one decimal, and one adult band: Underweight, Normal, Overweight, or Obesity.", "一位小数的 BMI，以及一个成人档位：Underweight、Normal、Overweight 或 Obesity。", "一位小數的 BMI，以及一個成人檔位：Underweight、Normal、Overweight 或 Obesity。", "小数第1位の BMI と、成人の区分一つ。Underweight、Normal、Overweight、Obesity。", "소수 한 자리 BMI와 성인 구간 하나. Underweight, Normal, Overweight, Obesity.", "Một BMI một chữ số thập phân, và một mức người lớn: Underweight, Normal, Overweight hoặc Obesity.", "BMI satu desimal, dan satu pita dewasa: Underweight, Normal, Overweight, atau Obesity.", "Un IMC a un decimal y una banda de adulto: Underweight, Normal, Overweight u Obesity."),
            "note": L("Open BMI when both numbers are above zero. The page uses kilograms and centimetres. It is not a diagnosis and it does not adjust for a child. Nothing is uploaded.", "两个数都大于 0 再打开 BMI。这一页用公斤和厘米。它不是诊断，也不按儿童调整。不上传。", "兩個數都大於 0 再開 BMI。這一頁用公斤和公分。它不是診斷，也不按兒童調整。不上傳。", "両方とも 0 より大きくなってから開く。キログラムとセンチメートル。診断ではなく、子ども用の調整もない。アップロードなし。", "두 수가 0보다 클 때 BMI를 여세요. 이 페이지는 킬로그램과 센티미터를 씁니다. 진단이 아니고 어린이 보정은 없습니다. 업로드 없음.", "Cả hai số lớn hơn 0 thì mở BMI. Trang dùng kilôgam và xentimét. Không phải chẩn đoán, cũng không chỉnh cho trẻ em. Không tải lên.", "Kedua angka di atas nol, baru buka BMI. Halaman memakai kilogram dan sentimeter. Bukan diagnosis, dan tidak menyesuaikan untuk anak. Tidak diunggah.", "Abra el IMC cuando ambos números sean mayores que cero. La página usa kilogramos y centímetros. No es un diagnóstico y no ajusta por la edad infantil. Nada se sube."),
            "s1t": L("Keep the height in centimetres", "身高用厘米", "身高用公分", "身長はセンチメートル", "키는 센티미터", "Chiều cao bằng xentimét", "Tinggi dalam sentimeter", "La estatura va en centímetros"),
            "s1b": L("70 kg and 170 cm is the pair for a BMI of 24.2. The box wants 170, not 1.70 and not a height in feet. 1.70 in the centimetre box is 1.70 cm, and the BMI becomes 242214.5.", "70 公斤配 170 厘米，BMI 是 24.2。这一格要 170，不是 1.70，也不是英尺。厘米那一格填 1.70，就是 1.70 厘米，BMI 会变成 242214.5。", "70 公斤配 170 公分，BMI 是 24.2。這一格要 170，不是 1.70，也不是英尺。公分那一格填 1.70，就是 1.70 公分，BMI 會變成 242214.5。", "70 kg と 170 cm で BMI は 24.2。欄は 170 であり、1.70 でもフィートでもない。センチの欄の 1.70 は 1.70 cm で、BMI は 242214.5 になる。", "70 kg와 170 cm가 BMI 24.2인 쌍입니다. 칸은 170을 원합니다. 1.70도 아니고 피트도 아닙니다. 센티미터 칸의 1.70은 1.70 cm이고 BMI는 242214.5가 됩니다.", "70 kg và 170 cm là cặp cho BMI 24,2. Ô muốn 170, không phải 1,70 và không phải chiều cao bằng foot. 1,70 trong ô xentimét là 1,70 cm, BMI thành 242214,5.", "70 kg dan 170 cm adalah pasangan untuk BMI 24,2. Kotak meminta 170, bukan 1,70 dan bukan tinggi dalam kaki. 1,70 di kotak sentimeter adalah 1,70 cm, dan BMI menjadi 242214,5.", "70 kg y 170 cm es el par para un IMC de 24,2. La casilla quiere 170, no 1,70 y no una estatura en pies. 1,70 en la casilla de centímetros es 1,70 cm, y el IMC pasa a 242214,5."),
            "s2t": L("Open BMI on cv.cm", "打开 cv.cm 的 BMI", "打開 cv.cm 的 BMI", "cv.cmのBMIを開く", "cv.cm BMI를 열기", "Mở BMI trên cv.cm", "Buka BMI di cv.cm", "Abra el IMC en cv.cm"),
            "s2b": L("The ratio stays in this tab.", "计算留在当前标签页。", "計算留在目前分頁。", "計算はこのタブ。", "계산은 이 탭에서.", "Phép tính ở trong tab này.", "Hitungan di tab ini.", "La cuenta queda en esta pestaña."),
            "s3t": L("Enter kilograms and centimetres", "填公斤和厘米", "填公斤和公分", "キログラムとセンチを入れる", "킬로그램과 센티미터 넣기", "Nhập kilôgam và xentimét", "Isi kilogram dan sentimeter", "Escriba kilogramos y centímetros"),
            "s3b": L("Both must be above zero. 70 and 170 become 24.2. The page divides the centimetres by 100 before it squares the metres.", "两个都要大于 0。70 和 170 变成 24.2。这一页先把厘米除以 100，再把米数平方。", "兩個都要大於 0。70 和 170 變成 24.2。這一頁先把公分除以 100，再把公尺數平方。", "両方 0 より大きいこと。70 と 170 は 24.2。センチを 100 で割ってからメートルを二乗する。", "둘 다 0보다 커야 합니다. 70과 170은 24.2가 됩니다. 페이지는 센티미터를 100으로 나눈 뒤 미터를 제곱합니다.", "Cả hai phải lớn hơn 0. 70 và 170 thành 24,2. Trang chia xentimét cho 100 trước khi bình phương mét.", "Keduanya harus di atas nol. 70 dan 170 menjadi 24,2. Halaman membagi sentimeter dengan 100 sebelum mengkuadratkan meter.", "Ambos deben ser mayores que cero. 70 y 170 pasan a 24,2. La página divide los centímetros entre 100 antes de elevar los metros al cuadrado."),
            "s4t": L("Read the one-decimal BMI", "看一位小数的 BMI", "看一位小數的 BMI", "小数第1位の BMI を読む", "소수 한 자리 BMI 읽기", "Đọc BMI một chữ số thập phân", "Baca BMI satu desimal", "Lea el IMC a un decimal"),
            "s4b": L("24.2 is the rounded line. The band is a separate line. Copy keeps both.", "24.2 是收成一位小数的那一行。档位是另一行。复制留下两行。", "24.2 是收成一位小數的那一行。檔位是另一行。複製留下兩行。", "24.2 が小数第1位の行。区分は別の行。コピーは両方残す。", "24.2가 소수 한 자리로 맞춘 줄입니다. 구간은 다른 줄입니다. 복사는 둘 다 남깁니다.", "24,2 là dòng đã làm tròn một chữ số. Mức là dòng riêng. Bản copy giữ cả hai.", "24,2 adalah baris yang dibulatkan. Pitanya baris terpisah. Salinan menyimpan keduanya.", "24,2 es la línea redondeada. La banda es otra línea. Copiar conserva ambas."),
            "s5t": L("Read the band from the cuts", "按分界读档位", "按分界讀檔位", "境目から区分を読む", "경계로 구간 읽기", "Đọc mức theo các mốc", "Baca pita dari batasnya", "Lea la banda desde los cortes"),
            "s5b": L("Below 18.5 is Underweight. 18.5 is Normal. 25 is Overweight. 30 is Obesity. 24.2 stays Normal. These are the adult cuts on this page, not a child's chart.", "不到 18.5 是 Underweight。18.5 是 Normal。25 是 Overweight。30 是 Obesity。24.2 仍是 Normal。这是这一页的成人分界，不是儿童表。", "不到 18.5 是 Underweight。18.5 是 Normal。25 是 Overweight。30 是 Obesity。24.2 仍是 Normal。這是這一頁的成人分界，不是兒童表。", "18.5 未満は Underweight。18.5 は Normal。25 は Overweight。30 は Obesity。24.2 は Normal のまま。このページの成人の境目であり、子どもの表ではない。", "18.5 미만은 Underweight. 18.5는 Normal. 25는 Overweight. 30은 Obesity. 24.2는 Normal입니다. 이 페이지의 성인 경계이지 어린이 표가 아닙니다.", "Dưới 18,5 là Underweight. 18,5 là Normal. 25 là Overweight. 30 là Obesity. 24,2 vẫn là Normal. Đây là mốc người lớn trên trang này, không phải bảng của trẻ em.", "Di bawah 18,5 adalah Underweight. 18,5 adalah Normal. 25 adalah Overweight. 30 adalah Obesity. 24,2 tetap Normal. Ini batas dewasa di halaman ini, bukan tabel anak.", "Por debajo de 18,5 es Underweight. 18,5 es Normal. 25 es Overweight. 30 es Obesity. 24,2 sigue en Normal. Son los cortes de adulto de esta página, no una tabla infantil."),
            "s6t": L("Leave the medical chart alone", "别把它当成诊断", "別把它當成診斷", "診断書にはしない", "진단으로 쓰지 않기", "Đừng lấy nó làm chẩn đoán", "Jangan jadikan diagnosis", "Déjelo fuera del diagnóstico"),
            "s6b": L("The page only divides two numbers and names a band. It does not see age, muscle, or a clinic. A zero or a negative number fails.", "这一页只把两个数相除，再给一个档位。它看不到年龄、肌肉或诊所。0 或负数会失败。", "這一頁只把兩個數相除，再給一個檔位。它看不到年齡、肌肉或診所。0 或負數會失敗。", "このページは二つの数を割って区分を名乗るだけ。年齢も筋肉も診察も見ない。0 や負の数は失敗。", "이 페이지는 두 수를 나누고 구간 이름을 붙일 뿐입니다. 나이, 근육, 진료는 보지 않습니다. 0이나 음수는 실패합니다.", "Trang chỉ chia hai số rồi gọi tên một mức. Nó không thấy tuổi, cơ bắp hay phòng khám. Số 0 hoặc số âm thì thất bại.", "Halaman hanya membagi dua angka dan menamai pita. Tidak melihat umur, otot, atau klinik. Nol atau angka negatif gagal.", "Esta página solo divide dos números y nombra una banda. No ve la edad, el músculo ni una clínica. Un cero o un número negativo falla."),
            "diagram1": L("70 kg and 170 cm is 24.2. 1.70 cm is 242214.5.", "70 公斤、170 厘米是 24.2。1.70 厘米是 242214.5。", "70 公斤、170 公分是 24.2。1.70 公分是 242214.5。", "70 kg、170 cm は 24.2。1.70 cm は 242214.5。", "70 kg, 170 cm는 24.2. 1.70 cm는 242214.5.", "70 kg và 170 cm là 24,2. 1,70 cm là 242214,5.", "70 kg dan 170 cm adalah 24,2. 1,70 cm adalah 242214,5.", "70 kg y 170 cm es 24,2. 1,70 cm es 242214,5."),
            "diagram2": L("18.5 is Normal. 25 is Overweight. 30 is Obesity.", "18.5 是 Normal。25 是 Overweight。30 是 Obesity。", "18.5 是 Normal。25 是 Overweight。30 是 Obesity。", "18.5 は Normal。25 は Overweight。30 は Obesity。", "18.5는 Normal. 25는 Overweight. 30은 Obesity.", "18,5 là Normal. 25 là Overweight. 30 là Obesity.", "18,5 adalah Normal. 25 adalah Overweight. 30 adalah Obesity.", "18,5 es Normal. 25 es Overweight. 30 es Obesity."),
        },
        {
            "q1": L("Can I calculate BMI free online?", "可以免费在线算 BMI 吗？", "可以免費線上算 BMI 嗎？", "BMIを無料で計算できる？", "BMI를 무료로 계산할 수 있나요?", "Tính BMI miễn phí online được không?", "Bisa hitung BMI gratis online?", "¿Puedo calcular el IMC gratis en línea?"),
            "a1": L("Yes. cv.cm shows the BMI and the band in this tab. Nothing is uploaded.", "可以。cv.cm 在当前标签页显示 BMI 和档位。不上传。", "可以。cv.cm 在目前分頁顯示 BMI 和檔位。不上傳。", "できる。このタブで BMI と区分を出す。アップロードなし。", "됩니다. 이 탭에서 BMI와 구간을 보여 줍니다. 업로드 없음.", "Được. Hiện BMI và mức trong tab này. Không tải lên.", "Ya. Menampilkan BMI dan pita di tab ini. Tidak diunggah.", "Sí. Muestra el IMC y la banda en esta pestaña. Nada se sube."),
            "q2": L("What is the BMI for 70 kg and 170 cm?", "70 公斤、170 厘米的 BMI 是多少？", "70 公斤、170 公分的 BMI 是多少？", "70 kg、170 cm の BMI は？", "70 kg, 170 cm의 BMI는?", "BMI của 70 kg và 170 cm là bao nhiêu?", "BMI untuk 70 kg dan 170 cm berapa?", "¿Cuál es el IMC de 70 kg y 170 cm?"),
            "a2": L("24.2, and the band is Normal.", "24.2，档位是 Normal。", "24.2，檔位是 Normal。", "24.2。区分は Normal。", "24.2이고 구간은 Normal입니다.", "24,2, và mức là Normal.", "24,2, dan pitanya Normal.", "24,2, y la banda es Normal."),
            "q3": L("What if I type 1.70 for the height?", "身高填 1.70 会怎样？", "身高填 1.70 會怎樣？", "身長に 1.70 と入れると？", "키에 1.70을 넣으면?", "Điền chiều cao 1,70 thì sao?", "Bagaimana jika tinggi diisi 1,70?", "¿Qué pasa si escribo 1,70 de estatura?"),
            "a3": L("The box is centimetres, so 1.70 means 1.70 cm. The BMI becomes 242214.5. Type 170.", "这一格是厘米，所以 1.70 表示 1.70 厘米。BMI 会变成 242214.5。要填 170。", "這一格是公分，所以 1.70 表示 1.70 公分。BMI 會變成 242214.5。要填 170。", "欄はセンチなので 1.70 は 1.70 cm。BMI は 242214.5 になる。170 と入れる。", "칸은 센티미터이므로 1.70은 1.70 cm입니다. BMI는 242214.5가 됩니다. 170을 넣으세요.", "Ô là xentimét, nên 1,70 nghĩa là 1,70 cm. BMI thành 242214,5. Hãy điền 170.", "Kotaknya sentimeter, jadi 1,70 berarti 1,70 cm. BMI menjadi 242214,5. Ketik 170.", "La casilla es de centímetros, así que 1,70 significa 1,70 cm. El IMC pasa a 242214,5. Escriba 170."),
            "q4": L("Where does Overweight start?", "Overweight 从哪里开始？", "Overweight 從哪裡開始？", "Overweight はどこから？", "Overweight는 어디서 시작하나요?", "Overweight bắt đầu từ đâu?", "Overweight mulai dari mana?", "¿Dónde empieza Overweight?"),
            "a4": L("At 25. 18.5 is still Normal. Obesity starts at 30.", "从 25 起。18.5 仍是 Normal。Obesity 从 30 起。", "從 25 起。18.5 仍是 Normal。Obesity 從 30 起。", "25 から。18.5 はまだ Normal。Obesity は 30 から。", "25부터입니다. 18.5는 아직 Normal. Obesity는 30부터입니다.", "Từ 25. 18,5 vẫn là Normal. Obesity bắt đầu từ 30.", "Dari 25. 18,5 masih Normal. Obesity mulai dari 30.", "En 25. 18,5 sigue siendo Normal. Obesity empieza en 30."),
            "q5": L("Are the numbers uploaded?", "这些数会上传吗？", "這些數會上傳嗎？", "アップロードされる？", "업로드되나요?", "Các số có bị tải lên không?", "Apakah angkanya diunggah?", "¿Se suben los números?"),
            "a5": L("No. Closing the tab discards them. The band is not a diagnosis.", "不会。关掉标签页就没了。档位不是诊断。", "不會。關掉分頁就沒了。檔位不是診斷。", "しない。タブを閉じると消える。区分は診断ではない。", "아니요. 탭을 닫으면 사라집니다. 구간은 진단이 아닙니다.", "Không. Đóng tab là mất. Mức không phải chẩn đoán.", "Tidak. Tutup tab, hilang. Pitanya bukan diagnosis.", "No. Al cerrar la pestaña se pierden. La banda no es un diagnóstico."),
        },
    ),
    "split-tip": lesson(
        {
            "name": L("How to split a tip", "怎么分小费", "怎麼分小費", "チップの割り方", "팁 나누는 법", "Cách chia tiền tip", "Cara bagi tip", "Cómo repartir una propina"),
            "blurb": L("100 at 20% for 4 people is a tip of 20.00, a total of 120.00, and 30.00 each. Each person splits the whole bill. 2.9 people counts as 2.", "100 的 20%，4 个人，小费 20.00，合计 120.00，每人 30.00。每人分的是整张账单。2.9 个人按 2 个人算。", "100 的 20%，4 個人，小費 20.00，合計 120.00，每人 30.00。每人分的是整張帳單。2.9 個人按 2 個人算。", "100 の 20% を 4 人で割ると、チップ 20.00、合計 120.00、一人 30.00。一人が割るのは勘定全体。2.9 人は 2 人。", "100의 20%를 4명이 나누면 팁 20.00, 합계 120.00, 각자 30.00. 각자 나누는 것은 계산서 전체. 2.9명은 2명으로 셉니다.", "100 với 20% cho 4 người là tip 20,00, tổng 120,00, mỗi người 30,00. Mỗi người chia cả hóa đơn. 2,9 người tính là 2.", "100 dengan 20% untuk 4 orang adalah tip 20,00, total 120,00, dan 30,00 masing-masing. Setiap orang membagi seluruh tagihan. 2,9 orang dihitung 2.", "100 con un 20% para 4 personas es una propina de 20,00, un total de 120,00 y 30,00 cada uno. Cada persona reparte la cuenta entera. 2,9 personas cuentan como 2."),
            "title": L("How to split a tip", "怎么分小费", "怎麼分小費", "チップの割り方", "팁 나누는 법", "Cách chia tiền tip", "Cara bagi tip", "Cómo repartir una propina"),
            "lead": L("You have a bill, a percent, and a number of people. You will read the tip, the total, and the share in this tab. 100 at 20% for 4 people is a tip of 20.00 and 30.00 each. The 30.00 is the whole bill split four ways. The tip alone, split four ways, would be 5.00.", "你有账单、百分比和人数。在当前标签页看小费、合计和每人一份。100 的 20%，4 个人，小费是 20.00，每人 30.00。这 30.00 是整张账单分成四份。只把小费分成四份，会是 5.00。", "你有帳單、百分比和人數。在目前分頁看小費、合計和每人一份。100 的 20%，4 個人，小費是 20.00，每人 30.00。這 30.00 是整張帳單分成四份。只把小費分成四份，會是 5.00。", "勘定、パーセント、人数がある。このタブでチップ、合計、一人分を読む。100 の 20% を 4 人ならチップ 20.00、一人 30.00。30.00 は勘定全体を四つに割った額。チップだけを四つに割ると 5.00。", "계산서, 퍼센트, 인원수가 있습니다. 이 탭에서 팁, 합계, 몫을 읽으세요. 100의 20%를 4명이면 팁 20.00, 각자 30.00. 30.00은 계산서 전체를 넷으로 나눈 값입니다. 팁만 넷으로 나누면 5.00입니다.", "Bạn có hóa đơn, phần trăm và số người. Đọc tiền tip, tổng và phần mỗi người trong tab này. 100 với 20% cho 4 người là tip 20,00 và mỗi người 30,00. 30,00 là cả hóa đơn chia bốn. Chỉ chia tiền tip làm bốn thì là 5,00.", "Anda punya tagihan, persen, dan jumlah orang. Baca tip, total, dan bagian di tab ini. 100 dengan 20% untuk 4 orang adalah tip 20,00 dan 30,00 masing-masing. 30,00 adalah seluruh tagihan dibagi empat. Tip saja dibagi empat adalah 5,00.", "Tiene una cuenta, un porcentaje y un número de personas. Lea la propina, el total y la parte aquí. 100 con un 20% para 4 personas es una propina de 20,00 y 30,00 cada uno. Los 30,00 son la cuenta entera en cuatro partes. Solo la propina, en cuatro partes, sería 5,00."),
            "result": L("A tip, a total, and one share, each to two decimals, from one bill, one percent, and one count of people.", "一个小费、一个合计、一份每人金额，都到两位小数，来自一张账单、一个百分比和一个人数。", "一個小費、一個合計、一份每人金額，都到兩位小數，來自一張帳單、一個百分比和一個人數。", "チップ、合計、一人分。どれも小数第2位。勘定一つ、パーセント一つ、人数一つから。", "팁, 합계, 한 사람 몫. 모두 소수 둘째 자리. 계산서 하나, 퍼센트 하나, 인원 하나에서.", "Một khoản tip, một tổng, một phần mỗi người, hai chữ số thập phân, từ một hóa đơn, một phần trăm và một số người.", "Satu tip, satu total, dan satu bagian, dua desimal, dari satu tagihan, satu persen, dan satu jumlah orang.", "Una propina, un total y una parte, cada uno a dos decimales, a partir de una cuenta, un porcentaje y un número de personas."),
            "note": L("Open the tip split when the bill is zero or more and the people count is at least 1. The page does not name a currency. Nothing is uploaded.", "账单大于或等于 0，并且人数至少是 1，再打开小费分摊。这一页不标明货币。不上传。", "帳單大於或等於 0，並且人數至少是 1，再開小費分攤。這一頁不標明貨幣。不上傳。", "勘定が 0 以上で人数が 1 以上になってから開く。通貨名は出さない。アップロードなし。", "계산서가 0 이상이고 인원이 최소 1일 때 팁 나누기를 여세요. 이 페이지는 통화를 적지 않습니다. 업로드 없음.", "Hóa đơn từ 0 trở lên và số người ít nhất là 1 thì mở chia tip. Trang không ghi đơn vị tiền. Không tải lên.", "Tagihan nol atau lebih dan jumlah orang minimal 1, baru buka bagi tip. Halaman tidak menyebut mata uang. Tidak diunggah.", "Abra el reparto cuando la cuenta sea cero o más y las personas sean al menos 1. La página no nombra una moneda. Nada se sube."),
            "s1t": L("Split the whole bill, not only the tip", "分的是整张账单，不是只分小费", "分的是整張帳單，不是只分小費", "割るのは勘定全体。チップだけではない", "나누는 것은 계산서 전체, 팁만이 아님", "Chia cả hóa đơn, không chỉ tiền tip", "Bagi seluruh tagihan, bukan hanya tipnya", "Reparta la cuenta entera, no solo la propina"),
            "s1b": L("100 at 20% for 4 people: the tip is 20.00, the total is 120.00, and each person pays 30.00. Dividing only the tip by 4 gives 5.00, which is a different question.", "100 的 20%，4 个人：小费 20.00，合计 120.00，每人付 30.00。只把小费除以 4 得到 5.00，那是另一个问题。", "100 的 20%，4 個人：小費 20.00，合計 120.00，每人付 30.00。只把小費除以 4 得到 5.00，那是另一個問題。", "100 の 20% を 4 人：チップ 20.00、合計 120.00、一人 30.00。チップだけを 4 で割ると 5.00。それは別の問い。", "100의 20%, 4명: 팁 20.00, 합계 120.00, 각자 30.00. 팁만 4로 나누면 5.00. 그것은 다른 질문입니다.", "100 với 20%, 4 người: tip 20,00, tổng 120,00, mỗi người trả 30,00. Chỉ chia tip cho 4 được 5,00, đó là câu khác.", "100 dengan 20%, 4 orang: tip 20,00, total 120,00, masing-masing membayar 30,00. Membagi hanya tipnya dengan 4 memberi 5,00, itu pertanyaan lain.", "100 con un 20% para 4 personas: la propina es 20,00, el total es 120,00 y cada persona paga 30,00. Dividir solo la propina entre 4 da 5,00, y esa es otra pregunta."),
            "s2t": L("Open the tip split on cv.cm", "打开 cv.cm 的小费分摊", "打開 cv.cm 的小費分攤", "cv.cmのチップ割りを開く", "cv.cm 팁 나누기를 열기", "Mở chia tip trên cv.cm", "Buka bagi tip di cv.cm", "Abra el reparto de propina en cv.cm"),
            "s2b": L("The arithmetic stays in this tab.", "计算留在当前标签页。", "計算留在目前分頁。", "計算はこのタブ。", "계산은 이 탭에서.", "Phép tính ở trong tab này.", "Hitungan di tab ini.", "La cuenta queda en esta pestaña."),
            "s3t": L("Enter the bill, the percent, and the people", "填账单、百分比和人数", "填帳單、百分比和人數", "勘定、パーセント、人数を入れる", "계산서, 퍼센트, 인원 넣기", "Nhập hóa đơn, phần trăm và số người", "Isi tagihan, persen, dan orang", "Escriba la cuenta, el porcentaje y las personas"),
            "s3b": L("The bill must be zero or more. The percent is the tip rate. 100 at 20% adds a tip of 20.00.", "账单要大于或等于 0。百分比是小费比例。100 的 20% 加上小费 20.00。", "帳單要大於或等於 0。百分比是小費比例。100 的 20% 加上小費 20.00。", "勘定は 0 以上。パーセントはチップ率。100 の 20% はチップ 20.00 を足す。", "계산서는 0 이상. 퍼센트는 팁 비율. 100의 20%는 팁 20.00을 더합니다.", "Hóa đơn từ 0 trở lên. Phần trăm là tỉ lệ tip. 100 với 20% cộng tip 20,00.", "Tagihan nol atau lebih. Persen adalah tarif tip. 100 dengan 20% menambah tip 20,00.", "La cuenta debe ser cero o más. El porcentaje es la tasa de propina. 100 con un 20% suma una propina de 20,00."),
            "s4t": L("Read tip, total, and each", "看小费、合计和每人", "看小費、合計和每人", "チップ、合計、一人分を読む", "팁, 합계, 각자 읽기", "Đọc tip, tổng và mỗi người", "Baca tip, total, dan masing-masing", "Lea propina, total y cada uno"),
            "s4b": L("All three lines use two decimals. There is no currency. Each is the total divided by the people count the page kept.", "三行都是两位小数。没有货币。每人那一行是合计除以这一页留下的人数。", "三行都是兩位小數。沒有貨幣。每人那一行是合計除以這一頁留下的人數。", "三行とも小数第2位。通貨はない。一人分は、ページが残した人数で合計を割った額。", "세 줄 모두 소수 둘째 자리. 통화는 없습니다. 각자 줄은 합계를 페이지가 남긴 인원으로 나눈 값입니다.", "Cả ba dòng đều hai chữ số thập phân. Không có đơn vị tiền. Mỗi người là tổng chia cho số người trang giữ lại.", "Ketiga baris dua desimal. Tidak ada mata uang. Masing-masing adalah total dibagi jumlah orang yang halaman simpan.", "Las tres líneas van a dos decimales. No hay moneda. Cada uno es el total dividido por el número de personas que la página conservó."),
            "s5t": L("A fraction of a person is dropped", "不满 1 的零头人数会被丢掉", "不滿 1 的零頭人數會被丟掉", "1 人に満たない端数は捨てる", "한 명에 못 미치는 끝수는 버림", "Phần lẻ của một người bị bỏ", "Pecahan orang dibuang", "La fracción de una persona se descarta"),
            "s5b": L("2.9 people counts as 2. On a bill of 100 at 20%, each of those 2 pays 60.00. 1.2 people counts as 1, so the one person pays 120.00.", "2.9 个人按 2 个人算。账单 100、20% 时，这 2 人每人付 60.00。1.2 个人按 1 个人算，所以这一人付 120.00。", "2.9 個人按 2 個人算。帳單 100、20% 時，這 2 人每人付 60.00。1.2 個人按 1 個人算，所以這一人付 120.00。", "2.9 人は 2 人。勘定 100 の 20% なら、その 2 人が一人 60.00。1.2 人は 1 人なので、その一人が 120.00。", "2.9명은 2명으로 셉니다. 계산서 100의 20%이면 그 2명이 각자 60.00. 1.2명은 1명으로 세므로 그 한 사람이 120.00.", "2,9 người tính là 2. Hóa đơn 100 với 20%, mỗi người trong 2 người đó trả 60,00. 1,2 người tính là 1, nên người đó trả 120,00.", "2,9 orang dihitung 2. Pada tagihan 100 dengan 20%, masing-masing dari 2 orang itu membayar 60,00. 1,2 orang dihitung 1, jadi orang itu membayar 120,00.", "2,9 personas cuentan como 2. En una cuenta de 100 con un 20%, cada una de esas 2 paga 60,00. 1,2 personas cuentan como 1, así que esa persona paga 120,00."),
            "s6t": L("Fewer than one person fails", "不到一个人会失败", "不到一個人會失敗", "1 人未満は失敗", "한 명보다 적으면 실패", "Ít hơn một người thì thất bại", "Kurang dari satu orang gagal", "Menos de una persona falla"),
            "s6b": L("0.9 does not become one person, and it does not become zero. The page fails. A bill below zero also fails. A bill of 0 is a tip of 0.00.", "0.9 不会变成一个人，也不会变成零。这一页会失败。账单小于 0 也会失败。账单 0 的小费是 0.00。", "0.9 不會變成一個人，也不會變成零。這一頁會失敗。帳單小於 0 也會失敗。帳單 0 的小費是 0.00。", "0.9 は 1 人にも 0 にもならない。ページは失敗する。0 未満の勘定も失敗。勘定 0 のチップは 0.00。", "0.9는 한 명이 되지도 않고 0이 되지도 않습니다. 페이지가 실패합니다. 0보다 작은 계산서도 실패합니다. 계산서 0의 팁은 0.00.", "0,9 không thành một người, cũng không thành không. Trang thất bại. Hóa đơn dưới 0 cũng thất bại. Hóa đơn 0 thì tip là 0,00.", "0,9 tidak menjadi satu orang, dan tidak menjadi nol. Halaman gagal. Tagihan di bawah nol juga gagal. Tagihan 0 adalah tip 0,00.", "0,9 no se convierte en una persona, ni en cero. La página falla. Una cuenta menor que cero también falla. Una cuenta de 0 es una propina de 0,00."),
            "diagram1": L("100 at 20% for 4 people: tip 20.00, total 120.00, each 30.00.", "100 的 20%，4 人：小费 20.00，合计 120.00，每人 30.00。", "100 的 20%，4 人：小費 20.00，合計 120.00，每人 30.00。", "100 の 20%、4 人：チップ 20.00、合計 120.00、一人 30.00。", "100의 20%, 4명: 팁 20.00, 합계 120.00, 각자 30.00.", "100 với 20%, 4 người: tip 20,00, tổng 120,00, mỗi người 30,00.", "100 dengan 20%, 4 orang: tip 20,00, total 120,00, masing-masing 30,00.", "100 con 20%, 4 personas: propina 20,00, total 120,00, cada uno 30,00."),
            "diagram2": L("2.9 people counts as 2, so each pays 60.00.", "2.9 个人按 2 个人算，所以每人付 60.00。", "2.9 個人按 2 個人算，所以每人付 60.00。", "2.9 人は 2 人なので、一人 60.00。", "2.9명은 2명이므로 각자 60.00.", "2,9 người tính là 2, nên mỗi người trả 60,00.", "2,9 orang dihitung 2, jadi masing-masing membayar 60,00.", "2,9 personas cuentan como 2, así que cada una paga 60,00."),
        },
        {
            "q1": L("Can I split a tip free online?", "可以免费在线分小费吗？", "可以免費線上分小費嗎？", "チップを無料で割れる？", "팁을 무료로 나눌 수 있나요?", "Chia tip miễn phí online được không?", "Bisa bagi tip gratis online?", "¿Puedo repartir una propina gratis en línea?"),
            "a1": L("Yes. cv.cm shows the tip, the total, and each share in this tab. Nothing is uploaded.", "可以。cv.cm 在当前标签页显示小费、合计和每人一份。不上传。", "可以。cv.cm 在目前分頁顯示小費、合計和每人一份。不上傳。", "できる。このタブでチップ、合計、一人分を出す。アップロードなし。", "됩니다. 이 탭에서 팁, 합계, 각자 몫을 보여 줍니다. 업로드 없음.", "Được. Hiện tip, tổng và phần mỗi người trong tab này. Không tải lên.", "Ya. Menampilkan tip, total, dan bagian masing-masing di tab ini. Tidak diunggah.", "Sí. Muestra la propina, el total y la parte de cada uno en esta pestaña. Nada se sube."),
            "q2": L("What does each person pay on 100 at 20% for 4 people?", "100 的 20%，4 个人，每人付多少？", "100 的 20%，4 個人，每人付多少？", "100 の 20% を 4 人なら一人いくら？", "100의 20%를 4명이면 각자는?", "100 với 20% cho 4 người, mỗi người trả bao nhiêu?", "100 dengan 20% untuk 4 orang, masing-masing bayar berapa?", "¿Cuánto paga cada persona en 100 con un 20% para 4?"),
            "a2": L("30.00. The tip is 20.00 and the total is 120.00. 5.00 would be the tip split alone.", "30.00。小费是 20.00，合计是 120.00。5.00 只是小费单独分成四份。", "30.00。小費是 20.00，合計是 120.00。5.00 只是小費單獨分成四份。", "30.00。チップは 20.00、合計は 120.00。5.00 はチップだけを割った額。", "30.00. 팁은 20.00, 합계는 120.00. 5.00은 팁만 나눈 값입니다.", "30,00. Tip là 20,00 và tổng là 120,00. 5,00 chỉ là tip chia riêng.", "30,00. Tipnya 20,00 dan totalnya 120,00. 5,00 adalah tip yang dibagi sendiri.", "30,00. La propina es 20,00 y el total es 120,00. 5,00 sería solo la propina repartida."),
            "q3": L("What does 2.9 people mean?", "2.9 个人是什么意思？", "2.9 個人是什麼意思？", "2.9 人とは？", "2.9명은 무슨 뜻인가요?", "2,9 người nghĩa là gì?", "Apa arti 2,9 orang?", "¿Qué significa 2,9 personas?"),
            "a3": L("It counts as 2. The fraction is dropped. On 100 at 20%, each of those 2 pays 60.00.", "按 2 个人算。零头丢掉。100 的 20%，这 2 人每人付 60.00。", "按 2 個人算。零頭丟掉。100 的 20%，這 2 人每人付 60.00。", "2 人として数える。端数は捨てる。100 の 20% なら、その 2 人が一人 60.00。", "2명으로 셉니다. 끝수는 버립니다. 100의 20%이면 그 2명이 각자 60.00.", "Tính là 2. Phần lẻ bị bỏ. Với 100 và 20%, mỗi người trong 2 người đó trả 60,00.", "Dihitung 2. Pecahannya dibuang. Pada 100 dengan 20%, masing-masing dari 2 orang itu membayar 60,00.", "Cuenta como 2. La fracción se descarta. En 100 con un 20%, cada una de esas 2 paga 60,00."),
            "q4": L("What if the people count is below 1?", "人数小于 1 会怎样？", "人數小於 1 會怎樣？", "人数が 1 未満だと？", "인원이 1보다 작으면?", "Số người dưới 1 thì sao?", "Jika jumlah orang di bawah 1?", "¿Y si las personas son menos de 1?"),
            "a4": L("The page fails. 0.9 is not rounded up to 1.", "这一页会失败。0.9 不会进成 1。", "這一頁會失敗。0.9 不會進成 1。", "失敗する。0.9 は 1 に繰り上がらない。", "페이지가 실패합니다. 0.9는 1로 올림되지 않습니다.", "Trang thất bại. 0,9 không làm tròn lên 1.", "Halaman gagal. 0,9 tidak dibulatkan naik menjadi 1.", "La página falla. 0,9 no se redondea hacia arriba a 1."),
            "q5": L("Is the bill uploaded?", "账单会上传吗？", "帳單會上傳嗎？", "アップロードされる？", "업로드되나요?", "Hóa đơn có bị tải lên không?", "Apakah tagihannya diunggah?", "¿Se sube la cuenta?"),
            "a5": L("No. Closing the tab discards it. The numbers have no currency.", "不会。关掉标签页就没了。这些数字没有货币。", "不會。關掉分頁就沒了。這些數字沒有貨幣。", "しない。タブを閉じると消える。数に通貨はない。", "아니요. 탭을 닫으면 사라집니다. 숫자에는 통화가 없습니다.", "Không. Đóng tab là mất. Các số không có đơn vị tiền.", "Tidak. Tutup tab, hilang. Angkanya tidak punya mata uang.", "No. Al cerrar la pestaña se pierde. Los números no tienen moneda."),
        },
    ),
    "loan-payment": lesson(
        {
            "name": L("How to calculate a loan payment", "怎么算贷款月供", "怎麼算貸款月付", "ローン返済額の計算方法", "대출 상환액 계산하는 법", "Cách tính khoản trả góp", "Cara hitung cicilan", "Cómo calcular la cuota de un préstamo"),
            "blurb": L("10000 at 12% for one year is a monthly payment of 888.49. The interest is 661.85, not 1200. 12000 at 0% for one year is 1000.00 a month.", "10000、年利率 12%、一年，月供 888.49。利息是 661.85，不是 1200。12000、利率 0%、一年，每月 1000.00。", "10000、年利率 12%、一年，月付 888.49。利息是 661.85，不是 1200。12000、利率 0%、一年，每月 1000.00。", "10000 を年 12% で 1 年なら月々 888.49。利息は 661.85 であり 1200 ではない。12000 を 0% で 1 年なら毎月 1000.00。", "10000을 연 12%로 1년은 매달 888.49. 이자는 661.85이고 1200이 아닙니다. 12000을 0%로 1년은 매달 1000.00.", "10000 với 12% trong một năm là khoản tháng 888,49. Lãi là 661,85, không phải 1200. 12000 với 0% trong một năm là 1000,00 mỗi tháng.", "10000 pada 12% selama satu tahun adalah cicilan bulanan 888,49. Bunganya 661,85, bukan 1200. 12000 pada 0% selama satu tahun adalah 1000,00 sebulan.", "10000 al 12% durante un año es una cuota mensual de 888,49. El interés es 661,85, no 1200. 12000 al 0% durante un año es 1000,00 al mes."),
            "title": L("How to calculate a loan payment", "怎么算贷款月供", "怎麼算貸款月付", "ローン返済額の計算方法", "대출 상환액 계산하는 법", "Cách tính khoản trả góp", "Cara hitung cicilan", "Cómo calcular la cuota de un préstamo"),
            "lead": L("You have a principal, an annual percent, and a number of years. You will read the monthly payment, the interest, and the total in this tab. 10000 at 12% for one year is 888.49 a month. The interest is 661.85. A flat 12% of 10000 is 1200, and that is a different sum because this page pays the balance down every month.", "你有本金、年百分比和年数。在当前标签页看月供、利息和总额。10000、年利率 12%、一年，每月 888.49。利息是 661.85。10000 的 12% 一次算是 1200，那是另一笔数，因为这一页每个月都把余额还下去。", "你有本金、年百分比和年數。在目前分頁看月付、利息和總額。10000、年利率 12%、一年，每月 888.49。利息是 661.85。10000 的 12% 一次算是 1200，那是另一筆數，因為這一頁每個月都把餘額還下去。", "元金、年パーセント、年数がある。このタブで毎月の返済、利息、総額を読む。10000 を年 12% で 1 年なら月々 888.49。利息は 661.85。10000 の 12% を一度にかけると 1200。別の合計で、このページは毎月残高を減らす。", "원금, 연 퍼센트, 연수가 있습니다. 이 탭에서 월 상환액, 이자, 총액을 읽으세요. 10000을 연 12%로 1년은 매달 888.49. 이자는 661.85. 10000의 12%를 한 번에 매기면 1200. 다른 합계이고, 이 페이지는 매달 잔액을 줄입니다.", "Bạn có gốc, phần trăm năm và số năm. Đọc khoản tháng, tiền lãi và tổng trong tab này. 10000 với 12% một năm là 888,49 mỗi tháng. Lãi là 661,85. 12% phẳng của 10000 là 1200, đó là phép khác vì trang này trả dư nợ xuống mỗi tháng.", "Anda punya pokok, persen tahunan, dan jumlah tahun. Baca cicilan bulanan, bunga, dan total di tab ini. 10000 pada 12% selama satu tahun adalah 888,49 sebulan. Bunganya 661,85. 12% datar dari 10000 adalah 1200, itu jumlah lain karena halaman ini menurunkan saldo setiap bulan.", "Tiene un principal, un porcentaje anual y un número de años. Lea la cuota mensual, el interés y el total aquí. 10000 al 12% durante un año es 888,49 al mes. El interés es 661,85. Un 12% plano de 10000 es 1200, y esa es otra suma porque esta página va bajando el saldo cada mes."),
            "result": L("A monthly payment, the interest, and the total paid, each to two decimals.", "一个月供、一笔利息、一个还款总额，都到两位小数。", "一個月付、一筆利息、一個還款總額，都到兩位小數。", "毎月の返済、利息、支払総額。どれも小数第2位。", "월 상환액, 이자, 갚은 총액. 모두 소수 둘째 자리.", "Một khoản tháng, tiền lãi, và tổng đã trả, hai chữ số thập phân.", "Cicilan bulanan, bunga, dan total yang dibayar, dua desimal.", "Una cuota mensual, el interés y el total pagado, cada uno a dos decimales."),
            "note": L("Open the loan page when the principal is above zero and the years produce at least one month. 12 means 12% a year, not 0.12. Nothing is uploaded.", "本金大于 0，并且年数至少能化成一个月，再打开贷款。12 表示一年 12%，不是 0.12。不上传。", "本金大於 0，並且年數至少能化成一個月，再開貸款。12 表示一年 12%，不是 0.12。不上傳。", "元金が 0 より大きく、年数が少なくとも一か月になるとき開く。12 は年 12% であり 0.12 ではない。アップロードなし。", "원금이 0보다 크고 연수가 적어도 한 달이 될 때 대출을 여세요. 12는 연 12%이지 0.12가 아닙니다. 업로드 없음.", "Gốc lớn hơn 0 và số năm ra ít nhất một tháng thì mở khoản vay. 12 nghĩa là 12% một năm, không phải 0,12. Không tải lên.", "Pokok di atas nol dan tahun menghasilkan setidaknya satu bulan, baru buka pinjaman. 12 berarti 12% setahun, bukan 0,12. Tidak diunggah.", "Abra el préstamo cuando el principal sea mayor que cero y los años den al menos un mes. 12 significa 12% al año, no 0,12. Nada se sube."),
            "s1t": L("Do not multiply the principal by the rate once", "不要把本金乘一次利率就算完", "不要把本金乘一次利率就算完", "元金に利率を一度かけない", "원금에 이율을 한 번 곱하고 끝내지 않기", "Đừng nhân gốc với lãi một lần rồi xong", "Jangan kalikan pokok dengan suku sekali lalu selesai", "No multiplique el principal por la tasa una sola vez"),
            "s1b": L("10000 at 12% for one year is a payment of 888.49 each month, interest of 661.85, and a total of 10661.85. Twelve percent of 10000, taken once, is 1200. The loan interest is lower because each payment reduces the balance.", "10000、年利率 12%、一年：每月 888.49，利息 661.85，总额 10661.85。10000 的 12% 只乘一次是 1200。贷款利息更低，因为每一笔还款都在降低余额。", "10000、年利率 12%、一年：每月 888.49，利息 661.85，總額 10661.85。10000 的 12% 只乘一次是 1200。貸款利息更低，因為每一筆還款都在降低餘額。", "10000 を年 12% で 1 年：毎月 888.49、利息 661.85、総額 10661.85。10000 の 12% を一度だけかけると 1200。ローンの利息はそれより少ない。毎回の返済が残高を減らすから。", "10000을 연 12%로 1년: 매달 888.49, 이자 661.85, 총액 10661.85. 10000의 12%를 한 번만 매기면 1200. 대출 이자는 더 적습니다. 매번 상환이 잔액을 줄이기 때문입니다.", "10000 với 12% một năm: mỗi tháng 888,49, lãi 661,85, tổng 10661,85. 12% của 10000 lấy một lần là 1200. Lãi khoản vay thấp hơn vì mỗi lần trả làm dư nợ giảm.", "10000 pada 12% selama satu tahun: setiap bulan 888,49, bunga 661,85, dan total 10661,85. Dua belas persen dari 10000, sekali, adalah 1200. Bunga pinjaman lebih rendah karena setiap cicilan mengurangi saldo.", "10000 al 12% durante un año: una cuota de 888,49 cada mes, un interés de 661,85 y un total de 10661,85. El doce por ciento de 10000, una sola vez, es 1200. El interés del préstamo es menor porque cada cuota reduce el saldo."),
            "s2t": L("Open the loan page on cv.cm", "打开 cv.cm 的贷款", "打開 cv.cm 的貸款", "cv.cmのローンを開く", "cv.cm 대출을 열기", "Mở khoản vay trên cv.cm", "Buka pinjaman di cv.cm", "Abra el préstamo en cv.cm"),
            "s2b": L("The schedule stays in this tab. The page does not name a lender.", "计算留在当前标签页。这一页不写贷款方。", "計算留在目前分頁。這一頁不寫貸款方。", "計算はこのタブ。貸し手の名は出さない。", "계산은 이 탭에서. 이 페이지는 대출 기관을 적지 않습니다.", "Lịch ở trong tab này. Trang không ghi bên cho vay.", "Jadwal di tab ini. Halaman tidak menyebut pemberi pinjaman.", "El calendario queda en esta pestaña. La página no nombra un prestamista."),
            "s3t": L("Enter principal, annual percent, and years", "填本金、年百分比和年数", "填本金、年百分比和年數", "元金、年パーセント、年数を入れる", "원금, 연 퍼센트, 연수 넣기", "Nhập gốc, phần trăm năm và số năm", "Isi pokok, persen tahunan, dan tahun", "Escriba principal, porcentaje anual y años"),
            "s3b": L("12 in the rate box means 12% a year. The month uses that rate divided by 12. One year is 12 payments. Thirty years is 360 payments. The page rounds years times 12 to a whole number of months.", "利率那一格的 12 表示一年 12%。每个月用的是这个利率除以 12。一年是 12 笔还款。三十年是 360 笔。这一页把年数乘 12，再收成整数个月。", "利率那一格的 12 表示一年 12%。每個月用的是這個利率除以 12。一年是 12 筆還款。三十年是 360 筆。這一頁把年數乘 12，再收成整數個月。", "利率の欄の 12 は年 12%。月はその利率を 12 で割る。1 年は 12 回。30 年は 360 回。年数×12 を整数か月に丸める。", "이율 칸의 12는 연 12%입니다. 달은 그 이율을 12로 나눕니다. 1년은 12회. 30년은 360회. 페이지는 연수 곱하기 12를 정수 개월로 반올림합니다.", "12 trong ô lãi suất nghĩa là 12% một năm. Tháng dùng lãi đó chia 12. Một năm là 12 lần trả. Ba mươi năm là 360 lần. Trang làm tròn số năm nhân 12 thành số tháng nguyên.", "12 di kotak suku berarti 12% setahun. Bulan memakai suku itu dibagi 12. Satu tahun adalah 12 pembayaran. Tiga puluh tahun adalah 360 pembayaran. Halaman membulatkan tahun kali 12 menjadi jumlah bulan utuh.", "12 en la casilla de la tasa significa 12% al año. El mes usa esa tasa dividida entre 12. Un año son 12 cuotas. Treinta años son 360 cuotas. La página redondea los años por 12 a un número entero de meses."),
            "s4t": L("Read payment, interest, and total", "看月供、利息和总额", "看月付、利息和總額", "返済、利息、総額を読む", "상환액, 이자, 총액 읽기", "Đọc khoản trả, lãi và tổng", "Baca cicilan, bunga, dan total", "Lea cuota, interés y total"),
            "s4b": L("All three use two decimals. There is no currency. The payment is the same every month on this page. It is not an amortization table of changing lines.", "三个数都是两位小数。没有货币。这一页的月供每个月相同。它不是一行行变化的摊还表。", "三個數都是兩位小數。沒有貨幣。這一頁的月付每個月相同。它不是一行行變化的攤還表。", "三つとも小数第2位。通貨はない。このページの返済は毎月同じ。変わる行の償還表ではない。", "셋 다 소수 둘째 자리. 통화는 없습니다. 이 페이지의 상환액은 매달 같습니다. 줄마다 달라지는 상각표가 아닙니다.", "Cả ba đều hai chữ số thập phân. Không có đơn vị tiền. Khoản trả trên trang này mỗi tháng như nhau. Không phải bảng trả dần đổi từng dòng.", "Ketiganya dua desimal. Tidak ada mata uang. Cicilan di halaman ini sama setiap bulan. Bukan tabel amortisasi yang berubah tiap baris.", "Los tres van a dos decimales. No hay moneda. La cuota es la misma cada mes en esta página. No es una tabla de amortización con líneas que cambian."),
            "s5t": L("A zero rate divides the principal by the months", "利率为 0 时，本金除以月数", "利率為 0 時，本金除以月數", "利率 0 なら元金を月数で割る", "이율이 0이면 원금을 개월 수로 나눔", "Lãi suất 0 thì chia gốc cho số tháng", "Suku nol membagi pokok dengan jumlah bulan", "Una tasa cero divide el principal entre los meses"),
            "s5b": L("12000 at 0% for one year is a payment of 1000.00, interest of 0.00, and a total of 12000.00. Twelve payments of 1000.00 pay the principal and nothing more.", "12000、利率 0%、一年：月供 1000.00，利息 0.00，总额 12000.00。十二笔 1000.00 只还完本金。", "12000、利率 0%、一年：月付 1000.00，利息 0.00，總額 12000.00。十二筆 1000.00 只還完本金。", "12000 を 0% で 1 年：返済 1000.00、利息 0.00、総額 12000.00。1000.00 を十二回で元金だけを払い終える。", "12000을 0%로 1년: 상환액 1000.00, 이자 0.00, 총액 12000.00. 1000.00을 열두 번 내면 원금만 갚습니다.", "12000 với 0% trong một năm: khoản 1000,00, lãi 0,00, tổng 12000,00. Mười hai lần 1000,00 chỉ trả hết gốc.", "12000 pada 0% selama satu tahun: cicilan 1000,00, bunga 0,00, dan total 12000,00. Dua belas kali 1000,00 hanya melunasi pokok.", "12000 al 0% durante un año: una cuota de 1000,00, un interés de 0,00 y un total de 12000,00. Doce cuotas de 1000,00 pagan el principal y nada más."),
            "s6t": L("A term with no month fails", "化不成一个月的期限会失败", "化不成一個月的期限會失敗", "一か月にならない期間は失敗", "한 달이 안 되는 기간은 실패", "Kỳ hạn không ra một tháng thì thất bại", "Jangka yang tidak menjadi sebulan gagal", "Un plazo que no da un mes falla"),
            "s6b": L("The principal must be above zero. Years times 12 is rounded to a whole number of months, and that number must be at least 1. 0.04 years rounds to 0 months and fails.", "本金必须大于 0。年数乘 12 会收成整数个月，而且至少要有 1 个月。0.04 年收成 0 个月，会失败。", "本金必須大於 0。年數乘 12 會收成整數個月，而且至少要有 1 個月。0.04 年收成 0 個月，會失敗。", "元金は 0 より大きいこと。年数×12 は整数か月に丸められ、その数は 1 以上。0.04 年は 0 か月になり失敗。", "원금은 0보다 커야 합니다. 연수 곱하기 12는 정수 개월로 반올림되고, 그 수는 최소 1. 0.04년은 0개월로 반올림되어 실패합니다.", "Gốc phải lớn hơn 0. Số năm nhân 12 được làm tròn thành số tháng nguyên, và số đó phải ít nhất là 1. 0,04 năm làm tròn thành 0 tháng và thất bại.", "Pokok harus di atas nol. Tahun kali 12 dibulatkan menjadi jumlah bulan utuh, dan jumlah itu minimal 1. 0,04 tahun membulat menjadi 0 bulan dan gagal.", "El principal debe ser mayor que cero. Los años por 12 se redondean a un número entero de meses, y ese número debe ser al menos 1. 0,04 años se redondea a 0 meses y falla."),
            "diagram1": L("10000 at 12% for 1 year: payment 888.49, interest 661.85, not 1200.", "10000、12%、1 年：月供 888.49，利息 661.85，不是 1200。", "10000、12%、1 年：月付 888.49，利息 661.85，不是 1200。", "10000、12%、1 年：返済 888.49、利息 661.85。1200 ではない。", "10000, 12%, 1년: 상환 888.49, 이자 661.85, 1200 아님.", "10000, 12%, 1 năm: trả 888,49, lãi 661,85, không phải 1200.", "10000, 12%, 1 tahun: cicilan 888,49, bunga 661,85, bukan 1200.", "10000 al 12% por 1 año: cuota 888,49, interés 661,85, no 1200."),
            "diagram2": L("12000 at 0% for 1 year is 1000.00 a month and 0.00 interest.", "12000、0%、1 年是每月 1000.00，利息 0.00。", "12000、0%、1 年是每月 1000.00，利息 0.00。", "12000 を 0% で 1 年は毎月 1000.00、利息 0.00。", "12000을 0%로 1년은 매달 1000.00, 이자 0.00.", "12000 với 0% trong 1 năm là 1000,00 mỗi tháng và lãi 0,00.", "12000 pada 0% selama 1 tahun adalah 1000,00 sebulan dan bunga 0,00.", "12000 al 0% por 1 año es 1000,00 al mes e interés 0,00."),
        },
        {
            "q1": L("Can I calculate a loan payment free online?", "可以免费在线算贷款月供吗？", "可以免費線上算貸款月付嗎？", "ローン返済を無料で計算できる？", "대출 상환액을 무료로 계산할 수 있나요?", "Tính khoản trả góp miễn phí online được không?", "Bisa hitung cicilan gratis online?", "¿Puedo calcular una cuota de préstamo gratis en línea?"),
            "a1": L("Yes. cv.cm shows the monthly payment, the interest, and the total in this tab. Nothing is uploaded.", "可以。cv.cm 在当前标签页显示月供、利息和总额。不上传。", "可以。cv.cm 在目前分頁顯示月付、利息和總額。不上傳。", "できる。このタブで毎月の返済、利息、総額を出す。アップロードなし。", "됩니다. 이 탭에서 월 상환액, 이자, 총액을 보여 줍니다. 업로드 없음.", "Được. Hiện khoản tháng, lãi và tổng trong tab này. Không tải lên.", "Ya. Menampilkan cicilan bulanan, bunga, dan total di tab ini. Tidak diunggah.", "Sí. Muestra la cuota mensual, el interés y el total en esta pestaña. Nada se sube."),
            "q2": L("What is the payment on 10000 at 12% for one year?", "10000、年利率 12%、一年，月供是多少？", "10000、年利率 12%、一年，月付是多少？", "10000 を年 12% で 1 年の返済は？", "10000을 연 12%로 1년의 상환액은?", "10000 với 12% một năm thì khoản tháng là bao nhiêu?", "Cicilan 10000 pada 12% selama satu tahun berapa?", "¿Cuál es la cuota de 10000 al 12% durante un año?"),
            "a2": L("888.49 a month. Interest is 661.85 and the total is 10661.85. It is not 1200 of interest.", "每月 888.49。利息 661.85，总额 10661.85。利息不是 1200。", "每月 888.49。利息 661.85，總額 10661.85。利息不是 1200。", "毎月 888.49。利息 661.85、総額 10661.85。利息は 1200 ではない。", "매달 888.49. 이자는 661.85, 총액은 10661.85. 이자가 1200이 아닙니다.", "888,49 mỗi tháng. Lãi 661,85 và tổng 10661,85. Không phải lãi 1200.", "888,49 sebulan. Bunga 661,85 dan total 10661,85. Bukan bunga 1200.", "888,49 al mes. El interés es 661,85 y el total es 10661,85. No son 1200 de interés."),
            "q3": L("What does a zero interest rate do?", "利率为 0 会怎样？", "利率為 0 會怎樣？", "利率 0 だと？", "이율이 0이면?", "Lãi suất 0 thì sao?", "Apa yang dilakukan suku bunga nol?", "¿Qué hace una tasa de interés cero?"),
            "a3": L("It divides the principal by the number of months. 12000 for one year is 1000.00 a month and 0.00 interest.", "它把本金除以月数。12000、一年，是每月 1000.00，利息 0.00。", "它把本金除以月數。12000、一年，是每月 1000.00，利息 0.00。", "元金を月数で割る。12000 を 1 年なら毎月 1000.00、利息 0.00。", "원금을 개월 수로 나눕니다. 12000을 1년은 매달 1000.00, 이자 0.00.", "Nó chia gốc cho số tháng. 12000 trong một năm là 1000,00 mỗi tháng và lãi 0,00.", "Membagi pokok dengan jumlah bulan. 12000 selama satu tahun adalah 1000,00 sebulan dan bunga 0,00.", "Divide el principal entre el número de meses. 12000 durante un año es 1000,00 al mes e interés 0,00."),
            "q4": L("Does 12 in the rate box mean 0.12?", "利率格里的 12 是 0.12 吗？", "利率格裡的 12 是 0.12 嗎？", "利率欄の 12 は 0.12？", "이율 칸의 12는 0.12인가요?", "12 trong ô lãi suất có phải 0,12?", "Apakah 12 di kotak suku berarti 0,12?", "¿El 12 de la casilla de la tasa significa 0,12?"),
            "a4": L("No. 12 means 12% a year. The monthly rate is that percent divided by 12. One year is 12 payments, not one.", "不是。12 表示一年 12%。月利率是这个百分比除以 12。一年是 12 笔还款，不是 1 笔。", "不是。12 表示一年 12%。月利率是這個百分比除以 12。一年是 12 筆還款，不是 1 筆。", "違う。12 は年 12%。月利はそのパーセントを 12 で割る。1 年は 12 回であり 1 回ではない。", "아닙니다. 12는 연 12%입니다. 월 이율은 그 퍼센트를 12로 나눈 값입니다. 1년은 12회이지 1회가 아닙니다.", "Không. 12 nghĩa là 12% một năm. Lãi tháng là phần trăm đó chia 12. Một năm là 12 lần trả, không phải một.", "Tidak. 12 berarti 12% setahun. Suku bulanan adalah persen itu dibagi 12. Satu tahun adalah 12 pembayaran, bukan satu.", "No. 12 significa 12% al año. La tasa mensual es ese porcentaje dividido entre 12. Un año son 12 cuotas, no una."),
            "q5": L("Is the loan uploaded?", "贷款数字会上传吗？", "貸款數字會上傳嗎？", "アップロードされる？", "업로드되나요?", "Số liệu khoản vay có bị tải lên không?", "Apakah angka pinjaman diunggah?", "¿Se sube el préstamo?"),
            "a5": L("No. Closing the tab discards it. The page does not name a lender or a currency.", "不会。关掉标签页就没了。这一页不写贷款方，也不标明货币。", "不會。關掉分頁就沒了。這一頁不寫貸款方，也不標明貨幣。", "しない。タブを閉じると消える。貸し手も通貨も名指ししない。", "아니요. 탭을 닫으면 사라집니다. 이 페이지는 대출 기관도 통화도 적지 않습니다.", "Không. Đóng tab là mất. Trang không ghi bên cho vay hay đơn vị tiền.", "Tidak. Tutup tab, hilang. Halaman tidak menyebut pemberi pinjaman atau mata uang.", "No. Al cerrar la pestaña se pierde. La página no nombra un prestamista ni una moneda."),
        },
    ),
    "read-cron": lesson(
        {
            "name": L("How to read a cron expression", "怎么读 cron 表达式", "怎麼讀 cron 表達式", "cron式の読み方", "cron 식 읽는 법", "Cách đọc biểu thức cron", "Cara baca ekspresi cron", "Cómo leer una expresión cron"),
            "blurb": L("This page reads five fields: minute, hour, day of month, month, and weekday. 0 9 * * 1 is 09:00 on Monday. Sunday is both 0 and 7. MON and a sixth field fail.", "这一页读五个字段：分、时、日、月、星期。0 9 * * 1 是周一 09:00。0 和 7 都是周日。MON 和第六个字段会失败。", "這一頁讀五個欄位：分、時、日、月、星期。0 9 * * 1 是週一 09:00。0 和 7 都是週日。MON 和第六個欄位會失敗。", "このページは五つの欄を読む。分、時、日、月、曜日。0 9 * * 1 は月曜 09:00。0 も 7 も日曜。MON と六つ目の欄は失敗。", "이 페이지는 필드 다섯을 읽습니다. 분, 시, 일, 월, 요일. 0 9 * * 1 은 월요일 09:00. 0과 7은 모두 일요일. MON과 여섯째 필드는 실패합니다.", "Trang này đọc năm trường: phút, giờ, ngày, tháng và thứ. 0 9 * * 1 là 09:00 thứ Hai. 0 và 7 đều là Chủ nhật. MON và trường thứ sáu thì thất bại.", "Halaman ini membaca lima ruas: menit, jam, hari, bulan, dan hari dalam pekan. 0 9 * * 1 adalah 09:00 hari Senin. 0 dan 7 sama-sama Minggu. MON dan ruas keenam gagal.", "Esta página lee cinco campos: minuto, hora, día del mes, mes y día de la semana. 0 9 * * 1 es las 09:00 del lunes. El domingo es 0 y también 7. MON y un sexto campo fallan."),
            "title": L("How to read a cron expression", "怎么读 cron 表达式", "怎麼讀 cron 表達式", "cron式の読み方", "cron 식 읽는 법", "Cách đọc biểu thức cron", "Cara baca ekspresi cron", "Cómo leer una expresión cron"),
            "lead": L("You have a five-field cron expression. You will read what each field names in this tab. The order is minute, hour, day of month, month, weekday. 0 9 * * 1 is minute 0, hour 9, every day of the month, every month, and Monday. The page describes the fields. It does not start the job.", "你有一个五字段的 cron 表达式。在当前标签页看每个字段点了什么。顺序是分、时、日、月、星期。0 9 * * 1 是第 0 分、9 点、每个日、每个月、周一。这一页描述字段。它不启动那份工作。", "你有一個五欄位的 cron 表達式。在目前分頁看每個欄位點了什麼。順序是分、時、日、月、星期。0 9 * * 1 是第 0 分、9 點、每個日、每個月、週一。這一頁描述欄位。它不啟動那份工作。", "五つの欄の cron 式がある。このタブで各欄が何を指すか読む。順は分、時、日、月、曜日。0 9 * * 1 は 0 分、9 時、毎月の毎日、毎月、月曜。ページは欄を説明する。仕事は始めない。", "필드 다섯의 cron 식이 있습니다. 이 탭에서 각 필드가 무엇을 가리키는지 읽으세요. 순서는 분, 시, 일, 월, 요일. 0 9 * * 1 은 0분, 9시, 매월의 매일, 매월, 월요일. 페이지는 필드를 설명합니다. 작업은 시작하지 않습니다.", "Bạn có một biểu thức cron năm trường. Đọc từng trường chỉ gì trong tab này. Thứ tự là phút, giờ, ngày trong tháng, tháng, thứ. 0 9 * * 1 là phút 0, giờ 9, mọi ngày trong tháng, mọi tháng, và thứ Hai. Trang mô tả các trường. Nó không khởi chạy việc.", "Anda punya ekspresi cron lima ruas. Baca apa yang disebut tiap ruas di tab ini. Urutannya menit, jam, hari dalam bulan, bulan, hari dalam pekan. 0 9 * * 1 adalah menit 0, jam 9, setiap hari dalam bulan, setiap bulan, dan Senin. Halaman menjelaskan ruas. Tidak menjalankan pekerjaan.", "Tiene una expresión cron de cinco campos. Lea lo que nombra cada campo aquí. El orden es minuto, hora, día del mes, mes, día de la semana. 0 9 * * 1 es el minuto 0, la hora 9, cada día del mes, cada mes y el lunes. La página describe los campos. No arranca el trabajo."),
            "result": L("An English description of the five fields. Weekday 1 is Monday. Weekday 0 and weekday 7 are both Sunday.", "一行英文说明，点出这五个字段。星期 1 是周一。星期 0 和星期 7 都是周日。", "一行英文說明，點出這五個欄位。星期 1 是週一。星期 0 和星期 7 都是週日。", "五つの欄を英語で説明する一行。曜日 1 は月曜。曜日 0 と曜日 7 はどちらも日曜。", "다섯 필드를 영어로 설명하는 한 줄. 요일 1은 월요일. 요일 0과 요일 7은 모두 일요일.", "Một dòng mô tả tiếng Anh cho năm trường. Thứ 1 là thứ Hai. Thứ 0 và thứ 7 đều là Chủ nhật.", "Satu baris penjelasan bahasa Inggris untuk lima ruas. Hari 1 adalah Senin. Hari 0 dan hari 7 sama-sama Minggu.", "Una descripción en inglés de los cinco campos. El día 1 es lunes. El día 0 y el día 7 son domingo."),
            "note": L("Open cron when the expression is in front of you. Use numbers, stars, commas, and ranges. Words such as MON fail. Nothing is uploaded.", "表达式在眼前再打开 cron。用数字、星号、逗号和范围。MON 这类词会失败。不上传。", "表達式在眼前再開 cron。用數字、星號、逗號和範圍。MON 這類詞會失敗。不上傳。", "式が手元にあってから開く。数字、星、コンマ、範囲を使う。MON のような語は失敗。アップロードなし。", "식이 앞에 있을 때 cron을 여세요. 숫자, 별, 쉼표, 범위를 쓰세요. MON 같은 단어는 실패합니다. 업로드 없음.", "Có biểu thức thì mở cron. Dùng số, sao, dấu phẩy và khoảng. Từ như MON thì thất bại. Không tải lên.", "Ekspresi sudah di depan, baru buka cron. Pakai angka, bintang, koma, dan rentang. Kata seperti MON gagal. Tidak diunggah.", "Abra cron cuando la expresión esté delante. Use números, asteriscos, comas y rangos. Palabras como MON fallan. Nada se sube."),
            "s1t": L("Count five fields, in order", "按顺序数五个字段", "按順序數五個欄位", "五つを順に数える", "다섯 필드를 순서대로 세기", "Đếm năm trường, đúng thứ tự", "Hitung lima ruas, berurutan", "Cuente cinco campos, en orden"),
            "s1b": L("The fields are minute, hour, day of month, month, and weekday. 0 9 * * 1 is minute 0, hour 9, every day of the month, every month, and Monday. A star means every value in that field.", "字段是分、时、日、月、星期。0 9 * * 1 是第 0 分、9 点、每个日、每个月、周一。星号表示该字段的每一个值。", "欄位是分、時、日、月、星期。0 9 * * 1 是第 0 分、9 點、每個日、每個月、週一。星號表示該欄位的每一個值。", "欄は分、時、日、月、曜日。0 9 * * 1 は 0 分、9 時、毎月の毎日、毎月、月曜。星はその欄のすべての値。", "필드는 분, 시, 일, 월, 요일입니다. 0 9 * * 1 은 0분, 9시, 매월의 매일, 매월, 월요일. 별은 그 필드의 모든 값입니다.", "Các trường là phút, giờ, ngày trong tháng, tháng và thứ. 0 9 * * 1 là phút 0, giờ 9, mọi ngày trong tháng, mọi tháng, và thứ Hai. Dấu sao là mọi giá trị của trường đó.", "Ruasnya menit, jam, hari dalam bulan, bulan, dan hari dalam pekan. 0 9 * * 1 adalah menit 0, jam 9, setiap hari dalam bulan, setiap bulan, dan Senin. Bintang berarti setiap nilai di ruas itu.", "Los campos son minuto, hora, día del mes, mes y día de la semana. 0 9 * * 1 es el minuto 0, la hora 9, cada día del mes, cada mes y el lunes. Un asterisco significa cada valor de ese campo."),
            "s2t": L("Open cron on cv.cm", "打开 cv.cm 的 cron", "打開 cv.cm 的 cron", "cv.cmのcronを開く", "cv.cm cron을 열기", "Mở cron trên cv.cm", "Buka cron di cv.cm", "Abra cron en cv.cm"),
            "s2b": L("The expression stays in this tab.", "表达式留在当前标签页。", "表達式留在目前分頁。", "式はこのタブ。", "식은 이 탭에 있습니다.", "Biểu thức ở trong tab này.", "Ekspresi tetap di tab ini.", "La expresión queda en esta pestaña."),
            "s3t": L("Use stars, lists, and ranges", "用星号、列表和范围", "用星號、列表和範圍", "星、リスト、範囲を使う", "별, 목록, 범위 쓰기", "Dùng sao, danh sách và khoảng", "Pakai bintang, daftar, dan rentang", "Use asteriscos, listas y rangos"),
            "s3b": L("*/15 9-17 * * 1-5 is every 15 minutes, hours 9 through 17, every day of the month, every month, and Monday through Friday. 9-17 includes both 9 and 17. 1-5 is Monday through Friday.", "*/15 9-17 * * 1-5 是每 15 分钟，9 点到 17 点，每个日，每个月，周一到周五。9-17 把 9 和 17 都算进去。1-5 是周一到周五。", "*/15 9-17 * * 1-5 是每 15 分鐘，9 點到 17 點，每個日，每個月，週一到週五。9-17 把 9 和 17 都算進去。1-5 是週一到週五。", "*/15 9-17 * * 1-5 は 15 分ごと、9 時から 17 時、毎月の毎日、毎月、月曜から金曜。9-17 は 9 も 17 も含む。1-5 は月曜から金曜。", "*/15 9-17 * * 1-5 는 15분마다, 9시부터 17시까지, 매월의 매일, 매월, 월요일부터 금요일. 9-17은 9와 17을 모두 포함합니다. 1-5는 월요일부터 금요일입니다.", "*/15 9-17 * * 1-5 là mỗi 15 phút, các giờ từ 9 đến 17, mọi ngày trong tháng, mọi tháng, và thứ Hai đến thứ Sáu. 9-17 gồm cả 9 và 17. 1-5 là thứ Hai đến thứ Sáu.", "*/15 9-17 * * 1-5 adalah setiap 15 menit, jam 9 sampai 17, setiap hari dalam bulan, setiap bulan, dan Senin sampai Jumat. 9-17 mencakup 9 dan 17. 1-5 adalah Senin sampai Jumat.", "*/15 9-17 * * 1-5 es cada 15 minutos, las horas de 9 a 17, cada día del mes, cada mes y de lunes a viernes. 9-17 incluye el 9 y el 17. 1-5 es de lunes a viernes."),
            "s4t": L("Remember that Sunday is 0 and 7", "记住周日是 0，也是 7", "記住週日是 0，也是 7", "日曜は 0 でも 7 でもある", "일요일은 0이고 7이기도 함", "Nhớ Chủ nhật là 0 và cũng là 7", "Ingat Minggu adalah 0 dan juga 7", "Recuerde que el domingo es 0 y 7"),
            "s4b": L("Weekday 1 is Monday. Weekday 0 and weekday 7 both come out as Sunday. The word MON fails. Type 1 for Monday.", "星期 1 是周一。星期 0 和星期 7 都得出周日。MON 这个词会失败。周一要写 1。", "星期 1 是週一。星期 0 和星期 7 都得出週日。MON 這個詞會失敗。週一要寫 1。", "曜日 1 は月曜。曜日 0 と曜日 7 はどちらも日曜になる。語の MON は失敗。月曜は 1 と書く。", "요일 1은 월요일. 요일 0과 요일 7은 모두 일요일로 나옵니다. MON이라는 단어는 실패합니다. 월요일은 1로 쓰세요.", "Thứ 1 là thứ Hai. Thứ 0 và thứ 7 đều ra Chủ nhật. Từ MON thì thất bại. Thứ Hai hãy gõ 1.", "Hari 1 adalah Senin. Hari 0 dan hari 7 sama-sama keluar sebagai Minggu. Kata MON gagal. Ketik 1 untuk Senin.", "El día 1 es lunes. El día 0 y el día 7 salen ambos como domingo. La palabra MON falla. Escriba 1 para el lunes."),
            "s5t": L("Reject a minute of 60 and a sixth field", "第 60 分和第六个字段都会被拒绝", "第 60 分和第六個欄位都會被拒絕", "60 分も六つ目の欄も拒む", "60분과 여섯째 필드는 거절", "Phút 60 và trường thứ sáu đều bị từ chối", "Menit 60 dan ruas keenam ditolak", "Rechace el minuto 60 y un sexto campo"),
            "s5b": L("Minutes run from 0 to 59. Hours run from 0 to 23. Days run from 1 to 31. Months run from 1 to 12. Weekdays run from 0 to 7. 60 * * * * fails. 0 9 * * * * has six fields and fails. There is no seconds field.", "分是 0 到 59。时是 0 到 23。日是 1 到 31。月是 1 到 12。星期是 0 到 7。60 * * * * 会失败。0 9 * * * * 有六个字段，会失败。没有秒这一字段。", "分是 0 到 59。時是 0 到 23。日是 1 到 31。月是 1 到 12。星期是 0 到 7。60 * * * * 會失敗。0 9 * * * * 有六個欄位，會失敗。沒有秒這一欄位。", "分は 0 から 59。時は 0 から 23。日は 1 から 31。月は 1 から 12。曜日は 0 から 7。60 * * * * は失敗。0 9 * * * * は六つの欄で失敗。秒の欄はない。", "분은 0부터 59. 시는 0부터 23. 일은 1부터 31. 월은 1부터 12. 요일은 0부터 7. 60 * * * * 는 실패합니다. 0 9 * * * * 는 필드가 여섯이라 실패합니다. 초 필드는 없습니다.", "Phút từ 0 đến 59. Giờ từ 0 đến 23. Ngày từ 1 đến 31. Tháng từ 1 đến 12. Thứ từ 0 đến 7. 60 * * * * thì thất bại. 0 9 * * * * có sáu trường và thất bại. Không có trường giây.", "Menit dari 0 sampai 59. Jam dari 0 sampai 23. Hari dari 1 sampai 31. Bulan dari 1 sampai 12. Hari dalam pekan dari 0 sampai 7. 60 * * * * gagal. 0 9 * * * * punya enam ruas dan gagal. Tidak ada ruas detik.", "Los minutos van de 0 a 59. Las horas van de 0 a 23. Los días van de 1 a 31. Los meses van de 1 a 12. Los días de la semana van de 0 a 7. 60 * * * * falla. 0 9 * * * * tiene seis campos y falla. No hay un campo de segundos."),
            "s6t": L("Read the description, then leave the job unrun", "读完说明，先不要跑那份工作", "讀完說明，先不要跑那份工作", "説明を読んで、仕事はまだ走らせない", "설명을 읽고, 작업은 아직 실행하지 않기", "Đọc phần mô tả, rồi chưa chạy việc", "Baca penjelasannya, lalu jangan jalankan pekerjaannya", "Lea la descripción y deje el trabajo sin arrancar"),
            "s6b": L("The line is in English: minute, hour, day-of-month, and names such as monday. When both the day of the month and the weekday are restricted, this page still names both. It does not choose between them, and it does not run anything.", "这一行是英文：minute、hour、day-of-month，以及 monday 这类名字。日和星期都被限制时，这一页仍把两个都点出来。它不在两者之间做选择，也不运行任何东西。", "這一行是英文：minute、hour、day-of-month，以及 monday 這類名字。日和星期都被限制時，這一頁仍把兩個都點出來。它不在兩者之間做選擇，也不執行任何東西。", "行は英語。minute、hour、day-of-month、monday のような名前。日と曜日の両方が限られていても、このページは両方を名指しする。どちらかを選ばず、何も実行しない。", "그 줄은 영어입니다. minute, hour, day-of-month, 그리고 monday 같은 이름. 일과 요일이 모두 제한되어도 이 페이지는 둘 다 이름을 붙입니다. 둘 중 하나를 고르지 않고, 아무것도 실행하지 않습니다.", "Dòng đó bằng tiếng Anh: minute, hour, day-of-month, và tên như monday. Khi cả ngày trong tháng và thứ đều bị giới hạn, trang này vẫn gọi tên cả hai. Nó không chọn một trong hai, và không chạy gì.", "Baris itu dalam bahasa Inggris: minute, hour, day-of-month, dan nama seperti monday. Saat hari dalam bulan dan hari dalam pekan sama-sama dibatasi, halaman ini tetap menamai keduanya. Tidak memilih salah satu, dan tidak menjalankan apa pun.", "La línea está en inglés: minute, hour, day-of-month y nombres como monday. Cuando el día del mes y el día de la semana están ambos limitados, esta página sigue nombrando los dos. No elige entre ellos y no ejecuta nada."),
            "diagram1": L("Five fields: minute, hour, day of month, month, weekday. 0 9 * * 1 is Monday at 09:00.", "五个字段：分、时、日、月、星期。0 9 * * 1 是周一 09:00。", "五個欄位：分、時、日、月、星期。0 9 * * 1 是週一 09:00。", "五つの欄：分、時、日、月、曜日。0 9 * * 1 は月曜 09:00。", "필드 다섯: 분, 시, 일, 월, 요일. 0 9 * * 1 은 월요일 09:00.", "Năm trường: phút, giờ, ngày, tháng, thứ. 0 9 * * 1 là thứ Hai lúc 09:00.", "Lima ruas: menit, jam, hari, bulan, hari dalam pekan. 0 9 * * 1 adalah Senin pukul 09:00.", "Cinco campos: minuto, hora, día del mes, mes, día de la semana. 0 9 * * 1 es el lunes a las 09:00."),
            "diagram2": L("Sunday is 0 and 7. MON fails. Six fields fail.", "周日是 0 和 7。MON 会失败。六个字段会失败。", "週日是 0 和 7。MON 會失敗。六個欄位會失敗。", "日曜は 0 と 7。MON は失敗。六つの欄は失敗。", "일요일은 0과 7. MON은 실패. 여섯 필드는 실패.", "Chủ nhật là 0 và 7. MON thì thất bại. Sáu trường thì thất bại.", "Minggu adalah 0 dan 7. MON gagal. Enam ruas gagal.", "El domingo es 0 y 7. MON falla. Seis campos fallan."),
        },
        {
            "q1": L("Can I read a cron expression free online?", "可以免费在线读 cron 表达式吗？", "可以免費線上讀 cron 表達式嗎？", "cron式を無料で読める？", "cron 식을 무료로 읽을 수 있나요?", "Đọc biểu thức cron miễn phí online được không?", "Bisa baca ekspresi cron gratis online?", "¿Puedo leer una expresión cron gratis en línea?"),
            "a1": L("Yes. cv.cm describes the five fields in this tab. Nothing is uploaded, and the job is not started.", "可以。cv.cm 在当前标签页描述这五个字段。不上传，也不启动那份工作。", "可以。cv.cm 在目前分頁描述這五個欄位。不上傳，也不啟動那份工作。", "できる。このタブで五つの欄を説明する。アップロードせず、仕事も始めない。", "됩니다. 이 탭에서 다섯 필드를 설명합니다. 업로드하지 않고, 작업도 시작하지 않습니다.", "Được. Mô tả năm trường trong tab này. Không tải lên, và không khởi chạy việc.", "Ya. Menjelaskan lima ruas di tab ini. Tidak diunggah, dan pekerjaan tidak dijalankan.", "Sí. Describe los cinco campos en esta pestaña. Nada se sube y el trabajo no se arranca."),
            "q2": L("What does 0 9 * * 1 mean?", "0 9 * * 1 是什么意思？", "0 9 * * 1 是什麼意思？", "0 9 * * 1 は何？", "0 9 * * 1 은 무슨 뜻인가요?", "0 9 * * 1 nghĩa là gì?", "Apa arti 0 9 * * 1?", "¿Qué significa 0 9 * * 1?"),
            "a2": L("Minute 0, hour 9, every day of the month, every month, and Monday.", "第 0 分、9 点、每个日、每个月、周一。", "第 0 分、9 點、每個日、每個月、週一。", "0 分、9 時、毎月の毎日、毎月、月曜。", "0분, 9시, 매월의 매일, 매월, 월요일.", "Phút 0, giờ 9, mọi ngày trong tháng, mọi tháng, và thứ Hai.", "Menit 0, jam 9, setiap hari dalam bulan, setiap bulan, dan Senin.", "Minuto 0, hora 9, cada día del mes, cada mes y lunes."),
            "q3": L("Which number is Sunday?", "哪个数字是周日？", "哪個數字是週日？", "日曜はどの数字？", "일요일은 어떤 숫자인가요?", "Số nào là Chủ nhật?", "Angka berapa yang Minggu?", "¿Qué número es el domingo?"),
            "a3": L("0 and 7. Monday is 1. The word MON fails.", "0 和 7。周一是 1。MON 这个词会失败。", "0 和 7。週一是 1。MON 這個詞會失敗。", "0 と 7。月曜は 1。語の MON は失敗。", "0과 7. 월요일은 1. MON이라는 단어는 실패합니다.", "0 và 7. Thứ Hai là 1. Từ MON thì thất bại.", "0 dan 7. Senin adalah 1. Kata MON gagal.", "0 y 7. El lunes es 1. La palabra MON falla."),
            "q4": L("Why did a six-field expression fail?", "为什么六个字段会失败？", "為什麼六個欄位會失敗？", "なぜ六つの欄は失敗する？", "왜 여섯 필드가 실패하나요?", "Sao biểu thức sáu trường lại thất bại?", "Kenapa ekspresi enam ruas gagal?", "¿Por qué falló una expresión de seis campos?"),
            "a4": L("This page wants exactly five fields. There is no seconds field. Minute 60 also fails, because minutes stop at 59.", "这一页只要正好五个字段。没有秒这一字段。第 60 分也会失败，因为分只到 59。", "這一頁只要正好五個欄位。沒有秒這一欄位。第 60 分也會失敗，因為分只到 59。", "このページはちょうど五つの欄。秒の欄はない。60 分も失敗する。分は 59 まで。", "이 페이지는 필드가 정확히 다섯이어야 합니다. 초 필드는 없습니다. 60분도 실패합니다. 분은 59까지입니다.", "Trang này cần đúng năm trường. Không có trường giây. Phút 60 cũng thất bại, vì phút dừng ở 59.", "Halaman ini meminta tepat lima ruas. Tidak ada ruas detik. Menit 60 juga gagal, karena menit berhenti di 59.", "Esta página quiere exactamente cinco campos. No hay un campo de segundos. El minuto 60 también falla, porque los minutos terminan en 59."),
            "q5": L("Is the expression uploaded?", "表达式会上传吗？", "表達式會上傳嗎？", "アップロードされる？", "업로드되나요?", "Biểu thức có bị tải lên không?", "Apakah ekspresinya diunggah?", "¿Se sube la expresión?"),
            "a5": L("No. Closing the tab discards it. The page does not run the schedule.", "不会。关掉标签页就没了。这一页不运行这份日程。", "不會。關掉分頁就沒了。這一頁不執行這份日程。", "しない。タブを閉じると消える。ページは予定を実行しない。", "아니요. 탭을 닫으면 사라집니다. 이 페이지는 일정을 실행하지 않습니다.", "Không. Đóng tab là mất. Trang không chạy lịch.", "Tidak. Tutup tab, hilang. Halaman tidak menjalankan jadwal.", "No. Al cerrar la pestaña se pierde. La página no ejecuta el horario."),
        },
    ),
}

META = {
    "titleCalculateBmi": L("How to calculate BMI | cv.cm", "怎么算 BMI | cv.cm", "怎麼算 BMI | cv.cm", "BMIの計算方法 | cv.cm", "BMI 계산하는 법 | cv.cm", "Cách tính BMI | cv.cm", "Cara hitung BMI | cv.cm", "Cómo calcular el IMC | cv.cm"),
    "descCalculateBmi": L("70 kg and 170 cm is a BMI of 24.2, Normal. 1.70 in the centimetre box is 242214.5. 18.5 is Normal, 25 is Overweight, and 30 is Obesity. Nothing is uploaded.", "70 公斤、170 厘米是 BMI 24.2，Normal。厘米那一格填 1.70 会得到 242214.5。18.5 是 Normal，25 是 Overweight，30 是 Obesity。不上传。", "70 公斤、170 公分是 BMI 24.2，Normal。公分那一格填 1.70 會得到 242214.5。18.5 是 Normal，25 是 Overweight，30 是 Obesity。不上傳。", "70 kg と 170 cm は BMI 24.2、Normal。センチの欄の 1.70 は 242214.5。18.5 は Normal、25 は Overweight、30 は Obesity。アップロードなし。", "70 kg와 170 cm는 BMI 24.2, Normal. 센티미터 칸의 1.70은 242214.5. 18.5는 Normal, 25는 Overweight, 30은 Obesity. 업로드 없음.", "70 kg và 170 cm là BMI 24,2, Normal. 1,70 trong ô xentimét là 242214,5. 18,5 là Normal, 25 là Overweight, 30 là Obesity. Không tải lên.", "70 kg dan 170 cm adalah BMI 24,2, Normal. 1,70 di kotak sentimeter adalah 242214,5. 18,5 adalah Normal, 25 adalah Overweight, 30 adalah Obesity. Tidak diunggah.", "70 kg y 170 cm es un IMC de 24,2, Normal. 1,70 en la casilla de centímetros es 242214,5. 18,5 es Normal, 25 es Overweight y 30 es Obesity. Nada se sube."),
    "titleSplitTip": L("How to split a tip | cv.cm", "怎么分小费 | cv.cm", "怎麼分小費 | cv.cm", "チップの割り方 | cv.cm", "팁 나누는 법 | cv.cm", "Cách chia tiền tip | cv.cm", "Cara bagi tip | cv.cm", "Cómo repartir una propina | cv.cm"),
    "descSplitTip": L("100 at 20% for 4 people is a tip of 20.00, a total of 120.00, and 30.00 each. Each splits the whole bill. 2.9 people counts as 2. Nothing is uploaded.", "100 的 20%，4 人：小费 20.00，合计 120.00，每人 30.00。每人分的是整张账单。2.9 个人按 2 个人算。不上传。", "100 的 20%，4 人：小費 20.00，合計 120.00，每人 30.00。每人分的是整張帳單。2.9 個人按 2 個人算。不上傳。", "100 の 20% を 4 人：チップ 20.00、合計 120.00、一人 30.00。割るのは勘定全体。2.9 人は 2 人。アップロードなし。", "100의 20%, 4명: 팁 20.00, 합계 120.00, 각자 30.00. 각자 나누는 것은 계산서 전체. 2.9명은 2명. 업로드 없음.", "100 với 20% cho 4 người: tip 20,00, tổng 120,00, mỗi người 30,00. Mỗi người chia cả hóa đơn. 2,9 người tính là 2. Không tải lên.", "100 dengan 20% untuk 4 orang: tip 20,00, total 120,00, masing-masing 30,00. Setiap orang membagi seluruh tagihan. 2,9 orang dihitung 2. Tidak diunggah.", "100 con un 20% para 4 personas: propina 20,00, total 120,00, cada uno 30,00. Cada persona reparte la cuenta entera. 2,9 personas cuentan como 2. Nada se sube."),
    "titleLoanPayment": L("How to calculate a loan payment | cv.cm", "怎么算贷款月供 | cv.cm", "怎麼算貸款月付 | cv.cm", "ローン返済額の計算方法 | cv.cm", "대출 상환액 계산하는 법 | cv.cm", "Cách tính khoản trả góp | cv.cm", "Cara hitung cicilan | cv.cm", "Cómo calcular la cuota de un préstamo | cv.cm"),
    "descLoanPayment": L("10000 at 12% for one year is 888.49 a month. Interest is 661.85, not 1200. 12000 at 0% for one year is 1000.00 a month. Nothing is uploaded.", "10000、年利率 12%、一年，每月 888.49。利息是 661.85，不是 1200。12000、利率 0%、一年，每月 1000.00。不上传。", "10000、年利率 12%、一年，每月 888.49。利息是 661.85，不是 1200。12000、利率 0%、一年，每月 1000.00。不上傳。", "10000 を年 12% で 1 年は毎月 888.49。利息は 661.85 であり 1200 ではない。12000 を 0% で 1 年は毎月 1000.00。アップロードなし。", "10000을 연 12%로 1년은 매달 888.49. 이자는 661.85이고 1200이 아닙니다. 12000을 0%로 1년은 매달 1000.00. 업로드 없음.", "10000 với 12% một năm là 888,49 mỗi tháng. Lãi là 661,85, không phải 1200. 12000 với 0% một năm là 1000,00 mỗi tháng. Không tải lên.", "10000 pada 12% selama satu tahun adalah 888,49 sebulan. Bunga 661,85, bukan 1200. 12000 pada 0% selama satu tahun adalah 1000,00 sebulan. Tidak diunggah.", "10000 al 12% durante un año es 888,49 al mes. El interés es 661,85, no 1200. 12000 al 0% durante un año es 1000,00 al mes. Nada se sube."),
    "titleReadCron": L("How to read a cron expression | cv.cm", "怎么读 cron 表达式 | cv.cm", "怎麼讀 cron 表達式 | cv.cm", "cron式の読み方 | cv.cm", "cron 식 읽는 법 | cv.cm", "Cách đọc biểu thức cron | cv.cm", "Cara baca ekspresi cron | cv.cm", "Cómo leer una expresión cron | cv.cm"),
    "descReadCron": L("Five fields: minute, hour, day of month, month, weekday. 0 9 * * 1 is Monday at 09:00. Sunday is 0 and 7. MON and six fields fail. Nothing is uploaded.", "五个字段：分、时、日、月、星期。0 9 * * 1 是周一 09:00。周日是 0 和 7。MON 和六个字段会失败。不上传。", "五個欄位：分、時、日、月、星期。0 9 * * 1 是週一 09:00。週日是 0 和 7。MON 和六個欄位會失敗。不上傳。", "五つの欄：分、時、日、月、曜日。0 9 * * 1 は月曜 09:00。日曜は 0 と 7。MON と六つの欄は失敗。アップロードなし。", "필드 다섯: 분, 시, 일, 월, 요일. 0 9 * * 1 은 월요일 09:00. 일요일은 0과 7. MON과 여섯 필드는 실패. 업로드 없음.", "Năm trường: phút, giờ, ngày, tháng, thứ. 0 9 * * 1 là thứ Hai lúc 09:00. Chủ nhật là 0 và 7. MON và sáu trường thì thất bại. Không tải lên.", "Lima ruas: menit, jam, hari, bulan, hari dalam pekan. 0 9 * * 1 adalah Senin pukul 09:00. Minggu adalah 0 dan 7. MON dan enam ruas gagal. Tidak diunggah.", "Cinco campos: minuto, hora, día del mes, mes, día de la semana. 0 9 * * 1 es el lunes a las 09:00. El domingo es 0 y 7. MON y seis campos fallan. Nada se sube."),
}


def inject() -> None:
    if set(LESSONS) != {"calculate-bmi", "split-tip", "loan-payment", "read-cron"}:
        raise SystemExit("ids")
    for loc, path in FILES.items():
        data = json.loads(path.read_text())
        data["faq"].setdefault("learn", {})
        for lesson_id, payload in LESSONS.items():
            data["learn"][lesson_id] = payload["copy"][loc]
            data["faq"]["learn"][lesson_id] = payload["faq"][loc]
        for key, by_loc in META.items():
            data["meta"][key] = by_loc[loc]
        path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n")
        print("patched", path.name)


if __name__ == "__main__":
    inject()
