#!/usr/bin/env python3
"""Inject signature, screenshot, invoice, and password how-tos."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LOCS = ["en", "zh-CN", "zh-TW", "ja", "ko", "vi", "id", "es"]
FILES = {loc: ROOT / "src/locales" / f"{loc}.json" for loc in LOCS}


def L(*vals: str) -> dict[str, str]:
    if len(vals) != 8:
        raise ValueError(len(vals), vals[0] if vals else None)
    return dict(zip(LOCS, vals))


def lesson(fields: dict[str, dict[str, str]], faq: dict[str, dict[str, str]]) -> dict:
    return {
        "copy": {loc: {k: v[loc] for k, v in fields.items()} for loc in LOCS},
        "faq": {loc: {k: v[loc] for k, v in faq.items()} for loc in LOCS},
    }


LESSONS = {
    "make-signature": lesson(
        {
            "name": L("How to draw a signature PNG", "怎么手写签名 PNG", "怎麼手寫簽名 PNG", "署名PNGの描き方", "서명 PNG 그리는 법", "Cách vẽ chữ ký PNG", "Cara gambar tanda tangan PNG", "Cómo dibujar una firma PNG"),
            "blurb": L("Draw on the pad, download a cropped PNG, then check it at the size of the form. Not a legal e-sign.", "在板上写，下载裁好的 PNG，再按表单那么大看一眼。这不是法律电子签。", "在板上寫，下載裁好的 PNG，再按表單那麼大看一眼。這不是法律電子簽。", "パッドに書き、切り抜いたPNGを保存し、フォームの大きさで見る。法的な電子署名ではない。", "패드에 쓰고 자른 PNG를 받은 뒤 서류 크기로 보세요. 법적 전자서명이 아닙니다.", "Vẽ trên bảng, tải PNG đã cắt, xem cỡ form. Không phải chữ ký điện tử pháp lý.", "Gambar di pad, unduh PNG terpotong, cek seukuran formulir. Bukan e-sign legal.", "Dibuje en la almohadilla, descargue un PNG recortado y mírelo al tamaño del formulario. No es una firma electrónica legal."),
            "title": L("How to draw a signature PNG", "怎么手写签名 PNG", "怎麼手寫簽名 PNG", "署名PNGの描き方", "서명 PNG 그리는 법", "Cách vẽ chữ ký PNG", "Cara gambar tanda tangan PNG", "Cómo dibujar una firma PNG"),
            "lead": L("You need a picture of your name, not a legally binding e-sign. You will draw in this tab, download a PNG cropped to the ink, and check it at the size of the box on the form.", "你要的是名字的图，不是有法律效力的电子签。在当前标签页写，下载按墨迹裁好的 PNG，再按表单格子那么大看。", "你要的是名字的圖，不是有法律效力的電子簽。在目前分頁寫，下載按墨跡裁好的 PNG，再按表單格子那麼大看。", "欲しいのは名前の絵であり、法的な電子署名ではない。このタブで書き、インクに合わせて切ったPNGを保存し、欄の大きさで見る。", "필요한 것은 이름의 그림이지 법적 전자서명이 아닙니다. 이 탭에서 쓰고 잉크에 맞춰 자른 PNG를 받은 뒤 서류 칸 크기로 보세요.", "Bạn cần ảnh chữ tên, không phải chữ ký điện tử có hiệu lực. Vẽ trong tab này, tải PNG cắt theo nét, xem cỡ ô trên form.", "Anda butuh gambar nama, bukan e-sign yang mengikat. Gambar di tab ini, unduh PNG terpotong ke tinta, cek seukuran kotak formulir.", "Necesita una imagen de su nombre, no una firma electrónica vinculante. Dibuje aquí, descargue un PNG recortado a la tinta y mírelo al tamaño de la casilla."),
            "result": L("A PNG cropped to the ink, readable at form size, that is not a legal e-sign.", "一份按墨迹裁好的 PNG，表单那么大仍能认，不是法律电子签。", "一份按墨跡裁好的 PNG，表單那麼大仍能認，不是法律電子簽。", "インクに合わせて切ったPNG。欄の大きさで読める。法的な電子署名ではない。", "잉크에 맞춰 자른 PNG. 서류 크기에서도 읽힘. 법적 전자서명 아님.", "PNG cắt theo nét, đọc được cỡ form, không phải chữ ký điện tử pháp lý.", "PNG terpotong ke tinta, kebaca seukuran formulir, bukan e-sign legal.", "Un PNG recortado a la tinta, legible al tamaño del formulario, que no es una firma electrónica legal."),
            "note": L("Open signature when you are ready to draw. The preview pad is cream; the PNG is cropped to the ink with a clear background. Not a legal e-sign and not a stamp on a PDF. Nothing is uploaded.", "准备好再打开签名。预览板是米色；下载的 PNG 按墨迹裁切，底是透明的。不是法律电子签，也不会盖到 PDF 上。不上传。", "準備好再打開簽名。預覽板是米色；下載的 PNG 按墨跡裁切，底是透明的。不是法律電子簽，也不會蓋到 PDF 上。不上傳。", "書く準備ができてから開く。プレビューはクリーム。PNGはインクに切り抜き透明。法的電子署名ではなく、PDFに押すスタンプでもない。アップロードなし。", "쓸 준비가 되면 서명을 여세요. 미리보기는 크림색. PNG는 잉크에 맞춰 잘리고 배경이 투명합니다. 법적 전자서명이 아니고 PDF에 찍는 도장도 아닙니다. 업로드 없음.", "Sẵn sàng vẽ thì mở chữ ký. Bảng xem trước màu kem; PNG cắt theo nét, nền trong. Không phải chữ ký điện tử pháp lý, cũng không đóng lên PDF. Không tải lên.", "Siap menggambar, baru buka tanda tangan. Pad pratinjau krem; PNG terpotong ke tinta, latar tembus. Bukan e-sign legal, bukan cap di PDF. Tidak diunggah.", "Abra firma cuando vaya a dibujar. La almohadilla es crema; el PNG se recorta a la tinta con fondo transparente. No es e-sign legal ni un sello en un PDF. Nada se sube."),
            "s1t": L("Know this is a picture, not a legal e-sign", "先知道这是一张图，不是法律电子签", "先知道這是一張圖，不是法律電子簽", "絵であり法的電子署名ではない", "그림이지 법적 전자서명이 아님", "Đây là ảnh, không phải chữ ký điện tử pháp lý", "Ini gambar, bukan e-sign legal", "Sepa que es una imagen, no una firma electrónica legal"),
            "s1b": L("Banks and governments want a qualified e-sign or a wet signature. This PNG is for a form that asks you to paste an image of your name. It does not bind a PDF.", "银行和政府要的是合格电子签或手写原件。这张 PNG 是给「请贴一张名字图」的表单。它不会给 PDF 赋予效力。", "銀行和政府要的是合格電子簽或手寫原件。這張 PNG 是給「請貼一張名字圖」的表單。它不會給 PDF 賦予效力。", "銀行や行政は適格電子署名か直筆。このPNGは「名前の画像を貼れ」という欄用。PDFを拘束しない。", "은행과 정부는 적격 전자서명이나 원본 서명을 원합니다. 이 PNG는 이름 그림을 붙이라는 서류용입니다. PDF를 구속하지 않습니다.", "Ngân hàng và chính phủ cần chữ ký điện tử đủ điều kiện hoặc chữ ướt. PNG này cho form bảo dán ảnh tên. Nó không ràng PDF.", "Bank dan pemerintah minta e-sign berkualitas atau basah. PNG ini untuk formulir yang minta tempel gambar nama. Tidak mengikat PDF.", "Bancos y administraciones piden e-sign cualificada o tinta. Este PNG es para un formulario que pide pegar una imagen del nombre. No vincula un PDF."),
            "s2t": L("Open signature on cv.cm", "打开 cv.cm 的签名", "打開 cv.cm 的簽名", "cv.cmの署名を開く", "cv.cm 서명을 열기", "Mở chữ ký trên cv.cm", "Buka tanda tangan di cv.cm", "Abra firma en cv.cm"),
            "s2b": L("Drawing stays in this tab.", "书写留在当前标签页。", "書寫留在目前分頁。", "このタブで書く。", "이 탭에서 씁니다.", "Vẽ trong tab này.", "Gambar di tab ini.", "El trazo queda en esta pestaña."),
            "s3t": L("Draw with a finger, a stylus, or a mouse", "用手指、手写笔或鼠标写", "用手指、手寫筆或滑鼠寫", "指、スタイラス、マウスで書く", "손가락, 스타일러스 또는 마우스로 쓰기", "Vẽ bằng ngón, bút hoặc chuột", "Gambar dengan jari, stylus, atau mouse", "Dibuje con el dedo, un lápiz o el ratón"),
            "s3b": L("One continuous name is easier to crop than scattered initials. Undo the last stroke if a loop went wrong. A mouse is worse than a finger.", "连笔的名字比散开的缩写好裁。一笔写坏了就撤销。鼠标不如手指。", "連筆的名字比散開的縮寫好裁。一筆寫壞了就撤銷。滑鼠不如手指。", "つながった名前の方が切りやすい。失敗したらUndo。マウスより指。", "이어 쓴 이름이 흩어진 이니셜보다 자르기 쉽습니다. 한 획이 틀리면 실행 취소. 마우스보다 손가락.", "Tên liền nét dễ cắt hơn chữ cái rời. Nét sai thì hoàn tác. Chuột kém hơn ngón.", "Nama nyambung lebih mudah dipotong daripada inisial. Stroke salah: undo. Mouse lebih buruk daripada jari.", "Un nombre continuo se recorta mejor que iniciales sueltas. Deshaga el último trazo si falló. El ratón es peor que el dedo."),
            "s4t": L("Download the PNG", "下载 PNG", "下載 PNG", "PNGを保存", "PNG 받기", "Tải PNG", "Unduh PNG", "Descargue el PNG"),
            "s4b": L("Export crops to the ink and drops the cream pad. The background is clear. If the download is empty, you had no strokes.", "导出会按墨迹裁切，米色底板不要了。背景是透明的。下载是空的，就是还没写。", "匯出會按墨跡裁切，米色底板不要了。背景是透明的。下載是空的，就是還沒寫。", "書き出しはインクに切り、クリームのパッドは捨てる。背景は透明。空ならまだ書いていない。", "보내면 잉크에 맞춰 자르고 크림색 패드는 버립니다. 배경은 투명. 받은 파일이 비면 아직 안 쓴 것입니다.", "Xuất cắt theo nét, bỏ bảng kem. Nền trong. Tải trống thì chưa vẽ.", "Ekspor memotong ke tinta dan membuang pad krem. Latar tembus. Kosong: belum menggambar.", "Exportar recorta a la tinta y tira la almohadilla crema. El fondo es transparente. Si la descarga está vacía, no había trazos."),
            "s5t": L("Open it at the size of the form box", "按表单格子那么大打开看", "按表單格子那麼大打開看", "欄の大きさで開く", "서류 칸 크기로 열기", "Mở cỡ ô trên form", "Buka seukuran kotak formulir", "Ábralo al tamaño de la casilla"),
            "s5b": L("A signature that only reads full-screen will smear in a 200-pixel box. If it is too thin, draw again thicker. Keep the PNG; do not photograph the pad.", "只有全屏才看得清，塞进 200 像素的格子就会糊。太细就加粗再写。留着 PNG，不要给写字板拍照。", "只有全螢幕才看得清，塞進 200 像素的格子就會糊。太細就加粗再寫。留著 PNG，不要給寫字板拍照。", "全画面でしか読めないなら200pxの欄で潰れる。細いなら太く描き直す。PNGを残す。パッドを撮らない。", "전체 화면에서만 읽히면 200픽셀 칸에서 뭉개집니다. 너무 가늘면 굵게 다시 쓰세요. PNG를 남기세요. 패드를 찍지 마세요.", "Chỉ đọc được full màn hình thì nhét ô 200 pixel sẽ nhòe. Mỏng quá thì vẽ đậm lại. Giữ PNG; đừng chụp bảng.", "Hanya kebaca full screen: buram di kotak 200 piksel. Terlalu tipis: gambar lebih tebal. Simpan PNG; jangan foto pad.", "Si solo se lee a pantalla completa, se correrá en una casilla de 200 px. Si está fino, dibuje más grueso. Conserve el PNG; no fotografíe la almohadilla."),
            "s6t": L("Do not treat this as a signed PDF", "别把它当成签过的 PDF", "別把它當成簽過的 PDF", "署名済みPDFだと思わない", "서명된 PDF로 여기지 마세요", "Đừng coi đây là PDF đã ký", "Jangan anggap ini PDF tertandatangan", "No lo trate como un PDF firmado"),
            "s6b": L("If the destination wants a signature on a PDF page, that is a different job. Paste the PNG only where the form asks for an image.", "对方要的是盖在 PDF 页上的签，那是另一件事。只有表单要贴图时才贴这张 PNG。", "對方要的是蓋在 PDF 頁上的簽，那是另一件事。只有表單要貼圖時才貼這張 PNG。", "PDFのページに署名を置け、は別仕事。画像を貼れと言われた欄にだけこのPNGを使う。", "PDF 페이지에 서명을 올리라는 건 다른 일입니다. 서류가 그림을 붙이라고 할 때만 이 PNG를 붙이세요.", "Đích cần chữ trên trang PDF thì là việc khác. Chỉ dán PNG khi form hỏi ảnh.", "Kalau tujuan minta tanda di halaman PDF, itu kerja lain. Tempel PNG hanya jika formulir minta gambar.", "Si el destino pide una firma sobre una página PDF, es otro trabajo. Pegue el PNG solo donde el formulario pide una imagen."),
            "diagram1": L("This is a picture of a name. It is not a legal e-sign and it does not bind a PDF.", "这是名字的图。不是法律电子签，也不会给 PDF 赋予效力。", "這是名字的圖。不是法律電子簽，也不會給 PDF 賦予效力。", "名前の絵。法的電子署名ではなくPDFを拘束しない。", "이름의 그림. 법적 전자서명이 아니고 PDF를 구속하지 않습니다.", "Ảnh chữ tên. Không phải chữ ký điện tử pháp lý, không ràng PDF.", "Gambar nama. Bukan e-sign legal, tidak mengikat PDF.", "Una imagen del nombre. No es e-sign legal y no vincula un PDF."),
            "diagram2": L("Export crops to the ink. The PNG background is clear. Check it at form size.", "导出会按墨迹裁切。PNG 底是透明的。按表单那么大看。", "匯出會按墨跡裁切。PNG 底是透明的。按表單那麼大看。", "書き出しはインクに切る。PNGの背景は透明。欄の大きさで見る。", "보내면 잉크에 맞춰 자릅니다. PNG 배경은 투명. 서류 크기로 보세요.", "Xuất cắt theo nét. Nền PNG trong. Xem cỡ form.", "Ekspor memotong ke tinta. Latar PNG tembus. Cek seukuran formulir.", "Exportar recorta a la tinta. El fondo del PNG es transparente. Mírelo al tamaño del formulario."),
        },
        {
            "q1": L("Can I draw a signature free online?", "可以免费在线手写签名吗？", "可以免費線上手寫簽名嗎？", "署名を無料で描ける？", "서명을 무료로 그릴 수 있나요?", "Vẽ chữ ký miễn phí online được không?", "Bisa gambar tanda tangan gratis online?", "¿Puedo dibujar una firma gratis en línea?"),
            "a1": L("Yes. cv.cm draws in this tab. Nothing is uploaded. It is not a legal e-sign.", "可以。cv.cm 在当前标签页画，不上传。不是法律电子签。", "可以。cv.cm 在目前分頁畫，不上傳。不是法律電子簽。", "できる。このタブで描く。アップロードなし。法的電子署名ではない。", "됩니다. 이 탭에서 그립니다. 업로드 없음. 법적 전자서명이 아닙니다.", "Được. Vẽ trong tab này, không tải lên. Không phải chữ ký điện tử pháp lý.", "Ya. Menggambar di tab ini. Tidak diunggah. Bukan e-sign legal.", "Sí. Se dibuja en esta pestaña. Nada se sube. No es una firma electrónica legal."),
            "q2": L("Is this a legally binding e-signature?", "这是有法律效力的电子签吗？", "這是有法律效力的電子簽嗎？", "法的な電子署名？", "법적 전자서명인가요?", "Đây có phải chữ ký điện tử có hiệu lực?", "Ini e-sign yang mengikat?", "¿Es una firma electrónica vinculante?"),
            "a2": L("No. You get a PNG of ink. Banks and governments usually want a qualified e-sign or a wet signature.", "不是。你得到的是墨迹 PNG。银行和政府通常要合格电子签或手写原件。", "不是。你得到的是墨跡 PNG。銀行和政府通常要合格電子簽或手寫原件。", "違う。インクのPNG。銀行や行政は適格電子署名か直筆が多い。", "아니요. 잉크 PNG입니다. 은행과 정부는 보통 적격 전자서명이나 원본을 원합니다.", "Không. Bạn được PNG nét mực. Ngân hàng và chính phủ thường cần chữ ký điện tử đủ điều kiện hoặc chữ ướt.", "Tidak. Anda mendapat PNG tinta. Bank dan pemerintah biasanya minta e-sign berkualitas atau basah.", "No. Obtiene un PNG de tinta. Bancos y administraciones suelen pedir e-sign cualificada o tinta."),
            "q3": L("Does it stamp a PDF?", "会盖到 PDF 上吗？", "會蓋到 PDF 上嗎？", "PDFに押せる？", "PDF에 찍히나요?", "Có đóng lên PDF không?", "Apakah cap di PDF?", "¿Sella un PDF?"),
            "a3": L("No. Download a PNG and paste it only where a form asks for an image.", "不会。下载 PNG，只有表单要贴图时才贴。", "不會。下載 PNG，只有表單要貼圖時才貼。", "しない。PNGを保存し、画像を貼れと言われた欄にだけ使う。", "아니요. PNG를 받아 서류가 그림을 붙이라고 할 때만 붙이세요.", "Không. Tải PNG, chỉ dán khi form hỏi ảnh.", "Tidak. Unduh PNG dan tempel hanya jika formulir minta gambar.", "No. Descargue un PNG y péguelo solo donde el formulario pide una imagen."),
            "q4": L("Is the drawing uploaded?", "会上传吗？", "會上傳嗎？", "アップロードされる？", "업로드되나요?", "Có tải lên không?", "Apakah diunggah?", "¿Se sube el dibujo?"),
            "a4": L("No. Closing the tab discards it.", "不会。关掉标签页就没了。", "不會。關掉分頁就沒了。", "しない。タブを閉じると消える。", "아니요. 탭을 닫으면 사라집니다.", "Không. Đóng tab là mất.", "Tidak. Tutup tab, hilang.", "No. Al cerrar la pestaña se pierde."),
            "q5": L("Why is the PNG cropped?", "为什么 PNG 被裁过？", "為什麼 PNG 被裁過？", "PNGが切れているのはなぜ？", "PNG가 잘린 이유는?", "Sao PNG bị cắt?", "Kenapa PNG terpotong?", "¿Por qué el PNG está recortado?"),
            "a5": L("Export keeps the ink and drops empty pad. The background is transparent so it sits on a form.", "导出只留墨迹，空白底板不要了。底透明，好贴进表单。", "匯出只留墨跡，空白底板不要了。底透明，好貼進表單。", "書き出しはインクだけ残し空のパッドを捨てる。透明なので欄に載る。", "보내면 잉크만 남기고 빈 패드를 버립니다. 배경이 투명해 서류에 올라갑니다.", "Xuất giữ nét, bỏ bảng trống. Nền trong để dán vào form.", "Ekspor menjaga tinta dan membuang pad kosong. Latar tembus agar duduk di formulir.", "Exportar conserva la tinta y tira la almohadilla vacía. El fondo transparente encaja en el formulario."),
        },
    ),
    "annotate-screenshot": lesson(
        {
            "name": L("How to annotate a screenshot", "怎么给截图做标注", "怎麼給截圖做標註", "スクリーンショットの注釈", "스크린샷 주석 다는 법", "Cách chú thích ảnh chụp màn hình", "Cara anotasi tangkapan layar", "Cómo anotar una captura de pantalla"),
            "blurb": L("Drop a screenshot, add a box, an arrow, or a label, download a PNG, then check it at the size you will send.", "拖入截图，加框、箭头或字，下载 PNG，再按要发的大小看一眼。", "拖入截圖，加框、箭頭或字，下載 PNG，再按要發的大小看一眼。", "スクショを入れ、枠・矢印・文字を付け、PNGを保存し、送る大きさで見る。", "스크린샷을 넣고 상자, 화살표 또는 글을 단 뒤 PNG를 받아 보낼 크기로 보세요.", "Thả ảnh chụp, thêm khung, mũi tên hoặc chữ, tải PNG, xem cỡ sẽ gửi.", "Letakkan tangkapan, tambah kotak, panah, atau label, unduh PNG, cek ukuran kirim.", "Suelte una captura, añada un recuadro, una flecha o un rótulo, descargue PNG y mírela al tamaño al que la enviará."),
            "title": L("How to annotate a screenshot", "怎么给截图做标注", "怎麼給截圖做標註", "スクリーンショットに注釈を付ける方法", "스크린샷에 주석 다는 법", "Cách chú thích ảnh chụp màn hình", "Cara anotasi tangkapan layar", "Cómo anotar una captura de pantalla"),
            "lead": L("A bug report, a how-to, or a chat needs a mark on the picture, not a paragraph. You will drop a screenshot, draw a box or an arrow, and check the PNG at the size of a message.", "报 bug、写步骤、发聊天，要的是图上的标记，不是一段话。拖入截图，画框或箭头，再按消息那么大看 PNG。", "報 bug、寫步驟、發聊天，要的是圖上的標記，不是一段話。拖入截圖，畫框或箭頭，再按訊息那麼大看 PNG。", "バグ報告、手順、チャットは絵の上の印であり段落ではない。スクショを入れ、枠か矢印を描き、メッセージの大きさでPNGを見る。", "버그 보고, 절차, 채팅은 문단이 아니라 그림 위 표시가 필요합니다. 스크린샷을 넣고 상자나 화살표를 그린 뒤 메시지 크기로 PNG를 보세요.", "Báo lỗi, hướng dẫn, chat cần dấu trên ảnh, không phải một đoạn. Thả ảnh chụp, vẽ khung hoặc mũi tên, xem PNG cỡ tin nhắn.", "Laporan bug, langkah, chat butuh tanda di gambar, bukan paragraf. Letakkan tangkapan, gambar kotak atau panah, cek PNG seukuran pesan.", "Un informe de error, un how-to o un chat necesitan una marca en la foto, no un párrafo. Suelte la captura, dibuje un recuadro o una flecha y mire el PNG al tamaño de un mensaje."),
            "result": L("A PNG with a box, an arrow, or a short label that still reads at chat size, plus the original unmarked file.", "一份带框、箭头或短字的 PNG，聊天那么大仍能认，没标的原图还在。", "一份帶框、箭頭或短字的 PNG，聊天那麼大仍能認，沒標的原圖還在。", "枠・矢印・短い文字のPNG。チャットの大きさで読める。無印の原版は残る。", "상자, 화살표 또는 짧은 글이 있는 PNG. 채팅 크기에서도 읽힘. 표시 없는 원본은 남습니다.", "PNG có khung, mũi tên hoặc chữ ngắn, đọc được cỡ chat, ảnh gốc chưa đánh còn.", "PNG dengan kotak, panah, atau label pendek yang masih kebaca seukuran chat, plus file asli tanpa tanda.", "Un PNG con recuadro, flecha o rótulo corto que aún se lee al tamaño de un chat, y el original sin marcas."),
            "note": L("Open screenshot when the capture is on disk or on the clipboard. Rect, arrow, or text. Export is PNG. The original stays. Nothing is uploaded.", "截图在磁盘或剪贴板上再打开标注。框、箭头或字。导出是 PNG。原图还在。不上传。", "截圖在磁碟或剪貼簿上再打開標註。框、箭頭或字。匯出是 PNG。原圖還在。不上傳。", "キャプチャが手元かクリップボードにあってから開く。枠・矢印・文字。書き出しはPNG。原版は残る。アップロードなし。", "캡처가 디스크나 클립보드에 있으면 주석을 여세요. 상자, 화살표 또는 글. 보낸 파일은 PNG. 원본은 남습니다. 업로드 없음.", "Có ảnh chụp trên đĩa hoặc clipboard thì mở chú thích. Khung, mũi tên hoặc chữ. Xuất PNG. Bản gốc còn. Không tải lên.", "Tangkapan di disk atau papan klip, baru buka anotasi. Kotak, panah, atau teks. Ekspor PNG. Asli tetap. Tidak diunggah.", "Abra captura con la imagen en el disco o el portapapeles. Recuadro, flecha o texto. La exportación es PNG. El original se queda. Nada se sube."),
            "s1t": L("Decide box, arrow, or a short label", "先定是框、箭头还是短字", "先定是框、箭頭還是短字", "枠、矢印、短い文字のどれか", "상자, 화살표, 짧은 글 정하기", "Quyết khung, mũi tên hay chữ ngắn", "Tentukan kotak, panah, atau label pendek", "Decida recuadro, flecha o un rótulo corto"),
            "s1b": L("A box around the broken control. An arrow at the button to tap. Two or three words, not a paragraph. Too many marks fight the screenshot.", "坏掉的控件套框。要点的按钮画箭头。两三个词，不要一段。标太多会抢截图。", "壞掉的控制項套框。要點的按鈕畫箭頭。兩三個詞，不要一段。標太多會搶截圖。", "壊れた操作は枠。押すボタンは矢印。2–3語。段落を書かない。印が多すぎるとスクショと喧嘩する。", "깨진 컨트롤은 상자. 눌러야 할 버튼은 화살표. 두세 단어, 문단 금지. 표시가 많으면 스크린샷과 싸웁니다.", "Điều khiển hỏng thì khung. Nút cần bấm thì mũi tên. Hai ba từ, đừng một đoạn. Đánh quá nhiều thì tranh ảnh.", "Kontrol rusak: kotak. Tombol yang diketuk: panah. Dua tiga kata, bukan paragraf. Terlalu banyak tanda bertarung dengan tangkapan.", "Un recuadro en el control roto. Una flecha en el botón a pulsar. Dos o tres palabras, no un párrafo. Demasiadas marcas pelean con la captura."),
            "s2t": L("Open screenshot on cv.cm", "打开 cv.cm 的截图标注", "打開 cv.cm 的截圖標註", "cv.cmのスクショ注釈を開く", "cv.cm 스크린샷 주석을 열기", "Mở chú thích ảnh chụp trên cv.cm", "Buka anotasi tangkapan di cv.cm", "Abra captura en cv.cm"),
            "s2b": L("Work stays in this tab.", "标注留在当前标签页。", "標註留在目前分頁。", "このタブで処理。", "이 탭에서 만듭니다.", "Làm trong tab này.", "Proses di tab ini.", "El trabajo queda en esta pestaña."),
            "s3t": L("Drop or paste the capture", "拖入或粘贴截图", "拖入或貼上截圖", "ドロップまたは貼り付け", "넣거나 붙여넣기", "Thả hoặc dán ảnh chụp", "Letakkan atau tempel tangkapan", "Suelte o pegue la captura"),
            "s3b": L("Paste from the clipboard if you just captured. If the preview is blank, the file is not an image this browser can decode.", "刚截的就从剪贴板贴。预览空白，就是这款浏览器解不了这张图。", "剛截的就從剪貼簿貼。預覽空白，就是這款瀏覽器解不了這張圖。", "撮ったばかりならクリップボードから貼る。プレビューが空ならこのブラウザは不可。", "방금 찍었으면 클립보드에서 붙이세요. 미리보기가 비면 이 브라우저가 못 엽니다.", "Mới chụp thì dán clipboard. Xem trước trống thì trình duyệt không đọc được.", "Baru capture: tempel dari papan klip. Pratinjau kosong: peramban ini gagal.", "Si acaba de capturar, péguela del portapapeles. Si la vista está en blanco, este navegador no decodifica esa imagen."),
            "s4t": L("Draw one or two marks", "画一两处标记", "畫一兩處標記", "印を1–2個描く", "표시를 한두 개 그리기", "Vẽ một hoặc hai dấu", "Gambar satu atau dua tanda", "Dibuje una o dos marcas"),
            "s4b": L("Rect around the area. Arrow at the tap. Text for a two-word label. Undo the last mark if it covers the thing you meant to show.", "框住那一块。箭头指要点的地方。两个词的标签用文字。挡住要给看的东西，就撤销上一笔。", "框住那一塊。箭頭指要點的地方。兩個詞的標籤用文字。擋住要給看的東西，就撤銷上一筆。", "範囲は枠。タップは矢印。2語のラベルは文字。見せたいものを隠したらUndo。", "영역은 상자. 탭은 화살표. 두 단어 라벨은 글. 보여 줄 것을 가리면 마지막 표시를 실행 취소하세요.", "Khung quanh vùng. Mũi tên chỗ bấm. Chữ cho nhãn hai từ. Che mất thứ cần chỉ thì hoàn tác.", "Kotak di area. Panah di ketukan. Teks untuk label dua kata. Menutupi yang ingin ditunjukkan: undo.", "Recuadro en la zona. Flecha en el toque. Texto para un rótulo de dos palabras. Si tapa lo que quería mostrar, deshaga."),
            "s5t": L("Download the PNG", "下载 PNG", "下載 PNG", "PNGを保存", "PNG 받기", "Tải PNG", "Unduh PNG", "Descargue el PNG"),
            "s5b": L("Keep the unmarked original. Export does not change the file on disk.", "没标的原图留下。导出不会改磁盘上的文件。", "沒標的原圖留下。匯出不會改磁碟上的檔。", "無印の原版は残す。書き出しはディスクのファイルを変えない。", "표시 없는 원본을 남기세요. 보내도 디스크의 파일은 바뀌지 않습니다.", "Giữ bản gốc chưa đánh. Xuất không sửa file trên đĩa.", "Simpan asli tanpa tanda. Ekspor tidak mengubah file di disk.", "Conserve el original sin marcas. Exportar no cambia el archivo del disco."),
            "s6t": L("Open it at chat or ticket size", "按聊天或工单那么大打开看", "按聊天或工單那麼大打開看", "チャットやチケットの大きさで開く", "채팅이나 티켓 크기로 열기", "Mở cỡ chat hoặc ticket", "Buka seukuran chat atau tiket", "Ábralo al tamaño de un chat o un ticket"),
            "s6b": L("If the arrow vanishes when small, draw it thicker and closer. If type smears, shorten the label. Do not send the unmarked original by mistake.", "缩小后箭头没了，就加粗、靠近一点。字糊了，就缩短标签。别误发没标的原图。", "縮小後箭頭沒了，就加粗、靠近一點。字糊了，就縮短標籤。別誤傳沒標的原圖。", "小さくして矢印が消えるなら太く近く。文字が潰れるなら短く。無印の原版を誤送しない。", "작아져서 화살표가 사라지면 더 굵고 가깝게. 글이 뭉개지면 라벨을 줄이세요. 표시 없는 원본을 잘못 보내지 마세요.", "Thu nhỏ mũi tên mất thì vẽ đậm hơn, gần hơn. Chữ nhòe thì rút nhãn. Đừng gửi nhầm bản gốc chưa đánh.", "Mengecil panah hilang: gambar lebih tebal dan dekat. Teks buram: persingkat label. Jangan kirim asli tanpa tanda.", "Si la flecha desaparece en pequeño, dibújela más gruesa y cerca. Si el texto se corre, acorte el rótulo. No envíe el original sin marcas por error."),
            "diagram1": L("Box the broken control. Arrow the tap. Two words, not a paragraph.", "坏掉的控件套框。要点的画箭头。两个词，不要一段。", "壞掉的控制項套框。要點的畫箭頭。兩個詞，不要一段。", "壊れた操作は枠。タップは矢印。2語。段落を書かない。", "깨진 컨트롤은 상자. 탭은 화살표. 두 단어. 문단 금지.", "Điều khiển hỏng thì khung. Chỗ bấm thì mũi tên. Hai từ, đừng một đoạn.", "Kontrol rusak: kotak. Ketukan: panah. Dua kata, bukan paragraf.", "Recuadre el control roto. Flecha en el toque. Dos palabras, no un párrafo."),
            "diagram2": L("Export is PNG. Keep the unmarked original. Check at chat size.", "导出是 PNG。没标的原图留下。按聊天那么大看。", "匯出是 PNG。沒標的原圖留下。按聊天那麼大看。", "書き出しはPNG。無印の原版は残す。チャットの大きさで見る。", "보낸 파일은 PNG. 표시 없는 원본을 남기세요. 채팅 크기로 보세요.", "Xuất PNG. Giữ bản gốc chưa đánh. Xem cỡ chat.", "Ekspor PNG. Simpan asli tanpa tanda. Cek seukuran chat.", "La exportación es PNG. Conserve el original sin marcas. Mírelo al tamaño de un chat."),
        },
        {
            "q1": L("Can I annotate a screenshot free online?", "可以免费在线给截图做标注吗？", "可以免費線上給截圖做標註嗎？", "スクショに無料で注釈できる？", "스크린샷에 무료로 주석을 달 수 있나요?", "Chú thích ảnh chụp miễn phí online được không?", "Bisa anotasi tangkapan gratis online?", "¿Puedo anotar una captura gratis en línea?"),
            "a1": L("Yes. cv.cm draws in this tab. Nothing is uploaded.", "可以。cv.cm 在当前标签页画，不上传。", "可以。cv.cm 在目前分頁畫，不上傳。", "できる。このタブで描く。アップロードなし。", "됩니다. 이 탭에서 그립니다. 업로드 없음.", "Được. Vẽ trong tab này, không tải lên.", "Ya. Menggambar di tab ini. Tidak diunggah.", "Sí. Se dibuja en esta pestaña. Nada se sube."),
            "q2": L("What marks can I add?", "能加哪些标记？", "能加哪些標記？", "どんな印？", "어떤 표시를 달 수 있나요?", "Thêm dấu nào được?", "Tanda apa yang bisa ditambah?", "¿Qué marcas puedo añadir?"),
            "a2": L("A rectangle, an arrow, or a short text label. Undo removes the last mark.", "矩形、箭头或短文字。撤销会去掉上一笔。", "矩形、箭頭或短文字。撤銷會去掉上一筆。", "枠、矢印、短い文字。Undoは最後の印を消す。", "사각형, 화살표 또는 짧은 글. 실행 취소는 마지막 표시를 지웁니다.", "Hình chữ nhật, mũi tên hoặc chữ ngắn. Hoàn tác bỏ dấu vừa rồi.", "Persegi, panah, atau label teks pendek. Undo menghapus tanda terakhir.", "Un rectángulo, una flecha o un rótulo corto. Deshacer quita la última marca."),
            "q3": L("Is the screenshot uploaded?", "会上传吗？", "會上傳嗎？", "アップロードされる？", "업로드되나요?", "Có tải lên không?", "Apakah diunggah?", "¿Se sube la captura?"),
            "a3": L("No. Closing the tab discards it.", "不会。关掉标签页就没了。", "不會。關掉分頁就沒了。", "しない。タブを閉じると消える。", "아니요. 탭을 닫으면 사라집니다.", "Không. Đóng tab là mất.", "Tidak. Tutup tab, hilang.", "No. Al cerrar la pestaña se pierde."),
            "q4": L("Does this change the original file?", "会改原文件吗？", "會改原檔嗎？", "元ファイルは変わる？", "원본이 바뀌나요?", "Có sửa file gốc không?", "Apakah file asli berubah?", "¿Cambia el archivo original?"),
            "a4": L("No. You download a new PNG. The capture on disk stays unmarked.", "不会。你下载的是新 PNG。磁盘上的截图还没标。", "不會。你下載的是新 PNG。磁碟上的截圖還沒標。", "しない。新しいPNGを保存。元のキャプチャは無印のまま。", "아니요. 새 PNG를 받습니다. 디스크의 캡처는 표시가 없습니다.", "Không. Bạn tải PNG mới. Ảnh trên đĩa chưa đánh.", "Tidak. Anda mengunduh PNG baru. Tangkapan di disk tetap tanpa tanda.", "No. Descarga un PNG nuevo. La captura del disco sigue sin marcas."),
            "q5": L("Can I paste from the clipboard?", "能从剪贴板粘贴吗？", "能從剪貼簿貼上嗎？", "クリップボードから貼れる？", "클립보드에서 붙일 수 있나요?", "Dán từ clipboard được không?", "Bisa tempel dari papan klip?", "¿Puedo pegar del portapapeles?"),
            "a5": L("Yes, if the capture is an image. Then mark and download PNG.", "可以，只要截图是图片。然后标注，下载 PNG。", "可以，只要截圖是圖片。然後標註，下載 PNG。", "画像なら可。印を付けてPNGを保存。", "이미지면 됩니다. 표시한 뒤 PNG를 받으세요.", "Được nếu ảnh chụp là hình. Rồi đánh dấu, tải PNG.", "Ya jika tangkapan adalah gambar. Lalu tandai dan unduh PNG.", "Sí, si la captura es una imagen. Luego marque y descargue PNG."),
        },
    ),
    "make-invoice": lesson(
        {
            "name": L("How to make an invoice PDF", "怎么做发票 PDF", "怎麼做發票 PDF", "請求書PDFの作り方", "인보이스 PDF 만드는 법", "Cách làm hóa đơn PDF", "Cara buat faktur PDF", "Cómo hacer una factura PDF"),
            "blurb": L("Fill from/to, add line items, check tax and total, download a PDF, then read the numbers once. Not a tax form.", "填买卖双方，加明细，核对税额和合计，下载 PDF，再把数字看一遍。这不是税务申报表。", "填買賣雙方，加明細，核對稅額和合計，下載 PDF，再把數字看一遍。這不是稅務申報表。", "差出人と宛先、明細、税と合計を見てPDFを保存し、数字をもう一度読む。税務申告書ではない。", "보내는 사람/받는 사람, 품목, 세금과 합계를 확인한 뒤 PDF를 받고 숫자를 한 번 더 읽으세요. 세금 신고서가 아닙니다.", "Điền bên bán/mua, thêm dòng, kiểm thuế và tổng, tải PDF, đọc lại số. Không phải tờ khai thuế.", "Isi dari/ke, tambah baris, cek pajak dan total, unduh PDF, baca angkanya sekali. Bukan formulir pajak.", "Rellene de/para, añada líneas, revise impuesto y total, descargue un PDF y lea los números una vez. No es un formulario fiscal."),
            "title": L("How to make an invoice PDF", "怎么做发票 PDF", "怎麼做發票 PDF", "請求書PDFの作り方", "인보이스 PDF 만드는 법", "Cách làm hóa đơn PDF", "Cara buat faktur PDF", "Cómo hacer una factura PDF"),
            "lead": L("A simple bill: who you are, who pays, what was sold, tax, due date. You will fill the fields in this tab, check the totals, and open the PDF. This is not a government tax form.", "一张简单账单：你是谁、谁付钱、卖了什么、税、到期日。在当前标签页填好，核对合计，打开 PDF。这不是政府税务表。", "一張簡單帳單：你是誰、誰付錢、賣了什麼、稅、到期日。在目前分頁填好，核對合計，打開 PDF。這不是政府稅務表。", "簡単な請求。自分、支払う人、売ったもの、税、期日。このタブで埋め、合計を見てPDFを開く。行政の税務用紙ではない。", "간단한 청구서입니다. 나, 지불하는 사람, 판 것, 세금, 만기. 이 탭에서 채우고 합계를 본 뒤 PDF를 여세요. 정부 세금 서식이 아닙니다.", "Một hóa đơn đơn giản: bạn là ai, ai trả, bán gì, thuế, hạn. Điền trong tab này, kiểm tổng, mở PDF. Không phải tờ khai thuế nhà nước.", "Tagihan sederhana: siapa Anda, siapa bayar, apa yang dijual, pajak, jatuh tempo. Isi di tab ini, cek total, buka PDF. Bukan formulir pajak pemerintah.", "Una factura simple: quién es usted, quién paga, qué se vendió, impuesto, vencimiento. Rellene aquí, revise los totales y abra el PDF. No es un formulario fiscal."),
            "result": L("A one-page PDF whose line amounts and tax match the fields you typed, opened once before you send it.", "一份一页 PDF：明细金额和税对得上你填的数字，发出去之前打开看过。", "一份一頁 PDF：明細金額和稅對得上你填的數字，寄出去之前打開看過。", "1ページのPDF。明細と税が入力と一致。送る前に一度開く。", "한 페이지 PDF. 품목 금액과 세금이 입력과 맞음. 보내기 전에 한 번 열기.", "PDF một trang: thành tiền và thuế khớp ô bạn điền, đã mở một lần trước khi gửi.", "PDF satu halaman: jumlah baris dan pajak cocok dengan isian, sudah dibuka sekali sebelum kirim.", "Un PDF de una página cuyos importes e impuesto coinciden con lo que tecleó, abierto una vez antes de enviarlo."),
            "note": L("Open invoice when you know the parties and the lines. Tax is a percent on the subtotal. Not a VAT return and not a legal e-invoice. Nothing is uploaded.", "买卖双方和明细清楚再打开发票。税是小计的百分比。不是增值税申报，也不是法定电子发票。不上传。", "買賣雙方和明細清楚再打開發票。稅是小計的百分比。不是加值稅申報，也不是法定電子發票。不上傳。", "相手と明細が分かってから開く。税は小計の%。VAT申告でも適格請求書でもない。アップロードなし。", "당사자와 품목이 정해지면 인보이스를 여세요. 세금은 소계의 퍼센트. VAT 신고서도 법적 전자세금계산서도 아닙니다. 업로드 없음.", "Biết hai bên và các dòng thì mở hóa đơn. Thuế là phần trăm trên tạm tính. Không phải tờ khai VAT, cũng không phải hóa đơn điện tử pháp lý. Không tải lên.", "Tahu pihak dan baris, baru buka faktur. Pajak adalah persen dari subtotal. Bukan SPT PPN, bukan e-faktur legal. Tidak diunggah.", "Abra factura cuando sepa las partes y las líneas. El impuesto es un porcentaje del subtotal. No es una declaración de IVA ni una factura electrónica legal. Nada se sube."),
            "s1t": L("Gather from, bill-to, and the lines", "先备齐卖方、买方和明细", "先備齊賣方、買方和明細", "差出人・宛先・明細を揃える", "보내는 사람, 받는 사람, 품목을 모으기", "Chuẩn bị bên bán, bên mua và các dòng", "Siapkan dari, tagih ke, dan baris", "Reúna de, facturar a y las líneas"),
            "s1b": L("A name and address on each side. One row per thing sold: description, quantity, unit price. Write the currency and the tax percent the contract uses.", "两边各有名称和地址。卖的每样东西一行：说明、数量、单价。合同用哪种货币、百分之几的税，写清楚。", "兩邊各有名稱和地址。賣的每樣東西一行：說明、數量、單價。合約用哪種貨幣、百分之幾的稅，寫清楚。", "双方に名前と住所。売ったもの1行：説明・数量・単価。契約の通貨と税率を書く。", "양쪽에 이름과 주소. 판 것마다 한 줄: 설명, 수량, 단가. 계약의 통화와 세율을 적으세요.", "Mỗi bên một tên và địa chỉ. Mỗi món một hàng: mô tả, số lượng, đơn giá. Ghi đúng tiền tệ và phần trăm thuế trong hợp đồng.", "Nama dan alamat di tiap sisi. Satu baris per barang: deskripsi, qty, harga. Tulis mata uang dan persen pajak sesuai kontrak.", "Nombre y dirección a cada lado. Una fila por lo vendido: descripción, cantidad, precio. Anote la moneda y el porcentaje de impuesto del contrato."),
            "s2t": L("Open invoice on cv.cm", "打开 cv.cm 的发票", "打開 cv.cm 的發票", "cv.cmの請求書を開く", "cv.cm 인보이스를 열기", "Mở hóa đơn trên cv.cm", "Buka faktur di cv.cm", "Abra factura en cv.cm"),
            "s2b": L("Work stays in this tab.", "填写留在当前标签页。", "填寫留在目前分頁。", "このタブで処理。", "이 탭에서 작성합니다.", "Điền trong tab này.", "Isi di tab ini.", "El trabajo queda en esta pestaña."),
            "s3t": L("Fill the parties, number, dates, and currency", "填双方、编号、日期和货币", "填雙方、編號、日期和貨幣", "相手・番号・日付・通貨を入れる", "당사자, 번호, 날짜, 통화 넣기", "Điền hai bên, số, ngày và tiền tệ", "Isi pihak, nomor, tanggal, dan mata uang", "Rellene las partes, el número, las fechas y la moneda"),
            "s3b": L("Due should be on or after the invoice date. Pick the currency the buyer will actually pay.", "到期日不要早于开票日。货币要选买方真正会付的那种。", "到期日不要早於開票日。貨幣要選買方真正會付的那種。", "期日は請求日以後。支払う通貨を選ぶ。", "만기는 발행일 이후여야 합니다. 구매자가 실제로 낼 통화를 고르세요.", "Hạn không trước ngày hóa đơn. Chọn đúng tiền bên mua sẽ trả.", "Jatuh tempo pada atau setelah tanggal faktur. Pilih mata uang yang benar-benar dibayar pembeli.", "El vencimiento no puede ser anterior a la fecha. Elija la moneda que el comprador va a pagar de verdad."),
            "s4t": L("Add each line: description, qty, price", "每一行写说明、数量、单价", "每一行寫說明、數量、單價", "各行に説明・数量・単価", "각 줄에 설명, 수량, 단가", "Mỗi dòng: mô tả, số lượng, đơn giá", "Tiap baris: deskripsi, qty, harga", "Añada cada línea: descripción, cantidad, precio"),
            "s4b": L("Amount is qty × price. Empty descriptions make a messy PDF. Add a line per item, not a paragraph in one row.", "金额是数量×单价。说明空着，PDF 会乱。一件一行，不要把一段话塞进一行。", "金額是數量×單價。說明空著，PDF 會亂。一件一行，不要把一段話塞進一行。", "金額は数量×単価。説明が空だとPDFが荒れる。1品1行。1行に段落を詰め込まない。", "금액은 수량×단가. 설명이 비면 PDF가 지저분해집니다. 품목마다 한 줄. 한 줄에 문단을 넣지 마세요.", "Thành tiền = số lượng × đơn giá. Để trống mô tả thì PDF rối. Mỗi món một hàng, đừng nhét một đoạn vào một hàng.", "Jumlah = qty × harga. Deskripsi kosong: PDF berantakan. Satu barang satu baris, jangan paragraf dalam satu baris.", "El importe es cantidad × precio. Sin descripción, el PDF queda sucio. Una línea por ítem, no un párrafo en una fila."),
            "s5t": L("Set tax percent and read the totals", "填税率，再看合计", "填稅率，再看合計", "税率を入れ合計を読む", "세율을 넣고 합계 읽기", "Đặt phần trăm thuế và đọc tổng", "Set persen pajak dan baca total", "Fije el porcentaje de impuesto y lea los totales"),
            "s5b": L("Tax is a percent of the subtotal. 0 if the sale is untaxed here. The preview total must match qty × price plus tax before you download.", "税是小计的百分比。这里不征税就填 0。下载前，预览合计必须等于数量×单价再加税。", "稅是小計的百分比。這裡不徵稅就填 0。下載前，預覽合計必須等於數量×單價再加稅。", "税は小計の%。課税しないなら0。保存前にプレビューの合計が数量×単価+税と一致すること。", "세금은 소계의 퍼센트. 여기서 비과세면 0. 받기 전에 미리보기 합계가 수량×단가+세금과 맞아야 합니다.", "Thuế là phần trăm tạm tính. Không thuế thì 0. Tổng xem trước phải khớp số lượng × đơn giá cộng thuế trước khi tải.", "Pajak adalah persen subtotal. 0 jika tidak kena pajak di sini. Total pratinjau harus cocok qty × harga plus pajak sebelum unduh.", "El impuesto es un porcentaje del subtotal. 0 si aquí no se grava. El total de la vista debe coincidir con cantidad × precio más impuesto antes de descargar."),
            "s6t": L("Download the PDF and open it", "下载 PDF 并打开", "下載 PDF 並打開", "PDFを保存して開く", "PDF를 받아 열기", "Tải PDF và mở", "Unduh PDF dan buka", "Descargue el PDF y ábralo"),
            "s6b": L("One page. Read from, bill-to, each line, tax, and total. If a number is wrong, fix the field and export again. This file is not a VAT filing.", "一页。看卖方、买方、每一行、税、合计。数字错了，改字段再导。这份文件不是增值税申报。", "一頁。看賣方、買方、每一行、稅、合計。數字錯了，改欄位再導。這份檔不是加值稅申報。", "1ページ。差出人・宛先・各行・税・合計を読む。数字が違うなら直して再書き出し。VAT申告ではない。", "한 페이지. 보내는 사람, 받는 사람, 각 줄, 세금, 합계를 읽으세요. 숫자가 틀리면 칸을 고친 뒤 다시 보내세요. VAT 신고가 아닙니다.", "Một trang. Đọc bên bán, bên mua, từng dòng, thuế, tổng. Sai số thì sửa ô rồi xuất lại. File này không phải tờ khai VAT.", "Satu halaman. Baca dari, tagih ke, tiap baris, pajak, total. Angka salah: perbaiki kolom, ekspor lagi. File ini bukan SPT PPN.", "Una página. Lea de, facturar a, cada línea, impuesto y total. Si un número falla, corrija el campo y exporte. Este archivo no es una declaración de IVA."),
            "diagram1": L("From, bill-to, and one line per item. Amount is qty × price.", "卖方、买方，每样东西一行。金额是数量×单价。", "賣方、買方，每樣東西一行。金額是數量×單價。", "差出人・宛先。1品1行。金額は数量×単価。", "보내는 사람, 받는 사람, 품목마다 한 줄. 금액은 수량×단가.", "Bên bán, bên mua, mỗi món một hàng. Thành tiền = số lượng × đơn giá.", "Dari, tagih ke, satu baris per barang. Jumlah = qty × harga.", "De, facturar a, y una línea por ítem. El importe es cantidad × precio."),
            "diagram2": L("Tax is a percent of the subtotal. Open the PDF. This is not a tax return.", "税是小计的百分比。打开 PDF。这不是税务申报。", "稅是小計的百分比。打開 PDF。這不是稅務申報。", "税は小計の%。PDFを開く。税務申告ではない。", "세금은 소계의 퍼센트. PDF를 여세요. 세금 신고서가 아닙니다.", "Thuế là phần trăm tạm tính. Mở PDF. Không phải tờ khai thuế.", "Pajak adalah persen subtotal. Buka PDF. Bukan SPT pajak.", "El impuesto es un porcentaje del subtotal. Abra el PDF. No es una declaración fiscal."),
        },
        {
            "q1": L("Can I make an invoice PDF free online?", "可以免费在线做发票 PDF 吗？", "可以免費線上做發票 PDF 嗎？", "請求書PDFを無料で作れる？", "인보이스 PDF를 무료로 만들 수 있나요?", "Làm hóa đơn PDF miễn phí online được không?", "Bisa buat faktur PDF gratis online?", "¿Puedo hacer una factura PDF gratis en línea?"),
            "a1": L("Yes. cv.cm draws in this tab and downloads a PDF. Nothing is uploaded.", "可以。cv.cm 在当前标签页画，下载 PDF。不上传。", "可以。cv.cm 在目前分頁畫，下載 PDF。不上傳。", "できる。このタブで描きPDFを保存。アップロードなし。", "됩니다. 이 탭에서 그리고 PDF를 받습니다. 업로드 없음.", "Được. Vẽ trong tab này, tải PDF. Không tải lên.", "Ya. Menggambar di tab ini dan mengunduh PDF. Tidak diunggah.", "Sí. Se dibuja en esta pestaña y descarga un PDF. Nada se sube."),
            "q2": L("Is this a tax form or a legal e-invoice?", "这是税务表或法定电子发票吗？", "這是稅務表或法定電子發票嗎？", "税務用紙や適格請求書？", "세금 서식이나 법적 전자세금계산서인가요?", "Đây có phải tờ khai thuế hoặc hóa đơn điện tử pháp lý?", "Ini formulir pajak atau e-faktur legal?", "¿Es un formulario fiscal o una factura electrónica legal?"),
            "a2": L("No. It is a simple one-page bill. It does not file VAT and it is not a qualified e-invoice.", "不是。这是一张简单的一页账单。不会申报增值税，也不是合格电子发票。", "不是。這是一張簡單的一頁帳單。不會申報加值稅，也不是合格電子發票。", "違う。1ページの簡単な請求。VAT申告でも適格請求書でもない。", "아니요. 간단한 한 페이지 청구서입니다. VAT를 신고하지 않고 적격 전자세금계산서도 아닙니다.", "Không. Đây là hóa đơn một trang. Không nộp VAT, không phải hóa đơn điện tử đủ điều kiện.", "Tidak. Ini tagihan satu halaman. Tidak menyetor PPN, bukan e-faktur berkualitas.", "No. Es una factura simple de una página. No presenta el IVA ni es una factura electrónica cualificada."),
            "q3": L("How is tax calculated?", "税怎么算？", "稅怎麼算？", "税の計算は？", "세금은 어떻게 계산하나요?", "Thuế tính thế nào?", "Pajak dihitung bagaimana?", "¿Cómo se calcula el impuesto?"),
            "a3": L("A percent of the subtotal (qty × price for every line). Use 0 if the sale is untaxed here.", "小计的百分比（每行数量×单价之和）。这里不征税就填 0。", "小計的百分比（每行數量×單價之和）。這裡不徵稅就填 0。", "小計（各行の数量×単価の合計）の%。課税しないなら0。", "소계(각 줄 수량×단가의 합)의 퍼센트. 여기서 비과세면 0.", "Phần trăm trên tạm tính (tổng số lượng × đơn giá). Không thuế thì 0.", "Persen dari subtotal (qty × harga tiap baris). 0 jika tidak kena pajak di sini.", "Un porcentaje del subtotal (cantidad × precio de cada línea). Use 0 si aquí no se grava."),
            "q4": L("Are the fields uploaded?", "会上传吗？", "會上傳嗎？", "アップロードされる？", "업로드되나요?", "Có tải lên không?", "Apakah diunggah?", "¿Se suben los campos?"),
            "a4": L("No. Closing the tab discards them.", "不会。关掉标签页就没了。", "不會。關掉分頁就沒了。", "しない。タブを閉じると消える。", "아니요. 탭을 닫으면 사라집니다.", "Không. Đóng tab là mất.", "Tidak. Tutup tab, hilang.", "No. Al cerrar la pestaña se pierden."),
            "q5": L("Which currencies can I use?", "能用哪些货币？", "能用哪些貨幣？", "通貨は？", "어떤 통화를 쓸 수 있나요?", "Dùng tiền tệ nào?", "Mata uang apa?", "¿Qué monedas puedo usar?"),
            "a5": L("USD, EUR, GBP, CNY, JPY, KRW, VND, and IDR. Pick the one the buyer will pay.", "USD、EUR、GBP、CNY、JPY、KRW、VND、IDR。选买方会付的那种。", "USD、EUR、GBP、CNY、JPY、KRW、VND、IDR。選買方會付的那種。", "USD / EUR / GBP / CNY / JPY / KRW / VND / IDR。支払う通貨を選ぶ。", "USD, EUR, GBP, CNY, JPY, KRW, VND, IDR. 구매자가 낼 것을 고르세요.", "USD, EUR, GBP, CNY, JPY, KRW, VND, IDR. Chọn loại bên mua trả.", "USD, EUR, GBP, CNY, JPY, KRW, VND, IDR. Pilih yang dibayar pembeli.", "USD, EUR, GBP, CNY, JPY, KRW, VND e IDR. Elija la que el comprador va a pagar."),
        },
    ),
    "make-password": lesson(
        {
            "name": L("How to generate a strong password", "怎么生成强密码", "怎麼生成強密碼", "強いパスワードの作り方", "강한 비밀번호 만드는 법", "Cách tạo mật khẩu mạnh", "Cara buat kata sandi kuat", "Cómo generar una contraseña fuerte"),
            "blurb": L("Set length and character types, copy once, paste into the account, then close the tab. Do not email it.", "设好长度和字符种类，复制一次，贴进账号，关掉标签页。不要发邮件。", "設好長度和字元種類，複製一次，貼進帳號，關掉分頁。不要寄信。", "長さと文字種を決め、一度コピーしてアカウントに貼り、タブを閉じる。メールしない。", "길이와 문자 종류를 정하고 한 번 복사해 계정에 붙인 뒤 탭을 닫으세요. 이메일로 보내지 마세요.", "Đặt độ dài và loại ký tự, copy một lần, dán vào tài khoản, đóng tab. Đừng gửi email.", "Set panjang dan jenis karakter, salin sekali, tempel ke akun, tutup tab. Jangan email.", "Fije longitud y tipos de carácter, copie una vez, péguela en la cuenta y cierre la pestaña. No la envíe por correo."),
            "title": L("How to generate a strong password", "怎么生成强密码", "怎麼生成強密碼", "強いパスワードの作り方", "강한 비밀번호 만드는 법", "Cách tạo mật khẩu mạnh", "Cara buat kata sandi kuat", "Cómo generar una contraseña fuerte"),
            "lead": L("A unique password for one account. You will set length and character types in this tab, copy once, and paste into the signup. Random bytes come from this device. Do not reuse it.", "一个账号一把独特的密码。在当前标签页设长度和字符种类，复制一次，贴进注册页。随机字节来自这台设备。不要复用。", "一個帳號一把獨特的密碼。在目前分頁設長度和字元種類，複製一次，貼進註冊頁。隨機位元組來自這台裝置。不要復用。", "1アカウントに1つのユニークなパスワード。このタブで長さと文字種を決め、一度コピーして登録に貼る。乱数はこの端末。使い回さない。", "계정마다 고유한 비밀번호. 이 탭에서 길이와 문자 종류를 정하고 한 번 복사해 가입란에 붙이세요. 난수는 이 기기에서 나옵니다. 재사용하지 마세요.", "Mỗi tài khoản một mật khẩu riêng. Đặt độ dài và loại ký tự trong tab này, copy một lần, dán vào đăng ký. Byte ngẫu nhiên từ máy này. Đừng dùng lại.", "Satu akun satu kata sandi unik. Set panjang dan jenis karakter di tab ini, salin sekali, tempel ke daftar. Byte acak dari perangkat ini. Jangan dipakai ulang.", "Una contraseña única por cuenta. Fije longitud y tipos aquí, copie una vez y péguela en el alta. Los bytes aleatorios salen de este dispositivo. No la reutilice."),
            "result": L("A random password you pasted into one account, that never left this tab except via copy, and that you will not email.", "一把随机密码，只贴进一个账号，除了复制没有离开过当前标签页，也不会发邮件。", "一把隨機密碼，只貼進一個帳號，除了複製沒有離開過目前分頁，也不會寄信。", "1アカウントに貼った乱数パスワード。コピー以外このタブから出ていない。メールしない。", "한 계정에 붙인 난수 비밀번호. 복사 외에 이 탭을 떠나지 않았고 이메일로 보내지 않습니다.", "Mật khẩu ngẫu nhiên đã dán vào một tài khoản, không rời tab trừ copy, sẽ không gửi email.", "Kata sandi acak yang ditempel ke satu akun, tidak keluar tab kecuali salin, tidak akan diemail.", "Una contraseña aleatoria pegada en una cuenta, que no salió de esta pestaña salvo al copiar, y que no enviará por correo."),
            "note": L("Open password when you are creating or resetting one account. Default length 16. Exclude similar drops 0 O I l 1. Nothing is uploaded.", "给一个账号创建或重置时再打开。默认长度 16。排除相似会去掉 0 O I l 1。不上传。", "給一個帳號建立或重設時再打開。預設長度 16。排除相似會去掉 0 O I l 1。不上傳。", "1アカウントを作る・リセットするとき開く。初期長さ16。類似除外は0 O I l 1を落とす。アップロードなし。", "한 계정을 만들거나 재설정할 때 여세요. 기본 길이 16. 비슷한 문자 제외는 0 O I l 1을 뺍니다. 업로드 없음.", "Tạo hoặc đặt lại một tài khoản thì mở. Dài mặc định 16. Loại giống nhau bỏ 0 O I l 1. Không tải lên.", "Buat atau reset satu akun, baru buka. Panjang default 16. Kecualikan mirip membuang 0 O I l 1. Tidak diunggah.", "Abra contraseña al crear o restablecer una cuenta. Longitud por defecto 16. Excluir similares quita 0 O I l 1. Nada se sube."),
            "s1t": L("Use a unique password for this account", "这个账号用一把独特的密码", "這個帳號用一把獨特的密碼", "このアカウント専用にする", "이 계정만의 비밀번호", "Dùng mật khẩu riêng cho tài khoản này", "Pakai kata sandi unik untuk akun ini", "Use una contraseña única para esta cuenta"),
            "s1b": L("Reusing a password is how one leak opens the rest. A password manager can store it. Do not recycle a phrase you already typed on another site.", "复用密码，一处泄漏就会打开别处。密码管理器可以存。不要把别的网站用过的句子再拿来。", "復用密碼，一處洩漏就會打開別處。密碼管理器可以存。不要把別的網站用過的句子再拿來。", "使い回すと1件の漏洩で他も開く。マネージャーに預けてよい。他サイトで打った句を使わない。", "재사용하면 한 유출이 나머지를 엽니다. 비밀번호 관리자에 저장해도 됩니다. 다른 사이트에서 친 문구를 다시 쓰지 마세요.", "Dùng lại thì một chỗ lộ sẽ mở chỗ khác. Trình quản lý mật khẩu có thể lưu. Đừng tái chế cụm đã gõ ở site khác.", "Dipakai ulang: satu bocor membuka yang lain. Pengelola kata sandi boleh menyimpan. Jangan daur ulang frasa yang sudah diketik di situs lain.", "Reutilizarla es cómo una filtración abre el resto. Un gestor puede guardarla. No recicle una frase que ya tecleó en otro sitio."),
            "s2t": L("Open password on cv.cm", "打开 cv.cm 的密码生成", "打開 cv.cm 的密碼產生", "cv.cmのパスワードを開く", "cv.cm 비밀번호를 열기", "Mở mật khẩu trên cv.cm", "Buka kata sandi di cv.cm", "Abra contraseña en cv.cm"),
            "s2b": L("Generation stays in this tab. Random bytes come from Web Crypto on this device.", "生成留在当前标签页。随机字节来自这台设备上的 Web Crypto。", "產生留在目前分頁。隨機位元組來自這台裝置上的 Web Crypto。", "このタブで生成。乱数はこの端末のWeb Crypto。", "이 탭에서 만듭니다. 난수는 이 기기의 Web Crypto입니다.", "Tạo trong tab này. Byte ngẫu nhiên từ Web Crypto trên máy này.", "Generate di tab ini. Byte acak dari Web Crypto di perangkat ini.", "La generación queda en esta pestaña. Los bytes aleatorios salen de Web Crypto en este dispositivo."),
            "s3t": L("Set length 16 or more", "长度设成 16 或更长", "長度設成 16 或更長", "長さを16以上にする", "길이를 16 이상으로", "Đặt dài 16 trở lên", "Set panjang 16 atau lebih", "Fije longitud 16 o más"),
            "s3b": L("Default is 16. Longer is stronger if the site allows it. Below 12 is for the sites that still cap length, not a goal.", "默认 16。站点允许就更长。不到 12 只给仍限制长度的站点，不是目标。", "預設 16。站點允許就更長。不到 12 只給仍限制長度的站點，不是目標。", "初期は16。サイトが許すなら長く。12未満は上限があるサイト用であり目標ではない。", "기본은 16. 사이트가 허용하면 더 길게. 12 미만은 길이 제한이 있는 사이트용이지 목표가 아닙니다.", "Mặc định 16. Dài hơn thì mạnh hơn nếu site cho. Dưới 12 chỉ cho site còn giới hạn, không phải mục tiêu.", "Default 16. Lebih panjang lebih kuat jika situs izinkan. Di bawah 12 hanya untuk situs yang masih membatasi, bukan tujuan.", "Por defecto 16. Más largo es más fuerte si el sitio lo permite. Menos de 12 es para sitios que aún topean, no un objetivo."),
            "s4t": L("Keep letters, digits, and symbols unless the site forbids them", "除非站点禁止，否则留着字母、数字和符号", "除非站點禁止，否則留著字母、數字和符號", "サイトが禁じない限り字母・数字・記号を残す", "사이트가 금지하지 않으면 글자, 숫자, 기호를 남기기", "Giữ chữ, số và ký hiệu trừ khi site cấm", "Simpan huruf, angka, dan simbol kecuali situs melarang", "Conserve letras, dígitos y símbolos salvo que el sitio los prohíba"),
            "s4b": L("Exclude similar drops 0, O, I, l, and 1 so you can read it. If a bank form rejects symbols, turn symbols off for that account only.", "排除相似会去掉 0、O、I、l、1，好认。银行表单不要符号，就只给这个账号关掉符号。", "排除相似會去掉 0、O、I、l、1，好認。銀行表單不要符號，就只給這個帳號關掉符號。", "類似除外は0 O I l 1を落として読みやすくする。銀行が記号不可ならそのアカウントだけ記号を切る。", "비슷한 문자 제외는 0, O, I, l, 1을 빼 읽기 쉽게 합니다. 은행 서류가 기호를 거부하면 그 계정만 기호를 끄세요.", "Loại giống nhau bỏ 0, O, I, l, 1 cho dễ đọc. Form ngân hàng từ chối ký hiệu thì chỉ tắt ký hiệu cho tài khoản đó.", "Kecualikan mirip membuang 0, O, I, l, 1 agar kebaca. Formulir bank menolak simbol: matikan simbol hanya untuk akun itu.", "Excluir similares quita 0, O, I, l y 1 para poder leerla. Si un banco rechaza símbolos, apáguelos solo en esa cuenta."),
            "s5t": L("Copy once and paste into the account", "复制一次，贴进账号", "複製一次，貼進帳號", "一度コピーしてアカウントに貼る", "한 번 복사해 계정에 붙이기", "Copy một lần và dán vào tài khoản", "Salin sekali dan tempel ke akun", "Copie una vez y péguela en la cuenta"),
            "s5b": L("Do not screenshot it. Do not put it in email or chat. A password manager is the place to store it after paste.", "不要截图。不要放进邮件或聊天。贴完之后，存进密码管理器。", "不要截圖。不要放進郵件或聊天。貼完之後，存進密碼管理器。", "スクショしない。メールやチャットに入れない。貼ったらマネージャーに預ける。", "스크린샷하지 마세요. 이메일이나 채팅에 넣지 마세요. 붙인 뒤 비밀번호 관리자에 저장하세요.", "Đừng chụp màn hình. Đừng bỏ vào email hay chat. Dán xong thì lưu trình quản lý mật khẩu.", "Jangan screenshot. Jangan taruh di email atau chat. Setelah tempel, simpan di pengelola kata sandi.", "No la capture. No la ponga en correo ni en el chat. Tras pegar, un gestor es el sitio para guardarla."),
            "s6t": L("Close the tab", "关掉标签页", "關掉分頁", "タブを閉じる", "탭을 닫기", "Đóng tab", "Tutup tab", "Cierre la pestaña"),
            "s6b": L("Closing discards the password from this page. If you did not store it, generate a new one — do not try to remember a random string.", "关掉后，这页上的密码就没了。没存下来，就再生成一把——不要去记随机字符串。", "關掉後，這頁上的密碼就沒了。沒存下來，就再產生一把——不要去記隨機字串。", "閉じるとこのページのパスワードは消える。保存していなければ作り直す。乱数を覚えようとしない。", "닫으면 이 페이지의 비밀번호는 사라집니다. 저장하지 않았다면 새로 만드세요. 난수 문자열을 외우려 하지 마세요.", "Đóng thì mật khẩu trên trang mất. Chưa lưu thì tạo mới — đừng cố nhớ chuỗi ngẫu nhiên.", "Tutup, kata sandi di halaman hilang. Belum disimpan: buat baru. Jangan hafalkan string acak.", "Al cerrar, la contraseña desaparece de esta página. Si no la guardó, genere otra: no intente memorizar una cadena aleatoria."),
            "diagram1": L("Length 16+. Letters, digits, symbols. Exclude 0 O I l 1 if you will type it.", "长度 16+。字母、数字、符号。要手打就排除 0 O I l 1。", "長度 16+。字母、數字、符號。要手打就排除 0 O I l 1。", "長さ16+。字母・数字・記号。手入力なら0 O I l 1を除外。", "길이 16+. 글자, 숫자, 기호. 직접 칠 거면 0 O I l 1을 빼세요.", "Dài 16+. Chữ, số, ký hiệu. Sẽ gõ tay thì loại 0 O I l 1.", "Panjang 16+. Huruf, angka, simbol. Akan diketik: kecualikan 0 O I l 1.", "Longitud 16+. Letras, dígitos, símbolos. Si la va a teclear, excluya 0 O I l 1."),
            "diagram2": L("Copy once. Paste into one account. Do not email it. Close the tab.", "复制一次。贴进一个账号。不要发邮件。关掉标签页。", "複製一次。貼進一個帳號。不要寄信。關掉分頁。", "一度コピー。1アカウントに貼る。メールしない。タブを閉じる。", "한 번 복사. 한 계정에 붙이기. 이메일 금지. 탭을 닫기.", "Copy một lần. Dán một tài khoản. Đừng email. Đóng tab.", "Salin sekali. Tempel satu akun. Jangan email. Tutup tab.", "Copie una vez. Péguela en una cuenta. No la envíe por correo. Cierre la pestaña."),
        },
        {
            "q1": L("Can I generate a strong password free online?", "可以免费在线生成强密码吗？", "可以免費線上生成強密碼嗎？", "強いパスワードを無料で作れる？", "강한 비밀번호를 무료로 만들 수 있나요?", "Tạo mật khẩu mạnh miễn phí online được không?", "Bisa buat kata sandi kuat gratis online?", "¿Puedo generar una contraseña fuerte gratis en línea?"),
            "a1": L("Yes. cv.cm uses Web Crypto in this tab. Nothing is uploaded.", "可以。cv.cm 在当前标签页用 Web Crypto，不上传。", "可以。cv.cm 在目前分頁用 Web Crypto，不上傳。", "できる。このタブのWeb Crypto。アップロードなし。", "됩니다. 이 탭의 Web Crypto를 씁니다. 업로드 없음.", "Được. cv.cm dùng Web Crypto trong tab này, không tải lên.", "Ya. cv.cm memakai Web Crypto di tab ini. Tidak diunggah.", "Sí. cv.cm usa Web Crypto en esta pestaña. Nada se sube."),
            "q2": L("How long should a password be?", "密码要多长？", "密碼要多長？", "長さは？", "길이는?", "Dài bao nhiêu?", "Panjang berapa?", "¿De qué longitud?"),
            "a2": L("16 or more if the site allows it. Default here is 16. Below 12 is only for sites that still cap length.", "站点允许就 16 或更长。这里默认 16。不到 12 只给仍限制长度的站点。", "站點允許就 16 或更長。這裡預設 16。不到 12 只給仍限制長度的站點。", "サイトが許すなら16以上。ここは初期16。12未満は上限があるサイト用。", "사이트가 허용하면 16 이상. 여기 기본은 16. 12 미만은 길이 제한이 있는 사이트용.", "Site cho thì 16 trở lên. Ở đây mặc định 16. Dưới 12 chỉ cho site còn giới hạn.", "16 atau lebih jika situs izinkan. Default di sini 16. Di bawah 12 hanya untuk situs yang masih membatasi.", "16 o más si el sitio lo permite. Aquí el default es 16. Menos de 12 solo si el sitio aún topea."),
            "q3": L("What does exclude similar do?", "排除相似是做什么？", "排除相似是做什麼？", "類似除外は？", "비슷한 문자 제외는?", "Loại giống nhau làm gì?", "Kecualikan mirip untuk apa?", "¿Qué hace excluir similares?"),
            "a3": L("It drops 0, O, I, l, and 1 so the string is easier to read if you must type it.", "会去掉 0、O、I、l、1，免得手打时认错。", "會去掉 0、O、I、l、1，免得手打時認錯。", "0 O I l 1を落とし、手入力で読みやすくする。", "0, O, I, l, 1을 빼 직접 칠 때 읽기 쉽게 합니다.", "Bỏ 0, O, I, l, 1 để dễ đọc khi phải gõ.", "Membuang 0, O, I, l, 1 agar kebaca jika harus diketik.", "Quita 0, O, I, l y 1 para que se lea si tiene que teclearla."),
            "q4": L("Is the password uploaded?", "密码会上传吗？", "密碼會上傳嗎？", "アップロードされる？", "업로드되나요?", "Có bị tải lên không?", "Apakah diunggah?", "¿Se sube la contraseña?"),
            "a4": L("No. Closing the tab discards it.", "不会。关掉标签页就没了。", "不會。關掉分頁就沒了。", "しない。タブを閉じると消える。", "아니요. 탭을 닫으면 사라집니다.", "Không. Đóng tab là mất.", "Tidak. Tutup tab, hilang.", "No. Al cerrar la pestaña se pierde."),
            "q5": L("Should I email the password to myself?", "要把密码发到自己邮箱吗？", "要把密碼寄到自己信箱嗎？", "自分にメールしてよい？", "비밀번호를 내 메일로 보내도 되나요?", "Có nên email mật khẩu cho mình không?", "Boleh email kata sandi ke diri sendiri?", "¿Debo enviármela por correo?"),
            "a5": L("No. Paste into the account, store it in a password manager, close the tab.", "不要。贴进账号，存进密码管理器，关掉标签页。", "不要。貼進帳號，存進密碼管理器，關掉分頁。", "しない。アカウントに貼り、マネージャーに預け、タブを閉じる。", "아니요. 계정에 붙이고 비밀번호 관리자에 저장한 뒤 탭을 닫으세요.", "Không. Dán vào tài khoản, lưu trình quản lý, đóng tab.", "Tidak. Tempel ke akun, simpan di pengelola, tutup tab.", "No. Péguela en la cuenta, guárdela en un gestor y cierre la pestaña."),
        },
    ),
}

META = {
    "titleMakeSignature": L("How to draw a signature PNG | cv.cm", "怎么手写签名 PNG | cv.cm", "怎麼手寫簽名 PNG | cv.cm", "署名PNGの描き方 | cv.cm", "서명 PNG 그리는 법 | cv.cm", "Cách vẽ chữ ký PNG | cv.cm", "Cara gambar tanda tangan PNG | cv.cm", "Cómo dibujar una firma PNG | cv.cm"),
    "descMakeSignature": L("Draw on the pad, download a PNG cropped to the ink with a clear background, then check it at form size. Not a legal e-sign. Nothing is uploaded.", "在板上写，下载按墨迹裁好、底透明的 PNG，再按表单那么大看。不是法律电子签。不上传。", "在板上寫，下載按墨跡裁好、底透明的 PNG，再按表單那麼大看。不是法律電子簽。不上傳。", "パッドに書き、インクに切り透明なPNGを保存し欄の大きさで見る。法的電子署名ではない。アップロードなし。", "패드에 쓰고 잉크에 맞춰 자른 투명 PNG를 받은 뒤 서류 크기로 보세요. 법적 전자서명 아님. 업로드 없음.", "Vẽ trên bảng, tải PNG cắt theo nét nền trong, xem cỡ form. Không phải chữ ký điện tử pháp lý. Không tải lên.", "Gambar di pad, unduh PNG terpotong ke tinta berlatar tembus, cek seukuran formulir. Bukan e-sign legal. Tidak diunggah.", "Dibuje, descargue un PNG recortado a la tinta con fondo transparente y mírelo al tamaño del formulario. No es e-sign legal. Nada se sube."),
    "titleAnnotateScreenshot": L("How to annotate a screenshot | cv.cm", "怎么给截图做标注 | cv.cm", "怎麼給截圖做標註 | cv.cm", "スクリーンショットに注釈を付ける方法 | cv.cm", "스크린샷에 주석 다는 법 | cv.cm", "Cách chú thích ảnh chụp màn hình | cv.cm", "Cara anotasi tangkapan layar | cv.cm", "Cómo anotar una captura de pantalla | cv.cm"),
    "descAnnotateScreenshot": L("Drop or paste a screenshot, add a box, an arrow, or a short label, download PNG, then check at chat size. The original stays unmarked. Nothing is uploaded.", "拖入或粘贴截图，加框、箭头或短字，下载 PNG，再按聊天那么大看。原图没标。不上传。", "拖入或貼上截圖，加框、箭頭或短字，下載 PNG，再按聊天那麼大看。原圖沒標。不上傳。", "スクショを入れ枠・矢印・短い文字、PNGを保存しチャットの大きさで見る。原版は無印。アップロードなし。", "스크린샷을 넣거나 붙이고 상자, 화살표 또는 짧은 글을 단 뒤 PNG를 받아 채팅 크기로 보세요. 원본은 표시 없음. 업로드 없음.", "Thả hoặc dán ảnh chụp, thêm khung, mũi tên hoặc chữ ngắn, tải PNG, xem cỡ chat. Bản gốc chưa đánh. Không tải lên.", "Letakkan atau tempel tangkapan, tambah kotak, panah, atau label pendek, unduh PNG, cek seukuran chat. Asli tanpa tanda. Tidak diunggah.", "Suelte o pegue una captura, añada recuadro, flecha o rótulo corto, descargue PNG y mírela al tamaño de un chat. El original sigue sin marcas. Nada se sube."),
    "titleMakeInvoice": L("How to make an invoice PDF | cv.cm", "怎么做发票 PDF | cv.cm", "怎麼做發票 PDF | cv.cm", "請求書PDFの作り方 | cv.cm", "인보이스 PDF 만드는 법 | cv.cm", "Cách làm hóa đơn PDF | cv.cm", "Cara buat faktur PDF | cv.cm", "Cómo hacer una factura PDF | cv.cm"),
    "descMakeInvoice": L("Fill from and bill-to, add line items, set tax as a percent of the subtotal, download a PDF, then read the numbers. Not a tax form. Nothing is uploaded.", "填买卖双方，加明细，税按小计百分比，下载 PDF，再把数字看一遍。不是税务申报表。不上传。", "填買賣雙方，加明細，稅按小計百分比，下載 PDF，再把數字看一遍。不是稅務申報表。不上傳。", "差出人と宛先、明細、税は小計の%、PDFを保存して数字を読む。税務申告ではない。アップロードなし。", "보내는 사람/받는 사람, 품목, 세금은 소계의 퍼센트, PDF를 받은 뒤 숫자를 읽으세요. 세금 신고서가 아닙니다. 업로드 없음.", "Điền bên bán/mua, thêm dòng, thuế phần trăm tạm tính, tải PDF, đọc số. Không phải tờ khai thuế. Không tải lên.", "Isi dari/ke, tambah baris, pajak persen subtotal, unduh PDF, baca angka. Bukan formulir pajak. Tidak diunggah.", "Rellene de y facturar a, añada líneas, impuesto como porcentaje del subtotal, descargue un PDF y lea los números. No es un formulario fiscal. Nada se sube."),
    "titleMakePassword": L("How to generate a strong password | cv.cm", "怎么生成强密码 | cv.cm", "怎麼生成強密碼 | cv.cm", "強いパスワードの作り方 | cv.cm", "강한 비밀번호 만드는 법 | cv.cm", "Cách tạo mật khẩu mạnh | cv.cm", "Cara buat kata sandi kuat | cv.cm", "Cómo generar una contraseña fuerte | cv.cm"),
    "descMakePassword": L("Set length 16+, keep letters digits and symbols, copy once into one account, store it in a manager, close the tab. Random bytes stay on this device. Nothing is uploaded.", "长度 16+，留着字母数字符号，复制一次贴进一个账号，存进管理器，关掉标签页。随机字节留在这台设备。不上传。", "長度 16+，留著字母數字符號，複製一次貼進一個帳號，存進管理器，關掉分頁。隨機位元組留在這台裝置。不上傳。", "長さ16+、字母・数字・記号、一度コピーして1アカウントに貼り、マネージャーに預けタブを閉じる。乱数はこの端末。アップロードなし。", "길이 16+, 글자·숫자·기호를 남기고 한 번 복사해 한 계정에 붙인 뒤 관리자에 저장하고 탭을 닫으세요. 난수는 이 기기에 남습니다. 업로드 없음.", "Dài 16+, giữ chữ số ký hiệu, copy một lần vào một tài khoản, lưu trình quản lý, đóng tab. Byte ngẫu nhiên ở máy này. Không tải lên.", "Panjang 16+, huruf angka simbol, salin sekali ke satu akun, simpan di pengelola, tutup tab. Byte acak di perangkat ini. Tidak diunggah.", "Longitud 16+, letras dígitos y símbolos, copie una vez en una cuenta, guárdela en un gestor y cierre la pestaña. Los bytes aleatorios se quedan en este dispositivo. Nada se sube."),
}


def inject() -> None:
    for loc, path in FILES.items():
        data = json.loads(path.read_text())
        data["faq"].setdefault("learn", {})
        for lesson_id, payload in LESSONS.items():
            data["learn"][lesson_id] = payload["copy"][loc]
            data["faq"]["learn"][lesson_id] = payload["faq"][loc]
        for key, by_loc in META.items():
            data["meta"][key] = by_loc[loc]
        path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n")
        print("patched", path.name, list(LESSONS))


if __name__ == "__main__":
    inject()
